### ISSUE TITLE
Consumer getting no message after updating or using new Scheme registry

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [confluentinc/confluent-kafka-dotnet#1001]
Description
===========
I am much puzzled with schema registry concept. Therefore, asking this question. It is not an issue but i am not finding anyway to receive message on consumer. I have a producer and a consumer both are working well and receiving message in avro format. But i just make a change in my RecordSchema and now i am not getting the message in consumer. Is there anything need to do update the schema or how do i register new schema? I am using default schema currently.

How to reproduce
================

```
static async void KafkaProducer()
        {
            //if (args.Length != 3)
            //{
            //    Console.WriteLine("Usage: .. bootstrapServers schemaRegistryUrl topicName");
            //    return;
            //}

            string bootstrapServers = "localhost:9092";
            string schemaRegistryUrl = "Production163:8081"; 
            string topicName = "3drocket-player";
            string groupName = "avro-generic-example-group";

            /*var s = (RecordSchema)RecordSchema.Parse(
              @"{
                    ""namespace"": ""Confluent.Kafka.Examples.AvroSpecific"",
                    ""type"": ""record"",
                    ""name"": ""User"",
                    ""fields"": [
                        {""name"": ""name"", ""type"": ""string""},
                        {""name"": ""favorite_number"",  ""type"": [""int"", ""null""]},
                        {""name"": ""favorite_color"", ""type"": [""string"", ""null""]}
                    ]
                  }"
          );*/

            var s = (RecordSchema)RecordSchema.Parse(
                @"{
                    ""namespace"": ""Confluent.Kafka.Examples.AvroSpecific"",
                    ""type"": ""record"",
                    ""name"": ""User"",
                    ""fields"": [
                        {""name"": ""name"", ""type"": ""string""},
                        {""name"": ""favorite_number"",  ""type"": [""int"", ""null""]},
                        {""name"": ""color"", ""type"": [""string"", ""null""]}
                    ]
                  }"
            );

            using (var schemaRegistry = new CachedSchemaRegistryClient(new SchemaRegistryConfig { SchemaRegistryUrl = schemaRegistryUrl }))
            using (var producer =
                new ProducerBuilder<string, GenericRecord>(new ProducerConfig { BootstrapServers = bootstrapServers })
                    .SetKeySerializer(new AsyncAvroSerializer<string>(schemaRegistry))
                    .SetValueSerializer(new AsyncAvroSerializer<GenericRecord>(schemaRegistry))
                    .Build())
            {
                Console.WriteLine($"{producer.Name} producing on {topicName}. Enter user names, q to exit.");

                int i = 0;
                string text;
                while ((text = Console.ReadLine()) != "q")
                {
                    var record = new GenericRecord(s);
                    record.Add("name", text);
                    record.Add("favorite_number", i++);
                    record.Add("color", "blue");

                    producer.ProduceAsync(topicName, new Message<string, GenericRecord> { Key = text, Value = record })
                        .ContinueWith(task => task.IsFaulted
                            ? $"error producing message: {task.Exception.Message}"
                            : $"produced to: {task.Result.TopicPartitionOffset}");
                }
            }
            Console.ReadLine();
            //cts.Cancel();
        }
```

As you can see in above code, previously the schema was something like this:
`            var s = (RecordSchema)RecordSchema.Parse(
              @"{
                    ""namespace"": ""Confluent.Kafka.Examples.AvroSpecific"",
                    ""type"": ""record"",
                    ""name"": ""User"",
                    ""fields"": [
                        {""name"": ""name"", ""type"": ""string""},
                        {""name"": ""favorite_number"",  ""type"": [""int"", ""null""]},
                        {""name"": ""favorite_color"", ""type"": [""string"", ""null""]}
                    ]
                  }"
          );`
But now i have only change favourite_color to color but i am not getting any message in consumer. once i revert the change it start getting the message. What i am doing wrong? Is there any extra setting require to use new schema or updated schema?

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
if you change `favourite_color` to `color`, the new schema will not be `BACKWARD` compatible (the default compatibility setting in schema registry) because color doesn't have a `default` value (isn't optional). you'd therefore expect the producer to give an error when you try to produce the message with the new schema.

more info on schema compatibility: https://docs.confluent.io/current/schema-registry/avro.html#schema-evolution-and-compatibility

more info on schema registry: https://docs.confluent.io/current/schema-registry/index.html

note: IMO forward compatibility is generally more important than backward compatibility with kafka, as you generally care more about making sure old consumers can read messages from new producers.
