### ISSUE TITLE
Producer OnLog and OnError events has disappeared

### ISSUE THREAD

**Issue by robefernandez** [confluentinc/confluent-kafka-dotnet#1002]
Hello,
I've updated to the latest version (1.1.0). 
The producer **OnLog** event  and the consumer **OnError** events are not available anymore.

Do you know how can I subscribe to them? I'm more interested in the OnLog event that was so useful in some special cases.

Regards

**Comment by larsbrekken** [comment]
Check out the `SetLogHandler` and `SetErrorHandler` methods on the `ConsumerBuilder` and `ProducerBuilder` classes.

**Comment by robefernandez** [comment]
Thanks!
