### ISSUE TITLE
Local: Broker transport failure: (errno: No error)

### ISSUE THREAD

**Issue by bhartigwalani** [confluentinc/confluent-kafka-dotnet#1004]
Description
===========

Producer is failing occasionally with this message

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [0.11.6 ] Confluent.Kafka nuget version.
 - [ 0.10.1.0] Apache Kafka version.
 - [ ] Client configuration.
 - [windows ] Operating system.
 - [ INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: Broker changed state CONNECT -> APIVERSION_QUERY
INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: Connected (#6)
INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: Broker changed state APIVERSION_QUERY -> UP
INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: Connected to ipv4#52.166.130.125:9093
INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: Connecting to ipv4#52.166.130.125:9093 (ssl) with socket 6392
INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: Broker changed state DOWN -> CONNECT
INFO  -  [thrd:main]:   Topic changelogs partition 0 Leader 1
INFO  -  [thrd:main]:   Topic changelogs partition 1 Leader 1
INFO  -  [thrd:main]: ssl://dev-kafka-vm-2.:9093/2: 1/1 requested topic(s) seen in metadata
INFO  -  [thrd:main]:   Topic changelogs partition 2 Leader 2
INFO  -  [thrd:main]: Topic changelogs [0]: leader is down: re-query
INFO  -  [thrd:main]: Topic changelogs [1]: leader is down: re-query
INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: broker in state DOWN connecting
INFO  -  [thrd:main]:   Topic changelogs partition 1 Leader 1
INFO  -  [thrd:main]: ssl://dev-kafka-vm-2.:9093/2: 1/1 requested topic(s) seen in metadata
INFO  -  [thrd:main]:   Topic changelogs partition 2 Leader 2
INFO  -  [thrd:main]:   Topic changelogs partition 0 Leader 1
INFO  -  [thrd:main]: ssl://dev-kafka-vm-1.:9093/1: MetadataRequest failed: Local: Broker transport failure: actions Retry
INFO  -  [thrd:main]: ssl://dev-kafka-vm-1.:9093/1: MetadataRequest failed: Local: Broker transport failure: actions Retry
INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: Broker changed state UP -> DOWN
INFO  -  [thrd:ssl://dev-kafka-vm-1.:9093/bootstr]: ssl://dev-kafka-vm-1.:9093/1: failed: err: Local: Broker transport failure: (errno: No error)
ERROR - Failed to produce  message:ssl://dev-kafka-vm-1.:9093/1: Connection closed
INFO  -  [thrd:main]: ssl://dev-kafka-vm-2.:9093/2: 1/1 requested topic(s) seen in metadata
INFO  -  [thrd:main]:   Topic changelogs partition 0 Leader 1
INFO  -  [thrd:main]:   Topic changelogs partition 2 Leader 2
INFO  -  [thrd:main]:   Topic changelogs partition 1 Leader 1
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: Broker changed state CONNECT -> APIVERSION_QUERY
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: Broker changed state APIVERSION_QUERY -> UP
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: Connected (#5)
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: Connected to ipv4#52.166.135.99:9093
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: Connecting to ipv4#52.166.135.99:9093 (ssl) with socket 6676
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: Broker changed state DOWN -> CONNECT
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: broker in state DOWN connecting
INFO  -  [thrd:main]: ssl://dev-kafka-vm-2.:9093/2: MetadataRequest failed: Local: Broker transport failure: actions Retry
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: Starting fast leader query
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: ProduceRequest failed: Local: Broker transport failure: explicit actions Refresh
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: changelogs [2]: leader unavailable: produce: Local: Broker transport failure
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: changelogs [2]: MessageSet with 1 message(s) encountered error: Local: Broker transport failure (actions Refresh)
ERROR - Failed to produce  message: Local_Transport: Local: Broker transport failure
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: Broker changed state UP -> DOWN
ERROR - Failed to produce  message:ssl://dev-kafka-vm-2.:9093/2: Connection closed
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: failed: err: Local: Broker transport failure: (errno: No error)
INFO  -  [thrd:ssl://dev-kafka-vm-2.:9093/bootstr]: ssl://dev-kafka-vm-2.:9093/2: changelogs [2]: Produce MessageSet with 1 message(s) (837 bytes, ApiVersion 3, MsgVersion 2)
] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
those are just log messages reporting a recoverable error which the client will automatically recover from. what does the `Error` property on the delivery report tell you?
