### ISSUE TITLE
Getmessage: unexpected message SSL handshake failed error 1408EF04 client authentication might be required

### ISSUE THREAD

**Issue by MirzaAli-Baig** [confluentinc/confluent-kafka-dotnet#1006]
Description
===========

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by MirzaAli-Baig** [comment]
Confluent.Kafka nuget version.:1.1.0
  Apache Kafka version.  :
  Client configuration.

BootstrapServers = "",
                Debug = "security,broker,protocol", ApiVersionRequest=false, Acks= Acks.All,
                MessageSendMaxRetries =1,
                SecurityProtocol = SecurityProtocol.Ssl,
                SslCaLocation = @"truststore.cer.pem",
                 SslCertificateLocation = @"_client.crt",
                 SslKeyLocation = @"_client.key",
                // SslKeyPassword = "tytt",
                SslKeystorePassword = "tytt",

**Comment by MirzaAli-Baig** [comment]
Kafka version:1.0.2 version

**Comment by MirzaAli-Baig** [comment]
I have already referred this.

https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security

**Comment by iMajna** [comment]
> I have already referred this.
> 
> https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security

How did you fix it?
