### ISSUE TITLE
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by MirzaAli-Baig** [confluentinc/confluent-kafka-dotnet#1008]
Description
===========

I try to debug this code . It is throwing error 

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.' 
Happening at below line
                var errorCode = Librdkafka.producev(
                    handle,
                    topic,
                    partition,
                    (IntPtr)MsgFlags.MSG_F_COPY,
                    pValue, (UIntPtr)valLength,
                    pKey, (UIntPtr)keyLength,
                    timestamp,
                    headersPtr,
                    opaque);

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.
Ha

**Comment by MirzaAli-Baig** [comment]
Fault Module Name:	coreclr.dll

**Comment by mhowlett** [comment]
a scenario where this can happen if you are producing a message whilst simultaneously disposing the producer. we don't intend to fix this because it would incur performance penalty with produce. are you trying to do that? if not, please provide more information.
