### ISSUE TITLE
Travis CI failing with 'too many open files' on MacOS

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#101]
Occurs consistently but at seemingly random times whilst `dotnet restore` is executing.
Looks like this is actually a known issue: https://github.com/dotnet/cli/issues/809
This was working. Wondering if whether or not this issue occurs is dependent on time of day (i.e. load on server) - when I got it working, it was late on a Friday evening PST time.
Two things to try:
 - `ulimit` (though does this require root privileges, which we don't have?)
 - `dotnet restore --disable-parallel`

**Comment by lou1306** [comment]
In my case, specifying `--disable-parallel` was enough to work around the issue.
