### ISSUE TITLE
Write data when one broker goes down

### ISSUE THREAD

**Issue by igor-sh8** [confluentinc/confluent-kafka-dotnet#1011]
Hi. 
I have a cluster of two kafka brokers. On this cluster I created a topic with replication factor 1 and partitions count 4 (2 partitions per broker). 
The problem is that when one of the brokers goes down producer continues to write data to two brokers and in this case the half of the new data is not saved. 
I tried to use acks but it did not help. 
Is it possible to configure producer not to write data to the failed partitions (such partitions have leader -1 state) ?

**Comment by mhowlett** [comment]
I think you mean not write data to the non-failed partitions? no, I can't think how you would do that. You could do something approximating it in your own code (by utilizing either delivery report results or metadata requests you make yourself via the admin client), but it won't be perfect. Generally, you'd have your partitions replicated (in your setup, what happens is the broker failure is due to disk failure - you'd loose the data), in which case acks=all would achieve what you want.

**Comment by igor-sh8** [comment]
Hi. Thanks. 
I would like to create cluster of two or three brokers that are ideally independent of each other, but if I will need I can create topic with replication. If one of the brokers fails and I will lose all the data on that server - it is not a problem for me. But I want if for example one of such brokers goes down another two will work without any problems. And Ideally I do not want to use replication - because it creates high load on servers without the need in replication on my part. 
Is it possible to create similar schema ?

**Comment by mhowlett** [comment]
the client doesn't give you that specific functionality out of the box. Based on your description (it seems some message loss is fine), I'd create an abstraction above the producer which round-robins the produce calls to all partitions and in the event of a failed delivery, remembers that a partition failed and excludes it from the round-robining for some amount of time. After that time expires, if the broker is back up, all will be good. If it's not, then the partition gets excluded again. The specifics of the abstraction will depend on your exact requirements.

**Comment by igor-sh8** [comment]
Thanks for the information and advise. 
I think we will really work with our custom schema at the code level.
