### ISSUE TITLE
.NET Core + SASL GSSAPI/Kerberos support on Linux

### ISSUE THREAD

**Issue by lugospod** [confluentinc/confluent-kafka-dotnet#1014]
Description
===========
As far what I concluded that Confluent Kafka doesn't support SASL GSSAPI/Kreberos by default because the nuget (Librdkafka.redist) has shared object that were built without sasl gssapi support. Am I correct?

I tried to install librdkafka.devel directly on Centos, and that eliminated the SASL error but introduced a new one when I copied the librdkafka.so (from librdkafka.devel) the application directory: Unable to find an entry point named 'rd_kafka_message_status' in shared library 'librdkafka'.

Any advice on how to proceed on this error?
Do we have to build a new version of librdkafka for each OS when we need SASL GSSAPI?
Also, when we build new SO file, do we replace it only on runtime machine (library.load...) or is there another way?

Tnx

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.1.0 ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ Centos 7] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
> As far what I concluded that Confluent Kafka doesn't support SASL GSSAPI/Kreberos by default because the nuget (Librdkafka.redist) has shared object that were built without sasl gssapi support. Am I correct?

I can't recall off the top of my head, but I think that's probably the case for all the bundled librdkafka builds.

> I tried to install librdkafka.devel directly on Centos, and that eliminated the SASL error but introduced a new one when I copied the librdkafka.so (from librdkafka.devel) the application directory: Unable to find an entry point named 'rd_kafka_message_status' in shared library 'librdkafka'.

That's a relatively new method in librdkafka which suggests you're trying to use an old version of librdkafka.

> Do we have to build a new version of librdkafka for each OS when we need SASL GSSAPI?

Not necessarily - the build must just be compatible with the libsasl and libssl dependencies.

> Also, when we build new SO file, do we replace it only on runtime machine (library.load...) or is there another way?

`Library.Load` is the intended way. You could also overwrite the librdkafka builds in the .nuget packages directory. Thinking out loud here (I think this advice is good): if you include the custom build(s) of librdkafka as a resource so it's deployed with your application, and try to load them with `Library.Load`, it should make deployment acceptable across platforms. If the first librdkafka build isn't compatible with the current platform you're running on, it'll just fail (quickly) and you can try the next librdkafka build etc.

**Comment by lugospod** [comment]
> > As far what I concluded that Confluent Kafka doesn't support SASL GSSAPI/Kreberos by default because the nuget (Librdkafka.redist) has shared object that were built without sasl gssapi support. Am I correct?
> 
> I can't recall off the top of my head, but I think that's probably the case for all the bundled librdkafka builds.

OK Thank you.

> > I tried to install librdkafka.devel directly on Centos, and that eliminated the SASL error but introduced a new one when I copied the librdkafka.so (from librdkafka.devel) the application directory: Unable to find an entry point named 'rd_kafka_message_status' in shared library 'librdkafka'.
> 
> That's a relatively new method in librdkafka which suggests you're trying to use an old version of librdkafka.


![image](https://user-images.githubusercontent.com/29342608/61897567-9b87fd00-af17-11e9-8a49-abc26b0396b9.png)
As you can see in the image, I installed latest version 0.11.5 of librdkafka-devel package on CENTOS, so this doesn't look "old" to me. I grabbed the librdkafka.so from directory where package was installed. Did you mean some other part? The .net core application users the latest Confluence nuget . Do I have to change something in the .NET project if I replace SO file in the application directory?

> 
> > Do we have to build a new version of librdkafka for each OS when we need SASL GSSAPI?
> 
> Not necessarily - the build must just be compatible with the libsasl and libssl dependencies.
> 
> > Also, when we build new SO file, do we replace it only on runtime machine (library.load...) or is there another way?
> 
> `Library.Load` is the intended way. You could also overwrite the librdkafka builds in the .nuget packages directory. Thinking out loud here (I think this advice is good): if you include the custom build(s) of librdkafka as a resource so it's deployed with your application, and try to load them with `Library.Load`, it should make deployment acceptable across platforms. If the first librdkafka build isn't compatible with the current platform you're running on, it'll just fail (quickly) and you can try the next librdkafka build etc.

Ok. That is the last step... because currently I am trying to make it work on bare Linux because there are to many parameters that could go wrong so I am trying it without docker. After this succeeds, I will try to reproduce the same thing inside Alpine docker and then I could try and play with building librdkafka project ( I tried to create a build for CENTOS but the created build doesn't include ssl or SASL even though it says so in config.h - but I assume this is a problem I have to address on librdkafka github project).

ANd, thank you very much for you first quick response! I very appreciate it since we've already lost quite a lot of time trying to make this work :/

**Comment by mhowlett** [comment]
0.11.5 is very old - you should build librdkafka from source https://github.com/edenhill/librdkafka#build-from-source. Master branch will work fine in the present case, but in general you should check out the relevant tag (v1.1.0 here) and build that.

you just need to use `Library.Load` on your librdkafka build(s) as described above before using any other part of the Confluent library. You will definitley need a different build for alpine linux (it doesn't even use glibc, which is standard on other linux variants).

**Comment by lugospod** [comment]
OK, tnx for your help once again!
