### ISSUE TITLE
No such configuration property: "sasl.mechanism"

### ISSUE THREAD

**Issue by minakshikorad** [confluentinc/confluent-kafka-dotnet#1015]
Description
===========
I tried the sample dotnet example with the same configuration and it works fine.
Then I integrated it with my application and it fails as follows.

Exception when trying to initialize the kafka producer
No such configuration property: "sasl.mechanism"

How to reproduce
================
Add nuget package Confluent.Kafka 1.1.0

Config settings

            this.KafkaProducerConfig = new ProducerConfig
            {
                ApiVersionRequest = true,
                BootstrapServers = brokerList,
                SecurityProtocol = SecurityProtocol.SaslPlaintext,
                SaslMechanism = SaslMechanism.Plain,
                SaslUsername = "$ConnectionString",
                SaslPassword = connectionString,
                Debug = "security,broker,protocol"
            };

var producer = new ProducerBuilder<long, string>(config).SetKeySerializer(Serializers.Int64).SetValueSerializer(Serializers.Utf8).Build()
Exception while trying to intialize the producer as above 

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.1.0] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [.Net 4.5 ] Client configuration.
 - [ Windows] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
you are definitely on Windows? (not in docker?) it sounds like you're using a build of librdkafka that doesn't include SASL support, but on Windows I can't think how that would happen.

**Comment by minakshikorad** [comment]
yes on Windows.

**Comment by mhowlett** [comment]
what does `Library.VersionString` tell you?

**Comment by minakshikorad** [comment]
Version=1.1.0.0

**Comment by minakshikorad** [comment]
due to our custom package settings.. the required packages like System.Buffers, System.Numeric.Vectors etc. were not getting downloaded which was causing the issue. Fixed it by installing the Confluent.Kafka package from nuget.
