### ISSUE TITLE
After running for a period of time, an Unhandled Exception Event Args error may be reported in a few days or in a day.

### ISSUE THREAD

**Issue by yujiajunbmj** [confluentinc/confluent-kafka-dotnet#1016]
Description
===========
After running for a period of time, an Unhandled Exception Event Args error may be reported in a few days or in a day.
code:

_luggageKafkaConfigs = new Dictionary<string, object>
{
{ "group.id", "auto-video" },
{ "bootstrap.servers", kafkaServers },
{ "auto.offset.reset", "latest" }
};
Consumer<Ignore, string> _alarmConsumer = new Consumer<Ignore, string>(_alarmKafkaConfigs, null, new StringDeserializer(Encoding.UTF8));
_alarmConsumer.Subscribe(alarmTopic);
while (true)
{
Message<Ignore, string> msg;
if (_alarmConsumer.Consume(out msg, TimeSpan.FromSeconds(1))) 
{
//dispose
}
}

error:

在 Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_destroy(IntPtr rk)
在 Confluent.Kafka.Impl.SafeKafkaHandle.ReleaseHandle()
在 System.Runtime.InteropServices.SafeHandle.InternalFinalize()
在 System.Runtime.InteropServices.SafeHandle.Finalize()
How to reproduce

================
version 0.11.6.0

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
please upgrade to the latest version, I believe this issue is resolved.
