### ISSUE TITLE
SASL_PLAINTEXT with ScramSha256 disconnecting after upgrade to v1.1

### ISSUE THREAD

**Issue by vinodres** [confluentinc/confluent-kafka-dotnet#1018]
Description
===========
I am running into issues with SASL_PLAINTEXT authentication.
The error I am seeing in the logs is
`sasl_plaintext://mycorpmessagebroker:9092/bootstrap: Disconnected (after 8ms in state AUTH)`

Kafka broker is a 3 node cluster running on Linux. Consumer is running on Windows Server 2016. I am using .NET 4.7.2 with Confluent.Kafka v1.1 nuget library.

When I was using similar authentication setup with previous version of broker along with Confluent.Kafka 0.11.3 / librdkafka 0.11.0, it was workingexcept CPU issue (#285). Due to the CPU issue, I kept authentication disabled. Now I am revisiting it to enable authentication, but running into a new issue.

I have attached 2 log files after enabling debug with "fetch,protocol,broker,security".

Test with F5 between consumer and kafka broker
[SASL_LOG_WITH_F5.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/3439403/SASL_LOG_WITH_F5.txt)

Test **without** F5 between consumer and kafka broker
[SASL_LOG_NO_F5.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/3439404/SASL_LOG_NO_F5.txt)

In both cases, I am seeing following error and cannot figure what does it mean
```
 Send SASL frame to broker (53 bytes)
 bootstrap: failed: err: Local: Authentication failure: (errno: Invalid argument)
```

@edenhill Need some help from you in resolving/troubleshooting this issue. 

How to reproduce
================
Run the consumer client using following config
```
new ConsumerConfig
            {
                GroupId =  "Vinod_Test_Client.Group.1",
                ClientId = "Vinod_Test_Client.1",
                EnableAutoCommit = true,
                EnableAutoOffsetStore = false,
                BootstrapServers = "mycorpmessagebroker03:9092",
                SaslMechanism = SaslMechanism.ScramSha256,
                SecurityProtocol = SecurityProtocol.SaslPlaintext,
                SaslUsername = "TestUser",
                SaslPassword = "Test1234",
                AutoOffsetReset = AutoOffsetReset.Latest,
                Debug = "fetch,protocol,broker,security"
            };
```

Checklist
=========
Confluent.Kafka 1.1 Windows Server 2016 x64
There is F5 load balancer between Consumer and Kafka broker.
Kafka Broker v1.0.2 running on CentOS 7

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
That looks like an auth failure.
If possible, see if there's anything of interest in the broker logs.

**Comment by vinodres** [comment]
@edenhill , Found the issue. On the broker, ACLs were incorrect. Now it is working perfectly. Thank you.
