### ISSUE TITLE
Throwing an exception inside custom IDeserializer<T> stops the consumer

### ISSUE THREAD

**Issue by BineG** [confluentinc/confluent-kafka-dotnet#1020]
Description
===========
When an exception is thrown inside custom IDeserializer implementation, no further messages are received. This behaviour seems different in 1.1.0 than in the previous version we had where invalid received values seems to have been skipped. 

Even if I catch an exception how do I tell the consumer this message is not valid and should be skipped? With reference types I can check if it's null, but with int for example, the default value is 0 which is also a valid data received.

How to reproduce
================
Create a custom IDeserializer and have it throw an exception in it's Deserialize method.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ x] Confluent.Kafka nuget version. 1.1.0 
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system. Windows and Linux
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
All exceptions thrown in deserializers are caught and rethrown as a `ConsumeException` (to expose the source - key or value) and the original exception is set as the inner exception. To continue just handle the exception and keep consuming - consumption continue at the next message.

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Consumer.cs#L744

**Comment by BineG** [comment]
Oh I see. Obvious now that I think about it. 

Thank you
