### ISSUE TITLE
Can you query messages manually?  For example, I would like to inquire about 1,000 pieces of information that are not consumed.

### ISSUE THREAD

**Issue by klive** [confluentinc/confluent-kafka-dotnet#1021]
Description
===========

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
I'm not sure I understand the question, however you may be confused about what 'consumption' means - unlike traditional messaging systems, consuming a message does not cause the message to be removed from the broker.

**Comment by klive** [comment]
I'll think about it again.thanks
