### ISSUE TITLE
Memory leak in Produce, but not in ProduceAsync

### ISSUE THREAD

**Issue by mindcrash** [confluentinc/confluent-kafka-dotnet#1022]
Description
===========

While testing a service I discovered the following:

1. Produce(), which we use to rapidly send "fire-and-forget" messages eats up loads of unmanaged memory which makes the service rapidly hit a completely unwanted 1.3Gb in a few seconds (at which it also remains)

2. Replacing Produce with ProduceAsync() makes the service consume about 200 Mb memory which is fine given the use case.

It looks like Produce() is causing a memory leak under stress (e.g. confronted with a large number of big data structures to process in a short time).

How to reproduce
============

Write a large number of big data structures as fast as possible using Produce and ProduceAsync and note the memory consumption when using both

Checklist
=========

Please provide the following information:
 - [X] Confluent.Kafka nuget version: 1.1.0
 - [X] Apache Kafka version: 2.2.0
 - [X] Client configuration: .NET Core 2.2
 - [X] Operating system. Windows 10 client / Linux server
 - [X] Critical issue

**Comment by mhowlett** [comment]
I'm guessing you're just filing up the local message buffer in the case of `Produce` (i.e. producing message faster than the network/broker can accept them) but not `ProduceAsync` (which is less performant). You can tune this down using `queue.buffering.max.kbytes`.

**Comment by mindcrash** [comment]
Thanks Matt,

I'm on holiday at the moment but I will let a colleague look into it.
