### ISSUE TITLE
Kafka Consumer

### ISSUE THREAD

**Issue by binuedwin** [confluentinc/confluent-kafka-dotnet#1024]
Description
===========

Hi,

I am trying to kafka consumer to read from specific offset and multiple partitions and commit the values once read.

But, i did'nt find any api to send multiple partitions and offset. 

Thanks,

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
to assign to multiple partitions manually (specifying start offsets): https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/IConsumer.cs#L225

if you're using consumer groups, you can specify specific start offsets explicitly by returning a collection from the partitions assigned handler: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/ConsumerBuilder.cs#L236

you can commit offsets for multiple topics simultaneously using:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/IConsumer.cs#L339
