### ISSUE TITLE
Getting AccessViolaitonException

### ISSUE THREAD

**Issue by alexandery** [confluentinc/confluent-kafka-dotnet#1026]
Description
===========
I very often get an AccessViolationException from Consumer when raising a cancellation with a CancellationToken instance passed into ```.Consume()``` method:

```Consumer.Consume(cancellationToken);```

Checklist
=========

Please provide the following information:
 - [1.1.0 ] Confluent.Kafka nuget version.

**Comment by bartelink** [comment]
are you doing a `Close` on the consumer / can you share some more context? (I've personally seen similar, but in generally the cause is a missing `try .. finally consumer.Close()` wrapping)

**Comment by alexandery** [comment]
I'm seeing the exception when running in a debugger, so VS just breaks on the ```.Consume(cancellationToken)``` line and displays the exception pop-up. 

I see that internally Consumer is doing ```cancellationToken.ThrowIfCancellationRequested();``` and sometimes I get the related exception (OperationCanceledException), which I expect and process accordingly, but often I get the AccessViolationException, which can only be coming from ```ConsumeImpl()``` that interacts with librdkafka.

I'm running a test Net Core 2.2 console app, and that's where I see the behavior.

But yes, I do have ```.Close()``` and wrap the message consumption in a ```try...catch..finally```. So running outside of the debugger I'd be handling generic exception and moving on, but this is still concerning.

**Comment by mhowlett** [comment]
> I see that internally Consumer is doing cancellationToken.ThrowIfCancellationRequested();

we should change this since the experience when debugging is not good. it was purposefully written this way a long time ago to avoid an obscure bug, but I don't think this applies anymore (need to re-investigate).

there are known issue with access violation exceptions if you close / dispose the client then call other methods on it (as @bartelink notes). we don't plan to fix these because that would come with a performance penalty. without investigating in depth / more info, that seems most likely.

**Comment by alexandery** [comment]
@mhowlett I'm seeing access violation exceptions simply when Cancellation Token gets set/raised. And whatever is happening in ```ConsumeImpl()``` is causing that. I'm *not* doing anything else with the consumer. Just an FYI.

**Comment by mhowlett** [comment]
if you have some code demonstrating the problem, i'll take a look - the only known scenario where `ConsumeImpl()` will cause an access violation exception is if close or dispose has been called.

**Comment by AskMeAgain** [comment]
Its probl. to late, but if someone else is reading this: I think got this error when the consumer got disposed WHILE the Consume() happened. If you Dispose the consumer and then call consume, you get the normal ObjectDisposedException.
