### ISSUE TITLE
Authentication failure after calling SetLogHandler

### ISSUE THREAD

**Issue by tewarid** [confluentinc/confluent-kafka-dotnet#1028]
Description
===========

Using SASL_PLAINTEXT with SCRAM-SHA-512 auth, I'm seeing authentication failure with .NET core on Linux (Docker mcr.microsoft.com/dotnet/core/runtime:2.2-alpine base image) after SetLogHandler is called on producer builder to replace the log handler. Confluent.Kafka version is 1.1.0. Kafka version is 2.0.0.

How to reproduce
================

Everything works with

```c#
new ProducerBuilder<Null, string>(config)
    //.SetLogHandler((p, l) => { ... })
    .Build();
```

But, changing to this 

```c#
new ProducerBuilder<Null, string>(config)
    .SetLogHandler((p, l) => { ... })
    .Build();
```

Results in authentication failure

```log
[thrd:sasl_plaintext://kafka-server:39092/bootstrap]: sasl_plaintext://kafka-server:39092/bootstrap: SASL authentication failure: Disconnected: check client SCRAM-SHA-512 credentials and broker logs (after 961ms in state AUTH)
```

I'll gather and add additional details to the issue later.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
that's surprising. does your log handler block? (e.g. file io?). perhaps you're inadvertently adding a delay somewhere that matters, perhaps try doing blocking calls in another thread (perhaps `Task.Run(() => ...)` and see if that helps. also note that the log handler can be called spontaneously from a number of different threads, so the implementation must be thread safe.

**Comment by tewarid** [comment]
I tried Task.Run, an empty code block, calling SetLogHandler with a null value, all with the same result. The only thing that works so far is to not call SetLogHandler.

**Comment by tewarid** [comment]
Took a better look at the logs this morning. The following messages repeat each time I produce/send out data and an exception is raised because the queue is full

```
1/1 brokers are down
sasl_plaintext://kafka-server:39092/bootstrap: SASL authentication failure: Disconnected: check client SCRAM-SHA-512 credentials and broker logs (after 0ms in state AUTH)
Local: Queue full
1/1 brokers are down
sasl_plaintext://kafka-server:39092/bootstrap: SASL authentication failure: Disconnected: check client SCRAM-SHA-512 credentials and broker logs (after 0ms in state AUTH)
Local: Queue full
```

After waiting long enough, the broker is up, the problem goes away. Not setting the log handler was making me see just the `Local: Queue full` messages, and hence to wait long enough for the problem to go away.

Sorry for the bother.
