### ISSUE TITLE
[Question] Running Two Threads pointing to the same topic - "Revoked partitions: []" 

### ISSUE THREAD

**Issue by jeffreycruzana** [confluentinc/confluent-kafka-dotnet#103]
So I have two threads pointing on to the same topic and there is a message that says "Revoked partitions: []".
Is this something that I should adjust from our Kafka server to allow two threads to access the same partitions?

When I kill one of the threads it commences back on committing offsets.

**Comment by mhowlett** [comment]
It sounds like you are consuming? 

you shouldn't typically call the poll or consume method on the consumer from more than one thread (though you could). 

to parallelize, typically you would create more than one consumer (each of which reads from a mutually exclusive set of partitions) as part of a consumer group. this *could* be done in a single process on different threads, though typically you would do this in different processes.

if you need to parallelize work done on messages from a single partition, I'd read the messages on a single thread then immediately pass them off to thread pool threads for processing.

**Comment by jeffreycruzana** [comment]
Hi mate,
Yes, I am consuming. 

> to parallelize, typically you would create more than one consumer (each of which reads from a mutually exclusive set of partitions) as part of a consumer group. this could be done in a single process on different threads, though typically you would do this in different processes.

Are you saying that I should make my consumer exclusively read on a topic partition so for example, my topic is "TopicAwesome" and it has two partition. TopicAwesome[0] and TopicAwesome[1]. I should be able to make my consumer thread exclusive to any one of  them so for example, Consumer 1 is only for TopicAwesome[0] while Consumer 2 is only for TopicAwesome[1]?

> if you need to parallelize work done on messages from a single partition, I'd read the messages on a single thread then immediately pass them off to thread pool threads for processing.

This sounds great, I will explore on how can we do this safely and nicely.

**Comment by mhowlett** [comment]
Typically, one consumer may be reading from *many* partitions. as your application grows and you need more processing power, add consumers and each consumer will then read from less partitions (so will have less work to do). Start with a lot of partitions - the maximum number you ever expect to need. [you may be looking at the problem backwards]
