### ISSUE TITLE
Duplicate message processing with SetPartitionsAssignedHandler()

### ISSUE THREAD

**Issue by dorny** [confluentinc/confluent-kafka-dotnet#1030]
Description
===========
We are storing offsets in our DB to ensure exactly-once processing of data.
Storage of offsets and data from messages are in same transaction.
`SetPartitionsAssignedHandler` is used to retrieve the stored offsets from DB.
However the latest message is always duplicated when service is restarted.

Question
================
Should handler provided to `SetPartitionsAssignedHandler` return latest committed offset or offset of the first next message we want to receive?

**Comment by mhowlett** [comment]
you should specify the next message you want to receive (== committed offset if you were using kafka to track offsets)

**Comment by dorny** [comment]
"next message you want to receive" means offset of last received message + 1, right?

**Comment by mhowlett** [comment]
yes. the offset you return from the partitions assigned handler is expected to follow the same convention as what would be committed to kafka. see: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/IConsumer.cs#L357

**Comment by dorny** [comment]
Thanks for explanation. Works as expected :)
