### ISSUE TITLE
Consumer is hogging the CPU

### ISSUE THREAD

**Issue by structify** [confluentinc/confluent-kafka-dotnet#104]
I have 10 different consumers running in 10 different background processes all monitoring 10 different topics. 

Even if I simply instantiate the consumer and never call Subscribe or Poll, the CPU is pegged. If I don't instantiate the object, the CPU usage stays low.

**Comment by qed-** [comment]
See #87

**Comment by ewencp** [comment]
As @qed- said, see #87. This has been fixed in librdkafka and there's a workaround to get a patched version into your project in that issue, and an updated nuget package should hopefully be coming soon. Closing as duplicate, feel free to reopen if #87 does not resolve the problem for you.
