### ISSUE TITLE
Empty truststore: ssl.ca.location failed

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#1040]
In my application there is variable truststore that is combined from chosen source. Then I write all the certificates from selected source to .cer.pem file. And it works perfectly, except for one particular case, when the source does not have any trusted certificates and I just write empty .cer.pem file

But for some reason when SslCaLocation points to empty file Confluent throws exceptions.

What should I do to pass empty truststore in case I have no trusted certificates to pass in?

 - [ 1.0.0 ] Confluent.Kafka nuget version.

**Comment by edenhill** [comment]
SslCaLocation expects a proper certificate file.
If your truststore is empty, don't pass it to SslCaLocation.

**Comment by Never7Dice** [comment]
Ok, will do it like that. Thank you for the answer!

**Comment by saherahwal** [comment]
Do we need to pass the truststore location on Windows? shouldn't the client library figure it out
