### ISSUE TITLE
Is IProducer.ProduceAsync(...) thread safe?

### ISSUE THREAD

**Issue by ThomasHjorslevFcn** [confluentinc/confluent-kafka-dotnet#1041]
Description
===========

Is it safe to re-use an instance of `IProducer` to call `ProduceAsync()` from multiple threads?

My use case is an API method in an ASP.NET core application, in which I want to produce a message when the API is called.

How to reproduce
================

```csharp
[Route( "api/demo/producer" )]
[ApiController]
public class ProducerController : ControllerBase
{
    private readonly IProducer<int, string> _kafkaProducer;

    public ProducerController( IProducer<int, string> kafkaProducer )
    {
        _kafkaProducer = kafkaProducer;
    }

    [HttpPost( "produce" )]
    public async Task<string> Produce( [FromBody] int key, [FromBody] string value )
    {
        var message = new Message<int, string> { Key = key, Value = value };
        var result = await _kafkaProducer.ProduceAsync( "test-topic", message );
        return $"Delivered '{result.Key}','{result.Value}' to '{result.TopicPartitionOffset}'";
    }
}
```

where the producer instance is injected as a singleton by adding it as a singleton in `ConfigureServices()` like this:

```csharp
services.AddSingleton( new ProducerBuilder<int, string> ( config ).Build( ) );
```

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by ThomasHjorslevFcn** [comment]
Ok, thanks for the quick answer, may I suggest that this be specifically mentioned in `README.md` or in the examples?

**Comment by yinzara** [comment]
What about thread safety when using the transaction API? If I reuse an instance of IProducer and call "BeginTransaction()" on it, does that now mean if another thread uses that IProducer it will now be sharing the transaction of the first thread?

If that's the case, how am I supposed to manage a pool of IProducer(s) and keeping their transactional.id unique?

**Comment by mhowlett** [comment]
each librdkafka instance can only manage one transaction scope at a time (as indicated by the transactional.id). creating a dependent producer re-uses the same librdkafka instance. if you need concurrent transactions, you need to use different producer instances.

**Comment by yinzara** [comment]
wow ok 

Yeah that makes it extremely difficult when you have a multithreaded application with X number of simultaneous requests to each producer.  

You would basically have to keep a static pool of Producer Instances for each type of message you could produce that would be a fixed number and would have to be allocated at startup and "InitTransactions()" called on all potential pool instances.  Then you'd have to use an ObjectPool<> of some sort and a Scoped manager to distribute them.

Man it would be amazing if this was part of this library somehow. :-)

**Comment by mhowlett** [comment]
It's not available in any language - not the use case Kafka transactions were designed for. It's something i'd like to see as well, but not on the horizon.
