### ISSUE TITLE
Kafka Connect is loading the data from SQL server to Teradata; Very slow performance

### ISSUE THREAD

**Issue by sunilkpokkalla** [confluentinc/confluent-kafka-dotnet#1043]
Description
===========
We have 350 million records from source (SQL Server); We built a producer kafka connect application to push the data to kafka topic and another consumer application to consume to teradata with similar worker.properties.

**Connector.properies**
name=abcx
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=jdbc:sqlserver://xxx:port;database=xxxx;user=xxxx;selectMethod=cursor
connection.user=xx
connection.password=xx

query=select member_id,event_seq,column_name,modification_date,ISNULL(CONVERT(varchar(100),modified_by),'')  'modified_by',ISNULL(CONVERT(varchar(254),updated_value),'')  'updated_value',ISNULL(CONVERT(varchar(100),last_update_dbid),'')  'last_update_dbid',ISNULL(CONVERT(varchar(100),last_sync_seq),'')  'last_sync_seq',ISNULL(CONVERT(varchar(100),code_version),'')  'code_version' from hbo.tex

mode=bulk
auto.create=false
auto.evolve=false
auto.commit.enable=true
#mode=timestamp
#timestamp.column.name=modification_date
poll.interval.ms=846000000
#table.poll.interval.ms=36000
#timestamp.delay.interval.ms=36000
batch.max.rows=200000
topic.prefix=topic_test
---------------------------------------
**worker.properies**

rest.port=8083
bootstrap.servers=abc:port1, abec:p2 etc

key.converter=io.confluent.connect.avro.AvroConverter
value.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://schemaregistry_dev.sys.cigna.com:8081
value.converter.schema.registry.url=http://schemaregistry_dev.sys.cigna.com:8081
internal.key.converter=io.confluent.connect.avro.AvroConverter
internal.value.converter=io.confluent.connect.avro.AvroConverter
internal.key.converter.schema.registry.url=http://schemaregistry_dev.sys.cigna.com:8081
internal.value.converter.schema.registry.url=http://schemaregistry_dev.sys.cigna.com:8081
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.storage.file.filename=/tmp/abc.offsets
offset.flush.interval.ms=36000
offset.flush.timeout.ms=70000
#buffer.memory=10000
#offset.flush.interval.ms=36000
#offset.flush.timeout.ms=70000

# SSL properties 
security.protocol=SSL 
ssl.truststore.location=/opt/confluent/configs/dev/kafka.client.truststore.jks 
ssl.truststore.password=changeit

#Overriding Producer & Consumer Settings
producer.security.protocol=SSL
producer.ssl.truststore.location=/opt/confluent/configs/dev/kafka.client.truststore.jks
producer.ssl.truststore.password=changeit
producer.client.id=abcx
#consumer.metadata.max.age.ms=10000

#Overriding Producer settings to fix messages being retried
producer.acks=all
producer.retries=0
producer.max.block.ms=60000
producer.request.timeout.ms=30000
producer.max.in.flight.requests.per.connection=1

plugin.path=/opt/confluent/share/java
```
---------------------------------------------------------------
Its been 10 days; still its loading the data to teradata is consuming very slow


sink.properies

```properties
name=abc-teradatasink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1

connection.url=jdbc:teradata://xxx/LOGMECH=TD2,user=user_id,password=xxxxx,database=DB
table.name.format=target_table
connection.user=user_id
connection.password=xxxx

pk.mode=record_value
pk.fields= column1, date2

insert.mode=insert
batch.size=200000
auto.create=true
auto.evolve=false
max.retries=20

topics=topic_test
```

How to reproduce
================

Its been 10 days; still its loading the data to teradata is consuming very slow; we wanted to make it very fast; what is the approach for daily load and what is the approach for timestamp?

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by mhowlett** [comment]
this question isn't relevant to this client. It seems like the jdbc connector repo may be an appropriate place to ask this: https://github.com/confluentinc/kafka-connect-jdbc
