### ISSUE TITLE
AdminClient protocol parse error on DescribeConfig for Groups

### ISSUE THREAD

**Issue by CautiousMarmoset** [confluentinc/confluent-kafka-dotnet#1044]
Description
===========
We are using `AdminClient.DescribeConfigsAsync()` to get the config info for a Group.
Everything works fine for `Broker` and `Topic` resource types however when we attempt to get a `Group` I run into the following errors:

```
%3|1567721637.158|PROTOERR|***#producer-1| [thrd:main]: sasl_ssl://***.azure.com:31091/1: Protocol parse failure at 77/77 (rd_kafka_DescribeConfigsResponse_parse:2641) (incorrect broker.version.fallback?)

%3|1567721637.158|PROTOERR|***#producer-1| [thrd:main]: sasl_ssl://***.azure.com:31091/1: Broker returned ConfigResource 0,search that was not included in the original request
```

How to reproduce
================
```
let getGroupTest () =
    let configResource = Admin.ConfigResource(Name = "confluent", Type = Admin.ResourceType.Group)
    use client = Configuration.createAdminClientBuilder().Build()

    let result =
        client.DescribeConfigsAsync [ configResource ]
        |> Async.AwaitTask
        |> Async.RunSynchronously

    printfn "test result: %A" result
```

We get an exception with the above error and, interestingly, in the broker's logs we get:
```
[2019-09-05 22:44:55,936] ERROR [KafkaApi-1] Error when handling request: clientId=***, correlationId=4, api=DESCRIBE_CONFIGS, body={resources=[{resource_type=0,resource_name=confluent,config_names=null}],include_synonyms=true} (kafka.server.KafkaApis)
org.apache.kafka.common.errors.InvalidRequestException: Unexpected resource type UNKNOWN for resource confluent
```
It looks as though by the time the broker gets a hold of it the resource type has been set to 0, UNKNOWN.

This happens for all groups we try to get.
Is it possible that these things Im trying to get are not `Group` after all? They come back as results when I call `ListGroups()` so I assumed they were...

Checklist
=========
We are using Confluent.Kafka v. 1.1.0
We are using v 5.3.0 of the helm charts for Confluent Kafka Platform on a Kubernetes cluster.
Client is running on a Windows 10 machine.

**Comment by mhowlett** [comment]
only topic and broker resources are currently supported: https://kafka.apache.org/23/javadoc/org/apache/kafka/clients/admin/AdminClient.html#describeConfigs-java.util.Collection-org.apache.kafka.clients.admin.DescribeConfigsOptions-

**Comment by CautiousMarmoset** [comment]
I see. Thanks!
