### ISSUE TITLE
GenericRecord required to write against record schema but found Avro.Generic.GenericRecord

### ISSUE THREAD

**Issue by simon-gillespie-acrinax-com** [confluentinc/confluent-kafka-dotnet#1045]
Description
===========
I have a Producer Web App that accepts data from various sources and sends onto Kafka, I am using GenericRecord and ProduceAsync, I am getting the following ProduceException inner exception:

'GenericRecord required to write against record schema but found Avro.Generic.GenericRecord in field metadata'   

(the 'metadata' field is itself a record, I create a second GenericRecord, add info to it then add the GenericRecord onto the main GenericRecord)

This error sounds to me as though it thinks there are two different GenericRecord types and it is being provided with the wrong one...

How to reproduce
================
Issue is not intermittent, it occurs with each produce attempt.

Checklist
=========
  Dev env:
    Confluent.Apache.Avro v1.7.7.6
    Confluent.Kafka v1.1.0
    Confluent.Kafka.Avro v0.11.6
    Confluent.SchemaRegistry v1.1.0
    Confluent.SchemaRegistry.SerDes v1.10
    .Net Framework 4.5.2
    Visual Studio 2017 15.9.14
    Windows 10 dev machine.
  Deployed env:
    Windows Server 2012 R2, IIS version 8.5.9600

**Comment by martelskiy** [comment]
Can you add to the post your Kafka producer code?

**Comment by simon-gillespie-acrinax-com** [comment]
No, sorry, I had this issue a month ago and as I could see no way forward I have had to change the solution away from GenericRecord to standard classes, my solution now does not have the flexibility I originally intended by using GenericRecord but is nonetheless fit for purpose for the Customer.

**Comment by manudc** [comment]
Hi,

I also got the same error. "GenericRecord required to write against record schema but found System.String in field FUNDS".

problem is can't populate nested record type.
 record
        -field level1
        -record level1
                    -field level 2
                    -field level 2
       -field level1

Do you have sample code in C# using GenericRecord to write to kafka topic using ProduceAsync?

I got the exception in Confluent.SchemaRegistry.Serdes.GenericSerializerImpl class and method thrown exception is
new GenericWriter<GenericRecord>(writerSchema)
                        .Write(data, new BinaryEncoder(stream));
