### ISSUE TITLE
BootstrapServers is ignored

### ISSUE THREAD

**Issue by ahychu84** [confluentinc/confluent-kafka-dotnet#1050]
Description
===========
Just started looking at kafka and I've come upon a very strange issue, it seems to completely ignore the provided list of BootstrapServers. When the example below is run, it says it can't connect to localhost:9092. I've run the same program on the same server where Kafka is running and it works perfectly. I've looked a ton of examples and I believe my server formatting is correct. I'm using Confluent.Kafka 1.1.0 and just running the Confluent Platform 5.3.0 quick start.
The server that is running kafka is running CentOS 7 and my dev environment is currently Windows.

How to reproduce
================
```cs        
static async Task Main(string[] args)
{
    string brokerList = "10.0.0.119:9092";
    string topicName = "Test";
    var config = new ProducerConfig { BootstrapServers = brokerList };
    using (var producer = new ProducerBuilder<string, string>(config).Build())
    {
        var deliveryReport = await producer.ProduceAsync(topicName, new Message<string, 
         string> { Key = "test", Value = "test" });
    }
}
```

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [X] Client configuration.
 - [X] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [X] Critical issue.

**Comment by mhowlett** [comment]
this may be relevant: https://www.confluent.io/blog/kafka-listeners-explained 

if you set the `Debug` config property to `all` and provide logs, we can comment further.

**Comment by ahychu84** [comment]
That solved it. I'm amazed that this wasn't in any of the tutorials I found. Thank you for the quick response
