### ISSUE TITLE
ConsumerConfig

### ISSUE THREAD

**Issue by fancky2019** [confluentinc/confluent-kafka-dotnet#1058]
Description
===========
I can not find the config option ”max.poll.records” in class ConsumerConfig. 

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by bartelink** [comment]
In general https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md is the index of available settings from librdkafka so if it's not in there, it's not going to be in consumerconfig. Can you provide more detail as to what are you trying to accomplish?

**Comment by mhowlett** [comment]
in the .net client, messages are always delivered to the application one at a time. it might be worth noting that the `Consume` method does not directly correspond to broker FETCH requests - behind the scenes messages are fetched in batches from brokers for efficiency.

**Comment by fancky2019** [comment]
> in the .net client, messages are always delivered to the application one at a time. it might be worth noting that the `Consume` method does not directly correspond to broker FETCH requests - behind the scenes messages are fetched in batches from brokers for efficiency.
