### ISSUE TITLE
Consumption rate is very variable

### ISSUE THREAD

**Issue by scooper91** [confluentinc/confluent-kafka-dotnet#1059]
Description
===========
Confluent.Kafka version: 0.11.5
Kafka version: 1.1.1
Running on ECS Fargate (container based on microsoft/dotnet:2.1-sdk)

We're seeing very variable consumption rates when consuming messages.  Given there are plenty of messages in the topic still to be consumed, we are sometimes seeing ~300 messages a second being consumed, and other times, ~5 messages a second.

![image](https://user-images.githubusercontent.com/8831320/65325533-07e54c80-dba7-11e9-9d09-3a38b1335e7a.png)

The top graph shows the amount of messages still to be consumed by partition (there are 10 partitions).

The last graph in the image above shows the number of times `consumer.Consume` returns `false`.  When there are no messages, such as 23:45 on the graph, we are getting ~1.2k occurrences of `consumer.Consume` returning `false`.  When we are consuming at a good speed (e.g. 23:00 on the graph), we're getting ~600 occurrences of it returning `false`.  Interestingly, when consumption is being slow (e.g. 22:00), we are seeing more occurrences of `false` returned than when there is nothing left in the topic.  This suggests that it's not hitting the timeout when trying to consume a message.

Looking through the Confluent.Kafka library, we can see that `consumer.Consume` returns `false` when there is a consume error, when librdkafka fails to return a message or when we've reached the end of the partition.

We are not receiving any `OnConsumeError` events.  However, when message consumption is being slow, we are receiving lots of `OnPartitionEOF` events.  When consumption is fast, we're not seeing any of these messages.  As you can see in the top graph, all the partitions have data.

Our consumer code:
```
var consumer = new Confluent.Kafka.Consumer<string, string>(
    _kafkaConfig.Config, 
    new StringDeserializer(Encoding.UTF8), 
    new StringDeserializer(Encoding.UTF8));
    
consumer.Subscribe(topic);
consumer.OnPartitionsAssigned += OnPartitionsAssigned;
consumer.OnPartitionsRevoked += OnPartitionsRevoked;
consumer.OnError += OnError;
consumer.OnConsumeError += OnConsumeError;
consumer.OnPartitionEOF += OnPartitionEOF;

while (_isAlive)
{
    var consumedMessage = consumer.Consume(out var message,
        TimeSpan.FromMilliseconds(100));

    if (consumedMessage)
    {
        OnMessage(message);
    }
    else
    {
        _metrics.Increment("no_message_received", 1);
        Thread.Sleep(100);
    }
}
```

Our consumer config:
```
{ "group.id", configuration["appName"] },
{ "bootstrap.servers", configuration["kafkaHost"] },
{ "auto.offset.reset", "smallest" },
{ "enable.auto.commit", true },
{ "socket.receive.buffer.bytes", 1024*1024 } // added when trying to debug this issue - made no difference
```

How to reproduce
================
We are as yet unable to figure out how to reproduce this issue.  It can be quick for a couple of hours, and then slow for another couple of hours.

Thanks in advance!

**Comment by edenhill** [comment]
Why are you sleeping when there is no message? The timeout to consume already does that if there is no message.

**Comment by scooper91** [comment]
I'm not sure to be honest (I didn't write it).  I presume it was done to stop spamming Kafka when there is nothing left to consume, but I get your point about the kafka timeout! I don't think it should cause this issue though?

**Comment by edenhill** [comment]
There is no risk of spamming Kafka, the client already handles that internally in the background (see fetch.wait.max.ms).

With your current code, if the consumer consumes the last message in a topic/partition, calls Consume() again before a new message is available, it will call the thread sleep and block for 100ms.
If this happens frequently there will be 0.1s stalls, which will drastically reduce the throughput of the application.

**Comment by scooper91** [comment]
We can remove that timeout; however in this case, we're frequently getting no message consumed when (as you can see from the top graph), there are plenty of messages left to consume in all partitions.

**Comment by mhowlett** [comment]
there's some chance this is an issue with the client - you should upgrade to 0.11.6 at least, which is the most stable of the 0.11.x releases. We don't have the bandwidth to debug potential bugs with old versions unfortunately (unless you're a paying customer). If you upgrade to the latest release (v1.2), and experience similar issues, we'll look into it further.

**Comment by mhowlett** [comment]
issue relates to a very old version, probably not an underlying issue, closing.
