### ISSUE TITLE
consumer.Seek(...) throws KafkaException "Local: Errorneous state" when executed immediately

### ISSUE THREAD

**Issue by stefanloerwald** [confluentinc/confluent-kafka-dotnet#1061]
Description
===========

IConsumer.Seek(TopicPartitionOffset tpo) throws an exception, if immediately executed after IConsumer.Assign(TopicPartition). With a delay in between, it works. This should work immediately and suggest a non-completed task in Assign. I suggest creating async APIs where the state is sane when the API is awaited:

```csharp
await c.AssignAsync(topic);
await c.SeekAsync(topic_partition_offset);
```

Nuget package version: 1.2.0
Kafka version: 2.1.1cp1
OS: Windows (kafka + zookeeper in docker confluentinc/cp-....)

How to reproduce
================

```csharp
async Task Test()
{
   var config = new ConsumerConfig { BootstrapServers="localhost:1234", GroupId = "test",  };
   using (var c = new ConsumerBuilder<Ignore, string>(config).Build())
   {
      var tp = new TopicPartition("test-topic", new Partition(0));
      c.Assign(tp);
      //await Task.Delay(TimeSpan.FromSeconds(1)); // activate this to "fix" it / perform exponential backoff
      c.Seek(new TopicPartitionOffset(tp, 0)); // throws, if not delayed!
   }
}
```
Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [ X] Apache Kafka version.
 - [X ] Client configuration.
 - [ X] Operating system.
 - [N/A] Provide logs (with "debug" : "..." as necessary in configuration).
 - [N/A] Provide broker log excerpts.
 - [Well, you decide...] Critical issue.

**Comment by Mousavi310** [comment]
Similar to #827.

**Comment by nullptr1108** [comment]
I too am having this issue when trying to do an Assign() and then a Seek(). I have looked at #827 and it does not seem to address this issue. I have also tried to place the Seek() in the SetPartitionsAssignedHandler() method with the same Local: Erroneous state exception being thrown.

**Comment by Mousavi310** [comment]
Changing this:

     var tp = new TopicPartition("test-topic", new Partition(0));
     c.Assign(tp);

to this:

    consumer.Assign(new TopicPartitionOffset("test-topic", 0, 0));

has solved the problem for me. When you use `TopicPartition` to assign, the offset for assign is set to `Offset.Unset`. I don't know currently what is the effect of `Offset.Unset`, but now it works for me.

**Comment by nikoudel** [comment]
I was trying to seek to the beginning of all topics after restart (like told [here](https://jaceklaskowski.gitbooks.io/apache-kafka/kafka-properties.html)):
![image](https://user-images.githubusercontent.com/1636683/67228438-eeebe780-f441-11e9-9bd1-ec32bd6aba95.png)
and was getting the same error as in this issue, however, I suspect seeking is not the right wat to do it - the [consumer example](https://github.com/confluentinc/confluent-kafka-dotnet/blob/4d56f9cd8a1b1d94b30c967e959a0efd887d68a2/examples/Consumer/Program.cs#L63) suggests a different way:
```...
.SetPartitionsAssignedHandler((c, partitions) =>
{
	Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}]");
	// possibly manually specify start offsets or override the partition assignment provided by
	// the consumer group by returning a list of topic/partition/offsets to assign to, e.g.:
	// 
	// return partitions.Select(tp => new TopicPartitionOffset(tp, externalOffsets[tp]));

	// This will fail:
	//foreach (var p in partitions)
	//{
	//    c.Seek(new TopicPartitionOffset(p, Offset.Beginning));
	//}

	// This works:
	return partitions.Select(tp => new TopicPartitionOffset(tp, Offset.Beginning));
})
...```

**Comment by gelonggld** [comment]
i use this method,got same exception,not work.
```
      using (var c = new ConsumerBuilder<Ignore, byte[]>(conf)
                .SetPartitionsAssignedHandler((consumer,Partitions) => 
                { 
                    foreach(var p in Partitions)
                    {
                        consumer.Seek(new TopicPartitionOffset(p, Offset.End));
                    }
                })
                .Build()
                )
```

**Comment by edenhill** [comment]
Seek() may only be used on partitions that have been Assign()ed.
