### ISSUE TITLE
DllNotFoundException on Unity3D Mac Mojave

### ISSUE THREAD

**Issue by iaq3** [confluentinc/confluent-kafka-dotnet#1065]
Description
===========

How to reproduce
================
1. Download Kafka dotnet package
2. Build with visual studio community 2019
3. Drag Confluent.Kafka/bin/Release/net46/ contents into unity Assets folder
4. Try to construct a new ConsumerBuilder:
```
ConsumerConfig config = new ConsumerConfig
        {
            BootstrapServers = brokerList,
            GroupId = "csharp-consumer",
            EnableAutoCommit = false,
            StatisticsIntervalMs = 5000,
            SessionTimeoutMs = 6000,
            AutoOffsetReset = AutoOffsetReset.Earliest,
            EnablePartitionEof = true
        };
        const int commitPeriod = 5;
        using (var consumer = new ConsumerBuilder<Ignore, string>(config)
            // Note: All handlers are called on the main .Consume thread.
            .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
            .SetStatisticsHandler((_, json) => Console.WriteLine($"Statistics: {json}"))
            .SetPartitionsAssignedHandler((c, partitions) =>
            {
                Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}]");
                    // possibly manually specify start offsets or override the partition assignment provided by
                    // the consumer group by returning a list of topic/partition/offsets to assign to, e.g.:
                    // 
                    // return partitions.Select(tp => new TopicPartitionOffset(tp, externalOffsets[tp]));
                })
            .SetPartitionsRevokedHandler((c, partitions) =>
            {
                Console.WriteLine($"Revoking assignment: [{string.Join(", ", partitions)}]");
            })
            .Build())
        {
```

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x ] Confluent.Kafka nuget version. 1.1.0 & 1.2.0
 - [ x] Apache Kafka version. 1.1.0 & 1.2.0
 - [ ] Client configuration.
 - [x ] Operating system. Mac OS Mojave 10.14.6
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

Thank you for any help!

**Comment by Kamaropoulos** [comment]
For any one that comes up to this in the future, you also need the `librdkafka` library in order for Confluent.Kafka to run properly.
