### ISSUE TITLE
Exception when disposing consumer

### ISSUE THREAD

**Issue by roederja2** [confluentinc/confluent-kafka-dotnet#107]
I get the following exception when disposing the consumer "Local: Broker handle destroyed". I would not expect an exception to be thrown there. See https://msdn.microsoft.com/en-us/library/bb386039.aspx

Would still be interested in knowing what the exception means and why it happens.

**Comment by mhowlett** [comment]
Hi @roederja2 - thanks! It looks like this would happen if you call `Dispose` twice. Very good point - this is unexpected behavior and we should fix this. 

If you believe this is happening due to some other reason, it'd be great if you can post a code snippet demonstrating the problem.

**Comment by jbezak** [comment]
Hi. I encountered this problem when using [topshelf](http://topshelf-project.com/) to create a windows service with a consumer and disposing the consumer when stopping the service. The problem was that topshelf was disposing the consumer already.

**Comment by Moisessoares** [comment]
i have the same problem

**Comment by mhowlett** [comment]
`OnPartitionsAssigned` should only be called as a byproduct of the `Poll` or `Consume` method, and you shouldn't be doing that after `Dispose`ing the consumer (so i think the exception is desired).

I'd be v. interested to see a code sample that demonstrated the problem if you think I'm missing something here. 

It should be possible to call `Dispose` twice without an exception though, we need to fix that.

**Comment by mhowlett** [comment]
consolidating into #577
