### ISSUE TITLE
Kafka Confluent Consumer .net Console Setup

### ISSUE THREAD

**Issue by jake0029** [confluentinc/confluent-kafka-dotnet#1077]
Description
===========
Hello @mhowlett , @confluentgist 

Need of help about kafka client consumer setup, currently i have deployed 10 consumer consoles in Windows 2012 Server (not dedicated) and i will be having an incoming 20 consumer console deployment probably next month, the question is, do I have to build a dedicated server for this growing consumers? If yes, Is one dedicated server enough to cater multiple kafka consumer console? 

Hoping for your immediate response.

Thank you

**Comment by martelskiy** [comment]
Hi, @jake0029 . I think this question is not related to this repository. It's up to you to decide where you are going to run your consumers. Advice is just to start thinking about if your hardware can support such an amount of applications and if it's resilient to keep everything on one machine. But the question itself has no relation to neither Kafka nor dotnet implementations for Kafka

**Comment by Mousavi310** [comment]
I think you should monitor the `consumer lag` metric in the consumer for this purpose. If you have a noticeable lag in your consumer, then you can investigate the reason for the lag and if needed adding new resources.  librdkafka provides its metrics in configurable intervals. These metrics are described in [https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md](https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md). As an example you can set the config for 10 seconds by setting `StatisticsIntervalMs` config:

        var conf = new ConsumerConfig
        { 
            GroupId = Guid.NewGuid().ToString(),
            BootstrapServers = "localhost:9092",
            AutoOffsetReset = AutoOffsetReset.Earliest,
            StatisticsIntervalMs = 10000
        };

The statistics are provided as JSON. I use these simple classes to deserialize the JSON to find the lag:

        public class ConsumerStatistics
        {
            [JsonProperty(PropertyName="topics")]
            public Dictionary<string, TopicStatistic> Topics { get; set; }

            public ConsumerStatistics()
            {
                Topics = new Dictionary<string, TopicStatistic>();
            }
        }

        public class TopicStatistic
        {
            [JsonProperty(PropertyName="partitions")]
            public Dictionary<string, PartitionStatistic> Partitions { get; set; }

            public TopicStatistic()
            {
                Partitions = new Dictionary<string, PartitionStatistic>();
            }
        }

        public class PartitionStatistic
        {
            [JsonProperty(PropertyName="consumer_lag")]
            public long ConsumerLag { get; set; }
        }

And finally set the handler for handling JSON statistics:

        using (var c = new ConsumerBuilder<Ignore, string>(conf)
        .SetStatisticsHandler((d, statisticsJson) => 
        {
            var statistics = JsonConvert.DeserializeObject<ConsumerStatistics>(statisticsJson);
            foreach(var topic in statistics.Topics)
            {
                foreach(var partition in topic.Value.Partitions)
                {
                    logger.LogInformation($"Consumer lag for topic: [{topic.Key}], partition: [{partition.Key}], consumer group: [{conf.GroupId}] is {partition.Value.ConsumerLag}");
                }
            }
        })
        .Build())

An example of the log:

        Consumer lag for topic: [mytopic], partition: [0], consumer group: [e34d5806-bc33-4b30-bf48-64ab5beaa22d] is 932

If the consumer lag is increasing, you can find that your producers are faster than your consumers.
