### ISSUE TITLE
NET.Core 2.2 change log level for Kafka logs

### ISSUE THREAD

**Issue by martelskiy** [confluentinc/confluent-kafka-dotnet#1079]
Description
===========
Is there any way to disable logs which are coming from Kafka?

The log sample (consumer):
```
%5|1570698786.790|LIBSASL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/1001: GSSAPI client step 1

%5|1570698786.791|LIBSASL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/1001: GSSAPI client step 2

%5|1570699386.919|LIBSASL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/1001: GSSAPI client step 1

%5|1570699386.931|LIBSASL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/1001: GSSAPI client step 1

%5|1570699386.933|LIBSASL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/1001: GSSAPI client step 2
```
NuGet packages installed:

```
<PackageReference Include="Confluent.Kafka" Version="1.1.0" />
<PackageReference Include="Confluent.SchemaRegistry" Version="1.1.0" />
<PackageReference Include="Confluent.SchemaRegistry.Serdes" Version="1.1.0" />
```

"security.protocol" config is set to _sasl_plaintext_. I use Kerberos auth

Application framework: _NET.Core 2.2.401_.

It is possible to control all the logs from Microsoft libs by setting this:
```
"Logging": {
    "LogLevel": {
      "Microsoft": "#loglevel#",
    }
  }
```
Can I change the log level for logs that are coming from Kafka packages with more or less the same way?

**Comment by mhowlett** [comment]
if you set a log handler (in which you can do whatever you like) in the builder class, this will prevent the default behavior which is to log to stderr. 

to control which log messages your applications receives, you use the `debug` config property. librdkafka does have a log_level config setting, but in practice this isn't useful and we don't even expose it on the config classes.
