### ISSUE TITLE
GetEnum on double? in LingerMs getter

### ISSUE THREAD

**Issue by lorienpatt** [confluentinc/confluent-kafka-dotnet#1080]
I am trying to use the ProducerConfig and set my own LingerMs.  It is asking for a double?, so I enter a double, but then it fails with a System.ArgumentException - "Type provided must be an Enum.\nParameter name: enumType" (because it is using Enum.Parse in the GetEnum call of the LingerMs getter) and will not build my ProducerBuilder.
https://github.com/confluentinc/confluent-kafka-dotnet/blob/cf84fe8ead6be8be869cd1c4dd9fb38a430c4dea/src/Confluent.Kafka/Config_gen.cs#L946

**Comment by lorienpatt** [comment]
Created PR https://github.com/confluentinc/confluent-kafka-dotnet/pull/1083 for this issue

**Comment by mhowlett** [comment]
woah, that's a fairly bad oversight. for the moment, this can be circumvented with the `Set` method.

**Comment by lorienpatt** [comment]
@mhowlett I made a PR that fixes the issue #1083, if you want to take a look at it

**Comment by karlfs99** [comment]
Hi, when will this be available via nuget? How can I circumvent in the meantime? When I try config.LingerMs = 2000 or config.Set("linger.ms", "2000") it still is in exception state.
