### ISSUE TITLE
Question: Is there a plan for transactions for the producer?

### ISSUE THREAD

**Issue by longility** [confluentinc/confluent-kafka-dotnet#1091]
Is there a plan for a transactions for the producer?

Something like the following:

```java
producer.beginTransaction();
  for (ConsumerRecord record : records)
    producer.send(producerRecord(“outputTopic”, record));
  producer.sendOffsetsToTransaction(currentOffsets(consumer), group);  
  producer.commitTransaction();
```
Referenced from: https://www.confluent.io/blog/transactions-apache-kafka/

We are in need of this, and we are seeing if we should do a quick workaround or if we should wait. Unless someone can guide us on what that could look like, we might be able to contribute.

**Comment by mhowlett** [comment]
yes, we're targeting end of December and it should be available in preview form much sooner. don't hold us to that timeline though - it'll be out when we have confidence it is stable enough.

**Comment by longility** [comment]
@mhowlett that sounds awesome. Is there an item that we can keep track of or see progress?

**Comment by mhowlett** [comment]
watch the librdkafka PRs. it's not open yet.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/issues/1308

**Comment by noahdav** [comment]
@edenhill @mhowlett Can we offer any help to get this added sooner than end of year?  We have people who can work on this if together if needed.

**Comment by edenhill** [comment]
@noahdav The implementation is pretty much complete and we have full transactional functionality.
We're currently working on writing tests, there's a lot of intricate error cases that needs proper handling.

We really do appreciate your help; I believe the most valuable thing right now is testing, in particular to cover real world use-cases. So my suggestion would be for you to start using the new transactional API in your applications and report back any issues you may find.

The `txns` branch is not yet ready for wider use but it will be cleaned up this week and should be ready to go by next monday.

**Comment by noahdav** [comment]
@edenhill This is great news.  We can test this this at scale.  Please let me know when we can start using this branch.

**Comment by noahdav** [comment]
@edenhill Is this branch ready to be consumed for testing.  We would like to start testing this at scale.  Please let me know which branch we should start to use.

**Comment by noahdav** [comment]
@edenhill please let us know when we can start testing with this branch.

**Comment by smg-bg** [comment]
@edenhill I can help with testing as well

**Comment by edenhill** [comment]
Finalizing final error handling and test cases this week, will be ready for review and use by friday.

**Comment by mhowlett** [comment]
i've already integrated the current librdkafka txn branch with .net and have a working example, I hope to get that tidied up and a WIP PR pushed later today.

**Comment by mhowlett** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/pull/1147

**Comment by alexpirine** [comment]
Hello,

We're in dire need of EOS, and therefore we also need transactions to implement that.

Do you know if this is going to be released anytime soon now?

**Comment by mhowlett** [comment]
1.4.0-RC1 is on nuget, and includes transactions. It should be reliable. An EOS processing example is here: https://github.com/confluentinc/confluent-kafka-dotnet/tree/1.4.x/examples/Transactions

There will be an 1.4.0-RC2 today with changes unrelated to transactions. There will be an RC3 to reflect these changes: https://github.com/edenhill/librdkafka/pull/2728 and this will impact the API slightly, but shouldn't stop you from working with 1.4.0-RC1. 

We typically release following a successful 2 week soak test of the latest RC.
