### ISSUE TITLE
Question: Compression at producer

### ISSUE THREAD

**Issue by rlister302** [confluentinc/confluent-kafka-dotnet#1092]
Description
===========
We have certain messages that are above the default 1MB message size, so we want to compress the message before it goes to the server. However, I am unable to push the message to the bus due to the size. Is there something else that needs to be done during configuration of the producer other than setting the compression type and compression level?

Message in question was 1.88MB and I was using gzip at compression level 6.

Apache Kafka: 5.1.0
Confluent.Kafka: 1.2
Configuration: Default other than compression type/level
OS: Windows 10

How to reproduce
================
Try and send a large message with compression enabled at producer and message will be rejected.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
it sounds like the compressed size of the message is still > 1Mb. my understanding without digging deeper is the limit is applied to the total size of a message batch (and librdkafka will limit batch size according to conform to `message.max.bytes`) which is post compression. Increasing the max message size up to say 5Mb shouldn't be an issue I don't think. But IIRC, there's a big performance cliff around 25-30Mb.

**Comment by rlister302** [comment]
@mhowlett Let me play around with the message size some more then. I was browsing the librdkafka code and saw that the compression comes from the topic config. I recall from the previous version we used (11.6) that we had we specified "default.topic.config" in front of topic configuration properties, but I don't know if that is still supported with the strongly typed config object. I'm also making an assumption (it may be a bad one) that my message is getting below that threshold.

**Comment by mhowlett** [comment]
default.topic.config is depreciated, all corresponding config parameters are now specified at the top level. we may introduce optional per-topic config at a future time, but currently not exposed.

**Comment by rlister302** [comment]
Ok, good then. Thanks for the quick reply. I'll come back to this sometime over the weekend, but more than likely Monday. I'll either come back and elaborate or close the question.

**Comment by rlister302** [comment]
@mhowlett Do you know if the message size is checked pre-compression? I did a simple test with a byte array of 1MB with compression enabled since I would hopefully get at least one byte worth of compression. I was unable to push the message to the bus. However, once I increased the message.max.bytes on the client, I was able to push, and the bus did not reject it even though it is at the default message size of 1MB. If you are not sure, I can look around the code myself too.

**Comment by edenhill** [comment]
The `message.max.bytes` controls two things: the maximum allowed per-message size in produce(), and the maximum message batch size sent to the broker (but in this case it might be over-shot with at most one message).
There was a recent fix related to this:
https://github.com/edenhill/librdkafka/pull/2513/commits/b1b4d14a6fc01ac2345427af928a77aa96d180bd

**Comment by rlister302** [comment]
Thanks for adding some clarification. I think I have enough to move forward. I appreciate your time @mhowlett @edenhill
