### ISSUE TITLE
Producer silently fails when an exception was thrown in the produce() callback

### ISSUE THREAD

**Issue by fuyijun1989** [confluentinc/confluent-kafka-dotnet#1094]
Description
===========
When application code throws an exception from inside the [produce() callback](https://github.com/confluentinc/confluent-kafka-dotnet/blob/4d56f9cd8a1b1d94b30c967e959a0efd887d68a2/src/Confluent.Kafka/Producer.cs#L728), the producer will silently fail, the application won't print any log, the exception is also swallowed, but from now on no more messages deliver to Kafka.

We expect some change to this behavior, that either it prints the exception or throws it back to application code if it is possible. Silently fail is the worst we can expect.

How to reproduce
================
Throw an exception inside the produce() callback.

**Comment by mhowlett** [comment]
yes, we can do something better here. currently an exception in the callback will stop the poll loop.

**Comment by caj-johnson** [comment]
@mhowlett Any issues with implementing this as a ProducerException?

**Comment by mhowlett** [comment]
exceptions thrown in the produce callback are now exposed as error events to the registered error handler with type `ErrorCode.Local_Application`
