### ISSUE TITLE
Is Producer thread safe?

### ISSUE THREAD

**Issue by gelihu** [confluentinc/confluent-kafka-dotnet#1096]
Description
===========
Not an issue. I need some help.

1. Is Producer thread safe? 
1. If application is multi-threaded, which is a better pattern singleton or transient?

I feel bad for opening an issue for questions like this. Could you point me to forum where I can get answers for questions like this?

Thanks in advance.

How to reproduce
================
Not an issue

**Comment by mhowlett** [comment]
- the producer is thread safe.
- it's very expensive to create / pull down a client, so you want a singleton.

thanks for opening - helps us now what people don't understand. we need to improve the docs.

**Comment by gelihu** [comment]
Thank you for replying so quickly.
