### ISSUE TITLE
How to know, if the consumer is idle for x amount of time(using c#). I have a task I need to perform. If the consumer is idle for 2 minutes and then insert some data in DB.

### ISSUE THREAD

**Issue by rameshmaruthi80** [confluentinc/confluent-kafka-dotnet#1097]
Description
===========
How to know, if the consumer is idle for x amount of time(using c#). I have a task I need to perform. If the consumer is idle for 2 minutes and then insert some data in DB.

How to reproduce
================
Not a problem, just asking if we have seetings imilar tp python in c# like "consumer_timeout_ms = 5000"

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
    ConsumerConfig consumerConfig = new ConsumerConfig
            {
                GroupId = "Consumer23" + _kafkaOptions.GroupIdSuffix,
                ClientId = _kafkaOptions.ClientId,
                ApiVersionRequest = true,
                BootstrapServers = _kafkaOptions.Authenticated.Brokers,
                SecurityProtocol = SecurityProtocol.SaslSsl,
                AutoOffsetReset = AutoOffsetReset.Earliest,
                SaslKerberosServiceName = _kafkaOptions.Authenticated.KerberosServiceName
            };

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                consumerConfig.SaslMechanism = SaslMechanism.Gssapi;
                consumerConfig.SslCaLocation = _kafkaOptions.Authenticated.CaFilePath;
            }
            else
            {
                // Linux and MacOS
                consumerConfig.SaslKerberosKeytab = _kafkaOptions.Authenticated.KeyTabFilePath;
                consumerConfig.SaslKerberosPrincipal = _kafkaOptions.Authenticated.Principal;
            }

 - [ ] Confluent.Kafka nuget version.
         1.2.1

 - [ ] Apache Kafka version.
1.1.1

 - [ ] Client configuration. - 

provided in description 

 - [ ] Operating system. - Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).

provided in description 
 - [ ] Provide broker log excerpts.

provided in description 
 - [ ] Critical issue.

provided in description

**Comment by caj-johnson** [comment]
You could always provide a TimeSpan of 2 minutes to the .Consume() method call.  Then if the message is null, that should indicate that the consumer hasn't processed anything in the last 2 minutes.

**Comment by rameshmaruthi80** [comment]
Thanks for your reply @caj-johnson , but that sounds like polling right. It checks for the message every 2 minutes, right?

How different between this two:

consumer.Consume(TimeSpan.FromMinutes(2));
consumer.Consume(cancellationToken);

The second consume option will block and wait for messages to come in right?

**Comment by caj-johnson** [comment]
The second one you have to manually cancel it. 

What I'm suggesting is:

```
var msg = consumer.Consume(TimeSpan.FromMinutes(2));
if (msg == null)
{
  InsertDataIntoDB();
}
```

The only polling is the polling happening internal to the consumer.

**Comment by rameshmaruthi80** [comment]
Thanks @caj-johnson  !!
