### ISSUE TITLE
Connect to wrong brokers

### ISSUE THREAD

**Issue by danny8002** [confluentinc/confluent-kafka-dotnet#1104]
Description
===========
I just get a very strange error when run producer example to send data to **localhost:9092**.  from the log, i find that it try to connect to unknown servers. My workstation joins domain xxxxxxxx.com, here is the error message

`%3|1572492494.171|FAIL|rdkafka#producer-1| [thrd:cn-rezh-x1y.fareast.corp.xxxxxxxxx.com:9092/0]: cn-rezh-x1y.fareast.corp.xxxxxxxxx.com:9092/0: Connect to ipv4#100.64.29.89:9092 failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond... (after 21013ms in state CONNECT)`

in my company, I don't know who is cn-rezh-x1y.fareast.corp.xxxxxxxxx.com:9092, also I have nothing to with this IP. but Kafka client try to connect to this instead of localhost ..

this is my ipconfig

```

E:\>ipconfig

Windows IP Configuration

Ethernet adapter Ethernet 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : corp.xxxxxxxxx.com

Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 10.0.75.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : corp.xxxxxxxxx.com
   Link-local IPv6 Address . . . . . : fe80::fd48:28c5:6080:8b85%4
   IPv4 Address. . . . . . . . . . . : 10.172.205.88
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.172.205.1

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : 2001:0:2851:b9f0:2863:c32d:5823:16a7
   Link-local IPv6 Address . . . . . : fe80::2863:c32d:5823:16a7%11
   Default Gateway . . . . . . . . . : ::

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::ecb3:4566:b03e:ca9a%18
   IPv4 Address. . . . . . . . . . . : 192.168.153.65
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :

Ethernet adapter vEthernet (nat):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::49d7:5859:aebe:aefc%34
   IPv4 Address. . . . . . . . . . . : 172.27.160.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

Ethernet adapter vEthernet (435d6f11ff697d2):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::c9d1:91ba:85bf:fe31%44
   IPv4 Address. . . . . . . . . . . : 192.168.224.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

Ethernet adapter vEthernet (296e1daf89261c6):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::bc40:e967:a0dd:cfe1%48
   IPv4 Address. . . . . . . . . . . : 172.26.160.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

```

Checklist
=========
 - [1.2.1] Confluent.Kafka nuget version.
 - [kafka_2.12-2.2.0 ] Apache Kafka version.
 - [default] Client configuration.
 - [win10 ] Operating system.

I am not sure if any other logs are need and how to catch

**Comment by mhowlett** [comment]
seems like some sort of DNS issue. if you explicitly set the `listeners` or `advertised.listeners` property to `localhost:9092` that should work.

**Comment by whitmell** [comment]
Did you ever get this fixed?  I'm experiencing the same problem and having trouble finding info from web searches.

**Comment by milindl** [comment]
Closing this as it's been a while without info; please reopen if the issue occurs with the broker properties matt has suggested.
