### ISSUE TITLE
Confluent.Kafka 1.2 became strongly-signed and it breaks semantic versioning

### ISSUE THREAD

**Issue by zihotki** [confluentinc/confluent-kafka-dotnet#1114]
Description
===========
Strong-naming is a big breaking change and it should have been v2.0.0 instead according to the [SemVer.org](SemVer.org). Currently it causes issues with dependend libraries. For example, CloudNative.CloudEvents.Kafka nuget package references Confluent.Kafka >= 1.1.0. But version 1.2 is not possible to use instead of 1.1. 

How to reproduce
================
Install Confluent.Kafka v1.1, install CloudNative.CloudEvents.Kafka v1.0.60, update Confluent.Kafka to v1.2 and the code (sample below) will fail to compile saying that 

"Cannot convert type KafkaCloudEventMessage to Message<,>" 
"The type Message<,> is defined in an assembly that is not referenced. You must add a reference to assembly Confluent.Kafka v1.1"

But `KafkaCloudEventMessage` inherits from `Message<,>`

```
            var cloudEvent = new CloudEvent("com.blabla.bla",
                new Uri("https://some.org/url"))
            {
                Id = Guid.NewGuid().ToString(),
                Time = DateTime.UtcNow,
                Data = "hello world",
            };

            var message = new KafkaCloudEventMessage(cloudEvent, ContentMode.Structured, _cloudEventFormatter);

            await _producer.ProduceAsync(_kafkaTopic, message);
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by zihotki** [comment]
The only solution at the moment is to recompile all dependent libraries using Confluent.Kafka v1.2.0

**Comment by mhowlett** [comment]
thanks for reporting, we didn't realize this would cause this issue.
