### ISSUE TITLE
Unexpected Delay Because of fetch.max.wait.ms

### ISSUE THREAD

**Issue by john-larson** [confluentinc/confluent-kafka-dotnet#1115]
I have a single consumer subscribed to two topics. I have set `fetch.max.wait.ms` to `100000` so that **if there is no new message**, polling will not return until 100 seconds pass. I publish a message for the first topic and immediately receive the response. Then right after that, I publish a message for the second topic but consumer receives it at the end of the 100 second duration. Isn't the idea behind `fetch.max.wait.ms` that it should return immediately if there is a new message and wait otherwise?

Note: Also tried setting `FetchMinBytes` to 1 but it did not have any effect.

**Comment by mhowlett** [comment]
> Isn't the idea behind fetch.max.wait.ms that it should return immediately if there is a new message and wait otherwise?

no, this is the maximum amount time the broker may wait before sending messages back, even if they are available (so as to allow for better batching).

**Comment by john-larson** [comment]
@mhowlett So how can I achieve the scenario I mentioned? (Making the fetch wait until x ms when there is no new message but return as soon as there is a new message)

**Comment by mhowlett** [comment]
hmm, yes - setting `fetch.min.bytes` to 1 and `fetch.max.wait.ms` to 100 seconds should behave as you are wanting I think. these settings are just sent directly through in each protocol FETCH request to the broker, so the behavior is determined by the broker. 

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L4333

**Comment by edenhill** [comment]
Be careful with setting fetch.wait.max.ms too high since it effectively blocks other requests to the same broker.
Our recommendation is to stay well below socket.timeout.ms, and preferably not above 10s.

**Comment by hakankurcenlivivense** [comment]
I am trying to create an repro in an isolated project but even though I am using the same configs, the isolated repro behaves differently. No matter what I assign for `fetch.max.wait.ms`, I get the fetch response immeadiately. But in the original project, the current fetch waits until the end of the period and the next fetch receives the response at the beginning. Can you think of anything that might cause this difference in behavior?

**Comment by john-larson** [comment]
I am trying to create a repro in an isolated project but even though I am using the same configs, the isolated repro behaves differently. No matter what I assign for fetch.max.wait.ms, I get the fetch response immediately. But in the original project, the current fetch waits until the end of the period and the next fetch receives the response at the beginning. Can you think of anything that might cause this difference in behavior?

**Comment by mhowlett** [comment]
@john-larson - you mean you're looking at the logs and see this behavior? i don't quite understand what you're saying, if you provide very specific information (code / logs etc) we can comment.
