### ISSUE TITLE
Consumer assigned using TopicPartition not consuming

### ISSUE THREAD

**Issue by MrGlenThomas** [confluentinc/confluent-kafka-dotnet#112]
I'm not sure if this is intended behaviour, but appears a bug to me.

If I try to consume from a topic that has a set of messages on it and I have assigned using `Assign(IEnumerable<TopicPartitionOffset> partitions)`
..then this works fine and messages are consumed as expected.

If however I have assigned using `Assign(IEnumerable<TopicPartition> partitions)` then no messages are consumed, even though the topic has not been consumed from previously and no offsets have ever been committed. What I am expecting to happen is the consumer to begin receiving messages from the beginning of the topic. Or, if I have committed an offset then it would begin from that position.

**Comment by mhowlett** [comment]
This is behaving in accordance with the `auto.offset.reset` property which has a default value of latest.

**Comment by MrGlenThomas** [comment]
Ah I see, I'll close this then. Thanks.

**Comment by MrGlenThomas** [comment]
@mhowlett How do I configure the auto.offset.reset property? If I try to pass it in with the consumer configuration I get the error : 'No such configuration property: "auto.offset.reset"'
I see rdkafka uses a default_topic_conf, but I don't know how to apply this in the Confluent library

**Comment by edenhill** [comment]
auto.offset.reset is a topic level configuration property so you will need to set it on the "default.topic.config" sub-dictionary, like so:
```
            new Dictionary<string, object>
            {
                { "group.id", "advanced-csharp-consumer" },
                { "bootstrap.servers", brokerList },
                { "default.topic.config", new Dictionary<string, object>()
                    {
                        { "auto.offset.reset", "smallest" }
                    }
                }
            };
```

example: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdvancedConsumer/Program.cs

**Comment by MrGlenThomas** [comment]
Thanks, I had tried passing a default_topic_conf with a dictionary, but was getting the error 'Property "default_topic_conf" must be set through dedicated .._set_..() function'.

Your solution works perfectly.

**Comment by edenhill** [comment]
The next version of librdkafka will allow default topic configuration properties to be set on the global level, for convenience.
