### ISSUE TITLE
Producer Slow

### ISSUE THREAD

**Issue by MathavanN** [confluentinc/confluent-kafka-dotnet#1120]
Description
===========
I'm working on a solution, to produce messages to Kafka. Using a single producer to produce the messages. During the service startup, checking the Kafka connection, by getting the meta data of the topic. 

**Test (Kafka Broker down in between sending messages)**
After a successful producer creation, I stop the Kafka, but service try to send messages. At this time service never receive any error. I need to catch the broker down error message to notify and stop the service. 
To avoid this issue, I call meta data get method for the topic every time before send a message.  Now able to notify the broker down error message and stop the service. But **this slow down the producer speed.** 

How can be solve this issue.
Is there any way to identify the Kafka broker is running?

**Other observations**
I removed the meta data get method, Producer is able to produce the messages as we expected.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.0.0
 - [x] Apache Kafka version. 2.12
 - [ ] Client configuration. 
 - [x] Operating system. Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
the produce call will give you an error eventually - have a look at the `socket.timeout.ms` and `retries` config properties: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

if you really want to shut down your service when the cluster becomes unavailable, you can register an error handler and look for all brokers down errors.

note: typically, kafka is run in a cluster using high-availability settings, i.e. if a broker goes down, others will take over. the client is designed to automatically fail over in the case of errors and abstract this away from you.

**Comment by MathavanN** [comment]
@mhowlett this is my producer config
var config = new ProducerConfig
            {
                BootstrapServers = localhost:9092,
                SocketTimeoutMs = 1000,
                EnableIdempotence = true,
            };
1000ms is sufficient for the timeout?

**Other observations**
If I give very low SocketTimeoutMs(100) value, some of the messages getting the following error
**_Code: Local_TimedOut, IsBrokerError: False, IsError: True, IsFatal: False, IsLocalError: True, Reason: DT-P0418.local:9092/0: 2 request(s) timed out: disconnect (after 84051ms in state UP)_**
