### ISSUE TITLE
Stop Consumer When There is SIGTERM Signal in Linux

### ISSUE THREAD

**Issue by justin516142071** [confluentinc/confluent-kafka-dotnet#1121]
Description
===========

I am trying to implement graceful shutdown for my consumer running in Kubernetes. Is it possible for the consumer to stop consuming when there is a SIGTERM signal?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
it looks like handling SIGTERM is supported by .net core:
https://stackoverflow.com/questions/38291567/killing-gracefully-a-net-core-daemon-running-on-linux
https://github.com/microsoft/azure-pipelines-agent/pull/242

(i didn't read it), but do whatever that says in conjunction with the `ConsumeResult<TKey, TValue> Consume(CancellationToken cancellationToken = default(CancellationToken))` method.

**Comment by justin516142071** [comment]
Hi mhowlett, if there is a SIGTERM signal, what will Consume(CancellationToken) returns?

**Comment by mhowlett** [comment]
you need to set up a CancellationTokenSource that handles the SIGTERM. It will be similar to the Ctrl-C case in the examples: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Consumer/Program.cs#L199 if you cancel the cancellation token, the consume method with throw an exception.

**Comment by justin516142071** [comment]
Thanks for the quick response.

Will the consume method throw an OperationCanceledException or  a ConsumeException?

**Comment by mhowlett** [comment]
`OperationCanceledException`
