### ISSUE TITLE
Q: Mock Broker API?

### ISSUE THREAD

**Issue by tomasdeml** [confluentinc/confluent-kafka-dotnet#1134]
Description
===========
Are there any plans to expose the [mock broker functionality](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_mock.h#L39) introduced in librdkafka v1.3.0 ? I know it is marked as experimental yet it seems like a interesting feature for isolation testing. Or would you accept a PR? :-)

**Comment by mhowlett** [comment]
yes, for sure. we have no explicit timeline, but it will probably happen naturally as it matures and as we find we want it at the binding level.

**Comment by edenhill** [comment]
You should be able to use it as-is in sunny-scenario testing (i.e., messages will produce successfully) with producer applications by simply configuring `test.mock.num.brokers=3` in your existing application.
