### ISSUE TITLE
How do I trigger partitioner_cb?

### ISSUE THREAD

**Issue by ChadJessup** [confluentinc/confluent-kafka-dotnet#1135]
In #1133 - I'm trying to set up a custom partitioner via the ```Librdkafka.topic_conf_set_partitioner_cb``` callback.
The work was originally modeled on the Java client's implementation, and that approach isn't desired for this library, so I'm at a loss in how to make this happen.

1. The Kaka config documentation at http://kafka.apache.org/documentation/#producerconfigs
States that I need to set the "paritioner.class" key to the name of the partitioner class. Since we're going with lambda's for the handlers, I don't really have any class to set here, but I provided the name of my entrypoint class to see what would happen: ```typeof(Program).FullName```. When setting this key, librdkafka throws:
```System.InvalidOperationException: 'No such configuration property: "partitioner.class"'```

2. Next, I try to overload what the C# library does and set the key ```partitioner``` directly with ```typeof(Program).FullName```.
Which causes librdkafka to throw: ```System.ArgumentException: 'Invalid value for configuration property "partitioner": WordCountProcessorDemo.Program'```

3. I set: ```producerConfig.PluginLibraryPaths = Assembly.GetExecutingAssembly().Location;```
Which I'd think would make librdkafka aware of the assembly. The ```partitioner``` key can now be set (woo) - but during execution, this is thrown:
```System.ArgumentException: 'Failed to load symbol "conf_init": The specified procedure could not be found... (plugin <path>\WordCountProcessorDemo.dll)```

4. Setting ```producerConfig.PluginLibraryPaths = <path>``` to a Directory containing my assembly throws: ```System.ArgumentException: 'LoadLibrary() failed: Access is denied... (plugin <path>)```

I can't find documentation for this, and I'm not sure how to proceed, since I can't model this on the functioning implementation of the Java client.

Notes in #1133 from @edenhill:
```
1. The partitioner_cb will be triggered from two places: from the current application thread inside produce() if the partition count of the topic is already known, or from a background librdkafka thread as metadata is received for the topic (this typically only happens at one time (but for all queued messages) per topic).
```
_Originally posted by @edenhill in https://github.com/confluentinc/confluent-kafka-dotnet/pull/1133#issuecomment-561524381_

**Comment by mhowlett** [comment]
it's not exposed in the .net client yet. you can work around this by explicitly sending message to the desired partitions. you can build a 'partitioner' class to do the mapping if you want - and just use it on top of the current api.

**Comment by ChadJessup** [comment]
@mhowlett - my PR (#1133) is trying to implement it in the .net client. Or, are you saying that the underlying native dll won't handle this at this time?  @edenhill - did I misunderstand your comments, is it possible at all to even have the callback triggered today?

**Comment by ChadJessup** [comment]
This is resolved - I was passing in the wrong configuration object into it (needed a topic_conf).
