### ISSUE TITLE
Produce message which type is byte array

### ISSUE THREAD

**Issue by tiantianchiji** [confluentinc/confluent-kafka-dotnet#1137]
Description
===========
the type of  messages in my topic is byte array, i cann't find the method.
the message is a filestream of one xml file,i just want to know how to use the Message object to send byte array.
thanks

How to reproduce
================
demo
`     static void Main(string[] args)
        {
            var conf = new ProducerConfig { BootstrapServers = "172.27.9.55:9092"
                
            };
            Action<DeliveryReport<Null, string>> handler = r =>
            {
                Console.WriteLine(!r.Error.IsError
               ? $"Delivered message to {r.TopicPartitionOffset}"
               : $"Delivery Error: {r.Error.Reason}");
            };

            using (var p = new ProducerBuilder<Null, string>(conf).Build())
            {
                Console.WriteLine("produce start");
                long  i = 0;
                while (true)
                {
                    FileStream fs = new FileStream("D:\\123.xml",FileMode.Open);
                    BinaryReader br = new BinaryReader(fs);
                    byte[] bytes = br.ReadBytes((int)fs.Length);
                    fs.Close();
                    //how to join the byte array into the Message object
                    p.Produce("test-003", new Message<Null, byte[]> { Value = bytes }, handler);
                    Thread.Sleep(3000);
                    if (i > 1000)
                        break;
                    i++;
                }
                p.Flush(TimeSpan.FromSeconds(10));
                Console.WriteLine("produce finish");
            }
            
            Console.ReadLine();
        }`

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ 1.2.2] Confluent.Kafka nuget version.
 - [ kafka_2.11-2.3.1] Apache Kafka version.
 - [ BootstrapServers = "172.27.9.55:9092"] Client configuration.
 - [win10 64bit ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
producers are strongly typed on the message K and V. To do what you want, use `ProducerBuilder<Null, byte[]>`, not `ProducerBuilder<Null, string>`. 

side note: we may add a `ProducerBuilder` without generic parameters in a future version of the library.

**Comment by tiantianchiji** [comment]
> producers are strongly typed on the message K and V. To do what you want, use `ProducerBuilder<Null, byte[]>`, not `ProducerBuilder<Null, string>`.
> 
> side note: we may add a `ProducerBuilder` without generic parameters in a future version of the library.

**Comment by tiantianchiji** [comment]
thanks for you reply.   i toke some mistakes,i didn't know they are coherent .i need take more time to read you code.  looking foraward to your new version
