### ISSUE TITLE
IConsumer.StoreOffset should call rd_kafka_offset_store instead of rd_kafka_offsets_store

### ISSUE THREAD

**Issue by maximpashuk** [confluentinc/confluent-kafka-dotnet#1138]
Native library librdkafka has 2 functions for store offsets:
```rd_kafka_offsets_store``` - for **list** of TopicPartitionOffsets
```rd_kafka_offset_store``` - for **only one** TopicPartitionOffset

Confluent.Kafka .net library has 1 function for store offsets:
```IConsumer.StoreOffset(TopicPartitionOffset offset)``` - for **only one** TopicPartitionOffset

But internally, .net implementation always call list-specific function ``rd_kafka_offsets_store``.
See [Consumer.cs#L32](https://github.com/confluentinc/confluent-kafka-dotnet/blob/6128bdf65fa79fbb14210d73970fbd4f7940d4b7/src/Confluent.Kafka/Consumer.cs#L328) function just wraps TopicPartitionOffset with 1-element array and then call native api for list of TopicPartitionOffset

By my opinion, this is **not optimal implementation**.
.net implementation should not wrap TopicPartitionOffset with array, it should call native api method specific to only one TopicPartitionOffset, which is already exposed by librdkafka.

**Comment by mhowlett** [comment]
additionally, it seems that `rd_kafka_offset_store` acquires `rd_kafka_topic_rdlock` whereas `rd_kafka_offsets_store` does not, which is worrying. @edenhill can you comment?

regarding perf., this implementation detail is just a hangover from earlier times when there was a `StoreOffsets` method and not a `StoreOffset` method (since we have Linq, the latter is generally more convenient). well pointed out.

**Comment by maximpashuk** [comment]
> additionally, it seems that `rd_kafka_offset_store` acquires `rd_kafka_topic_rdlock` whereas `rd_kafka_offsets_store` does not, which is worrying. @edenhill can you comment?
> 
> regarding perf., this implementation detail is just a hangover from earlier times when there was a `StoreOffsets` method and not a `StoreOffset` method (since we have Linq, the latter is generally more convenient). well pointed out.

@mhowlett , I am not @edenhill , but I can see that ```rd_kafka_offsets_store``` calls function ```rd_kafka_offset_store0``` with parameter ```lock=1```
https://github.com/edenhill/librdkafka/blob/b50e247b77864c595569f7f7e9ec8dde63258210/src/rdkafka_offset.c#L692

I am not familiar with librdkafka, but by my opinion both functions have some locking logic, they are locking something called "toppar" (topic+partition?).

So as for me, I can't see big implementation differences between them, behaviour should be the same.

**Comment by edenhill** [comment]
@maximpashuk Your analysis on locking is correct 👍 

It is recommended to use `rd_kafka_offsets_store()` since it does not require the `rd_kafka_topic_t *` handle, but just a partition_list_t of topic names and partitions.

**Comment by maximpashuk** [comment]
Okay, @edenhill, you recomend always to use rd_kafka_offsets_store() function from librdkafka.
kafka-dotnet already uses it, so my issue should be closed without any fixes, am I correct?
Probably @mhowlett has some opinion.

**Comment by edenhill** [comment]
Yes, that's correct.
We're trying to move away from the rd_kafka_topic_t APIs.

**Comment by maximpashuk** [comment]
okay, I dont know about this fact then create my issue.
Now I close issue and related PR. Thanks.
