### ISSUE TITLE
[Discussion] Null Value and (de)serialization on compact topic

### ISSUE THREAD

**Issue by treziac** [confluentinc/confluent-kafka-dotnet#114]
Continuing discussion of #106 

Null serialized value are allowed on all topics, but they have a special meaning on compact topic (tombstone, delete key)
With primitive Serializer, we can't deserialize a null value

If we want to stick with java producer, we don't want to add specific behavior for producing/receiving tombstone. It should be handled directly by serializer
Easiest way is to have a NullableLong(De)Serializer and NullableInt(De)Serializer when compact topic are used, and specify in the doc it must be handled this way

Or we can deviate from the Java producer and have custom method / event for tombstone. After some tests, I prefer first option

**Comment by mhowlett** [comment]
I think we should definitely provide serdes for primitive types, which do not support `null`, as is currently the case.

I'd also happily include `NullableInt(De)Serializer`s as well, but don't see this as critical.

A very common use case for these serializers is in situations where `null` should never be used (i.e. they are keys), and I really like being able to strictly enforce that. Also I have a bit of an aversion to `Nullable` in general (e.g. no built in language support in F#).

Where you may need `null` is for values (particularly for tomb-stoning). but typically for values you will need some more complex data type, so these serializers will be less used there.

**Comment by treziac** [comment]
Yep, I am for keeping primitive serializer too.
It's just for the tombstone in rare case where value are primitive (for example a topic with stock quantity int value and productId long key), we have to use a Nullable<long> deser for the value with the current impl.

Posted an issue to keep a note here if people look for this (or to put in a wiki later)
And will be back on it in some months/year if KIP-82 or KIP-87 make it through :)

**Comment by mhowlett** [comment]
yep, good to have this discussion thread findable.
Closing for now since I think we've reached consensus.
I'll check through #106 once more and merge.
