### ISSUE TITLE
Calling ListGroups results in a ArgumentNullException

### ISSUE THREAD

**Issue by nvladimiroff** [confluentinc/confluent-kafka-dotnet#1141]
Description
===========
Calling the `ListGroups` method on the `AdminClient` without providing a specific group results in an `ArgumentNullException` instead of retrieving every group from the cluster.

How to reproduce
================
You can reproduce this by running the `AdminClient` [example program](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdminClient/Program.cs) using version 1.3.0 of the nuget package.

**Comment by mhowlett** [comment]
this is resolved in v1.4.0 https://github.com/confluentinc/confluent-kafka-dotnet/releases/tag/v1.4.0
