### ISSUE TITLE
Unable to publish message via client

### ISSUE THREAD

**Issue by MaorDavidzon** [confluentinc/confluent-kafka-dotnet#1145]
Description
===========
Hi.
I am using Kafka consumer and producer with the following configuration:
```    
 "ConsumerConfig": {
      "enable.auto.commit": true,
      "bootstrap.servers": "localhost:9092",
      "auto.offset.reset": "earliest",
      "broker.address.family": "v4"
    },
    "ProducerConfig": {
      "bootstrap.servers": "localhost:9092",
      "broker.address.family": "v4"
    }
```

Getting the following errors when trying to produce new messages:

```Assertion failed: (r == 0), function rwlock_wrlock, file tinycthread_extra```
```Delivery failed: Broker: Offset out of range```

The errors occur occasionally. (I am not sure that the errors are related to each other)

How to reproduce
================
.Net core 3 on Run on Mac 
(consume and produce from the same process in order to handle persistency)

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version. ```1.3```
 - [ ] Apache Kafka version. ```2.3.0```
 - [ ] Client configuration. 
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
My money is currently on this being a regression in 1.3, since a fair bit changed related to locking and I've never seen the problem before. It would be very useful to know if you observe the problem occurring with 1.2. It would also be very useful to have a minimal complete example demonstrating the problem so we can try to reproduce.

**Comment by MaorDavidzon** [comment]
I was able to reproduce the error in version 1.2.2.

**Comment by mhowlett** [comment]
if you can paste code, that would be super useful.

**Comment by MaorDavidzon** [comment]
After investigating the issue it was an internal bug, not related kafka confluent-kafka-dotnet.

Thanks
