### ISSUE TITLE
Unexpected memory usage when assigning partitions with AutoOffsetReset.Earliest

### ISSUE THREAD

**Issue by mausch** [confluentinc/confluent-kafka-dotnet#1148]
Description
===========

When subscribing/assigning a consumer to a topic with 9 partitions and ~16000 20KB messages in each partition and setting `AutoOffsetReset.Earliest`, memory usage blows up to 1.2GB even without consuming anything. 

How to reproduce
================

https://github.com/mausch/KafkaConsumerMemoryIssue

One the test data/topic is set up you can comment out the lines calling `DeleteTestData()` and `SetUpData()` .

I've tried to work around it by doing a Subscribe (+calling Consume() of course to actually get some partitions assigned) instead of a direct Assign, but it shows the same behaviour.

It takes a few seconds to get to that memory use, that's why I added that final delay.

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version. 1.3.0
 - [X] Apache Kafka version: Using Confluent's docker images, version 5.3.1
 - [X] Client configuration. in the project
 - [X] Operating system. Originally saw the issue on Linux, reproduced on Windows.
 - [X] Provide logs (with "debug" : "..." as necessary in configuration). N/A
 - [X] Provide broker log excerpts. N/A ?
 - [X] Critical issue.

**Comment by mhowlett** [comment]
the consumer very aggressively pre-caches message by default. you may want to tune down `QueuedMaxMessages.Kbytes` if your use case doesn't require high throughput.

**Comment by mausch** [comment]
Thanks, that did the trick! Certainly unexpected behaviour though... I get that it's a trade-off but IMHO an overly aggressive one. 
I see at least that I'm not the first one to be surprised by this e.g. https://gitter.im/edenhill/librdkafka?at=585594f7c895451b75eb1c7d , https://github.com/edenhill/librdkafka/issues/81

I'll leave this link here in case anyone hits this issue from a search : https://github.com/edenhill/librdkafka/wiki/FAQ#explain-the-consumers-memory-usage-to-me
