### ISSUE TITLE
Warn if librdkafka version lower than expected

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#115]
the version of the librdkafka binary that gets loaded is generally enforced via a nuget package dependency, however there are some scenarios where the version loaded could be different than expected (e.g. if the library is swapped out with a different build in the nuget packages directory or if using a custom build that references and older version of librdkafka.redist). 

this has lead to some difficult to track down problems - it'd be great if there was some mechanism to warn the user if an older version of librdkafka is being loaded.

more discussion at the end of #90

**Comment by treziac** [comment]
What happens if we have two apps using librdkafka.dll with different version? 
Does LoadLibrary/DllImport only check for loaded library inside the app or loaded anywhere, and does it check the version of the lib or only the name?

**Comment by edenhill** [comment]
I believe LoadLibrary will populate its own symbol table per call, so this should work. E.g., the application could use librdkafka vX and dotnet vY and it will work.
Dont really see why anyone would want to do that though

**Comment by treziac** [comment]
Had to call LoadLibrary myself in #91 

My question was more:
From what i understand, DllImport will call LoadLibrary on "librdkafka"
If librdkafka is already loaded, it won't be loaded an other time

Now if i have two apps which use Kafka, i don't know how DllImport will work - will the second app load the dll from its folder or use the already loaded dll from first app? 
And what if first app used a previous version of librdkafka (from what i Read, Loadlibrary it was only a name check, but i may be wrong, will have to test later)

> If no file name extension is specified in the lpFileName parameter, the default library extension .dll is appended. However, the file name string can include a trailing point character (.) to indicate that the module name has no extension. **When no path is specified, the function searches for loaded modules whose base name matches the base name of the module to be loaded. If the name matches**, the load succeeds. Otherwise, the function searches for the file.

DllImport call loadlibrary and we don't provide path so...
WIll have to test this
