### ISSUE TITLE
Seek or returning offsets from assigned callback do not have an effect; semantics are unclear

### ISSUE THREAD

**Issue by sershe84** [confluentinc/confluent-kafka-dotnet#1151]
Description + How to reproduce
================
AOR is set to Earliest.
I call Committed in OnAssigned callback that results from the very first Consume from a topic, and Kafka gives me offset X (I never commit anymore for this topic as I'm testing, so X is stable over hours for each partition). Yet, the consume call that resulted in the callback returns events starting from the offset X+Y where Y in my case is ~300-500 depending on partition. Future Consume calls continue returning  events at X+Y+i perpetually, and never any events between (X, Y). 

Ok, I override OnAssigned callback to return offsets, and return TPO with Offset X (or X+1) for the newly assigned partition. Consume calls still return events from X+Y+i forever.

Ok, I save the offset, and after the callback is done I explicitly call consumer.Seek(X (or +1)) for this partition. Regardless, Consume calls return events from X+Y+i.

What are the semantics of these calls/return values - how can one reliably go to the last committed offset? 
Also, is it possible to make Seek either definitively seek to an offset I asked it, or fail? I don't see how a seek call on a stream, in abstract, should be able to do anything else...

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file. 
 - [x] Confluent.Kafka nuget version. 1.2.2
 - [x] Apache Kafka version. 2.3.0?
 - [x] Client configuration. nothing special. AOR is set to Earliest.
 - [x] Operating system. Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
are you setting `EnableAutoCommit` to `false`? (it's `true` by default, which is a trap).

the behavior you describe is not expected (what you expect is what is expected), but without code it's hard to comment further. Can I suggest opening a PR with an integration test that demonstrates the failure, and I'll review?

**Comment by pranavrth** [comment]
Assuming the question is answered. Closing the issue. Please feel free to open a new one if required.
