### ISSUE TITLE
Group already referenced null

### ISSUE THREAD

**Issue by karayakar** [confluentinc/confluent-kafka-dotnet#1154]
https://github.com/confluentinc/confluent-kafka-dotnet/blob/2115c9d5d7d074b01ea9f3f79c5e773c99161bb3/src/Confluent.Kafka/Impl/SafeKafkaHandle.cs#L1026

=>        internal List<GroupInfo> ListGroups(int millisecondsTimeout)

**Comment by mhowlett** [comment]
thanks @karayakar !

**Comment by mhowlett** [comment]
this was resolved in v1.4
