### ISSUE TITLE
Support to .net core 3

### ISSUE THREAD

**Issue by ivoalexcorreia** [confluentinc/confluent-kafka-dotnet#1159]
Description
===========

So we are trying to port our application to .net core 3.1, but when we generate the docker image with .net core 3 as base image it fails because of Confluent.Kafka do not support .net core 3.

Can someone give me some information if the team is working on this or if there is any plan for soon to give support to .net core 3 .

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [] Critical issue.

**Comment by AndyPook** [comment]
Hi, I am not a maintainer but...

It ought to be fine, it does support netstandard2.0 (since at least 1.0).
I created a simple demo exe (using netcoreapp3.1). Seemed to compile and run ok.

Could you give a few more details? I'll try to help

**Comment by mhowlett** [comment]
I ran the integration tests yesterday targeting .NET Core 3.1 on ubuntu, and all was fine. there is this: https://github.com/confluentinc/confluent-kafka-dotnet/issues/1107 which I need to look into.

I'll do more extensive testing before v1.4 (the release with transactions).

**Comment by g7ed6e** [comment]
I can confirm it works with netcoreapp3.1 on a windows machine

**Comment by mhowlett** [comment]
we test that environment yes and aren't aware of any issues.

**Comment by ivoalexcorreia** [comment]
Sorry for the late response, on our app on the pre-build event we run the tool avrogen to generate the classes from Avro files, and that was the problem.

When running the build on a container with net core 3 SDK, the build fails because avrogen need netcore2 SDK installed to run.

Thanks for your tests and for your time.

**Comment by mehakkaur0409** [comment]
I am having the issue. is there alternative to generate classes from Avro files with .netcore 3.1 version ?

**Comment by mhowlett** [comment]
You could build Avrogen yourself using a newer .net version - i believe the current version packaged by the Apache project requires .NET 3.1.

**Comment by mehakkaur0409** [comment]
Hi matt, I am using .NET 3.1 only and it say on confluent documentation that:
 avrogen is available as a .NET Core Global Tool (requires .NET Core 2.1 or above). 
but when I am trying to install it, it saying incompatible.
My main objective is to convert avro schemas in .net to convert into c# classes so that I can achieve serialization and use the same by kafka producers(.net)

**Comment by mehakkaur0409** [comment]
Also I have tried with .net core version 3.1 and 5
