### ISSUE TITLE
Key serializer should not be set at producer construction

### ISSUE THREAD

**Issue by MrGlenThomas** [confluentinc/confluent-kafka-dotnet#116]
This is not a bug, but more a question on the design. I am building a system based on a large, existing set of data that has key properties of different data types. Some may be ints, some may be longs, some may be GUIDs, some may be strings. In partitioning examples I have seen, the key being used is a UserId, which could be an int. On another topic my key could be a RequestId, which is a GUID.

The producer is designed so that one instance can be used to produce messages for many topics, which is the optimum way of using the producer, but the key type for each topic may be different and the key serializer is set in the constructor. So, I am forced to have producer instances for each possible key type as the produce method does not accept a key serializer. This feels very awkward and I'm not sure how best to handle this situation. I don't want to have multiple producer instances (one per key serializer type), which I must select from based on the key type I am using. And I don't want to have to convert all my keys to strings and then always use a string serializer. I feel that the key serializer should be as dynamic as the topic name.

Please let me know what you think about this.

**Comment by treziac** [comment]
See mutli producer example for an example of use (GetSerializingProducer)

```
using (var producer = new Producer(config))
            {
                // sProducer1 is a lightweight wrapper around a Producer instance that adds
                // (string, string) serialization. Note that sProducer1 does not need to be
                // (and cannot be) disposed.
                var sProducer1 = producer.GetSerializingProducer<string, string>(new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8));

                // sProducer2 is another lightweight wrapper around kafkaProducer that adds
                // (null, int) serialization. When you do not wish to write any data to a key
                // or value, the Null type should be used.
                var sProducer2 = producer.GetSerializingProducer<Null, int>(new NullSerializer(), new IntSerializer());

                // write (string, string) data to topic "first-topic", statically type checked.
                sProducer1.ProduceAsync("first-topic", "my-key-value", "my-value");

                // write (null, int) data to topic "second-data". statically type checked, using
                // the same underlying producer as the producer1.
                sProducer2.ProduceAsync("second-topic", null, 42);

                // producers are NOT tied to topics. Although it's unusual that you might want to
                // do so, you can use different serializing producers to write to the same topic.
                sProducer2.ProduceAsync("first-topic", null, 107);

                // ProducerAsync tasks are not waited on - there is a good chance they are still
                // in flight.
                producer.Flush();
            }
```

**Comment by MrGlenThomas** [comment]
I hadn't seen that example. That is exactly what I am looking for. Thanks!

**Comment by MrGlenThomas** [comment]
Although, I have noticed the comment

> [UNSTABLE-API] We are considering making this class private in a future version so as to limit API surface area. Prefer to use the serializing producer where possible. Please let us know if you find the GetSerializingProducer method useful.

Well, I think this is quite important due to my use case above, which I imagine many others will also have!

**Comment by treziac** [comment]
Oh, i forgot this

I also have this use case, so I agree on this point. I would keep the Producer and state in the doc that producer should be created only once in common use case. Keep Producer<TKey, TValue> for simple discovery of the app (and simple cases)

I'm viewing the API as unstable (this may be my point of view only) as some things are still on discussion (hey, kafka is still not on 1.0 =D )

**Comment by mhowlett** [comment]
Thanks for the feedback @MrGlenThomas and @treziac . Some history here - I built this functionality and was strongly of the opinion that it was necessary, but there were other people arguing it should be excluded. The argument against is that the library surface area should by default be kept as small as possible (to make maintaining docs + support as easy as possible) and that since (evidently) no one ever complains about this functionality not existing on the java client it would be a little used feature.

Marking this as unstable made everyone happy enough as it makes it really to adjust / remove in a future version if we want. Assuming I continue to have any say in the matter, I expect everything will stay as is. I'll be arguing for removing the UNSTABLE notification in the next major release version.

Anyone else who finds the non-serializing producer useful, please comment here - the more votes we have the better :-)

**Comment by treziac** [comment]
It's not so much that the non serizalizing producer is useful, but it's the best way to have a single producer instance (librdkafka point of view). 

It would be the low-level producer, allowing to produce with arraysegment and other thing the closest to librdakfka as possible (so don't need nice overload and other: if you use it for something else than getting a high-level serializer producer, you have to know what you do)

While including timestamp I ended up playing a little with the overloads and impl (but changing the api - it's bad, I know) Will post a PR for feedback about it :)

**Comment by mhowlett** [comment]
@treziac re: discussion on non-serializing producer - yes, exactly.

**Comment by mhowlett** [comment]
PR #183
