### ISSUE TITLE
No message consumed after disconnection

### ISSUE THREAD

**Issue by RomainAn** [confluentinc/confluent-kafka-dotnet#1162]
Hi everyone,

Recently i got some issue when i was facing a disconnection or a coordination load in progress.

> failed: No connection could be made because the target machine actively refused
Error: GroupCoordinator: Connect to ipv4#XXXXXXXXXXX:9092 failed: No connection could be made because the target machine actively refused it... (after 2001ms in state CONNECT)
Revoking assignment: XXXXXXX@16829]
Assigned partitions: [XXXXXX [[0]]

After that, messages are not consumed anymore and just my program is waiting.

Sometimes also : 

> Revoking partition
> Coordinator load in progress
> Assigning partition

Is it a know issue of the version (I recently updated from 1.0.0 or 1.0.1) ? Did i do something wrong or do i have to do something more ?

Thank you for your kind help !

- Confluent.Kafka nuget version : 1.3.0
- Client configuration : 
```
        private ConsumerConfig _configKafka => new ConsumerConfig
        {
            BootstrapServers = ConfigurationManager.AppSettings["BrokerList"],
            GroupId = "app", // DO NOT CHANGE THIS
            EnableAutoCommit = false,
            SessionTimeoutMs = 20000,
            MaxPollIntervalMs = 600000,
            AutoOffsetReset = AutoOffsetReset.Earliest
        };
```
- Operating system : Windows server

**Comment by mhowlett** [comment]
are you catching exceptions thrown by `Consume` (logging and continuing)? this is a re-tryable error but iirc it may leak out into application code (we need to fix). you can safely ignore this if it's an exception.

**Comment by Rymix** [comment]
I think it's thrown by consume, but i'm not sure. The issue is that the consumer revoke and assign back normally but there is no message consumed anymore.
I have to manually restart the application to process messages again.

**Comment by mhowlett** [comment]
i say the above because they symptom you note is often a result of people not catching the consume exception, and their program exiting the consume loop (so not consuming messages), but the application still remaining active in a zombie state.

to comment more, need more information - minimal source code demonstrating the problem or logs etc.

**Comment by Rymix** [comment]
Hi, sorry for the misunderstanding.
I confirm you that my try catch is within the consume loop.

```
while (!_keepRunning.IsCancellationRequested)
{
    try
    {
        UtilsDebug.ConsumeResult = null;
        consumeResult = consumer.Consume(_keepRunning.Token);
    }
    catch (OperationCanceledException e)
    {
        SentryManager.SendException(e);
        consumer.Close();
        return;
    }
    catch (Exception e)
    {
        SentryManager.SendException(e);
    }
    CommitMsg(consumer, consumeResult);
}
```

I removed json operations and other stuff that are not related to kafka.
As I mentioned in my previous message, this stuff happened while updating to a new version.
I'm gonna try to downgrade in my testing environments.

**Comment by mhowlett** [comment]
you shouldn't `close` the consumer if three is an exception - generally just log it and keep consuming. afaict from your code, if there is an exception you exit the consumer loop, so you would not expect to keep consuming.

**Comment by Rymix** [comment]
Hi.

Actually, the return and the close inside the OperationCanceledException is needed, because this is a windows service, and if it's stop, i need to exit the code.
Just to code up with my issue, i reverted in a previous version and there is no more issue. So i will test new version later.

**Comment by jeremy001181** [comment]
> Hi.
> 
> Actually, the return and the close inside the OperationCanceledException is needed, because this is a windows service, and if it's stop, i need to exit the code.
> Just to code up with my issue, i reverted in a previous version and there is no more issue. So i will test new version later.

You have the `_keepRunning` cancellation token, so if the service is stoped, it should break out of the loop anyway?

**Comment by laukotomi** [comment]
I can also reproduce this bug. The overload for consume method which takes CancellationToken behaves differently than the ones which take a timeout.

`consumer.Subscribe("topic3"); // this topic doesn't exist
var cts = new CancellationTokenSource();

while (true)
{
    try
    {
        consumer.Consume(cts.Token);
    }
    catch(Exception ex)
    {
        Console.WriteLine(ex.Message);
    }

    Thread.Sleep(new TimeSpan(0, 0, 1)); // hours, minutes, seconds
}`

The exception will only be logged once then the program freezes on the next Consume() call. If I create the topic nothing happens. When I do the same procedure with Consume(100) then it "works": no exceptions are thrown, but null is returned and "Unknown topic or partition" is logged and when I create the topic again then it starts consuming.
