### ISSUE TITLE
Not able to connect with broker via SASL on Windows

### ISSUE THREAD

**Issue by justin516142071** [confluentinc/confluent-kafka-dotnet#1165]
Description
===========
Hi, I am trying to use connect to the broker via SASL_SSL on a Window Machine.

But I got error saying InitializeSecurityContext failed: Target unknown

Note: I am able to connect to the broker via SSL.

How to reproduce
================
Operating System: Windows 7
Confluent Kafka Dotnet version: 1.3.0
Apache Kafka version: Confluent 5.2.2 (Apache Kafka 2.2.1)

Producer configuration:

                BootstrapServers ="broker:6668",
                SaslMechanism = SaslMechanism.Gssapi,
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SslCaLocation = "./cert.pem",
                SslCertificateLocation = "./cert.pem",
                SslKeyLocation = "./cert.key",
                SaslKerberosServiceName = "service",
                SaslKerberosPrincipal = "service/principle@domain.com",
                ApiVersionRequest = false,
                Debug = "all"
Log
=========

%7|1579192615.371|SEND|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Sent SaslHandshakeRequest (v1, 29 bytes @ 0, CorrId 10)
%7|1579192615.390|RECV|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Received SaslHandshakeResponse (v1, 14 bytes, CorrId 10, rtt 18.89ms)
%7|1579192615.392|SASLMECHS|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Broker supported SASL mechanisms: GSSAPI
%7|1579192615.394|AUTH|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Auth in state AUTH_HANDSHAKE (handshake supported)
%7|1579192615.395|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Broker changed state AUTH_HANDSHAKE -> AUTH_REQ
%7|1579192615.398|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: Broadcasting state change
%7|1579192615.398|SASL|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Initializing SASL client: service name esaas, hostname broker, mechanisms GSSAPI, provider Win32 SSPI

%7|1579192615.401|SASL|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Acquired Kerberos credentials handle (expiry in 2147483404.-322922497s)
%7|1579192615.402|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: failed: err: Local: Authentication failure: (errno: Invalid argument)
%3|1579192615.404|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown (0x80090303) (after 6ms in state AUTH
_REQ)
%3|1579192615.407|ERROR|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown (0x80090303) (after 6ms in state AUTH_REQ)

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by edenhill** [comment]
confluent-kafka-dotnet (or more precisely the underlying librdkafka client) will use the logged on user's principal to authenticate via GSSAPI on Windows, while it will use the krb5 tools on Linux/OSX.

**Comment by justin516142071** [comment]
Is there way to find out what content (in which format) was used to authenticate via GSSAPI?

**Comment by rnpridgeon** [comment]
You actually obtain a TGT meaning your client's credentials are valid but the KDC(Domain Controller) is unable to locate the service principal you are requesting a ticket for.  In your case this looks to be `esaas/broker@DOMAIN.COM`. 

```
%7|1579192615.398|SASL|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Initializing SASL client: service name esaas, hostname broker, mechanisms GSSAPI, provider Win32 SSPI
...
%7|1579192615.401|SASL|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Acquired Kerberos credentials handle (expiry in 2147483404.-322922497s)
...
%3|1579192615.404|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker:6668/bootstrap]: sasl_ssl://broker:6668/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown (0x80090303) (after 6ms in state AUTH
_REQ)
```

You will need to ensure your broker UPN has an SPN matching {service name}/{fully-qualified-hostname}@{domain}. Also ensure that all user accounts (client and server) have strong encryption enabled. By default all windows users will use RC4-HMAC, you'll need AES-128/AES-256 otherwise you will get odd failures when client/server negotiate a session key.

**Comment by MarkRx** [comment]
> confluent-kafka-dotnet (or more precisely the underlying librdkafka client) will use the logged on user's principal to authenticate via GSSAPI on Windows, while it will use the krb5 tools on Linux/OSX.

Does this mean that it is not possible to use a principle other than the logged user's to authenticate?

**Comment by edenhill** [comment]
@MarkRx Correct. There might be some trick with SetSPN with friends, but that's outside my knowledge.
