### ISSUE TITLE
Question on expected lifetimes of ProducerBuilder and Producer.

### ISSUE THREAD

**Issue by CautiousMarmoset** [confluentinc/confluent-kafka-dotnet#1168]
Question:
Is it considered optimal to create one ProducerBuilder for the lifetime of the application and build and dispose of a Producer per produce request? Or is it preferable to create one Producer only for the lifetime of the application?

**Comment by mhowlett** [comment]
Creating a `Producer` is very expensive, you should generally only have one over the lifetime of the application.

The lifetime of `ProducerBuilder` is unimportant.

**Comment by moxixuan** [comment]
> 
> 
> Question:
> Is it considered optimal to create one ProducerBuilder for the lifetime of the application and build and dispose of a Producer per produce request? Or is it preferable to create one Producer only for the lifetime of the application?

https://github.com/confluentinc/confluent-kafka-dotnet/issues/159
