### ISSUE TITLE
1.3 ProduceAsync changes

### ISSUE THREAD

**Issue by JohnTicehurst** [confluentinc/confluent-kafka-dotnet#1170]
Description
===========
I'm trying to upgrade our app from 0.11.4 to 1.3.
One of our tests is to drop the Kafka broker during processing.
In 0.11.4 we caught this error with the following code and used the Result.Error.HasError member
var task = producer.ProduceAsync(topic, messageKey, message, partition.Value) :
return task.Result;

This test doesn't work well in 1.3 ,
Firstly the Result.Error property is no longer in the DeliveryResult class
Secondly the test just hangs in ProduceAsync never returning and never throwing out.

I am using a Console App to test this and I can see ERRORS / FAIL  being written to the Console - it must be from ProduceAsync - but no result is returned or no exception thrown see the  screenshot below.

![Broker_Down](https://user-images.githubusercontent.com/18668889/73572648-6e6b6700-44c5-11ea-9398-5fcd156da96a.png)

How can I get ProduceAsync to throw/return  from this error ?

How to reproduce
================
Using 1.3 just take the Broker down during Producer processing. 

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
Errors exposed via the Error property of the delivery report in 0.11.x are exposed as exceptions in 1.x API. How long are you waiting? the default settings of `retries=2` and `socket.timeout.ms=60000` will result in an error after 3 minutes (iirc).

**Comment by JohnTicehurst** [comment]
Well I do get a Local timeout exception but it's well after the fact - more than 300 seconds after the Broker has been dropped.
The first screenshot shows the producer properties I use. Socket Timeout 3000 and retries of 1  
![image](https://user-images.githubusercontent.com/18668889/73698018-1e460c00-4734-11ea-8931-03de53366c21.png)

The next screenshot shows the code capturing the Local timeout exception after 5 minutes.
![image](https://user-images.githubusercontent.com/18668889/73698133-62d1a780-4734-11ea-8f1b-3e9619f12ba1.png)

This screenshot shows the Console log and the exception of the Kafka Broker at 09
:41:41 - this log also has my debug text and I used these timestamps, but you can see FAIL and ERROR messages being written by your code.
![image](https://user-images.githubusercontent.com/18668889/73698208-93194600-4734-11ea-9712-da1f69c26f1e.png)

This last screenshot is the console app after ProduceAsync throws the excpetion and returns at 09:47:28
![image](https://user-images.githubusercontent.com/18668889/73698305-decbef80-4734-11ea-8f37-48fa0cf3ea99.png)

Is there any other property I can use to detect the problem in a more timely manner.

Thanks,
John

**Comment by JohnTicehurst** [comment]
It starts to behave much better when I set the message.timeout.ms property to 3000ms
I think that's the property I needed.

Thanks for looking at it,
John

**Comment by mhowlett** [comment]
Yep, `MessageTimouetMs`.

The idea with the API/default config is that you give your message to the .net client, then it does whatever's necessary to deliver it to the cluster under the terms you've configured (retries, timeouts etc). i.e. the client attempts to abstract away what you're trying to do manually.
