### ISSUE TITLE
consumer doesn't receive messages( kafka running on docker)

### ISSUE THREAD

**Issue by blenddata** [confluentinc/confluent-kafka-dotnet#1172]
Description
===========
I'm using [debezium ](http://debezium.io) on docker hosted on Ubuntu, zookeeper, Kafka and connector are working fine, event Im able to add connector from client via rest API.
(Trying to connect from windows client)
![image](https://user-images.githubusercontent.com/50766350/73656633-cd87d200-46a5-11ea-9590-c7c13898927f.png)

According to [this log file](http://txt.do/16j9c), ([Producer log file](http://txt.do/16j97)) I'm connected to the instance, with debezium watcher able to see messages:
watcher CMD:
`docker run -it --name watcher --rm --link zookeeper:zookeeper --link kafka:kafka debezium/kafka:1.0 watch-topic -a -k OKS00505.xx.xxxx`

but when i subscribe with below code nothing comes up. 

```
var config = new ConsumerConfig
            {
                GroupId = new Guid().ToString(),
                BootstrapServers = brokerList, //172.31.64.69:9092
                AutoOffsetReset = AutoOffsetReset.Earliest,
                StatisticsIntervalMs = 5000,
                SessionTimeoutMs = 6000,
                EnablePartitionEof = true,
                EnableAutoCommit = true
            };

            using (var consumer =
                new ConsumerBuilder<Null, string>(config)
                    .SetErrorHandler((_, e) => 
                    Console.WriteLine($"Error: {e.Reason}")
                    )
                .SetStatisticsHandler((_, json) => 
                Console.WriteLine($"Statistics: {json}")
                )
                .SetPartitionsAssignedHandler((c, partitions) =>
                {
                    Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}]");
                })
                .SetPartitionsRevokedHandler((c, partitions) =>
                {
                    Console.WriteLine($"Revoking assignment: [{string.Join(", ", partitions)}]");
                })
                    .Build())

            {
                consumer.Assign(topics.Select(topic => new TopicPartitionOffset(topic, 0, Offset.Beginning)).ToList());

                try
                {
                    while (true)
                    {
                        try
                        {
                            var consumeResult = consumer.Consume(cancellationToken);
                            Console.WriteLine($"Received message at {consumeResult.TopicPartitionOffset}: ${consumeResult.Value}");
                        }
                        catch (ConsumeException e)
                        {
                            Console.WriteLine($"Consume error: {e.Error.Reason}");
                        }
                    }
                }
                catch (OperationCanceledException)
                {
                    Console.WriteLine("Closing consumer.");
                    consumer.Close();
                }
            }
        }
```

Am I doing something wrong? 
Appreciate any helps.
:heart:

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.  (1.3.0)
 - [ ] Apache Kafka version. (2.4.0)
 - [ ] Client configuration.
 - [ ] Operating system.(Ubuntu)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
It looks like 172.31.64.69:9092 is telling you that the group coordinator is 172.17.0.3:9092, but the client can't access it, so looks like a docker network usage issue. You may need to set the advertised.listeners property on the broker.

at one point i was setting up some tests to use docker (but never got merged), these might be helpful:

https://github.com/mhowlett/confluent-kafka-dotnet/tree/smoke/env

... or the latest might be the smoke2, or smoke3 branch, I can't remember :-).

**Comment by blenddata** [comment]
:confused: 
Yeah you are right. 
A piece of advise to who are reading this "**Do not run any platform on docker except you micro-services**", Its networking is a pain, do you know how much time I spend on it? Last time I was trying to run spark cluster on it and stuck in networking again. Now I'm asking myself whats the point of that except more maintenance.
Actually `KAFKA_ADVERTISED_LISTENERS  ` is a environment variable that must be set in yaml file then build the image. [Here is a good explanation of it.](https://rmoff.net/2018/08/02/kafka-listeners-explained/)
@mhowlett thanks for your response.
