### ISSUE TITLE
Q: Deserialization of Statistics Json

### ISSUE THREAD

**Issue by msallin** [confluentinc/confluent-kafka-dotnet#1174]
It is possible to retrieve metrics using "SetStatisticsHandler" as JSON (https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md). To make use of them, they might need to be deserialized.

Is there a particular reason why they are exposed as raw JSON and not as deserialized object? If not, would you accept a PR which implements this?

Thanks, Marc

**Comment by mhowlett** [comment]
the statistics handler simply passes through what's exposed by librdkafka (which is a string in json format).

it's an open question as to the best way to improve this. we are also thinking about exposing metrics in prometheus format for example, which would be quite different to the current setup.

the best way to help out here is probably to provide an analysis on the different ways metrics can be exposed and opinions/justification on what is most useful.

anyone feel free to chime in!

**Comment by msallin** [comment]
Okay. I might give a bit of context what we are doing.

Our applications are required to expose metrics (Runtime, Hosting). As we use Kafka as backbone for communicating, we have to have metrics there as well. 

We built a library which collects metrics using .NET Core EventCounters and expose them in Prometheus format, using a middleware. We plan to make this OSS as soon as its finished. The nice thing about this solution is that EventCounters are part of .NET Standard and technology agnostic. Furthermore, we can use the .NET Core tooling around EventCounters.

We use a library which wraps this library (see https://github.com/BEagle1984/silverback & there https://github.com/BEagle1984/silverback/pull/56/files#r368285370). As its a rather thin abstract, we can get our hands at the Statistics-JSON. However, now we want to expose certain values of the statistics JSON as EventCounters, which of course needs deserialization. 

We didn't thought fully through all metrics to gather but certainly we want to have things like the following. Not even sure if all of them are present in the statistics.

Consumer: 
- # messages received
- # Assigned partitions
- Incoming byte rate
- Consumer lag
- # Rebalances

Producer:
- # messages sent
- #outgoing byte rate
- # retries
- # messages in buffer (producer queue)

We didn't discuss the level on which we want to aggregate (topic? partition?).

cc: @beagle1984

**Comment by BEagle1984** [comment]
@mhowlett I believe that you shouldn't focus too much on the serialized format (json vs. prometheus vs. whatever). What I would expect is to receive an object (deserialized) in the statistics event. Then each client can decide to re-serialize the data and/or store them in the form that better suit them.
We can of course deserialize it on our side or at least parse it somehow but I really believe this is something that you should take care of in your library, since you are the ones wrapping librdkafka and you should be aware of managing the possible changes in the json schema.

**Comment by mhowlett** [comment]
@BEagle1984 - yes we would ideally create a C# object hierarchy to represent the stats events, and that would be good. The reason we haven't is simply time to do so, and burden to keep it up to date (prioritization, we have other things to do ahead of it).

when I say prometheus, i mean the client would have an embedded HTTP server and expose the stats through that, allowing super easy integration with prometheus (which is a common ask). assuming we did provide a nice C# object of the stats, a lot of work would be required to achieve prometheus integration still. also, we'd probably implement all this in the C level, providing the capability across all librdkafka bindings simultaneously. it would be good to have strongly typed C# object as well, but the promethus integration is likely to be prioritized higher (higher roi).
