### ISSUE TITLE
Handle Local_QueueFull error gracefully 

### ISSUE THREAD

**Issue by maximecaron** [confluentinc/confluent-kafka-dotnet#1175]
Description
===========
When calling Produce or ProduceAsync on instance of IProducer<TKey, TValue> at high throughput
an exception of type ProduceException with Error.Code == ErrorCode.Local_QueueFull will be thrown.

I know this is by design inside librdkafka but the only way it can be handled by the caller is by calling _producer.Poll and retrying at a later time.

To mitigate the issue we had to do a retry loop like this
```
    do
	{
		try
		{
			_producer.Produce(topicPartition, msg, deliveryHandler.HandleDeliveryReport);
			msgWritten = true;
		}
		catch (ProduceException<Null, byte[]> ex)
		{
			if (ex.Error.Code == ErrorCode.Local_QueueFull)
			{
				_producer.Poll(TimeSpan.FromSeconds(1));
			}
			else
			{
				throw;
			}
		}
	} while (msgWritten == false);
```

I believe this logic should abstracted inside confluent-kafka-dotnet library.

**Comment by mhowlett** [comment]
yes it's by design - we don't want to make the api blocking.

one thing we will do eventually to make it slightly easier is add a specific exception type corresponding to Local_QueueFull that derives from ProduceException.

**Comment by alfhv** [comment]
according to the example here: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/ExactlyOnce/Program.cs#L421

a Thread.Sleep() could be used.

question: which 'pause' event we should use to allow queue be processed ? Poll or Sleep ?

**Comment by mhowlett** [comment]
the .net client polls for you in a background thread, so some other mechanism, possibly Sleep.
