### ISSUE TITLE
[Documentation] Avro Schema file extension

### ISSUE THREAD

**Issue by cyberKarapuz** [confluentinc/confluent-kafka-dotnet#1176]
Description
===========
In the avrogen usage section, Avro schema file extension is `asvc`, but it should be  `avsc`.
Same thing applies for the leading Confluent page [Decoupling Systems with Apache Kafka, Schema Registry and Avro](https://www.confluent.io/blog/decoupling-systems-with-apache-kafka-schema-registry-and-avro/)
It's not the case for this library (any type of text file can be used as an input for `avrogen`), but, as it states here 

[Apache Avro™ 1.8.1 Getting Started](https://avro.apache.org/docs/1.8.1/gettingstartedjava.html)
> Note that if you using the Avro Maven plugin, there is no need to manually invoke the schema compiler; the plugin automatically performs code generation on any .avsc files present in the configured source directory.

wrong file extension can cause problems.

**Comment by mhowlett** [comment]
thanks! changes underway.
