### ISSUE TITLE
Question: ProduceAsync Schema Validation

### ISSUE THREAD

**Issue by stephenwood** [confluentinc/confluent-kafka-dotnet#1180]
Description
===========
This is a little involved, so I'll try to be as clear (but succinct) as possible.  

My company's CI/CD pipeline uses gradle to generate AVRO schemas from AVDL files. 

When I use avrogen to generate a class from one of those schemas, the generated code contains a static schema property. The initialization of that property looks like this:

public static Schema _SCHEMA = Schema.Parse("SCHEMA TEXT HERE").

When the code is generated, the SCHEMA TEXT HERE part is a very slimmed down version of the schema in the registry.  That would be fine, except that when I call ProduceEvent, it apparently goes looking for a schema that precisely matches the text of the schema in the static _SCHEMA variable,  And because Schema.Parse only grabs a subset of the provided string, that checksum fails every time. So I get a 40303 error.

Has anyone else seen this? If so, what did you do to get around this? NOTE: I don't think this is a bug.  I just think it's a situation, and if it weren't for a CI/CD pipeline process over which I have no control, it wouldn't be an issue.  That also means I can describe how repro steps look from my side, but have no visibility into the CI/CD pipeline.

How to reproduce
================

1. Create a valid AVDL file.
2. Use a command like this one to 

ava -jar avro-tools-1.9.1.jar idl2schemata c:\\schema-repository\\MySchema.avdl c:\\schema_files

3. avrogen -s c:\\schema-repository\\MySchema.avdl

4.  Call ProtonProducer.ProduceEvent on the generated class.

Unfortunately, that's as far as I can go in providing repro steps because I don't have physical access to the gradel file that generates the .avsc files.

=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
i'm putting the likely blame here on avro. i'm quite sure the schema matching in schema registry isn't text based. however i don't trust avrogen to have not made some incompatible adjustment to the schema it embedded in the class. 

now we have protobuf and json support across confluent platform, i'd recommend one of these serialization formats if possible since they have more mature implementations in .net, and will likely cause fewer headaches.
