### ISSUE TITLE
ListGroups throws exception

### ISSUE THREAD

**Issue by kuehlmeyer** [confluentinc/confluent-kafka-dotnet#1181]
Description
===========

I'm creating an AdminClient with the AdminClientBuilder and then call the method **ListGroups** with only a time limit as parameter. See below for a code example. With version 1.3.0, the call throws this exception:

    Unhandled Exception: System.ArgumentNullException: Argument 'group' must not be null.
    Parameter name: group
       at Confluent.Kafka.Impl.SafeKafkaHandle.ListGroupsImpl(String group, Int32 millisecondsTimeout)
       at Confluent.Kafka.AdminClient.ListGroups(TimeSpan timeout)
       at KafkaConsumer.Program.Main(String[] args) in C:\Git\am-tools\Source\KafkaConsumer\KafkaConsumer\Program.cs:line 78

I can't even pass in a "group" parameter.

How to reproduce
================

Sample code:

            AdminClientConfig config = new AdminClientConfig
            {
                BootstrapServers = "some-server"
            };

            using (var adminClient = new AdminClientBuilder(config).Build())
            {
                var groups = adminClient.ListGroups(TimeSpan.FromSeconds(20.0));
                Console.WriteLine("Found " + groups.Count + " groups");
            }

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.3.0] Confluent.Kafka nuget version.
 - [5.0.1] Apache Kafka version.
 - [ ] Client configuration.
 - [Windows] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
thanks for reporting! already resolved in the 1.4.x branch, will be fixed in v1.4.0: https://github.com/confluentinc/confluent-kafka-dotnet/commit/f19cfb8886f114052498f52ccda559228b83d84f

**Comment by kuehlmeyer** [comment]
Cool! Thanks!

**Comment by BrennenSprimont** [comment]
As info,
This seems to have been introduced in the 1.3.0 release.
Reverting back to 1.2.2 is a functional workaround (until 1.4.x is released).
