### ISSUE TITLE
Confluent Kafka throws Commit Error : Local: Waiting for coordinator

### ISSUE THREAD

**Issue by ManteshJangond** [confluentinc/confluent-kafka-dotnet#1182]
Description
===========

Sometimes confluent Kafka consumer not consuming messages until restart instance.

Getting the following exception 

Commit Error : Local: Waiting for coordinator

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - Confluent.Kafka nuget version. v1.3.0
 -  Apache Kafka version. v2.3.1
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 -  Provide broker log excerpts. Commit Error : Local: Waiting for coordinator
 -  Critical issue.

**Comment by mhowlett** [comment]
there are some possibly related fixes in v1.4.2: https://github.com/edenhill/librdkafka/releases please reopen if the problem persists in this version (and provide as much info as possible, in particular debug: all logs).
