### ISSUE TITLE
Q: Next Release/Timeline(With Transaction Support)?

### ISSUE THREAD

**Issue by gelihu** [confluentinc/confluent-kafka-dotnet#1185]
Description
===========

Not an issue. Few questions:
* When will be the next version(1.4.?) released?
* And will this include Tranx support?
* Should we try working with Nuget Package(1.4.0.PRE) first?
* If I leverage transactions, do I have to ammend consumer along with producer (I apologize, if question is intuitive; I would be very much obliged if you could refer me to some documention/caveats on transactions)? 

Thank you very much for this feature...

**Comment by mhowlett** [comment]
just opened the PR for 1.4.0-RC1 https://github.com/confluentinc/confluent-kafka-dotnet/pull/1186, should get it on nuget soon. AFAWK this has no blocker issues, but we continue to soak test and currently plan on releasing on a ~< 2week timeframe. yes this has transactions. no, don't use 14.0-PRE, wait for RC1. look at the WordCount example for usage. Be warned it's pretty verbose, but you should be able to copy/paste a lot of that.

**Comment by gelihu** [comment]
Wow, that was quick, you guys are the best 😍 , thanks for the PR and information.
