### ISSUE TITLE
listing consumer group fails

### ISSUE THREAD

**Issue by michael-elly** [confluentinc/confluent-kafka-dotnet#1188]
Description
===========
The code which I built to list consumer groups which is based on the sample from
confluent-kafka-dotnet/examples/AdminClient/
fails. It returns the error:
System.ArgumentNullException: 'Argument 'group' must not be null. Parameter name: group'
but no such argument is provided. 

How to reproduce
================
simply run the example and choose to list the consumer groups.

I have installed Kafka on my development windows machine (kafka_2.11-2.4.0.tgz). It all works fine and I'm able to send and receive messages using the sample batch scripts.

Trying to build a C# windows application, I'm using Confluent's .NET Client for Apache Kafka (version 1.3.0.0) on a C# windows application. However when I'm using the sample given by Confluent to list the group subscriptions I'm getting the error System.ArgumentNullException: 'Argument 'group' must not be null. Parameter name: group' but there is no such argument that I pass into the method. Here's the code sample:

Thats the code I have:
private static string ListConsumerGroups(string bootstrapServers) {
    string s = ($"Consumer Groups:"); 
    using (var adminClient = new AdminClientBuilder(new AdminClientConfig { BootstrapServers = bootstrapServers }).Build()) {
        var groups = adminClient.ListGroups(TimeSpan.FromSeconds(10));
        foreach (var g in groups) {
            s += "\r\n" + ($"  Group: {g.Group} {g.Error} {g.State}");
            s += "\r\n" + ($"  Broker: {g.Broker.BrokerId} {g.Broker.Host}:{g.Broker.Port}");
            s += "\r\n" + ($"  Protocol: {g.ProtocolType} {g.Protocol}");
            s += "\r\n" + ($"  Members:");
            foreach (var m in g.Members) {
                s += "\r\n" + ($"    {m.MemberId} {m.ClientId} {m.ClientHost}");
                s += "\r\n" + ($"    Metadata: {m.MemberMetadata.Length} bytes");
                s += "\r\n" + ($"    Assignment: {m.MemberAssignment.Length} bytes");
            }
        }
    }
    return s;
}

The code fails when making the call to adminClient.ListGroups with the timespan argument (no other arguments allowed into this method). When using the batch scripts to list the consumer group I do get a valid answer back.

> kafka-consumer-groups.bat --list --bootstrap-server "localhost:9092"

Confluent.Kafka nuget version:
\source\repos\KafkaClient\packages\Confluent.Kafka.1.3.0\lib\net46\Confluent.Kafka.dll

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
this is fixed in 1.4.0-RC1, available on nuget.
