### ISSUE TITLE
[Question] Is Confluent.Kafka or Librdkafka thread-safe? 

### ISSUE THREAD

**Issue by jeffreycruzana** [confluentinc/confluent-kafka-dotnet#119]
I'm going to do some further improvements on my solution that uses Confluent.Kafka. One of the improvements is me creating new worker threads that subscribes to a single or multiple topics. 

Is Confluent.Kafka or Librdkafka thread-safe?

**Comment by treziac** [comment]
Yes, they are, except for some functions which are strictly mentioned this way (for example, PartitionAvailable should be called only in the partitioner)

Note that if you can, it could be better to have only one consumer polling, and redistribute messages to your worker threads (this will prevent duplicated network connexions), not sure if there have been benchmarked given this scenario.

**Comment by mhowlett** [comment]
this thread continued from #103 (relevant discussion there).

as @treziac says, almost all methods are thread safe and those that aren't are marked as such.

if you find yourself wanting to poll on a single consumer instance from multiple threads, you're almost certainly looking at things the wrong way.
