### ISSUE TITLE
How to pass Headers into ProduceAsync?

### ISSUE THREAD

**Issue by bsurtz** [confluentinc/confluent-kafka-dotnet#1193]
Description
===========
I can not figure out how to pass Headers into ProduceAsync.  Is there any sample C# code that does this?

Version 1.3.0

How to reproduce
N/A
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
just set the`Headers` property in the `Message` object. I don't think there's an example project that does this, but here it is being done in an integration test: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/test/Confluent.Kafka.IntegrationTests/Tests/Headers.cs#L57

**Comment by bsurtz** [comment]
Thanks for the quick reply.  I'll give that a try.

**Comment by pranavrth** [comment]
Closing this as the question has been answered. Please open a new one if you have more questions.
