### ISSUE TITLE
Is the library able to send message from a window server to kafka on linux with SASL_PLAINTEXT and GSSAPI

### ISSUE THREAD

**Issue by chouyazi** [confluentinc/confluent-kafka-dotnet#1198]
Description
===========
I've read through a few posts that it seems to me the answer to my question is NO, can someone confirm my understanding? I'm using Kafka 0.10.0.2.5.3.51-3 and .NET framework 4.6.1. 

I tried with below code, but no luck.

var config = new Dictionary<string, string> {
                    { "bootstrap.servers", "server.com:9092" },
                    { "api.version.request", "true" },
                    { "group.id", "TestKafka" },
                    { "sasl.mechanisms", "GSSAPI" },
                    { "security.protocol", "SASL_PLAINTEXT" },
                    { "sasl.kerberos.service.name", "kafka" },
                    { "debug","all"},
                   { "sasl.kerberos.principal", "user@domain.COM" }           
             };
            var kafkaConfig = new ProducerConfig(config);
            string topic = "test_kafka_topic";
            using (var producer = new ProducerBuilder<Null, string>(kafkaConfig).Build())
            {
                producer.ProduceAsync(topic, new Message<Null, string> { Value = "testing" });
            }

            

Error without debug option on:
%3|1582767467.907|FAIL|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown (0x80090303) (after 11ms in state AUTH_LEGACY)

Trace with debug option on:
%7|1582767700.858|SASL|rdkafka#producer-1| [thrd:app]: Selected provider Win32 SSPI for SASL mechanism GSSAPI
%7|1582767700.869|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1582767700.871|WAKEUPFD|rdkafka#producer-1| [thrd:app]: sasl_plaintext://server.com:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1582767700.872|BROKER|rdkafka#producer-1| [thrd:app]: sasl_plaintext://server.com:9092/bootstrap: Added new broker with NodeId -1
%7|1582767700.872|CONNECT|rdkafka#producer-1| [thrd:app]: sasl_plaintext://server.com:9092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1582767700.873|BRKMAIN|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enter main broker thread
%7|1582767700.873|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.3.0 (0x10300ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, SSL ZLIB SNAPPY SASL_SCRAM PLUGINS HDRHISTOGRAM, debug 0xfffff)
%7|1582767700.873|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Received CONNECT op
%7|1582767700.874|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1582767700.875|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: Broadcasting state change
%7|1582767700.875|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1582767700.876|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1582767700.876|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: Broadcasting state change
%7|1582767700.917|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Connecting to ipv4#IP:9092 (sasl_plaintext) with socket 2908
%7|1582767700.919|TOPIC|rdkafka#producer-1| [thrd:app]: New local topic: test_kafka_topic
%7|1582767700.922|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Connected to ipv4#IP:9092
%7|1582767700.927|CONNECTED|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Connected (#1)
%7|1582767700.928|FEATURE|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1582767700.930|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1582767700.926|TOPPARNEW|rdkafka#producer-1| [thrd:app]: NEW test_kafka_topic [-1] 05258420 (at rd_kafka_topic_new0:393)
%7|1582767700.933|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: Broadcasting state change
%7|1582767700.937|SEND|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Sent ApiVersionRequest (v0, 25 bytes @ 0, CorrId 1)
%7|1582767700.941|RECV|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Received ApiVersionResponse (v0, 120 bytes, CorrId 1, rtt 4.17ms)
%7|1582767700.944|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Broker API support:
%7|1582767700.947|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey Produce (0) Versions 0..2
%7|1582767700.955|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey Fetch (1) Versions 0..2
%7|1582767700.967|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey Offset (2) Versions 0..0
%7|1582767700.974|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey Metadata (3) Versions 0..1
%7|1582767700.978|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey LeaderAndIsr (4) Versions 0..0
%7|1582767700.987|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey StopReplica (5) Versions 0..0
%7|1582767701.000|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey UpdateMetadata (6) Versions 0..2
%7|1582767701.003|DESTROY|rdkafka#producer-1| [thrd:app]: Terminating instance (destroy flags none (0x0))
%7|1582767701.011|TERMINATE|rdkafka#producer-1| [thrd:app]: Interrupting timers
%7|1582767701.009|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey ControlledShutdown (7) Versions 1..1
%7|1582767701.025|TERMINATE|rdkafka#producer-1| [thrd:app]: Sending TERMINATE to internal main thread
%7|1582767701.039|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey OffsetCommit (8) Versions 0..2
%7|1582767701.049|TERMINATE|rdkafka#producer-1| [thrd:main]: Internal main thread terminating
%7|1582767701.068|DESTROY|rdkafka#producer-1| [thrd:main]: Destroy internal
%7|1582767701.061|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey OffsetFetch (9) Versions 0..1
%7|1582767701.048|TERMINATE|rdkafka#producer-1| [thrd:app]: Joining internal main thread
%7|1582767701.072|BROADCAST|rdkafka#producer-1| [thrd:main]: Broadcasting state change
%7|1582767701.084|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey FindCoordinator (10) Versions 0..0
%7|1582767701.108|DESTROY|rdkafka#producer-1| [thrd:main]: Removing all topics
%7|1582767701.110|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey JoinGroup (11) Versions 0..0
%7|1582767701.122|TOPPARREMOVE|rdkafka#producer-1| [thrd:main]: Removing toppar test_kafka_topic [-1] 05258420
%7|1582767701.129|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey Heartbeat (12) Versions 0..0
%7|1582767701.130|DESTROY|rdkafka#producer-1| [thrd:main]: test_kafka_topic [-1]: 05258420 DESTROY_FINAL
%7|1582767701.133|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey LeaveGroup (13) Versions 0..0
%7|1582767701.136|DESTROY|rdkafka#producer-1| [thrd:main]: Sending TERMINATE to sasl_plaintext://server.com:9092/bootstrap
%7|1582767701.137|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey SyncGroup (14) Versions 0..0
%7|1582767701.139|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey DescribeGroups (15) Versions 0..0
%7|1582767701.138|TERMINATE|rdkafka#producer-1| [thrd:main]: Purging reply queue
%7|1582767701.140|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey ListGroups (16) Versions 0..0
%7|1582767701.141|TERMINATE|rdkafka#producer-1| [thrd:main]: Decommissioning internal broker
%7|1582767701.142|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey SaslHandshake (17) Versions 0..0
%7|1582767701.146|TERMINATE|rdkafka#producer-1| [thrd:main]: Join 2 broker thread(s)
%7|1582767701.146|TERM|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Received TERMINATE op in state INIT: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1582767701.147|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:   ApiKey ApiVersion (18) Versions 0..0
%7|1582767701.149|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: No error)
%7|1582767701.149|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature MsgVer1: Produce (2..2) supported by broker
%7|1582767701.150|FAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Client is terminating (after 291ms in state INIT)
%7|1582767701.151|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature MsgVer1: Fetch (2..2) supported by broker
%7|1582767701.152|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> DOWN
%7|1582767701.153|BROADCAST|rdkafka#producer-1| [thrd::0/internal]: Broadcasting state change
%7|1582767701.153|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enabling feature MsgVer1
%7|1582767701.154|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1582767701.159|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature MsgVer2: Produce (3..3) NOT supported by broker
%7|1582767701.160|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1582767701.161|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature MsgVer2: Fetch (4..4) NOT supported by broker
%7|1582767701.162|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset
%7|1582767701.167|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Disabling feature MsgVer2
%7|1582767701.179|TERMINATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Handle is terminating in state DOWN: 1 refcnts (05222C50), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1582767701.180|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature ApiVersion: ApiVersion (0..0) supported by broker
%7|1582767701.187|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enabling feature ApiVersion
%7|1582767701.192|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature BrokerGroupCoordinator: FindCoordinator (0..0) supported by broker
%7|1582767701.187|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: No error)
%7|1582767701.201|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enabling feature BrokerGroupCoordinator
%7|1582767701.222|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature BrokerBalancedConsumer: FindCoordinator (0..0) supported by broker
%7|1582767701.215|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1582767701.230|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker
%7|1582767701.243|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1582767701.250|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker
%7|1582767701.251|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset
%7|1582767701.252|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker
%7|1582767701.268|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker
%7|1582767701.273|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker
%7|1582767701.274|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker
%7|1582767701.281|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enabling feature BrokerBalancedConsumer
%7|1582767701.285|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature ThrottleTime: Produce (1..2) supported by broker
%7|1582767701.285|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature ThrottleTime: Fetch (1..2) supported by broker
%7|1582767701.298|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enabling feature ThrottleTime
%7|1582767701.312|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature Sasl: JoinGroup (0..0) supported by broker
%7|1582767701.315|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enabling feature Sasl
%7|1582767701.316|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature SaslHandshake: SaslHandshake (0..0) supported by broker
%7|1582767701.323|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enabling feature SaslHandshake
%7|1582767701.336|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature LZ4: FindCoordinator (0..0) supported by broker
%7|1582767701.343|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Enabling feature LZ4
%7|1582767701.346|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature OffsetTime: Offset (1..1) NOT supported by broker
%7|1582767701.361|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Disabling feature OffsetTime
%7|1582767701.376|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature IdempotentProducer: InitProducerId (0..0) NOT supported by broker
%7|1582767701.387|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Disabling feature IdempotentProducer
%7|1582767701.399|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature ZSTD: Produce (7..7) NOT supported by broker
%7|1582767701.407|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature ZSTD: Fetch (10..10) NOT supported by broker
%7|1582767701.410|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Disabling feature ZSTD
%7|1582767701.413|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature UnitTest: SaslHandshake (1..1) NOT supported by broker
%7|1582767701.414|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap:  Feature UnitTest: SaslAuthenticate (0..0) NOT supported by broker
%7|1582767701.415|APIVERSION|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Disabling feature UnitTest
%7|1582767701.416|FEATURE|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4
%7|1582767701.417|AUTH|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Auth in state APIVERSION_QUERY (handshake supported)
%7|1582767701.418|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Broker changed state APIVERSION_QUERY -> AUTH_HANDSHAKE
%7|1582767701.422|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: Broadcasting state change
%7|1582767701.423|TERM|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Received TERMINATE op in state AUTH_HANDSHAKE: 2 refcnts, 0 toppar(s), 0 active toppar(s), 1 outbufs, 0 waitresps, 0 retrybufs
%7|1582767701.425|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: No error)
%7|1582767701.426|FAIL|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Client is terminating (after 3ms in state AUTH_HANDSHAKE)
%7|1582767701.427|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Broker changed state AUTH_HANDSHAKE -> DOWN
%7|1582767701.428|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: Broadcasting state change
%7|1582767701.429|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Purging bufq with 0 buffers
%7|1582767701.433|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Purging bufq with 1 buffers
%7|1582767701.433|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Updating 0 buffers on connection reset
%7|1582767701.434|TERMINATE|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Handle is terminating in state DOWN: 1 refcnts (0522C070), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1582767701.435|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: No error)
%7|1582767701.436|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Purging bufq with 0 buffers
%7|1582767701.437|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Purging bufq with 0 buffers
%7|1582767701.438|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://server.com:9092/bootstrap]: sasl_plaintext://server.com:9092/bootstrap: Updating 0 buffers on connection reset
%7|1582767701.451|TERMINATE|rdkafka#producer-1| [thrd:main]: Internal main thread termination done
%7|1582767701.451|TERMINATE|rdkafka#producer-1| [thrd:app]: Destroying op queues
%7|1582767701.463|TERMINATE|rdkafka#producer-1| [thrd:app]: Termination done: freeing resources

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
yes, however see this comment: https://github.com/edenhill/librdkafka/issues/1259#issuecomment-432534315
