### ISSUE TITLE
High End to End Latency with low rtt

### ISSUE THREAD

**Issue by mattk-mojio** [confluentinc/confluent-kafka-dotnet#1207]
Description
===========

- I created two console apps - a producer that sends a message with a timestamp, and a consumer that uses that timestamp to calculate end-to-end latency.
- I produce 10 messages per second, for 10 seconds each with a total of 10 bytes for the message content (8 bytes of which is the timestamp).
- rtt for consume and produce is around network latency (~50 ms) - so it seems the issue is not processing on the kafka side.
- end to end latency as measured by the consumer is as below:
Avg: 85.84 ms, 50th: 86 ms, 75th: 97 ms, 85th: 108 ms, 90th: 111 ms, 95th: 112 ms, 98th: 119 ms, 99th: 213 ms, 99.9th: 213 ms.
- Question is where is the extra 30, 40, 50, 60 ms going?

How to reproduce
================
- run consumer
- once consumer has sync'd up with kafka, run the producer

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version - 1.3.0
 - [x] Apache Kafka version: kafka_2.12-2.3.0
 - [x] Client configuration.
- Producer:
"security.protocol": "PlainText",
    "bootstrap.servers": "broker1:9092,broker2:9092,broker3:9092",
    "compression.type": "gzip",
    "linger.ms": "5",
    "message.timeout.ms": "60000",
    "request.required.acks": "1",
 "debug": "protocol",
    "socket.nagle.disable": "true"
- Consumer:
"auto.offset.reset": "latest",
    "group.id": "test",
    "enable.auto.commit": "true",
    "bootstrap.servers": "broker1:9092,broker2:9092,broker3:9092",
    "security.protocol": "plaintext",
    "enable.partition.eof": "true",
    "fetch.wait.max.ms": "5",
    "fetch.min.bytes": "1000",
 "debug": "protocol",
    "socket.nagle.disable":"true"
 - [x] Operating system.
- Consumer & Producer: Windows 10 Pro
- Kafka: ubuntu 16.04 (3 brokers, and 1 zookeeper node)
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.
[consumer_stats.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/4296037/consumer_stats.txt)
[producer_stats.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/4296038/producer_stats.txt)

**Comment by mhowlett** [comment]
it's hard to say without more information / debugging it. but the additional latency you're seeing is high. are all the brokers in the same data center? this info might be helpful: https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#low-latency
