### ISSUE TITLE
Consume the same message if processing message fails

### ISSUE THREAD

**Issue by rezamanshouri** [confluentinc/confluent-kafka-dotnet#1212]
Description
===========
Question:
I am using Confluent.Kafka .NET client version 1.3.0. I am following the [docs](https://docs.confluent.io/current/clients/dotnet.html#store-offsets):

```
var consumerConfig = new ConsumerConfig
{
    BootstrapServers = "server1, server2",
    AutoOffsetReset = AutoOffsetReset.Earliest,
    EnableAutoCommit = true,
    EnableAutoOffsetStore = false,
    GroupId = this.groupId,
    SecurityProtocol = SecurityProtocol.SaslPlaintext,
    SaslMechanism = SaslMechanism.Plain,
    SaslUsername = this.kafkaUsername,
    SaslPassword = this.kafkaPassword,
};

using (var consumer = new ConsumerBuilder<Ignore, string>(consumerConfig).Build())
{
    var cancellationToken = new CancellationTokenSource();
    Console.CancelKeyPress += (_, e) =>
    {
        e.Cancel = true;
        cancellationToken.Cancel();
    };

    consumer.Subscribe("my-topic");
    while (true)
    {
        try
        {
            var consumerResult = consumer.Consume();
            // process message
            consumer.StoreOffset(consumerResult);
        }
        catch (ConsumeException e)
        {
            // log
        }
        catch (KafkaException e)
        {
            // log
        }
        catch (OperationCanceledException e)
        {
            // log
        }
    }
}
```
The problem is that even if I comment out the line `consumer.StoreOffset(consumerResult)`, I keep getting the next unconsumed message the next time I `Consume`, i.e. the offset keeps increasing which doesn't seem to be what the documentation claims it does, i.e. at least one delivery.

Even if I set `EnableAutoCommit = false` and remove `EnableAutoOffsetStore = false` from the config, and replace `consumer.StoreOffset(consumerResult)` with `consumer.Commit()`, I still see the same behavior, i.e. even if I comment out the `Commit`, I still keep getting the next unconsumed messages.

I feel like I am missing something fundamental here, but can't figure what. Any help is appreciated!

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by saagar2000** [comment]
I've added some comments [here ](https://stackoverflow.com/questions/60549752/re-consume-kafka-messages-from-a-given-time?noredirect=1#comment107310366_60549752) in stackoverflow post. I believe it comes down whether there is  option to pass some kind of seek callback to the subscribe call so when the message processing fails we can seek to offset and process it again. I know this can be done by using separate assign/seek/consume workflow but we will lose the consumer re-balance and group subscription. Just wondering if there was option to keep everything while still be able to seek on demand from subscribe flow.

**Comment by mhowlett** [comment]
> The problem is that even if I comment out the line consumer.StoreOffset(consumerResult), I keep getting the next unconsumed message the next time I Consume, i.e. the offset keeps increasing which doesn't seem to be what the documentation claims it does, i.e. at least one delivery.

this is intended behavior. what calling `StoreOffset` does is tell the consumer to commit the offsets back to kafka, marking them as consumed. doingthis doesn't have any effect until the next time a consumer in the group starts reading from the partition.
