### ISSUE TITLE
Consumer can't  consume data when it consume working more 30day+

### ISSUE THREAD

**Issue by copts001** [confluentinc/confluent-kafka-dotnet#1216]
Description
===========
Hi, I'm use Confluent.Kafka Version = 0.11.5.0
I Use consumer to connect in config 

I found problem when myservice call kafkaconsumer and working run more 30+ day sometime kafkaConsumer can't consume message anymore but no error log response i try to fix  by restart service but it not work can't fix the problem
and i try to restart my server and run it again it work normally
and no log error show like it working normally but no have error message  i have try catch on myfunction but it look like working normally with try function and no error and it not go to catch error

sorry for my bad english

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. = 0.11.5.0
 - [ ] Apache Kafka version. 
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
there was an overflow issue with 0.11.5 related to timestamp which was resolved in 0.11.6, this sounds like that. 0.11.6 is API compatible with 0.11.5, recommend upgrading to at least that version (ideally later as there are many more stability fixes, but we broke API compatibility in a big way in 1.0).
