### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by zm935580231** [confluentinc/confluent-kafka-dotnet#122]
Hi,how to judge the program occur Connection Timed Out Error

**Comment by mhowlett** [comment]
hi @zm935580231 - the library manages connections for you. In general, a `Producer` or `Consumer` may be connected to more than one broker - this is abstracted away. In the configuration, you supply one or more bootstrap servers and the client finds the location of other brokers automatically via metadata requests. If a broker dies, or goes down, the client works out what to do automatically.

If you are consuming, you may want to adjust the `session.timeout.ms` parameter which controls how long before kafka waits before considering a `Consumer` to be unresponsive and ejecting it from the consumer group.

If you are producing, you can tell if all brokers are unreachable by looking at the `Error` property of delivery reports returned by the `ProduceAsync` method. You can control number of retries / timeouts etc. via relevant config parameters. refer to: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by zm935580231** [comment]
Thanks,but how to look at the Error property of delivery reports returned by the ProduceAsync method.
the program export the Error message  the Console,how to catch it?

**Comment by treziac** [comment]
You have an OnError delegate on the producer (resp. consumer) for error which are not related to a specific message. When it is not registered, a console.writeline is called.

For the result of a produceAsync, you can look at the task<Message> (or the IDeliveryHandler when using the proper overload) Error property (with a continuewith for example) to get the corresponding error

**Comment by mhowlett** [comment]
To stop messages being logged to the console, you'll need to specify an `OnLog` handler to override the default one. You can use the `OnError` handler to detect 'critical' errors (though note: the client will try to automatically recover for you, they should not be considered catastrophic). There isn't a default `OnError` handler.

**Comment by zm935580231** [comment]
OK,thanks men!(*^__^*) 嘻嘻……
