### ISSUE TITLE
Consumer.QueryWatermarkOffsets returns incorrect offsets

### ISSUE THREAD

**Issue by deeptowncitizen** [confluentinc/confluent-kafka-dotnet#1222]
Description
===========
I'm using Consumer.QueryWatermarkOffsets to calculate Lag for a concrete partition/consumer group/topic. No specific manipulation, only pure API data.

But when I compare this Lag with Lenses data it differs 10%+.
From my observation, Lenses showed pretty correct data most of the time.
Is there any accuracy/caching or any other mechanism which may lead to a such behavior?

How to reproduce
================
Nuget: 1.2.2
Kafka: 1.1.1
Lenses: 2.2.2
Env: K8S nix

Pretty straightforward code:
`
let consumer = new Consumer(...consumerGroup...);
consumer.QueryWatermarkOffsets(TopicPartition('<topic>', '<partition>')
`

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
`QueryWatermarkOffsets` directly calls the kafka protocol offsets api and returns the result, there is no caching.
