### ISSUE TITLE
Subscribe topic with regex , When kafka  added new topic, Consume will not receive new topic message

### ISSUE THREAD

**Issue by lsunflower** [confluentinc/confluent-kafka-dotnet#1223]
Description
===========
Subscribe topic with regex , When kafka  added new topic, Consume will not receive new topic message, Unless resubscribed.

How to reproduce
================
nuget:1.3.0
kafka:2.4.0
env:windows

Code:
 ```
            using (var consumer = new ConsumerBuilder<Ignore, string>(conf).Build())
            {
                consumer.Subscribe("^project.*");

                CancellationTokenSource cts = new CancellationTokenSource();
                Console.CancelKeyPress += (_, e) =>
                {
                    e.Cancel = true; 。
                    cts.Cancel();
                };

                try
                {
                    while (true)
                    {
                        try
                        {
                            var cr = consumer.Consume(cts.Token);
                        }
                        catch (ConsumeException e)
                        {
                        }
                    }
                }
                catch (OperationCanceledException e)
                {
                    consumer.Close();
                }
            }
```
Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
The consumer will see the new topics on its next periodic metadata refresh which is controlled by `topic.metadata.refresh.interval.ms`.
You can also trigger a refresh manually by calling `Metadata()`
