### ISSUE TITLE
maxpoll rdkafka application maximum poll interval exceeded

### ISSUE THREAD

**Issue by mfjiang** [confluentinc/confluent-kafka-dotnet#1224]
Description
===========
run a consumer app as a long-running service,by a few days after,it was a error like:
maxpoll rdkafka application maximum poll interval <300000ms>exceeded by 755614245ms adjust max.poll.interval.ms for long-running message processing:leaving group

How to reproduce
================
run a consumer app as a long-running service by a few days. 

Checklist
=========
Confluent.Kafka nuget version:  1.3.0
Apache Kafka version: 2.11-2.1.1
Client configuration: default
Operating system: cent os 7 (server), windows server 2012 (consumer client)

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version. 
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
are you using subscribe or assigning to the partitions to read from directly? (i.e. this might be #1220 )?

**Comment by mfjiang** [comment]
i try to another way to make a long-running consumer.when it's EOF then resubscribe the topic. may be corrected,now let it run a few days.

**Comment by mfjiang** [comment]
corrected
