### ISSUE TITLE
AvroGen: Uncompilable code for records having a field with the same name as the record

### ISSUE THREAD

**Issue by bhaeussermann** [confluentinc/confluent-kafka-dotnet#1230]
Description
===========

When generating code for a record having a field with the same name as the record, AvroGen produces a class containing a property having the same name as the class, which C# does not allow.

Confluent.Apache.Avro package version used is 1.7.7.7

This is problematic when using the Avro.CodeGen class to generate Avro types at run-time.

How to reproduce
================

Invoke AvroGen on the schema below. It generates a class named "cars" containing a property named "cars".

```
{
	"type": "record",
	"name": "person",
	"namespace": "Kafka.Tests.AvroTypes",
	"fields": [
		{
			"name": "garage",
			"type": 
			{
				"type": "record",
				"name": "cars",
				"fields": [
					{
						"name": "cars",
						"type": {
							"type": "array",
							"items": {
								"type": "record",
								"name": "car",
								"fields": [
									{
										"name": "model",
										"type": "string"
									},
									{
										"name": "make",
										"type": "string"
									}
								]
							}
						}
					}
				]
			}
		}
	]
}
```

**Comment by mhowlett** [comment]
In v1.4.0, we've migrated to using the official Apache Avro packages. Please these versions of the tools instead and report any issues to the Avro repo: https://github.com/apache/avro

We've also introduced support for protobuf and json - you might want to consider these serialization formats instead which have better implementations in .net.
