### ISSUE TITLE
Question: Compression at producer

### ISSUE THREAD

**Issue by leafduan** [confluentinc/confluent-kafka-dotnet#1232]
Description
===========
Exception: Broker: Message size too large
The max message size is 2 MB, and the produced message size in 2.052 MB.
Using ProducerConfig with setted Compression, it did not working. But, using gzip compress before producing message, and set ProducerConfig.CompressionType  to None, it works.

How should I to set the ProducerConfig Compress to make it works?

Confluent.Kafka: 1.3.0
Configuration: setted compression type/level
OS: Windows 10

How to reproduce
================
``` csharp
var config = new ProducerConfig
{
	BootstrapServers = "",
	CompressionType = CompressionType.Gzip,
	CompressionLevel = 1
};

var msg = new Message<string, byte[]>s
{ 
	// Value = Encoding.UTF8.GetBytes("large string");  // Broker: Message size too large
	Value = Compress(Encoding.UTF8.GetBytes("large strings")); // pass
 }

producer.ProduceAsync("leaf.test", msg)

bytes[] Compress(bytes bytes)
{
	using (var mstream = new MemoryStream())
	{
		using (var zstream = new GZipStream(mstream, CompressionLevel.Fastest))
		{
			 zstream .Write(bytes, 0, bytes.Length);
		}

		return mstream.ToArray();
	}
}
```

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
This is expected behaviour, the message.max.bytes limit is checked on each produce() for the uncompressed size, and to limit the maximum batch size after compression.

**Comment by leafduan** [comment]
Thanks, I got it.
