### ISSUE TITLE
Dotnet API analogue for kafka-reassign-partitions.sh

### ISSUE THREAD

**Issue by spaceorc** [confluentinc/confluent-kafka-dotnet#1233]
Description
===========
Couldn't find method in AdminClient that can do partition reassignment, like kafka-reassign-partitions.sh can, as described in https://kafka.apache.org/documentation/#basic_ops_increase_replication_factor. Is there any plans to add this functionality to AdminClient?

nuget: confluent.kafka/1.3.0

**Comment by mhowlett** [comment]
no there's no plans for this.
