### ISSUE TITLE
Does consume timeout produce a message that is null or an exception?

### ISSUE THREAD

**Issue by masyyy** [confluentinc/confluent-kafka-dotnet#1234]
Couldnt find this clearly explained in the API documentation so decided to ask here. Does a call to consume timing out produce a message that is null always or throw an exception? Also if the answer is that it produces a message that is null does any other situation produce a null message? In essence can a null message be automatically assumed to have happened because of a timeout?

 - [ 1.2.2] Confluent.Kafka nuget version.

**Comment by mhowlett** [comment]
yes, if you get `null`, that is always because no message is available to be consumed before the specified timeout.

note also that exceptions thrown by `Consume` should generally just be logged, they aren't terminal.

**Comment by masyyy** [comment]
Thank you for the answer!
