### ISSUE TITLE
Connection state change callback?

### ISSUE THREAD

**Issue by andy1547** [confluentinc/confluent-kafka-dotnet#1239]
Description
===========
Is there any way to know that a connection state change has occurred (disconnected & reconnected events) when using Producers/Consumers? 

For example the .NET NATS client provides the following hooks https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/Options.cs#L67

Thanks in advance.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.4.0 ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
The logic in librdkafka related to this is a bit lengthy and I don't have time to work through it right now to give a precise answer. Marking as enhancement as I think we should document this in detail. But yes, you can know this by registering an error and/or log handler. I'm pretty sure you'll get connection closed notifications via the 'error' handler, if registered, but to pick up on connection establishment you'll need to add a log handler and specify a `Debug` property string that includes 'broker' (or all). This info isn't easily exposed because the idea is that it be completely abstracted away from you. What is your use case - general monitoring of network / cluster stability?

key librdkafka function for tracing this: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L532

**Comment by edenhill** [comment]
The connection status of single brokers are not of much interest since the application will not know what broker to track the state of.

**Comment by edenhill** [comment]
Lengthy explanation:
https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down

**Comment by mhowlett** [comment]
> .. I believe it is more useful to look at the data than the protocol: Set up a statistics callback and raise an alarm if partition message queues or round-trips are building up; this covers far more problems than monitoring for single broker disconnects

yes! in suggesting the above, i mean in the context of devising some health check based on potentially various bits of information. but as @edenhill points out, on reflection, connection status is not going to be a particularly valuable input into that.

even in the case of a client that wants to passively monitor the health of a cluster, such a health check would be better derived from say metadata requests.

**Comment by andy1547** [comment]
Thanks for the quick responses.

Our particular use case involves producing events to a single Kafka broker instance, the source of the events is a MySQL queue table. 

Periodically we poll for new events, we rely on the delivery report callback to know the event has been delivered at least once (we're happy to produce duplicates occasionally), before removing from the MySQL queue row.

The MySQL queue is often massive in size (100GB+), if we continued to add events to the Kafka client queue buffer while down we'd eventually hit QueueBufferingMaxKbytes/QueueBufferingMaxMessages (I assume messages would start getting discarded in the Kafka client in FIFO). 

We'd like to try and avoid this, in this scenario a callback would allow polling to be disabling until the broker comes back up.

**Comment by edenhill** [comment]
While this is not recommended for the reasons stated in the FAQ, you can achieve this logic by monitoring stats, keeping track of the leader for each partition and the state of each leader.
https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

A more robust and less complex alternative would perhaps be to minimize the producer queue and simply rely on produce() QUEUE_FULL backpressure, you push MySQL table events into the producer until it returns QUEUE_FULL, then hold back for x seconds before resuming.

**Comment by andy1547** [comment]
I went with using the RX statistic as it still get incremented when the connection is healthy but no messages are being consumed/produced.
Thanks for your assistance.
