### ISSUE TITLE
JsonSerializer- Local: Value serialization error : Unrecognized field: references; error code: 422

### ISSUE THREAD

**Issue by MohamedRDwedar** [confluentinc/confluent-kafka-dotnet#1242]
I follow the example of JsonDeserializer  
and i always got this error message 

Local: Value serialization error : Unrecognized field: references; error code: 422
i am using the these nuget versions 

Confluent.Kafka : 1.4.0
Confluent.SchemaRegistry: 1.4.0
Confluent.SchemaRegistry.Serdes : 1.3.0
Confluent.SchemaRegistry.Serdes.Json:  1.4.0

what i am missing here ?

**Comment by mijgame** [comment]
I also have this issue with the Protobuf serializer.

**Comment by mhowlett** [comment]
please provide more information. does the example application work for you? https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/JsonSerialization

**Comment by edenhill** [comment]
JSON and Protobuf is only supported in the not yet released version of Confluent Schema Registry. You will need to build it manually from source until it has been formally released.

**Comment by mhowlett** [comment]
thanks @edenhill , i have no idea how that slipped my mind.

**Comment by MohamedRDwedar** [comment]
@mhowlett no it doesn't work for me i have downloaded the example you have mentioned 
and i got this error after Local: Value serialization error : Unrecognized field: references; error code: 422 .

also try the same steps in my application and got the same error .

**Comment by MohamedRDwedar** [comment]
@edenhill  this nuget package has been realsed 5 days ago Confluent.SchemaRegistry.Serdes.Json -Version 1.4.0
or you mean another another one ?

**Comment by mhowlett** [comment]
The first version of Schema Registry to support JSON Schema is v5.5.0, however that hasn't been released yet. To use the JSON or Protobuf serdes you need that. To get started now, you'll need to download from https://github.com/confluentinc/schema-registry and compile yourself (master or 5.5.x branch)

**Comment by MohamedRDwedar** [comment]
thanks @mhowlett is there any time frame when the official docker images ill be released .

**Comment by mhowlett** [comment]
i don't know when exactly, but it shouldn't be too far off.

**Comment by MohamedRDwedar** [comment]
thanks @mhowlett i hope in will very soon as i am starting new project based of kafka

**Comment by mhowlett** [comment]
Confluent Platform v5.5 is now out.

**Comment by Alpesh1984909090** [comment]
I'm also getting the same error. i'm using Avro format and trying to push the message using confluent kafka libraries for C# 

Local: Value serialization error
 ---> Confluent.SchemaRegistry.SchemaRegistryException: ; error code: -1
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func`1 createRequest)
   at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)
   at Confluent.SchemaRegistry.RestService.GetLatestSchemaAsync(String subject)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.GetLatestSchemaAsync(String subject)
   at Confluent.SchemaRegistry.Serdes.SpecificSerializerImpl`1.Serialize(String topic, T data, Boolean isKey)
   at Confluent.SchemaRegistry.Serdes.AvroSerializer`1.SerializeAsync(T value, SerializationContext context)
   at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)
