### ISSUE TITLE
OffsetForTimes usage: Assign/Unassign must not be called in the partitions assigned handler

### ISSUE THREAD

**Issue by codertimu** [confluentinc/confluent-kafka-dotnet#1243]
Description
===========
Hello,

I want to consume a Kafka topic based on timestamps. I tried to use `OffsetForTimes` as follows:
```
            var today = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            var timeStampsToSearch = new List<TopicPartitionTimestamp>();
            foreach (var topicPartition in partitionsAssigned)
            {
                timeStampsToSearch.Add(new TopicPartitionTimestamp(topicPartition, new Timestamp(today)));
            }
            
            var offSets = _kafkaConsumer.OffsetsForTimes(timeStampsToSearch, TimeSpan.FromSeconds(30));
            
```
I tried to do the above in `PartitionsAssigned` handler but got the exception "Assign/Unassign must not be called in the partitions assigned handler".

I need partitions to be able to create `TopicPartitionTimestamps`, how do I get the partitions for a topic? 

I wonder why there is no corresponding API for the Java counterpart:
`List<PartitionInfo> partitionsFor(String topic)`?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.3.0
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system. Mac OS
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
in addition to the above code you pasted, are you also calling `Assign` in the partitions assigned handler?

to specify the start offsets, the collection of `TopicPartitionOffset`s from the handler, don't call `Assign`.

**Comment by codertimu** [comment]
Yes, I did like this `_kafkaConsumer.Assign(offSets);` inside assigned handler.

>to specify the start offsets, return the collection of TopicPartitionOffsets from the handler, don't call Assign.

Sorry,  I didn't get what you meant above.
How should I use the `TopicPartitionOffsets` I created in the assigned handler?

**Comment by mhowlett** [comment]
see the comment here: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Consumer/Program.cs#L66

**Comment by codertimu** [comment]
I got it now. Thanks.
