### ISSUE TITLE
415 Unsupported Media Type when charset=utf-8 is included in Content-Type header

### ISSUE THREAD

**Issue by jeremy001181** [confluentinc/confluent-kafka-dotnet#1245]
I set up my Kafka with Aiven and I was getting 415 unsupported media type error response when checking schema 
![image](https://user-images.githubusercontent.com/2342277/78888931-95f92580-7a5a-11ea-82d0-5eda712ec12a.png)

After looking into I figured out it was because the `charset=utf-8` that was added in the content-type header causing the problem, and it works fine after removing it. And I believe this is added on this line [L258](https://github.com/confluentinc/confluent-kafka-dotnet/blob/25f320a672b4324d732304cb4efa2288867b320c/src/Confluent.SchemaRegistry/Rest/RestService.cs#L258)

So I am not sure if it is something must require, or can be removed? I don't mind creating a PR for it if you agree that it can be removed

Thanks

**Comment by mhowlett** [comment]
yep, sounds good - it's not intended to be there. Confluent's Schema Registry is tolerant of this, so it's never been an issue.

**Comment by jeremy001181** [comment]
thanks, @mhowlett I have raised a PR for it
