### ISSUE TITLE
Apache.Avro support for .net framework 4.x

### ISSUE THREAD

**Issue by PaluruSumanth** [confluentinc/confluent-kafka-dotnet#1248]
Why is that .Net framework support is removed in Apache.Avro 1.9.1 onwards? Is there plan to support .Net framework in upcoming versions? Is there anyway for .Net framework 4.x applications to consume latest apache.avro changes?

**Comment by mhowlett** [comment]
previously, Confluent maintained a fork of the official repo to facilitate rapidly making changes required to use the library with Confluent.Kafka. In 1.9.1, the official Avro library incorporated all our bug fixes and overtook our fork in terms of features and we switched over in 1.4. Our fork supported net451, but the official library only supports back to netstandard2.0. This is compatible with net461 and above.
