### ISSUE TITLE
Question about partitioning by a message class property

### ISSUE THREAD

**Issue by lambdakris** [confluentinc/confluent-kafka-dotnet#1250]
Say that I have a data stream of patients for many hospitals, where the patient type looks something like this:
```
class Patient {
    public string HospitalId { get; set; }
    public string AccountNumber { get; set; }
}
```
Is it possible to arrange for there to be a partition per Hospital so that all messages pertaining to a Hospital would be in order and the consumer could know which Hospital it would be receiving data for (know which partition to subscribe to)?

**Comment by mhowlett** [comment]
when you produce, specify a specific partition based on the hospital id. you could just take the hospitalId modulo the number of partitions.

```
        Task<DeliveryResult<TKey, TValue>> ProduceAsync(
            TopicPartition topicPartition,
            Message<TKey, TValue> message,
            CancellationToken cancellationToken = default(CancellationToken));
```
