### ISSUE TITLE
Committed Offsets are not sequential when produced with Transactional Producer

### ISSUE THREAD

**Issue by gelihu** [confluentinc/confluent-kafka-dotnet#1251]
Description
===========

Committed offsets are not sequential when messages are produced with a transactional producer, some offsets are being skipped, one gets skipped. Is this expected with a transactional producer?

How to reproduce
================
``` csharp
namespace SampleKafkaClient
{
    internal class Program
    {
        static void Main(string[] args)
        {
            const string server = "localhost:9092";
            var pcfg = new ProducerConfig
            {
                BootstrapServers = server,
                ClientId = "non-non-biyori",
                TransactionalId = "non-non"
            };
            var defaultTimeSpan = TimeSpan.FromSeconds(90);

            using (var prd = new ProducerBuilder<byte[], byte[]>(pcfg).Build())
            {
                prd.InitTransactions(defaultTimeSpan);
                int i = 0;
                var sha512 = SHA512.Create();
                void printReport(DeliveryReport<byte[], byte[]> dr)
                {
                    Console.WriteLine("Produced at {0}", dr.TopicPartitionOffset);
                }
                do
                {
                    Thread.Sleep(2500);
                    try
                    {
                        prd.BeginTransaction();
                        for (int j = 0; j < 2; j++)
                        {
                            var key = Encoding.UTF8.GetBytes(Guid.NewGuid().ToString("N"));
                            var val = sha512.ComputeHash(key);
                            var msg = new Message<byte[], byte[]>
                            {
                                Key = key,
                                Value = val
                            };
                            prd.Produce("loli-con", msg, printReport);
                        }
                        prd.CommitTransaction(defaultTimeSpan);
                    }
                    catch(ProduceException<string, string> e)
                    {
                        prd.AbortTransaction(defaultTimeSpan);
                    }
                } while (++i < 100);
            }
        }
    }
}
```

## Additional Info

- **OS**: Windows 10
- **Kafka**: 2.3.0
- **Nuget**: 1.4.0

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
yes, that's expected. behind the scenes, every commit or abort places a "marker message" in the log, and these are never exposed by the consumer.

**Comment by gelihu** [comment]
I think this has implication on the stats of the consumer: reported rxmsgs = 2 * actual rxmsgs ??

**Comment by mhowlett** [comment]
quickly looking at the code, i believe rxmsgs reflects just the number of messages delivered to the consumer. there's certainly no reason for reported to equal 2x actual, if it did differ it would be by the number of txn control messages (but i don't think it does differ).

**Comment by gelihu** [comment]
I am referring to `rxmsgs` field of [top level metrics](https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md#top-level) of a consumer type client. Same is happening with `rxmsgs` with [partition metrics](https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md#partitions). However, producer type client stats are accurate.

Client Version: 1.4.0

**Comment by mhowlett** [comment]
this is only an issue when transactions are in use?

**Comment by gelihu** [comment]
Yup

**Comment by mhowlett** [comment]
Can you open a new issue for this so we can track it separately?
