### ISSUE TITLE
AvroGen created invalid .cs file for nullable decimal type field

### ISSUE THREAD

**Issue by AlexWFBOS** [confluentinc/confluent-kafka-dotnet#1257]
Description
===========
I was using the apache avro 1.9.2 dotnet tool to generate the cs files. There is a nullable logical type 'decimal' in my schema file. The cs file generated has an error as follows.

How to reproduce
================
My schema file is like this:
{
          "name": "Previous",
          "type":
          [
            {
              "type": "bytes",
              "logicalType": "decimal",
              "precision": 19,
              "scale": 4
            },
            "null"
          ]
        }
The cs file created has an error:
case 1: this.Previous = (System.Nullable`1[Avro.AvroDecimal])fieldValue; break;

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [X] Critical issue.

**Comment by mhowlett** [comment]
This is an avro issue, you should open an issue with that project. Now that Schema Registry supports protobuf and json, i'd recommend you use one of these serialization formats if possible as the implementations in .net are more mature.
