### ISSUE TITLE
ProtobufSerializer produces reference subject names which contain slashes

### ISSUE THREAD

**Issue by m-martino** [confluentinc/confluent-kafka-dotnet#1258]
The situation is that I have a proto file `foo1.proto` which imports another file in a subfolder `Protolib/foo2.proto`. I then use Grpc.Tools to generate messages from these and would like to produce these to Kafka in protobuf format using a schema registry. The problem comes in registering the schemata via the ProtobufSerializer. In my case the serialiser tries to register the schema in `/subjects/foo1.proto/versions` (which is OK) and the dependency in `/subjects/protolib/foo2.proto/versions` (which causes a 404 error in the registry). 

An example project is here: [ProtobufProducerError.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/4522827/ProtobufProducerError.zip)

It seems that in ProtobufSerializer there is no way to modify the ReferenceSubjectNameStrategy, which at the moment just uses the FileDescriptor.Name, and can contain `/`. Are there are plans to extend the strategies available? Ideally, it would be great to be able to set a custom subject for messages and their references.

**Comment by mhowlett** [comment]
there's no way to provide custom naming strategies yet, I planned to add it as needed (taking this issue as a +1). It's easy to implement, the main thing to decide is whether or not to make builder classes for the serializer / deserializers to specify the delegates (going overboard?), or allow the delegate to be set directly in the config.

and yeah, the default reference subject name is obviously a problem here. This could be fixed by passing just the filename, not the path from the serializer, or adjusting the default reference subject name strategy to be path aware. neither seems ideal. We should probably do whatever the java case does.

**Comment by edenhill** [comment]
Is it perhaps sufficient to properly url-encode the subject name?

**Comment by mhowlett** [comment]
doh, yes, of course. i'll check what the java implementation does though still. probably this.

**Comment by m-martino** [comment]
As an added point, I also have protos which have the same name, but exist in different packages, which is also why I was asking about the most flexible option (in the back of my mind I was thinking about something like using a fully qualified name). Of course, there is an easy way around this by just renaming the files, but I thought I'd mention it.

**Comment by m-martino** [comment]
I noticed that this problem is also stopping me from using protobuf well-known types like Timestamp, which is would be great. Is there an ETA for this fix?

**Comment by mhowlett** [comment]
If you want to help push this along, the first step is to work out what the java serdes do (do they url encode?). if so, the fix will be very easy, and the second thing to do is open a PR, which i can likely merge quickly and do a release. juggling with a few other high priority things ...

**Comment by m-martino** [comment]
Sure, I'll have a look at it after the weekend.

**Comment by m-martino** [comment]
I had a look into this and interestingly enough, the java implementation is the same as the .NET one. I experimented anyway with UrlEncode and it didn't work out - it looks at first sight as though there is some decoding going on in the schema registry which causes the schema to not be registered correctly.

**Comment by mhowlett** [comment]
cc @rayokota - any commentary?

**Comment by rayokota** [comment]
The Java client does URL encoding.  I believe the Python client does URL encoding as well.

**Comment by m-martino** [comment]
Then it seems that I oversaw that the Schema normalises the subject names - I was looking at the ReferenceSubjectNameStrategy only. Ok, that is different to the .NET implementation.

**Comment by mhowlett** [comment]
would very happily ok a pr that adds url encoding :-)
or will take care of it myself pretty soon.

**Comment by chrisdginn** [comment]
Any idea when this will be released.  I'm now running into this issue as well.  Thanks!

**Comment by mhowlett** [comment]
next couple of days.

**Comment by mhowlett** [comment]
this should be resolved in v1.4.3, please re-open if the problem persists.

**Comment by chrisdginn** [comment]
Just tested it.  Looks like it's working now.

**Comment by mhowlett** [comment]
awesome, thanks!

**Comment by m-martino** [comment]
Thanks! Sorry I didn't get onto it - was a bit snowed under at my end.

**Comment by zzztimbo** [comment]
>  I believe the Python client does URL encoding as well.

I'm not sure about that.
https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/schema_registry/__init__.py#L89

**Comment by CTCC1** [comment]
> > I believe the Python client does URL encoding as well.
> 
> I'm not sure about that.
> 
> https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/schema_registry/__init__.py#L89

Just for the record: For python, the default strategy function itself doesn't take care of URL encode, but the schema registry client does. See https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/schema_registry/schema_registry_client.py#L337
