### ISSUE TITLE
Broker : Request timed out when Commit

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1260]
Description
===========

Error "Broker: Request timed out" when Commit offset

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.2.2 ] Confluent.Kafka nuget version.
 - [0.11.6 ] Confluent.Kafka.Avro nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ RedHat] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ x] Critical issue.

I have a Consumer consumming messages very fast, it is ignoring a lot of messages as it only look for specific data. Means the consumer Handler is returning almost inmediatly and Commit is called just after.
AutoCommit is set to false.

code basically look like:

```
while(!cancellationToken.IsCancellationRequested)
{
  var msg = consumer.Consume( cancellationToken );
  if (msg == null || msg.IsPartitionEOF || cancellationToken.IsCancellationRequested)
    continue;

  Handle(msg.Value);

 consumer.Commit(msg)
}

```

Problem is after some time running and commiting message very often I receive Exception:

KafkaException : Broker: Request timed out

It is raised when calling Commit(msg), looking stack trace exception is generated in SafeKafkaHandler.cs, method Commit(IEnumerable<TopicPartitionOffset> offset), in this piece of code:

```
var errorCode = Librdkafka.event_error(rkev);
if (errorCode != ErrorCode.NoError)
            {
                var errorString = Librdkafka.event_error_string(rkev);
                Librdkafka.event_destroy(rkev);
                throw new KafkaException(CreatePossiblyFatalError(errorCode, errorString));
            }
```
(see: https://github.com/confluentinc/confluent-kafka-dotnet/blob/0936f779acd9e21f6091510985ad2c0cccc1642a/src/Confluent.Kafka/Impl/SafeKafkaHandle.cs#L739)

Message is not commited and consumer stopped.

How can I deal with this error ? Why is the cause ? if it is due to some network latency, there is some workaround on it ?
It is safe to ignore exception and retry Commit() ?

**Comment by mhowlett** [comment]
The broker didn't respond to the commit request within the timeout period (without checking, pretty sure this is == `SocketTimeoutMs`). If it's a recurring problem, my first step for me would be to look at the broker logs for clues. Yes it's safe to retry the `Commit`.

**Comment by alfhv** [comment]
I think that reach SocketTimeoutMs is almost impossible in my case, I have a very fast consumer doing only in memory calculations, here sample code and logs:


```
while(!cancellationToken.IsCancellationRequested)
{
  var msg = consumer.Consume( cancellationToken );
  if (msg == null || msg.IsPartitionEOF || cancellationToken.IsCancellationRequested)
    continue;
 
  LogInfo("handle message");
  Handle(msg.Value);
 
 LogInfo($"committing message {consumeResult.Offset.Value}");
 consumer.Commit(msg)
 LogInfo($"finish with message {consumeResult.Offset.Value}");
}
```

logs:
2020-04-25T15:21:15.3373342+02:00  [INF]  handle message (f9d5e10f)
2020-04-25T15:21:15.3373665+02:00  [INF]  committing message 100610 (b86a7a76)
2020-04-25T15:21:15.3434776+02:00  [INF]  finish with message 100610 (7d6b5a28)
// ok
2020-04-25T15:21:15.3438590+02:00  [INF]  handle message (f9d5e10f)
2020-04-25T15:21:15.3438728+02:00  [INF]  committing message 100611 (49a91cf1)
2020-04-25T15:21:15.3626073+02:00  [INF]  finish with message 100611 (8fd4fefb)
// ok
2020-04-25T15:21:15.3630248+02:00  [INF]  handle message (f9d5e10f)
2020-04-25T15:21:15.3630583+02:00  [INF]  committing message 100612 (0c37a20f)
// Broker: Request timed out error here trying to commit

**Comment by mhowlett** [comment]
how long does it take to get the request timed out error after the commit that failed?

**Comment by alfhv** [comment]
I think I will go with this solution, seems deal with fast processing time, what do you think ??

https://docs.confluent.io/current/clients/dotnet.html#store-offsets

**Comment by mhowlett** [comment]
yes, store offsets is the best way to achieve at least once semantics.
