### ISSUE TITLE
System.UriFormatException when produce messages to Kafka from  CLR assembly hosted in sql server

### ISSUE THREAD

**Issue by AliBaghernejad** [confluentinc/confluent-kafka-dotnet#1262]
Currently, depending on our requirements we want to produce Kafka message from CLR integrated assembly hosted on the SQL server.
I know When working with stream data in the Kafka ecosystem you have different or even better approaches to produce messages/events into topics. ( Kafka Connect, KSQL,...).

The process of creating assembly and the related stored procedures is successful
`CREATE ASSEMBLY KafkaMessaging
AUTHORIZATION dbo
FROM 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\KafkaCLR.dll'
WITH PERMISSION_SET = UNSAFE
GO

CREATE PROCEDURE Produce
    (
        @topicname NVARCHAR(100) NOT NULL,
        @message NVARCHAR(3000) NOT NULL
    )
AS
EXTERNAL NAME KafkaMessaging.[KafkaCLR.StoredProcedures].ProduceMessage;
.`
**ProduceMessage** is a C# .Net method that creates a producer via a producer builder and produces messages through that. 

When calling the **produce** stored procedure  from SQL server, we got an error message like this:

Msg 6522, Level 16, State 1, Procedure produce, Line 0 [Batch Start Line 20]
A .NET Framework error occurred during the execution of user-defined routine or aggregate "produce": 
System.UriFormatException: Invalid URI: The URI is empty.
System.UriFormatException: 
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
   at Confluent.Kafka.ProducerBuilder`2.Build()
   at KafkaCLR.StoredProcedures.ProduceMessage(SqlChars topicName, SqlChars message)

It seems the exception comes from Initialize method of librdkafka due to  the **EscapedCodeBase property of assembly **  that is empty.

[https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Impl/LibRdKafka.cs](url)

How to reproduce
================
Create Clr assembly that wraps a Kafka producer inside.
Deploy .dd file into SQL server instance and make sure all dependencies loaded correctly.
create the required stored procedure for the equivalent CLR method.
Execute the stored procedure cause an exception.

Confluent.Kafka nuget version: 1.4.0.0
Apache Kafka version: 2.4
Operating system: Windows 10

**Comment by mhowlett** [comment]
`Confluent.Kafka` depends on the unmanaged librdkafka library. The error you're seeing is in the code that's loading that. it seems the issues is early - at the point when it's trying to work out the path of the `Confluent.Kafka` assembly, before it even attempts to load librdkafka.

This is a scenario we haven't tested. There's a good chance that because of the native dependency we won't be able to make it work here (but i don't know, i haven't looked into it).

**Comment by jidexl21** [comment]
I noticed there is a provision to load librdkafka manually using the Library.Load("path/to/dll") this fixed the issue. View the kafka [Documentation](https://docs.confluent.io/current/clients/confluent-kafka-dotnet/api/Confluent.Kafka.Library.html#Confluent_Kafka_Library_Load_System_String_l)
