### ISSUE TITLE
What is the right way to setup the consumer without a group?

### ISSUE THREAD

**Issue by quixoticaxis** [confluentinc/confluent-kafka-dotnet#1263]
I'm currently trying to setup the consumer that reads the topic from the start (all of the partitions).
What is the right way to setup it using the Confluent.Kafka client?

I'm currently using
```csharp
new ConsumerConfig
{
    BootstrapServers = _configuration.BootstrapServers,
    AutoOffsetReset = AutoOffsetReset.Earliest,
    EnableAutoCommit = false,
    GroupId = Guid.NewGuid().ToString() // null or string.Empty do not work
};
// ...
consumer.Subscribe(topicName);
```
but it creates "__consumer_offsets" topic in the cluster and writes to it (I believe it writes at least the name of the group).
Is there any way to use the consumer without a group (as in this particular service I would always have a single consumer that reads everything)?

According to [this issue](https://github.com/confluentinc/confluent-kafka-python/issues/250) I can try using `Assign` instead of the `Subscribe` call, but the topic "__consumer_offsets" still gets created.

Any help is much appreciated.

**Comment by mhowlett** [comment]
`__consumer_offsets` is an internal detail of Kafka. I don't know off the top of my head exactly when it gets created, but it's existence isn't anything to worry about. Do you see any messages in it? Unless you're committing offsets, there shouldn't be.

`Assign` requires a list of `TopicPartition`s - you need to know how many partitions there are if you want to consume from them all. If you don't want to specify this manually, you could use `AdminClient.GetMetadata`. But if you just have one consumer, you probably don't need more than one partition.

Finally, i'm not sure what downside there is to creating a group. It will disappear when you shutdown your consumer automatically and if you're not committing offsets, you won't be storing any data on the broker.

**Comment by quixoticaxis** [comment]
There are some messages in the `__consumer_offsets` even though I explicitely create a consumer that does not commit anything, so it seems like the the creation of a group produces a message into it. It's not a big issue for me anyway, but I'm still interested whether using a random group name is ok.

**Comment by mhowlett** [comment]
`__consumer_offsets` is used to store offsets only - creating a consumer group won't put any messages in it (unless i'm missing something important... always a possibility, but i don't think so here). If you're still suspicious that using a random group name is ok, use a fixed one - there's no downside since you're not relying on any of the group functionality.

**Comment by quixoticaxis** [comment]
Ok, thank you.
