### ISSUE TITLE
Local: Value deserialization error on classes generated by AvroGen

### ISSUE THREAD

**Issue by rafamerlin** [confluentinc/confluent-kafka-dotnet#1265]
I'm consuming messages generated in Elixir and using the service registry.

When I tried to consume the messages I got this error and checked that it would give me more details like:
```
Schema mismatch.Reader: {
    "type": "record",
    "name": "TestKey",
    "namespace": "bla.public.testnamespace",
    "fields": [{
            "name": "test",
            "type": {
                "type": "record",
                "name": "TestRecord",
                "namespace": "bla.public.testnamespace",
                "fields": [{
                        "name": "uuid",
                        "type": "string"
                    }
                ]
            }
        }
    ]
}, writer: {
    "type": [{
            "type": "record",
            "name": "TestKey",
            "namespace": "bla.public.testnamespace",
            "fields": [{
                    "name": "test",
                    "type": {
                        "type": "record",
                        "name": "TestRecord",
                        "namespace": "bla.public.testnamespace",
                        "fields": [{
                                "name": "uuid",
                                "type": "string"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
```

If I copy the content of the Writer and add it exactly as is to the avsc file and generate the this class again and check the schema inside the class, instead of having the outermost `type` array like the writer has it will go back to exactly the schema the reader had before.

This causes it to fail.
If I manually get the class that was generated and replace its schema the writer's schema to it manually it goes past that error and then I get stuck in not finding the assembly possibly because the .public. is a protected key in dotnet and changes to @public when generating the classes.

**Comment by mhowlett** [comment]
this seems to be a problem with avrogen - please open an issue on the avro project or consider using protobuf or json, which have more mature implementations in .net than avro.
