### ISSUE TITLE
Feature Request: Kafka Streams

### ISSUE THREAD

**Issue by bobcat1506** [confluentinc/confluent-kafka-dotnet#1266]
We are a .NET Core shop and are starting to use Kafka.  We would really like to code Kafka Stream applications using our native tools and skillsets.

**Comment by mhowlett** [comment]
thanks for request. please refer to and add your thumbs up to this issue: https://github.com/confluentinc/confluent-kafka-dotnet/issues/344 and you might like to follow this project: https://github.com/LGouellec/kafka-streams-dotnet
