### ISSUE TITLE
Error Local: Erroneous state

### ISSUE THREAD

**Issue by danneisollentuna** [confluentinc/confluent-kafka-dotnet#1268]
Description
===========
I am trying to produce a message to our Kafka cluster from a kafka client I have just created. It is secured over SSL. But I recieve the following error: 

"Confluent.Kafka.ProduceException`2[System.String,System.String]: Local: Erroneous state at Confluent.Kafka.Producer`2.Produce(TopicPartition topicPartition, Message`2 message, Action`1 deliveryHandler) at"

How to reproduce
================
This is the config I have:
            var conf = new ProducerConfig
            {
                BootstrapServers = _kafkaModel.UrlAndPort,
                SecurityProtocol = SecurityProtocol.Ssl,
                EnableIdempotence = true,
                TransactionalId = Guid.NewGuid().ToString(),
                EnableDeliveryReports = true,
                SslCertificateLocation = _kafkaModel.SslCertificateLocation,
                SslKeyLocation = _kafkaModel.SslKeyLocation,
                SslKeyPassword = _kafkaModel.SslKeyPassword
            };

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
My guess is that you have not successfully called InitTransactions(), or BeginTransaction() prior to producing.

**Comment by danneisollentuna** [comment]
Okay. Interesting. I have not looked at that. I will definitly give it a
try!

tors 30 apr. 2020 kl. 09:39 skrev Magnus Edenhill <notifications@github.com

**Comment by edenhill** [comment]
The transactional semantics are quite strict and requires a bit of effort on the application side.
If you don't need transactions I recommend that you just enable idempotence.
See the transaction example here: https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/Transactions

**Comment by danneisollentuna** [comment]
Turns out the certificates were incorrect. Now we are able to produce messages to Kafka =). Unfortunately, there is one config property we cannot get right. EnableIdempotence we set to true, and then no messages are produced. The callback function handler never gets hit. I do not find any logs. In the Kafka cluster we do not see anything either. How can we add more logging for IProducer.Produce?

**Comment by edenhill** [comment]
Try setting Debug to `broker,eos,msg`.

:+1: on your username
/mangeinorrtalje

**Comment by danneisollentuna** [comment]
where can I find those logs? Will they be put on the client in a file?

**Comment by mhowlett** [comment]
they're written the console if you don't set a log handler. you can set a log handler with `SetLogHandler` on the builder class.

**Comment by danneisollentuna** [comment]
Good stuff! Thank you guys.
