### ISSUE TITLE
Consumer methods using ICollection parameters instead of IEnumerable

### ISSUE THREAD

**Issue by MrGlenThomas** [confluentinc/confluent-kafka-dotnet#127]
I have just noticed that most of the methods of the Consumer<TKey, TValue> class take ICollection parameters. I think it would make a lot of cases simpler to use IEnumerable instead, otherwise having to convert IEnumerables (e.g. arrays) to ICollection types and the internal implementation should not require ICollection...

```
public void SubscribeTopics(Consumer<long, string> consumer, IEnumerable<string> topics)
{
    consumer.Subscribe(topics.ToList());
}
```

**Comment by mhowlett** [comment]
Sounds good to me (though maybe there is something I'm missing). This decision was inherited from rdkafka-dotnet - I've not considered it in any depth.

`ICollection` inherits from `IEnumerable` so we don't need to worry about breaking the API.

**Comment by treziac** [comment]
Some API were changed from ICollection to IEnumerable but all weren't modified so yes, we will have to change this

**Comment by mhowlett** [comment]
closing this as there is PR #128 for it now.
