### ISSUE TITLE
Kafka.System.Exception: Could not load file or assembly Confluent.Kafka or Confluent.SchemaRegistry

### ISSUE THREAD

**Issue by harshpatel94** [confluentinc/confluent-kafka-dotnet#1270]
Description
===========
I have recently upgraded Confluent.Kafka and Confluent.SchemaRegistry, librdkafka to 1.4.0. As soon as I build the project it is working successfully locally in Debug mode. It starts to throw an error with following error. 

System.IO.FileLoadException: Could not load file or assembly 'Confluent.SchemaRegistry, Version=1.3.0.0, Culture=neutral, PublicKeyToken=34ce5df5fa699c09' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I saw in project.assets.json and Nuget UI from VS19 where 
 Confluent.SchemaRegistry.Serde is at 1.3.0 and which had dependency of 1.3.0 versions it seems that's where it fails with above error while Building Producer. I tried to find what actually is looking for version 1.3.0 and I am suspecting Confluent.SchemaRegistry.Serde version 1.3.0 is culprit here. However I am beginner to this, not sure. 

I tried to minimize the error by putting following application Binding Redirects at .config level which helped but which is according to me is Little Hack. 

`    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Confluent.Kafka" publicKeyToken="12c514ca49093d1e" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-1.4.0.0" newVersion="1.4.0.0"/>
      </dependentAssembly>
    </assemblyBinding>  
`

`    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Confluent.SchemaRegistry" publicKeyToken="34ce5df5fa699c09" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-1.4.0.0" newVersion="1.4.0.0"/>
      </dependentAssembly>
    </assemblyBinding>`

My questions are, 
1) Is Confluent.SchemaRegistry.Serde required with new Confluent.Kafka and Confluent.SchemaRegistry v1.4.0? 
2) Why discrepancy between locally and on server? 

As being naive to this concept, guide me over this. 

How to reproduce
================
Upgrade NuGet Packages Confluent

Checklist
=========
**All Nuget packages:** 
Confluent.Kafka = v1.4.0
librdkafka.redist = v1.4.0
Confluent.SchemaRegistry = v1.4.0
Confluent.SchemaRegistry.Serdes = v1.3.0 (which NuGet UI shows as stable version)
.NET Framework = v4.7.2
Used outer .bat file to generate POCO classes. 
Server Box = Win2k8 R2 Server 64-bit (installed till .NET v4.7.2 compatibility)

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [X] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
`Confluent.SchemaRegistry.Serdes` has effectively become `Confluent.SchemaRegistry.Serdes.Avro` and there is also `Confluent.SchemaRegistry.Serdes.Protobuf` and `Confluent.SchemaRegistry.Serdes.Json`

see: https://github.com/confluentinc/confluent-kafka-dotnet#referencing

**Comment by mhowlett** [comment]
note: there are some minor errors in the README.md related to this that have already been fixed on the 1.4.x branch and will be on master with the release of 1.4.2 in a few days.

**Comment by harshpatel94** [comment]
Thank you @mhowlett for your prompt response. I will add `Confluent.SchemaRegistry.Serdes.Avro` to my project via NuGet. Another question, to add this at Nuget level, do I have to remove any other Nuget package to remove conflict? 

For example, since you introduced `Confluent.SchemaRegistry.Serdes.Avro`, does that mean I should remove either `Confluent.Apache.Avro` or `Confluent.SchemaRegistry` ? 

Asking out of curiosity. Thanks.

**Comment by mhowlett** [comment]
you shouldn't need to reference Confluent.SchemaRegistry explicitly - it will be included transitively by way of referencing Confluent.SchemaRegistry.Serdes.Avro. Same with Confluent.Apache.Avro, except in this case, this is no longer actually the correct dependency - it's been swapped out for Apache.Avro in > v1.4.0. Just reference Confluent.SchemaRegistry.Serdes.Avro.

**Comment by Alpesh1984909090** [comment]
@mhowlett I'm facing some weird issue. My application is working fine with the .net framework 4.6.2 but the same code is giving an error in .net core 6.0 Local: Value serialization error
 ---> Confluent.SchemaRegistry.SchemaRegistryException: ; error code: -1" 

Is there any changes between these two libraries? As you mentioned I'm just referring "Confluent.SchemaRegistry.Serdes.Avro." in .net core as other required assemblies are already there as dependency.
