### ISSUE TITLE
Consumer subscribes to a single partition

### ISSUE THREAD

**Issue by alexandery** [confluentinc/confluent-kafka-dotnet#1276]
Description
===========
Working against Confluent Cloud instance.

Starting a test app with a consumer group that I used a while ago results in a consumer being assigned a single partition (#6 out of 12 partitions in a topic). If I change the consumer group name to some new, random value - my consumer instance gets assigned to all 12 partitions. Switching back to the original consumer group name I observe the same issue of getting same (#6) partition assigned.

Sample code is pretty much what you've got in examples. Here it is:

```c#
var Consumer = new ConsumerBuilder<string, byte[]>(GetConsumerConfig())
	.SetKeyDeserializer(Deserializers.Utf8)
	.SetValueDeserializer(Deserializers.ByteArray)
	.SetPartitionsAssignedHandler((c, partitions) =>
	{
		Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}]");
	})
	.Build();

// Topics is IList<string> with a single topic that has 12 partitions
Consumer.Subscribe(Topics);

while (!cancellationToken.IsCancellationRequested)
{
	ConsumeResult<string, byte[]> result = null;
	try
	{
		result = Consumer.Consume(cancellationToken);
		if (!result.IsPartitionEOF)
		{
			await InvokeHandler(result).ConfigureAwait(false);
		}
	}
	catch (ConsumeException e)
	{
		logger.LogError($"ConsumeException: {e.Message}");
	}
	catch (OperationCanceledException)
	{
		logger.LogTrace("Message consumption cancelled");
	}
	catch (Exception ex)
	{
		logger.LogError($"Unhandled exception while consuming message. Error message: {ex.Message}. Stack trace: {ex.StackTrace}");
	}
	finally
	{
		if (result != null && !result.IsPartitionEOF)
		{			
			Consumer.Commit(result);
		}
	}
}

```

Checklist
=========

Please provide the following information:
 - [ x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ 1.4.2] Confluent.Kafka nuget version.
 - [Confluent Cloud ] Apache Kafka version.
 - [Win 10 ] Operating system.

**Comment by mhowlett** [comment]
you're 100% sure you don't have other consumers running in the same group? you can check with the `kafka-consumer-groups` command in the kafka distribution:

```
./bin/kafka-consumer-groups.sh --bootstrap-server <bootstrap-server> --describe --group <group name>
```

oh, you'll need to set credentials with `--command-config` as well. i know that's not the most convenient thing to use from windows, but hopefully doable.

i don't know how this could be happening otherwise, so the above is the first thing to check. the next thing is to provide us `Debug=all` logs, but i suspect they'll just suggest there are other consumers in the group.

**Comment by alexandery** [comment]
@mhowlett Hi Matt. Yes, I've been looking into that earlier this morning and was going to close this issue even though I cannot find any other consumers, but my Confluent Cloud Consumer page shows that I've got one consumer in there, which seems to consume all messages. So clearly there is something running somewhere and I need to hunt that down.
