### ISSUE TITLE
consumer writing suggestion

### ISSUE THREAD

**Issue by liuyl1992** [confluentinc/confluent-kafka-dotnet#1277]
Description
===========
why not change this writing
```csharp
 consumer.Consume((cts.Token)
```
 to consumer.Consume+={function...} as rabbitmq for receive event
" while (true)" not elegant and can block other operations

**Comment by mhowlett** [comment]
C# events don't play nicely with `async` functions is an important reason we counted that out. v0.11.6 and earlier actually did use the C# event language feature, but we changed the API for the above reason and also to closely match the Java API. In the future, we will probably add a more sophisticated API that allows complex dispatching depending on message schema / topic. There is a bit of design work in that (considering wider range of possible use cases, some of which we might not have thought of), and to start with we went with a more straightforward API. This also has the advantage of it's easy to reason about what thread things are happening on.

**Comment by liuyl1992** [comment]
> C# events don't play nicely with functions is an important reason we counted that out. v0.11.6 and earlier actually did use the C# event language feature, but we changed the API for the above reason and also to closely match the Java API. In the future, we will probably add a more sophisticated API that allows complex dispatching depending on message schema / topic. There is a bit of design work in that (considering wider range of possible use cases, some of which we might not have thought of), and to start with we went with a more straightforward API. This also has the advantage of it's easy to reason about what thread things are happening on.`async`

i understand this.
Hope this project to inspire you [cap kafka](https://github.com/dotnetcore/CAP/tree/master/src/DotNetCore.CAP.Kafka)

**Comment by liuyl1992** [comment]
will DependencyInjection of netcore be supported in the future

**Comment by mhowlett** [comment]
yeah, this would definitely be a useful thing to provide out of the box, though the complexity of the configuration, desire to have a good API in contexts where you don't want dependency injection, and desire for consistency between the consumer (typically want to use in non DI context) and producer (often want in DI context) make it something that needs thought.

also, a DI wrapper is pretty trivial to make yourself. i do this all the time, and each time it's tailored for the task at hand. it is almost never a 1:1 mapping to the confluent.kafka producer api, and the code structure is more encapsulated than if the confluent producer was DI pluggable. In fact, i think the current api probably pushes you towards better code (sometimes i don't like DI - I think it's over used). But yes, something DI pluggable out of the box could be something we want to add.
