### ISSUE TITLE
Having trouble putting some values into configuration

### ISSUE THREAD

**Issue by cculver** [confluentinc/confluent-kafka-dotnet#1281]
I need a way to set some settings on the ProducerConfig and ConsumerConfig objects that don't appear to be available in the c# library, but are available in the librdkafka base library. Below is a partial recommended configuration for working with Kafka on Azure found [here](https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/CONFIGURATION.md). We are having trouble locating the corresponding fields in bold.

Producers:
socket.keepalive.enable: true
metadata.max.age.ms: 180000
**connections.max.idle.ms**: 180000
**max.request.size**: 1000000
**metadata.max.idle.ms**: 180000

Consumers:
socket.keepalive.enable: true
metadata.max.age.ms: 180000
**connections.max.idle.ms**: 180000
heartbeat.interval.ms: 3000
session.timeout.ms: 30000

I presume there may be a way to add ad-hoc settings to the kafka library. Is there a method to do that? If not, what do you suggest we do here?

**Comment by Rytisk** [comment]
If you look closely at ProducerBuilder (or ConsumerBuilder) constructors, you can see, that it accepts IEnumerable<KeyValuePair<string, string>>

So you could pass your configurations like this: 

```
var producer = new ProducerBuilder<string, string>(new [] 
{
    new KeyValuePair<string, string>("connections.max.idle.ms", "10000000")
}).Build();
```

**Comment by cculver** [comment]
Thanks, that helps.

**Comment by edenhill** [comment]
`connections.max.idle.ms` is not a confluent-kafka-dotnet/librdkafka configuration property, it only exists in the Java clients.

**Comment by cculver** [comment]
So, I continued as suggested and attempted to use the constructor to add max.request.size and metadata.max.idle.ms to a producer. This threw an InvalidOperationException saying: No such configuration property: "max.request.size"

I assume it will do this for metadata.max.idle.ms as well. Any ideas here?

**Comment by edenhill** [comment]
See the full list of configuration properties here:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by cculver** [comment]
Right, sorry for the confusion.
