### ISSUE TITLE
Need consume list of records

### ISSUE THREAD

**Issue by LGouellec** [confluentinc/confluent-kafka-dotnet#1283]
Description
===========
Calling consumer.Consume will return at most one message. Would it be possible to return a collection of records like Java API Implementation ?
I believe you use internal queue, so maybe it's not lot of work. 
I need this feature to process a list of records for each poll request. Would that be possible for you?

Checklist
=========
 - [x] Confluent.Kafka nuget version (all versions)

**Comment by mhowlett** [comment]
no, we don't plan to implement this - if you really need messages in batches, just call consume with a timeout of 0 for as many items as you want in a batch or until you get `null`. We have discussed this and we didn't think of any scenario in which the batch api would be more appropriate than the message by message api. Feel free to describe your scenario in more detail.
