### ISSUE TITLE
Confluent.SchemaRegistry.Serdes nuget version 1.4.2 missing

### ISSUE THREAD

**Issue by stefan-benjamin** [confluentinc/confluent-kafka-dotnet#1284]
Description
===========
It seems that nuget package version 1.4.2 for Confluent.SchemaRegistry.Serdes has not been published.

How to reproduce
================
I have a .Net framework 4.7.2 application consuming messages with dynamic avro schema (without model classes - using GenericRecord). To retrieve the schema, I am using a CachedSchemaRegistryClient.

My client initialization is:

`using( var consumer = new ConsumerBuilder<GenericRecord, GenericRecord>( consumerConfig )
            .SetKeyDeserializer( new AvroDeserializer<GenericRecord>( schemaRegistry ).AsSyncOverAsync() )
            .SetValueDeserializer( new AvroDeserializer<GenericRecord>( schemaRegistry ).AsSyncOverAsync() )`

When a message is consumed, `ConsumeException` is thrown, as seen in the image below:

![image](https://user-images.githubusercontent.com/17021979/81787391-43030a00-9501-11ea-8711-e54403122392.png)

Confluent.Kafka nuget version: **1.4.2 (newest)**
Confluent.SchemaRegistry version: **1.4.2 (newest)**
Confluent.SchemaRegistry.Serdes version: **1.3.0 (newest)**
Confluent.Apache.Avro nuget version: 1.7.7.7 (newest)

**Comment by mhowlett** [comment]
There is no `Confluent.SchemaRegistry.Serdes` package. The Avro serdes have moved to `Confluent.SchemaRegistry.Serdes.Avro`, and there are also packages for protobuf and json. This is to avoid unnecessary dependencies (e.g. if you are using avro, you don't want protobuf dependencies).

**Comment by stefan-benjamin** [comment]
Thank you @mhowlett, this answered my question. Closing the issue 👍
