### ISSUE TITLE
unmanaged resources should all get released if you don't call `Dispose` - they are all wrapped by SafeHandles which have finalizers that call the `ReleaseHandle` method which we override to do the right thing for all relevant cases.

### ISSUE THREAD

**Issue by danneisollentuna** [confluentinc/confluent-kafka-dotnet#1285]
unmanaged resources should all get released if you don't call `Dispose` - they are all wrapped by SafeHandles which have finalizers that call the `ReleaseHandle` method which we override to do the right thing for all relevant cases.

That said, tbh I haven't explicitly tested the above. A good way to verify it would be to see how long a group rebalance takes after exiting a program that's using a `Consumer` without disposing it. If the rebalance takes less than `session.timeout.ms` (defaults to 30s), then the consumer resources must have been freed because this indicates the failure detection protocol didn't come into play. This would verify the mechanism we're using is working correctly (same approach is used for producers / topics / config unmanaged resources).

_Originally posted by @mhowlett in https://github.com/confluentinc/confluent-kafka-dotnet/issues/223#issuecomment-308276958_

**Comment by danneisollentuna** [comment]
Does the text imply that we do not need to dispose the IProducer in any way? I recently tried using it in a using statement, which did not work. It got disposed before the call was made. Another thought II had was to make the IProducer a singleton for our application. Can it live "forever"?

**Comment by mhowlett** [comment]
i can't immediately think of any significant consequences of not disposing the producer before exiting your application. as a general rule though, you should have a clean shutdown sequence. it's just safer - you don't know what you don't know, and things might change.

are you writing an asp.net application?
