### ISSUE TITLE
Memory Leak with 1.4.2 version with CancellationToken

### ISSUE THREAD

**Issue by msoler8785** [confluentinc/confluent-kafka-dotnet#1287]
Description
===========
When you call ProduceAsync with a CancellationToken it fails to dispose the register CancellationTokenRegister object.

Appears to be a regression of this issue:  
[https://github.com/confluentinc/confluent-kafka-dotnet/issues/638](https://github.com/confluentinc/confluent-kafka-dotnet/issues/638)

How to reproduce
================
Call ProduceAsync 1000s time and you will see the memory go up as the CancellationTokenRegister is not disposed.

In source code Producer.cs
Line 728: cancellationToken.Register(() => handler.TrySetCanceled());
[https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Producer.cs#L728](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Producer.cs#L728)

You are not disposing the Registered object.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [X] Critical issue.

**Comment by mhowlett** [comment]
yes, you're very right - thanks the reporting.

**Comment by mhowlett** [comment]
this should be resolved by #1289, which will be included in v1.4.3. please reopen if this is not the case.

**Comment by msoler8785** [comment]
Sorry for the delay, but I just got around to testing this and it looks like this worked. Thank you!

**Comment by mhowlett** [comment]
good to hear!
