### ISSUE TITLE
Support for topic auto create in AdminClient

### ISSUE THREAD

**Issue by HenningRoigaard** [confluentinc/confluent-kafka-dotnet#1294]
Description
===========
The AdminClient fails with “Broker: Leader not available” when fetching metadata for a non-existing topic, even though Kafka automatically creates the topic as result of the request. Subsequent requests for metadata succeed. 

Since Kafka considers metadata requests as sufficient to auto create topics, I propose that the IAdminClient implementation should support that scenario and not fail.

A simple solution could be to simply catch LeaderNotAvailable errors and retry. Perhaps with a minor backoff.

How to reproduce
================
I used local docker Kafka with auto create topic enabled and extended the \examples\AdminClient project with another case

```
case "topicmetadata":  
  if (!PrintTopicMetadata(args[0], args[2]))
    PrintTopicMetadata(args[0], args[2]);
  break;
```
where
```
static bool PrintTopicMetadata(string bootstrapServers, string topic)
{
  using (var adminClient = new AdminClientBuilder(new AdminClientConfig { BootstrapServers = bootstrapServers }).Build())
  {
    var metadata = adminClient.GetMetadata(topic, TimeSpan.FromSeconds(5));
    var topicMetadata = metadata.Topics.Single();
    if (topicMetadata.Error.IsError)
    {
      Console.WriteLine(topicMetadata.Error.Reason);
      return false;
    }
    Console.WriteLine($"Topic: {topicMetadata.Topic} {topicMetadata.Error}");
    topicMetadata.Partitions.ForEach(partition =>
    {
      Console.WriteLine($"  Partition: {partition.PartitionId}");
      Console.WriteLine($"    Replicas: {ToString(partition.Replicas)}");
      Console.WriteLine($"    InSyncReplicas: {ToString(partition.InSyncReplicas)}");
    });
    return true;
  }
}
```
I then executed the sample using
```
$ dotnet run localhost:9092 topicmetadata foo
Broker: Leader not available
Topic: foo Success
  Partition: 0
    Replicas: [1]
    InSyncReplicas: [1]
```
which shows the first request failing, and the second succeding

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.  
        Reproduced using local clone of this repo with head 6469519 as well as release 1.3.0
 - [ ] Apache Kafka version.
        Confluent Docker image cp-kafka:5.3.3
 - [ ] Client configuration.
 - [ ] Operating system.
        Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
Topic auto creation is deprecated in favour of the Admin CreateTopics API.

**Comment by HenningRoigaard** [comment]
Just an inquiry: Do you mean that Apache Kafka has decided to deprecate auto topic creation, or only that the client library has decided not to support it?
If the former, could you point me in the direction of documentation?
I found KIP-487 suggesting some level of deprecation (especially on metadata request) in Kafka itself, but it is marked as _Under Discussion_.

**Comment by edenhill** [comment]
AK itself.
I don't have a link to share but it is the general consensus that users should use the Admin API to create topics instead of topic auto creation.
