### ISSUE TITLE
is flush() mandatory ?

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1296]
I'm testing with a producer using Produce() with DeliveryHandler without calling Flush() as it introduce some latency and I want a high performace producer.
I can see the messages arrive to kafka, even without calling Flush().
Is that normal ? it is due to some internal timeouts ?
It is safe to dont call Flush ?
what could be the proper configuration/implementation of a high performance producer ?

**Comment by mhowlett** [comment]
produce calls are buffered before being sent to the brokers. there is no requirement to call flush, but if  you don't and you aren't synchronously producing (which you generally shouldn't be, an exception being awaiting produceasync calls in a highly concurrent scenario such as a web app), there is a risk that exiting your application will leave messages undelivered.
