### ISSUE TITLE
No such configuration property: "client.software.name"

### ISSUE THREAD

**Issue by DevTMak** [confluentinc/confluent-kafka-dotnet#1298]
Description
===========

Getting exception - No such configuration property: "client.software.name". 
Going through Confluent.kafka dotnet source code, I found this proerty is by default set to "confluent-kafka-dotnet", and it is hidden in the wrapper for users.

How to reproduce
================
Error while creating instance of ConsumerBuilder using Confluent.Kafka dotnet wrapper. - 
Var Consumer = new ConsumerBuilder<Ignore, String>(config).Build()

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ x] Confluent.Kafka nuget version. - v1.4.3
 - [ x] Apache Kafka version. - v2.4.0
 - [ ] Client configuration.
 - [ ] Operating system. 
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ x] Critical issue.

**Comment by mhowlett** [comment]
`Confluent.Kafka` is almost certainly loading an older version of librdkafka (not the one in the referenced `librdkafka.redist`. do you have an older version of librdkafka installed in a system dir, or anywhere else on your path?

**Comment by edenhill** [comment]
Setting `Debug: "Generic"` will print a log line at client instantiation saying what version of librdkafka it is using.

**Comment by edenhill** [comment]
But.. failing to set client.software.* properties should not be a fatal error to the .NET client, it should ignore these errors.

**Comment by DevTMak** [comment]
@mhowlett - My project has librdkafka v1.4.2 installed. This got updated when I updated Confluent.Kafka to v1.4.3. Not sure how it will be loading an older version.

@edenhill - Where can I set the Debug: "Generic" property? Is this one of the consumer config attribute?

**Comment by mhowlett** [comment]
@DevTMak - you can also use `Library.VersionString` in your code instead.

**Comment by mhowlett** [comment]
@edenhill - I would say `Confluent.Kafka` shouldn't be backwards compatible with earlier versions of librdkafka (simplifies things + no point), so startup should fail for that reason (before it gets to the invalid config problem).

**Comment by DevTMak** [comment]
@mhowlett  Library.VersionString returned v1.2.0; don't know why it was referring to an older version. I reinstalled the librdkafka v1.4.2  package in my project, and it ressolved the issue. 
Appreciate your help.
