### ISSUE TITLE
Manual offset commit issue

### ISSUE THREAD

**Issue by vkmerlin** [confluentinc/confluent-kafka-dotnet#1300]
Description
===========
To make sure that a message has been processed we store offsets manually. A Kafka topic has 60 partitions (customer requirement). Recently it turned out that we have a large number of duplicates. After a research I found that offset is considered to be committed only after the next offset will be committed to the same partition. Otherwise after the partition reassignment messages will be consumed again. 
Committed() method returns the current offset committed. But after the restart an application starts from the last committed message and creates a duplicate if a next one has not been committed.

Today, I've updated Nuget package to the latest version(1.4.3) but the issue persists. 
Do I have a capability to store an offset and avoid waiting a next commitment to the same partition to prevent duplicates?

Aiven Kafka 2.3.1

P.S. 
I made attempts to use various configurations such as:
```
                EnableAutoCommit = false,
                EnableAutoOffsetStore = false
```
```
                EnableAutoCommit = true,
                EnableAutoOffsetStore = false
Without Commit() method.
```
But only 
```
                EnableAutoCommit = true,
                EnableAutoOffsetStore = true
```
configuration allows to avoid duplicates but in this case we can't guarantee the the message will be processed.

Thanks in advance.

How to reproduce
================

```
using System;
using System.Collections.Generic;
using Confluent.Kafka;
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var conf = new ConsumerConfig
            {
                GroupId = "test-consumer-group-VK",
                BootstrapServers = "localhost:9092",
                AutoOffsetReset = AutoOffsetReset.Earliest,
                EnableAutoCommit = false,
                EnableAutoOffsetStore = false
            };
            using (var consumer = new ConsumerBuilder<Ignore, string>(conf)
                .Build())
            {
                consumer.Subscribe("backblaze_smart");

                while (true)
                {
                    try
                    {
                        var result = consumer.Consume(TimeSpan.FromMilliseconds(10));

                        if (result == null || result.IsPartitionEOF)
                        {
                            continue;
                        }

                        consumer.StoreOffset(result.TopicPartitionOffset);
                        consumer.Commit(new List<TopicPartitionOffset>
                        {
                            result.TopicPartitionOffset
                        });

                        var committed = consumer.Committed(new List<TopicPartition>
                            {
                                result.TopicPartitionOffset.TopicPartition
                            },
                            TimeSpan.FromSeconds(10));
                    }
                    catch (ConsumeException e)
                    {
                        Console.WriteLine($"Error occured: {e.Error.Reason}");
                    }
                }
            }
        }
    }
}
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by mhowlett** [comment]
> After a research I found that offset is considered to be committed only after the next offset will be committed to the same partition.

The committed offset is defined to be the offset of the next message to read, not the offset of the last message read. This is a Kafka convention - it's not unique to the .net client.

have a look at the code to see the correct offset logic, e.g. :https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Consumer.cs#L339

**Comment by vkmerlin** [comment]
Thank you, Matt. Just a simple increment but it works and solve the issue.
