### ISSUE TITLE
Exception when I call Assign and Seek juste after

### ISSUE THREAD

**Issue by LGouellec** [confluentinc/confluent-kafka-dotnet#1303]
Description
===========                                               ,
I want assign my consumer to a topic partition (test, 0) and set offset to the beginning for this topicpartition.
When I call Assign and Seek immedialty after, I have an exception with this message : Local: Erroneous state.

My only workaround is called Thread.Sleep(5000) after my assignment. It's works ! but it's not really production ready.

How to reproduce
================
var config = new ConsumerConfig
            {
                GroupId = "test-app",
                BootstrapServers = "192.168.56.1:9092",
                SecurityProtocol = SecurityProtocol.SaslPlaintext,
                SaslMechanism = SaslMechanism.Plain,
                SaslUsername = "admin",
                SaslPassword = "admin",
                Debug = "generic, broker, topic, metadata, consumer"
            };

            var builder = new ConsumerBuilder<string, string>(config);
            using (var consumer = builder.Build())
            {
                var water = consumer.GetWatermarkOffsets(new TopicPartition("test", 0));
                consumer.Assign(new TopicPartition("test", 0));
                // WORK AROUND => Thread.Sleep(5000);
                consumer.Seek(new TopicPartitionOffset("test", 0, water.Low));
                while (true)
                {
                    var r = consumer.Consume(1000);
                }
            }

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version. (1.4.0-RC4)
 - [ X] Apache Kafka version (2.4.0)
 - [X] Client configuration. (cf: code above)
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [X] Critical issue.

**Comment by mhowlett** [comment]
why not assign the consumer to start at the beginning watermark offset (rather than 0). If 0 is not a valid offset, the behavior of the consumer will be determined by the config setting `AutoOffsetReset` - I don't think you want to be explicitly assigning to offset 0 without knowing it is valid first.

I know @edenhill has specific thoughts on the behavior of seek in edge cases like this, but i can't recall exactly what (this is on our radar anyway).

**Comment by LGouellec** [comment]
I start the consumer at the beginning watermark offset  with this code : 
``` csharp
var water = consumer.GetWatermarkOffsets(new TopicPartition("test", 0));
            consumer.Assign(new TopicPartition("test", 0));
            // WORK AROUND => Thread.Sleep(5000);
            consumer.Seek(new TopicPartitionOffset("test", 0, water.Low)); // HERE
```

0 is the partition number, not the offset ..

**Comment by LGouellec** [comment]
My problem is : With Thread.Sleep(5000) between Assign(...) and Seek(..) my code works !
If I remove Thread.Sleep(5000), I have an exception (Local: Erroneous state) when Seek(..)'s called.

I think Assign method is none waiting, and the local state of my consumer is not compatible with Seek's call. That's why a thead.sleep resolve the problem.

Maybe create async/await method for assignment ?

**Comment by mhowlett** [comment]
oh, sorry - assign with `TopicPartitionOffset` (where offset is the low watermark offset), not `TopicPartition`. seek gives you the error you're seeing if the toppar isn't fetching. Calling it immediately on assign evidently means it's in that state. this doesn't seem great behavior, but it is what it is currently (I hope we can change that in the future).

**Comment by mmoron** [comment]
so if I assign like this I don't need to call `Seek(...)` anymore?

```
consumer.Assign(new TopicPartitionOffset("test", 0, Offset.Beginning));
```

**Comment by mhowlett** [comment]
yeah, I believe logical offsets (i.e. `Offset.Beginning`) are valid there. If this doesn't work, you'll need to query watermark offsets (which technically introduces a possibly race condition, though an unlikely one). sorry was answering quickly ...
