### ISSUE TITLE
Property configuration

### ISSUE THREAD

**Issue by robsonrjan** [confluentinc/confluent-kafka-dotnet#1310]
Description
===========

[12:22 PM] Unhandled exception. System.InvalidOperationException: No such configuration property: "client.software.name"
   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
   at Confluent.Kafka.Consumer`2.<>c__DisplayClass69_0.<.ctor>b__3(KeyValuePair`2 kvp)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.Kafka.Consumer`2..ctor(ConsumerBuilder`2 builder)
   at Confluent.Kafka.ConsumerBuilder`2.Build()

on kubernetes container, 

new ConsumerConfig
            {
                Acks = Acks.None,
                GroupId =  DefaultConsumerGroup,
                EnableAutoCommit = AutoCommit,
                FetchWaitMaxMs = FetchWaitMaxMs,
                AutoCommitIntervalMs = AutoCommitIntervalMs,
                StatisticsIntervalMs = StatisticsIntervalMs,
                SocketReceiveBufferBytes = ConsumerBufferInBytes,
                MessageMaxBytes = MessageMaxBytes,
                FetchMaxBytes = MessageMaxBytes,
                BootstrapServers = configuration.Brokers,
                QueuedMaxMessagesKbytes = configuration.QueuedMaxMessagesKbytes,
                AutoOffsetReset = AutoOffsetReset.Earliest
           };

SafeConfigHandle.cs
Method Set, 

Confluent.Kafka nuget version - 1.4
Apache Kafka version - 2.3.1

How to reproduce
================

I couldn't reproduce it locally

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x ] Confluent.Kafka nuget version.
 - [x ] Apache Kafka version.
 - [ x] Client configuration.
 - [x ] Operating system.
 - [x ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
the problem will be that you're somehow referencing a version of librdkafka < 1.4.0.

**Comment by robsonrjan** [comment]
ok, librdkafka < 1.4.0, we rebuild project and works, thanks
