### ISSUE TITLE
Local: Message timed out error when using AWS MSK Cluster

### ISSUE THREAD

**Issue by MohamedRDwedar** [confluentinc/confluent-kafka-dotnet#1313]
Description
===========

I have AWS MSK cluster with 2 broker nodes.
I am not able at all to produce any messages to the brokers always got Local: Message timed out error .

I can access the cluster normally in using AWS CLI
the cluster node doesn't have any authentication just the application should run in a certain  AWS VPC 

How to reproduce
================

I have tried the simplest example and just replace the bootstrap servers with the AWS Cluster nodes
here is the code 

 string brokerList = "b-1.8.c2.kafka.eu-central-1.amazonaws.com:9092,b-2.8.c.c2.kafka.eu-central-1.amazonaws.com:9092";
            string topicName = "TestTopic";

            var config = new ProducerConfig { BootstrapServers = brokerList };

            using (var producer = new ProducerBuilder<string, string>(config).Build())
            {
                Console.WriteLine("\n-----------------------------------------------------------------------");
                Console.WriteLine($"Producer {producer.Name} producing on topic {topicName}.");
                Console.WriteLine("-----------------------------------------------------------------------");
                 
                try
                {
                    var deliveryReport = await producer.ProduceAsync(
                        topicName, new Message<string, string> { Key = "MyKey", Value = "MyValue" });

                    Console.WriteLine($"delivered to: {deliveryReport.TopicPartitionOffset}");
                }
                catch (ProduceException<string, string> e)
                {
                    Console.WriteLine($"failed to deliver message: {e.Message} [{e.Error.Code}]");
                }
I have tried both of TLS and Plaintext which are both allowed in the cluster and got the same error message.

Also have change the cluster configuration from  auto.create.topics.enable=false to auto.create.topics.enable=true and still the same result.

Checklist
=========

Please provide the following information:
 - [ ] Confluent.Kafka nuget version. -  Confluent.Kafka 1.4.3
 - [ ] Apache Kafka version.  - 2.4.1
 - [ ] Client configuration.  
 - [ ] Operating system. -Linux 
 - [ ] Provide broker log excerpts. - Local: Message timed out

**Comment by mhowlett** [comment]
this won't be an issue with the client, please contact amazon support.

**Comment by feihu-wyze** [comment]
Hi @MohamedRDwedar , 
Whether the issue has been fixed or not, I don't think it's an AWS issue. I found no issue using command line under the same AWS vpc network.

**Comment by mhowlett** [comment]
it will be a connectivity issue. setting the debug config property to all may give you some insight as to what's going on.
