### ISSUE TITLE
Is Producer 300 ms Connect time to a Broker normal when network time is 50 - 60 ms?

### ISSUE THREAD

**Issue by mattk-mojio** [confluentinc/confluent-kafka-dotnet#1317]
Description
===========
When a message arrives to the producer for a Broker that is not connected yet it takes around 300 ms to connect to the brokers (connect, apiversion queries, metadata queries included). The network time is something like 50 ms - 60 ms. Is 300 ms a normal connect time? Is there anything we can do to get this down closer to the normal rtt time for produce requests?

How to reproduce
================
- Have a Kafka cluster with 5 brokers.
- Have a topic with 32 partitions.
- Send message to the producer in a loop - eventually you will hit a broker that is not connected yet.
- Observer that this first time connect takes around 300 ms (connect, apiversion\metadata queries).
- Latency for this first message is around 360 ms (300 ms connec time + usual 60 ms produce time).

[KafkaReconnectTest.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/4753650/KafkaReconnectTest.zip)
[broker_first_time_connect.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/4753655/broker_first_time_connect.txt)

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
v1.4.3
 - [x] Apache Kafka version.
kafka_2.12-2.3.0
 - [x] Client configuration.
 - [x] Operating system.
Producer client running on Windows 10 pro, 12 cores
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
Attached.
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
following on from #1308 

The time cost should be entirely due to the network RTT (cost on broker should be negligible). 300ms seems a bit higher than i'd guess given a 60ms RTT - since (i think) you need to pay that only three times, but it's in the same ballpark.

> I don't think non-sparse connections is the proper way to fix connect latency, it will just increase the load on the cluster and further increase connect latency (via @edenhill).

Number of connections has negligible impact on load unless you have thousands of them (based on my own testing). Connection establishment (particularly SSL) is more expensive, and will have a greater impact on server load if occurring frequently. In the above scenario, it seems reasonable to me that you might legitimately prefer a setup where connections stay primed. For higher throughput applications sparse connections will pretty much have no impact on p99 latency. But if you have a super low throughput application (which I think we should be accommodative of), you're going to pay a big price on average latency. Especially if your clients are distant from your brokers (which i would guess is more likely that people would want in super low throughput use cases). This definitely shouldn't be on by default! I'm just saying there are some cases where it seems to make sense to me (based on what I can see atm).

**Comment by edenhill** [comment]
> Number of connections has negligible impact on load unless you have thousands of them 

That stance is client-centric though, from a broker perspective it will have an impact, and consequently also impact the clients, thus a system-wide concern.


enable.sparse..=off will bring other problems, such as the Azure load balancer idle disconnects that are not discovered until a request times out (60s by default), and even with more standard environments these connections will be idle-reaped and increase the load on the cluster.

**Comment by mattk-mojio** [comment]
@edenhill @mhowlett Thank you both for your responses. 

- @edenhill Yes if we set enable.sparse.connections=fasle - we could get even worse latency or at least no improvement because at low throughput after 4 or 5 minutes azure will silently kill them and the next metadata refresh, or message for that killed broker connection will take 20 seconds (still not sure why it is always 20 seconds as we are at default socket.timeout.ms?, but in any case a long time relatively speaking).
 
In the attached logs I see 3 or 4 places where the 300 ms is spent:

1. Am guessing this is the connect (seems to be ballpark 3 rtt's - 3 x 60 ms ~ 200 ms)?:
[Debug] [2020-06-08 12:28:18.773] name: rdkafka#producer-1, facility: BROADCAST, level: Debug, message: [thrd:kafkabk2.something.com:9092/boots]: Broadcasting state change
[Debug] [2020-06-08 12:28:18.920] name: rdkafka#producer-1, facility: CONNECT, level: Debug, message: [thrd:kafkabk2.something.com:9092/boots]: kafkabk2.something.com:9092/2: Connecting to ipv4#0.0.0.2:9092 (plaintext) with socket 2020

2. QRYLEADER - 18 ms. Should this take 18 ms - is there any IO here? Looks like we haven't finished connecting to broker yet here.
[Debug] [2020-06-08 12:28:18.920] name: rdkafka#producer-1, facility: TOPPAR, level: Debug, message: [thrd:kafkabk2.something.com:9092/boots]: kafkabk2.something.com:9092/2: 32-part-test-topic [20] 1 message(s) queued but broker not up
[Debug] [2020-06-08 12:28:18.938] name: rdkafka#producer-1, facility: QRYLEADER, level: Debug, message: [thrd:main]: Topic 32-part-test-topic [0]: broker is down: re-query

3. Additional 60 ms. Not sure why. Is some other operation blocking us here? I see there is a metadata request happening on kafkabk0 at the same time.
[Debug] [2020-06-08 12:28:18.920] name: rdkafka#producer-1, facility: CONNECT, level: Debug, message: [thrd:kafkabk2.something.com:9092/boots]: kafkabk2.something.com:9092/2: Connecting to ipv4#0.0.0.2:9092 (plaintext) with socket 2020
[Debug] [2020-06-08 12:28:18.984] name: rdkafka#producer-1, facility: CONNECT, level: Debug, message: [thrd:kafkabk2.something.com:9092/boots]: kafkabk2.something.com:9092/2: Connected to ipv4#0.0.0.2:9092

4.  Then we have 2 x APIVersion Request\Response ~ 120 ms. This makes sense - although is there some way to do only 1 here?

5. The final produce request. As expected ~ 50 ms.

Could you please provide feedback on the above. Thank you very much.

**Comment by edenhill** [comment]
What is your machine specs? Is it a shared instance? How many vcores? What is the CPU and system load?
