### ISSUE TITLE
[Question] The best way to check if broker is up and running?

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#1318]
In my application there's a requirement for Kafka instance to know if it's still online or it went down. This instance doesn't always have active consumers or producers, it may be idling, while still always knowing the status of the connection.

So the idea I have right now is that I refresh process (timing of which I do not control) which runs pretty frequently and I am sending getMetaData request with adminClient, the problem is that because of how frequent those refreshes are and the meta data not being small it produces quite a bit of traffic, I wonder if there's any better way, like fetching only broker version or status; or something like a debug consumer just for connection... 

 - [ 1.0.0 ] Confluent.Kafka nuget version.
 - [ 2.12-2.2.0] Apache Kafka version.

**Comment by mhowlett** [comment]
it's not a simple question: https://github.com/confluentinc/confluent-kafka-dotnet/wiki/Client#can-i-use-the-net-client-to-check-if-my-kafka-cluster-is-down

we do hope to provide one or more aggregate measures in the future, but currently we don't.

if you register an error handler, you will get "all broker down" notifications on that. or you could use a metadata request to check that at least one broker is up.

**Comment by Never7Dice** [comment]
So I ended up with a thread that tries to consume the message on "some-debug-topic", while having error handler, that sets isError variable to true. And when the status refresh function is being called it looks on isError value and if it's true it will run getMetaData to broker using adminClient and if it throws exception the status remains error and if it does get meta data it switches back to OK.

**Comment by gmeena** [comment]
@mhowlett do we have any aggregate measures now apart from the options you mentioned?
