### ISSUE TITLE
Multiple consumer / GetSerializingConsumer

### ISSUE THREAD

**Issue by treziac** [confluentinc/confluent-kafka-dotnet#132]
Currently, if we want to subscribe to multiple topic with different serialization, we have to either create different instance of consumer (and as many connexion to the brokers) or a base consumer where we do the redirection manually on each message to the correct deserializer

Other solution is to make a GetSerializingConsumer, but it's less immediate than on producer (but still feasible I think, with a topic/serialized consumer mapping)

This could come in handy with a stream processing layer I think

**Comment by mhowlett** [comment]
Less straightforward than the `Producer` case, but maybe this can work. Feel free to articulate an approach in more detail :-).

**Comment by treziac** [comment]
Didn't dug too much. My base idea was to have a dictionary to map topic <=> serializer, and the base consumer would then dispatch to the correct consumer when receiving a message
Like for Producer, some events would be only on base Consumer and not on the serialized one.

The problem is for subscribing or assigning. Both are not possible first, if we want to mix them we need two instances. And if we subscribe (or assign) to a topic on a Serializing consumer, we have to unsubscribe / resubscribe to already assigned topic, and manage the subscriptions somewhere. 
I think it's possible, but not straight forward - perhaps it's better to just provide an helper to dispatch the message on the base Consumer when subscribing than dooing this in the Consumer<K,V>.

Also, do we plan to add methods AddSubscriptions / RemoveSubscriptions (resp. Assignment) which would itnernal keep the list of subscriptions and call the unsubscribe/subscribe with correct topics, rather than let the user manage it himself?

**Comment by mhowlett** [comment]
I talked with one of our more experienced SE's about this (i.e. someone who has lots of exposure to the requirements of many people) and he thought there would be very little need for this - could think of no cases. It would be possible to build a custom deserializer that did this if required, so I think we will never make adjustments to the library to add explicit support for this.
