### ISSUE TITLE
Programmatically capture consumer lag for all consumers in a consumer group

### ISSUE THREAD

**Issue by robertpaker888** [confluentinc/confluent-kafka-dotnet#1328]
We use Kafka to process our click-stream data. Most of our consumers are written in  C# and use the confluent-kafka-dotnet driver. They are hosted in aws ECS Fargate. Our Kafka cluster is hosted in confluent cloud.

We would like to programmatically capture consumer lag for all consumers in a consumer group so that we can publish this as a custom metric into aws cloudwatch and respond accordingly. 

What would be the best approach to achieve this?

Regards,

Rob

**Comment by edenhill** [comment]
Set up a SetStatisticsHandler(), set StatisticsIntervalMs to a reasonable value (e.g 1000), and extract the consumer_lag for each partition that is in fetch_state="active" in the stats handler.
Stats format here: https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by robertpaker888** [comment]
Wow that was quick. Thanks very much

**Comment by bartelink** [comment]
In case it helps, here's an example impl: https://github.com/jet/FsKafka/blob/master/src/FsKafka/FsKafka.fs#L310-L323

**Comment by robertpaker888** [comment]
Cheers, appreciated
