### ISSUE TITLE
Does rd_kafka_consumer_poll block for any reason?

### ISSUE THREAD

**Issue by jeremy001181** [confluentinc/confluent-kafka-dotnet#1329]
Hey

I am calling `Consume(TimeSpan=100ms)` method that doesn't contain a `while` loop, and I am expecting this method should just return either `null` (no message) or an instance of `consumeResult` without blocking.

And I put some debug logging before and after this method, and strangely it only made 3 calls then it hangs at the 4th call, however, if I change my Kafka server setting to a random invalid host that doesn't exist, it will happily calling it again and again with `null` as the return value which is what I wanted.

Can you help me understand is there any blocking condition inside the `c` lib that does blocking?

Regards

Thanks

**Comment by mhowlett** [comment]
`Consume` should never block if you provide a timeout. can you provide a code snippet + set the `Debug` config property to `"all"` and post the output here (over a period of time where you're experiencing the issue)?

**Comment by jeremy001181** [comment]
> `Consume` should never block if you provide a timeout. can you provide a code snippet + set the `Debug` config property to `"all"` and post the output here (over a period of time where you're experiencing the issue)?

Hey @mhowlett , thanks for reply, how do I enable debug logging for confluent-kafka, can you be more specific please?

**Comment by jeremy001181** [comment]
Don't worry. I think I found how to enable debug
