### ISSUE TITLE
Correct librdkafka.redist nupkg

### ISSUE THREAD

**Issue by treziac** [confluentinc/confluent-kafka-dotnet#133]
librdkafka.redist nuget is not correctroy structured
@edenhill  (This is more a librdkafka issue but I think this is more relevant to put it here)

- Content types are incorrect, this cause nuget2 (VS2013) to not unpack the nupkg
- build props is incorrectly loaded for new csproj (it was working for project.json) Took the solution from here : https://github.com/dotnet/cli/issues/4848#issuecomment-265320368
- it misses the package folder we find everywhere else (with metdatata psmdcp file, don't really know where it's used though)

Don't know how to do it with CoApp but here is how to create manually a correct librdkafka.redist to replace existing package

- Unzip https://github.com/treziac/confluent-kafka-dotnet/blob/nuget-librdkafka.redist/librdkafka.redist.zip to get the proper hierarchy and modify version from nuspec
- run "nuget pack librdkafka.nuspec" (tested with nuget 3.5&4 CLI)

The resulted package can be found here:
https://github.com/treziac/confluent-kafka-dotnet/blob/nuget-librdkafka.redist/librdkafka.redist.0.9.4.nupkg

Could test it successfully on VS2013, 2015, 2017 and dotnet cli (windows/linux)

**Comment by mhowlett** [comment]
@treziac - awesome - so happy you've looked into this for us.

**Comment by treziac** [comment]
My bad, it seems there is still a problem with net45 (unit tests don't work on dotnet cli), will investigate a bit more

**Comment by edenhill** [comment]
I played a bit with CoApp, there's a template for it here:
https://github.com/edenhill/librdkafka/blob/master/win32/librdkafka.autopkg.template

But it seems that MS is abandoning CoApp for [vcpkg](https://github.com/Microsoft/vcpkg) which is most likely fantastic but it wont help our users very much since it is too new and not really integrated into anything else, from what I can tell.

**Comment by edenhill** [comment]
I'm planning to roll a new librdkafka.redist packages soon and I would like to include your fixes, @treziac.
What's the latest status, are all known issues resolved with your 0.9.4 patch1?
Can I base my package off that?

**Comment by treziac** [comment]
I did some more tests. 
I found a bug : when using a .net45+ project (standard, not core) with packagereference (new option in vs2017) enable instead of package.config, it does not work.
Relying on package.config being present on build/props doesn't seem to be the good solution. I don't know how to distinguish a net452 project created from .net core and one created from traditional desktop. Will open a issue on nuget/home for this later (may not have time today)

**Comment by mhowlett** [comment]
really happy you've been looking into this @treziac - it's a pretty annoying problem. If you manage to get it sorted out before I get a chance to look at it i'll definitely owe you a beer or two or three.

**Comment by treziac** [comment]
Ok, the PackageReference on classic csproj is really weird with transitive dependancies and build/runtimes, or perhaps it doesn't work well with local package sources. will try to upload a custom confluent.kafka package to see

**Comment by cklaw** [comment]
May I just ask if anyone thinks this issue is fixed? I am experiencing the exact same problem as many people have reported:

- Windows 10 x64
- Visual Studio 2017 Pro
- Windows Forms App
- .NET Framework 4.5.1
- Confluent.Kafka v0.9.4
- librdkafka.redist v0.9.4
- Microsoft Visual C++ 2013 Redistributable (x64) 12.0.30501

Results in:
System.TypeInitializationException: Unable to load DLL 'librdkafka': The specified module could not be found

Am I missing something? I tried referencing the patch but still got he same error.

Could someone explain the steps to resolve this?

TIA

Charles

**Comment by edenhill** [comment]
@cklaw Could you try out librdkafka.redist 0.9.5-RC2 which aims to fix some of these problems?
https://www.nuget.org/packages/librdkafka.redist/0.9.5-RC2

**Comment by cklaw** [comment]
Thanks, just tried it, but sadly still exactly the same error/exception.

**Comment by treziac** [comment]
@cklaw 
Do you use the new ProjectReference in your csproj or the package.config?
You can also try https://www.nuget.org/packages/librdkafka.redist/0.9.5-RC3

Do you have the x64/x86 folder when building your project?

**Comment by cklaw** [comment]
I have just tried RC3 but still get the error. I use whatever VS uses by default in my csproj, which appears to be a packages.config.

I have both x64 and x86 folders, so I deleted them when the exception occurred. I then rebuilt the solution and they reappeared. The files that are in there all have the datetime 13/04/17 19:02.

**Comment by treziac** [comment]
You tried confluent.kafka rc3 or librdkakfa.redist rc3?

Le 14 avr. 2017 8:44 PM, cklaw <notifications@github.com> a écrit :

I have just tried RC3 but still get the error. I use whatever VS uses by default in my csproj, which appears to be a packages.config.

I have both x64 and x86 folders, so I deleted them when the exception occurred. I then rebuilt the solution and they reappeared. The files that are in there all have the datetime 13/04/17 19:02.

**Comment by mhowlett** [comment]
@cklaw try referencing Confluent.Kafka 0.9.5-RC3 (just put on nuget).

**Comment by cklaw** [comment]
What I meant was that I tried librdkafka.redist/0.9.5-RC3 as treziac suggested.

**Comment by treziac** [comment]
Confluent.Kafka RC3 was not released at this time, can you try it instead? 
It fixes the way librdkafka libs are loaded on classic .Net framework

I tried this case (VS2017, w10 x64, win forms app, net451, package.config) with no issue, but it seems by default it was the x86 version which was launched, which required the x86 version of vsredist c++2013. This prerequisite should no longer be needed in 0.9.5 (corresponding dll is now correctly packed&loaded)

**Comment by cklaw** [comment]
The exception has changed:

_InvalidOperationException: Error while loading librdkafka.dll or its dependencies from O:\Projects. Check the directory exists, if not check your deployment process_

This is the root of my project, which is a couple of sub-folders below this, but needless to say it does exist. I tried a 'clean' on the solution and rebuilt.

I don't know if it is significant, but when I look at the loaded packages, after running

`Install-Package Confluent.Kafka -Pre`

only the Confluent.Kafka package exists; the librdkafka.redist package is no longer there. I tried running

`Install-Package librdkafka.redist -Pre`

but it tells me that it already exists.

**Comment by treziac** [comment]
@cklaw 
You should have an other Innerexception (win32Exception), what is it?

I did a sample here:
https://github.com/treziac/confluent-kafka-VS2017-winforms

Can you try it?

@mhowlett my bad, i forgot to include in the message the x64 / x86 folder, but that was just informative
I don't see why it doesn't work though

**Comment by cklaw** [comment]
The inner exception was "The specified module could not be found", but it doesn't say what module.

The x64 folder is at

_O:\Projects\C#\ConfluentKafkaTest\ConfluentKafkaTest\bin\Debug\x64_

When I run that code, baseDirectory is indeed O:\Projects.

`Directory.GetCurrentDirectory()` returns

_O:\\Projects\\C#\\ConfluentKafkaTest\\ConfluentKafkaTest\\bin\\Debug_

but I don't know if that is reliable enough to always get the executable folder.

**Comment by cklaw** [comment]
Your sample works when I have it in this path

_C:\Users\ckl\Source\Repos\confluent-kafka-VS2017-winforms_

But when I put it here

_O:\Projects\C#\confluent-kafka-VS2017-winforms_

it fails with the same exception as my project.

**Comment by treziac** [comment]
I assume it's because of the # sign?

Directory.GetCurrentDirectory() is not reliable - current directory can be changed at runtime.
Will do some tests, thanks for the report!

**Comment by cklaw** [comment]
Good spot. Trust me to find an edge case ;-). It'll be nice to have it fixed, though.

**Comment by mhowlett** [comment]
thanks @treziac - i will happily await a PR :-) but also let me know you want me to fix it. Definitely should get this fixed for 0.9.5.

**Comment by treziac** [comment]
Will do tonigh :)

**Comment by mhowlett** [comment]
Confluent.Kafka 0.9.5-RC4 will be available on nuget shortly and should resolve the # issue.

**Comment by treziac** [comment]
@mhowlett 
The RC4 only targets netstandard1.3, can you rebuild one on windows to have net45 also and apply the tag on github?
Btw are released done manually? It would make everything easier if it was automated in appveyor I think.

**Comment by mhowlett** [comment]
yep. apparently it's time to start doing this properly.

**Comment by javierholguera** [comment]
@mhowlett any idea when Confluent.Kafka 0.9.5-RC4 will be available again?

**Comment by mhowlett** [comment]
it's actually still on nuget (just hidden) and you should still be able to reference it. 
RC5 will be out probably today, possibly tomorrow.

**Comment by treziac** [comment]
Closing as 0.9.5 is released which fixes the original errors (net4* binding)
