### ISSUE TITLE
In which scenarios a Producer would thrown an "Offset out of range " exception?

### ISSUE THREAD

**Issue by kaiohenrique** [confluentinc/confluent-kafka-dotnet#1335]
Description
===========

In production we are logging "Offset out of range" unexpectedly. 
It is important to say that we are awaiting Delivery Report. 
I've experienced these error when consuming but never when producing. Do you guys have any ideas?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version. -> *1.2.2*
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by BibhutiBhusanDora** [comment]
> # Description
> In production we are logging "Offset out of range" unexpectedly.
> It is important to say that we are awaiting Delivery Report.
> I've experienced these error when consuming but never when producing. Do you guys have any ideas?
> 
> # How to reproduce
> # Checklist
> Please provide the following information:
> 
> * [ ]  A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
> * [ ]  Confluent.Kafka nuget version. -> _1.2.2_
> * [ ]  Apache Kafka version.
> * [ ]  Client configuration.
> * [ ]  Operating system.
> * [ ]  Provide logs (with "debug" : "..." as necessary in configuration).
> * [ ]  Provide broker log excerpts.
> * [ ]  Critical issue.

Do u have a debug log from Kafka and any stacktrace?

**Comment by edenhill** [comment]
This is a bug in librdkafka which is fixed in 1.4.0

**Comment by kaiohenrique** [comment]
> This is a bug in librdkafka which is fixed in 1.4.0

Hey, @edenhill. Could you please, point the PR in which this bug were fixed?

**Comment by edenhill** [comment]
@kaiohenrique https://github.com/edenhill/librdkafka/commit/18882875af641dcf22ea58ddfabfd76007769533#diff-1057ff10d16a12ea9d5ef68e83274e13L645

**Comment by kaiohenrique** [comment]
> @kaiohenrique [edenhill/librdkafka@1888287#diff-1057ff10d16a12ea9d5ef68e83274e13L645](https://github.com/edenhill/librdkafka/commit/18882875af641dcf22ea58ddfabfd76007769533#diff-1057ff10d16a12ea9d5ef68e83274e13L645)

@edenhill  I understand. But it is quite odd the producer is configured with `EnableIdempotence = false`.
