### ISSUE TITLE
Consuming a message - How to detect if this is the last message on the partition

### ISSUE THREAD

**Issue by bristowsutor** [confluentinc/confluent-kafka-dotnet#1340]
I am trying to establish if the message I am consuming is the last message on the partition. Trawling through the Confluent.Kafka lib I am able to get the current offset but not the end offset even the Offset.cs class seems to have this available.

Any guidance on how to achieved would be great. @mhowlett be great to get your thoughts

**Comment by mhowlett** [comment]
enable partition eof consume results by setting the `EnablePartitionEof` config property to `true` and testing `IsPartitionEOF` property.
