### ISSUE TITLE
We are using Confluent.Apache.Avro version "1.7.7.7", We wanted to know it is equivalent to which version of Apache.Avro version?

### ISSUE THREAD

**Issue by PaluruSumanth** [confluentinc/confluent-kafka-dotnet#1348]
We are using Confluent.Apache.Avro version "1.7.7.7", We wanted to know it is equivalent to which version of Apache.Avro version? Which version of avro is used in the confluent.apache.avro package?

**Comment by mhowlett** [comment]
It's a fork of apache avro 1.7 (with bug fixes).

All of our fixes/improvements are now in the Apache.Avro package and we've switched to that, discontinuing our fork.
