### ISSUE TITLE
Question : slow .NET core producer

### ISSUE THREAD

**Issue by Sandesh-J** [confluentinc/confluent-kafka-dotnet#1358]
Description
===========

	I have a .NET CORE 2.1 application which is trying to publish messages to Kafka topic in Avro format. Application is deployed on Windows server. I am using Confluent.Kafka - 1.2.0., Confluent.SchemaRegistry 1.2.0,  Microsoft.Hadoop.Avro-Core 1.1.19
	Strangely it is taking good amount to time to publish messages in parallel tasks. 
	We have single instance of producer and calling async method to produce _producer.ProduceAsync

	Below is somewhat similar code which we are trying to use where we are creating multiple tasks to publish message to Kafka topic in parallel. 
	Total time taken is to publish 30 messages comes out to be around 23-27 seconds. I have tried multiple times with same result. Also when Iincrease the number of parallel tasks, the time taken for complete batch increases proportionately.
	Do I need to add additional configuration at producer level or Kafka broker level to make it more efficient? 
	

How to reproduce
================

```
	var topicName = "Enter topic name here";
            var schemaRegistryClient = new CachedSchemaRegistryClient(new[]
            {
                new KeyValuePair<string, string>("schema.registry.url", "Enter Schema registry")
            });

            var producerConfig = new[]
            {
                new KeyValuePair<string, string>("bootstrap.servers", "enter bootstrapServer")
            };
            var avroSerializer = new MicrosoftAvroSerializer<ClassNameToPublish>(schemaRegistryClient, false, true, 128);
            var producerBuilder = new ProducerBuilder<Guid, ClassNameToPublish>(producerConfig)
                                        .SetKeySerializer(new GuidSerializer())
                                        .SetValueSerializer(avroSerializer);

            IProducer<Guid, ClassNameToPublish> _producer;
            _producer = producerBuilder.Build();
            var stopwatchMain = Stopwatch.StartNew();
            var tasks = new List<Task>();
            for (var i = 0; i < 30; i++)
            {
                var producerId = i;
                var task = Task.Run(async () =>
                {
                    try
                    {
                        var kafkaMessage = new Confluent.Kafka.Message<Guid, ClassNameToPublish>
                        {
                            Key = new Guid(),
                            Value = new ClassNameToPublish() { Id = new Guid().ToString() }
                        };
                        var stopwatch = Stopwatch.StartNew();
                       await _producer.ProduceAsync(topicName, kafkaMessage).ConfigureAwait(false);
                        stopwatch.Stop();
                        File.AppendAllText(@"ProducerMetrics_Single_" + producerId + ".txt", "totalMilliSeconds=" + stopwatch.Elapsed.TotalMilliseconds + Environment.NewLine);
                    }
                    catch (Exception ex)
                    {
                        var test3 = ex.Message;
                        throw;
                    }
                }, cancellationToken);
                tasks.Add(task);
            }
            Task.WaitAll(tasks.ToArray());

            stopwatchMain.Stop();
            File.AppendAllText(@"ProducerMetrics_TotalBatch.txt", "totalMilliSeconds=" + stopwatchMain.Elapsed.TotalMilliseconds + Environment.NewLine);

```
Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
the general approach seems ok - i don't immediately see what's wrong. evidently it's not running the tasks concurrently for some reason. also, how long does each produce take? (it should be ~1-3ms to localhost, not 1s).

**Comment by Sandesh-J** [comment]
> the general approach seems ok - i don't immediately see what's wrong. evidently it's not running the tasks concurrently for some reason. also, how long does each produce take? (it should be ~1-3ms to localhost, not 1s).

Thanks for quick reply Matt.

For 30 parallel tasks it is taking almost 23714 milliseconds. 

Another strange thing.. I removed parallel execution and removed executing within tasks and called ProduceAsync sequentially as below

```
 var stopwatchMain = Stopwatch.StartNew();

             for (var i = 0; i < 30; i++)
            {
                try
                {

                    var kafkaMessage = new Confluent.Kafka.Message<Guid, ClassNameToPublish>
                    {
                        Key = new Guid(),
                        Value = new ClassNameToPublish() { AssetId = new Guid().ToString() }
                    };
                    var stopwatch = Stopwatch.StartNew();

                    _producer.ProduceAsync(topicName, kafkaMessage);
                    stopwatch.Stop();
                    File.AppendAllText(@"ProducerMetrics.txt", "totalMilliSeconds=" + stopwatch.Elapsed.TotalMilliseconds + Environment.NewLine);
                }
                catch (Exception ex)
                {
                    var test3 = ex.Message;

                    throw;
                }
            }

 
            stopwatchMain.Stop();
            File.AppendAllText(@"ProducerMetricsMain.txt", "totalMilliSeconds=" + stopwatchMain.Elapsed.TotalMilliseconds + Environment.NewLine);
```

In this sequential execution it took total of 775.3531 milliseconds for the loop of 30 iterations and first produce taking around 661 milliseconds  and rest 29 produce taking very less time.

Now I did one more change as below where I called ProduceAsync before running for loop where parallel tasks are created. This did magic. First ProduceAsync  before for loop took 779 milli seconds and total time for batch of 30 messages after that took around 150 milli seconds.  

```
_producer = producerBuilder.Build();

            var kafkaMessage1 = new Confluent.Kafka.Message<Guid, ClassNameToPublish>
            {
                Key = new Guid(),
                Value = new ClassNameToPublish() { AssetId = new Guid().ToString() }
            };
            var stopwatch1 = Stopwatch.StartNew();

            _producer.ProduceAsync(topicName, kafkaMessage1);
            stopwatch1.Stop();
            File.AppendAllText(@"ProducerMetrics_000.txt", "totalMilliSeconds=" + stopwatch1.Elapsed.TotalMilliseconds + Environment.NewLine);

            var stopwatchMain = Stopwatch.StartNew();

            var tasks = new List<Task>();
            for (var i = 0; i < 30; i++)
            {
                var consumerId = i;
                var task = Task.Run(() =>
                    {
                        try
                        {

                            var  kafkaMessage = new Confluent.Kafka.Message<Guid, ClassNameToPublish>
                            {
                                Key = new Guid(),
                                Value = new ClassNameToPublish() { AssetId = new Guid().ToString() }
                            };
                            var stopwatch = Stopwatch.StartNew();

                            _producer.ProduceAsync(topicName, kafkaMessage);
                            stopwatch.Stop();
                            File.AppendAllText(@"ProducerMetrics" + consumerId + ".txt", "totalMilliSeconds=" + stopwatch.Elapsed.TotalMilliseconds + Environment.NewLine);
                        }
                        catch (Exception ex)
                        {
                            var test3 = ex.Message;

                            throw;
                        }
                     }, cancellationToken);

                tasks.Add(task);
            }

            Task.WaitAll(tasks.ToArray());

            stopwatchMain.Stop();
            File.AppendAllText(@"ProducerMetricsMain.txt", "totalMilliSeconds=" + stopwatchMain.Elapsed.TotalMilliseconds + Environment.NewLine);
```
 

So it is strange that I need to give one call to ProduceAsync before calling it in parallel tasks to get good performance. Any thoughts?

**Comment by mhowlett** [comment]
The first call is different because as a side effect it's probably accessing schema registry (I don't know what `MicrosoftAvroSerializer` is or does exactly though). I seems like the problem is likely something to do with that. Something worth noting is that `SchemaRegistryClient` previously didn't `.Configure.Await(false)` async calls, so maybe that's related, maybe try upgrading. We generally remove more bugs than we introduce in each release, so keeping your client up to date is a good idea :-).

**Comment by lixiandai** [comment]
@mhowlett i had same issue there with the producer perfomanace.
await _producer.ProduceAsync(topicName, kafkaMessage)
vs 
_producer.ProduceAsync(topicName, kafkaMessage)

when we await the task result, the producer is super slow there but without await, it perfoms as fast as expected.
But i guess without the await, we are at risk there to lose data, am i right?

**Comment by mhowlett** [comment]
if the synchronous `ProduceAsync` continues without throwing an exception, then the message was successfully written.

you can add a delivery report callback to the `Produce` method to know if the message was written without error asynchronously.

producing synchronously is slow because you need to wait for a network round trip. generally this should be avoided where possible.

**Comment by oesebus** [comment]
Hi , After upgrading from version 1.7.0 to 1.92 , i am facing some performance issue at producer level . 
The time to producer is twice more than previously with the 1.7.0 version (for the same code base) . Any idea ?
