### ISSUE TITLE
How to adjust timeout setting for kafka producer

### ISSUE THREAD

**Issue by jeremy001181** [confluentinc/confluent-kafka-dotnet#1360]
Description
===========

I am using v1.4.3, in an event of Kafka server is down, our producer took ~5min before timing out itself, 5 min seems a bit too long for us, and can you advise where is the setting for controlling this, so I can make it timeout after 30s for instance

```
Confluent.Kafka.ProduceException`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Avro.Generic.GenericRecord, Confluent.Apache.Avro, Version=1.7.7.7, Culture=neutral, PublicKeyToken=eb2f4c54031a04ba]]
```

**Comment by mhowlett** [comment]
`MessageTimeoutMs`, `Retries`, `SocketTimeoutMs`. Refer to: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by jeremy001181** [comment]
Hey @mhowlett might be a silly question, so I notice the underlying implementation of `ProduceAsync` method call into the c++ lib handle for sending messages, and if I am right, it won't be using the async IO? if so, my question is, during that 5min waiting time, does it holds up a background thread from the thread pool?
Thanks

**Comment by mhowlett** [comment]
it won't. there is a fixed number of long running threads (one per broker and one control thread in librdkafka and an additional thread to handle delivery report notification in the .net client). task continuations will happen on the .net threadpool.

**Comment by jeremy001181** [comment]
Ok, so what happens in this situation, where requests to publish events keep coming in, while the Kafka is offline. I am guessing the fixed number of long-running threads will have to run out some point? and what happens after that?

**Comment by mhowlett** [comment]
it'll wait 3 minutes - retries is in addition to the original request.

messages are stored in queues (not one per thread!), the maximum size of which is controlled by `queue.buffering.max.kbytes` and `queue.buffering.max.messages`.

**Comment by jeremy001181** [comment]
Thanks, so I do not quite understand why we are seeing 5min, not 3min?
![image](https://user-images.githubusercontent.com/2342277/90151806-0c968e80-dd7f-11ea-821c-dce47a893efc.png)
