### ISSUE TITLE
Produce message to all partitions

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1364]
Description
===========

I have multiple consumers (same group) consumming on a topic with mutiple partitions.
I'm in a model like request/reply, one consumer trigger a request and each consumers receive a separate set of messages.
At the end of request, the producer is sending an EndOfRequest message, problem is only one consumer will get this message.

I would like to know what is the appropiate way to allow all consumers receive the EndOfRequest message.

Can a producer send one message to all available partitions on a topic ??

note: kafka native EOF handler can not be used as multiple requests could be processed at the same time so even if a request is done the partition could be not empty.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [latest ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ linux/windows] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
> I would like to know what is the appropiate way to allow all consumers receive the EndOfRequest message.

i'm not completely following your requirements, but this may be a case where the ability of the consumer to override the partitions assigned to it by the group may be useful. In the assign / revoke handlers, you can return the actual set of partitions that should be assigned to be read from, and this may be different from the set assigned to you by the group (note: the java client doesn't allow you to do this). You can adjust the sets to always include a particular 'control' partition (may be a separate topic). but note that ordering guarantees are per-partition only.

you could also maybe write a message to every partition, not just one of them (you can produce explicitly to a topic/partition using Produce or ProduceAsync). you can determine how many partitions a topic has on the fly using AdminClient.GetMetadata.

**Comment by gccmbr** [comment]
Which version would you recommend that allows message partition assignment in the producer?   I am still using 1.0.0-beta and sending such messages via: 

var drb = KafkaProducer.ProduceAsync(mypartition, msg);
drb.ContinueWith(task =>{})
1.0.0-beta has been working great but noticed we lost message partition assignments in later builds.  Thanks!
