### ISSUE TITLE
Issue when Events are called before they are assigned

### ISSUE THREAD

**Issue by treziac** [confluentinc/confluent-kafka-dotnet#137]
Events (OnLog but I assume also OnError and other) can be invoked before we can assign callbacks to them.

We should allow to set a callback before the handle is created to correct that. We could use the "log_cb" and "error_cb" config keys, they should not be used by the the users of confluent-kafka-dotnet.

Or perhaps the user should be able to define its own callbacks which would replace the one we created? I like it when library let me do low-level operation (though hidden enough so that nobody will try to override them) In this case, we need to define other config name

Simple reproductible code:

```
var config = new Dictionary<string, object> { { "bootstrap.servers", brokerList }, { "debug", "all" } };

using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
{
    producer.OnLog += (o, e) => Console.WriteLine("log");
}
```

will print (on windows) :
```
7|2017-04-03 17:59:13.415|rdkafka#producer-1|BRKMAIN| [thrd::0/internal]: :0/internal: Enter main broker thread
7|2017-04-03 17:59:13.415|rdkafka#producer-1|BROKER| [thrd:app]: kafka:9092/bootstrap: Added new broker with NodeId -1
7|2017-04-03 17:59:13.424|rdkafka#producer-1|BRKMAIN| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Enter main broker thread
7|2017-04-03 17:59:13.424|rdkafka#producer-1|CONNECT| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: broker in state INIT connecting
7|2017-04-03 17:59:13.424|rdkafka#producer-1|STATE| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
7|2017-04-03 17:59:13.425|rdkafka#producer-1|BROADCAST| [thrd::0/internal]: Broadcasting state change
7|2017-04-03 17:59:13.432|rdkafka#producer-1|CONNECT| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connecting to ipv4#10.150.12.67:9092 (plaintext) with socket 1028
7|2017-04-03 17:59:13.433|rdkafka#producer-1|STATE| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Broker changed state INIT -> CONNECT
7|2017-04-03 17:59:13.434|rdkafka#producer-1|BROADCAST| [thrd:kafka:9092/bootstrap]: Broadcasting state change
log
log
log
log
log
log
log
...
```

**Comment by mhowlett** [comment]
Yeah, known deficiency.

I think we probably want to allow event handlers to be set in the configuration (though not alternate implementations of log_cb or error_cb).

Something else we could do is buffer events until such time as an event handler is added (but not indefinitely). This is conceptually worse, and more difficult to implement, though neater API.

**Comment by treziac** [comment]
The later sure would be more user friendly, but does it mean we would not send it to the default consoleLogger for some time at the beginning, or send to the ConsoleLogger immediatly and then to the OnLog when it is subscribed on?

We can also have overload constructor where callbacks are passed as parameter, but going on with configuration seems better.

"though not alternate implementations of log_cb or error_cb" : that means that we can use those conf to pass confluent-kafka-dotnet typed callbacks? (and not tranfer them to the librdkafka conf), or rather use new defined conf?

Also there is an other related bug: OnError should be send to OnLog if OnError has no callback (the librdkafka behavior)

**Comment by mhowlett** [comment]
the 1.0 API removes the `OnLog`, `OnError` and `OnStatistics` events in favor of callbacks set in the configuration object.
