### ISSUE TITLE
Assign with regex topic

### ISSUE THREAD

**Issue by alinmotogna** [confluentinc/confluent-kafka-dotnet#1370]
I'm writing a thin wrapper over `Consumer` to provide ease-of-use for our specific scenarios
Users can create this wrapper and call this method 
              ```public void Subscribe<T>(string topic, Offset offset, Action<T> handler)```
**multiple times** during the lifetime of the instance (think a WinForms control subscribing to various topics based on user input)

Regex subscriptions are another requirement for this wrapper

My understanding is that calling `Consumer.Subscribe()` multiple times, even if I keep track of subscribed topics, will mess offsets
To avoid keeping track of consumed offset and re-assign them in PartitionsAssignedHandler, I want to use `Assign` isntead of `Subscribe`.
Seems more straightforward for my use-case (per this: https://github.com/confluentinc/confluent-kafka-dotnet/issues/278#issuecomment-318858243)

Is it possible to pass a topic containing wildcards to Assign()?

Didn't find anything in the documentation, wrote a simple test and it doesn't seem to work, but maybe I'm missing something
```
public static async Task Consumer_Assign_Regex(string bootstrapServers)
{
    var msg = new Message<string, string> { Key = "test key 0", Value = "test val 0" };

    var producerConfig = new ProducerConfig {
        BootstrapServers = bootstrapServers
    };

    using (var producer = new ProducerBuilder<string, string>(producerConfig).Build()) {
        var pr = await producer.ProduceAsync("TEST-1", msg);
        Console.WriteLine($"Delivered: {pr.TopicPartitionOffset}");
    }

    var consumerConfig = new ConsumerConfig {
        GroupId = Guid.NewGuid().ToString(),
        BootstrapServers = bootstrapServers
    };

    using (var consumer = new ConsumerBuilder<byte[], byte[]>(consumerConfig).Build()) {
        consumer.Assign(new TopicPartitionOffset("^TEST.*", 0, Offset.Beginning));
        var cr = consumer.Consume(TimeSpan.FromSeconds(10));
        Console.WriteLine($"Consume: {{{cr?.TopicPartitionOffset}}}");
    }
}
```

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version: 1.50
 - [x] Apache Kafka version: 5.3.1-ccs
 - [x] Operating system: Win10

**Comment by mhowlett** [comment]
> Is it possible to pass a topic containing wildcards to Assign()?

no. you need to pass a list of topic/partitions.

> calling Consumer.Subscribe() multiple times, even if I keep track of subscribed topics, will mess offsets

It will cause a group rebalance. Following the rebalance, consumption will start from the last committed offsets. Offsets will be committed automatically in the event of a rebalance if auto commit is enabled, or if disabled, the PartitionsRevokedHandler gives you a chance to commit them before the partitions are given back to the group for the rebalance.

notes:
a rebalance is (as of v1.5) a stop-the-world operation across all consumers in the group.
new topics matching subscribed regex will be discovered at a period of `topic.metadata.refresh.interval.ms`.
