### ISSUE TITLE
ProduceAsync crashes app without generating an exception

### ISSUE THREAD

**Issue by nielsenbe** [confluentinc/confluent-kafka-dotnet#1371]
Description
===========
calling await producer.ProduceAsync crashes the application without an exception.

The message will be sent, but the application will terminate immediatly with nothing more than a
The program '[6856] .exe' has exited

How to reproduce
================

```cs
class Program
    {
        static void Main(string[] args)
        {
            RunTest();
        }

        private async static void RunTest()
        {
            var clientConfig = new ClientConfig
            {
                BootstrapServers = "-----.centralus.azure.confluent.cloud:9092",
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslMechanism = SaslMechanism.Plain,
                SaslUsername = "----",
                SaslPassword = @"----",
                SslCaLocation = @"D:\



cacert.pem",
                Debug = "all"
            };

            var config = new ProducerConfig(clientConfig);

            using (var producer = new ProducerBuilder<string, string>(config)
                .SetLogHandler((_, m) => Debug.Print(m.Message))
                .Build())
            {
                try
                {
                    // Works
                    Debug.WriteLine("----------------Sending value 1-------------");
                    var result = producer.ProduceAsync("dev-order", new Message<string, string> { Key = "key01", Value = "value01" });
                    producer.Flush(TimeSpan.FromSeconds(10));


                    // Message sent, but crashes program, doesn't even throw an exception
                    Debug.WriteLine("----------------Sending value 2-------------");
                    await producer.ProduceAsync("dev-order", new Message<string, string> { Key = "key02", Value = "value02" });

                    Debug.WriteLine("----------------Code never reaches here-------------");
                }
                catch (KafkaException ex)
                {
                    // Exception is never thrown
                    throw ex;
                }
            }
        }
    }
```

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version:  V1.5
 - [X] Apache Kafka version: Confluent Cloud
 - [X] Client configuration: In code / .NET Core 3.1
 - [X] Operating system: Windows 10 Pro
 - [X] Provide logs (with "debug" : "..." as necessary in configuration).

[Logs.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/5038882/Logs.txt)
 with code 0 (0x0).

**Comment by mhowlett** [comment]
you're using `async` incorrectly - you're not awaiting `RunTest` so the second ProduceAsync won't have a chance to run before `RunTest` completes (after which the program will exit immediately, without error).

the first produce works because you call flush, which is blocking (you generally shouldn't do this in async code). maybe have a look at the examples for examples.

**Comment by nielsenbe** [comment]
My code is simplified to try to demo the problem I'm having.

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Producer/Program.cs
Example code:
`var deliveryReport = await producer.ProduceAsync(topicName, new Message<string, string> { Key = key, Value = val });`
My code:
`await producer.ProduceAsync("dev-order", new Message<string, string> { Key = "key02", Value = "value02" });`

The code is pretty much lifted verbatim from that example.  Even if you comment out the first example the second example still crashes without an exception.  The code is inside a try catch block.  The produceasync shouldn't be crashing the entire app.

**Comment by nielsenbe** [comment]
Simplified code example:
```cs
using (var producer = new ProducerBuilder<string, string>(config)
                .SetLogHandler((_, m) => Debug.Print(m.Message))
                .Build())
            {
                try
                {
                    // Crashes program, doesn't even throw an exception
                    Debug.WriteLine("----------------Sending value-------------");
                    var deliveryReport = await producer.ProduceAsync("dev-order", new Message<string, string> { Key = "key33", Value = "value01" });

                    Debug.WriteLine("----------------Code never gets here-------------");
                }
                catch (KafkaException ex)
                {
                    throw ex;
                }
            }
```

If I leave out the first async statement the program just ends and the message isn't even sent.  The app just stops.  The second debug is never hit.  I attached an updated log for the simple code.

[Logs2.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/5039190/Logs2.txt)

**Comment by mhowlett** [comment]
that second code snippet should work if it's inside a method that is `await`ed. if it's not, the second debug statement won't get hit, as you're saying.

**Comment by nielsenbe** [comment]
You are right.  Didn't notice my method signature was async void instead of async Task.  Still new to async programming.  Nothing like wasting hours over a misplaced keyword.  Such is the life of a programmer. Thank you for your time.
