### ISSUE TITLE
Using a CustomPartitioner

### ISSUE THREAD

**Issue by Sepp12391** [confluentinc/confluent-kafka-dotnet#139]
Hi,
I am trying to update from rdkafka-dotnet and there is a Problem, cause I am not able to find the possibility to build/create a CustomerPartitioner.

**Comment by treziac** [comment]
It's not available yet, should come soon.

**Comment by mhowlett** [comment]
hi @Sepp12391 - yes, this has not been added yet. It was cut because we wanted to think more about the API before committing to it. The interop functionality is all still there from rdkafka-dotnet under the hood, it's just not exposed yet.

**Comment by ashishbhatia22** [comment]
Any updates on when the custom partitioning is going to be available? We are looking to use this library. However, custom partitioning is a must for us given the volume of messages we are dealing with. Thanks,

**Comment by mhowlett** [comment]
no update - it's not a lot of work, but it's not explicitly on my near-term todo list.

Will review PRs.

It's maybe worth noting that custom partitioners are not commonly required. Feel free to describe your use case for feedback.

**Comment by ashishbhatia22** [comment]
We are working on IOT solution. We need to route the message to devices ending with (1-5) to 1 partition and devices ending with (6-9) to a separate partition. let me know if this works..

**Comment by treziac** [comment]
For now, you can easily do this via ProduceAsync (though I agree it's not ideal)

int partitionToUse = (key%10 / 5) + 1;
producer.ProduceAsync(topic, key, val, partitionToUse);

Only downside is that you can't used the PartitionAvailable.
I will do a PR when I have time if not done before, but for now I have no computer nor internet at home and no time at work so will have to wait :)

**Comment by mhowlett** [comment]
this is definitely coming - we've worked out what the API will look like (which is the hardest part). this feature has been prioritized to be added soon after we've finalized the breaking api changes in 1.0 (i.e. later this year sometime).
