### ISSUE TITLE
Unable to send messages to kafka  from Windows 2008 R2 

### ISSUE THREAD

**Issue by SanjanaSanikommu** [confluentinc/confluent-kafka-dotnet#1394]
Description
===========
I am able to publish and subscribe kafka messages successfully from Windows 7 - x64 , but on windows 2008 R2 server I am not able to connect to kafka. and send messages

The code base & configurations are exactly same on windows 7 - x64 & windows 2008 R2 server.

code is setup in java version.

Is it OS issue?

How to reproduce
================

Does connecting to kafka need any additional properties?

Can you please check with sample message if kafka works on Windows 2008 R2 Server

Checklist
=========

Please provide the following information:
 - [] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [Windows 2008 R2 ] Operating system.
 - [No logs/debug statements ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ Yes] Critical issue.

**Comment by mhowlett** [comment]
are you using SSL? it could be that you don't have the required CA certs on Windows 2008 R2.

if you enable debug logging (set `Debug` config to `all`), we'll probably be able to identify the issue from the logs.

**Comment by SanjanaSanikommu** [comment]
yeah this is cert issue , keystore cert file was corrupted, after regenerating certs I am able to send messages
