### ISSUE TITLE
How does Kafka create Topic set the number of partitions

### ISSUE THREAD

**Issue by gaojiandonggg** [confluentinc/confluent-kafka-dotnet#1395]
Description
===========
I want to dynamically generate topic names through generics, and dynamically set the number of partitions to 3 at the same time. Now, after successful topic creation, the default partition is one

example:

var config = new ProducerConfig
            {
                BootstrapServers = kafkaMQConfig.brokerList
            };
        
            config.SslCaLocation =string.IsNullOrWhiteSpace(kafkaMQConfig.SslCaLocation)?"": Path.Combine(IWebHostEnvironment.ContentRootPath, kafkaMQConfig.SslCaLocation);
            config.SslCertificateLocation = string.IsNullOrWhiteSpace(kafkaMQConfig.SslCertificateLocation) ? "" : Path.Combine(IWebHostEnvironment.ContentRootPath, kafkaMQConfig.SslCertificateLocation);
            config.SslKeyLocation = string.IsNullOrWhiteSpace(kafkaMQConfig.SslKeyLocation) ? "" : Path.Combine(IWebHostEnvironment.ContentRootPath, kafkaMQConfig.SslKeyLocation);
            config.SslKeyPassword = string.IsNullOrWhiteSpace(kafkaMQConfig.KeyPassword) ? "" : kafkaMQConfig.KeyPassword;
            config.SslKeystorePassword = string.IsNullOrWhiteSpace(kafkaMQConfig.KeyPassword) ? "" : kafkaMQConfig.KeyPassword;
            if (!string.IsNullOrEmpty(kafkaMQConfig.SslCaLocation) ||
                !string.IsNullOrEmpty(kafkaMQConfig.SslCertificateLocation) ||
                !string.IsNullOrEmpty(kafkaMQConfig.SslKeyLocation))
            {
                config.SecurityProtocol = SecurityProtocol.Ssl;
                config.SslEndpointIdentificationAlgorithm = SslEndpointIdentificationAlgorithm.None;
            }
            if (!string.IsNullOrWhiteSpace(kafkaMQConfig.UserName))
            {
                config.SaslUsername = kafkaMQConfig.UserName;
                config.SaslPassword = kafkaMQConfig.Password;
            }
            config.Acks = Acks.All;
            //发送失败重试3次
            config.MessageSendMaxRetries = 3;

  

            topicName = string.IsNullOrEmpty(topicName) ? $"{_customKey}.{typeof(T).FullName}" : $"{_customKey}.{topicName}";
            key = string.IsNullOrEmpty(key) ? $"{_customKey}.{typeof(T).FullName}" : $"{_customKey}.{key}";
        using (var producer = new ProducerBuilder<string, string>(config).Build())
               {
                   try
                   {
                       if (partition > 0)
                       {
                           var deliveryResult = await producer.ProduceAsync(
                               new TopicPartition(topicName, new Partition(partition)),
                               new Message<string, string> { Key = key, Value = JsonConvert.SerializeObject(message) });
                       }
                       else
                       {
                           var deliveryResult = await producer.ProduceAsync(topicName.ToLower(),
                               new Message<string, string> { Key = key, Value = JsonConvert.SerializeObject(message) });
                       }
                   }
                 
               }

How to do?

**Comment by mhowlett** [comment]
Number of partitions for auto-created topics is controlled with the broker `num.partitions` config property.

Relying on topic auto creation is no longer recommended now that we have `AdminClient`. You can explicitly specify number of partitions when using that.

**Comment by gaojiandonggg** [comment]
> Number of partitions for auto-created topics is controlled with the broker `num.partitions` config property.
> 
> Relying on topic auto creation is no longer recommended now that we have `AdminClient`. You can explicitly specify number of partitions when using that.


Thanks you
