### ISSUE TITLE
Question:  using new ProducerBuilder in event handler

### ISSUE THREAD

**Issue by gccmbr** [confluentinc/confluent-kafka-dotnet#1399]
Is there any significant performance hit when using the new ProducerBuilder inside of an active event handler that is receiving messages and then publishing those messages to Kafka via the producer?

**Comment by mhowlett** [comment]
creating a producer is very expensive, you should generally do that only once per application instance.

**Comment by gccmbr** [comment]
Given I was going to performance test this, my server thanks you for waving me off 👍
