### ISSUE TITLE
Add support for local-timestamp-millis

### ISSUE THREAD

**Issue by akorotin** [confluentinc/confluent-kafka-dotnet#1401]
Description
===========
Add support for "local-timestamp-millis", while the regular timestamp-millis is supported

How to reproduce
================
{ \"logicalType\": \"local-timestamp-millis\", \"type\": \"long\" }

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.5.1 ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
you can open an issue for this on the apache avro repo: https://github.com/apache/avro
