### ISSUE TITLE
How to incorporate System.Text.Json JSONConverters into serialization/deserialization of message value?

### ISSUE THREAD

**Issue by dcs3spp** [confluentinc/confluent-kafka-dotnet#1405]
Description
===========
Hi,

I am a new user.

I have just finished implementing some System.Text.Json custom JsonConverters implemented for POCO classes.

I have looked at the source code briefly in the examples for JSONSerializers and notice that this is performed with NewtonSoft JSON.

Is there any way I can use the JsonConverters that I have implemented to deserilize a value?

**Comment by mhowlett** [comment]
At the time this was implemented, and I think it's still the case, System.Text.Json didn't allow for any JSON Schema capability which is required for integration with Schema Registry. If you don't want to use Schema Registry, you could write your own serdes that use System.Text.Json.

**Comment by dcs3spp** [comment]
Ok, thanks for response @mhowlett , appreciated 👍 

Probably the safest option would be to go with schema registry support for integrity and security, so it looks as though I will  have to write two Newtonsoft JSON.NET custom converters.

I have looked at the source of the [JSON serdes](https://github.com/confluentinc/confluent-kafka-dotnet/blob/6337d8a268da24bfdecbbde429053077ceeb2357/src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs#L112). 

What steps are necessary for the validation capability?

**Comment by RagingKore** [comment]
@dcs3spp avoid  Newtonsoft JSON.NET like the plague. Too slow and bloated. It actually destroys the performance of Kafka or any other system. No reason at all to use it.

But this simple example of a client side serialization/deserialization implementation should do the trick.

It assumes that the clr message type is added as a header to the produced messages and always available in the consumed messages.

```csharp
    var consumer == new ConsumerBuilder<byte[], object?>(consumerConfig)
        .SetValueSerializer(new SystemTextJsonSerDe(jsonOptions))
        .Build();
```

```csharp
    var producer = new ProducerBuilder<byte[], object?>(producerConfig)
        .SetValueSerializer(new SystemTextJsonSerDe(jsonOptions))
        .Build();
```

```csharp
    using System;
    using System.Text;
    using System.Text.Json;
    using Confluent.Kafka;

    public class SystemTextJsonSerDe : ISerializer<object?>, IDeserializer<object?>
    {
        public SystemTextJsonSerDe(JsonSerializerOptions defaultOptions) => DefaultOptions = defaultOptions;

        JsonSerializerOptions DefaultOptions { get; }

        public byte[] Serialize(object? data, SerializationContext context)
            => JsonSerializer.SerializeToUtf8Bytes(data, GetMessageType(context), DefaultOptions);

        public object? Deserialize(ReadOnlySpan<byte> data, bool isNull, SerializationContext context)
            => JsonSerializer.Deserialize(data, GetMessageType(context), DefaultOptions);

        static Type GetMessageType(SerializationContext context)
            => Type.GetType(Encoding.UTF8.GetString(context.Headers[0].GetValueBytes()))!;
    }
```

**Comment by dcs3spp** [comment]
Many thanks for this @RagingKore, understood and appreciated :)

In the projects that you have been involved with how are you doing validation of JSON.Schema with Kafka using ```System.Text.Json``` ?

**Comment by RagingKore** [comment]
At the time, we required dynamic serialization & deserialization for multiple message types per topic, using Protobuf and/or System.Text.Json.

So we skipped the schema registry altogether.

It is in our plans to look into using Schema Registry in a near future to be able to interact with connectors that depend on it.

**Comment by dcs3spp** [comment]
Ok, thanks again @RagingKore for the serialization/deserialization example earlier.

It looks as though there is a library called [Cogito.Text.Json.Schema](https://github.com/dotnet/runtime/issues/29887#issuecomment-569348442) that can support some form of JSON schema validation for use with System.Text.Json. I am not sure how effective it is though, since I have not tried it yet....

**Comment by RobThree** [comment]
@RagingKore Just wondering, is there any reason why you didn't implement the (de)serializer with generics?

```c#
public class SystemTextJsonSerDe<T> : ISerializer<T>, IDeserializer<T>
{
    private JsonSerializerOptions DefaultOptions { get; }

    public SystemTextJsonSerDe(JsonSerializerOptions defaultOptions)
        => DefaultOptions = defaultOptions;

    public byte[] Serialize(T data, SerializationContext context)
        => JsonSerializer.SerializeToUtf8Bytes(data, DefaultOptions);

    public T Deserialize(ReadOnlySpan<byte> data, bool isNull, SerializationContext context)
        => JsonSerializer.Deserialize<T>(data, DefaultOptions)!;
}
```
