### ISSUE TITLE
How to notify users sessions of messages consumed?

### ISSUE THREAD

**Issue by dcs3spp** [confluentinc/confluent-kafka-dotnet#1406]
Hi,

At the time of writing, consuming messages is achieved using a synchronous loop, i.e. there is no ```ConsumeAsync```.

Due to the expense associated with a consumer, I have read that it is recommended to have a [singleton](https://github.com/confluentinc/confluent-kafka-dotnet/issues/288#issuecomment-567121705) 
kafka consumer per process. This executes within a long running task that lasts for the process lifetime.

If I want logged in users to be able to receive updates on an application page to monitor messages received from kafka topic .........how can I get each user's scoped service to automatically receive notification of consumed messages and update the page? 

1. SignalR?
2. Posting an event (for each consumed message) to an event bus, eg. NServiceBus, Rebus etc? Each frontend page refreshes upon notification of an event received from the event bus.....
3. API to act as a front end to the kafka topic. Each front end page for the logged in user then frequently polls the API to refresh?

**Comment by mhowlett** [comment]
sorry, outside the scope of this forum for what we have bandwidth to answer ...
