### ISSUE TITLE
batchNumMessages doesn't seem to be working

### ISSUE THREAD

**Issue by saherahwal** [confluentinc/confluent-kafka-dotnet#1409]
Description
===========
It doesn't seem that batching using batchNumMessages setting is working. I created two producers: one with batchNumMessages=1 and another with batchNumMessages=32 (I also adjusted lingerMs to around 5 ms in that case). 
The stats for both producers seem to be the same:
here is snippet from JSON stats that the second producer outputs. Similar to the one with no batching. 

```
"topics": {
		"bl-perf": {
			"topic": "bl-perf",
			"age": 59641,
			"metadata_age": 58984,
			"batchsize": {
				"min": 246,
				"max": 246,
				"avg": 246,
				"sum": 83886,
				"stddev": 0,
				"p50": 246,
				"p75": 246,
				"p90": 246,
				"p95": 246,
				"p99": 246,
				"p99_99": 246,
				"outofrange": 0,
				"hdrsize": 14448,
				"cnt": 341
			},
			"batchcnt": {
				"min": 1,
				"max": 1,
				"avg": 1,
				"sum": 341,
				"stddev": 0,
				"p50": 1,
				"p75": 1,
				"p90": 1,
				"p95": 1,
				"p99": 1,
				"p99_99": 1,
				"outofrange": 0,
				"hdrsize": 8304,
				"cnt": 341
			},
```

I am using batchNumMessages as opposed to BatchSize since the earlier one was the only one available prior to most recent release. 

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. (1.5.0)
 - [x] Apache Kafka version. (2.2)
 - [x] Client configuration. ("Kafka__StatisticsIntervalMs": "30000)
 - [x] Operating system. (Windows Server 2012 R2)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
this is the maximum number of messages to include in a batch. you may also need to increase linger.ms.
