### ISSUE TITLE
Question: Is it possible to consume from a specific offset?

### ISSUE THREAD

**Issue by c3f8** [confluentinc/confluent-kafka-dotnet#141]
Hi there,
I am not an expert in .Net so maybe i am missing something. 
Is it possible to start consuming from a specific offset? 

Best regards.

**Comment by Aenima4six2** [comment]
See the consumer example. 
consumer.Assign(new List<TopicPartitionOffset> { new TopicPartitionOffset(topics.First(), 0, 0) });

**Comment by c3f8** [comment]
Thanks for the answer. I will check the example better.
I also found and example on the documentation

consumer.OnPartitionsAssigned += (obj, partitions) => {
    Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}], member id: {consumer.MemberId}");
    var fromBeginning = partitions.Select(p => new TopicPartitionOffset(p.Topic, p.Partition, Offset.Beginning)).ToList();
    Console.WriteLine($"Updated assignment: [{string.Join(", ", fromBeginning)}]");
    consumer.Assign(fromBeginning);
};
