### ISSUE TITLE
Cannot connect to Kafka server with .net confluent client

### ISSUE THREAD

**Issue by yli-dev** [confluentinc/confluent-kafka-dotnet#1410]
Description
===========
I tried to run .net confluent Kafka client on my Windows machine. The ConsumerBuilder failed to build the consumer and threw this error:

```
System.InvalidOperationException: ssl.ca.location failed: No error
  at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config, IClient owner)
  at Confluent.Kafka.Consumer`2..ctor(ConsumerBuilder`2 builder)
  at Confluent.Kafka.ConsumerBuilder`2.Build()
  at xxx.KafkaHandler.Subscribe(String consumerId, IEnumerable`1 topics, CancellationToken stoppingToken, Func`2 messageHandler, Action`1 errorPusher, IAlerter alerter, Boolean resolveWhenSuccess) in
  at xxx.ConsumerTask`2.Consume(CancellationToken stoppingToken) in
```
The way how I called the ConsumerBuilder was:

```
 using (var consumer = new ConsumerBuilder<Null, KafkaMessage>(_kafkaConsumerConfig)
    .SetErrorHandler((IConsumer<Null, KafkaMessage> message, Error e) => _logger.LogStructuredInformation("Detected error in consumer", new Dictionary<string, object> { { "consumergroup", consumerGroupId }, { "reason", e.Reason } }))
    .SetValueDeserializer(new NotifyMessageDeserializer())
    .Build())
```
and the _kafkaConsumerConfig was:

```
  {
    BootstrapServers = config.KafkaServers,
    SecurityProtocol = SecurityProtocol.Ssl,
    SslCertificateLocation = _filer.ClientCertificateFile(),
    SslKeyLocation = _filer.ClientCertificateKeyFile(),
    SslCaLocation = _filer.TrustedCertificateFile(),

    SocketKeepaliveEnable = true,
    EnableAutoCommit = false,
    EnablePartitionEof = true,
    SessionTimeoutMs = 30000,
    AutoOffsetReset = AutoOffsetReset.Earliest,
  }
```

The exact same code runs smoothly on Ubuntu 18.04 LTS (Bionic Beaver).

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version: 1.5.1
 - [x] Apache Kafka version: 2.2.1
 - [x] Client configuration.
 - [x] Operating system: Windows 10 build 1809
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by weeco** [comment]
Same here, some screenshots:

![image](https://user-images.githubusercontent.com/23424570/99655757-608ad080-2a5c-11eb-929a-90123ce8a47b.png)

![image](https://user-images.githubusercontent.com/23424570/99655795-6c769280-2a5c-11eb-9759-60e5f947c70a.png)

```cs
new ProducerConfig {
					BootstrapServers = options.kafka.BootstrapServers,
					SaslMechanism = SaslMechanism.Plain,
					SaslUsername = options.kafka.Sasl.Username,
					SaslPassword = options.kafka.Sasl.Password,
					SecurityProtocol = SecurityProtocol.SaslSsl,
					ClientId = "OwlShop",
					SslCaLocation = @"C:\Users\h9pe\Documents\projects\cloudhut\owl-shop\plat-sandbox.crt",
					Debug = "security"
				},
```

Any idea what's wrong @edenhill ?

**Comment by yli-dev** [comment]
In case someone bump into the same problem, for my case the cause was that the CA cert is missing line breaks..
