### ISSUE TITLE
Question about Consumer CPU usage and how to fine-tune/mitigate its usage.

### ISSUE THREAD

**Issue by TheFireCookie** [confluentinc/confluent-kafka-dotnet#1413]
Description
===========
Hello @mhowlett , this is more a question than reporting an issue but I didn't find a better place to ask for questions / informations.

So my 2 questions is:
We have a .NET app that consumes topics with 68 consumers configured.

When they is no new messages (so when the appand kafka are idle), the CPU consumption is still high and we would like to mitigate that.

1) We actually have 1 consumer by topic consumed, would it be less CPU-hungry if we would have less consumers but consuming multiple topics?
2) Is there some configs we can do to make the CPU less hungry ? (the polling of the consumer is configurable?)

Thanks,
Matthias.

**Comment by mhowlett** [comment]
yes, a consumer instance is relatively expensive. if you can, try to hang everything off one consumer. 68 topics indicates you may have an architecture that the API wasn't designed for. Can you briefly describe what your 68 topics are?

**Comment by TheFireCookie** [comment]
Hello @mhowlett , thank you for your fast answer.
So the idea is that in the project I'm currently working on, we use a microservices approach that using events to talk to each others.

The service is the sample I've described is a service that listen to a lot of other services.
For each services put its events in one topic.
Let's take an example:
Service1 put its events in "Topic1",
Service2 put its events in "Topic2",
etc for a lot of services.

Then my service, let's call it "EaterService", consumes all the events from all these topics.
So for now we do a consumer by topic to avoid bottlenecks in the consumption.
It's not really easy to explain it better without showing you all the code.

2 questions following your answer then:
1. So if we do less consumers but some consumers multiple topics, we will gain CPU, true?
2. We have another use cases where we need to push & consume A LOT of data from only one topic. What parameters / methods could we use to optimise this flow?
I've seen that using "Produce" instead of "ProduceAsync may be more performant?
I've also seens that the produce in reality do bulk pushes into kafka. If we do bigger bulks, it will be more performant? And on the consumer side, if we only consume one topic, is there way to fasten the consuming speed? (maybe configuring multiple partitions on the same topic?)

Thanks,
Matthias.

**Comment by mhowlett** [comment]
> So if we do less consumers but some consumers multiple topics, we will gain CPU, true?

yes. a conventional kafka application would maximize the amount of data flowing through each client. this isn't the only architectural pattern you might like to have, but the current state of affairs is still really tailored to that.

> We have another use cases where we need to push & consume A LOT of data from only one topic. What parameters / methods could we use to optimise this flow?

The default parameters are pretty optimized for high throughput. You also might like to look at the benchmark test, which has parameters optimized for throughput.

When I run that, I get about 500,000 msg/s produce and 1,000,000 msg/s consume (localhost, 10 byte messages, single partition topic).

> I've seen that using "Produce" instead of "ProduceAsync may be more performant?

Yes, there's overhead in using `Task`s.

> I've also seens that the produce in reality do bulk pushes into kafka. If we do bigger bulks, it will be more performant? And on the consumer side, if we only consume one topic, is there way to fasten the consuming speed? (maybe configuring multiple partitions on the same topic?)

batching happens behind the scenes - messages are cached on both produce and consume in the client before being send and as they are received.

unless you have a super fast network, that will probably be the bottleneck.

**Comment by TheFireCookie** [comment]
Thanks a lot, that is enough information for me. We can close this topic for me!
