### ISSUE TITLE
Failed to load the librdkafka native library - When using Kafka with MongoDB package

### ISSUE THREAD

**Issue by braca** [confluentinc/confluent-kafka-dotnet#1416]
Description
===========
It seems that there is a conflict between `Confluent.Kafka` and `MongoDB.Driver`.

If I publish my app as self-contained for windows (`dotnet publish -r win-x86`), the app crashes at startup because `Confluent.Kafka` won't be able to load `librdkafka`, this only happens if I have `MongoDB.Driver` package installed as well.

I've been looking into this, and I believe that the culprit is the `libzstd.dll` that both projects use, but I'm not sure how I can fix this.

**Details:**
- Confluent.Kafka version: 1.5.1
- MongoDB.Driver version: 2.11.2
- .netcore 2.1/3.1
- Apache Kafka version: Not relevant (it crashes before establishing any connection to kafka)
- Operating System: Windows 10 / Windows Server 2016

**Exception:**
```
System.DllNotFoundException: Failed to load the librdkafka native library.
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Consumer`2..ctor(ConsumerBuilder`2 builder)
   at Confluent.Kafka.ConsumerBuilder`2.Build()
   at kafka_mongo_issue.Startup.StartKafkaConsumer() in D:\Dev\kafka-mongo-issue\Startup.cs:line 61
```

How to reproduce
================
```
git clone https://github.com/braca/kafka-mongo-issue
cd kafka-mongo-issue
dotnet publish -r win-x86 -c Release -o output
cd output
kafka-mongo-issue.exe
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by mhowlett** [comment]
that sounds likely. @edenhill - can we statically link libzstd?

**Comment by braca** [comment]
@mhowlett @edenhill any clue about how can I solve this?

**Comment by edenhill** [comment]
Can you please create an issue on librdkafka to statically link zstd in the nuget packages?

**Comment by braca** [comment]
@edenhill done -> https://github.com/edenhill/librdkafka/issues/3122

**Comment by naughtyGitCat** [comment]
does this problem be fixed?

**Comment by naughtyGitCat** [comment]
failed with this problem again, net 5.0 confluent.kafka 1.6.3

**Comment by naughtyGitCat** [comment]
is there any clue to fix this? i was consuming zstd compressed msg from kafka and save to mongodb

**Comment by naughtyGitCat** [comment]
2021-04-26 14:12:48.780 +08:00 [DBG] =>[DBASlowLogBroker.Services.KafkaConsumerService]=> Now start to consume asynchronously
2021-04-26 14:12:49.355 +08:00 [ERR] =>[DBASlowLogBroker.Services.KafkaConsumerService]=> Consume failed, Confluent.Kafka.ConsumeException: Local: Invalid compressed data
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
   at DBASlowLogBroker.Services.KafkaConsumerService.ConsumeOneByOneAsync(String topic, Func`2 func, CancellationToken cancellationToken) in

**Comment by naughtyGitCat** [comment]
forgive me, fix this by jump Kafka offset, maybe incomplete msg been uploaded to kafka

**Comment by milindl** [comment]
Closing this as the ticket within librdkafka is merged a while back. Please reopen for further issues with zstd static linking.
