### ISSUE TITLE
status of confluent package?

### ISSUE THREAD

**Issue by bkim54** [confluentinc/confluent-kafka-dotnet#143]
are there any release notes on what is supported in the confluent package in comparison to rdkafka?

**Comment by mhowlett** [comment]
no we haven't done this. the only top level feature missing c.f rdkafka-dotnet is custom partitioners (I don't think i'm forgetting anything). we do plan to add this feature back.

**Comment by bkim54** [comment]
Will you provide any documentation on what features are/aren't present vs rdkafka, in the future?

I was also wondering what the timeline for the custom partitioners are? We are currently using rdkafka and the custom partitioner feature is necessary for us, but would like to upgrade to the confluent package

**Comment by mhowlett** [comment]
we have a number of requests for custom partitioners and they shouldn't take much effort, so I suspect this is not too far away. they are difficult to implement in some other languages for reasons that don't apply in C# (i believe, though there are some details I want to carefully check). one reason they were deprioritized initially is that most use cases for custom partitioners can be re-thought in a different way. 

there will be release notes for all upcoming versions.
