### ISSUE TITLE
Update librdkafka.redist dependency to 1.5.2

### ISSUE THREAD

**Issue by GureevLeonid** [confluentinc/confluent-kafka-dotnet#1432]
Description
===========

edenhill just released new version of librdkafka https://github.com/edenhill/librdkafka/releases/tag/v1.5.2
It contains many fixes.
Like this one https://github.com/edenhill/librdkafka/issues/2933, it's periodically reproducing in our production environment and we are fixing it with consumer recreation.
It would be great to remove hacks from our code and update librdkafka dll's.

**Comment by mhowlett** [comment]
1.5.2-RC1 is already on nuget and I don't think there are changes, i'll do the final release later today probably.

**Comment by amotl** [comment]
Confluent.Kafka 1.5.2 has been released, see https://www.nuget.org/packages/Confluent.Kafka/. Thanks a bunch, @mhowlett and @edenhill!

I believe this issue can well be closed then.
