### ISSUE TITLE
Cannot use JsonValueSerializer<T> for types without a public, parameterless constructor

### ISSUE THREAD

**Issue by ahernandez-allegion** [confluentinc/confluent-kafka-dotnet#1434]
Description
===========

A Producer cannot use `JsonValueSerializer<T>` if the type  does not have a public, parameterless ctor. This is quite limiting as it prevents using existing libraries such as `CloudEvents`:

https://github.com/cloudevents/sdk-csharp

See also: https://github.com/cloudevents/sdk-csharp/blob/master/src/CloudNative.CloudEvents.Kafka/KafkaCloudEventMessage.cs

How to reproduce
================

When constructing a `Producer` using the `ProducerBuilder`, use `JsonValueSerializer<T>()` where `T` does not meet the `new()` constraint.

```
public class CloudEvent {
  public string Id { get; set; }

  public CloudEvent(string id) {
    Id = id;
  }
}

var producer = new ProducerBuilder<string, CloudEvent>(producerConfig)
                .SetValueSerializer(new JsonSerializer<CloudEvent>(schemaRegistryClient, jsonSerializerConfig))
                .Build();
```

`AvroSerializer<T>` does not have this constraint. Also, while `ProtobufSerializer<T>` does, it has an additional constraint on `IMessage<T>`, which also implies it could not support `IMessage<T, U>`.

Workaround
================

It seems the only workaround would be to use Avro or to write a custom implementation of `IAsyncSerializer<T>`.

Checklist
================

[1.5.2] Confluent.Kafka version

**Comment by mhowlett** [comment]
thanks @ahernandez-allegion - I just merged a change by @appleseed7even to fix this to master, so it'll be in 1.6.
