### ISSUE TITLE
[Question] Disable Disk IO/history

### ISSUE THREAD

**Issue by LiorBanai** [confluentinc/confluent-kafka-dotnet#1441]
Hi,

I'm using the latest version and have  some issues where the consumer/client keep getting old data and the disk performance is very slow which causes some delay.

In my application I'm interesting in real time data only, meaning I don't need or want to save/access old data. This mean that only clients that are connected when also a producer is alive and sending messages they will get those. In effect no need to save data to disk..

Is there a way to configure this mode? or at least reduce the disk usage to minimal without impact performance (non ssd disk)?

**Comment by mhowlett** [comment]
it's not exactly, but you can set the retention period on the broker to be very short to minimize the amount of data stored, and you can assign to a partition with offset `Partition.End` when you start reading from it to only get latest messages after it connects. disk is not usually a bottleneck, what is your throughput?

**Comment by LiorBanai** [comment]
WE have seen clear problems with non ssd disks. How would you print the throughput? is it part of the statistics (we are printing them every minute to log)

**Comment by mhowlett** [comment]
the client statistics `rx_bytes` and `tx_bytes` show the number of bytes received and transmitted to Kafka brokers (ever increasing counter) - but i mean just roughly, how many messages per second / how big are the messages approximately.

https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by LiorBanai** [comment]
Thanks, I'll check this
