### ISSUE TITLE
Question: Is lock required in the transactions example

### ISSUE THREAD

**Issue by alex-basiuk** [confluentinc/confluent-kafka-dotnet#1442]
Hi @mhowlett ,

I came across your [Transactions example](https://github.com/confluentinc/confluent-kafka-dotnet/blob/e5503c170662067a751710d027ddf06521e1ac73/examples/Transactions/Program.cs) recently. Are you sure [the lock](https://github.com/confluentinc/confluent-kafka-dotnet/blob/e5503c170662067a751710d027ddf06521e1ac73/examples/Transactions/Program.cs#L294) on `producerState` is required? 
```c#
lock (producerState)
{
	producerState.Add(tp, new ProducerState<string, Null> { Producer = p, Offset = Offset.Unset });
}
```
If yes, why we don't sync in the [`SetPartitionsRevokedHandler`](https://github.com/confluentinc/confluent-kafka-dotnet/blob/e5503c170662067a751710d027ddf06521e1ac73/examples/Transactions/Program.cs#L294)?

**Comment by mhowlett** [comment]
everything operates in the consumer poll loop on a single thread, so a lock is mostly not required. In the location you point out though, the example is parallelising the construction of the producers - there are multiple threads running. so we need to synchronize access to the producerState dictionary (but only here, not elsewhere). I believe the example is correct.
