### ISSUE TITLE
Bad performance in 1.5.2 vs 1.3.0

### ISSUE THREAD

**Issue by LiorBanai** [confluentinc/confluent-kafka-dotnet#1444]
After upgrading to 1.5.2 we have worse performance of real time streaming (basically it is unusable).
This is probably due to some defaults that  have changed on the producer side between versions that we are not setting and have negative impact.

Is there a way to print all the settings of the producer after it is created?
We would like to compare all settings of 1.5.2 vs 1.3.0 to find what tare the changes.
Is it possible?

**Comment by mhowlett** [comment]
It's not possible to get the merged user/default config after startup with the .net client.

We've changed some defaults as per https://github.com/edenhill/librdkafka/issues/2853, which were optimized for extremely high throughput use cases. The downside was a lot of latent network usage and excessive pre-caching for most users (causing problems for users paying for usage based on bandwidth).

The new defaults are still high, and should be suitable for the majority of use cases (even high throughput).

**Comment by LiorBanai** [comment]
we have exactly  the opposite effect of this.  We tested it few time by having the same code running with 1.3.0 and with 1.5.2 side by side...
we will investigate this more...

**Comment by mhowlett** [comment]
You might also like to enable debug logging (may be very verbose if throughput is high). Perhaps `Debug` = `broker` will help, or `broker,protocol` or `all` if you can.

**Comment by LiorBanai** [comment]
Thanks. I'll also check this
