### ISSUE TITLE
Not able to send messages to kafka asynchronously and get a callback to handle the errors (if any) later

### ISSUE THREAD

**Issue by AdikaSinghvi** [confluentinc/confluent-kafka-dotnet#1448]
Description
===========
We are using Confluent.Kafka 1.5.2. For serializing keys and values, we use Confluent.SchemaRegistry.Serdes.Avro 1.5.2. 
Apache.Avro contract version is 1.9.1.

We are trying to use the below Produce API to send messages asynchronously and get a callback at a later point. We plan to handle the errors via callback.
void Produce(string topic, Message<TKey, TValue> message, Action<DeliveryReport<TKey, TValue>> deliveryHandler = null);

At runtime, we are getting error "System.InvalidOperationException: Produce called with an IAsyncSerializer key serializer configured but an ISerializer is required.
   at Confluent.Kafka.Producer`2.Produce(TopicPartition topicPartition, Message`2 message, Action`1 deliveryHandler)"

How to reproduce
================
 producerBuilder = new ProducerBuilder<string, T>(producerconfig)
                            .SetKeySerializer(new Confluent.SchemaRegistry.Serdes.AvroSerializer<string>(schemaRegistryconfig))
                            .SetValueSerializer(new Confluent.SchemaRegistry.Serdes.AvroSerializer<T>(schemaRegistryconfig))
                            .Build();

producerBuilder.Produce(topicName, data, CallbackHandler);

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.5.2
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by mhowlett** [comment]
you need to convert the async serializer into a sync one. there's a helper method for this:

`using Confluent.Kafka.SyncOverAsync;`

then use `.AsSyncOverAsync()` on the serializer instance.
