### ISSUE TITLE
FlushAsync?

### ISSUE THREAD

**Issue by icambron** [confluentinc/confluent-kafka-dotnet#1449]
My scenario is that I'm running in an asynchronous context, producing a lot of messages, and waiting for them to be delivered. Of course I could produce them one at a time with `ProduceAsync`, but that seems unnecessarily slow. The readme shows this pattern:

```cs
        using (var p = new ProducerBuilder<Null, string>(conf).Build())
        {
            for (int i=0; i<100; ++i)
            {
                p.Produce("my-topic", new Message<Null, string> { Value = i.ToString() }, handler);
            }

            // wait for up to 10 seconds for any inflight messages to be delivered.
            p.Flush(TimeSpan.FromSeconds(10));
        }
```

which makes sense, but `Flush` blocks the thread, which is going to cause all sorts of other problems in my asynchronous methods. I'd like an asynchronous way to do know when my "batch" of messages have all been delivered.

My only current alternative is to keep a counter and increment it from all my callbacks, poll that counter until it matches my expected count (or a timeout), and wrap that all up in an async method. That's both cumbersome and doesn't actually whatever it is `Flush` actually does.

Does it make sense to add a `FlushAsync` to the lib?

**Comment by mhowlett** [comment]
the reason we don't have this is technical constraints imposed by librdkafka. generally, you should only need to call Flush on exit. in that context, it's fine to just use `Task.Run(() => p.Flush(timeout))`, and that is better than blocking a thread that is assumed to not block by the runtime. If you want to wait on a batch of messages, you don't need to await `ProduceAsync`, you can put multiple tasks into an array and `await Task.WaitAll`.

**Comment by icambron** [comment]
Thanks. If `Flush` is only for exit, I think the readme should clarify that. I agree that putting it in `Task.Run` is ok there, but it's not in the general case, since it still blocks a thread.

Re: `await Task.WaitAll`: I tried that first, and had some issues with it. If that's the recommended approach, I'll go back and give it another shot. Could have just been user error.

For reference, this is my current implementation:

```cs
    public class AsyncKafkaBatcher<T1, T2>
    {
        private int _errored, _delivered, _sent;
        private readonly IProducer<T1, T2> _producer;

        public AsyncKafkaBatcher(IProducer<T1, T2> producer)
        {
            _errored = 0;
            _delivered = 0;
            _sent = 0;
            _producer = producer;
        }

        public void Produce(string topic, Message<T1, T2> message, Action<DeliveryReport<T1, T2>> callback)
        {
            _producer.Produce(topic, message, WrapCallback(callback));
            Interlocked.Increment(ref _sent);
        }

        public async Task<BatchDeliveryReport> Flush(TimeSpan timeout)
        {
            var stopwatch = Stopwatch.StartNew();
            while (true)
            {
                var timedOut = stopwatch.Elapsed > timeout;
                if (timedOut || _sent == _delivered + _errored)
                {
                    stopwatch.Stop();
                    return new BatchDeliveryReport
                    {
                        TimedOut = timedOut,
                        Errored = _errored,
                        Delivered = _delivered
                    };
                }

                await Task.Delay(TimeSpan.FromMilliseconds(500));
            }
        }
        
        private Action<DeliveryReport<T1, T2>> WrapCallback(Action<DeliveryReport<T1, T2>> callback) =>
            dr =>
            {
                if (dr.Error.IsError)
                {
                    IncrementErrored();
                }
                else
                {
                    IncrementDelivered();
                }

                callback(dr);
            };

        private void IncrementDelivered() => Interlocked.Increment(ref _delivered);
        private void IncrementErrored() => Interlocked.Increment(ref _errored);

```

**Comment by mhowlett** [comment]
> Thanks. If Flush is only for exit, I think the readme should clarify that. I agree that putting it in Task.Run is ok there, but it's not in the general case, since it still blocks a thread.

It does not block a thread that the scheduler assumes will not block though, so it's a valid solution.

When I said `Flush` is usually only used on exit, it's also the case that you don't generally need to wait for a batch of delivery reports. If you do want to do that `Flush` is fine (and you can await the run). `Task.WaitAll` is also fine. The above approach is unnecessarily complicated.
