### ISSUE TITLE
Kafka Version

### ISSUE THREAD

**Issue by handaxin** [confluentinc/confluent-kafka-dotnet#1450]
Description
===========
What is the current Kafka Version ?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
2.6

https://kafka.apache.org/downloads

**Comment by handaxin** [comment]
Sorry, I didn't make that clear. Actually, I want know what is the version of kafka in confluent-kafka-dotnet.

**Comment by edenhill** [comment]
confluent-kafka-dotnet is a Kafka client, it does not bundle the Kafka server.  confluent-kafka-dotnet works with any Apache Kafka version >= 0.8.

**Comment by handaxin** [comment]
> confluent-kafka-dotnet is a Kafka client, it does not bundle the Kafka server. confluent-kafka-dotnet works with any Apache Kafka version >= 0.8.

I understand. Thank you very much!
