### ISSUE TITLE
MaxPollRecords Not Available on the ConsumerConfig

### ISSUE THREAD

**Issue by justin-souders** [confluentinc/confluent-kafka-dotnet#1451]
Description
===========
We have a long running process tied to our records that can sometimes result in a `Application maximum pool interval exceeded` message being thrown.  There is currently a `MaxPoolIntervalsMS` property on the `ConsumerConfig` that we can set to help with this issue, but we only encounter this when getting a large amount of records at once.  Based on some articles and documentation I have read there is a configuration option called `max.poll.records` that can be set to limit the amount of records per poll.  The default is 500, but I would like to try changing this to a smaller value to see if this helps with the error.  The issue I have is there is not a property exposed on the `ConsumerConfig` for the `max.pool.records` setting.  Is this by design or am I missing something?

**Comment by mhowlett** [comment]
`max.poll.records` isn't relevant to the C# consumer (or any other librdkafka based client) because messages are delivered one at a time to the application. in the java client, they are delivered in batches.

**Comment by justin-souders** [comment]
@mhowlett I did not realize that C# and Java consumers had different strategies for message polling.  Thank you for the response!

**Comment by fcu423** [comment]
> it's a design choice that mimics the librdkafka API. you could easily create a batch consume method if you want it that simply consumes up to N messages then returns them in a collection. it's not a design flaw, or performance limitation - librdkafka has higher consume throughput than the java client.

Thanks for your answer, that makes a lot of sense. I've been thinking about it more, and I am wondering how are the different Kafka settings that apply to "batching" work with Kafka .NET then? Are they ignored or do they simply apply for a single message that is returned with each Consume call?

**Comment by mhowlett** [comment]
librdkafka fetches / produces messages to the broker in batches like the java client. it differs in that messages are delivered to the application one-by-one on consume.

**Comment by shazilanjum** [comment]
@mhowlett Don't the messages load in buffer during fetch? Then the consumer loop polls them one by one? Basically i want to limit the number of messages loaded into buffer during fetch
