### ISSUE TITLE
When to support interceptor ??

### ISSUE THREAD

**Issue by JokerBoom** [confluentinc/confluent-kafka-dotnet#1454]
Description
===========

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
we have no near term plans to add support for interceptors at the C# level.

librdkafka has an interceptor API, but you'll need to write them in C, and you won't be able to share state from C# code easily.

**Comment by careless6666** [comment]
Interceptors were useful both for metrics, logs and traces

**Comment by douglasg14b** [comment]
Interceptors are *vital* when you have encrypted messages & headers....

Never mind useful for all the other reasons.
