### ISSUE TITLE
Compression in producer not working

### ISSUE THREAD

**Issue by FreeAndNil** [confluentinc/confluent-kafka-dotnet#1455]
Description
===========
Setting ProducerConfig.CompressionType has no effect (because it sets "compression.type" and not "compression.codec").
See also: https://stackoverflow.com/questions/64699151/kafka-message-size-with-activated-compression

How to reproduce
================
- create a big payload with redundant text (e.g. 2 million A's)
- create a producer with ProducerConfig.CompressionType = CompressionType.Zstd
- produce a message with the payload
-> the broker won't accept the message because 2 MB is uncompressed more than 1 MB (which is the default message limit)
-> calling producerConfig.Set("compression.codec", "zstd") solves the problem

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.3.0
 - [x] Apache Kafka version. 2.6.0
 - [ ] Client configuration.
 - [x] Operating system. Producer: Windows 10 20H2, Broker: Ubuntu 20.04 LTS
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by FreeAndNil** [comment]
@mhowlett I have no idea how to adjust the ConfigGen.
Can you provide a hint?
Then I could create a PR.

Thanks.

**Comment by mhowlett** [comment]
`compression.type` is an alias for `compression.codec`. we choose to only expose a single name for each config property in the .net strongly typed config classes, and we chose compression type (in hindsight, compression codec is probably the nicer name). so rather than change ProducerConfig, we need to understand why it's apparently not working.

Are you seeing this with v1.5.2?

**Comment by FreeAndNil** [comment]
I found it, the problem was that producerConfig.MessageMaxBytes was not big enough for the uncompressed message.
Raising this setting solved the problem.

**Comment by alfhv** [comment]
I have similar issue, I’m trying to send a big message setting CompressionType = GZip but producer reject it with « Message too long ». 
Is not enough to set the compression type ? I need to change some other configuration values ?
I would like to modify only on producer side, not in broker or consumer.

**Comment by FreeAndNil** [comment]
We changed the following on the producer site:
`ProducerConfig producerConfig = new()`
`{`
`  ...`
`  CompressionType = CompressionType.Zstd, // must be the same as on the brokers`
`  MessageMaxBytes = 20 * 1024 * 1024, // is the maximum uncompressed size (checked before compression)`
`  ...`
`};`

**Comment by alfhv** [comment]
Thanks, it is working for me.
But I would like to inderstand better how config works around compression.

If producer dont set compression, and topic is configured with some ‘compression.type’ then the messages will be compressed when stored in kafka ? 

During my tests, topic is configured with some compression.type and I’m configuring Producer with a different one and messages are accepted, in that case, which compression.type Is used ? Topic or Producer one ??

**Comment by FreeAndNil** [comment]
When compression is only configured on broker or different between producer and broker, the message gets compressed or de- and again compressed on the broker. You probably don't want that because it increases the load on the broker.

**Comment by alfhv** [comment]
So correct if necessary:

Given max.size on broker is 1M, max.size on producer is 5M,

If topic compression is set and producer compression is not set, then when sending a msg of 8M(uncompressed) it will be rejected on producer.

If topic compression is set and producer compression is not set, then when sending a msg of 4M(uncompressed)/400K(compressed) it will be accepted by broker and compressed in broker.

If topic compression is set and producer compression is set, then when sending a msg of 8M(uncompressed)/400K(compressed) it will be rejected by producer.

If topic compression is set and producer compression is set, then when sending a msg of 4M(uncompressed)/400K(compressed) it will be compressed by producer and accepted by broker.

If topic compression is set and producer compression is set, then when sending a msg of 4M(uncompressed)/2M(compressed) it will be compressed by producer BUT rejected by broker.

**Comment by christiankittel** [comment]
That's it.

**Comment by lorines** [comment]
do we need to decompress on the consumer side?
