### ISSUE TITLE
Consumer subscribe patterns interfere with ACL

### ISSUE THREAD

**Issue by stefan-benjamin** [confluentinc/confluent-kafka-dotnet#1457]
Description
===========

When specifying a subscribe pattern on the Kafka consumer, _describe_ is called on all topics, also those that do not fit the user's ACL, causing the Kafka broker to log authorization error.

As an example, the Kafka cluster has the following 2 topics:
- data.unit1
- test.data.unit1

A user has been created, having ACL to access data topic, but not test topic. The user was configured with the following ACL settings: `--allow-principal User:user1 --operation All --topic 'data.'`

If the user subscribes only to `data.unit1`, everything is fine. However, if the user subscribes to the topic using the pattern `^data.*`, the Kafka broker logs: `Principal = User:user1 is Denied Operation = Describe from host = XX.XX.XX.XX on resource = Topic:LITERAL:test.data.unit1`. The subscription behavior however works as expected.

Using:
- Confluent.Kafka nuget version 1.5.2
- Confluent.SchemaRegistry version 1.5.2
- Confluent.SchemaRegistry.Serdes.Avro version 1.5.2
- librdkafka.redist version 1.5.2

- Kafka cluster version 2.5.1

Is there any way to avoid this unnecessary logging? I think the consumer should call describe only for the topics matching the subscription patterns...

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [ ] Operating system.
 - [ ] Client configuration.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [X] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
I'm guessing the user has DESCRIBE but not READ access to the test topic, which means the consumer will see test.data.unit1 and thus subscribe to it, but not be able to actually fetch messages, and that's when the auth logs are generated.

**Comment by stefan-benjamin** [comment]
I reproduced the issue and I attached the consumer log. I can see that `test.data.unit1` is not present in the log. However, the error appears on the Kafka broker side, in the `kafka-authorizer.log` file:

`Principal = User:user1 is Denied Operation = Describe from host = <client IP> on resource = Topic:LITERAL:test.data.unit1`

The error seems to appear every 5 minutes, each time the consumer refreshes the metadata, as the `metadata.max.age.ms` consumer configuration is left default (5 minutes).

[consumer.log](https://github.com/confluentinc/confluent-kafka-dotnet/files/5524096/consumer.log)

**Comment by edenhill** [comment]
Sorry, that should've been `Debug: "topic,protocol,cgrp,metadata"`. Can you create a new log?

**Comment by stefan-benjamin** [comment]
I created a new log - hope this helps to identify the issue. It seems that, as you say - the consumer tries to describe/list all the topics if a pattern is provided. But this approach is not in accordance with the ACL.

[consumer_2.log](https://github.com/confluentinc/confluent-kafka-dotnet/files/5524384/consumer_2.log)

**Comment by edenhill** [comment]
There is no mention of test.data.unit1 in that log file, which means the client does not reference it explicitly but only by enumerating all topics in the cluster and that is what triggers the auth log.
There is nothing the consumer can do to circumvent that, it needs to list all topics to be able to do wildcard matching of the subscription.

**Comment by stefan-benjamin** [comment]
I understand, I thought it is possible to request a list of topics based on a pattern directly from the kafka broker. Shall we conclude that getting the authentication error on the kafka broker is normal/expected in this scenario?

**Comment by edenhill** [comment]
I think there are plans for broker-side wildcards, but not yet supported.

As for the access logs on full metadata listing, maybe that should be considered an issue with the broker, so perhaps file an AK JIRA?

**Comment by stefan-benjamin** [comment]
I close the issue, I have added a JIRA issue regarding this, hopefully the description makes sense for the Kafka team. https://issues.apache.org/jira/browse/KAFKA-10717
