### ISSUE TITLE
Deserializing avro message with our schema registry

### ISSUE THREAD

**Issue by E4M9i** [confluentinc/confluent-kafka-dotnet#1466]
Description
===========
Hi there, 
Is there anyway that I can deserialize messages that have been produced with schema registry and avro serializer,
The point is I want to consume message first as string and then desrialize it based on avsc file or any other mechanism and convention.
My program don't need typed models as the goal is to just store data, converting consumed avro message to json will do the work.
Problem is when I register my consumer with string value type I cant get proper value.
Thanks

**Comment by mhowlett** [comment]
The wire format used by confluent serdes is as follows: https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#wire-format

The serialized data for avro messages is everything after the first 5 bytes. You should be able to use that with the `Apache.Avro` library to deserialize messages given the avsc file.

**Comment by milindl** [comment]
Closing this as the question is answered by the comment above. Please reopen in case of a follow up.
