### ISSUE TITLE
Question: How to synchronize Producer and Consumer with StoreOffset?

### ISSUE THREAD

**Issue by WolfspiritM** [confluentinc/confluent-kafka-dotnet#1469]
Description
===========
I have some rare cases where messages get lost and I'm not yet sure when and how that can happen.
My usecase currently has a Consumer consuming messages, working on the messages and Procuding the result into another topic. I don't await ProduceAsync cause of performance reasons and after the work is done and produceasync is called I call StoreOffset.

```c#
async Task Main()
{	
	var c = new CancellationTokenSource().Token;	
	while(!c.IsCancellationRequested) {
		try {
		    var msg = consumer.Consume(c);
			await DoWork(msg.Message.Value);
			consumer.StoreOffset(msg);						
		} catch (OperationCanceledException) {
			break;
		}
		// catch ...
	}
}

async Task DoWork(byte[] data)
{
	await Task.Delay(100); // Some work
	_ = producer.ProduceAsync("test", new Message<string, byte[]>() { Key = "test", Value = data });
}
```

As StoreOffset just marks an offset as "commitable" and ProduceAsync actually waits for a batch of messages to be send before actually sending I wonder if for example the broker goes down the offset gets commited but the batch of messages created by ProduceAsync is not transferred correctly before shutdown of my application.

Now I'm wondering what the best practice is to "synchronize" these two without awaiting produce async.

My current idea was to push a function into my "DoWork" method and execute it within ContinueWith but that feels kind of ugly:

``` c#
async Task Main()
{	
	var c = new CancellationTokenSource().Token;	
	while(!c.IsCancellationRequested) {
		try {
			var msg = consumer.Consume(c);
			await DoWork(msg.Message.Value, () => consumer.StoreOffset(msg));					
		} catch (OperationCanceledException) {
			break;
		}
		// catch ...
	}
}

async Task DoWork(byte[] data, Action Commit)
{
	await Task.Delay(100); // Some work
	_ = producer.ProduceAsync("test", new Message<string, byte[]>() { Key = "test", Value = data })
		.ContinueWith((x) =>
		{
			if(x.Exception == null) {
				Commit();
			}
		});
}
```

What would be the recommended way to handle that?

**Comment by mhowlett** [comment]
(after reading quickly) - if you're not waiting for the delivery report, then you don't know for sure if the message gets delivered or not. if you're using store offsets / auto commit, you don't know for sure if the offsets get committed. you seem to have a read-process-write workflow - this is what transactions are designed for. if you only have single partition topics, this feature is good to use now. if you have multi-partition topics, KIP-447, which should be coming soon, makes this much easier.

**Comment by milindl** [comment]
Closing the issue as the answer is in the comment. Please reopen for further questions.
