### ISSUE TITLE
[Question] Use routing key for consume related event ?

### ISSUE THREAD

**Issue by NicolasReyDotNet** [confluentinc/confluent-kafka-dotnet#1471]
Description
===========
Hi, I wonder if it's possible to use any mechanism to route related event (ie same provided correlation id, or orderId or whatever that can link two events in term of business) when they are consumed by load balanced consumers (same groupId) on same topic ?

My point is to use this kind mechanism to project downstreams of domain aggregates with a high rate of events production, events that can be be related to each others (same orderId for example) and that I absolutely need to project in their current topic ordering persistence. With a routing key, I'll ensure that all related events of the same orderId for example are consumed and processed by the same instance, thus in the expected ordering as they are produced. 
If I can't use this kind of mechanism, nothing guarantee me that if two related events are balanced to two different instances of my consumer (same groupId) they will be able to process them in the order they have been consumed (due to network latency, database behavior or whatever ...). It leads me to use only one instance of my consumer, which is a pity in term of scalability.

Could you advice me on that ?
Many thanks for your amazing work, I use your lib every day and I enjoy it a lot!

**Comment by mhowlett** [comment]
right, that's what partitioning is for (set the thing you want to partition on as the key). using consumer groups isn't compatible with your requirements though as i understand them, because the group can rebalance, changing which node processes which key. so you'll want to manually assign (don't use subscribe) partitions to each of your nodes. you'll need some strategy compatible with your requirements if you ever want to scale up/down though (you may want a custom partitioning strategy to help with that, coming in 1.6).

**Comment by NicolasReyDotNet** [comment]
@mhowlett thank you, it's exactly what I need, do you know if these custom strategies will be able to be based on data from the event payload ? 
For example : let's say odd orderId goes to consumer instance1 and event orderId goes to consumer instance2 .

**Comment by mhowlett** [comment]
you can partition based on message key, so if you put orderId in the key, then you can partition on that. Note that this capability is in 1.6.0-PRE1, which is on nuget already. But that release is not production ready.

https://github.com/confluentinc/confluent-kafka-dotnet/blob/1.6.x/src/Confluent.Kafka/ProducerBuilder.cs#L54

**Comment by NicolasReyDotNet** [comment]
@mhowlett you made my day! I'll follow the release with interest

**Comment by pranavrth** [comment]
This is released. Closing the issue. Please raise a new one if you need more help.
