### ISSUE TITLE
Creating Producer and Consumer using SSL Security protocol

### ISSUE THREAD

**Issue by jbhardwaj-tc** [confluentinc/confluent-kafka-dotnet#1472]
Description
===========

I am using the example here: https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/Web.
My Kafka cluster requires SSL security protocol and passing the certificate. So when creating the producer and consumer's I update the following properties in the **ClientConfig** as such

    config.EnableSslCertificateVerification = false;
    config.SecurityProtocol = SecurityProtocol.Ssl;
    config.SslCertificatePem = certificate.Certificate;
    config.SslKeyPem = certificate.PrivateKey;

The problem is that the certificate is valid only for 24 hours (and I can't change that). Which means that after 24 hours, my producer and consumer instances will have an invalid certificate. I can identify when the certificate has expired. But what's the best way to reconstruct the Producer and Consumer instances at runtime?

I am using **ASP.Net Core** and registering the Producer and Consumer instances as **Singletons**

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
you should encapsulate the capability to recreate the Confluent.Kafka.Producer instance as part of the instance type you register as a singleton.
