### ISSUE TITLE
No deep copy of config parameter collection. why?

### ISSUE THREAD

**Issue by koshdim** [confluentinc/confluent-kafka-dotnet#1478]
Description
===========
I noticed this description in Config constructor
_This will change the values "in-place" i.e. operations on this class WILL modify the provided collection_
after I spend a day debugging my code assuming there is deep copy there. Why was it implemented this way?

I had an issue because config instance was reused for multiple producer, one with TransactionId set in my code, another - as it is. But setting TransactionId sets it for both configs, which results one Producer to throw "Local: Erroneous state" ProducerException, which is very hard to deal with.

How to reproduce
================
 var producerConfig0 = producerConfig;
 var producerConfig1 = new ProducerConfig(producerConfig) { TransactionalId = Guid.NewGuid().ToString() };
 var producer = new ProducerBuilder<string, string>(producerConfig0).Build();
 producer.Produce(...); <-- Erroneous state

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [* ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [* ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
yeah, I agree with you. there's a long argument in an issue/pr somewhere I was having with a contributor about this and in the end I let him have his way (shouldn't have). we can't change it now unfortunately - breaking the API is worse, it's not a big enough deal to do that.

**Comment by koshdim** [comment]
>  breaking the API is worse

indeed. thanks for quick response! other than this, thanks for awesome package!
