### ISSUE TITLE
Producer defaults are not applied?

### ISSUE THREAD

**Issue by LiorBanai** [confluentinc/confluent-kafka-dotnet#1489]
Description
===========
I'm using the following producer:
```csharp
            producerConfig = new ProducerConfig
            {
                BootstrapServers = _kafkaServerURL,
                Acks = Acks.All,
                EnableIdempotence = true,
                StatisticsIntervalMs = 60 * 1000,
                 };
```
with those settings I'm getting delays in producing:
![kafka_delay](https://user-images.githubusercontent.com/36262995/103241145-020a1980-495b-11eb-9d28-8a5cde37b851.gif)
 
but if I add   ```LingerMs = 0.5``` there is no delay:
![kafka_no_delay](https://user-images.githubusercontent.com/36262995/103241177-1cdc8e00-495b-11eb-89a1-664054a5ad21.gif)

Why is that? I assumed defaults are applied without the need to specify them in code (it even says default value 0.5 for Linger)..
I'm using V1.3.0

**Comment by mhowlett** [comment]
thanks for letting us know - this is odd, i don't know how specifying the default explicitly could have this effect. would be interested to know if you see this with v1.5.3, and if so, would be interesting to see some Debug=all logs covering a period with the delay. definitely recommend 1.5.3 over 1.3.0 (bug fixes).

**Comment by LiorBanai** [comment]
we had to revert back to 1.3 due to bad performance with 1.5 (https://github.com/confluentinc/confluent-kafka-dotnet/issues/1444). I'll try again with 1.5 by setting back the defaults that were not good for us in V1.5 and then check the linger value if needed or not.

I'll update..

**Comment by mhowlett** [comment]
we aren't aware of any performance issues with v1.5. if you provide a small code snippet demonstrating the issue, we can either comment on the code of investigate further.
