### ISSUE TITLE
Consumer lag

### ISSUE THREAD

**Issue by Abby86** [confluentinc/confluent-kafka-dotnet#1490]
Hi 

we have a .Net consumer reading message from a kafka topic with 3 partition. We are noticing lag in the consumer reading messages. At times there is a lag of more than 15 sec when it is posted in topic and when it was picked up. We are using 1.4.3 version. Can you please suggest what can be the issue.

consumer config

statisticsintervalms:36000
Sessiontimeoutms:36000
Enableautocommit:false
Enablepartitioneof:true
Autooffsetreset:Latest

can you please help.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by Abby86** [comment]
Hi Matt - can you please assist. Any setting which maybe missing or misconfigured

Thanks

**Comment by mhowlett** [comment]
are you using confluent cloud on azure?

what is your throughput approximately? msgs/s?

it is hard to know without more information. if you provide `Debug`=`all` logs over a period of time where you believe a message is in a topic to be consumed, but the consumer did not receive it quickly, we can probably tell a lot from that. please be as specific as possible about timing, including a timestamp for the delivery report for the produced message if possible for correlation with the logs.

**Comment by Abby86** [comment]
Hi Matt.. No the consumer in running on the windows server with kafka
broker on linux.

The msgs throughput is really small i.e. around 5 msg per 10 sec.

In the kafka monitor i see the message is available at a particular time
but it is getting picked up by consumer 10-15 secs late. This is happening
with only couple of topics, for other topics it gets picked up in < 50 ms.
Logs will be difficult to provide due to policy. Can you please guide if
there is something missing in the consumer setting or what in the logs I
can check. The logs are pretty huge so any guidance will be helpful.
