### ISSUE TITLE
Using SyncOverAsync Produce in Full Framework doesn't return the first few times it's called

### ISSUE THREAD

**Issue by tjochums** [confluentinc/confluent-kafka-dotnet#1492]
Description
===========
We have an application running the Dot Net Full framework, and we're using the SyncOverAsync currently, and when we call produce, I'm seeing a behavior where the first two times produce gets called during execution, it does not return, and then after that it starts working. 

How to reproduce
================
To start with we're using version 1.5.3 of the confluent libraries

We're using the AvroSerializer with a CachedSchemaRegistryClient and it looks like inside of that, when the cache isn't loaded and it makes a call to the the schema registry for the key, the await never returns, the next time I call, it has loaded the key, but needs to call the registry for the value, so it never returns, and then subsequent calls, the registry is loaded.

In the [Avro Serializer](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializer.cs)
```
       public async Task<byte[]> SerializeAsync(T value, SerializationContext context)
        { 
            try
            {
                if (serializerImpl == null)
                {
                    serializerImpl = typeof(T) == typeof(GenericRecord)
                        ? (IAvroSerializerImpl<T>)new GenericSerializerImpl(schemaRegistryClient, autoRegisterSchema, initialBufferSize, subjectNameStrategy)
                        : new SpecificSerializerImpl<T>(schemaRegistryClient, autoRegisterSchema, initialBufferSize, subjectNameStrategy);
                }

                return await serializerImpl.Serialize(context.Topic, value, context.Component == MessageComponentType.Key);
            }
            catch (AggregateException e)
            {
                throw e.InnerException;
            }
       }
```
If I change the await to ConfigureAwait(continueOnCapturedContext: false) like done elsewhere in the library, it resolves the problem I'm encountering. (Note [AvroDeserializer](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Avro/AvroDeserializer.cs) also has the issue though we're not using it in this case)

Also, if I pre-load the schema cache before making the produce call, it ends up working as well since it doesn't need to call the out to the schema registry first.

**Comment by mhowlett** [comment]
thanks @tjochums - that's an oversight. this will be in v1.6.0
