### ISSUE TITLE
Is this correct example for Kafka Transactions?

### ISSUE THREAD

**Issue by koshdim** [confluentinc/confluent-kafka-dotnet#1496]
Description
===========
How I use Kafka Transactions in my code:

```
using IProducer<string, string> producer = new ProducerBuilder<string, string>(_producerConfig).Build();
producer.InitTransactions(_defaultTransactionTimeout);
_consumerConfig.AutoOffsetReset = AutoOffsetReset.Earliest;
using var consumer = new ConsumerBuilder<string, string>(_consumerConfig).Build();
consumer.Subscribe(_consumeTopic);

while (!stoppingToken.IsCancellationRequested)
{
var consumeResult = consumer.Consume(stoppingToken);

producer.BeginTransaction();

producer.Produce(_produceTopic, new Message<string, string>   {...  });

producer.SendOffsetsToTransaction(new List<TopicPartitionOffset> { consumeResult.TopicPartitionOffset}, consumer.ConsumerGroupMetadata, _defaultTransactionTimeout);

producer.CommitTransaction(_defaultTransactionTimeout);
}
```

Is this correct way to use Kafka Transactions? It works most of the time but sometimes it fails with error below:

```

%1|1609846051.178|TXNERR|rdkafka#producer-2| [thrd:main]: Fatal transaction error: Failed to add offsets to transaction: Broker: Producer attempted an operation with an old epoch (INVALID_PRODUCER_EPOCH)
%3|1609846051.178|ERROR|rdkafka#producer-2| [thrd:main]: Fatal error: Broker: Producer attempted an operation with an old epoch: Failed to add offsets to transaction: Broker: Producer attempted an operation with an old epoch
```

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [* ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
yes, that's broadly right. there is an example https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/Transactions . that error indicates you have another producer with the same `transactional.id` started after this application. side note: you need to make sure you disable auto commit on the consumer (which is on by default) - not sure if you're doing that.

1.6.x is adding KIP-447 support which makes using transactions much easier. there will be a new example. we also currently plan on doing a blog post about transactions this quarter (probably with python examples, but those will translate directly to .net).

**Comment by koshdim** [comment]
> note: you need to make sure you disable auto commit on the consumer (which is on by default) - not sure if you're doing that.

yes, I didn't disable auto commits explicitly, thanks.

>  that error indicates you have another producer with the same transactional.id started after this application.

what if the application crashes/killed and then restarts on the machine? the producer will be recreated, could this be the reason? if yes, should I do some cleanup when starting new Producer?

would random generation on each Producer initialization be bad idea?

thanks

**Comment by mhowlett** [comment]
> would random generation on each Producer initialization be bad idea?

yes, the transactional id is what identifies the producer across process restarts, if you use random transactional ids, you won't get exactly once semantics.

> what if the application crashes/killed and then restarts on the machine? the producer will be recreated, could this be the reason? if yes, should I do some cleanup when starting new Producer?

the reverse should be true (any old zombie producers will be fenced by this error, and the new should work). i hesitate in answering this though because i did notice an example where I think I saw what you say happen. it's on my list to dig deeper to clarify my understanding / look into soon.

regardless, if you get this error, it won't cause duplicate messages if you restart in that case (and make sure you're only using one producer instance per transactional.id at any given time).

**Comment by koshdim** [comment]
funny thing is I observed this error only when starting the app and new producer tries to produce first message. thanks for suggestion, I guess it can be because producer with the same transactional.id running elsewhere at the moment...

**Comment by koshdim** [comment]
hi @mhowlett , I checked the example you provided and implemented that approach. but when I call AbortTransaction() in SetPartitionsRevokedHandler like in example, sometimes producers throw this exception:

   ```
Confluent.Kafka.KafkaException: Operation not valid in state Ready
   at Confluent.Kafka.Impl.SafeKafkaHandle.AbortTransaction(Int32 millisecondsTimeout)
   at Confluent.Kafka.Producer`2.AbortTransaction(TimeSpan timeout)
   at ...
```

any advice how to do "cleanup abort" properly?

**Comment by Keerthikan** [comment]
@koshdim The answer you seem to looking for 
https://github.com/confluentinc/confluent-kafka-dotnet/issues/1671

**Comment by ksdvishnukumarcse** [comment]
@mhowlett and @koshdim , 

Even i too face the INVALID_PRODUCER_EPOCH error.
Am running the my application in Windows 10 machine.
I have a single Producer and TransactionId is Random Guid, enabled Idempotence as well. No other instance of the application or same TransactionId is used. When i try to Commit in case of successful message processing or Abort in case of failure while message processing i am getting the error.

I have disabled AutoCommit and AutoOffsetStore as well in the consumer settings


Below is the  Debug log for the same
```
      producerClient Transaction commit started...
%7|1655388819.918|TXNAPI|rdkafka#producer-1| [thrd:app]: Transactional API called: commit_transaction (begin) (in txn state InTransaction, idemp state Assigned)
%7|1655388819.918|TXNSTATE|rdkafka#producer-1| [thrd:main]: Transaction state change InTransaction -> BeginCommit
%7|1655388819.921|TXNCOMMIT|rdkafka#producer-1| [thrd:app]: Flushing 0 outstanding message(s) prior to commit
%7|1655388819.928|TXNCOMMIT|rdkafka#producer-1| [thrd:app]: Transaction commit message flush complete
%7|1655388819.928|TXNAPI|rdkafka#producer-1| [thrd:app]: Transactional API called: commit_transaction (in txn state BeginCommit, idemp state Assigned)
%7|1655388819.929|TXNSTATE|rdkafka#producer-1| [thrd:main]: Transaction state change BeginCommit -> CommittingTransaction
%7|1655388819.930|ENDTXN|rdkafka#producer-1| [thrd:main]: EndTxn returned INVALID_PRODUCER_EPOCH in state CommittingTransaction (may_retry=true)
%1|1655388819.930|TXNERR|rdkafka#producer-1| [thrd:main]: Fatal transaction error: Failed to end transaction: Local: This instance has been fenced by a newer instance (_FENCED)
%0|1655388819.932|FATAL|rdkafka#producer-1| [thrd:main]: Fatal error: Local: This instance has been fenced by a newer instance: Failed to end transaction: Local: This instance has been fenced by a newer instance
%7|1655388819.932|TXNSTATE|rdkafka#producer-1| [thrd:main]: Transaction state change CommittingTransaction -> FatalError
info: MyLogger[0]
      Producer Error Handler: Failed to end transaction: Local: This instance has been fenced by a newer instance
info: MyLogger[0]
      producerClient Transaction abort started...
%7|1655388834.104|TXNAPI|rdkafka#producer-1| [thrd:app]: Transactional API called: abort_transaction (begin) (in txn state FatalError, idemp state Assigned)
```

Could please provide input for the same.

**Comment by ksdvishnukumarcse** [comment]
it got resolved by increasing the TransactionTimout setting
