### ISSUE TITLE
How to configure and use sasl?

### ISSUE THREAD

**Issue by lonelyislong** [confluentinc/confluent-kafka-dotnet#1499]
As the title，thank you very much！

**Comment by mhowlett** [comment]
this depends on the sasl mechanism. this might be useful: https://docs.confluent.io/platform/current/kafka/authentication_sasl/index.html

**Comment by OneCricketeer** [comment]
@mhowlett That package seems to discuss JAAS properties, but those are Java-specific, no?

**Comment by anchitj** [comment]
https://github.com/confluentinc/librdkafka/wiki/Using-SASL-with-librdkafka
