### ISSUE TITLE
How to log messages from librdkafka?

### ISSUE THREAD

**Issue by koshdim** [confluentinc/confluent-kafka-dotnet#1501]
Description
===========
I use NLog to write log messages to file. It was noticed that some messages seen in the console do not appear in file log. For example
` %4|1610704117.841|CONFWARN|rdkafka#consumer-1| [thrd:app]: Configuration property `sasl.username` only applies when `sasl.mechanism` is set to PLAIN or SCRAM-SHA-..`
I investigated a bit and found that this message is produced by librdkafka, which is used by Confluent.Kafka nuget.
Is there some way to configure Confluent.Kafka nuget to forward this message to .Net loggers?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [* ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
when building the client, provide custom functions to `SetLogHandler` and also `SetErrorHandler` (which although called error, the most appropriate action to take is usually just to log)

**Comment by koshdim** [comment]
awesome, it works! Thank you very much!
