### ISSUE TITLE
How to configure logging

### ISSUE THREAD

**Issue by mindwerxkmg** [confluentinc/confluent-kafka-dotnet#1506]
Description
===========

I cannot find any information on how to log Kafka debug output with the 1.5.3 client.  The OnLog event is not available on the ProducerBuilder class.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
`SetLogHandler`

**Comment by mindwerxkmg** [comment]
Thank you!
