### ISSUE TITLE
[Question] Async handling of consumed messages in EXACTLY ONCE scenario

### ISSUE THREAD

**Issue by jbhardwaj-tc** [confluentinc/confluent-kafka-dotnet#1508]
Description
===========

This is following up on the example [here](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Web/RequestTimeConsumer.cs).

My use case is that I need to reach out to an external provider with the consumed message. Which could (for all intents and purposes) may be down/ respond slowly. So adding a bit of example scenario code to the code in the link above like this:

```
try
{
    var cr = kafkaConsumer.Consume(cancellationToken);
    var message = cr.Message.Value;

    // External http call, which may be slow
    try 
    {
        var externalResponse = await externalProvider.Process(message, cancellationToken);    
        kafkaConsumer.StoreOffset(result);
    }
    catch { kafkaConsumer.StoreOffset(result); }
}
```
To achieve **EXACTLY ONCE** semantic, I manually store the offsets once the external provider returns (either successfully or error's out, either way)
```
EnablePartitionEof = true;
EnableAutoCommit = true;
EnableAutoOffsetStore = false;
AutoOffsetReset = AutoOffsetReset.Earliest;
```

**Question:**

- Since the `kafkaConsumer.Consume(cancellationToken);` runs on a separate background thread (does it?), it is possible, in the event that the external provider is slow that the consume runs again before the offsets can be stored for the message fetched previously, and the same message is read again, right?

Any sort of best practice way you recommend to handle this?

Thanks.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version: **1.5.2**
 - [ ] Apache Kafka version.
 - [x] Client configuration
 - [x] Operating system: **Windows 2016 server**
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
> Since the kafkaConsumer.Consume(cancellationToken); runs on a separate background thread (does it?), 

it runs in the application thread (i.e. not in the background).

`kafkaConsumer.StoreOffset(result);` marks the offset as eligible to be committed, which happens periodically in a background thread inside the client.

to achieve exactly once semantics, you'll need to use kafka transactions, or transactionally store offsets in your external system + the external calling code must be idempotent.
