### ISSUE TITLE
[Question] Any support for cooperative rebalancing protocol?

### ISSUE THREAD

**Issue by alexcothron** [confluentinc/confluent-kafka-dotnet#1512]
Our use case implements a large number of consumers running in K8s. We are seeing a lot of "rebalancing storms" and I believe cooperative rebalancing might help. Is there a way to achieve this, or perhaps a workaround?

Thanks in advance.

**Comment by mhowlett** [comment]
this will be in v1.6.0, which should be out in about a week. it's in 1.6.0-RC2, which is on nuget, but note that there are some known issues in that version.

**Comment by korchak-aleksandr** [comment]
I think you could close this issue.
Cooperative sticky strategy appeared in version 1.6.0.
