### ISSUE TITLE
Clarify on default Partitioner

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1526]
I would like to know what is actually the default partitioner used when message key is not specified.

I can see the code with this comments:

///     Partitioner: `random` - random distribution, `consistent` - CRC32 hash of key (Empty and NULL keys are mapped to single partition), `**consistent_random**` - CRC32 hash of key (Empty and NULL keys are **randomly** partitioned), `murmur2` - Java Producer compatible Murmur2 hash of key (NULL keys are mapped to single partition), `murmur2_random` - Java Producer compatible Murmur2 hash of key (NULL keys are randomly partitioned. This is functionally equivalent to the default partitioner in the Java Producer.).
        ///
        ///     default: consistent_random
        
it means: consistent_random => Empty and NULL keys are randomly partitioned

but, in Confluent doc: https://docs.confluent.io/platform/current/clients/producer.html
(I have kafka 2.3, Confluent.Kafka 1.5.3,  confluent 5.1)
we can read: 

"In Confluent Platform versions prior to 5.4.x, the partition is assigned in a **round robin** method, starting at a random partition."

so, using confluent kafka dotnet with Confluent prior to v5.4, what is the default partitioner used ?? round-robin or random ?
it is applied message by message?? (no batching involved) ??

**Comment by mhowlett** [comment]
> consistent_random => Empty and NULL keys are randomly partitioned

correct. the docs you link to refer to the java client and don't apply.

librdkafka actually has more complex behavior than this - if a partition is unavailable, another will be randomly selected rather than not deliver the message. if this second partition is unavailable though, the client won't choose another - it'll wait for it to become available before delivering the message.

in version 1.6.0, we introduce the sticky partitioner, which is on by default. partitioning is still random, but "sticky".

I would strongly recommend using the `murmur2_random` partitioner which won't randomly partition empty keys and is compatible with the java client default partitioner.

**Comment by edenhill** [comment]
Note the difference between empty (e.g. a zero-length string) and Null (NULL).

**Comment by alfhv** [comment]
so which partitioner to use to have round-robin distribution "with Null keys" ?? assuming all partitions are available.

**Comment by mhowlett** [comment]
there isn't a built in one, you'll need to define a custom one (available in .net from v1.6.0).

what is your use case where round-robin is suitable but random isn't?

**Comment by alfhv** [comment]
i'm just trying to ensure balance between all consumers. the random partitioner ensure a fair balanced distribution ? 
reading here https://www.confluent.fr/blog/apache-kafka-producer-improvements-sticky-partitioner/ the sticky batch is not good for me... I have a fast producer and a lot of slow consumers so increase latency sending is not an issue but having a bad partition distribution will give me unused consumers and increase processing time.

**Comment by edenhill** [comment]
Any partitioner which has _random in the name will provide fair distribution over time (i.e., effectively same as round-robin) for Null keys.

**Comment by mhowlett** [comment]
you can disable sticky partitioning by setting `sticky.partitioning.linger.ms` to 0 (not applicable until 1.6.0 is out).

**Comment by alfhv** [comment]
but this is not what doc mention..... ???

> At first glance, it might seem like setting linger.ms to 0 would only lead to the production of single-record batches. However, this is usually not the case. Even when linger.ms is 0, the producer will group records into batches when they are produced to the same partition around the same time. This is because the system needs a bit of time to handle each request, and batches form when the system cannot attend to them all right away.

**Comment by mhowlett** [comment]
that's not referring to sticky partitioning. it's relevant to high throughput usage (many messages produced in < 1ms)

**Comment by milindl** [comment]
Closing this as the questions seem to be answered, please reopen if there are further questions.
