### ISSUE TITLE
get Consumer status connected/diconnected

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1531]
What is the most reliable way to know the Consumer status : connected or disconnected to broker ?
Assigment ? Subscription ? MemberId ?

I want to check any possible disconnections due to any kind of error.

and what is the proper way to reconnect in case of non-auto-recoverable disconnection ? Calling ConsumeMessages() again ?

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down

TLDR: there is no single "the Kafka is up" metric, there are too many moving parts. Instead monitor your data rate; no data for X time units => something is wrong.

> and what is the proper way to reconnect in case ..
The client will recover automatically from all temporary errors.
