### ISSUE TITLE
Why my consumer does not get the ConsumeResult<Tkey, TValue> with IsPartitionEOF mark as true at all 

### ISSUE THREAD

**Issue by lixiandai** [confluentinc/confluent-kafka-dotnet#1532]
Description
===========
https://github.com/confluentinc/confluent-kafka-dotnet/blob/1.5.x/src/Confluent.Kafka/Consumer.cs#L716-L721
Seems consumer should get a ConsumeResult record with message = null but IsPartitionEOF = true so we could decide if that partition is done processing. however my consumer never get that message instead of keep getting NULL ConsumeResult<Tkey, TValue>

I am using .net 1.5.3 nuget version 

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
Did you EnablePartitionEof to true in your consumer config?

**Comment by lixiandai** [comment]
@edenhill  is that value suppose to be defautl as true?

**Comment by edenhill** [comment]
No, it defaults to false: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by lixiandai** [comment]
@edenhill cool. i guess that is why. thank you for the quick reply
