### ISSUE TITLE
CommitTransaction doesn't fail when the transaction times out and is rolled back by Kafka

### ISSUE THREAD

**Issue by bastien-hofmann** [confluentinc/confluent-kafka-dotnet#1533]
Description
===========
If there is a long pause between the last call to "Produce" and the call to "CommitTransaction", the transaction is deemed to have timed out by Kafka, who will roll back the transaction.
At that point, with the transaction rolled back, the call to "CommitTransaction" will run without exception, giving the impression to the client that the transaction was successful, and that the messages are committed on the server.
However that's not the case, and a Consumer with "read committed" doesn't see the messages.

In that situation, I would expect the "CommitTransaction" method to throw an exception, indicating that the transaction was rolled back.

How to reproduce
================
- Create a producer, begin a transaction
- Produce some messages
- Pause for a duration longer than the producer transaction timeout and kafka server cleanup interval (2 minutes should do it)
- call "CommitTransaction"
The call succeeds even though the transaction was rolled back on the server.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
```
            var bootstrapServers = "localhost:9092";

            var producerConfig = new ProducerConfig { BootstrapServers = bootstrapServers, TransactionalId = "SampleKafka2", EnableIdempotence = true, TransactionTimeoutMs = 10000 };

            using (var p = new ProducerBuilder<string, string>(producerConfig).Build())
            {
                p.InitTransactions(TimeSpan.FromSeconds(30));
                p.BeginTransaction();

                p.Produce("test-topic", new Message<string, string> { Key = "One", Value = "test" });

                Console.WriteLine("Simulating a pause longer than the Kafka transaction cleanup time");
                Thread.Sleep(TimeSpan.FromMinutes(2));

                p.CommitTransaction(TimeSpan.FromSeconds(30));

                Console.WriteLine("We see this, even tough the transaction has been rolled back by the server");
            }

            // Try to read the topic, which should contain a message if the transaction was indeed successful

            var consumerConfig = new ConsumerConfig { BootstrapServers = bootstrapServers, GroupId = "SampleKafka", AutoOffsetReset = AutoOffsetReset.Earliest };

            using (var c = new ConsumerBuilder<Ignore, string>(consumerConfig).Build())
            {
                c.Subscribe("test-topic");

                var cr = c.Consume(TimeSpan.FromSeconds(10));

                if (cr?.Message == null)
                    Console.WriteLine("Message is null here because the transaction was indeed rolled back");
            }

            Console.WriteLine("Finished, press any key");
            Console.ReadKey();
```
 - [x] Confluent.Kafka nuget version.
 - Version 1.5.3
 - [x] Apache Kafka version.
 - Confluent version 5.5.1
 - [x] Operating system.
 - Client in Windows 10, Kafka running in Docker
 - [x] Provide broker log excerpts.
```
[2021-02-11 14:45:30,143] INFO [TransactionCoordinator id=1] Initialized transactionalId SampleKafka2 with producerId 1 and producer epoch 0 on partition __transaction_state-42 (kafka.coordinator.transaction.TransactionCoordinator)
[2021-02-11 14:45:31,620] INFO [Controller id=1] Processing automatic preferred replica leader election (kafka.controller.KafkaController)
[2021-02-11 14:45:41,139] INFO [TransactionCoordinator id=1] Completed rollback of ongoing transaction for transactionalId SampleKafka2 due to timeout (kafka.coordinator.transaction.TransactionCoordinator)
```

**Comment by mhowlett** [comment]
closing, please open again if problem persists.

**Comment by bastien-hofmann** [comment]
Hello,
Thank you for your answer, upgrading to version 1.6.2 did indeed solve my issue.
