### ISSUE TITLE
JSON serialization validation message does not provide needed information

### ISSUE THREAD

**Issue by drinehim** [confluentinc/confluent-kafka-dotnet#1535]
Description
===========
The message of the InvalidDataException  thrown by JsonSerializer is not correctly providing the paths that fail validation. Instead it returns `Schema validation failed for properties: [System.Linq.Enumerable+SelectListIterator`2[NJsonSchema.Validation.ValidationError,System.String]]`

How to reproduce
================
Install any 1.5.x or 1.6.x version of Confluent.SchemaRegistry.Serdes.Json. The project that implements the message for kafka uses C# Nullables. The project that calls IProducer.ProduceAsync does not and incorrectly set a property to null. The serialization throws the InvalidDataException without the information to determine what failed validation.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
will happily accept pull request

**Comment by drinehim** [comment]
Sorry this is taking so long. I'm working with my manager on the Contributor License Agreement

**Comment by artikweb** [comment]
Bumped into this issue today as well, couldn't figure out which property of my json was causing the validation failure. 
Is there any ETA for the fix?

**Comment by mhowlett** [comment]
merged #1681, thanks for the contribution @drinehimer
