### ISSUE TITLE
Wrong/Missing Documentation

### ISSUE THREAD

**Issue by msallin** [confluentinc/confluent-kafka-dotnet#1537]
The configuration for `DeliveryReportFields` contains the following summary comment.

```
A comma separated list of fields that may be optionally set in delivery reports. Disabling delivery
report fields that you do not require will improve maximum throughput and reduce memory usage. Allowed
values: key, value, timestamp, headers, all, none. default: all importance: low
```

https://github.com/confluentinc/confluent-kafka-dotnet/blob/e5503c170662067a751710d027ddf06521e1ac73/src/ConfigGen/Program.cs#L472

The value for "status" is missing.
https://github.com/confluentinc/confluent-kafka-dotnet/blob/v1.5.3/src/Confluent.Kafka/Producer.cs#L625

Should I submit a PR?

**Comment by mhowlett** [comment]
yes @msallin ! that would be great. sorry for the delay in getting to this.

**Comment by msallin** [comment]
Done
