### ISSUE TITLE
Unable to receive kafka requests at AdvancedConsumer after 2 days

### ISSUE THREAD

**Issue by erkanerten87** [confluentinc/confluent-kafka-dotnet#154]
I m using your advanced consumer example in my windows service .
On windows service start I m using Task.Factory.StartNew() to call AdvancedConsumer Run_Poll method on another thread. At Run_Poll method i check my cancellation token and poll from kafka in while loop.

I have seen connection closed logs after the service starts in 10 minutes but my consumer continue to receive kafka requests for 2 days.

After 2 days consumer can't poll requests and there is no error outside connection closed in logs.

When i restart my windows service. The problem is solved but i need to use it in production.

**Comment by mhowlett** [comment]
the consumer will automatically recover from connection problems behind the scenes, so:

> I have seen connection closed logs after the service starts in 10 minutes but my consumer continue to receive kafka requests for 2 days.

sounds normal.

More information is required to understand exactly what's going on after 2 days. You could enable more verbose logging. Also, you could try version 0.9.5 which is going to be released very shortly, hopefully today.

**Comment by erkanerten87** [comment]
I m logging (NLog)  every event on advanced customer like your example , I registered onLog and onMessage event in consumer now and i will send this logs 2 days later. How can i enable more detailed log information? 

Here is my configuration and statistics logs:
Confluent Version : 0.9.4-preview2
Client Configuration:
                { "group.id", "xxx" },
                { "enable.auto.commit", true},
                { "auto.commit.interval.ms", 5000 },
                { "statistics.interval.ms", 60000 },
                { "bootstrap.servers", brokerList },
                { "default.topic.config",  {     {  offset.reset", "smallest" } }

Statictics log:Info - Statistics: { "name": "rdkafka#consumer-3","type": "consumer", "ts":3464002671000, "time":1491823990, "replyq":0, "msg_cnt":0, "msg_size":0,"msg_max":0, "msg_size_max":0, "simple_cnt":0,
 "brokers":{ "broker1:port/bootstrap": { "name":"broker1:port/bootstrap", "nodeid":-1, "state":"UP", "stateage":1020203000, "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":0, "waitresp_msg_cnt":0, "tx":220, "txbytes":6746, "txerrs":0, "txretries":2, "req_timeouts":0, "rx":219, "rxbytes":160585, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "zbuf_grow":0, "buf_grow":0, "rtt": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "throttle": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "toppars":{ } } , 
 "broker2:port/bootstrap": { "name":"broker2:port/bootstrap", "nodeid":-1, "state":"UP", "stateage":1009640000, "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":0, "waitresp_msg_cnt":0, "tx":214, "txbytes":6750, "txerrs":0, "txretries":0, "req_timeouts":0, "rx":214, "rxbytes":127036, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "zbuf_grow":0, "buf_grow":0, "rtt": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "throttle": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "toppars":{ } } , 				"broker3:port/bootstrap": { "name":"broker3:port/bootstrap", "nodeid":-1, "state":"UP", "stateage":409531000, "outbuf_cnt":0,  "outbuf_msg_cnt":0, "waitresp_cnt":0, "waitresp_msg_cnt":0, "tx":218, "txbytes":6914, "txerrs":0, "txretries":0, "req_timeouts":0, "rx":218, "rxbytes":117454, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "zbuf_grow":0, "buf_grow":0, "rtt": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "throttle": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "toppars":{ } } ,
"broker2:port/2": { "name":"broker2:port/2", "nodeid":2, "state":"UP", "stateage":1609796000,  "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":0, "waitresp_msg_cnt":0, "tx":213,    "txbytes":6675,     "txerrs":0, "txretries":0, "req_timeouts":0, "rx":213,    "rxbytes":151711,   "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "zbuf_grow":0, "buf_grow":0, "rtt": { "min":0,     "max":0,      "avg":0,      "sum":0, 	    "cnt":0 },  "throttle": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "toppars":{ } } ,  "broker1:port/1": { "name":"broker1:port/1", "nodeid":1, "state":"UP", "stateage":88620921000, "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":2, "waitresp_msg_cnt":0, "tx":832809, "txbytes":55211848, "txerrs":0, "txretries":0, "req_timeouts":0, "rx":832807, "rxbytes":27372435, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "zbuf_grow":0, "buf_grow":0, "rtt": { "min":15000, "max":422000, "avg":110949, "sum":61688000, "cnt":556 }, "throttle": { "min":0, "max":0, "avg":0, "sum":0, "cnt":501 }, "toppars":{ "HIGH": { "topic":"HIGH", "partition":0} } } , "broker3:port/3": { "name":"broker3:port/3", "nodeid":3, "state":"UP", "stateage":409515000,   "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":0, "waitresp_msg_cnt":0, "tx":217, 	 "txbytes":6865, 	 "txerrs":0, "txretries":0, "req_timeouts":0, "rx":217, "rxbytes":164071,	   "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "zbuf_grow":0, "buf_grow":0, "rtt": { "min":0,	   "max":0, 	 "avg":0,	   "sum":0, 	   "cnt":0 }, 	"throttle": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "toppars":{ } } }, a"topics":{ "HIGH": { "topic":"HIGH", "metadata_age":120437, "partitions":{ "0": { "partition":0, "leader":1, "desired":true, "unknown":false, "msgq_cnt":0, "msgq_bytes":0, "xmit_msgq_cnt":0, "xmit_msgq_bytes":0, "fetchq_cnt":0, "fetchq_size":0, "fetch_state":"active", "query_offset":-2, "next_offset":3, "app_offset":3, "stored_offset":3, "commited_offset":3, "committed_offset":3, "eof_offset":3, "lo_offset":0, "hi_offset":3, "consumer_lag":0, "txmsgs":0, "txbytes":0, "msgs": 0, "rx_ver_drops": 0 } , "-1": { "partition":-1, "leader":-1, "desired":false, "unknown":false, "msgq_cnt":0, "msgq_bytes":0, "xmit_msgq_cnt":0, "xmit_msgq_bytes":0, "fetchq_cnt":0, "fetchq_size":0, "fetch_state":"none", "query_offset":0, "next_offset":0, "app_offset":-1001, "stored_offset":-1001, "commited_offset":-1001, "committed_offset":-1001, "eof_offset":-1001, "lo_offset":-1001, "hi_offset":-1001, "consumer_lag":-1, "txmsgs":0, "txbytes":0, "msgs": 0, "rx_ver_drops": 0 } } } } }

**Comment by treziac** [comment]
Note there are two events for consumer: OnError (which is typically related to broker errors) and OnConsumerError (which is related to a given message when consuming from the consumer queue). @mhowlett I think it's missing in the AdvancedConsumer

Typically, the connection close error is **normal**, it is the broker which close an idle connexion automatically. You can deactivate it with by putting log.connection.close to false (see the doc at https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md )
Under the hood, librdkafka consider an "error" anything which is not a zero return (for example, end of partition, but we treat it specifically to return an OnPartitionEOF in this case here), and same in Confluent.Kafka. There i no such thinks as warning, only logs (through debug config). Also error callbacks are triggered only when librdkafka can't handle them (it will retry to send message by itself if it fails, reconnect automatically, etc)


To debug the consumer, the best is to set debug to "cgrp,topic,fetch". Also look at your brokers logs if you have any related log to this problem.


> I m logging (NLog) every event on advanced customer like your example.

Do you mean every OnMessage, OnError, OnLog, etc? What is your result when you don't set debug? Are you sure you don't have an exception somewhere which stops your process btw?

> I registered onError event and there is no error log after 2 days.

OnError only shows non recoverable errors (except the one I mentioneded above), so it's normal

> Now, I registered onLog and onMessage events in consumers (3 consumers per topic HIGH,MEDIUIM,LOW ) 

I don't quite understand... Can you elaborate? How many topics, consumer, machine is there and what do you try to achieve with your topics?

**Comment by mhowlett** [comment]
> @mhowlett I think it's missing in the AdvancedConsumer

good idea (this was a relatively late addition to the API, forgot to update the example to demonstrate). PR #158

**Comment by erkanerten87** [comment]
To debug the consumer i set "cgrp,topic,fetch" and i closed connection error logging like https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

 I updated the latest kafka library and  i have version problem 
` The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception. ---> System.IO.FileLoadException: Invalid librdkafka version 902ff, expected at least 903ff`

 i solved this error with returning the latest stable version,now my packages.config is:
```
 "Confluent.Kafka" version="0.9.5" targetFramework="net461" />
 librdkafka.redist" version="0.9.5" targetFramework="net461" />
 "Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
  RdKafka.Internal.librdkafka" version="0.9.1" targetFramework="net461" />
```
Are these versions up to date?

>Do you mean every OnMessage, OnError, OnLog, etc? What is your result when you don't set debug? Are you sure you don't have an exception somewhere which stops your process btw?

I mean OnMessage, OnError and OnLog, OnPartitionEOF, OnOffsetsCommitted, OnPartitionsAssigned, OnPartitionsRevoked,On Istatictics  Events. Without debug i only see statictics logs and connection errors and there is no exception. With updating the latest version i registered onConsumerError event  and unregistered from OnStatictics event.


> Now, I registered onLog and onMessage events in consumers (3 consumers per topic HIGH,MEDIUIM,LOW )

>I don't quite understand... Can you elaborate? How many topics, consumer, machine is there and what do you try to achieve with your topics?

I have 3 topics HIGH,MEDIUM,LOW like priority queue. I have 3 consumers,
Each consumer has its own thread, poll timeout and reads only one topic
Ex. first consumer reads only HIGH topic and it's poll timeout is 20 seconds, so first consumer's thread polls HIGH topic every 20 seconds. 

As soon as i reproduce error, i will sent the error logs.

**Comment by treziac** [comment]
Remove RdKafka.Internal.librdkafka, it should not be used with confluent.kafka

**Comment by treziac** [comment]
Did you reproduce your problem or did upgrading  to 0.9.5 solve the issue?

Is there any reason to poll with a 20s timeout? It should have no impact on librdkafka internally (edenhill or mhowlett could confirm) but it seems strange to me (except if you are doing some aggregations on time windows for example)

Also note that it would be better to have only one consumer instance which would subscribe to all three topics, and dispatch the process after that (if you have a single process) rather than three separated instances. It would lower the number of connections and bandwith, though it's not such important in your case for now I think. Just keep it in mind if one day you have to treat many more topics :)

**Comment by erkanerten87** [comment]
I haven't reproduced this problem yet, Sometimes issue occurs longer than 2 days,In my tests Avarage time of reproducing this issue is 2 days so updating 0.9.5 version may solve this issue. I will continue to monitor the system.

In my logs i have seen some error logs :

> 2017-04-27 00:00:01.0057 [10] Info - Facility: OFFSET Level: 7 Name: rdkafka#consumer-1  Message: [thrd:main]: Topic LOW [0]: stored offset -1001, committed offset -1001
2017-04-27 00:00:01.0057 [10] Info - Facility: OFFSET Level: 7 Name: rdkafka#consumer-1  Message: [thrd:main]: Topic LOW [0]: setting offset INVALID for commit
2017-04-27 00:00:01.0057 [10] Info - Facility: COMMIT Level: 7 Name: rdkafka#consumer-1  Message: [thrd:main]: OffsetCommit internal error: Local: No offset stored
2017-04-27 00:00:01.0057 [10] Info - Facility: COMMIT Level: 7 Name: rdkafka#consumer-1  Message: [thrd:main]: OffsetCommit for 1 partition(s): cgrp auto commit timer: returned: Local: No offset stored

>Is there any reason to poll with a 20s timeout? 

No, there is no reason.I will decrease it and add some thread.sleep codes to while loop but i don't want to restart my windows service to reproduce the issue.

**Comment by erkanerten87** [comment]
Upgrading to 0.9.5 version solved this case. Thanks for help.I'm closing the issue.
