### ISSUE TITLE
One Of Partitions Cannot Be Consumed

### ISSUE THREAD

**Issue by IrfanSiddiq** [confluentinc/confluent-kafka-dotnet#1543]
Description
===========
I have a .Net core console application, that uses Confluent.Kafka. I build a consumer for consuming messages from specific topic. the app is intended to run all day long, consume the messages on the specified topic and process them, i have 3 broker in my cluster and the topic have configuration replication factor 2 and 4 partition.

after run the app for a couple month with running no issue, suddenly there is an issue with one partition cannot consume bythe application, i try run consumer in Apache NIFI1.12 with the new3es consumer processor with the same group-id the issue still the same partition 0 of my topic cannot be consumed, but strangely if i use kafka-console-consumer.sh using same group-id the script that provide in kafka the partition 0 can be consumed.

after lot of research i try run my app using debug and found that stored offset of my partition 0 is -1001 not the value of current offset in my broker * run command `./bin/kafka-consumer-groups.sh --describe -group monitor-irfan --bootstrap-server <bootstrap-server>` but another stored aprtition have correct value
sorry for my bad english..

How to reproduce
================
i try running consumer example app and using the same group-id the issue still in there the stored offset is -1001 this is the sample log:
` "topics": {
        "gate-fail": {
            "topic": "gate-fail",
            "age": 45634,
            "metadata_age": 46975,
            "batchsize": {
                "min": 306,
                "max": 493,
                "avg": 421,
                "sum": 1684,
                "stddev": 74,
                "p50": 405,
                "p75": 481,
                "p90": 493,
                "p95": 493,
                "p99": 493,
                "p99_99": 493,
                "outofrange": 0,
                "hdrsize": 14448,
                "cnt": 4
            },
            "batchcnt": {
                "min": 2,
                "max": 2,
                "avg": 2,
                "sum": 8,
                "stddev": 0,
                "p50": 2,
                "p75": 2,
                "p90": 2,
                "p95": 2,
                "p99": 2,
                "p99_99": 2,
                "outofrange": 0,
                "hdrsize": 8304,
                "cnt": 4
            },
            "partitions": {
                "0": {
                    "partition": 0,
                    "broker": 1,
                    "leader": 1,
                    "desired": true,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "active",
                    "query_offset": -1001,
                    "next_offset": 9615401,
                    "app_offset": -1001,
                    "stored_offset": -1001,
                    "commited_offset": 9615401,
                    "committed_offset": 9615401,
                    "eof_offset": -1001,
                    "lo_offset": 8843585,
                    "hi_offset": 9615913,
                    "ls_offset": 9514305,
                    "consumer_lag": 0,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 0,
                    "rxbytes": 0,
                    "msgs": 0,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                },
                "1": {
                    "partition": 1,
                    "broker": 2,
                    "leader": 2,
                    "desired": true,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "active",
                    "query_offset": -1001,
                    "next_offset": 9625441,
                    "app_offset": 9625441,
                    "stored_offset": 9625441,
                    "commited_offset": 9625431,
                    "committed_offset": 9625431,
                    "eof_offset": 9625439,
                    "lo_offset": 8844085,
                    "hi_offset": 9625441,
                    "ls_offset": 9625441,
                    "consumer_lag": 0,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 530,
                    "rxbytes": 99297,
                    "msgs": 530,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                },
                "2": {
                    "partition": 2,
                    "broker": 3,
                    "leader": 3,
                    "desired": true,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "active",
                    "query_offset": -1001,
                    "next_offset": 9629183,
                    "app_offset": 9629183,
                    "stored_offset": 9629183,
                    "commited_offset": 9629176,
                    "committed_offset": 9629176,
                    "eof_offset": 9629183,
                    "lo_offset": 8852505,
                    "hi_offset": 9629183,
                    "ls_offset": 9629183,
                    "consumer_lag": 0,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 432,
                    "rxbytes": 79745,
                    "msgs": 432,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                },
                "3": {
                    "partition": 3,
                    "broker": 1,
                    "leader": 1,
                    "desired": true,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "active",
                    "query_offset": -1001,
                    **"next_offset": 9612039,
                    "app_offset": 9612039,
                    "stored_offset": 9612039,
                    "commited_offset": 9612036,
                    "committed_offset": 9612036,
                    "eof_offset": 9612039,**
                    "lo_offset": 8838922,
                    "hi_offset": 9612039,
                    "ls_offset": 9612039,
                    "consumer_lag": 0,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 493,
                    "rxbytes": 90615,
                    "msgs": 493,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                },
                "-1": {
                    "partition": -1,
                    "broker": -1,
                    "leader": -1,
                    "desired": false,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "none",
                    "query_offset": -1001,
                    "next_offset": 0,
                    "app_offset": -1001,
                    "stored_offset": -1001,
                    "commited_offset": -1001,
                    "committed_offset": -1001,
                    "eof_offset": -1001,
                    "lo_offset": -1001,
                    "hi_offset": -1001,
                    "ls_offset": -1001,
                    "consumer_lag": -1,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 0,
                    "rxbytes": 0,
                    "msgs": 0,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                }
            }
        }
    },`
"topics": {
        "gate-fail": {
            "topic": "gate-fail",
            "age": 45634,
            "metadata_age": 46975,
            "batchsize": {
                "min": 306,
                "max": 493,
                "avg": 421,
                "sum": 1684,
                "stddev": 74,
                "p50": 405,
                "p75": 481,
                "p90": 493,
                "p95": 493,
                "p99": 493,
                "p99_99": 493,
                "outofrange": 0,
                "hdrsize": 14448,
                "cnt": 4
            },
            "batchcnt": {
                "min": 2,
                "max": 2,
                "avg": 2,
                "sum": 8,
                "stddev": 0,
                "p50": 2,
                "p75": 2,
                "p90": 2,
                "p95": 2,
                "p99": 2,
                "p99_99": 2,
                "outofrange": 0,
                "hdrsize": 8304,
                "cnt": 4
            },
            "partitions": {
                "0": {
                    "partition": 0,
                    "broker": 1,
                    "leader": 1,
                    "desired": true,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "active",
                    "query_offset": -1001,
                    **"next_offset": 9615401,
                    "app_offset": -1001,
                    "stored_offset": -1001,
                    "commited_offset": 9615401,
                    "committed_offset": 9615401,
                    "eof_offset": -1001,
                    "lo_offset": 8843585,
                    "hi_offset": 9615913,
                    "ls_offset": 9514305,**
                    "consumer_lag": 0,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 0,
                    "rxbytes": 0,
                    "msgs": 0,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                },
                "1": {
                    "partition": 1,
                    "broker": 2,
                    "leader": 2,
                    "desired": true,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "active",
                    "query_offset": -1001,
                    **"next_offset": 9625441,
                    "app_offset": 9625441,
                    "stored_offset": 9625441,
                    "commited_offset": 9625431,
                    "committed_offset": 9625431,
                    "eof_offset": 9625439,
                    "lo_offset": 8844085,
                    "hi_offset": 9625441,
                    "ls_offset": 9625441,**
                    "consumer_lag": 0,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 530,
                    "rxbytes": 99297,
                    "msgs": 530,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                },
                "2": {
                    "partition": 2,
                    "broker": 3,
                    "leader": 3,
                    "desired": true,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "active",
                    "query_offset": -1001,
                    **"next_offset": 9629183,
                    "app_offset": 9629183,
                    "stored_offset": 9629183,
                    "commited_offset": 9629176,
                    "committed_offset": 9629176,
                    "eof_offset": 9629183,
                    "lo_offset": 8852505,
                    "hi_offset": 9629183,
                    "ls_offset": 9629183,**
                    "consumer_lag": 0,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 432,
                    "rxbytes": 79745,
                    "msgs": 432,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                },
                "3": {
                    "partition": 3,
                    "broker": 1,
                    "leader": 1,
                    "desired": true,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "active",
                    "query_offset": -1001,
                    **"next_offset": 9612039,
                    "app_offset": 9612039,
                    "stored_offset": 9612039,
                    "commited_offset": 9612036,
                    "committed_offset": 9612036,
                    "eof_offset": 9612039,
                    "lo_offset": 8838922,
                    "hi_offset": 9612039,
                    "ls_offset": 9612039,**
                    "consumer_lag": 0,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 493,
                    "rxbytes": 90615,
                    "msgs": 493,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                },
                "-1": {
                    "partition": -1,
                    "broker": -1,
                    "leader": -1,
                    "desired": false,
                    "unknown": false,
                    "msgq_cnt": 0,
                    "msgq_bytes": 0,
                    "xmit_msgq_cnt": 0,
                    "xmit_msgq_bytes": 0,
                    "fetchq_cnt": 0,
                    "fetchq_size": 0,
                    "fetch_state": "none",
                    "query_offset": -1001,
                    "next_offset": 0,
                    "app_offset": -1001,
                    "stored_offset": -1001,
                    "commited_offset": -1001,
                    "committed_offset": -1001,
                    "eof_offset": -1001,
                    "lo_offset": -1001,
                    "hi_offset": -1001,
                    "ls_offset": -1001,
                    "consumer_lag": -1,
                    "txmsgs": 0,
                    "txbytes": 0,
                    "rxmsgs": 0,
                    "rxbytes": 0,
                    "msgs": 0,
                    "rx_ver_drops": 0,
                    "msgs_inflight": 0,
                    "next_ack_seq": 0,
                    "next_err_seq": 0,
                    "acked_msgid": 0
                }
            }
        }
    },

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.6.2
 - [x] Apache Kafka version.  kafka_2.12-2.5.0
 - [x] Client configuration. same as example
 - [x] Operating system. Broker (Centos 7) Client(Centos,Windows)
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
Are you using transactions? the committed offset is higher than the last stable offset (though less than the high watermark offset), which makes it invalid (-1001 is a special value librdkafka uses to mean "invalid").

```
"committed_offset": 9615401,
"hi_offset": 9615913,
"ls_offset": 9514305,
```

I don't know how you would get into this state, but committing an offset before the last stable offset may be how you might want to fix it.

**Comment by IrfanSiddiq** [comment]
Thank your for your answer..

yes our producer configuration using transaction.. so if i set the consumer to read uncommited is it solve solve my problem?, i'm sorry i cannot try the solution because our broker only store data for one week and for the time being i use mirror maker to replicate that topic to another cluster and my application consume from that cluster. if i encounter that issue again ill try your solution

**Comment by mhowlett** [comment]
`read_uncommitted` should solve the problem, except that your consumer will read aborted messages.

note: I would highly recommend using v1.6.2 if you are using transactional producer - it includes some important bug fixes.
