### ISSUE TITLE
[Question] How to set compatibility mode when registering schema in registry?

### ISSUE THREAD

**Issue by mdrgeniebelt** [confluentinc/confluent-kafka-dotnet#1545]
Hello,

So maybe stupid question but I can't find any options for specifying compatibility mode (backward, forward, full etc) when registering schemas in registry? Is it just always the default (which is backward) and if we want to change it we have to do it manually?

That's how we're registering schemas. I don't see any overloads or options on schema type to specify the compatibility mode (I can see that it is possible in nodejs library). I also could find anything on `SchemaRegistryConfig`.

```c#
var schemaJson = await File.ReadAllTextAsync("filePath");
var subject = SubjectNameStrategy.Topic.ConstructValueSubjectName("topic");

await _schemaRegistryClient.RegisterSchemaAsync(subject, new Schema(schemaJson, SchemaType.Avro));
```

I nodejs it looks more or less like this:
![image](https://user-images.githubusercontent.com/44974903/109544400-d07f0d00-7ac7-11eb-8ed0-86cee406e7ef.png)

**Comment by mhowlett** [comment]
`SetCompatibilityAsync` or `SetGlobalCompatibilityAsync` 

compatibility mode is a property on the subject - it don't think it's a great API to allow this to be set when registering a schema, as it's a logically separate operation.
