### ISSUE TITLE
Consumer Lag

### ISSUE THREAD

**Issue by tech7857** [confluentinc/confluent-kafka-dotnet#1547]
We have an independent application which is scheduled and basically doing nightly processing. This process is completely independent of the kafka consumer. What is the best way for this independent application to know that when it runs there is currently no kafka consumer lag. We were thinking of maintaining eof partition in db but it will be costly. Please suggest

**Comment by mhowlett** [comment]
you should be able to instantiate a consumer (specifying the relevant group.id) and call `public List<TopicPartitionOffset> Committed(IEnumerable<TopicPartition> partitions, TimeSpan timeout)` specifying all partitions subscribed to by members of the group, then call QueryWatermarkOffsets to get the high watermarks.
