### ISSUE TITLE
Coverity openssl vulnerabilities in alpine-librdkafka.so and centos6-librdkafka.so

### ISSUE THREAD

**Issue by bmgbeokwere** [confluentinc/confluent-kafka-dotnet#1556]
Description
===========
Logged an issue for alpine-librdkafka.so and centos6-librdkafka.so having out of date openssl dependencies. This ticket is to track updates to Confluent.Kafka.

Quote from Issue in librdkafka repo:
> Description
> We run our microservices through a binary analysis tool and both alpine-librdkafka.so and centos6-librdkafka.so look to have outdated references to openssl. Alpine looks to be referencing 1.0.2u while centos6 references 1.1.1i. Can we update these references to the latest versions?
> 
> In addition, is there a way to better manage these dependencies? It seems that we would lag on protection from know vulnerabilities if we require a new release to guard ourselves.
> 
> How to reproduce
> Run through a binary analysis tool.

Link to librdkafak issue:
https://github.com/edenhill/librdkafka/issues/3290

How to reproduce
================
Run through a binary analysis tool.
![image](https://user-images.githubusercontent.com/11319487/110676239-bf0dc300-81a1-11eb-9386-7ab7d39cfd10.png)
![image](https://user-images.githubusercontent.com/11319487/110676272-c634d100-81a1-11eb-8225-4c7bdbd057b2.png)

Checklist
=========

Please provide the following information:
 - [ ] Confluent.Kafka nuget version 1.6.2.

**Comment by mhowlett** [comment]
https://github.com/edenhill/librdkafka/pull/3288 (merged) updates this to 1.1.1j.

**Comment by mhowlett** [comment]
(will be in the next release)
