### ISSUE TITLE
Library release notes

### ISSUE THREAD

**Issue by javierholguera** [confluentinc/confluent-kafka-dotnet#156]
Hi,

Have you published anywhere the library release notes? 

I think it'd be useful to understand any potential impact of new versions.

**Comment by treziac** [comment]
There are some here : https://github.com/confluentinc/confluent-kafka-dotnet/releases
Major change though is the binding to librdkafka 0.9.5 instead of 0.9.4.

You can find the release note of it here: https://github.com/edenhill/librdkafka/releases/tag/v0.9.5

**Comment by javierholguera** [comment]
@treziac great, thanks.
