### ISSUE TITLE
Consolidate Travis/Appveyor/Make automations into a GitHub Actions pipeline

### ISSUE THREAD

**Issue by aleks-ivanov** [confluentinc/confluent-kafka-dotnet#1564]
A single GitHub Actions pipeline for all the required automated processes (with the addition of some other automation ideas, written as pseudo code in the pipeline in the connected PR) to eliminate potentially unnecessary overhead of maintaining several separate automation systems

We can start working on this promptly, just please let us know if you are interested in the implementation of the idea 🙂 

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by anchitj** [comment]
We can't use GH actions. We are using another tool Semaphore for all of this.
