### ISSUE TITLE
Annotation for consumer.

### ISSUE THREAD

**Issue by HarshMultani** [confluentinc/confluent-kafka-dotnet#1569]
Hi @mhowlett, 
 I wanted to listen for messages from kafka topic using C#.

Like in Java there is an annotation @KafkaListener, which when added above a function, listens messages from a topic and then the logic of the function executes.

@KafkaListener(topics = "topicname", groupId = "groupid")
// function code HERE

Similarly, is there an annotation for the same in C# using Confluent.Kafka

**Comment by anchitj** [comment]
Please check consumer examples in the repo.
