### ISSUE TITLE
Kafka ACLs

### ISSUE THREAD

**Issue by surbhi-software** [confluentinc/confluent-kafka-dotnet#1570]
We can get list of all ACLs added for principal(users) on the given topic whether they have permission or not. 

Say I have 2 users
1. User:Reader: this user is having read permission.
2. User:Writer: this user is having write permission.

From the above example can we come to a conclusion that User-Reader is a consumer and user-writer is a producer for topic "A"? Also, is getting information about ACLs users correct?

Thanks,
Surbhi

**Comment by surbhi-software** [comment]
Hello,

Any help would be appreciated.

**Comment by mhowlett** [comment]
I'm not quite sure I understand the question. If a user has write permissions, they _can_ produce to the topic (but might not have). If a user has read permissions, they _can_ consume from the topic (but might not have).

Note that the .net client doesn't yet allow you to work with ACLs. To do that, you can either use REST Proxy 
https://docs.confluent.io/platform/current/kafka-rest/api.html#acl or call out to the ./bin/kafka-acls.sh command.

**Comment by surbhi-software** [comment]
Hi Matt,

My question was if a user has write permission, can we conclude he is a producer for a topic "A"? Similarly, if a user has read permission, can we conclude that user is consumer for a topic "A"?

**Comment by mhowlett** [comment]
no, just because a user has permission to do something, it doesn't mean they have done that thing.
