### ISSUE TITLE
0xC0000005 The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

### ISSUE THREAD

**Issue by Vytas999** [confluentinc/confluent-kafka-dotnet#1577]
Description
===========
Hello, during "consume" process, time to time we're experiencing the problem with service crash and all the time the dump refers to this exception:
`
Dump Summary
------------
Last Write Time:	2021-03-29 12:41:12
Process Name:	w3wp.exe : c:\Windows\System32\inetsrv\w3wp.exe
Process Architecture:	x64
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Present

System Information
------------------
OS Version:	10.0.17763
CLR Version(s):	4.700.20.47201

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
w3wp.exe	c:\Windows\System32\inetsrv\w3wp.exe	10.0.17763.1
ntdll.dll	C:\Windows\System32\ntdll.dll	10.0.17763.1728
kernel32.dll	C:\Windows\System32\kernel32.dll	10.0.17763.475
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	10.0.17763.1790
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.17763.475
combase.dll	C:\Windows\System32\combase.dll	10.0.17763.1790
ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	10.0.17763.1490
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	10.0.17763.1697
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	10.0.17763.1613
iisutil.dll	c:\Windows\System32\inetsrv\iisutil.dll	10.0.17763.802
advapi32.dll	C:\Windows\System32\advapi32.dll	10.0.17763.1131
sechost.dll	C:\Windows\System32\sechost.dll	10.0.17763.1697
ws2_32.dll	C:\Windows\System32\ws2_32.dll	10.0.17763.771
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	10.0.17763.1
ntmarta.dll	C:\Windows\System32\ntmarta.dll	10.0.17763.1
user32.dll	C:\Windows\System32\user32.dll	10.0.17763.1728
win32u.dll	C:\Windows\System32\win32u.dll	10.0.17763.1
gdi32.dll	C:\Windows\System32\gdi32.dll	10.0.17763.1697
gdi32full.dll	C:\Windows\System32\gdi32full.dll	10.0.17763.1817
msvcp_win.dll	C:\Windows\System32\msvcp_win.dll	10.0.17763.348
w3wphost.dll	c:\Windows\System32\inetsrv\w3wphost.dll	10.0.17763.1
oleaut32.dll	C:\Windows\System32\oleaut32.dll	10.0.17763.1757
nativerd.dll	c:\Windows\System32\inetsrv\nativerd.dll	10.0.17763.1
bcrypt.dll	C:\Windows\System32\bcrypt.dll	10.0.17763.1613
ncrypt.dll	C:\Windows\System32\ncrypt.dll	10.0.17763.1
xmllite.dll	C:\Windows\System32\xmllite.dll	10.0.17763.678
ktmw32.dll	C:\Windows\System32\ktmw32.dll	10.0.17763.1
ntasn1.dll	C:\Windows\System32\ntasn1.dll	10.0.17763.1
iisres.dll	c:\Windows\System32\inetsrv\iisres.dll	10.0.17763.1
cryptsp.dll	C:\Windows\System32\cryptsp.dll	10.0.17763.1
rsaenh.dll	C:\Windows\System32\rsaenh.dll	10.0.17763.1
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	10.0.17763.1
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10941.16384
mlang.dll	C:\Windows\System32\mlang.dll	10.0.17763.1697
iiscore.dll	C:\Windows\System32\inetsrv\iiscore.dll	10.0.17763.771
sspicli.dll	C:\Windows\System32\sspicli.dll	10.0.17763.1490
w3tp.dll	c:\Windows\System32\inetsrv\w3tp.dll	10.0.17763.1
w3dt.dll	c:\Windows\System32\inetsrv\w3dt.dll	10.0.17763.771
httpapi.dll	C:\Windows\System32\httpapi.dll	10.0.17763.1728
NapiNSP.dll	C:\Windows\System32\NapiNSP.dll	10.0.17763.1
mswsock.dll	C:\Windows\System32\mswsock.dll	10.0.17763.1192
dnsapi.dll	C:\Windows\System32\dnsapi.dll	10.0.17763.1697
nsi.dll	C:\Windows\System32\nsi.dll	10.0.17763.1554
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	10.0.17763.615
nlaapi.dll	C:\Windows\System32\nlaapi.dll	10.0.17763.134
FWPUCLNT.DLL	C:\Windows\System32\FWPUCLNT.DLL	10.0.17763.1790
loghttp.dll	C:\Windows\System32\inetsrv\loghttp.dll	10.0.17763.1
cachuri.dll	C:\Windows\System32\inetsrv\cachuri.dll	10.0.17763.1
cachfile.dll	C:\Windows\System32\inetsrv\cachfile.dll	10.0.17763.1
cachtokn.dll	C:\Windows\System32\inetsrv\cachtokn.dll	10.0.17763.1
cachhttp.dll	C:\Windows\System32\inetsrv\cachhttp.dll	10.0.17763.1
compdyn.dll	C:\Windows\System32\inetsrv\compdyn.dll	10.0.17763.1
compstat.dll	C:\Windows\System32\inetsrv\compstat.dll	10.0.17763.1
defdoc.dll	C:\Windows\System32\inetsrv\defdoc.dll	10.0.17763.1
dirlist.dll	C:\Windows\System32\inetsrv\dirlist.dll	10.0.17763.1
protsup.dll	C:\Windows\System32\inetsrv\protsup.dll	10.0.17763.1
static.dll	C:\Windows\System32\inetsrv\static.dll	10.0.17763.1
authanon.dll	C:\Windows\System32\inetsrv\authanon.dll	10.0.17763.1
modrqflt.dll	C:\Windows\System32\inetsrv\modrqflt.dll	10.0.17763.557
custerr.dll	C:\Windows\System32\inetsrv\custerr.dll	10.0.17763.1
warmup.dll	C:\Windows\System32\inetsrv\warmup.dll	10.0.17763.1
iiswsock.dll	C:\Windows\System32\inetsrv\iiswsock.dll	10.0.17763.1
websocket.dll	C:\Windows\System32\websocket.dll	10.0.17763.1039
rewrite.dll	C:\Windows\System32\inetsrv\rewrite.dll	7.1.1993.2351
aspnetcore.dll	C:\Windows\System32\inetsrv\aspnetcore.dll	12.1.20266.23
winhttp.dll	C:\Windows\System32\winhttp.dll	10.0.17763.1728
aspnetcorev2.dll	C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll	13.1.20268.9
shell32.dll	C:\Windows\System32\shell32.dll	10.0.17763.1790
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	10.0.17763.1
SHCore.dll	C:\Windows\System32\SHCore.dll	10.0.17763.1697
windows.storage.dll	C:\Windows\System32\windows.storage.dll	10.0.17763.1728
profapi.dll	C:\Windows\System32\profapi.dll	10.0.17763.1075
powrprof.dll	C:\Windows\System32\powrprof.dll	10.0.17763.1
shlwapi.dll	C:\Windows\System32\shlwapi.dll	10.0.17763.1697
version.dll	C:\Windows\System32\version.dll	10.0.17763.1
crypt32.dll	C:\Windows\System32\crypt32.dll	10.0.17763.1790
msasn1.dll	C:\Windows\System32\msasn1.dll	10.0.17763.1
dpapi.dll	C:\Windows\System32\dpapi.dll	10.0.17763.1
gzip.dll	C:\Windows\System32\inetsrv\gzip.dll	10.0.17763.1
hostfxr.dll	C:\Program Files\dotnet\host\fxr\3.1.9\hostfxr.dll	3.100.920.47301
hostpolicy.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\hostpolicy.dll	3.100.920.47301
aspnetcorev2_inprocess.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\aspnetcorev2_inprocess.dll	13.1.20267.9
coreclr.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\coreclr.dll	4.700.20.47201
ole32.dll	C:\Windows\System32\ole32.dll	10.0.17763.1697
System.Private.CoreLib.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Private.CoreLib.dll	4.700.20.47201
clrjit.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\clrjit.dll	4.700.20.47201
System.Runtime.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Runtime.dll	4.700.20.47203
Microsoft.AspNetCore.Server.IIS.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Server.IIS.dll	3.100.920.47309
System.Runtime.Extensions.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Runtime.Extensions.dll	4.700.20.47203
System.Threading.Tasks.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Threading.Tasks.dll	4.700.20.47203
Microsoft.AspNetCore.Hosting.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Hosting.Abstractions.dll	3.100.920.47309
Microsoft.AspNetCore.Hosting.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Hosting.dll	3.100.920.47309
netstandard.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\netstandard.dll	4.700.20.47203
Microsoft.AspNetCore.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.dll	3.100.920.47309
Microsoft.Extensions.Configuration.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Configuration.Abstractions.dll	3.100.920.47302
Microsoft.Extensions.DependencyInjection.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.DependencyInjection.Abstractions.dll	3.100.920.47302
Microsoft.Extensions.DependencyInjection.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.DependencyInjection.dll	3.100.920.47302
Microsoft.Extensions.Logging.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Logging.dll	3.100.920.47302
Microsoft.Extensions.Configuration.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Configuration.dll	3.100.920.47302
Microsoft.Extensions.Hosting.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Hosting.Abstractions.dll	3.100.920.47302
Microsoft.Extensions.FileProviders.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.FileProviders.Abstractions.dll	3.100.920.47302
System.Collections.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Collections.dll	4.700.20.47203
Microsoft.Extensions.Configuration.EnvironmentVariables.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Configuration.EnvironmentVariables.dll	3.100.920.47302
Microsoft.Extensions.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Primitives.dll	3.100.920.47302
System.Linq.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Linq.dll	4.700.20.47203
System.Threading.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Threading.dll	4.700.20.47203
System.IO.FileSystem.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.IO.FileSystem.dll	4.700.20.47203
Microsoft.AspNetCore.Http.Features.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Http.Features.dll	3.100.920.47309
System.Diagnostics.DiagnosticSource.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Diagnostics.DiagnosticSource.dll	4.700.20.47203
Microsoft.AspNetCore.Http.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Http.Abstractions.dll	3.100.920.47309
Microsoft.AspNetCore.Http.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Http.dll	3.100.920.47309
Microsoft.AspNetCore.Mvc.Core.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Mvc.Core.dll	3.100.920.47309
Microsoft.Extensions.FileProviders.Physical.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.FileProviders.Physical.dll	3.100.920.47302
System.Memory.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Memory.dll	4.700.20.47203
System.Runtime.InteropServices.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Runtime.InteropServices.dll	4.700.20.47203
Microsoft.Extensions.Configuration.FileExtensions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Configuration.FileExtensions.dll	3.100.920.47302
Microsoft.Extensions.Configuration.Json.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Configuration.Json.dll	3.100.920.47302
System.IO.FileSystem.Watcher.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.IO.FileSystem.Watcher.dll	4.700.20.47203
System.ComponentModel.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.ComponentModel.Primitives.dll	4.700.20.47203
System.Collections.Concurrent.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Collections.Concurrent.dll	4.700.20.47203
Microsoft.Extensions.FileSystemGlobbing.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.FileSystemGlobbing.dll	3.100.920.47302
System.Threading.Timer.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Threading.Timer.dll	4.700.20.47203
System.Threading.Overlapped.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Threading.Overlapped.dll	4.700.20.47203
Microsoft.Win32.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\Microsoft.Win32.Primitives.dll	4.700.20.47203
System.Text.Json.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Text.Json.dll	4.700.20.47203
System.Text.Encoding.Extensions.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Text.Encoding.Extensions.dll	4.700.20.47203
System.Buffers.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Buffers.dll	4.700.20.47203
System.Numerics.Vectors.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Numerics.Vectors.dll	4.700.20.47203
System.Runtime.CompilerServices.Unsafe.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Runtime.CompilerServices.Unsafe.dll	4.700.20.47203
System.Diagnostics.Tracing.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Diagnostics.Tracing.dll	4.700.20.47203
Microsoft.Extensions.Options.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Options.dll	3.100.920.47302
Microsoft.Extensions.Logging.Configuration.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Logging.Configuration.dll	3.100.920.47302
Microsoft.Extensions.Options.ConfigurationExtensions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Options.ConfigurationExtensions.dll	3.100.920.47302
Microsoft.Extensions.Logging.Console.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Logging.Console.dll	3.100.920.47302
Microsoft.Extensions.Logging.Debug.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Logging.Debug.dll	3.100.920.47302
Microsoft.Extensions.Logging.EventSource.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.Logging.EventSource.dll	3.100.920.47302
Microsoft.AspNetCore.Connections.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Connections.Abstractions.dll	3.100.920.47309
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll	3.100.920.47309
System.Net.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Net.Primitives.dll	4.700.20.47203
Microsoft.AspNetCore.Hosting.Server.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll	3.100.920.47309
Microsoft.AspNetCore.HostFiltering.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.HostFiltering.dll	3.100.920.47309
Microsoft.AspNetCore.HttpOverrides.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.HttpOverrides.dll	3.100.920.47309
Microsoft.AspNetCore.Routing.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Routing.dll	3.100.920.47309
Microsoft.Extensions.ObjectPool.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.Extensions.ObjectPool.dll	3.100.920.47302
Microsoft.AspNetCore.Routing.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Routing.Abstractions.dll	3.100.920.47309
System.ObjectModel.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.ObjectModel.dll	4.700.20.47203
Microsoft.AspNetCore.Authentication.Core.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Authentication.Core.dll	3.100.920.47309
Microsoft.AspNetCore.Authentication.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.9\Microsoft.AspNetCore.Authentication.Abstractions.dll	3.100.920.47309
System.Security.Claims.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Security.Claims.dll	4.700.20.47203
System.Reflection.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.Reflection.dll	4.700.20.47203
System.AppContext.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.AppContext.dll	4.700.20.47203
System.IO.FileSystem.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.IO.FileSystem.Primitives.dll	4.700.20.47203
System.IO.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.9\System.IO.dll	4.700.20.47203
...
`

How to reproduce
================
Not possible to reproduce normally, it occurs maybe once in two weeks at random time, which doesn't correlate to any infrastructure update or so.

Checklist
=========

Unhandled exception at 0x00007FFECAC81DCB (coreclr.dll).

StackTrace:
` 	ntdll.dll!RtlpExecuteHandlerForException()	Unknown
 	ntdll.dll!RtlDispatchException()	Unknown
 	ntdll.dll!KiUserExceptionDispatch()	Unknown
 	ntdll.dll!RtlpWaitOnCriticalSection()	Unknown
 	ntdll.dll!RtlpEnterCriticalSectionContended()	Unknown
 	ntdll.dll!RtlEnterCriticalSection()	Unknown
 	librdkafka.DLL!00007ffec2d1c2b1()	Unknown
 	librdkafka.DLL!00007ffec2d1c7ee()	Unknown
 	librdkafka.DLL!00007ffec2cb471d()	Unknown
 	librdkafka.DLL!00007ffec2cb4489()	Unknown
 	librdkafka.DLL!00007ffec2c657c0()	Unknown
 	[Managed to Native Transition]	
 	Confluent.Kafka.dll!Confluent.Kafka.Consumer<Confluent.Kafka.Null, NS.PPP.Checker.Contracts.ProCnt>.Consume(int millisecondsTimeout)	Unknown
 	Confluent.Kafka.dll!Confluent.Kafka.Consumer<Confluent.Kafka.Null, NS.PPP.Checker.Contracts.ProCnt>.Consume(System.Threading.CancellationToken cancellationToken)	Unknown
 	NS.PP.Messaging.Kafka.dll!NS.PP.Messaging.Kafka.ConfluentKafka.KafkaConsumerPoll<Confluent.Kafka.Null, NS.PPP.Checker.Contracts.ProCnt>.Poll(object state)	Unknown
>	System.Private.CoreLib.dll!System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() Line 879	C#
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 677	C#
 	System.Private.CoreLib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 29	C#
 	[Native to Managed Transition]	
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown`
 	
 	Confluent.Kafka nuget version: 1.5.0

**Comment by mhowlett** [comment]
unclear from the information provided, i'd need code & debug etc.
