### ISSUE TITLE
how can i pasue and resume the consumer safely,because I want to limit the poll request

### ISSUE THREAD

**Issue by JOJOJOFran** [confluentinc/confluent-kafka-dotnet#1580]
Description
===========
when I pasue the consumer, Should I need always call consumer.conusme(timeout) method? becasue consumer will maxpoll timeout.

i have paused the consumer, but consumer trigging to revoked, I need pause again in the PartitionsAssignedHandler?

Checklist
=========
 - [ 1.5.3] Confluent.Kafka nuget version.
 - [ 0.10.2 ] Apache Kafka version.

**Comment by mhowlett** [comment]
Yes, you need to keep calling `Consume` (this behavior matches the Java client). The idea is to protect against the case where the application is still running, but in a zombie state.

**Comment by JOJOJOFran** [comment]
@mhowlett when consumer rebalance , assigned partition changed,  will the pause probably not work? will the consumer thread consume the data ?
