### ISSUE TITLE
One Consumer Instance, Consume on One Thread, Manually Commit on Another?

### ISSUE THREAD

**Issue by phamrick** [confluentinc/confluent-kafka-dotnet#1581]
I've been trying to research the thread safety of doing this but I am not confident I understand.

Say I have two threads:

A) consumer thread
B) processing thread

Thread A has a consumer loop.

In thread B messages are processed.  Processing can take some time, but upon the successful processing of a message, it should be committed.

Is it OK to create a single instance of a consumer and then call it on thread A for consumption but also call it on thread B for committing (committing by offset)?

**Comment by mhowlett** [comment]
yes, but you might want to consider using `StoreOffsets` and let librdkafka auto commit for you. Set `EnableAutoCommit` to true (the default) and `EnableAutoOffsetStore` to false, then call `StoreOffsets` to signal that the offsets are ok for librdkafka to commit. It will commit regularly at an interval `AutoCommitIntervalMs`.

**Comment by dougolima** [comment]
@phamrick maybe [this project](http://github.com/Farfetch/kafka-flow) can help you.

You must just configure the `workersCount` property (.WithWorkersCount(X)) and then the framework will create X + 1 underlying threads for you (1 consumer thread  and X processing threads)
