### ISSUE TITLE
ProduceAsync fails with added await Task.Delay()

### ISSUE THREAD

**Issue by vishwajeets7** [confluentinc/confluent-kafka-dotnet#1585]
`var result =await client.APICall(record); //async method returns the API response

await producer.ProduceAsync(topic, new Message<keyObj,, ValObj> {key=result.Key, value=result.Value}, cancellationToken)
.ContinueWith(task = > {
 if(!task.IsFaulted) {....}
else {.....}
})`

APICall method:
`
public Async Task<KeyValuePair<k,v>> APICall(dynamic rec){
await Task.Delay(500);
return await Task.FromResult(GetStaticResponse());
}
`

Running the above code in Parallel.Foreach, runs as expected with actual http client call configured in the code.

However if the code in client.APICall method is replaced with await Task.Delay(500) with returning a static hard coded response, the producer throws Local key serialization error. (No issues with static response, its tested and ok)

In stead of await Task.Delay(500), the Thread.Sleep(500) works.

**Comment by mhowlett** [comment]
what is `keyObj`? whatever serializer you have registered to serializer values of that type is throwing an exception when it tries to serialize result.Value. You can look at the inner exception for more info.

**Comment by vishwajeets7** [comment]
Thank you for your response @mhowlett.

its a Json serialization being used here, and it works if the APICall function is calling Http client or with Thread.Sleep() for stimulated delay. However fails with await Task.Delay()

The exception or inner exception does not throw more details.

**Comment by vishwajeets7** [comment]
@mhowlett & team, Proposing the issue as a  bug 

Here are my findings, 
Facts:
Producer is using JsonSerialization with AsSyncOverAsync()
Flush is called with timespan of 5 seconds.

With httpClient Call:
1. Code works well with calling HttpClient to get required response

With hard coded response & Thread.sleep():
1. Code works well with returning hard coded response with a Thread.Sleep()

With hard coded response & await Task.delay();
1. Throws an exception as "Local: Key serialization error", with an inner exception of "Cannot access disposed object. Object name: System.Net.Http.HttpClient"

Note: In the failure scenario, there is no HttpClient object is used or referred in the code.
