### ISSUE TITLE
SchemaId set after assigned schemaById dictionary

### ISSUE THREAD

**Issue by jeremy001181** [confluentinc/confluent-kafka-dotnet#1586]
This [line](https://github.com/confluentinc/confluent-kafka-dotnet/blob/e5503c170662067a751710d027ddf06521e1ac73/src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs#L305) assigns `schemaById[schemaId]` with retrieved schema after setting `schemaId` 

Is it a bug? should it set the `schemaId` first before assigning the dictionary, otherwise it is going to be `0` for the first time when there is no cache?

**Comment by jeremy001181** [comment]
should the Line [305](https://github.com/confluentinc/confluent-kafka-dotnet/blob/e5503c170662067a751710d027ddf06521e1ac73/src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs#L305) swap with line 306

**Comment by jeremy001181** [comment]
@mhowlett hey Matt sorry for tagging you, can you help on this one please? Thanks

**Comment by mhowlett** [comment]
yes, that line should read:

```
schemaById[registeredSchema.Id] = registeredSchema.Schema;
```

do you agree?

**Comment by jeremy001181** [comment]
> yes, that line should read:
> 
> ```
> schemaById[registeredSchema.Id] = registeredSchema.Schema;
> ```
> 
> do you agree?

yes, I can create a PR for this if you agree

**Comment by mhowlett** [comment]
thanks - will include it in 1.7.0

**Comment by jeremy001181** [comment]
> thanks - will include it in 1.7.0

https://github.com/confluentinc/confluent-kafka-dotnet/pull/1587

**Comment by jeremy001181** [comment]
do you have a time estimate for 1.7.0 please? @mhowlett
