### ISSUE TITLE
Do we have DLQ (Dead letter queue) in .net library  

### ISSUE THREAD

**Issue by Purvesh-shah** [confluentinc/confluent-kafka-dotnet#1588]
Description
===========
HI There,

We are planning to add error mechanism, there are three approach, which one is suggested and recommended 
 

- Whenever there is error we will publish to error topic respective to each topic
- Whenever there is a error we will publish to common topic(needs to add custom partitioner ) 
-  Use DLQ(Dead letter queue)

How to reproduce
================
Question

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
what you want depends on your requirements...

there is no explicit concept of a dead letter queue in the API, but you can just use a normal topic for that purpose.
