### ISSUE TITLE
Own custom partition assignor

### ISSUE THREAD

**Issue by NewHouses** [confluentinc/confluent-kafka-dotnet#1589]
Hi, I'm trying to built a custom partition assignor, but I'm not pretty sure this is implemented in Kafka consumer c#.

**Comment by edenhill** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/blob/dddfb9313fc9b01c16c81ccd28766218b60c3900/test/Confluent.Kafka.IntegrationTests/Tests/Producer_CustomPartitioner.cs#L67

**Comment by NewHouses** [comment]
Thanks edenhill, but I mean a custom **assignor** for the consumers. I want that a consumer of a group consumer choose a partition with another strategy instead of range or roundrobin

**Comment by edenhill** [comment]
Oh, sorry. No, that is currently not possible and there are no immediate plans to provide such an interface.

Do note that there's now the cooperative-sticky assignor, as explained here: https://www.confluent.io/blog/incremental-cooperative-rebalancing-in-kafka/

**Comment by mhowlett** [comment]
(though best to wait for 1.7 before using the cooperative sticky assignor, some bug fixes coming)
