### ISSUE TITLE
App crashes after upgrading Confluent.Kafka to 1.6.3

### ISSUE THREAD

**Issue by michael-elly** [confluentinc/confluent-kafka-dotnet#1594]
Description
===========
I have a monitoring worker service written in C# .NET Core 3.1, using the admin Confluent.Kafka classes along with HWM querying and topic assignments to gather info on brokers, topics, partitions, ISR, high water marks, consumer lags, etc. This service scans all brokers/topics/partitions/consumers every ~ 20 sec (thread sleeps in between). 
This service was running fine for days in both Windows and Linux. 
After I upgraded the NuGet package from 1.4.4 to 1.6.3 (no other changes in the code) the service simply crashes without any crash stack info. 

I have a general app domain method to log unhandled exceptions, but this method does not even hit. Process simply crashes with no .NET stack info. Application logs don't show any information either, they just stop. 
AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;

The app crashes and the CurrentDomain_UnhandledException method never hits. 

This is the only thing I see in the windows event viewer:
Faulting application name: KafkaMon.exe, version: 1.0.0.0, time stamp: 0x602c3b1b
Faulting module name: ntdll.dll, version: 10.0.18362.1500, time stamp: 0x48069cf7

I see same issue when trying previous package 1.6.2
I also saw the same issue even when changed to .NET Core 5.0. 

When using confluent.Kafka version 1.5.3 the crash issue does not appear to happen any more. Hence we're seeing the problem with versions 1.6.x (both .NET Core 3.1 or 5.0). 

Apache Kafka 2.5.0. 

How to reproduce
================
I will need to send my entire project since I cannot get valuable debug/stack info today. Any guidance how to gather more info on the crash cause would be appreciated. 

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
hi @michael-elly - do you see this issue with v1.7.0-RC4 (now on nuget)?

**Comment by michael-elly** [comment]
Hi Matt, This is resolved with the latest v1.7.0-RC4. Thanks!! I was getting really worried about it... Do you know what could have caused it?

**Comment by mhowlett** [comment]
I don't have time to do an RCA in the the context of OS issues, but I do recall at least one librdkafka PR related to addressing  possible segfaults.

**Comment by michael-elly** [comment]
OK. Thanks.
