### ISSUE TITLE
Inappropriate exception in Consumer constructor

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#16]
When configuration parameters meant for a Producer are passed to the Consumer constructor, the following exception is thrown:

"Failed to redirect the poll queue to consumer_poll queue"

An exception should be thrown, but it should provide a more appropriate error message.

**Comment by mhowlett** [comment]
Notes / Questions:

1. The error returned by rd_kafka_poll_set_consumer is _UNKNOWN_GROUP. Why is a group.id required by rd_kafka_poll_set_consumer?
2. a call to rd_kafka_new (type Consumer) is successful with no group.id specified, but the resulting client is not really very useful. It seems it can be used for some things, for example querying the watermark offsets, but can't be used to consume anything.
3. The way things are then, I think I should add a check for the existence of "group.id" in the Consumer constructor and throw an appropriate exception if it doesn't exist.
4. but this seems wrong - why is a group.id a prerequisite for calling .Assign and reading messages from topics? Calling .Assign outside of .Subscribe does not create a consumer group as far as i can tell. And you can read messages having called it with no consumer group ever created. The way it seems this should work to me is for a group.id to not be required, and an exception thrown only if the user of the consumer tries to call .Subscribe (i.e. use group functionality).

**Comment by ewencp** [comment]
@edenhill may have different reasoning, but I actually prefer requiring the group ID (which the Java implementation doesn't require). Not doing so has multiple paths that can cause problems. Anything with group membership or offsets require a group ID. That means offset commit would also fail. And deciding what offset to start at would differ between the two modes (one checks for committed offsets first, the other doesn't). I think the confusing part is that it's not fail fast and leaves some functionality working (e.g. presumably all the generic stuff that's available on both producers and consumers).

**Comment by mhowlett** [comment]
First, I think it's pretty clear here given all the constraints that we should fail fast on no group.id and throw an exception with a good error. 

But... my preference for not having to specify group.id is strong. If I have to specify a group.id in scenarios where it's not needed I might be left wondering if there is something about those scenarios that I don't understand properly. If the requirements of the API match up with the actual operation, I'm left with more certainty - a better mental model more easily - of how things are working when I'm fiddling about trying to work things out. Kafka is complex, and I think this sort of thing is important to helping people grok it. 

This is made more important because some people do actually consume without using Kafka for group or offset management. I know of at least on big company that does this, and in fact I do this in a [substantial] hobby project (different reasons in each case). Surely there are more cases. Also, many of the tests/examples do not require consumer group functionality, yet require group.id to be specified and people will be looking at these to learn from.

**Comment by ewencp** [comment]
Sure, I get the argument for it. And yes, there are use cases where you don't need it. The most obvious one to me is any sort of debugging tool where you will just want to be able to inspect some messages, but never need to commit offsets. I also think it's sometimes worth optimizing the simplicity of the common case (fewer branches in docs to explain how things work in different scenarios) at the cost of the less common case being a bit harder or confusing. In any case, I'm sure @edenhill will have a better explanation than mine and probably already has user feedback on this.

**Comment by edenhill** [comment]
librdkafka originally had a simple low-level consumer API which does not make use of group.id.
The new high-level consumer is implemented partly on top of the low-level one and requires a group.id to be set to initialize the consumer group machinery which is later used by Subscribe(), Commit(), etc.

But since rd_kafka_new() can't know if the consumer instance it is being told to create will be used as a low-level or high-level consumer it can't really enforce the group.id until it is needed, which is when Subscribe() is called.

Why? backwards compatibility / API/ABI stability guarantees.

Since our language bindings only expose the high-level consumer it makes sense to enforce the group.id, even if some autonomous consumer-level operations dont require it, but as Ewen says such tools are rare and they can just set a dummy group.id for the time being. If it becomes a big community concern we can remove the group.id constraint on the Consumer constructor.

For reference, the Go consumer requires group.id to be set while the Python one doesn't.

**Comment by mhowlett** [comment]
Thanks for the background @edenhill 

BTW: i used the word 'strong' above, but perhaps 'definite' better reflects my sentiment here. Requiring a dummy group.id seems a bit klunky for a legitimate use case, but doesn't cause me too much anguish.

**Comment by edenhill** [comment]
We could stay with librdkafka's behaviour and error out on Subscribe() and Commit()

**Comment by edenhill** [comment]
:+1: on what Magnus said. Let's not over engineer things this early, the more transparent these bindings are the easier they'll be to support, and change as needed based on community feedback.

**Comment by mhowlett** [comment]
👍 on what Magnus said after he changes the behavior of rd_kafka_poll_set_consumer to not error out if group.id is not set. Additionally, if he does that, i'd buy him a beer.

**Comment by edenhill** [comment]
huhm, ooh, ok, yeah, we can't do that.
The consumer poll is the group, internally.

**Comment by mhowlett** [comment]
btw feel free to LGTM #30
