### ISSUE TITLE
Error Deserializing Avro Message - Magic byte was 20 expecting 0

### ISSUE THREAD

**Issue by weberms** [confluentinc/confluent-kafka-dotnet#1601]
Description
===========
When using the AvroDeserializer<T> class to deserialize a message with a defined schema in the schemaregistry, I get the following error:

Local: Value deserialization error
Expecting data with Confluent Schema Registry framing. Magic byte was 20, expecting 0

I haven't been able to find the culprit.  I confirmed with the application publishing the event that we're using the same schema.  I used avrogen to generate the classes used for deserialization.

Suggestions?

**Comment by mhowlett** [comment]
how are you writing the message to kafka? messages written using AvroSerializer include framing (in particular the id of the schema in schema registry) in addition to the avro data, it sounds like that is missing.

**Comment by weberms** [comment]
The message is written by another java-based application that we don't have control over.   It doesn't look like the .net client accepts any parameters to turn off "schema framing".  If that is the case what are our options?  

I'm also curious if the client is picking up the schema id from the message and then retrieving the schema from the schema registry why the schema is embedded in the _Schema field in the C# classes created by avrogen.

**Comment by weberms** [comment]
@mhowlett  I confirmed the upstream java app will not publish with schema framing to prevent vendor tie-in.  In that case should we be reading the events as byte[] or string and using Avro library directly to serialize/deserialize?  Do you have any examples of this use case?

**Comment by mhowlett** [comment]
yes, you can read read as byte[] and use the avro library directly.
the framing isn't vendor lock in - it just identifies the schema that was used to write the data, which you should really keep with the avro data as best practice (though there is an argument that this would be better in the kafka message header). you can easily avoid "vendor lockin" by providing your own CachedSchemaRegistryClient implementation (which could be trivial, if you're not managing schemas)

**Comment by weberms** [comment]
@mhowlett  The approach taken is the schema is identified with headers (subject and version) instead of the first 5 bytes of the message body.  Confluent schema id is not used.  It would be great if the Serdes classes supported a plain wire format and alternative way to pull the schema from the registry instead of only by ID so we didn't have to implement ourselves.

**Comment by prevostc** [comment]
We have this issue as well consuming a topic where we can't update the producer at all (that's from another company).
