### ISSUE TITLE
Consumer.QueryWatermarkOffsets does not behave properly when using authentication

### ISSUE THREAD

**Issue by jerive** [confluentinc/confluent-kafka-dotnet#1606]
Description
===========
When not using authentication, **Consumer.QueryWatermarkOffsets** returns a correct result regardless of whether a topic is being consumed or not.

When using authentication, **Consumer.QueryWatermarkOffsets** fails with 

```
Confluent.Kafka.KafkaException: Local: All broker connections are down
   at Confluent.Kafka.Impl.SafeKafkaHandle.QueryWatermarkOffsets
(String topic, Int32 partition, Int32 millisecondsTimeout)
```

and no network call happens.

But if and only if at least one topic is being consumed from the same consumer, the call will succeed.

We suspect it is more an issue with librdkafka but we would like your opinion on this

How to reproduce
================
Create a new consumer configured with authentication.
Call consumer.QueryWatermarkOffsets(topic).

```csharp
public class Program
{
      public static void Main(string[] args) {
          var topic = '...';
          var consumerConfig = new ConsumerConfig
          {
              BootstrapServers = ['localhost:9091'],
              SecurityProtocol = SecurityProtocol.SaslPlaintext,
              SaslMechanism = SaslMechanism.OAuthBearer
          };
          
          var consumer = new ConsumerBuilder<byte[], byte[]>(consumerConfig)
              // This method is not called
              .SetOAuthBearerTokenRefreshHandler(OAuthBearerTokenRefreshHandler)
              .Build();
  
          // Exception!
          consumer.QueryWatermarkOffsets(new TopicPartition(topic, 0), TimeSpan.FromSeconds(10));
      }
}
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version: 1.6.2
 - [x] Any kafka broker version
 - [x] Client configuration.
 - [x] Operating system: MACOS, Linux
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts. No need
 - [ ] Critical issue.

**Comment by jerive** [comment]
Found in librdkafka:

```csharp
/**
 * @brief SASL/OAUTHBEARER token refresh callback class
 * Note that before any SASL/OAUTHBEARER broker connection can succeed the
 * application must call RdKafka::oauthbearer_set_token() once -- either
 * directly or, more typically, by invoking RdKafka::poll() -- in order to
 * cause retrieval of an initial token to occur.
 *
 * An application must call RdKafka::poll() at regular intervals to
 * serve queued SASL/OAUTHBEARER token refresh callbacks (when
 * OAUTHBEARER is the SASL mechanism).
 */

/**
 * to avoid an initial connection stall as we wait for the application to call poll(). 
 * /
```

**Comment by mhowlett** [comment]
connectivity issue, for more information, set the `Debug` config property to `all`
