### ISSUE TITLE
About IConsumer.Unassign

### ISSUE THREAD

**Issue by Megasoft2** [confluentinc/confluent-kafka-dotnet#1610]
Description
===========

Updating .net consumer console app: Confluent.Kafka (0.11.6) to Confluent.Kafka (**1.6.3**) (.Net Core 3.1)
The IConsumer.Unassign() is invoked in case of error for re-start consume from last starting point  (Without applying commit)

Now with Confluent.Kafka (1.6.3) is another behavior: Stop consumption and it does not receive messages until the next consumer group rebalance occurs!
Any suggestions or comments to receive messages again at a certain time?

How to reproduce
================
Here you are an example:

Boolean IsProcessOk = false;
ConsumeResult<Ignore, String> mConsumeResult = null;
Try
{
  mConsumeResult  = myKafkaconsumer.Consume(500);
  if ( mConsumeResul != null)
  {
  // Add the message to string collection
   msgCount  +=1;
  }

  if (msgCount % MIN_COMMIT_COUNT = 0)
  {
   throw new ArgumentException("a test");
  // Kafka commit and string collection is saved.
  }
  IsProcessOk = true;
}
catch (Exception ex)
{
   myLog(ex, mConsumeResult)
}
Finally
{
if (!IsProcessOK)
   {
      myKafkaconsumer.**Unassign()**;  
     //Clear the string collection
   }
}

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ X] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by Megasoft2** [comment]
Hi. I found a solution: 
The method: Assign
For example.
myKafkaconsumer.Unassign();
//Clear the string collection
myKafkaconsumer.Assign(mPartitions);

That's all. Work for me!
Any comments?
Thanks.

**Comment by mhowlett** [comment]
i'm not quite following. closing, since you seem to have worked it out.
