### ISSUE TITLE
[IDeserializer<T>] Add Partition and Offset to SerializationContext

### ISSUE THREAD

**Issue by DrorOzgaon** [confluentinc/confluent-kafka-dotnet#1611]
Description
===========
Currently, the SerializationContext contains the Topic, is it possible to have the Partition and the Offset as well?

When we fail to deserialize a message we want to know what partition and offset the message came from so we can log and further analyse the issue.

Is there another way to retrieve this information within the Deserializer?

How to reproduce
================
1. Create a string Producer
2. Produce any message
2. Create a string Consumer
3. Create a custom IDeserializer<string> and log the topic name from the SerializationContext.Topic property --> **Ideally here we would have more information about the consumption like the Partition and the Offset.**
4. SetValueDeserializer to the custom IDeserializer<string> created in #3
5. Consume a message
6. Log exists with the topic name

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. --> Latest
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
No - throw an exception and put this logic outside the Consume method (which is structurally better under all circumstances i can think of).

**Comment by mhowlett** [comment]
`ConsumeException.ConsumerRecord` should give you this.

**Comment by DrorOzgaon** [comment]
That works for me, thanks for pointing that out!
