### ISSUE TITLE
Two times more outgoing messages on Azure Metrics dashboard [Question]

### ISSUE THREAD

**Issue by przeradalukasz** [confluentinc/confluent-kafka-dotnet#1612]
Description
===========

I use Confluent.Kafka with Azure Event Hub. Everything works just fine but one thing bugs me.

On Azure Portal Metrics screen you can check Incoming vs Outgoing messages, like that:
![obraz](https://user-images.githubusercontent.com/22884026/117705899-f06c3480-b1cc-11eb-8aaf-bfe05f1b6b80.png)

As you can see there are 2x more outgoing messages. I have only one consumer group and by debugging application locally I am certain that it does not duplicate messages taken from Event Hub. But every triggered Consume shows as 2 outgoing messages on the Azure Metrics Screen. 

Do I have something to worry about or maybe thats some known bug with the Metrics dashboard ?

**Comment by mhowlett** [comment]
i'm afraid i have never used Event Hubs, have you tried Confluent Cloud on Azure? https://www.confluent.io/azure/
