### ISSUE TITLE
manually committing offsets in kafka 

### ISSUE THREAD

**Issue by PoojaSingh15** [confluentinc/confluent-kafka-dotnet#1616]
Description
===========
I have a list of offsets with their corresponding partition and I need to commit them manually.
To do so I am looping through the list and assigning partition to the consumer and then seeking to a particular offset.
then I am consuming the message and passing the ConsumerBulider to commit method. 
Sometimes it executes smoothly but sometimes it throws "Local:Waiting for Coordinator" exception. 
But in both the cases , when I try consuming messages afterwards I re-consume the same series of messages I already have committed or should I say I tried committing. Which means I never really could commit them :(

foreach(var item in cmdparamslist) 
                {
                    Partition p = new Partition(Int16.Parse(item.PartitionID));
                    TopicPartition tp = new TopicPartition(configuration.GetSection("KafkaSettings").GetSection("Topic").Value, p);
                    Offset o = new Offset(long.Parse(item.Offset));
                    TopicPartitionOffset tpo = new TopicPartitionOffset(tp,o);
                    //Ltpo.Add(tpo);
                    try
                    {
                        KafkaConsumer.Assign(tpo);
                        await Task.Delay(TimeSpan.FromSeconds(1)); 
                        KafkaConsumer.Seek(tpo);
                        var cr = KafkaConsumer.Consume(cts.Token);
                        try
                        {
                            KafkaConsumer.Commit(cr);
                        }
                        catch (TopicPartitionOffsetException e1)
                        {
                             Console.WriteLine("exception "+e);
                        }
                        catch (KafkaException e)
                        {
                            Console.WriteLine("exception "+e);
                        }
                    }
                    catch (KafkaException e)
                    {
                          Console.WriteLine("exception "+e);
                    }
                }              
                   KafkaConsumer.Close();             
            }
            catch(Exception e)
            {
                Console.WriteLine("exception "+e);
            }
        }

Consumer / Client configuration:
var conf = new ConsumerConfig
            {
                GroupId = Guid.NewGuid().ToString(),
                BootstrapServers = configuration.GetSection("KafkaSettings").GetSection("RemoteServers").Value,
                AutoOffsetReset = AutoOffsetReset.Earliest,
                SaslMechanism = SaslMechanism.Gssapi,
                SecurityProtocol = SecurityProtocol.SaslPlaintext,
                EnableAutoCommit = false
                //EnableAutoOffsetStore = false
            };

I am using Confluent.Kafka 1.6.2 version

Could someone please help me ?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [x] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by mhowlett** [comment]
various notes:
- are you sure auto commit was set to false?
- you shouldn't call seek. that is required with the java API, but with librdkafka the assign method allows you to specify start offsets.
- if you want to commit specific offsets, you can just call commit with the list of TopicPartitionOffsets - no need to consume.
- if all you want to do is commit offsets, you don't even need to assign to the partitions, you can just commit them (this will fail if there are active consumers subscribed to the group though).
- best not to mix async and sync code - unfortunately the consumer api is sync. (i.e. don't use await Task.Delay)
- I'd need to investigate why the waiting for coordinator error is being exposed, but you can just retry in that case, and also be confident offsets weren't committed because it's a local error.

**Comment by PoojaSingh15** [comment]
Thank you mhowlett for your response
- Yes , I have explicitly configured that, while creating ConsumerConfig instance => EnableAutoCommit = false
Is there a way to make sure it is properly set?

- okay , I didn't know that , I need to learn more about it 

- Yes I tried directly passing list of offsets to commit , but didn't work , I still am getting the same messages :(

                List<TopicPartitionOffset> Ltpo = new List<TopicPartitionOffset>();
                foreach(var item in cmdparamslist) 
                {
                    Partition p = new Partition(Int16.Parse(item.PartitionID));
                    TopicPartition tp = new TopicPartition(configuration.GetSection("KafkaSettings").GetSection("Topic").Value, p);
                    Offset o = new Offset(long.Parse(item.Offset));
                    TopicPartitionOffset tpo = new TopicPartitionOffset(tp,o);
                    Ltpo.Add(tpo);
                }
                try
                {
                    KafkaConsumer.Commit(Ltpo);
                }
                catch (Exception e)
                {
                    Console.WriteLine("exception " + e);
                    err = "Y";
                }

**Comment by mhowlett** [comment]
> I have explicitly configured that, while creating ConsumerConfig instance => EnableAutoCommit = false
Is there a way to make sure it is properly set?

there is currently no way to read back configuration actually in use, we have discussed adding this.

> foreach(var item in cmdparamslist) 

where is `cmdparamslist` coming from?

**Comment by PoojaSingh15** [comment]
Thank you mhowlett.

cmdparamslist is an input to my application. It contains the list of offsets and their corresponding partition for which application needs to perform commit.
I am clueless why I am not able to commit the offsets manually :(
