### ISSUE TITLE
Question: can get a topic partitions count?

### ISSUE THREAD

**Issue by BEagle1984** [confluentinc/confluent-kafka-dotnet#1617]
I'd like every instance of my microservice to consume every partition, since my topic contains some data I need to load into memory at startup.
To do so I think I could simply statically assign all partitions.
I would like to know if there is a smart way to assign all partitions. Or an API to retrieve the amount of partitions in a topic. Otherwise I'd need a config for the amount of partitions but I don't like that a lot, since the topic configuration is under the control of the produce and would require some synchronization across the projects.

So, is there a way to assign all partitions without hardcoding the partitions count?

**Comment by BEagle1984** [comment]
I think what I may be looking for is a porting of `partitionsForTopic` method from the [Java Consumer](https://kafka.apache.org/26/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html)

**Comment by mhowlett** [comment]
just subscribe to the topic (with a unique consumer group)

or the GetMetadata method on the admin client will give you the information you want.

**Comment by leader80** [comment]
@mhowlett but what if you want to scale horizontally with more pods?

**Comment by BEagle1984** [comment]
Subscribing with a unique consumer group could work but it isn't as dynamic since the group.id has to be listed in the ACL. Therefore we wouldn't be able to freely scale.
Furthermore, isn't this just an unneeded overhead? I don't even want the offset to be stored server-side, as I will always just consume from the beginning.

Using the `AdminClient` could be an option.

Do you know if the Java client uses the admin API as well? Or is it another mechanism?

**Comment by mhowlett** [comment]
The Java client's `partitionsFor` method does a broker metadata request for the topic (the same as GetMetadata in the .net client), that will tell you what you want.

subscribing to the group requires a couple more server round trips, but in the scheme of things, in most scenarios, would be negligible overhead. if you don't commit offsets, there's no overhead to using groups due to that specifically.

**Comment by BEagle1984** [comment]
Ah yes, we could even avoid committing the offsets for this case.

Thank you @mhowlett for the clarifications. I think we got all information to decide how to proceed. Both options seems actually feasible (`AdminClient` or subscribing with a dynamic group id, given we find a workaround for the ACL and we maybe avoid committing).
