### ISSUE TITLE
question: using pause/resume to control which partition gets consumed?

### ISSUE THREAD

**Issue by BEagle1984** [confluentinc/confluent-kafka-dotnet#1621]
In my library/framework (https://github.com/BEagle1984/silverback/) I create a sort of blocking collection per each partition (a `Channel` actually) and I push the consumed messages into them. The messages from different partitions are therefore processed in parallel, while the blocking collection ensure that the backpressure is kept under control.

I wonder if I could/should use `Pause` and `Resume` on the consumer to further optimize this mechanism. The idea is to pause the partition as soon as a message is being consumed and sent through the processing pipeline, to resume it immediately after it the processing is completed. This would ensure that a message taking longer to consume wouldn't affect in any way the processing of the other partitions.

What do you think? Is this a good idea in your opinion @mhowlett?

**Comment by mhowlett** [comment]
unfortunately, librdkafka clears locally cached messages for partitions that are paused, making your idea inefficient. we ultimately hope to improve that behavior, but the work is not prioritized afaik. i'd recommend only using pause / resume for protection against more extreme cases. i.e. to protect against potentially very unbalanced queueing in your .net code (if you are seeing that in practice).

**Comment by BEagle1984** [comment]
Got it, thank you for the quick and accurate reply.
