### ISSUE TITLE
IAdminClient.GetMetadata(topic, timeout) creates the topic if it doesn't exit

### ISSUE THREAD

**Issue by nathanscottdaniels** [confluentinc/confluent-kafka-dotnet#1622]
Description
===========
Within `IAdminClient` there is a method `GetMetadata(string topic, TimeSpan timeout)` which loads the metadata for a given topic.  If the topic does not exist, it actually gets created, instead of an exception being thrown or some other indication that the topic doesn't exist.  This is unexpected, though I am not sure if it's by design or not.

The problem starts in [AdminClient.cs#555](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/AdminClient.cs#L555) where `SafeKafkaHandle.newTopic(topic, IntPtr.Zero)` is called, which then calls [SafeKafkaHandle.NewTopic](https://github.com/confluentinc/confluent-kafka-dotnet/blob/2446dff3df20586d6c346b66bcf93c12471a32b0/src/Confluent.Kafka/Impl/SafeKafkaHandle.cs#L256).  The summary of that internal method states:

> Setting the config parameter to IntPtr.Zero returns the handle of an existing topic, or an invalid handle if a topic with name `topic` does not exist. Note: Only the first applied configuration for a specific topic will be used.

However, this is not true.  This method calls librdkafka's [rd_kafka_topic_new](https://docs.confluent.io/2.0.0/clients/librdkafka/rdkafka_8h.html#ab1dcba74a35e8f3bfe3270ff600581d8) method, which is used to create a topic, and if a null config pointer is provided, the default topic configuration is used.

How to reproduce
================
.NET 5 Top-level program:
```
using Confluent.Kafka;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

var client = new AdminClientBuilder(
    new[] {
        KeyValuePair.Create("bootstrap.servers", "localhost:19092"),
        KeyValuePair.Create("debug", "all"),
    })
    .SetLogHandler((_,m) => Console.WriteLine($"[{DateTime.Now}] [{m.Level}] {m.Message}"))
    .Build();

// "Get" the nonexistent topic
var nonexistentTopic = Guid.NewGuid().ToString("n");
var topicMetdata = client.GetMetadata(nonexistentTopic, TimeSpan.FromSeconds(1000)).Topics.SingleOrDefault();

Console.WriteLine($"Waiting for topic {nonexistentTopic} to suddenly appear...");

await Task.Delay(5000);

// Get all topics
var allTopics = client.GetMetadata(TimeSpan.FromSeconds(1000)).Topics;

// Fail when we see this topic in the all-topics
Console.WriteLine($"\nTopics: \n{String.Join("\n", allTopics.Select(t => t.Topic))}");
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. **1.7.0**
 - [x] Apache Kafka version. **6.0.1**
 - [x] Client configuration. **inine**
 - [x] Operating system.  **all of them**
 - [x] Provide logs (with "debug" : "..." as necessary in configuration). [librdkafka.log](https://github.com/confluentinc/confluent-kafka-dotnet/files/6517879/librdkafka.log)
 - [ ] Provide broker log excerpts. 
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
> Within IAdminClient there is a method GetMetadata(string topic, TimeSpan timeout) which loads the metadata for a given topic. If the topic does not exist, it actually gets created, instead of an exception being thrown or some other indication that the topic doesn't exist. This is unexpected, though I am not sure if it's by design or not.

yes, it's "by design" in that this is the behavior of the broker. you can disable this (and it is good practice) with the broker setting:

```
auto.create.topics.enable=false
```

**Comment by nathanscottdaniels** [comment]
I see.  I had no idea that auto.create.topics would also do so when getting metadata, but thank you for the clarification!  I will close this issue.
