### ISSUE TITLE
equivalent dotnet property for following for Producer(buffer.memory, max.block.ms, max.request.size) and Consumer(max.poll.records)

### ISSUE THREAD

**Issue by rpanzade** [confluentinc/confluent-kafka-dotnet#1623]
Description
===========
I am trying to find equivalent dotnet property for following for Producer and Consumer while creating instance.
But I am not able to find one. Aren't those supported or is there any equivalent property available?

For Producer -- buffer.memory, max.block.ms, max.request.size
For Consumer -- max.poll.records

Please provide the following information:
 - 1.5.3 Confluent.Kafka nuget version.

**Comment by mhowlett** [comment]
The consumer supplies one record at a time to the application, there is no equivalent property to max.poll.records.

On the producer, have a look at `queue.buffering.max.kbytes` and `batch.size`. There is no equivalent to `max.block.ms` (I would argue this is an anti-feature).

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
