### ISSUE TITLE
Feature Request: DependentConsumerBuilder

### ISSUE THREAD

**Issue by RafaelLiendo** [confluentinc/confluent-kafka-dotnet#1631]
Hi, I'm implementing a delayed retry logic. And for that I have to create multiple consumers with the same config. 

For example, my topics are going to look like this and I need a consumer for each one of them:
* my-topic
* my-topic_retry_5min
* my-topic_retry_30min
* my-topic_retry_1hr
* my-topic_dead-letter

I searched for a DependentConsumerBuilder and noticed that it is not implemented. Is there any good reason for that?

**Comment by mhowlett** [comment]
this isn't possible due to internal limitations, however we are hoping to build something even better, we just haven't been able to prioritize it.
