### ISSUE TITLE
Different behavior when using Produce and ProduceAsync

### ISSUE THREAD

**Issue by john-larson** [confluentinc/confluent-kafka-dotnet#1632]
In the following code snippet, when I use `Produce`, the message is consumed. But when I use the `ProduceAsync` version (the next line which  is commented out), the message is not consumed. I would expect the behavior to be the same with `Produce` and `ProduceAsync`. 

```
class Program
    {
        static void Main(string[] args)
        {
            var config = new ConsumerConfig
            {
                BootstrapServers = "localhost:9092",
                GroupId = Guid.NewGuid().ToString(),
                AutoOffsetReset = AutoOffsetReset.Latest
            };

            Task.Run(() => Start(config));

            while (true)
            {
                Console.ReadLine();
            }

        }

        private static void Start(ConsumerConfig config)
        {
            using var producer = new ProducerBuilder<Null, string>(config).Build();

            using var consumer = new ConsumerBuilder<Ignore, string>(config).Build();

            producer.Produce("test", new Message<Null, string> { Value = "test" });

            //producer.ProduceAsync("test", new Message<Null, string> { Value = "test" }).Wait();

            consumer.Subscribe(new List<string>() { "test" });

            var consumeResult = consumer.Consume();
            Console.WriteLine(consumeResult?.Message?.Value);

        }

    }
```

**Comment by john-larson** [comment]
Did anyone have a chance to at least confirm the issue?

**Comment by mhowlett** [comment]
`Produce` is non-blocking and you have `AutoOffsetReset` set to `Latest` meaning the consumer will start reading from the end of the log if there are no committed offsets for the group, which there won't be because you're using a unique group name. Evidently the ListOffsets request to Kafka initiated by the call to `Consume` is being serviced before the message is written to the log.

**Comment by john-larson** [comment]
Isn't `Produce` blocking and `ProduceAsync` non-blocking? And shouldn't `Produce()` and `ProduceAsync.Wait()` give the same results in terms of message consumption?

**Comment by mhowlett** [comment]
neither are blocking, except that you wait for `ProduceAsync`, which blocks the call, ensuring the message is in the log before you try to consume from it.

**Comment by john-larson** [comment]
If I understand you correctly, `Produce` is also asynchronous. It sounds kind of confusing since by convention, one is led to believe `Produce` is sync and `ProduceAync` is async.  But anyways, thanks for the clarification. 

And you are saying that calls to `Subscribe` and `Consume` act faster than `Produce` so that the message appears in the partition after `Consume` is waiting for a message, right?
