### ISSUE TITLE
Consumer groupId issue with multiple instance running

### ISSUE THREAD

**Issue by jackiesphan1996** [confluentinc/confluent-kafka-dotnet#1633]
Hi,

I am facing the issue in consuming the event from topic.  There are 3 partitions for topic and also there are three consumers in the same group Id that are consuming this topic. I tried to push 1000 message at the same time to the topic but only one consumer handles messages. I really want that each consumer in group will process a part of all message to reduce  whole processing time.

**Comment by jackiesphan1996** [comment]
![image](https://user-images.githubusercontent.com/59761905/121886970-56098e80-cd40-11eb-92f9-ccd028891846.png)

**Comment by jackiesphan1996** [comment]
I'm using _comsumer.Assign to set Consumer listen from specific partition.

**Comment by mhowlett** [comment]
it sounds like you are writing all the messages to the same partition?

**Comment by jackiesphan1996** [comment]
@mhowlett  this is another consumer
![image](https://user-images.githubusercontent.com/59761905/121903219-47c46e00-cd52-11eb-8cca-5a7ed7f379ab.png)

**Comment by jackiesphan1996** [comment]
@mhowlett I'm not sure but let me check producing part.

**Comment by zhanghaiboshiwo** [comment]
i have a same question

**Comment by mhowlett** [comment]
recommend inspecting the topic using some independent means, perhaps the kafka-consumer-group tool, confluent control center, or just looking at the relative size of the partitions on disk in the kafka data directory. this is not likely a problem with the consumer.
