### ISSUE TITLE
Client with EnableAutoOffsetStore=false commits offset automatically

### ISSUE THREAD

**Issue by bdpeterson** [confluentinc/confluent-kafka-dotnet#1635]
Description
===========
When attempting to block further processing of a Topic Partition when a recoverable failure occurs, the Consumed message offset is automatically committed prior to consumption.

My system is not able to shunt failures to another topic, as order is critical for data integrity.

I would expect that the received message would be processed and if failure occurred, the Offset would not be saved.

If the offset isn't saved, the next Consume call would result in the previously failed message.

This would result in a spin-loop of processing the same request and other behaviour to pause the polling of the topic/partition. 
However, this doesn't happen and it appears that the offset was committed.

I've attempted this with Confluent.Kafka versions :1.4.2, 1.6.2, 1.7.0.
Running with dotnet core 5.0 or 3.2 
on MacOX.

This is a critical issue as I am unable to use Kafka if this is a software problem outside my control.

How to reproduce
================
Using the examples provided at https://github.com/confluentinc/examples/tree/6.2.0-post/clients/cloud
with the following modifications (Enable Auto Commit = true and Enable Auto Offset Store false):
`        static void Consume(string topic, ClientConfig config)
        {
            var consumerConfig = new ConsumerConfig(config);
            consumerConfig.GroupId = "dotnet-example-group-1";
            consumerConfig.AutoOffsetReset = AutoOffsetReset.Earliest;
            consumerConfig.EnableAutoCommit = true;
            consumerConfig.EnableAutoOffsetStore = false;

            CancellationTokenSource cts = new CancellationTokenSource();
            Console.CancelKeyPress += (_, e) => {
                e.Cancel = true; // prevent the process from terminating.
                cts.Cancel();
            };

            using (var consumer = new ConsumerBuilder<string, string>(consumerConfig).Build())
            {
                consumer.Subscribe(topic);
                var totalCount = 0;
                try
                {
                    while (true)
                    {
                        try
                        {
                            var cr = consumer.Consume(cts.Token);
                            totalCount += JObject.Parse(cr.Message.Value).Value<int>("count");
                            Console.WriteLine(
                                $"Consumed record with key {cr.Message.Key} and value {cr.Message.Value}, and updated total count to {totalCount}");
                            throw new ArgumentException();
                            // consumer.StoreOffset(cr);
                        }
                        catch (ArgumentException ex)
                        {
                            Console.WriteLine("Exception thrown.");
                        }
                    }
                }
                catch (OperationCanceledException)
                {
                    // Ctrl-C was pressed.
                }
                finally
                {
                    consumer.Close();
                }
            }
        }
`

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by bdpeterson** [comment]
The documentation could be a lot more clear.

It appears that the Consumer will continue processing those delivered to the Consumer... if the Consumer dies, it will restart at the initial offset.

For my needs, I am leveraging a combination of the consumer  Seek on failure, and StoreOffset on success.
I pause individual partitions on a failing topic to allow other partitions to continue forward.

If a poison pill is introduced, it will affect a single partition on the topic until such time it is ejected or re-try failure count is exhausted.

**Comment by mhowlett** [comment]
After reading quickly, i'm not quite following (you may be assuming traditional messaging like semantics, I can't quite tell). The functionality related to storing/committing/reading message semantics is well tested and widely used and is unlikely to be operating incorrectly. Note that most use cases do not require use of `Seek`.
