### ISSUE TITLE
Support for OAuthBearer SASL authentication mechanism for C# desktop application

### ISSUE THREAD

**Issue by kamleshsingh4u** [confluentinc/confluent-kafka-dotnet#1636]
Description
===========
It seems now Confluent kafka is already supporting the OAuthBearer SASL Authentication mechanism for C#.net,
We are using our own jwt token and validating it on kafka broker service deployed on our internal cloud. We wanted to use this token on consumer and producer side to send to broker and validate it.

We are looking for a C# sample consumer producer which is implementing the OAuthBearer SASL authentication mechanism.

How to reproduce
================
We are looking for a C# sample consumer producer which is implementing the OAuthBearer SASL authentication mechanism.
Can we have the sample please, it will help a lot to people who wanted to use OAuthBearer SASL authentication mechanism in C# and connecting kafka.

Checklist
=========

Please provide the following information:
 - [need sample ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ using the lastes version which shows Auth bearer machanism] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [C# consumer will run on desktop windows ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
Take a look at the integration tests:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/test/Confluent.Kafka.IntegrationTests/Tests/OauthBearerToken_PublishConsume.cs
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/test/Confluent.Kafka.IntegrationTests/Tests/OauthBearerToken_Delegate.cs

yes, we need to get some better documentation for this.
