### ISSUE TITLE
How to reduce the size of so file for .net core

### ISSUE THREAD

**Issue by chaoscn** [confluentinc/confluent-kafka-dotnet#1637]
Description
===========
We are using  <PackageReference Include="Confluent.Kafka" Version="1.4.4" /> for .net core project.
When publish the project, it generates a few ".so" files.
Those files contained debug information and make our overall binary size too large.
For example:
debian9-librdkafka.so - 23045K
alpine-librdkafka.so - 18470K

Is there any way to reduce the size of those ".so" files by eliminate debug information or even remove some unnecessary so files ?

 Thanks,
Chenhao

**Comment by mhowlett** [comment]
There are multiple .so's corresponding to different platforms. You only need the one(s) for the platform(s) you're deploying to. You could write a script that's executed after you build your project to remove the ones you don't want. Unfortunately there's not a cleaner way to do this the way things are set up. This should work - if it doesn't, please report back. The binaries themselves can't be minimized any further AFAIK.
