### ISSUE TITLE
Problem with WPF

### ISSUE THREAD

**Issue by zxfishhack** [confluentinc/confluent-kafka-dotnet#164]
in a class inherited from INotifyPropertyChanged，
public void SubScribe()
{
	var brokerList = Ip + ":" + Port;
	var config = new Dictionary<string, object>
	{
		{"group.id", _groupId },
		{"bootstrap.servers", brokerList }
	};

	var consumer = new Consumer<string, string>(
		config, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)
		);
	consumer.Subscribe(Topic);
	consumer.OnMessage += OnMessage;
	Task.Run(() =>
	{
		while (true)
		{
			consumer.Poll();
		}
	});
	NotSubscribe = false;
}

after calling SubScribe()，CPU ratio will raise up to 13%（4C8T I7） without receiving any messages.

**Comment by edenhill** [comment]
@zxfishhack What version are you using? 
If v0.9.4 you are probably seeing #87 in which case you should upgrade to v0.9.5

**Comment by zxfishhack** [comment]
upgraded to v0.9.5, problem solved.
