### ISSUE TITLE
What is the equivalent of fetch.max.wait.ms for testing kafka consumer?

### ISSUE THREAD

**Issue by Enthusiast-block** [confluentinc/confluent-kafka-dotnet#1640]
Hi @mhowlett and team

I am tesing kafka producer and consumer using shell script :- 

kafka-producer-perf-test.sh and
kafka-consumer-perf-test.sh

While testing producer I am using the command :- 

bin/kafka-producer-perf-test.sh --topic topic_name --num-records 1000 --throughput -1 --producer-props bootstrap.servers=host:port batch.size=100000 acks=1 linger.ms=100 buffer.memory=33554432 compression.type=lz4 --record-size 1000

and while using consumer, I am using the command :- 

bin/kafka-consumer-perf-test.sh --topic topic_name --bootstrap-server host:port --messages 1000 -fetch-size 100000 --timeout 300000

Like for producer there are parameters :- batch.size and linger.ms
and for consumer there are parameters :- --fetch-size

I want to know that through which parameter (to consumer) we can tell the kafka cluster to wait for a certain time (ms) and then send the message whenever a pull is wanted.

I did a kafka-consumer-perf-test.sh --help,
but could not find a parameter that does it for me?

Thanks for the help.

**Comment by mhowlett** [comment]
I'd guess you can set propertyname=value like the kafka-producer-perf-test, but I didn't check.

If you're interested in performance of .net in particular, you could use this:
https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/test/Confluent.Kafka.Benchmark
(results will be different than java)
