### ISSUE TITLE
Question: Expected number of connections

### ISSUE THREAD

**Issue by HenningRoigaard** [confluentinc/confluent-kafka-dotnet#1645]
During a test we noticed that Kafka reported 2000-ish connections across 3 nodes, which clearly was all generated by our test (they went away once we terminated the test). 
The number seemed a little high, but then again, we did have 900-ish producers, a few with initialized transactions, 40-ish consumers running concurrently and a small number of admin client instances.

All in all, it made us wonder: How many connections are expected?

Is there any kind of documentation or rule of thumb on this?

I would expect that each producer, consumer, and admin client instance to have at most as many connections as there are nodes in the Kafka cluster. That is, it never makes sense for one instance to have 2 or more connections to the same node. Is this correct?

From purely guesswork I would expect the number of connections to be the number of _unique nodes_ from

**Producers**
* 1 Connection per partition leader to which we produce.
* 1 Connection to Transaction Coordinator if transaction is initialized.

**Consumers**
* 1 Connection per partition leader from which we consume.
* 1 Connection to Consumer Group Coordinator if member of group.

**Admin Client**
* 1 Connection per node involved in a request.

Are there other sources for connections than these?

With n nodes, that should provide an upper limit of (n+1) connections per producer or consumer, and n connections per admin client. Is this correct? 

Conversely, I would expect that connections may actively be kept lower than this:

* I know that Kafka can close idle connections, but according to [FAQ](https://github.com/edenhill/librdkafka/wiki/FAQ), librdkafka always automatically reconnects these. Thus, the remote idle connection reaper appears to reduce the number of connections only shortly. Is there some kind of similar idle connection reaper on the client side which only reconnects when needed (not counting disposing the instance of course)? 
* Is there any kind of connection sharing which may reduce the number of connections below the expected cf. the above? E.g., can to different producer instances that produce to partitions on the same node share the same connection?

**Comment by edenhill** [comment]
Your assumptions are correct:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#sparse-connections

2000 connections for 940 client instances seems reasonable:
bootstrap connections may be kept alive by metadata refresh (topic.metadata.refresh.interval.ms), whose connections are selected randomly but weighing the most frequently used connection.
See https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L1408

> librdkafka always automatically reconnects these

only if it needs the connection (e.g., requests to be sent).


Which librdkafka version are you on? 

> Is there any kind of connection sharing which may reduce the number of connections below the expected cf. the above?

No, connections will not be shared across client instances.

**Comment by HenningRoigaard** [comment]
Thank you for the answer.

We are using 1.5.1 of the .net library, so I guess that means 1.5.0 of librdkafka

**Regarding automatic reconnect**
It is great that it only reconnect if needed.
The [FAQ](https://github.com/edenhill/librdkafka/wiki/FAQ ) though seems to indicate that reconnect happens based on time, and not if they are needed:
> NOTE: Whenever a connection is closed for whatever reason, librdkafka will automatically reconnect after reconnect.backoff.jitter.ms (default 500ms).

Is that note wrong, or am I confusing something?

**Comment by edenhill** [comment]
Yeah, that doc should be updated to say "will automatically reconnect (if needed) after .."
