### ISSUE TITLE
Any plan to support [KIP-568] Enforce Rebalance

### ISSUE THREAD

**Issue by guilherme-bauer** [confluentinc/confluent-kafka-dotnet#1648]
Hi, i would like to know if there is any plan to support [KIP-568](https://cwiki.apache.org/confluence/display/KAFKA/KIP-568%3A+Explicit+rebalance+triggering+on+the+Consumer) Enforce Rebalance.

Thanks!

**Comment by mhowlett** [comment]
it's not scheduled yet, but in general the plan is that librdkafka will support everything that java client does. with that said, this looks like something that may get bumped for a bit to allow us to get other stuff done. recommend opening a librdkafka issue and making the case for the importance of this feature.
