### ISSUE TITLE
SchemaRegistryClient does not support References for AVRO schemas

### ISSUE THREAD

**Issue by Khazuar** [confluentinc/confluent-kafka-dotnet#1649]
Even though explicitly allowed by [the documentation](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)), the [RestService](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry/Rest/RestService.cs#L320) only sends the `SchemaString` without the references to the SchemaRegistry. This is done explicitly because of "backwards compatibility" reasons (I suspect to support SchemaRegistry < v5.5.0).

**Comment by mhowlett** [comment]
This isn't supported by the Avro .NET implementation. Generally, I would recommend using either Protobuf of Json with .NET.

**Comment by Khazuar** [comment]
What do you mean by "not supported by the Avro .NET implementation"? What else is not working with Avro schema references?
