### ISSUE TITLE
Custom Partitioners

### ISSUE THREAD

**Issue by bkim54** [confluentinc/confluent-kafka-dotnet#165]
Can we set custom partitioners?

What is currently the default partitioning scheme for producing messages, and can we change it?

Thanks!

**Comment by treziac** [comment]
Duplicate of #139 

Not for now, though it should come soon
The default partitioner currently used is consistent_random: it takes the hash of the key (if provided) so all messages with same keys are produced to same partitions, and random for values without key (beteen 0 and partition_count-1).

**Comment by bkim54** [comment]
what is the hash being used? It is the same as the java client? (murmur2) 

thanks!

**Comment by edenhill** [comment]
librdkafka uses a consistent_random partitioner by default.
If there is no key a random partition will be used,
if there is a key a crc32 hash of the key will be used.

**Comment by edenhill** [comment]
It uses CRC32 for hashing.
There are plans to add a partitioner that is compatible with the Java producer.

**Comment by bkim54** [comment]
sounds good, looking forward to the additions!
