### ISSUE TITLE
IAM Access Control Setting for Confluent Kafka .Net Library

### ISSUE THREAD

**Issue by vivekkwatra** [confluentinc/confluent-kafka-dotnet#1651]
Description
===========

We are running Apache Kafka using AWS service i.e. AWS MSK and AWS MSK cluster has configured to use IAM-based security mechanism. How we can configure IAM Mechanism in Confluent Kafka .Net library? Incase it is not possible any pointers how we can implement IAM based mechanism like the one mentioned for Java client at https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html (Configure clients for IAM access control)

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ 1.6.3] Confluent.Kafka nuget version.
 - [ AWS MSK] Apache Kafka version.
 - [ ] Client configuration.
 - [Windows 10 ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
https://github.com/edenhill/librdkafka/issues/3402
