### ISSUE TITLE
Code Snippet

### ISSUE THREAD

**Issue by anantupadhyay5786** [confluentinc/confluent-kafka-dotnet#1652]
Description
===========

I need to support for Partition Level Consumers which means each consumer is dedicated to specific partition for consume.
Do we have any code snippet or the support for the same ?
Please do let me know

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
We don't have an example. You need to build an additional queuing layer on top of the consumer which combines all messages / events into a single queue for all partitions it's assigned to. We have discussed adding a per-partition consume to the API, but don't have a timeline for this. And do you need support for consumer groups? if not, just use `Consumer.Assign` directly and not `Consumer.Subscribe`.
