### ISSUE TITLE
confluent-kafka avro Value deserialization error

### ISSUE THREAD

**Issue by wuliaolaomo** [confluentinc/confluent-kafka-dotnet#1654]
I am using consumer with schema registry to consume Avro data,while error occurs like this:

Message = "Local: Value deserialization error"

StackTrace = " at Confluent.Kafka.Consumer2.Consume(Int32 millisecondsTimeout)\r\n at Confluent.Kafka.Consumer2.Consume(CancellationToken cancellationToken)\r\n `

This is the code:
var consumeTask1 = Task.Run(() =>
            {
                using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
                using (var consumer =
                    new ConsumerBuilder<string, QuoteMessage>(new ConsumerConfig { BootstrapServers = bootstrapServers, GroupId = groupName })
                        .SetKeyDeserializer(new AvroDeserializer<string>(schemaRegistry).AsSyncOverAsync())
                        .SetValueDeserializer(new AvroDeserializer<QuoteMessage>(schemaRegistry).AsSyncOverAsync())
                        .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
                        .Build())
                {
                    consumer.Subscribe(topicName);
                    try
                    {
                        while (true)
                        {
                            try
                            {
                                var consumeResult = consumer.Consume(cts.Token);
                                var temp = consumeResult.Message.Value;
                                Console.WriteLine($"Key: {consumeResult.Message.Key}“);
                            }
                            catch (ConsumeException e)
                            {
                                Console.WriteLine(e.StackTrace);
                                Console.WriteLine($"Consume error: {e.Error}");
                            }
                        }
                    }
                    catch (OperationCanceledException)
                    {
                        consumer.Close();
                    }
                }
            });

confusingly,when i used GenericRecord to consume the message, it just fine,code like this:
var consumeTask = Task.Run(() =>
            {
                using (var schemaRegistry = new CachedSchemaRegistryClient(new SchemaRegistryConfig { Url = schemaRegistryUrl }))
                using (var consumer =
                    new ConsumerBuilder<string, GenericRecord>(new ConsumerConfig { BootstrapServers = bootstrapServers, GroupId = groupName })
                        .SetKeyDeserializer(new AvroDeserializer<string>(schemaRegistry).AsSyncOverAsync())
                        .SetValueDeserializer(new AvroDeserializer<GenericRecord>(schemaRegistry).AsSyncOverAsync())
                        .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
                        .Build())
                {
                    consumer.Subscribe(topicName);
                    try
                    {
                        while (true)
                        {
                            try
                            {
                                var consumeResult = consumer.Consume(cts.Token);
                                Console.WriteLine($"Key1111111: {consumeResult.Message.Key}\nValue: {consumeResult.Message.Value}");
                            }
                            catch (ConsumeException e)
                            {
                                Console.WriteLine($"Consume error: {e.Error.Reason}");
                            }
                        }
                    }
                    catch (OperationCanceledException)
                    {
                        consumer.Close();
                    }
                }
            });
thanks for your attention

**Comment by mhowlett** [comment]
the inner exception will give you more information.
recommend using protobuf or json if you can.

**Comment by wuliaolaomo** [comment]
> the inner exception will give you more information.
> recommend using protobuf or json if you can.

There's no further infomation about which value causing this exception ,so still unresolved

**Comment by wuliaolaomo** [comment]
> the inner exception will give you more information.
> recommend using protobuf or json if you can.

besides,when using /kafka-avro-console-consumer --topic wind --bootstrap-server xxx.xxx.xxx.xxx:9092 --perporty schema.registry.url="xxx.xxx.xxx.xxx:8081",it consumed the message normally

**Comment by mhowlett** [comment]
It will likely be an issue with the .NET Apache Avro library, specific to your schema.

**Comment by wuliaolaomo** [comment]
> It will likely be an issue with the .NET Apache Avro library, specific to your schema.

sir,the library, Apache.Avro 1.10.2;Confluent.SchemaRegistry.Serdes.Avro 1.7.0;
Another problem,the producer code and the consumer code are in the same project ,while it produced message correctly and could't consume the messge produced by that producer

**Comment by OneCricketeer** [comment]
> there is someting wrong with the code in .net?

Doubtful, since [the tests pass](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Avro/ProduceConsume.cs)
