### ISSUE TITLE
Question regarding consumer's offset deletion

### ISSUE THREAD

**Issue by paveldayneko** [confluentinc/confluent-kafka-dotnet#1655]
Kafka admin API has support for consumer's offset deletion. According to https://cwiki.apache.org/confluence/display/KAFKA/KIP-496%3A+Administrative+API+to+delete+consumer+offsets

Seems like librdkafka has this feature supported as well https://github.com/edenhill/librdkafka/blob/55ad6101ac80a9ba09b802eab1c4dbf484245004/src/rdkafka_request.c#L1400

I can't find a way to delete consumer's offset on C# library, does it mean this this feature is not adapted here yet?

**Comment by mhowlett** [comment]
yep, looks like we don't have it yet. shouldn't be too hard to add.
