### ISSUE TITLE
Message prioritization with bucket priority pattern

### ISSUE THREAD

**Issue by ffernandolima** [confluentinc/confluent-kafka-dotnet#1657]
Description
===========

I've taken a look at this [article](https://www.confluent.io/blog/prioritize-messages-in-kafka/) which has been published on the confluent.io website and it seems to be a good solution to implement message prioritization in Apache Kafka.

The example implementation is done using the java client library which exposes an easy way to create/implement custom partitioners and assignors.

I'm wondering if there's the possibility to create custom partitioners and assignors using the .NET client library.

As far as I looked for, custom partitioners can be implemented as it's done by these [examples](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/test/Confluent.Kafka.IntegrationTests/Tests/Producer_CustomPartitioner.cs), but how about custom assignors?

I'd appreciate any help to clarify the usage of these structures on the .NET client library.

Thanks in advance.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
Custom assignors are not yet possible with the .net client. Also, they aren't yet pluggable in librdkafka.

Side note: I would guess it is likely that Confluent will provide a built in solution for message prioritization on Kafka before too long, though not in the next 6 months say.

**Comment by ffernandolima** [comment]
@mhowlett thank you so much for the info.
