### ISSUE TITLE
Error on running project

### ISSUE THREAD

**Issue by shasu01** [confluentinc/confluent-kafka-dotnet#1659]
Description
===========
I followed the steps on the home screen, and clicked run and got the attached error about connection
![connection error](https://user-images.githubusercontent.com/30653592/126993385-7aa08afa-606c-4d90-9e46-2338176f779f.PNG)

How to reproduce
================
Create project in Visual Studio 2019 - .NET Core 3.1 Console Application
Install-Package Confluent.Kafka -Version 1.7.0
dotnet add package -v 1.7.0 Confluent.Kafka
Attached is the code from the project

![Kafka project](https://user-images.githubusercontent.com/30653592/126993893-4e7194f3-fcf7-40b1-a5cb-7bfb021ce3c0.PNG)

Checklist
=========
[Kafka.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/6878416/Kafka.zip)

**Comment by mhowlett** [comment]
I see you are on Windows, how are you running Kafka? The client isn't successfully connecting to any broker. This blog post might help you do that: https://www.confluent.io/blog/set-up-and-run-kafka-on-windows-linux-wsl-2/ or you could use Confluent Cloud.

**Comment by shasu01** [comment]
I have docker running

**Comment by OneCricketeer** [comment]
> I have docker running

Please refer to [this post](https://stackoverflow.com/questions/51630260/connect-to-kafka-running-in-docker)
