### ISSUE TITLE
Local: No offset stored - Error on Consumer

### ISSUE THREAD

**Issue by mahrvz** [confluentinc/confluent-kafka-dotnet#1661]
Description
===========

I get "Local: No offset stored" Exceptions in my Consumer. Is this bad? Can i just ignore/catch these Messages? What causes this?
I then restart the conusming instance and then it is working again.

Thanks for your help ind advance.

Cheers,
Michael

**Comment by ThreadedStream** [comment]
Hi, @mahrvz. Can you share your config map please?

**Comment by mahrvz** [comment]
Hi, 
this is our code:
`public class KafkaConsumer<TKey, TValue> : Abstraction.IConsumer<TKey, TValue>
        where TValue : ISpecificRecord
    {
        private readonly ConsumerConfiguration configuration;

        private ISchemaRegistryClient? schema;
        private IConsumer<TKey, TValue>? stream;

        private bool isConsumingEnabled;
        private Func<DataSynchronisationMessage<TKey, TValue>, bool>? messageHandler;
        private Action<DataSynchronisationError>? errorHandler;

        public KafkaConsumer(ConsumerConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public void Init()
        {
            schema = new CachedSchemaRegistryClient(new SchemaRegistryConfig { Url = configuration.SchemaRegistryUrl });

            stream = new ConsumerBuilder<TKey, TValue>(GetConsumerConfig(configuration))
                .SetKeyDeserializer(new AvroDeserializer<TKey>(schema).AsSyncOverAsync())
                .SetValueDeserializer(new TombstoneAvroDeserializer<TValue>(schema).AsSyncOverAsync())
                .Build();
        }

        public void UseErrorHandler(Action<DataSynchronisationError> handler)
        {
            errorHandler = handler ?? throw new ArgumentNullException(nameof(handler));
        }

        public void UseMessageHandler(Func<DataSynchronisationMessage<TKey, TValue>, bool> handler)
        {
            messageHandler = handler ?? throw new ArgumentNullException(nameof(handler));
        }

        public Task ConsumeAsync(string topic, CancellationToken cts)
        {
            if (stream == null)
            {
                throw new Exception($"must call {nameof(Init)} first");
            }

            return Task.Run(async () =>
            {
                stream.Subscribe(topic);

                try
                {
                    isConsumingEnabled = true;

                    while (isConsumingEnabled)
                    {
                        try
                        {
                            var result = stream.Consume(cts);

                            var message = new DataSynchronisationMessage<TKey, TValue>
                            {
                                Key = result.Message.Key,
                                Value = result.Message.Value,
                                Topic = result.Topic,
                                Offset = result.Offset.Value
                            };

                            // Callback must throw exceptions on error
                            if (messageHandler?.Invoke(message) == true)
                            {
                                // only commit the message
                                stream.Commit();
                            }
                        }
                        catch (ConsumeException e)
                        {
                            // if only deserialization-error: dead letter queue or stop
                            errorHandler?.Invoke(new DataSynchronisationError { Reason = e.Error.Reason, Code = (int)e.Error.Code });
                            throw;
                        }

                        await Task.Delay(configuration.PollDelay, cts);
                    }
                }
                catch (OperationCanceledException)
                {
                    // commit final offsets and leave the group.
                    stream.Close();
                }
            }, cts);
        }

        private static ConsumerConfig GetConsumerConfig(ConsumerConfiguration configuration)
        {
            var config = new ConsumerConfig
            {
                BootstrapServers = configuration.BootstrapServers,
                GroupId = configuration.GroupId,
                AutoOffsetReset = configuration.AutoOffsetReset ?? AutoOffsetReset.Latest,
                // no autocommit to make sure data can be processed before
                EnableAutoCommit = false
            };

            if (!configuration.IsSslEnabled)
            {
                return config;
            }

            config.SecurityProtocol = SecurityProtocol.Ssl;
            config.SslCaLocation = configuration.CaCertPath;
            config.SslCertificateLocation = configuration.ClientCertPath;
            config.SslKeyLocation = configuration.PrivateKeyPath;
            config.SslKeyPassword = configuration.PrivateKeyPassword;

            return config;
        }
    }`

**Comment by ilya-girman** [comment]
Same issue!
We have very simple setup with single partition topic with no huge load (only a few messages per minute). 

Configuration is: 
`

            var cfg = new ConsumerConfig
            {
                GroupId = DefaultConsumerGroup,
                BootstrapServers = bootStrapServers,
                EnableAutoCommit = false,
                AutoOffsetReset = AutoOffsetReset.Earliest,
            };`
Code is: 
`

            while (_running)
            {
                try
                {
                    var result = GetMessage(_stopCancellationSource.Token);
                    _timeOutCancellationSource.CancelAfter(CONSUME_MESSAGE_TIMEOUT_MS);
                    ConsumeMessage(result.Message, tokenSource.Token);
                    CommitMessage();
                }
                catch (ConsumerException e)
                {
                    LogError(e.Message);
                }
                // other catches
           }`
GetMessage and CommitMessage are very simple wrappers on _kafkaConsumerClient.Consume(ct) and _kafkaConsumerClient.Commit(); respectively.

We've just caught situation with this sequence:

1. We got message with offset 509, 
2. after that in Commit() we got exception with error: "**Confluent.Kafka.KafkaException: Local: No offset stored**".
3. We execute next GetMessage() and receive message **with offset 509 again**!
4. Second Commit() for message with offset 509 was called successfully.
5. All other messages starting from offset 510 were processed normally as expected.

I have no clue how could it be. Any thoughts will be highly appreciated.
Thank you!

Confluent.Kafka nuget version: 1.7.0
Kafka setup: 3 brokers. AWS-managed (MSK).

**Comment by mhowlett** [comment]
> We got message with offset 509, after that in Commit() we got exception with error: "Confluent.Kafka.KafkaException: Local: No offset stored". We execute next GetMessage() and receive message with offset 509 again!

i would guess you got a consumer group rebalance, and your application didn't commit offsets before it lost ownership of the partitions. after the rebalance, you got ownership of the partition again, and because offsets weren't committed you got the same message again.

you can block the rebalance from happening behind your back by setting partition revoke / assign handlers (that do nothing) - this works because they are called on the application thread as a side effect of consume and effectively block the rebalance until then. note though that you can only be guaranteed at-least once semantics without using transactions.
