### ISSUE TITLE
Magic bytes are missing in Avro serialized message

### ISSUE THREAD

**Issue by vishwajeets7** [confluentinc/confluent-kafka-dotnet#1663]
Description
===========
Have implemented custom serializer with Avro, noticed the magic bytes are missing while deserializing.

How to reproduce
================
Below is code used for custom serializer, noticed magic bytes don't exist while deserializing.

public class CustomAvroSerializer<T> : IAsyncSerializer<T>
    where T : class, ISpecificRecord
{
    public Task<byte[]> SerializeAsync(T data, SerializationContext context)
    {
        return Task.Run(() =>
        {
            using (var ms = new MemoryStream())
            {
                var enc = new BinaryEncoder(ms);
                var writer = new SpecificDefaultWriter(data.Schema);
                writer.Write(data, enc);
                return ms.ToArray();
            }
        });
    }
}

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by OneCricketeer** [comment]
As you've stated, you've created _your own Serializer_. If you did not put the "magic bytes" there in the serializer, can you explain why you'd expect them in the deserializer or record?

More specifically, what's the use case for having your own Serializer?

**Comment by vishwajeets7** [comment]
How to include magic bytes with custom serializer?

**Comment by OneCricketeer** [comment]
It would be [`enc.WriteBytes(byte[])`](https://avro.apache.org/docs/1.7.1/api/csharp/classAvro_1_1IO_1_1BinaryEncoder.html#ae5f01f625e96d3733ebea97f7d9466eb), but you're going off-road and this pattern is not supported by this project. 

You can [see in the source code](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs#L240-L250) that your code shown is almost the exact same that is already done for Specific Avro types
