### ISSUE TITLE
[Question] Does the project follow SemVer?

### ISSUE THREAD

**Issue by quixoticaxis** [confluentinc/confluent-kafka-dotnet#1665]
I've found a few mentions of SemVer in the closed issues, but could not find versioning being explicitely mentioned anywhere in the docs.

I had two small issues after upgrading from 1.5.3 to 1.7.0:
- The consumers and producers started quickly throwing when created while cluster is unreachable. I beleive it is a change to public API.
- The `IConsumer` and `IProducer` got additional methods that provide no default implementation. It can break builds, but, which is more dangerous, it can lead to runtime `TypeLoadException`s, because if Confluent.Kafka comes with different versions in dependency graph, .Net would silently feed 1.7.0 to the components that rely on 1.5.3.

**Comment by mhowlett** [comment]
we try to, but sometimes we make mistakes.

**Comment by quixoticaxis** [comment]
@mhowlett Thank you for the quick reply.
