### ISSUE TITLE
Lots of Metadata Threads Issue

### ISSUE THREAD

**Issue by recao** [confluentinc/confluent-kafka-dotnet#167]
Hi, we are new to confluent-kafka-dotnet, and recently started testing it as our Kafka consumer client. 

**Testing Environment Info:** 

- 346 Brokers Machines (Kafka=0.10.2, inter.broker.protocol.version=0.8.1, Windows OS)

- 10 Test Topics (each topic has partition 50 to 300, qps 1k to 10k)

- 30 Consumer Machines (Latest master branch of confluent-kafka-dotnet, consuming the same way as Run_Consume method in AdvancedConsumer under examples)

After started consuming, we notice each consumer has over 13,000 threads, all rd_kafka_metadata thread from librdkafka.dll. Thread Stack: 

![threads](https://cloud.githubusercontent.com/assets/20957260/25760105/10e20f54-318a-11e7-847f-c1ce3775107a.PNG)

We are not sure why so many meta fetching threads got created. Any idea of this? Thanks.

**Comment by mhowlett** [comment]
Given the large number of brokers / partitions, it would not surprise me if this is normal, though it still seems pretty high. @edenhill ?

**Comment by edenhill** [comment]
librdkafka will create at most 1+B+N threads per instance (an instance correspsonds to a Producer or Consumer instance in the .NET client), where B is the number of bootstrap.servers brokers and N is the number of brokers in the cluster.
Do note though that if the bootstrap servers are configured to exactly match the advertised hostname of the brokers then the B threads will merged with the N threads, resulting in 1+N threads.

With 346 brokers in the cluster and passing all those 346 brokers as bootstrap.servers (but with a non-matching name, such as the address, an alias, or lacking the domain name or similar), then you'll have 1+(346*2) threads per client instance.
With matching bootstrap servers you'll have 1+346 threads per client instance.


I'm not sure what you mean by "30 Consumer Machines"? Are they separate hardware hosts, separate VMs on the same host,  separate applications on the same host, or client instances in the same application?

Regarding the stacktrace: librdkafka is probably not exposing its internal symbols, so the threads are not in fact in rd_kafka_metadata() but more like in rd_kafka_transport_io_serve() waiting for IO.

---

Finally: we are looking into minimizing the number of required threads for librdkafka.

**Comment by recao** [comment]
Hi @edenhill , thanks for the detailed reply, that explains :)
We have 38 consumer objects running on each separate hardware host, and 38 objects * 346 brokers = 13k threads, which matches our observation. Glad to know we have a plan to minimize it, kindly ask do we have a estimated time for this upgrade?

**Comment by treziac** [comment]
Are your 38 consumers on same process? If yes, did you consider having only one consumer which would register to your needed topics and then dispatch the messages recieved to the corresponding thread?

**Comment by recao** [comment]
Hi @treziac , yes, we have 38 consumers on the same process. We will try to use less consumer objects and test it again. Thanks for the advice!

**Comment by treziac** [comment]
@recao I had some toughts about adding a SerializingConsumer in #132 as there is a SerializingProducer (ie create a bse instance, and use it as a proxy for serializing instances) Due to subscribing & assigment, it's much less straight forward, and it depends of how the consumers are used.

I would happily take any feedbacks on how you use your consumers (ie one topic/consumer or more, many consumers sharing the same topics, use of subscribe or assign, different config, etc)

**Comment by mhowlett** [comment]
one final comment before closing - we won't be implementing a consumer that allows for multiple serializers to be registered since it is not commonly needed, however this functionality could be built on `Consumer<byte[], byte[]>` easily enough for those who need it.
