### ISSUE TITLE
Flush blocks until linger.ms

### ISSUE THREAD

**Issue by HenningRoigaard** [confluentinc/confluent-kafka-dotnet#1670]
Description
===========
I would expect that Producer.Flush immediately produces all buffered messages. However, Flush blocks until linger.ms has passed. This effectively makes Flush unusable, as the producer would produce at that time anyways.

How to reproduce
================
The following has been executed against a local docker hosted Kafka (confluentinc/cp-enterprise-kafka:5.5.1) using Confluent.Kafka 1.5.1 on Windows 10.0.19042 Build 19042

```
var config = new ProducerConfig()
{
  Acks = Acks.All,
  BatchNumMessages = 1000,
  LingerMs = TimeSpan.FromSeconds(20).TotalMilliseconds,
  BootstrapServers = "localhost:9092",
  Debug = "All"
};
var producerBuilder = new ProducerBuilder<string, string>(config);
var producer = producerBuilder.Build();

var sw = Stopwatch.StartNew();
producer.Produce("foo", new Message<string, string>() { Key = "foo" });

Console.WriteLine("************************************* Flushing");
producer.Flush();
Console.WriteLine("************************************* Flushed in ms: " + sw.ElapsedMilliseconds);
```
The log output will show that flush blocks until linger.ms has passed since adding the message (varying linger.ms verifies this)

[Debug log](https://github.com/confluentinc/confluent-kafka-dotnet/files/6944914/FlushDebugLog.txt) attached.
I cannot identify the cause in the log, but there is one observation: Essentially all the time is used in a loop printing

`%7|1628241970.989|TOPPAR|rdkafka#producer-1| [thrd:kafka:9092/1]: kafka:9092/1: foo [0] 1 message(s) in xmit queue (0 added from partition queue)`

**Comment by HenningRoigaard** [comment]
Issue also exist on Confluent.Kafka 1.7.0

**Comment by edenhill** [comment]
> This effectively makes Flush unusable, as the producer would produce at that time anyways.

flush() is mainly used to wait for outstanding messages to be delivered before terminating the producer, it is not aimed to be used in a synchronous produce+flush cycle. See https://github.com/edenhill/librdkafka/wiki/FAQ#why-is-there-no-sync-produce-interface

**Comment by HenningRoigaard** [comment]
The reproduction scenario above was just to showcase the behavior. We don’t use it in the sync style shown. 

My issue with this behavior arises when terminating a service. We use a rather high linger.ms of several minutes to achieve effective batching. This works fine, and the producer flushes itself from time to time in the async manner that is intended. When the service shuts down, we need to ensure that any buffered messages are flushed from the producer.

Naively, I used the `Flush` method to accomplish this. But due to the behavior described here, if any messages are buffered, we may have to wait many minutes. This provides are very bad experience for operations, and worse, the service may be terminated before production by an external coordinator (e.g., Kubernetes) which results in (unneccessary) message loss.

Since `Flush` isn’t suitable for this, is there any other way in which I can support a quick(er) shutdown?

Note that I have seen the guide for creating a [sync producer](https://github.com/edenhill/librdkafka/wiki/Sync-producer), but I would like for the producer to be async except when shutting down.

**Comment by edenhill** [comment]
Okay, I guess that approach makes sense if you have a very low produce rate with large and highly compressible messages.

Can you file a feature request issue on librdkafka to make flush() force a flush despite linger?

**Comment by HenningRoigaard** [comment]
Will do.

**Comment by HenningRoigaard** [comment]
https://github.com/edenhill/librdkafka/issues/3489
