### ISSUE TITLE
Why are producers immediately disposed after use?

### ISSUE THREAD

**Issue by Keerthikan** [confluentinc/confluent-kafka-dotnet#1671]
Description
===========
I am not quite sure I understand why an producer is disposed once it has been created produced the wanted message on to the topic. I cannot seem to find any elaboration on this via the documentation, could someone elaborate on this, why can I not reuse an existing producer - as long I do the proper initTransaction, beginTransaction and commitTransaction, or abortTransaction according to the requirement, I assume that is the lifecycle of an producer, or am I missing something? 
The only way I see to use the same producer is by disposing the old, and recreate it again with the same config, which then will trigger the zombie fencing and bump up the producer epoch, I assume that also have some sort of limit?

How to reproduce
================
```
using Confluent.Kafka;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Collections.Generic;


namespace Confluent.Kafka.Examples.ProducerExample
{
    public class Program
    {
        public IProducer RecreateProducer(IProducer disposableProducer, ProducerConfig config)
        {
            disposableProducer.Flush();
            disposableProducer.Dispose();
            return new ProducerBuilder<string, string>(config).Build();
        }

        public static async Task Main(string[] args)
        {


            string brokerList = "localhost:9092";
            string topicName = "dummy";

            var config = new ProducerConfig { BootstrapServers = brokerList, TransactionalId = "something_1", EnableIdempotence = true, ClientId = "Producer" };
            var producer = new ProducerBuilder<string, string>(config).Build()
            producer.InitTransactions();
            producer.BeginTransaction()
            var deliveryReport = await producer.ProduceAsync(
                            topicName, new Message<string, string> { Key = key, Value = val });
            producer.CommitTransaction()
            
            producer.InitTransactions(); <-- will cause an error producer, I will need to run producer = RecreateProducer(producer, config) , if I want to use the "same producer again" but this will trigger zombie fencing everytime it is recreated
            producer.BeginTransaction()
            var deliveryReport = await producer.ProduceAsync(
                            topicName, new Message<string, string> { Key = key, Value = val });

            }
        }
    }
}
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version - 1.7.0.
 - [ ] Apache Kafka version.
 - [x] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
`InitTransactions` is used to register the producer instance against the `transactional.id` - you should only call it once for a given producer instance.

**Comment by Keerthikan** [comment]
@mhowlett thanks for the clarification, is this somehow documented?
I have not seen this noted anywhere?

**Comment by mhowlett** [comment]
it's documented in general kafka and librdkafka documentation. we haven't documented this explicitly for the .net client, except by way of the example.
