### ISSUE TITLE
One Way SSL with AWS MSK

### ISSUE THREAD

**Issue by vivekkwatra** [confluentinc/confluent-kafka-dotnet#1675]
Description
===========
I want to implement the One Way SSL using AWS MSK to encrypt the in-transit data. I have gone to the given instruction at [https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security] and applied only relevant step : 

1. Create a Certificate Authority (CA) private key / root certificate
2. Configure the client

Below is my configuration setting to enable SSL:
 
producerConfig.SecurityProtocol = SecurityProtocol.Ssl;
producerConfig.SslCaLocation = @"C:\Users\Administrator\ca-root.crt";

But I'm still getting below error while connecting the same. Can you please let me know if I'm missing any steps while configuration.

 [thrd:ssl:/**********.kafka.us-east-1.amazonaws.c]: ssl://**********.kafka.us-east-1.amazonaws.com:9094/bootstrap: SSL handshake failed: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (add broker's CA certificate to the Windows Root certificate store) (after 11ms in state CONNECT)

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version - 1.6.3
 - [X] Apache Kafka version. 2.6.2
 - [X] Client configuration.
 - [X] Operating system - Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
sounds like a question for AWS support to me :-)
