### ISSUE TITLE
Unable to access TimeStamp property of ConsumeResult class on Linux

### ISSUE THREAD

**Issue by anantupadhyay5786** [confluentinc/confluent-kafka-dotnet#1676]
Description
===========
    public class **ConsumeResult**<TKey, TValue>
    { public Timestamp **Timestamp** { get; }
    }
On Linux, whenever we are trying to access **TimeStamp.UtcDateTime** property defined in **ConsumeResult** class then the UTC time returned is default UTC time of 01/01/1970 though we set it explicitly as per our use case from producer.
The same works fine on Windows environment.

Please provide an explanation for same.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
there aren't any known issues here. if you provide a complete minimal example demonstrating the issue (or add to the https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/test/Confluent.Kafka.IntegrationTests/Tests/Timestamps.cs integration test) we can take a look.
