### ISSUE TITLE
Question: Any Way to Get Consumer Group State?

### ISSUE THREAD

**Issue by dogac00** [confluentinc/confluent-kafka-dotnet#1678]
Description
===========
Hello,

My question is, is there any way to get current consumer group's state?

---
Here's all possible states of a consumer group.

State | Description
-- | --
CompletingRebalance | Transitioned to when:initNextGeneration (and there are any members)
Dead | Transitioned to when:GroupCoordinator is requested to handleDeleteGroups (when in Empty state)GroupCoordinator is requested to onGroupUnloadedGroupMetadataManager is requested to cleanupGroupMetadata
Empty | Transitioned to when:initNextGeneration (and there are no members)GroupMetadataManager is requested to cleanupGroupMetadata (when in Empty state with no offsets)GroupMetadataManager is requested to readGroupMessageValue (and there are no members)
PreparingRebalance | Transitioned to when:GroupCoordinator is requested to prepareRebalance
Stable | Transitioned to when:GroupCoordinator is requested to doSyncGroup (when in CompletingRebalance state and the generationId did not change)GroupMetadataManager is requested to readGroupMessageValue (and there is at least one member)

**Comment by mhowlett** [comment]
not via the .net client (yet). you could consider calling out to `kafka-consumer-groups.sh` that comes with kafka, or using REST Proxy (note: this is enabled by default in confluent cloud now IIRC for most clusters). we have prioritized admin capability in REST Proxy as it gives more coverage across languages quicker.

**Comment by dogac00** [comment]
Thanks for the answer @mhowlett 

We need to wait for the consumer group rebalance completion after subscribing to a topic via .NET client.

Currently, after calling `consumer.Subscribe(topic)` we are waiting for `consumer.Assignment` list to populate with a timeout of 3 seconds, there can be idle consumers of course, therefore we tolerate the timeout and not throw any errors.

Is this a safe way to wait for so-called `Stable` state of the current consumer group?

Thanks

**Comment by mhowlett** [comment]
The `SetPartitionsRevokedHandler` and `SetPartitionsAssignedHandler` calls mark the bounds of when your consumer owns a particular collection of partitions. AFAICT from what you say, you should be using those.
