### ISSUE TITLE
Need a strongly named assembly

### ISSUE THREAD

**Issue by zikifer** [confluentinc/confluent-kafka-dotnet#168]
Due to circumstances out of my control, I need all assemblies to be signed (strong-named).  Is there an item on the road map for this?

If you are worried about a signed assembly screwing things up for all the people who do not need such things (and in all fairness they are probably the majority), maybe you could go the same route as the StackExchange.Redis group and supply two assemblies, one signed and one not (StackExchange.Redis.StrongName and StackExchange.Redis, respectively).  Setting up a second project that shares the same source code and simply signs the assembly is pretty straightforward - however, I do not know how this would affect your release procedures.

**Comment by mhowlett** [comment]
Thanks for asking about this @zikifer -

At this point, this is not currently on our radar (it's never come up before).

I'd be happy to review a PR that includes updates the AppVeyor build script to make two versions. Note that due to low level of demand seen, I'd be very keen to ensure that releasing two versions only required minimal ongoing maintenance, otherwise this would displace other things we can be doing with this time.

I encourage anyone else who wants this to chime in here with their input.

**Comment by treziac** [comment]
Did you try .NET Assembly Strong-Name Signer as a workaround?
https://blog.maartenballiauw.be/post/2014/09/10/automatically-strong-name-signing-nuget-packages.html
or this
http://www.geekzilla.co.uk/ViewCE64BEF3-51A6-4F1C-90C9-6A76B015C9FB.htm

Someone asked for this on rdkafka https://github.com/ah-/rdkafka-dotnet/issues/114 and someone did it also in #131 (to register dll in gac)
So this seems not so uncommon (though I think it is when working with legacy projects, so it's more to them to sign it in this case)
I join @mhowlett : this would be ok to add it as a second nuget, but as there seems to be workarounds and uncommon cases it's not this urgent

For reference:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md
https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/

**Comment by zikifer** [comment]
Actually, as a workaround I pulled down the code and built it signed :)  I will put together a formal PR when I get a chance.

I need to send that second link to the guy here that insists all of our assemblies be signed...

**Comment by zikifer** [comment]
For @mhowlett, would you prefer an updated appveyor.yml for the second package or an all-new appveyor file (appveyor_strongname.yml for example)?  Full disclosure I've never used AppVeyor and I'm unsure how to verify any changes.

**Comment by treziac** [comment]
You can register on appveyor with your github accout and link it to your fork, add the confluent-kafka project with default values. Then push changes either to master or your new branch and voila, it should build automatically. No opinions on the config (single file allow a single entry point and easier to maintain, two files make it easier to see if there is an error on signing only)

**Comment by mhowlett** [comment]
closing as this now exists.
