### ISSUE TITLE
Does Confluence Kafka support .NET MVC 5 ?

### ISSUE THREAD

**Issue by jackiesphan1996** [confluentinc/confluent-kafka-dotnet#1682]
Description
===========

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
they're orthogonal, so yes. you'll probably want to inject a producer with DI, and we don't have code for that out of the box. for some guidance on how to do that have a look at this example: https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/Web
