### ISSUE TITLE
[Question] Why is the JsonSerializer not validating against the Schema in the Schema Registry?

### ISSUE THREAD

**Issue by DrorOzgaon** [confluentinc/confluent-kafka-dotnet#1686]
Description
===========
I have a small question regarding the JsonSerializer - it extracts the Schema from the <T> generic as follows:

this.schema = NJsonSchema.JsonSchema.FromType<T>()
https://github.com/confluentinc/confluent-kafka-dotnet/blob/5331f7af6063efcebbc3b830c59ded8f22ceb611/src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs#L100
https://github.com/confluentinc/confluent-kafka-dotnet/blob/5331f7af6063efcebbc3b830c59ded8f22ceb611/src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs#L101

Since we have a Schema Registry configured, shouldn't the JsonSerializer retrieve the Schema from the Schema Registry and perform the validation against it?

Am I missing something? Because if someone modifies the Schema, but doesn't modify the <T> model in his application, the validation will always pass.

How to reproduce
================\

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
this is effectively checked in the `SerializeAsync` method.
