### ISSUE TITLE
Commit multiple TopicPartitionsOffset not commit all

### ISSUE THREAD

**Issue by gilkolin** [confluentinc/confluent-kafka-dotnet#1689]
Description
===========

Hi

I work with commit synchronously (auto commit is false), each message I read I add the TopicPartitionOffset(+1) to list and after several messages I call to Commit(myList<TopicPartitionOffset>).
I noticed it not commit the all items.

I log all the list items:

`2021-09-14 11:58:04,793 INFO KafkaConsumerInter::CommitBulk -> commited the offsets:
	mcapi.avro.provisioning.fs_provisioning_request [[2]] @5,
	mcapi.avro.provisioning.fs_provisioning_request [[2]] @10,
	mcapi.avro.provisioning.fs_provisioning_request [[1]] @24,
	mcapi.avro.provisioning.fs_provisioning_request [[3]] @38,
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @326,
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @664,
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @746,
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @762,
	mcapi.avro.provisioning.fs_provisioning_request [[2]] @11,
	mcapi.avro.provisioning.fs_provisioning_request [[2]] @12,
	mcapi.avro.provisioning.fs_provisioning_request [[1]] @25,
	mcapi.avro.provisioning.fs_provisioning_request [[1]] @26,
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @763,
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @764,
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @765,
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @766,
	mcapi.avro.provisioning.fs_provisioning_request [[3]] @39,
	mcapi.avro.provisioning.fs_provisioning_request [[3]] @40`

and after this called to Commited():
`2021-09-14 11:58:04,809 DEBUG KafkaConsumerInter::CommitBulk -> Commited:
	mcapi.avro.provisioning.fs_provisioning_request [[0]] @765,
	mcapi.avro.provisioning.fs_provisioning_request [[1]] @24,
	mcapi.avro.provisioning.fs_provisioning_request [[2]] @11,
	mcapi.avro.provisioning.fs_provisioning_request [[3]] @38`

How to reproduce
================

configure autoCommit=false and create list of TopicPartitionsOffset(+1) to each recieve message.
call to Commit with list as argument

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by gilkolin** [comment]
maybe the list not commited by order, I will try to send List with count==numOfPartitions and send just the most laterest message offset. will update

**Comment by gilkolin** [comment]
I thought maybe need to commit just the most laterest offset for each partition... no. so, back to the original comment.

thanks

**Comment by edenhill** [comment]
You seem to have duplicate topic-partitions in your commit list, that won't work well.

**Comment by gilkolin** [comment]
so, if I want to commit all the tpo:

mcapi.avro.provisioning.fs_provisioning_request [[2]] @5, mcapi.avro.provisioning.fs_provisioning_request [[2]] @10, mcapi.avro.provisioning.fs_provisioning_request [[1]] @24, mcapi.avro.provisioning.fs_provisioning_request [[3]] @38, mcapi.avro.provisioning.fs_provisioning_request [[0]] @326, mcapi.avro.provisioning.fs_provisioning_request [[0]] @664, mcapi.avro.provisioning.fs_provisioning_request [[0]] @746, mcapi.avro.provisioning.fs_provisioning_request [[0]] @762, mcapi.avro.provisioning.fs_provisioning_request [[2]] @11, mcapi.avro.provisioning.fs_provisioning_request [[2]] @12, mcapi.avro.provisioning.fs_provisioning_request [[1]] @25, mcapi.avro.provisioning.fs_provisioning_request [[1]] @26, mcapi.avro.provisioning.fs_provisioning_request [[0]] @763, mcapi.avro.provisioning.fs_provisioning_request [[0]] @764, mcapi.avro.provisioning.fs_provisioning_request [[0]] @765, mcapi.avro.provisioning.fs_provisioning_request [[0]] @766, mcapi.avro.provisioning.fs_provisioning_request [[3]] @39, mcapi.avro.provisioning.fs_provisioning_request [[3]] @40

should I commit the next list:
    mcapi.avro.provisioning.fs_provisioning_request [[0]] @326
    mcapi.avro.provisioning.fs_provisioning_request [[1]] @24
    mcapi.avro.provisioning.fs_provisioning_request [[2]] @5,
    mcapi.avro.provisioning.fs_provisioning_request [[3]] @38, 

and after this list:
    mcapi.avro.provisioning.fs_provisioning_request [[0]] @664
    mcapi.avro.provisioning.fs_provisioning_request [[1]] @25
    mcapi.avro.provisioning.fs_provisioning_request [[2]] @10
    mcapi.avro.provisioning.fs_provisioning_request [[3]] @39
    
until I done all my tpo?

**Comment by mhowlett** [comment]
the latest offset committed will override any previous offset committed for a partition.

you can commit as you suggest, or just not bother with the first set.
