### ISSUE TITLE
After Rebalancing Consumers Offset go back

### ISSUE THREAD

**Issue by ErenArslan** [confluentinc/confluent-kafka-dotnet#1691]
Description
===========
When we scale consumers up  Rebalancing started. And 1 partition suddenly has 60k lag. And It has data from 3 day ago. There was not any lag until rebalancing.

We write a Wrapper DI library with confluent kafka in company. We consume and process as batch. Normally in production our RPM was 30k and 80 ms Response Time with 20 pod. But now RPM is 4M with 20 pod instance.  It works perfectly. But This issue happened twice in month. Normally There is no any lag.
If consumer could not commit, the lag would increase and we would see this. It happened after rebalancing.

BatchSize: 200
Concurrency: 25
Partition 60
Our Config:  
```
var consumerConfig = new ConsumerConfig
            {
                BootstrapServers = servers,
                GroupId = groupId,
                EnableAutoCommit = true,
                EnableAutoOffsetStore = false,
                AutoOffsetReset = AutoOffsetReset.Latest
            };

```

```
 public static IReadOnlyCollection<ConsumeResult<TKey, TValue>> ConsumeBatch<TKey, TValue>(this IConsumer<TKey, TValue> consumer,CancellationToken cancellationToken,  int maxBatchSize)
            {
                var message = consumer.Consume(cancellationToken);

                if (message?.Message is null)
                    return Array.Empty<ConsumeResult<TKey, TValue>>();

                var messageBatch = new List<ConsumeResult<TKey, TValue>> { message };

                while (messageBatch.Count < maxBatchSize)
                {
                    message = consumer.Consume(TimeSpan.Zero);
                    if (message?.Message is null)
                        break;

                    messageBatch.Add(message);
                }

                return messageBatch;
            }
```

```
while (!token.IsCancellationRequested)
                {
                    try
                    {
                        var results = _consumer.ConsumeBatch(token,_kafkaConfiguration.BatchSize);
                        var taskList = results.Select(message => Process(message, provider, logger, token)).ToList();

                        var totalPages = (int)Math.Ceiling((decimal)taskList.Count / (decimal)_kafkaConfiguration.Concurrency);
                        
                        for (var i = 0; i < totalPages; i++)
                        {
                            await Task.WhenAll(taskList
                                .Skip(i * _kafkaConfiguration.Concurrency)
                                .Take(_kafkaConfiguration.Concurrency));
                        }
                        
                        _consumer.StoreOffset(results.Last());
                    }
                    catch (Exception e)
                    {
                        logger.LogError($"[ERROR]  Consumer error  . Topic : {_kafkaConfiguration.Topics.FirstOrDefault()} Error: {e}");
                    }

```

Checklist
=========

Please provide the following information:
 - [1.7.0 ] Confluent.Kafka nuget version.

**Comment by oguzhaneren** [comment]
may be related with AutoCommitIntervalMs. when you store offset using StoreOffset function, kafka clients commits periodically using AutoCommitIntervalMs. 

you can override SetPartitionsRevokedHandler callback method, in this method you can use Commit function to commit last offset immediately

**Comment by ErenArslan** [comment]
But this is the problem actually. if consumer could not commit, the lag would increase and we would see this. Committing is okey I think. After Rebalancing AutoOffsetReset acting like earliest . And This is not happing always. Randomly 
There is another issue like this. We update version to 1.8.0. We hope that fixed 
#1672

**Comment by mhowlett** [comment]
this seems like #1672 - closing in favor of that. we're currently investigating it.
