### ISSUE TITLE
Calling IConsumer.Subscription in a LogHandler causes consumer thread to become blocked indefinitely when the Kafka server is restarted.  

### ISSUE THREAD

**Issue by Saraphite** [confluentinc/confluent-kafka-dotnet#1692]
Description
===========
When accessing IConsumer.Subscription in a LogHandler, repeated calls (as a result of a broker/server becoming unreachable) causes the consumer thread to become blocked indefinitely.

This was observed on Confluent.Kafka 1.5.2, 1.8.0 and 1.8.1.

Consumer is running on Windows 10.

We would occasionally receive the following log messages (but not all the time):
`Consumer group session timed out (in join-state steady) after 30215 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group`

`172.21.0.3:9092/bootstrap: Connect to ipv4#172.21.0.3:9092 failed: Unknown error (after 21502ms in state CONNECT)`

How to reproduce
================
This was reproduced with a topic that had a 'heartbeat' tick published to it every second. The consumer subscribed to this topic.
This was reproduced with the Kafka consumer running as part of an ASP.NET Core Background Service.

1. Build a Kafka consumer and set a log handler (with SetLogHandler).
2. In that method try and access the IConsumer.Subscription property.
3. Make the Kafka broker/server becomes unreachable.
4. Observe that a large number of logs going through the LogHandler causes the thread to become blocked on IConsumer.Subscription. 
5. Make the Kafka broker/server reachable.
6. Observe that it doesn't reconnect due to aforementioned thread blocking.

```
using System;
using System.Threading;
using System.Threading.Tasks;
using Confluent.Kafka;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace KafkaTest
{
    class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(builder =>
                {
                    builder.ClearProviders();
                    builder.SetMinimumLevel(LogLevel.Information);
                })
                .ConfigureServices(ConfigureServices)
                .UseWindowsService();

        public static void ConfigureServices(HostBuilderContext context, IServiceCollection services)
        {
            var consumerConfig = new ConsumerConfig
            {
                GroupId = "KafkaTest",
                BootstrapServers = "kafka:9092",
                EnableAutoCommit = true,
                EnableAutoOffsetStore = false,
                AutoOffsetReset = AutoOffsetReset.Latest,
                SocketKeepaliveEnable = true
            };

            services.AddSingleton(new ConsumerBuilder<Ignore, string>(consumerConfig).SetLogHandler(HandleLog).Build());
            services.AddHostedService<ConsumerBackgroundService>();
        }

        private static void HandleLog(IConsumer<Ignore, string> consumer, LogMessage logMessage)
        {
            try
            {
                var subscriptions = consumer.Subscription;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }
    }

    public class ConsumerBackgroundService : BackgroundService
    {
        private readonly IConsumer<Ignore, string> _consumer;
        private const string Topic = "HEARTBEAT_TICKER";

        public ConsumerBackgroundService(IConsumer<Ignore, string> consumer)
        {
            _consumer = consumer;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            Console.WriteLine($"Subscribing to {Topic}...");
            _consumer.Subscribe(Topic);
            Console.WriteLine($"Subscribed to {Topic}.");

            var cts = new CancellationTokenSource();
            while (!stoppingToken.IsCancellationRequested)
            {
                try
                {
                    var cr = _consumer.Consume(cts.Token);
                    Console.WriteLine($"Message: {cr.Message.Value}");
                }
                catch (ConsumeException ce)
                {
                    Console.WriteLine($"Consume Exception: {ce.Message}");
                }
                catch (Exception e)
                {
                    Console.WriteLine($"General Exception: {e.Message}");
                }
            }

        }
    }
}
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [] Apache Kafka version. _(I do not have access to this)._
 - [x] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [] Provide broker log excerpts. _(I do not have access to these)._
 - [x] Critical issue.

**Comment by mhowlett** [comment]
from the SetLogHandler docstring:

```
        ///     Warning: Log handlers are called spontaneously from internal
        ///     librdkafka threads and the application must not call any
        ///     Confluent.Kafka APIs from within a log handler or perform any
        ///     prolonged operations.
```
