### ISSUE TITLE
Create GenericRecord with only Specific fields name with corresponding values from the base schema

### ISSUE THREAD

**Issue by Amit3421** [confluentinc/confluent-kafka-dotnet#1699]
I have a GenericRecord with the following base schema and message value: 

schema = @"{
			  ""name"": ""ModelForecastPrices"",
              ""namespace"": ""ABC.Kafka.Entities"",
              ""type"": ""record""
              ""fields"": [
                {
                  ""name"": ""model_run_uid"",
                  ""type"": ""int""
                },
                {
                  ""name"": ""metadata"",
                  ""type"": {
                    ""type"": ""map"",
                    ""values"": ""string""
                  }
                },
                {
                  ""name"": ""model_name"",
                  ""type"": ""string""
                },
                {
                  ""name"": ""event_trigger"",
                  ""type"": ""string""
                },
                {
                  ""logicalType"": ""timestamp-millis"",
                  ""name"": ""version_datetime"",
                  ""type"": ""double""
                },
                {
                  ""name"": ""publication_status"",
                  ""type"": ""string""
                },
                {
                  ""name"": ""scenario_name"",
                  ""type"": ""string""
                },
                {
                  ""name"": ""series_items"",
                  ""type"": {
                    ""items"": {
                      ""fields"": [
                        {
                          ""logicalType"": ""timestamp-millis"",
                          ""name"": ""applies_from"",
                          ""type"": ""double""
                        },
                        {
                          ""name"": ""output_1_forecast_series_code"",
                          ""type"": ""string""
                        },
                        {
                          ""name"": ""output_1_forecast_short_name"",
                          ""type"": ""string""
                        },
                        {
                          ""name"": ""output_1_forecast_long_name"",
                          ""type"": ""string""
                        },
                        {
                          ""name"": ""output_1_forecast_unadjusted_forecast"",
                          ""type"": ""float""
                        },
						{
                          ""default"": null,
                          ""name"": ""input_1_forecast_price"",
                          ""type"": [
                            ""float"",
                            ""null""
                          ]
                        }
                      ],
                      ""name"": ""series_item"",
                      ""type"": ""record""
                    },
                    ""type"": ""array""
                  }
                }
              ]
            }";

messageValue = @"{
  ""model_run_uid"": 3295,
  ""metadata"": {
    ""event_type"": ""Published"",
    ""partition_key"": ""5e28b7af-aebf-4886-a443-513631eb951f"",
    ""correlation_id"": ""388e6100-6dc1-47b6-a84a-b8ca141f6af9"",
    ""id"": ""5b4f2f3f-2549-4817-a69a-4e8149bba76b"",
    ""source"": ""ADP"",
    ""type"": ""Kafka.Entities.ModelForecastPrices"",
    ""event_time"": ""1627304499261""
  },
  ""model_name"": ""mod_price_europe_mediterranean_gas_oil_spot_v1"",
  ""event_trigger"": ""model_run"",
  ""version_datetime"": 1627304497.958459,
  ""publication_status"": ""Draft"",
  ""scenario_name"": ""base"",
  ""series_items"": [
    {
      ""applies_from"": 1625097600.000,
      ""output_1_forecast_series_code"": ""5e28b7af-aebf-4886-a443-513631eb951f"",
      ""output_1_forecast_short_name"": ""europe mediterranean"",
      ""output_1_forecast_long_name"": ""europe mediterranean forecast usd cif spot mt"",
      ""output_1_forecast_unadjusted_forecast"": 618.8817,
      ""input_1_forecast_price"": {
        ""float"": 624.6046
      }
    },
    {
      ""applies_from"": 1627776000,
      ""output_1_forecast_series_code"": ""5e28b7af-aebf-4886-a443-513631eb951f"",
      ""output_1_forecast_short_name"": ""europe mediterranean"",
      ""output_1_forecast_long_name"": ""europe mediterranean forecast usd cif spot mt"",
      ""output_1_forecast_unadjusted_forecast"": 604.1177,
	  ""input_1_forecast_price"": {
        ""float"": 620.0999
      }
    },
    {
      ""applies_from"": 1630454400.0002,
      ""output_1_forecast_series_code"": ""5e28b7af-aebf-4886-a443-513631eb951f"",
      ""output_1_forecast_short_name"": ""europe mediterranean"",
      ""output_1_forecast_long_name"": ""europe mediterranean forecast usd cif spot mt"",
      ""output_1_forecast_unadjusted_forecast"": 599.31305,
	   ""input_1_forecast_price"": {
        ""float"": 611.2931
      }
    }
    }
  ]
}";

I have a requirement where I need to create a new GenericRecord that contains only the specific fields and corresponding message values from the above specified base schema and message values. The specified fields name that I need to extract from the base schema will be in a config file.

For Example: I need only below fields and corresponding message values should be a part of new schema and message value in new GenericRecord. 

model_run_uid,
publication_status,
scenario_name,
series_items

newSchema = @"{
              ""name"": ""ModelForecastPrices"",
              ""namespace"": ""ABC.Kafka.Entities"",
              ""type"": ""record""
              ""fields"": [
                {
                  ""name"": ""model_run_uid"",
                  ""type"": ""int""
                },
                {
                  ""name"": ""publication_status"",
                  ""type"": ""string""
                },
                {
                  ""name"": ""scenario_name"",
                  ""type"": ""string""
                },
                {
                  ""name"": ""series_items"",
                  ""type"": {
                    ""items"": {
                      ""fields"": [
                        {
                          ""logicalType"": ""timestamp-millis"",
                          ""name"": ""applies_from"",
                          ""type"": ""double""
                        },
                        {
                          ""name"": ""output_1_forecast_series_code"",
                          ""type"": ""string""
                        },
                        {
                          ""name"": ""output_1_forecast_short_name"",
                          ""type"": ""string""
                        },
                        {
                          ""name"": ""output_1_forecast_long_name"",
                          ""type"": ""string""
                        },
                        {
                          ""name"": ""output_1_forecast_unadjusted_forecast"",
                          ""type"": ""float""
                        },
						{
                          ""default"": null,
                          ""name"": ""input_1_forecast_price"",
                          ""type"": [
                            ""float"",
                            ""null""
                          ]
                        }
                      ],
                      ""name"": ""series_item"",
                      ""type"": ""record""
                    },
                    ""type"": ""array""
                  }
                }
              ]
            }";

newMessageValue = @"{
  ""model_run_uid"": 3295,
  ""publication_status"": ""Draft"",
  ""scenario_name"": ""base"",
  ""series_items"": [
    {
      ""applies_from"": 1625097600.000,
      ""output_1_forecast_series_code"": ""5e28b7af-aebf-4886-a443-513631eb951f"",
      ""output_1_forecast_short_name"": ""europe mediterranean"",
      ""output_1_forecast_long_name"": ""europe mediterranean forecast usd cif spot mt"",
      ""output_1_forecast_unadjusted_forecast"": 618.8817,
      ""input_1_forecast_price"": {
        ""float"": 624.6046
      }
    },
    {
      ""applies_from"": 1627776000,
      ""output_1_forecast_series_code"": ""5e28b7af-aebf-4886-a443-513631eb951f"",
      ""output_1_forecast_short_name"": ""europe mediterranean"",
      ""output_1_forecast_long_name"": ""europe mediterranean forecast usd cif spot mt"",
      ""output_1_forecast_unadjusted_forecast"": 604.1177,
	  ""input_1_forecast_price"": {
        ""float"": 620.0999
      }
    },
    {
      ""applies_from"": 1630454400.0002,
      ""output_1_forecast_series_code"": ""5e28b7af-aebf-4886-a443-513631eb951f"",
      ""output_1_forecast_short_name"": ""europe mediterranean"",
      ""output_1_forecast_long_name"": ""europe mediterranean forecast usd cif spot mt"",
      ""output_1_forecast_unadjusted_forecast"": 599.31305,
	   ""input_1_forecast_price"": {
        ""float"": 611.2931
      }
    }
  ]
}";

I am using the Apache.Avro (1.9.1) and Confluent.SchemaRegistry (1.7.0) on windows 10 machine.

Is there any way I can do this?

**Comment by mhowlett** [comment]
Just going through triaging issues. Apologies, I don't have enough bandwidth to look into this - it relates to the Apache Avro dependency.
