### ISSUE TITLE
Support for Kafka offsets in addition to Zookeeper offsets

### ISSUE THREAD

**Issue by drinkbird** [confluentinc/confluent-kafka-dotnet#170]
Hi there. I couldn't find something in documentation, and I was wondering if the client supports Kafka offsets in addition to Zookeeper offsets.

Ideally I would like to enable double commitment​s to both types until all the topics are migrated, then completely switch to kafka offsets.

Thank you in advance for your time

**Comment by edenhill** [comment]
This client does not support ZK based offsets and it is highly unlikely that it ever will, since it is a deprecated legacy feature.

You could implement it yourself using a zookeeper library though.

**Comment by drinkbird** [comment]
Thanks for the quick reply. That's good news, I thought I had a different problem.

I'm using the advanced consumer and I commit on every message. The problem is that after a topic has been consumed for some time using this client, people connecting with a different client (using the same consumer group) receive an error indicating that offsets are not available at group coordinator.

The confluent client works as expected, and the other consumer also works fine for other topics we haven't consumed using confluent.

Any ideas or suggestions would be highly appreciated

**Comment by treziac** [comment]
If you consume messages at high rate, commiting after every message is killer-perf, you should rather commit every x messages / t secondes. If you need exactly once, you will need to make this a transactional way through other mechanism, you will get at least once with this

But the error looks more like a broker configuration issue, did you check your logs on broker and topic configuration?

**Comment by drinkbird** [comment]
Thanks for the tips treziac. I don't have direct access to the broker/topic configuration but I think you are right, that's where the problem should be.
