### ISSUE TITLE
How to manul to close kafka connection for Producer

### ISSUE THREAD

**Issue by KallerLong1** [confluentinc/confluent-kafka-dotnet#1702]
Description
===========
We want to manul to close the connection for producer.

Now our code: 
  var config = new ProducerConfig() { BootstrapServers = kafkaOptions.Value.KafkaBootstrapServers };
                using (var p = new ProducerBuilder<Null, string>(config).Build())
                {
                    p.Produce(topic, new Message<Null, string> { Value = message });
                    p.Flush();
                    return true;
                }

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
the producer instance manages broker connections - you can't manually close a connection without disposing the producer instance (which you are doing).
