### ISSUE TITLE
Support for Apple M1 silicon

### ISSUE THREAD

**Issue by andrebires** [confluentinc/confluent-kafka-dotnet#1707]
Description
===========

The library doesn't support the Apple M1 silicon (ARM64).

The .NET version is 6.0.100-rc.2.21505.57 which [already supports this architecture](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-6/#x64-emulation-update).

The exception call stack is:
```csharp
System.DllNotFoundException: Failed to load the librdkafka native library.
   at Confluent.Kafka.Impl.Librdkafka.TrySetDelegates(List`1 nativeMethodCandidateTypes)
   at Confluent.Kafka.Impl.Librdkafka.LoadOSXDelegates(String userSpecifiedPath)
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
   at Confluent.Kafka.ProducerBuilder`2.Build()
```

Maybe related to https://github.com/edenhill/librdkafka/issues/3546

How to reproduce
================

1. Create a .NET 6 RC project and install the Confluent.Kafka package (1.8.2) in a Mac with M1 silicon
2. Create a producer instance via ProducerBuilder
3. Run the solution

Checklist
=========

Please provide the following information:
 - [x] Confluent.Kafka nuget version: 1.8.2
 - [x] Operating system.
![image](https://user-images.githubusercontent.com/1099597/137987493-14664d41-d179-4497-b88f-a934463a9002.png)

**Comment by andrebires** [comment]
Hmmm, building the librdkafka from the source and referencing it via `Library.Load` seems to do the trick:

```
git clone https://github.com/edenhill/librdkafka.git
cd librdkafka
./configure --install-deps
brew install  openssl zstd pkg-config
./configure
make
sudo make install
```

```csharp
Library.Load("/usr/local/lib/librdkafka.dylib");
```

So there is something work in the brew distribution of librdkafka. But anyway, it would be nice if the Nuget package included the correct runtime version.

**Comment by robertmircea** [comment]
@andrebires did you find a workaround for the above error? I've made all the steps you described using the latest HEAD revision and I received the same error as you when trying to publish a message. Consume works well so far.

**Comment by andrebires** [comment]
> @andrebires did you find a workaround for the above error? I've made all the steps you described using the latest HEAD revision and I received the same error as you when trying to publish a message. Consume works well so far.

No, unfortunately I didn't. I just gave up using Kafka with .NET and started using with Go, which is working.

**Comment by vinhhrv** [comment]
same error with Macbook Air M1, dotnet 6.0

**Comment by kazim3k** [comment]
@mhowlett Are you planning to look into this issue in the near future?

**Comment by mhowlett** [comment]
@edenhill - any plans on this for `librdkafka.redist`?

I think what we ideally want is a way for you to add a candidate librdkafka binary to the set included in librdkafka.redist simply by referencing an additional nuget package. Then we, or anyone, could make and distribute librdkafka nuget packages for any platform. I think this might not have been feasible in the past, but it might be worth looking into this again.

**Comment by rusuly** [comment]
As a workaround, this library works when installing Rosetta 2 and x64 version of .NET 6

**Comment by Kikimora** [comment]
This is my workaround to have both ARM and x64 Sdks side by side
1. Install .NET x64
2. Add this to .csproj file
```
<RuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('OSX'))">osx-x64</RuntimeIdentifier>
```

In other words for projects that use Kafka I force x64 SDK on OSX.

**Comment by Minorsonek** [comment]
Any ETA for arm/M1 build? It's already half of Q1, is it going to happen or is it delayed?

**Comment by justinbarias** [comment]
> This is my workaround to have both ARM and x64 Sdks side by side
> 
> 1. Install .NET x64
> 2. Add this to .csproj file
> 
> ```
> <RuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('OSX'))">osx-x64</RuntimeIdentifier>
> ```
> 
> In other words for projects that use Kafka I force x64 SDK on OSX.

This worked for me too.

To be clear - i think this just "tricks" Confluent.Kafka to use the same librdkafka x64 binaries. It doesn't actually run the .NET6 in emulation mode

**Comment by mhowlett** [comment]
also relevant: https://github.com/confluentinc/confluent-kafka-dotnet/issues/1769

**Comment by andrebires** [comment]
> > This is my workaround to have both ARM and x64 Sdks side by side
> > 
> > 1. Install .NET x64
> > 2. Add this to .csproj file
> > 
> > ```
> > <RuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('OSX'))">osx-x64</RuntimeIdentifier>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In other words for projects that use Kafka I force x64 SDK on OSX.
> 
> This worked for me too.
> 
> To be clear - i think this just "tricks" Confluent.Kafka to use the same librdkafka x64 binaries. It doesn't actually run the .NET6 in emulation mode

Yeah, this seems to be used only by Nuget for restoring the dependencies of the project:

 > RID values are used to identify target platforms where the application runs. They're used by .NET packages to represent platform-specific assets in NuGet packages.

https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

**Comment by niemyjski** [comment]
@mhowlett any updates for this? I'm currently blocked on this.

**Comment by mhowlett** [comment]
this is in 1.9.0-RC10
