### ISSUE TITLE
Azure Function Kafka Trigger

### ISSUE THREAD

**Issue by tech7857** [confluentinc/confluent-kafka-dotnet#1709]
Hi 

We have an Azure function with Kafka trigger running in Azure cloud. We are seeing some frequent failure occurring. Will it possible to guide us why these will be occurring and what can be done or troubleshoot these. We did check our broker and finding no errors logged there.

Kafka Trigger : https://github.com/Azure/azure-functions-kafka-extension
Broker : Confluent Kafka 5.5.1

Errors reported 

Libkafka: [thrd:GroupCoordinator]: GroupCoordinator: xxx:9092: 1 request(s) timed out: disconnect (after 585436ms in state UP)
Libkafka: [thrd:xxxx:9092/bootstrap]: xxxx:9092/bootstrap: Connect to ipv4#172.18.18.163:9092 failed: Unknown error (after 21034ms in state CONNECT)
Libkafka: [thrd:xxxx:9092/2]: xxxxx:9092/2: Failed to resolve 'xxxxx:9092': No such host is known. (after 2768ms in state CONNECT)

Please let us know if any other information is required.

Thanks

**Comment by mhowlett** [comment]
> [thrd:xxxx:9092/2]: xxxxx:9092/2: Failed to resolve 'xxxxx:9092': No such host is known. (after 2768ms in state CONNECT)

looks like it can't resolve the bootstrap server - seems like an issue outside the client.
