### ISSUE TITLE
Loads of `Receive failed: Disconnected` errors

### ISSUE THREAD

**Issue by javierholguera** [confluentinc/confluent-kafka-dotnet#171]
Hi,

We have a recent setup of Kafka and some microservices. Some of them use Java official clients, but one of them is built in C# and uses this library.

We see many of the following errors, constantly (more than 1000 in the last 24 hours). This is from a testing environment, not production. In this environment, the load is fairly low. However, there seems to not be a relation between the volume of events and how often these errors are logged.
```
Kafka | 2017-05-09 15:00:21.810 | AvroProducer<String,ProductSelected>#producer-2 | Error | Local | Error Local_Transport - ssl://broker02.edited-kafka-url:9092/bootstrap: Receive failed: Disconnected
```
We have errors for consumers as well. Settings are defaults for both clients and brokers.

Other issues I've read mentioned that it may be related to Kafka brokers releasing idle connections. However, we're seen these errors even when there is activity.

**Comment by treziac** [comment]
Is the activity on all brokers? The idle connection are on each broker.
1000 in 24 hours means 1/2 every minutes, how many brokers/clients do you have?
You will find more information here : https://github.com/edenhill/librdkafka/issues/437

**Comment by javierholguera** [comment]
@treziac we have 3 brokers and we're getting disconnections from all of them I think. Regarding clients, the logs come from one microservice. This microservice has 3 consumers and 2 producers. It's displaying errors for all of them as well. [See this](https://pastebin.com/uzCFwEWq) for an extended version of those logs.

About that librdkafka issue, if we were seeing these errors in idle producers every 5 or more minutes, I would be sure that's the problem. However, as you can see in the extended log, they happen more often, despite the brokers using the default reaper delay. Plus they happen while there is activity (new event coming every 10 secs). So I'm not sure this is the problem in this case.

What can I provide in terms of logs, configuration that could help?

**Comment by treziac** [comment]
Strange. Are you using the latest release? (Confluent.Kafka 0.9.5 with the correct librdkafka.redist 0.9.5) What is your broker version and environment (do your microservices run on nano or linux, and which distrib in this case ?)
You can launch the client with group and topic logs (set "debug" config to "cgrp,topic")
Also please provide your client config and any relevant logs on your broker side.

I don't use ssl myself so not sure if it might come from this - do you have any non ssl broker endpoint where you could connect to test if you replicate?

This would be a librdkafka issue so you may want to open an issue on https://github.com/edenhill/librdkafka instead

**Comment by javierholguera** [comment]
[These other errors are happening](https://pastebin.com/9A48xQW1), although less often. An example of one of them

```
Kafka | 2017-05-09 16:29:26.547 | AvroConsumer<String,InstitutionalQuotaChanged>#consumer-4 | Error | Local | Error Local_MsgTimedOut - ssl://10.16.9.16:9092/1002: 1 request(s) timed out: disconnect (average rtt 100.777ms)
```

**Comment by javierholguera** [comment]
@treziac yeah, I think it makes sense to move this to [https://github.com/edenhill/librdkafka](https://github.com/edenhill/librdkafka).

I'll open an issue there, copy the information from here as context and close this one.

**Comment by treziac** [comment]
MsgTimedOut is an other much more problematic problem: your message aren't processed to te broker. You may have a network issue
Could also paste the code in your microservice (how you instantiate / produce message)?

**Comment by javierholguera** [comment]
Closing here, continues in https://github.com/edenhill/librdkafka/issues/1206

**Comment by javierholguera** [comment]
@treziac we wrap the `Producer<TKey, TValue>` in our own producer.

This is its instantiation inside our class:
```c#
this.innerProducer = new Producer<TKey, TValue>(config.ToDictionary(), keySerde, valueSerde);
```

Then these are the methods that we use to produce and produce async.

```c#
        public Task<PublishResult> Produce(TValue message, TKey key)
        {
            if (message == null)
                throw new ArgumentNullException(nameof(message));

            // ContinueWith by default will have the same behaviour than
            // ConfigureAwait(false), regarding synchronization contexts.
            // Until this bug is fixed (https://github.com/confluentinc/confluent-kafka-dotnet/issues/92),
            // we cannot do async/await against ProduceAsync

            return this.innerProducer
                .ProduceAsync(this.topic, key, message)
                .ContinueWith(t => ToPublishResult(t.Result));
        }
        public PublishResult ProduceSync(TValue message, TKey key)
        {
            // Produce synchronously would reduce throughput but would provide extra durability.
            return Produce(message, key).Result;
        }
```

Our microservice is producing synchronously to one topic, and asynchronously to another.

**Comment by treziac** [comment]
You are using the same producer instance for both synchronous and asynchronous?

maxInFlightRequestsPerConnection = 1 seems wrong. Did you try the default value or do you have precise needs? I'm not sure how this will behave if you mix your synchronous and asynchronous call

**Comment by javierholguera** [comment]
No, they are separate producers.

Max flight is on purpose, to guarantee order even if producer retries. I don't know how it would be related to the SSL disconnects, though

**Comment by javierholguera** [comment]
@treziac we've changed the consumer configuration to not define maxInFlightRequestsPerConnection = 1. The disconnections are still happening, despite the regular heartbeats.

I'm going to close the issue here, since this is very likely to be something either in our Kafka infra or librdkafka. Will continue in this [librdkafka issue](https://github.com/edenhill/librdkafka/issues/1206).

Thanks for your help.
