### ISSUE TITLE
Consumer consumes same messages again and again

### ISSUE THREAD

**Issue by Tony-Hop** [confluentinc/confluent-kafka-dotnet#1711]
Description
===========
Hello,
I have a problem with one of my consumers. 
It consumes all the messages as expected but a bit later it starts to consume all messages again and again. 

This consumer can take up to 2 min to consume a message

the config :

EnableAutoOffsetStore = true,
EnableAutoCommit = false,
AutoOffsetReset = AutoOffsetReset.Earliest,
PartitionAssignmentStrategy = PartitionAssignmentStrategy.CooperativeSticky

the code : 

          using (var consumer = new ConsumerBuilder<Tkey, TValue>(_config)
                .SetValueDeserializer(new ProtobufDeserializer<TValue>().AsSyncOverAsync())
                .SetErrorHandler((_, e) => _log.Error(new System.Exception(e.Reason), "Error"))
                .Build())
            {
                consumer.Subscribe(topicName);

                try
                {

                    while (!cancellationToken.IsCancellationRequested)
                    {
                        try
                        {
                            var consumeResult = consumer.Consume(cancellationToken);

                           consumer.Commit(consumeResult );

                        }
                        catch (ConsumeException e)
                        {
                            _log.Error(e, $"Consume error: {e}");
                        }
                    }

                }
                catch (OperationCanceledException)
                {
                    _log.Info($"Consumer got canceled!");
                }
                finally
                {
                    _log.Info($"Closing consumer.");
                    consumer.Close();
                }

            }

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.  (1.7.0)
 - [x] Apache Kafka version. (2.8.1)
 - [x] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by Tony-Hop** [comment]
it seems  I have this problem because I use the same consumer group to consume 2 different topics with same kind of messages

**Comment by mhowlett** [comment]
> same consumer group to consume 2 different topics

you don't state if you have different consumers subscribing to different topics, but if you do, it is not recommended to use  the same consumer group were you don't have to to get auto-scaling capability.
