### ISSUE TITLE
Notify consumer when new event is published to kafka topics

### ISSUE THREAD

**Issue by PoojaSingh15** [confluentinc/confluent-kafka-dotnet#1713]
Description
===========
Is there a way to notify consumer about the new events being published to kafka topics which consumer has subscribed to while consumer is not actively listening? I know the question itself seems confusing but i was thinking if it is really necessary to have one process running continuously in order to consume messages. I think it will make consumer process easier if we know when the message is available to read. 
Any help is appreciated.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
no. worth noting that the kafka protocol is really designed for very high throughput processing, and this kind of feature isn't in line with that use case.
