### ISSUE TITLE
Question Kafka multiple tenancy consumer

### ISSUE THREAD

**Issue by juniorschen** [confluentinc/confluent-kafka-dotnet#1717]
Description
===========
Hi, we are really enjoying your work and we are starting to develop a system based on kafka. A question that came up is how to deal with the creation of consumers per tenant. We would like to create a consumer per tenant, looking at your example the way you do this is creating a background service for a consumer, we would like to know what kind of problems we would have when scheduling the creation of multiple background services for each of our tenants. Another possibility would be to work only with a background service and create multiple tasks for each consumer, but we don't really know the impacts that can be caused in our application. Is there any good practice/example for our situation? Thanks for any help, we are very excited to work on this.

Model 1:
![image](https://user-images.githubusercontent.com/46031261/143038335-273c2706-5061-46e6-b7a2-2eccba16f393.png)
Will we have some kind of blocking of messages from a certain customer because another one fires a large number of messages?
Will we have any kind of problem due to large allocation of threads?

Model 2:
![image](https://user-images.githubusercontent.com/46031261/143038369-1a80f40f-2686-4644-9105-1edfc81ee94f.png)
Have some kind of problem with so many instances of background services?

How to reproduce
================
Checklist
=========
Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
An answer to this will require more depth/consideration than I can give here, and i'm also not quite sure I understand the question.

As a general comment, the consumer uses a lot of resources, and you should generally aim to have an architecture that utilizes them well (you seem do be doing that).
