### ISSUE TITLE
Adding default properties do AvroDeserializerConfig

### ISSUE THREAD

**Issue by rlanhellas** [confluentinc/confluent-kafka-dotnet#1724]
Hi Guys, any roadmap to add default properties inside [AvroDeserializerConfig](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Avro/AvroDeserializerConfig.cs) class like [AvroSerializerConfig](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializerConfig.cs) class ?

**Comment by mhowlett** [comment]
which property specifically were you after?

**Comment by mhowlett** [comment]
going through triaging issues. feel free to open a new issue with more specific info.
