### ISSUE TITLE
Kafka Consumer freezes on Broker reboot

### ISSUE THREAD

**Issue by manik3pg** [confluentinc/confluent-kafka-dotnet#1726]
Description

On performing a broker reboot we sometimes observe that consumer freezes and a new consumer has to be created for consuming the data again.

How do we know that the consumer has frozen?
We set a timeout of 30 sec while calling Consume method and once we this issue is produced the consumer no longer times out in case no message is received. If we call any other method on the consumer instance like Unassign or Unsubscribe the thread gets stuck on the call and we do not receive any response from consumer.

How to reproduce
Start consuming any topic and restart broker multiple time. This reproduces the case in our case

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file. - Attaching the consumer code snipet. - [ConsumerCode.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/7580803/ConsumerCode.txt)
 - [ ] Confluent.Kafka nuget version. -  **1.8.1**
 - [ ] Apache Kafka version. - 2.8.0
 - [ ] Client configuration. - 
                 EnableAutoCommit = false,
                StatisticsIntervalMs = 0,
                EnablePartitionEof = true,
                AutoOffsetReset = AutoOffsetReset.Latest,
                EnableAutoOffsetStore = false,
                SocketKeepaliveEnable = true,
                TopicMetadataRefreshIntervalMs = 30000,
                SessionTimeoutMs = 180000,
 - [ ] Operating system - Both Windows and linux
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration). - There are no logs which specify anything
 - [ ] Provide broker log excerpts. - No logs avaliable
 - [ ] Critical issue. - Yes

**Comment by mhowlett** [comment]
thanks for reporting.

**Comment by damianhw** [comment]
This can be very painful access confluent cloud.
Any ETA on a potential fix?

**Comment by mhowlett** [comment]
closing - please reopen if this is still an issue in v1.9.3
