### ISSUE TITLE
Client Auth Configuration refresh support

### ISSUE THREAD

**Issue by Vikash08Mishra** [confluentinc/confluent-kafka-dotnet#1728]
Description
===========
When configuring a producer or consumer client, we generally update configuration details and use ProducerBuilder.Build() or ConsumerBuilder.Build() to create respective producer or consumer. Now in today's world most of the application would create a producer or consumer during application startup and register in dependency injection container of the choice.
Now, if auth credentials(e.g. sasl) changes, even though application can Programmatically fetch updated secret details but cannot update credentials for producers or consumers as there is no option or handler available to update an existing producer or consumer configuration.
So, only option remains application restart. Please let me know if there is any alternative ?

How to reproduce
================
- Create a Producer with auth configured.
- Register it via any DI container (I used .Net core default DI)
- update the Kafka Sasl credentials.
- We would start getting Sasl auth error as app is still using old credentials.
- Even if App can programmatically fetch updated credentials after receiving error, there is no way to update producer config, only way would be to restart and create new producer instances with updated config.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version - All versions, validated with 1.7.0 and 1.8.2
 - [ ] Apache Kafka version. - NA
 - [ ] Client configuration. - 
 new ProducerConfig
            {
                BootstrapServers = "bootstrapServers",
                Acks = Acks.Leader,
                Partitioner = Partitioner.Random,
                LingerMs = 10,
                MessageSendMaxRetries = 3,
                MessageTimeoutMs = 5000,
                //sasl config
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslMechanism = SaslMechanism.ScramSha256,
                SaslUsername = "user",
                SaslPassword = "password",
            };
 - [ ] Operating system.- Windows, though doesn't matter
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).- NA
 - [ ] Provide broker log excerpts. - NA
 - [ ] Critical issue. - Feature request

**Comment by edenhill** [comment]
oauthbearer supports updated credentials (through SetToken()).

**Comment by Vikash08Mishra** [comment]
@edenhill Not sure if OAuthBearerSetToken extension would apply to update credentials update. For e.g. if you look at ProducerConfig I posted above, let's say SASL password changes, unsure how would that sasl configuration credentials can be updated for existing producer.
```
new ProducerConfig
{
BootstrapServers = "bootstrapServers",
Acks = Acks.Leader,
Partitioner = Partitioner.Random,
LingerMs = 10,
MessageSendMaxRetries = 3,
MessageTimeoutMs = 5000,
//sasl config
SecurityProtocol = SecurityProtocol.SaslSsl,
SaslMechanism = SaslMechanism.ScramSha256,
SaslUsername = "user",
SaslPassword = "password",
};
```
Also extension looks at mandatory token parameter which would not be applicable for above configuration.
Please let me know if I am missing something

**Comment by edenhill** [comment]
Right, SetToken() only works for OAUTHBEARER, not SCRAM. Just thought I'd mention it.

**Comment by mhowlett** [comment]
you could wrap the confluent producer or consumer in a custom class that manages their lifetime & allows security credentials to be specified, and if so, destroys the client instance and recreates it. you'll need to make a helper class to wrap the clients anyway for DI.
