### ISSUE TITLE
Json representation for AvroDecimal

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1735]
Description
===========

I know there is a dedicated repo for Avro but can't post an issue there so maybe here I can find some tip.

I need to serialize Avro generated classes with avrogen to Json, but the AvroDecimal logical type dont serialize the values, it is empty.

Also, when I define a decimal logical type in Avro schema with some Scale value, I can't set a value with a lower Scale.

I would like to define AvroDecimal with the maximum Scale possible value and later be able to use a smaller scale. Is that possible ??

**Comment by mhowlett** [comment]
I'd need to investigate. Would love to help, but time constrained so closing as it relates to the Avro project.
