### ISSUE TITLE
AvroGen tool problem generating C# classes for complex avsc files

### ISSUE THREAD

**Issue by meghanay-gain** [confluentinc/confluent-kafka-dotnet#1737]
Description
===========
On executing avrogen command to generate C# class file from a complex avsc, It results into an error for the complex type.
Eg- 
"avrogen -s /schema/com/google/type/DateTime.avsc ." results into below error
Exception occurred. Undefined name: com.google.protobuf.Duration at 'fields[7].type[1]'
since com.google.protobuf.Duration is another avsc file.

How to reproduce
================
This can be reproduced on any complex avsc that has another avsc reference.

Checklist
=========

avrogen.dll version: 1.7.7.4
Confluent.Apache.Avro.dll version: 1.7.7.4
Operating system: Mac OS
Critical issue

**Comment by dineshtripathi** [comment]
following

**Comment by mhowlett** [comment]
I believe avro/avrogen doesn't support referencing types in different files. In the java case, there is a maven plugin that achieves this with string substitution, but i believe there is no off the shelf solution for doing that in .NET.

Note also that the Confluent fork of Avro have been deprecated - we merged all our changes/fixes up into the Apache project.
