### ISSUE TITLE
Controlling the LogLevel

### ISSUE THREAD

**Issue by d1820** [confluentinc/confluent-kafka-dotnet#1738]
I can not seem to find anywhere the list of sinks used for logging in Kafka. So far in my appsettings. I have tried the following

```
"Confluent.Kafka": "Warning"
"Kafka": "Warning"
"org.apache.kafka": "Warning",
"org.apache.zookeeper": "Warning",
"Microsoft": "Warning",
"System": "Warning",
"System.Diagnostics": "Warning"
```

All of these still display the Information messages. How can I turn the Information log level off for the Kafka SDk?

**Comment by mhowlett** [comment]
set log and error handlers that don't do anything using `SetLogHandler` and `SetErrorHandler` on the builder class.
