### ISSUE TITLE
I need DeleteGroups interface

### ISSUE THREAD

**Issue by GY101** [confluentinc/confluent-kafka-dotnet#1744]
Description
===========
I need delete unused Group

**Comment by OneCricketeer** [comment]
Kafka deleted groups without offset commits on its own.

**Comment by GY101** [comment]
> 

offset is commits  ,but unused .
how delete?

**Comment by GY101** [comment]
> Kafka deletes groups without offset commits on its own.


offset is commits  ,but unused .
how delete?

**Comment by OneCricketeer** [comment]
Just wait for `offsets.retention.minutes` (broker config) to pass

https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#brokerconfigs_offsets.retention.minutes

**Comment by GY101** [comment]
@OneCricketeer thanks

**Comment by GY101** [comment]
@OneCricketeer 
How to Delete it Immediately？

**Comment by OneCricketeer** [comment]
Not with C# https://stackoverflow.com/q/38402364

**Comment by mhowlett** [comment]
you could call out to the cli command.

or you could use REST proxy (which is exposed on Confluent Cloud).

unfortunately we don't have full coverage of the admin commands prioritized in the near term.

**Comment by chenjing1294** [comment]
I also need the implementation of AdminClient.deleteConsumerGroups method in .NET

**Comment by mhowlett** [comment]
this is in 1.9.2-RC2
