### ISSUE TITLE
KSQLDB: JOINs on multiple conditions are not yet supported

### ISSUE THREAD

**Issue by NCAndreea** [confluentinc/confluent-kafka-dotnet#1745]
Description
===========
Hi,

I have following scenario in which I need to join multiple tables to store the result in another Kafka topic.
Unfortunately looks like KSQLDB does not support join condition to be formed on multiple columns.
Moreover if I remove the join that caused this error I get another error because the tables primary keys are different.
Please can you advise what option/solution do I have?
Thank you for your help.

Regards,

How to reproduce
================

CREATE TABLE TEST1 (ID VARCHAR PRIMARY KEY, Country_ID VARCHAR, Code1 VARCHAR) 
    WITH (kafka_topic='test1', value_format='JSON', partitions=3);

INSERT INTO TEST1 (ID, Country_ID, Code1) VALUES ('1','1','A');

CREATE TABLE TEST2 (Country_ID VARCHAR PRIMARY KEY, Country_Name VARCHAR) 
    WITH (kafka_topic='test2', value_format='JSON', partitions=3);

INSERT INTO TEST2 (Country_ID, Country_Name) VALUES ('1','Spain');

CREATE TABLE TEST3 (Country_ID VARCHAR PRIMARY KEY, Code1 VARCHAR PRIMARY KEY, Code_description VARCHAR) 
    WITH (kafka_topic='test3', value_format='JSON', key_format='JSON', partitions=3);

INSERT INTO TEST3 (Country_ID, Code1, Code_description) VALUES ('1','A', 'ABC');

select 
TEST1.ID,
TEST2.Country_Name,
TEST3.Code_description
from TEST1 left join TEST2 on TEST1.Country_ID=TEST2.Country_ID
left join TEST3 on TEST1.Country_ID=TEST3.Country_ID and TEST1.Code1=TEST3.Code1
emit changes limit 5;

![image](https://user-images.githubusercontent.com/96262788/148412469-8111c5f4-6116-42e2-80dc-5569473fef76.png)

**Comment by OneCricketeer** [comment]
This is the C# client. 

KSQL issues should be reported at https://github.com/confluentinc/ksql/issues

**Comment by NCAndreea** [comment]
I have recreated it there. Please feel free to close this one. Thank you.
