### ISSUE TITLE
Error from nuget 'Invalid librdkafka version 10201ff, expected at least 10502ff' with Ubuntu

### ISSUE THREAD

**Issue by jasonxu08** [confluentinc/confluent-kafka-dotnet#1749]
Description
===========
I created a .NET 5 project on Ubuntu and added a package reference of Confluent.Kafka with version 1.8.2. When I started to run it, there was an error (going below).

_Exception has occurred: CLR/System.IO.FileLoadException
An unhandled exception of type 'System.IO.FileLoadException' occurred in Confluent.Kafka.dll: 'Invalid librdkafka version 10201ff, expected at least 10502ff'
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
   at Confluent.Kafka.ProducerBuilder`2.Build()
   at testKafka.A.Produce(String topic, ClientConfig config) in /home/jason/Documents/code/testcode/testKafka/Program.cs:line 37
   at testKafka.A.test() in /home/jason/Documents/code/testcode/testKafka/Program.cs:line 33
   at testKafka.Program.Main(String[] args) in /home/jason/Documents/code/testcode/testKafka/Program.cs:line 11_

It looks like the version of librdkafka that Confluent takes is lower than expected for Ubuntu. 

How to reproduce
================
Run the code attached.
[testKafka.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/7887263/testKafka.zip)

Checklist
=========

Please provide the following information:
 - [attached] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.8.2 ] Confluent.Kafka nuget version.
 - [/] Apache Kafka version.
 - [/] Client configuration.
 - [Ubuntu 20.04.3LTS 64-bit] Operating system.
 - [/ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [/ ] Provide broker log excerpts.
 - [Y ] Critical issue.

**Comment by edenhill** [comment]
Sounds like you have a system-installed (apt-get) librdkafka version v1.2.1 that is being loaded by Confluent.Kafka instead of the bundled v1.8.2 librdkafka.
The reason for this could be that the bundled libraries are incompatible with your system, which shouldn't be the case for Ubuntu 20.04 x64.
But it would be greated if you could verify this by finding librdkafka.redist installation path (somewhere in the nuget package installation directory), and there locate the following files:
```
runtimes/linux-x64/native/librdkafka.so
runtimes/linux-x64/native/centos6-librdkafka.so
runtimes/linux-x64/native/alpine-librdkafka.so
runtimes/linux-x64/native/centos7-librdkafka.so
```

and run `ldd <file>` for each one, providing us with the output.

E.g.:
```bash
for f in ...some..path/native/*.so ; do echo $f: ; ldd $f ; done

runtimes/linux-x64/native/alpine-librdkafka.so:
        linux-vdso.so.1 (0x00007ffc771ed000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fcde4f4b000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fcde4c75000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fcde4c59000)
        libc.musl-x86_64.so.1 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcde4c36000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcde4a44000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcde4a3c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fcde52a9000)
runtimes/linux-x64/native/centos6-librdkafka.so:
        linux-vdso.so.1 (0x00007ffd029f5000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f29bc1b8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f29bc1b2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f29bc18f000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f29bc184000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f29bbf92000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f29bcac9000)
runtimes/linux-x64/native/centos7-librdkafka.so:
        linux-vdso.so.1 (0x00007fffc3fb9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f937a1f1000)
        libsasl2.so.3 => not found
        libssl.so.10 => not found
        libcrypto.so.10 => not found
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f937a1d5000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f937a1cf000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f937a1aa000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f937a19f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9379fad000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f937a816000)
runtimes/linux-x64/native/librdkafka.so:
        linux-vdso.so.1 (0x00007fffa252f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f901cf5d000)
        libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f901cf40000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f901ccd8000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f901c895000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f901c879000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f901c873000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f901c84e000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f901c843000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f901c651000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f901d598000)

```

**Comment by jasonxu08** [comment]
I did install librdkafka-dev a couple of days ago. I'll remove that and try again. Thanks for the answer.

**Comment by edenhill** [comment]
So removing librdkafka-dev solved the issue?
