### ISSUE TITLE
When a deserializer throws an exception, expose via OnConsumeError

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#175]
Exceptions are not used very much in the consumer API, so i'm thinking it would be a more consistent (and more convenient) if any exception thrown by a deserializer was surfaced via the `OnConsumeError` event.

It would be best if there was a new `ErrorCode` value for this. It would be good if librdkafka explicitly set aside a block of values reserved for custom use.

also, when a serializer throws an exception, producer probably should handle.

**Comment by treziac** [comment]
Agreed on this

**Comment by mhowlett** [comment]
closing - PR #179 addresses this.
