### ISSUE TITLE
Getting error: unknown topic/partition in consumer after upgradation to 1.8.2

### ISSUE THREAD

**Issue by ManaseePatra** [confluentinc/confluent-kafka-dotnet#1750]
Description
===========
Hi,

Getting Error "Unknown topic or partition" after upgrading to 1.82 from consumer when subscribing nonexistent topics - confluent-kafka. It was working fine with 1.4.4 version. currently due to some vulnerability of zlib.dll library we are upgrading confluent.kafka 1.8.2 which will resolve  this vulnerability issue. But after upgradation we are continuously getting the unknown topic exception. 

I have also tried to add the following config in my consumer config 'allow.auto.create.topics': True And I am sure the broker is enabled to auto create topics with auto.create.topics.enable = true(verified as well). but still no luck.

Please help this needful. Appreciate your earliest response. 

How to reproduce
================
it is reproduceable after upgradation in consumer side while subscribing some non-existent topics.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version. ----1.8.2
 - [ ] Apache Kafka version.  -----2.8.0
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
Do the reported topics exist on the cluster, or are you relying on auto-create in the consumer for it to be created?

In the latter case, we recommend having the producers create the topics (or create them manually). The consumers will discover the topics within topic.metadata.refresh.interval.ms when they are created.

**Comment by ManaseePatra** [comment]
> Do the reported topics exist on the cluster, or are you relying on auto-create in the consumer for it to be created?

Thank you.
we are relying on auto-create in the consumer for it to be created as of now with earlier version. what will be the best practice to create the topics.

As per one of your blog, current version will not trigger the topic creation in consumer side. Any suggestion to handle this exception in consumer side?
This topic.metadata.refresh.interval.ms property value, we are not using explicitly and in docs it's showing 30000ms by default. But my case i am continuously getting this error. what will be appropriate value for this property?

**Comment by edenhill** [comment]
Right, the consumer will only create topics (if allow.auto...=true) for topic it references directly through assign().
Subscribed topics will not be auto-created.

The recommended workaround is to explicitly create your topic through the AdminAPI CreateTopics(). This also allows you to specify the replication-factor and partition count.

**Comment by ManaseePatra** [comment]
> 
> In the latter case, we recommend having the producers create the topics (or create them manually). The consumers will discover the topics within topic.metadata.refresh.interval.ms when they are created.

If I am following this, ideally it should be create the topics whenever some request coming to producers. I have observed in some requests topics are not creating due to this it's failing.
