### ISSUE TITLE
Confluent vs Cloudera?

### ISSUE THREAD

**Issue by lugospod** [confluentinc/confluent-kafka-dotnet#1753]
Package https://www.nuget.org/packages/Cloudera.Kafka/1.8.2 is referencing this project.

And this project states that FIVE packages are built and non of them is Cloudera.Kafka
- Confluent.Kafka [net45, netstandard1.3, netstandard2.0]
- Confluent.SchemaRegistry.Serdes.Avro [netstandard2.0]
- Confluent.SchemaRegistry.Serdes.Protobuf [netstandard2.0]
- Confluent.SchemaRegistry.Serdes.Json [netstandard2.0]
- Confluent.SchemaRegistry [netstandard1.4, netstandard2.0]

Can someone explain relationship between nugets created by this project and package https://www.nuget.org/packages/Cloudera.Kafka/1.8.2?

thank you!

**Comment by bartelink** [comment]
https://en.wikipedia.org/wiki/Cloudera is a different company. The nuget links to this repo but there is no Cloudera.Kafka repo on https://github.com/cloudera - I'd decompile the package to figure out what it is, but I'd be asking Cloudera, not Confluent.

This seems an entrypoint to the Cloudera docs https://docs.cloudera.com/runtime/7.2.10/kafka-developing-applications/topics/kafka-develop-dotnet.html

**Comment by lugospod** [comment]
@bartelink thank you for a quick response. Yes, I saw this entry point but it doesn't state anything regarding the source code of the nuget package.

I sent an email to the "owner" of the Nuget package, but currently there is no response so that is why I asked here just to check if I was missing something because I use Confluent.Kafka library for another project and I don't remember ever Cloudera being mentioned in the code.

**Comment by bartelink** [comment]
From basic googling, it seems Cloudera offer a competing packaged offering of Apache Kafka. There may well be good reasons to go down that road, but in terms of a known quantity, obviously `Confluent.Kafka` is where one would start.
