### ISSUE TITLE
[Question] Consumer, Non-destructive flush of final stored offsets when EnableAutoOffsetStore = false and EnableAutoCommit = true

### ISSUE THREAD

**Issue by ycherkes** [confluentinc/confluent-kafka-dotnet#1758]
I'm trying to use the recommended asynchronous commit approach [documentation](https://docs.confluent.io/clients-confluent-kafka-dotnet/current/overview.html#:~:text=var%20config%20%3D%20new%20ConsumerConfig%0A%7B%0A%20%20%20%20...%0A%20%20%20%20EnableAutoCommit%20%3D%20true%20//%20(the%20default)%0A%20%20%20%20EnableAutoOffsetStore%20%3D%20false%0A%7D%0A%0A...%0A%0Awhile%20(!cancelled)%0A%7B%0A%20%20%20%20var%20consumeResult%20%3D%20consumer.Consume(cancellationToken)%3B%0A%0A%20%20%20%20//%20process%20message%20here.%0A%0A%20%20%20%20consumer.StoreOffset(consumeResult)%3B%0A%7D), but I ran into the problem that the only way to forcibly commit all the final stored offsets is with Consumer.Close().

But this is a destructive call, is there a way to do this without destroying the consumer?

I've tried to call the consumer.Commit(), sometimes it raises an exception (no stored offsets), sometimes it runs with no errors, but it doesn't cause consumer.OffsetsCommitted event.

**Comment by mhowlett** [comment]
the no stored offsets exception will be harmless, but it shouldn't be exposed. `Commit` should work. what version are you using?

**Comment by ycherkes** [comment]
Hi @mhowlett, I'm using the following version: Confluent.Kafka 1.8.2.
As far as I understand, this question is closer to librdkafka.redist project, because they don't provide the FlushStoredOffsets method.
I wouldn't use the Commit method, because this method doesn't fire OffsetsCommitted event.

**Comment by mhowlett** [comment]
What is your use case for `FlushStoredOffsets`?
The API can't do what you want, and it would be probably better if it could - I'm not sure what the priority is though, given I don't know when you would use this.

**Comment by mhowlett** [comment]
i'm closing this as below the threshold for something we'll likely act on, but feel free to continue the conversation.
