### ISSUE TITLE
Best way to handle ArgumentNullException if key is null

### ISSUE THREAD

**Issue by maxplanck76er** [confluentinc/confluent-kafka-dotnet#176]
Hello,

I'm using this kind of code :
```
Message<string, string> msg;
consumer.Consume(out msg);

```
The second line throws an ArgumentNullException because of the null message key.
What is the best way to handle messages which are part of the same topic, but can have a key or not ?
You can notice that I am using the consume method directly, but only because I need manual commits.

Thanks.

**Comment by mhowlett** [comment]
At this point either write a new string serializer that doesn't throw an exception and use that (this is not hard), or catch and ignore the exception. #175 will also provide a solution. Also, consider a different message format where key is always null or not null (which is usually what you want).

note: manual commits also work with the `poll` method which is preferred.

**Comment by maxplanck76er** [comment]
Thank you @mhowlett ! 

I also notice that 0.9.5 version of the library fix this problem.

**Comment by treziac** [comment]
Yes, String(De)seralizer was changed in 0.9.5 to accept null, but it was more for the value than for key. Note that it's not the case of the other serializers provied on the repo (throw on null)
