### ISSUE TITLE
"Local: Value deserialization error" .NET

### ISSUE THREAD

**Issue by alejandrohn** [confluentinc/confluent-kafka-dotnet#1761]
Description
===========
Hello,

two ways

Consumer

this is with

```
 using(var c = new ConsumerBuilder<Null, EventoKafkaJson>(conf)
                .SetValueDeserializer(new JsonDeserializer<EventoKafkaJson>().AsSyncOverAsync())
                .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
                .Build())
```

+	**Unexpected character encountered while parsing value: . Path '', line 0, position 0.**

Consumer

this is with:

```
(var c =   new ConsumerBuilder<string, EventoKafkaJson>(conf)
                                   .SetValueDeserializer(new Confluent.SchemaRegistry.Serdes.AvroDeserializer<EventoKafkaJson>(schemaRegistry).AsSyncOverAsync())
                                   .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
                                   .Build())
```

"Local: Value deserialization error"

+		**InnerException	{"AvroDeserializer only accepts type parameters of int, bool, double, string, float, long, byte[], instances of ISpecificRecord and subclasses of SpecificFixed."}	System.Exception {System.InvalidOperationException}**

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.8.2 ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
What serializer are you using to write the values? you need to use the serializer corresponding to the deserializer you are using. Note that the Schema Registry enabled serializer adds some framing information before the serialized data, which the deserializer expects.

**Comment by gscms-piyush** [comment]
Please check object cast some where value not change proper value type for example Date : 01/01/0001 occur issue, or you pass int value instead of string value, can cause this issue
