### ISSUE TITLE
Consumer high CPU utilization while waiting for new messages

### ISSUE THREAD

**Issue by SergeSavel** [confluentinc/confluent-kafka-dotnet#1762]
I have a .NET WebAPI application which acts like a REST-wrapper around Kafka Consumer. Clients can create, assign, delete consumers and consume messages via REST interface.
The issue is that the application consumes a lot of CPU resources just waiting for new data. On my computer with 8 cores one consumer instance takes about 17% CPU. The same behaviour reproduces on all machines there the application runs.

The application creates a consumer, manually assigns partitions, and then executes "Consumer.Consume(timeout)" on each client request with timeout of 15 seconds. And while executing "Consumer.Consume(timeout)" CPU utilisation rises up to 100% in case of multiple active consumer instances even if there are no new incoming messages.

The strange thing is that this behaviour doesn't reproduce on "example" scenarios. I wrote simple console app that just creates a consumer with the same config, assign partitions and wait for new messages in loop - it works fine and doesn't take any CPU resources. The only difference that I can see is that in my web app consumers are created and accessed in different threads, but access is strictly sequential.

Could you please provide me with possible reasons of this behaviour?

Confluent.Kafka 1.8.2 (tried 1.7.0)
Apache Kafka 3.1.0 (tried 2.8.1)
Client configuration:
    bootstrap.servers: localhost:9092
    security.protocol: PLAINTEXT
    group.id: kafkatest3@silent
    auto.offset.reset: earliest
    enable.partition.eof: false
Operating system: Windows 10

Debug logs (consumer,cgrp,topic,fetch) while executing "Consumer.Consume(timeout)":
```
%7|1645037196.207|FETCH|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: Fetch topic test5 [2] at offset 0 (v3)
%7|1645037196.207|FETCH|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: Fetch topic test5 [1] at offset 0 (v3)
%7|1645037196.207|FETCH|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: Fetch topic test5 [0] at offset 0 (v3)
%7|1645037196.207|FETCH|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: Fetch 3/3/3 toppar(s)
%7|1645037196.707|FETCH|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: Fetch topic test5 [1] at offset 0 (v3)
%7|1645037196.707|FETCH|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: Fetch topic test5 [0] at offset 0 (v3)
%7|1645037196.707|FETCH|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: Fetch topic test5 [2] at offset 0 (v3)
%7|1645037196.707|FETCH|rdkafka#consumer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: Fetch 3/3/3 toppar(s)
... (other strings are the same)
```

**Comment by SergeSavel** [comment]
It seems to me, I found the culprit.
The problem is only happens than DependentAdminClient is initialized.
The code below demonstrates high CPU usage. On my computer this app consumes ~17% CPU.
Is it a normal behaviour, or a bug?

```
using Confluent.Kafka;  

var exiting = false;
 Console.CancelKeyPress += delegate
 { 
    exiting = true; 
    Console.WriteLine("Exiting..."); 
};

  const string servers = "localhost:9092"; 
const string topic = "test5";  

var config = new ConsumerConfig 
{ 
    BootstrapServers = servers, 
    GroupId = "csharp-consumer",
     EnableAutoCommit = false,
     EnablePartitionEof = false 
}; 

using var consumer = new ConsumerBuilder<string, string>(config).Build(); 
using var adminClient = new DependentAdminClientBuilder(consumer.Handle).Build();  

var assignment = adminClient.GetMetadata(topic, TimeSpan.FromSeconds(10)) 
    .Topics.SelectMany(topicMetadata => topicMetadata.Partitions) 
    .Select(partitionMetadata => new TopicPartitionOffset(topic, partitionMetadata.PartitionId, 0)); consumer.Assign(assignment);  

Console.WriteLine("Start consuming."); 
while (!exiting) 
{ 
    var consumeResult = consumer.Consume(TimeSpan.FromSeconds(15)); 
}  
Console.WriteLine("Finish consuming.");

```

**Comment by mhowlett** [comment]
Interesting, that's not good, labeling bug. Have you tried setting the `CancellationDelayMaxMs` config parameter to something higher? Does that help?
