### ISSUE TITLE
CachedSchemaRegistryClient.cs does not support passwords that include ':' character

### ISSUE THREAD

**Issue by villanisaac-kr** [confluentinc/confluent-kafka-dotnet#1767]
Description
===========

When adding Basic Auth Info to the schema registry object it does not support passwords that contain ':' due to checking for split size != 2

 <PackageReference Include="Confluent.Kafka" Version="1.8.2" />
 <PackageReference Include="Confluent.SchemaRegistry" Version="1.8.2" />
 <PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="1.8.2" />

Including link as reference 
https://github.com/confluentinc/confluent-kafka-dotnet/blob/de0fe579c0b5f830f6cfe36b5a48d5fe0d7caf5e/examples/AvroSpecific/Program.cs
           

How to reproduce
================

Modify previous sample to include BasicAuthUserInfo

```
 var schemaRegistryConfig = new SchemaRegistryConfig
            {
                // Note: you can specify more than one schema registry url using the
                // schema.registry.url property for redundancy (comma separated list). 
                // The property name is not plural to follow the convention set by
                // the Java implementation.
                Url = "https://myregistry:8443/dev",
                BasicAuthUserInfo = "myUser:3d:Xz+|4cKw$HJL*T"
            };
```
#### Logs

```
Unhandled exception. System.ArgumentException: Configuration property schema.registry.basic.auth.user.info must be of the form 'username:password'.
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient..ctor(IEnumerable`1 config)
   at HelloWorld.Program.Main(String[] args) in /Users/JG28943/Workspaces/test/cs/Program.cs:line 122
```
Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
right. correct behavior would be to assume everything after the first colon is the password.
