### ISSUE TITLE
Akka vs MassTransit vs Kafka

### ISSUE THREAD

**Issue by eaba** [confluentinc/confluent-kafka-dotnet#177]
This is just a question bugging my mind. I want to understand how those three can play together.
What role would Kafka if we decided to use the three together?
Thanks

**Comment by mhowlett** [comment]
we'll consider writing up an article on this if we get more questions about it.

**Comment by eaba** [comment]
Hello @mhowlett this might not be the most appropriate option seeing that not lots of developers might have anything to do with theses libs. Why don't u make a poll and let developers vote? This way other developers can come to be aware of these other libs and learn more about them. This is just my suggestion

**Comment by eaba** [comment]
The book: Big Data SMACK: A Guide to Apache Spark, Mesos, Akka, Cassandra, and Kafka
gave me some idea
