### ISSUE TITLE
cannot run schema registry with ssl enabled: network password is not correct

### ISSUE THREAD

**Issue by ruifrvaz** [confluentinc/confluent-kafka-dotnet#1772]
Description
===========
hi
I am facing an issue when setting my keystore.p12 in SchemaRegistryConfig.SslKeystoreLocation . I get an error saying the network password is not correct when running on a windows server 2016. This happens even when the password is blank. Strangely it works on my local with same keystore and truststore. Locally i am running windows 10
Has anyone encountered a similar problem or know the cause?

How to reproduce
================
run a kafka producer on Windows server 2016 with ssl

                var schemaRegistry = new SchemaRegistryConfig
                {
                    Url = schemaRegistryUrls,
                    SslKeystoreLocation = $"yourp12keystore",
                    SslKeystorePassword = "",
                    SslCaLocation = $"yourtruststore"
                };
               _cachedSchemaRegistryClient = new CachedSchemaRegistryClient(schemaRegistry);

=========

Please provide the following information:
Application:
Framework > netcoreapp3.1
Confluent.SchemaRegistry, Version=1.7.0.0
Confluent.Kafka Version="1.7.0"

Hosting server:
Windows server 2016

Keystore created using keytool in jks format and then converted to p12
Key is rsa

----------------

error:

Exception: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The specified network password is not correct.
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.SetSslConfig(IEnumerable`1 config)

**Comment by mhowlett** [comment]
i'd need to spend time investigating this, outside my immediate expertise.
happy to look into if this if it's identified as a bug.

**Comment by ruifrvaz** [comment]
> i'd need to spend time investigating this, outside my immediate expertise. happy to look into if this if it's identified as a bug.

Hi mhowlett,
After digging a bit more into it i have excluded confluence as being the culprit. the issue seems related to the keyvault itself or how it is being read by the server. I don't suppose this issue is relevant to this repository although would be nice if anyone experiencing the same problem could share their findings

**Comment by carlosmpcorreia** [comment]
Hi @ruifrvaz 
I have the exact same issue and I'm still struggling with it.
Did you find the solution?

Obrigado!

**Comment by mohamedfady** [comment]
Stuck with the same, any other solution rather than upgrade the server to be windows server 2019?
It is all regarding the encryption protocol of AES256SHA256 which is not supported by windows 2016 build number <19xx
