### ISSUE TITLE
consumer.Position method always return -1001

### ISSUE THREAD

**Issue by zsy406** [confluentinc/confluent-kafka-dotnet#1776]
Description
===========
When I tried to get the current offset rather than the committed offset, this method seems doesn't work, it always return -1001.
_consumer.Position(new TopicPartition("myTopic",0));
{Unset [-1001]}
    IsSpecial: true
    Value: -1001

is there any way to calculate the lag? I just want to use` _consumer.QueryWatermarkOffsets(partition, timeout)` to get the end offset, and get the current offset with `_consumer.Position(new TopicPartition("myTopic",0))`  doesn't work, it always return -1001.

How to reproduce
================

 ```
using (IAdminClient adminClient = new AdminClientBuilder(new AdminClientConfig()
            {
                BootstrapServers = brokerList
            }).Build())
            {
                Metadata metadata = adminClient.GetMetadata(topic, TimeSpan.FromSeconds(30));
                _topicMetadata = metadata.Topics.FirstOrDefault();

               if (_topicMetadata.Partitions != null)
                {
                    var partitions = _topicMetadata.Partitions
                            .Select(p => new TopicPartition(topic, p.PartitionId));
                    using (var _consumer = new ConsumerBuilder<string, string>(ConstructConfig(brokerList))
                       .Build()){
                      foreach( var partition in partitions)
                      {
                                var currentOffset = _consumer.Position(partition); //this is always -1001.
 WatermarkOffsets offsets = _consumer.QueryWatermarkOffsets(topicOffset.TopicPartition, TimeSpan.FromSeconds(5));
                            var realOffset = _consumer.Position(topicOffset.TopicPartition);
                                var lag = offsets.High.Value - currentOffset.Value;  

                   }
             }

```
Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
position gives the current position (locally) when the consumer is actively reading from a partition.
you should be able to use `Committed` to get committed offsets for all partitions in the group the consumer is configured for.
-1001 the a constant value librdkafka uses to signify "unknown/invalid/not specified"
