### ISSUE TITLE
Remove support for .NET 4.5/4.6 please

### ISSUE THREAD

**Issue by bjornbouetsmith** [confluentinc/confluent-kafka-dotnet#1779]
Description
===========
.NET 4.5 targeting pack no longer exists in any easy form, which makes it borderline impossible to build the solution using visual studio 2022 unless you go through loops.

.NET 4.5 is almost 10 years old and surely nobody is building applications that target that runtime anymore.  Support ended in 2016.
.NET 4.6 stops being supported in april 2022, so its definetely also dead - so here you need to move to .NET 4.6.2 which will have support until the OS it runs on no longer has support.

[Lifecycle](https://docs.microsoft.com/en-US/lifecycle/faq/dotnet-framework)

How to reproduce
================
* Install only VS 2022
* Clone this repository
* Build

~~~
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	Confluent.Kafka	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1217	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for .NETFramework,Version=v4.6 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	Confluent.Kafka	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1217	
~~~

To quote [microsoft](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers):
~~~
Starting with Visual Studio 2022, Visual Studio no longer includes .NET Framework components for .NET Framework 4.0 - 4.5.1 because these versions are no longer supported. Visual Studio 2022 and later versions can't build apps that target .NET Framework 4.0 through .NET Framework 4.5.1. To continue building these apps, you can use Visual Studio 2019 or an earlier version.
~~~

As an alternative to removing support entirely you could also create a new csproj that only builds .NET 4.5/4.6 and those running VS 2022 could simply unload these projects. The disadvantage to this is that any build errors would not be caught inside visual studio.
So my preferred solution would be to remove support for .NET 4.5/4.6 and simply move onto .NET 4.8 or if you want to reach the most people 4.7.2

**Comment by mhowlett** [comment]
we can replace `net45;net46` with `net462` as they are eol or eol in a month, but we care about not breaking compatibility for anyone using a runtime that is not eol.

i think what we want, as you suggest, a separate project that CI uses to build the nuget packages.

**Comment by bjornbouetsmith** [comment]
> i think what we want, as you suggest, a separate project that CI uses to build the nuget packages.
I am not 100% what you suggest?
Remove net45/46 in a month? or make a separate project to build these?

One of the disadvantages of staying with these "ancient" .net versions is that its hard to make optimisations that get benefit of better implemented classes in the framework.
Unless you want to start introducing `#compilerflags` like `#if NET45` - which then quickly becomes a mess to maintain.

If the task is simply remove `net45;net46` and replacing with `net462` then I will be happy to make a pull request for that?

**Comment by mhowlett** [comment]
we do indeed have `#if`s about the place, which would need updating..

would the suggested PR solve your annoyance?

**Comment by bjornbouetsmith** [comment]
> would the suggested PR solve your annoyance?

It would make it possible for me to build the solution :-) So yes - and everyone else using visual studio 2022 have the same issue, unless they have gone through hoops to be able to build these old frameworks.

**Comment by bjornbouetsmith** [comment]
Pull request created.
https://github.com/confluentinc/confluent-kafka-dotnet/pull/1783

**Comment by bjornbouetsmith** [comment]
@mhowlett How goes - can you approve my pull request? - Just so it does not grow stale because time goes?

**Comment by mhowlett** [comment]
merged.

**Comment by KalleOlaviNiemitalo** [comment]
This will need a change in <https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/README.md> as well.  Will that be done closer to the 1.9.0 release?

<https://github.com/confluentinc/confluent-kafka-dotnet/blob/af24fcb3f6c9c09d6c4d00ebe18903009eb3a7d3/README.md?plain=1#L38>

**Comment by mhowlett** [comment]
thanks... well spotted
https://github.com/confluentinc/confluent-kafka-dotnet/pull/1810
