### ISSUE TITLE
Serialize before sending message

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#178]
Instead of injecting key and value serializer in producer object, is there an option to serialize the payload and then just instruct the producer to push the message. 

Currently, we are using this
  producer = new Producer<string, string>(config, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8));

I will like something like this
  byte[] payload = serializer.Serialize(value);
producer.Publish(KeyPayload,ValuePayload)

Can this be accomplished by using a <byte[]> serializer in producer object? Does this instruct producer that  the object is already serialized and producer simply needs to send bytes to Kafka? Please confirm

**Comment by treziac** [comment]
You can use the Producer class (no generics) or a trivial ByteArray serializer like you said
