### ISSUE TITLE
How to get a list of consumers for a consumer group?

### ISSUE THREAD

**Issue by mausch** [confluentinc/confluent-kafka-dotnet#1784]
Hi, is it possible to do this programmatically? I can't seem to find the equivalent of this:

`kafka-consumer-groups --bootstrap-server <kafka-broker>:9092 --describe --group sample-consumer-group`

Just checked librdkafka and it seems it's not available there either?

Many thanks

Somewhat related to https://github.com/confluentinc/confluent-kafka-dotnet/issues/1678

**Comment by edenhill** [comment]
`ListGroups()`
