### ISSUE TITLE
Question about supported kafka version

### ISSUE THREAD

**Issue by mesies** [confluentinc/confluent-kafka-dotnet#1785]
Hello!

Cannot find anywhere on the documentation a definite answer, so I am trying here, does confluentinc/confluent-kafka-dotnet/ support kafka version 3?

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#compatibility

**Comment by mesies** [comment]
Thank you @edenhill for the quick reply! Closing the issue
