### ISSUE TITLE
I need to avoid launching ObjectDisposedException

### ISSUE THREAD

**Issue by AbraaoHonorio** [confluentinc/confluent-kafka-dotnet#1787]
Description
===========
I need to know if the handle is already closed, how can I do this?
I didn't find anything about this, so I made this simple public method
![image](https://user-images.githubusercontent.com/15929970/161322875-75ae4a2a-ed1a-42b3-8dcb-be9f59467125.png)

### Logs
```
   at Confluent.Kafka.Impl.SafeKafkaHandle.ThrowIfHandleClosed()
   at Confluent.Kafka.Impl.SafeKafkaHandle.Flush(Int32 millisecondsTimeout)
   at Confluent.Kafka.Producer`2.Flush(CancellationToken cancellationToken)
   at Strategio.Streams.Kafka.Producer.Strategies.ProducerSchemalessStrategy`3.Dispose(Boolean disposing) in 
```
Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. - 1.7.0.
 - [x] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [x] Provide broker log excerpts.
 - [] Critical issue.

**Comment by mhowlett** [comment]
Thanks for the suggestion. A good design would not allow for a client method to be called after it's been disposed. For that reason we won't add a way to check for this.
