### ISSUE TITLE
ConsumeException is missing the human readable error string

### ISSUE THREAD

**Issue by edenhill** [confluentinc/confluent-kafka-dotnet#1788]
When consumer_poll() returns an error there is also a rich error string that provides context to the error code.
However, this error string is not passed to the ConsumeException, which makes troubleshooting harder.

This line should be changed to add the output from `rd_kafka_message_errstr()`:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Consumer.cs#L857

**Comment by mhowlett** [comment]
done https://github.com/confluentinc/confluent-kafka-dotnet/pull/1800
