### ISSUE TITLE
Consumer health check

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1790]
what could be the preferred way to check status of the consumer ?
I would like to implemented some kind of health check: bool Consumer.IsConnected()

If for some reason consumer is not connected, what is the preferred way to reconnect ?:

- consumer.Subscribe()
or
- consumer = new ConsumerBuilder()

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#is-kafka-up

The client will automatically reconnect as needed, so there's no action the application should or can do.

**Comment by alfhv** [comment]
I mean in case the client is disconnected due to broker down, client timeout, client exception, etc.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down

**Comment by alfhv** [comment]
and what about client unhandled exception or consumer take too long processing a message and it is get disconnected ??
The service itself stay running but the process where consumer is running is killed and we have consumers really disconnected.
We would like to know consumer status at this moment, and eventually be able to reconnect the consumer without restart the service.
