### ISSUE TITLE
JsonSerializer - round trip of schema definition

### ISSUE THREAD

**Issue by mattrandle** [confluentinc/confluent-kafka-dotnet#1791]
We are attempting to do schema (json) first development for kafka topics which looks like,

1. Define a schema for a topic and register it with Schema Registry
2. Generate a C# class definition for the schema (using NjsonSchema) 
3. Use producers with UseLatestVersion=false and AutoRegister=false to ensure you are producing to the topic with a valid pre-registered schema.

In this case, the JsonSerializer uses NJsonSchema to infer a schema from the C# object and attempts to lookup the schema in schema registry.

The issue is that the generated schema from the C# object doesn't roundtrip back to an equivalent schema (according to schema registry) used to generate the object in the first place ! 

Its possible that setting 'normalize=true' when registering/looking up the schemas fixes this but we are running on 6.2.1 that doesnt support schema normalization.

Would it be possible to add an overload to the JsonSerializer constructor where you can pass in a schema definition (so JsonSerializer is not inferring the schema from the C# class - its just parsing the passed in schema definition instead) ?  You can do this with the Java client.

I am happy to do this ?  Do I just create a pull request and sign the agreement ?

**Comment by mhowlett** [comment]
sounds good, but i'll need to spend more than a minute or two thinking about this.. you can feel free to open a PR, but a bit of a warning that it may sit there for a while though before we get to it.

it's fine to use your own (modified) serdes - this is intended as a point of extensibility.

**Comment by mattrandle** [comment]
Thanks @mhowlett 

I did work round this by copy/pasting the existing JsonSerializer and creating my own 

Ill create a pull request but no worries if you dont get to it anytime soon
