### ISSUE TITLE
Consumer error: The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by andreig1** [confluentinc/confluent-kafka-dotnet#1799]
I have a windows service sunning consumer inside try-catch block. Nuget version 1.7

Service dies after some time with error:

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Communicators.KCConsumer.StartKafkaConsumer(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

How to reproduce
================
code   try
            {
                ThreadPool.QueueUserWorkItem(StartKafkaConsumer, obj);
            }
            catch (Exception e)
            {
                _logger.Log(LogType.Error, $"{e.Message}");
            }
call this method
private void StartKafkaConsumer(object obj)
        {
            _logger.Log(LogType.Comment, "Starting Consumer");
            var token = (CancellationToken)obj; 

            try
            {
                using (var consumer = new ConsumerBuilder<Ignore, string>(new ConsumerConfig(KafkaConfig)).Build())
                {
                    try
                    {
                        consumer.Subscribe(Topic);
                        ConsumerRunning = true;
                        while (!token.IsCancellationRequested)
                        {
                            _consume = consumer.Consume(10);
                            if (_consume == null) continue;
                            _message = _consume.Message;    
                            
                            LastRecv = DateTime.Now;
                            if (LogLevel != 0)
                                _logger.Log(LogType.Comment,
                                $"From: {_consume.TopicPartitionOffset} Message: {_message.Value}");
                            ParseAndSaveInputData(_message.Value);
                        }
                    }
                    catch (Exception e)
                    {
                        ConsumerRunning = false;

                        _errorMsg = e.Message;
                        if (e.InnerException != null &&
                            string.IsNullOrEmpty(e.InnerException.Message) == false)
                            _errorMsg += " " + e.InnerException.Message;
                        if (e.InnerException != null && e.InnerException.InnerException != null &&
                            string.IsNullOrEmpty(e.InnerException.InnerException.Message) == false)
                            _errorMsg += " " + e.InnerException.InnerException.Message;

                        try
                        {
                            consumer?.Close();
                            consumer?.Dispose();
                        }
                        catch (Exception ex)
                        {
                            throw new Exception($"Failed to close consumer: {ex.Message}");
                        }

                        throw new Exception($"Failed to consume: {_errorMsg}");
                    }

                    if (!token.IsCancellationRequested) return;

                    ConsumerRunning = false;
                    consumer?.Close();
                    consumer?.Dispose();
                }
            }
            catch (Exception e)
            {
                ConsumerRunning = false;
                throw new Exception($"Consumer error: {e.Message}");
            }
        }

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by mhowlett** [comment]
i don't know. i don't see evidence this is caused by the .net kafka client.
