### ISSUE TITLE
Trying to connect to Azure EventHub unable to consume

### ISSUE THREAD

**Issue by NicolaDipierro** [confluentinc/confluent-kafka-dotnet#1813]
Description
===========
I'm trying to connect and consume azure eventhub using confluent kafka and It's hanging on Consume.
The polling operation never can consume the message.

How to reproduce
================
Create a new azure event hub, produce a new message and try to consume using my sample code.

This is the code used:
using System;
using System.Threading;
using Confluent.Kafka;

class Program
{
    public static void Main(string[] args)
    {
        var conf = new ConsumerConfig
        {
            GroupId = "****",
            BootstrapServers = "****",
            // Note: The AutoOffsetReset property determines the start offset in the event
            // there are not yet any committed offsets for the consumer group for the
            // topic/partitions of interest. By default, offsets are committed
            // automatically, so in this example, consumption will only start from the
            // earliest message in the topic 'my-topic' the first time you run the program.
            AutoOffsetReset = AutoOffsetReset.Earliest,
            SaslPassword = "******",
            SaslUsername = "******",
            SecurityProtocol = SecurityProtocol.SaslSsl,
            SaslMechanism = SaslMechanism.Plain,
            SslCaLocation = @"file.pem",
            EnableAutoCommit = false
        };
        using (var c = new ConsumerBuilder<Ignore, string>(conf)
            .Build())
        {
            c.Subscribe("****");
            CancellationTokenSource cts = new CancellationTokenSource();
            Console.CancelKeyPress += (_, e) =>
            {
                e.Cancel = true; // prevent the process from terminating.
                cts.Cancel();
            };

            try
            {
                while (true)
                {
                    try
                    {
                        var cr = c.Consume(cts.Token);
                        Console.WriteLine($"Consumed message '{cr.Message.Value}' at: '{cr.TopicPartitionOffset}'.");
                    }
                    catch (ConsumeException e)
                    {
                        Console.WriteLine($"Error occured: {e.Error.Reason}");
                    }
                }
            }
            catch (OperationCanceledException)
            {
                // Ensure the consumer leaves the group cleanly and final offsets are committed.
                c.Close();
            }
        }
    }
}

Checklist
=========

 - [ ] Confluent.Kafka nuget version.
Latests
 - [ ] Operating system.
Windows

**Comment by mhowlett** [comment]
Confluent doesn't offer support for EventHubs (i.e. I won't try and debug this for you).

You can get a lot of information about what the client is doing by setting the `Debug` config to `all`, that might help you pin point the issue.

**Comment by NicolaDipierro** [comment]
Hi @mhowlett,

Thank you for your response. Reading the log you ask me to enable I see this:

%7|1652685213.226|PROTOERR|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Protocol parse failure for ApiVersion v3(flex) at 3/10 (rd_kafka_handle_ApiVersion:2131) (incorrect broker.version.fallback?)
%7|1652685213.227|PROTOERR|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: ApiArrayCnt -1 out of range

Could this be the source of my error?

**Comment by NicolaDipierro** [comment]
Hi @mhowlett,

Trying to solve the issue, I have added manually the topic partitions to the consumer and it works:

`
string topic = "topicName";
var partitions = new List<TopicPartitionOffset>();
for (int i = 0; i < 10; i++)
{
    partitions.Add(new TopicPartitionOffset(new TopicPartition(topic, new Partition(i)), Offset.Beginning));
}
c.Assign(partitions);
c.Subscribe(topic);

`
Dont know why buy I hope this workaround helps someone with my same problem.

If you know why this is working, please let me know.

**Comment by edenhill** [comment]
> %7|1652685213.226|PROTOERR|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Protocol parse failure for ApiVersion v3(flex) at 3/10 (rd_kafka_handle_ApiVersion:2131) (incorrect broker.version.fallback?)

That's no a problem, just how the protocol works. It can be safely ignored.
