### ISSUE TITLE
Kafka Retry Configurations and Offset commit

### ISSUE THREAD

**Issue by Gowtham2371998** [confluentinc/confluent-kafka-dotnet#1814]
Description
===========
How to configure Kafka to retry on the transient exceptions in messages?
What are the exceptions that need to be handled on Kafka messages?

Please provide some examples or documentation for more understanding.

**Comment by mhowlett** [comment]
we could do a better job of documenting error handling generally.
(marking as enhancement)

**Comment by mhowlett** [comment]
closing as we're well aware of need to document errors better and tracking elsewhere.
