### ISSUE TITLE
AvroSerializerConfig has some missing PropertyNames in the 1.8.2. release

### ISSUE THREAD

**Issue by domozi** [confluentinc/confluent-kafka-dotnet#1817]
Description
===========

SubjectNameStrategy Property of AvroSerializerConfig class is missing in 1.8.2. release.

How to reproduce
================

Try to setting up the SubjectNameStrategy in AvroSerializerConfig. Not possible because AvroSerializerConfig does not contain a definition for "SubjectNameStrategy" . 

  var avroSerializerConfig = new AvroSerializerConfig
            {
                // optional Avro serializer properties:
                BufferBytes = 100,
                AutoRegisterSchemas = false,
               SubjectNameStrategy = SubjectNameStrategy.Topic  //missing property

            };

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.8.2 ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
this property exists: 

https://github.com/confluentinc/confluent-kafka-dotnet/blob/1.8.x/src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializerConfig.cs#L136

https://github.com/confluentinc/confluent-kafka-dotnet/blob/1.8.x/src/Confluent.SchemaRegistry/SubjectNameStrategy.cs#L40
