### ISSUE TITLE
Consumer return half of message

### ISSUE THREAD

**Issue by tung1608** [confluentinc/confluent-kafka-dotnet#1819]
Description
===========
Producer
```
_producer = new ProducerBuilder<string, string>(new ProducerConfig()
            {
                BootstrapServers = _config.BootstrapServers,
                CompressionLevel = 6,
                CompressionType = CompressionType.Gzip,
                SecurityProtocol = SecurityProtocol.SaslPlaintext,
                SaslMechanism = SaslMechanism.Plain,
                SaslUsername = _config.UserName,
                SaslPassword = _config.Password,
                TransactionTimeoutMs = 30000,
                TransactionalId = Guid.NewGuid().ToString(),
                SocketKeepaliveEnable = true
            }).Build();
```

Consumer
```
_consumer = new ConsumerBuilder<string, string>(new ConsumerConfig()
            {
                BootstrapServers = config.BootstrapServers,
                GroupId = $"{config.GroupId}",
                AutoOffsetReset = AutoOffsetReset.Earliest,
                EnableAutoCommit = false,
                EnableAutoOffsetStore = false,
                SessionTimeoutMs = 20000,
                HeartbeatIntervalMs = 3000,
                EnablePartitionEof = true,
                SocketKeepaliveEnable = true,
                SecurityProtocol = SecurityProtocol.SaslPlaintext,
                SaslMechanism = SaslMechanism.Plain,
                IsolationLevel = IsolationLevel.ReadCommitted,
                MaxPollIntervalMs = 600*1000,
                PartitionAssignmentStrategy = PartitionAssignmentStrategy.CooperativeSticky
            }).Build();
```

I produce message in Json to Kafka with Gzip compression. From consumer side I got this exception randomly.
```
Local: Invalid compressed data 
    at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(TimeSpan timeout) 
```
Initially, I think problem cause by compress/decompress process. Then I try clear all messages and produce message with no compression to Kafka. No exception encountered but I see that, Consume method randomly return half of message and I can not deserialize Json string to object

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka 1.8.2.
 - [x] Apache Kafka version 3.1.0.
 - [x] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by tung1608** [comment]
Thank you @mhowlett.
That is weird, but I've got that issue quite often that day. After replace network adapter by new one then issue gone. I started to learn about Kafka for few months and this issue have never happened until that day when we going to apply for production. Its definitely caused by network adapter. So surprise if it can be handled in code. I hope that what I said can let you get more clear about the issue.

**Comment by mhowlett** [comment]
- Issues with the network would not result in half messages being returned.
- If there is a gzip issue, it is most likely an issue with the gzip library. But the library we use is standard, well tested and this hasn't come up before.

**Comment by tung1608** [comment]
hi @mhowlett , Kindly refer this video and data file
[screen-capture.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/8820476/screen-capture.zip)
[data.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/8820481/data.txt)

At 11th second, I got half of message. Then I try consume again from start by changing consumer groupId. I 've got full message with the same partion and offset at the end of video
