### ISSUE TITLE
system.AccessViolationException caught while exiting kafka as a background service.

### ISSUE THREAD

**Issue by mrabhishek393** [confluentinc/confluent-kafka-dotnet#1826]
Description
===========
system.AccessViolationException is thrown when the application is closed (using ctrl+c). Kafka consumer is run as a background service. I picked up the code from: -
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Web/RequestTimeConsumer.cs 

I know the cause of the error is _consumer.consume() which is being called after it has been disposed of. But how to handle this exception? 
@mhowlett 

How to reproduce
================
**ConsumerBackgroundService** class: 
`using Confluent.Kafka;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace extra
{
    public class ConsumerBackgroundService : BackgroundService
    {

        private readonly string _topic;
        private readonly IConsumer<Ignore, string> _consumer;

        public ConsumerBackgroundService(IConfiguration config)
        {
            ConsumerConfig consumerconfig = new ConsumerConfig
            {
                GroupId = config["Kafka:ConsumerSettings:GroupId"],
                BootstrapServers = config["Kafka:ConsumerSettings:BootstrapServers"],
                AutoOffsetReset = AutoOffsetReset.Latest
            };
            _consumer = new ConsumerBuilder<Ignore, string>(consumerconfig).Build();
            _topic = config["Kafka:Topic"];
        }

        protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            new Thread(() => StartConsumerLoop(stoppingToken)).Start();

            return Task.CompletedTask;
        }

        private void StartConsumerLoop(CancellationToken cancellationToken)
        {
            _consumer.Subscribe(_topic);

            while (!cancellationToken.IsCancellationRequested)
            {

                try
                {
                    var cr = _consumer.Consume(cancellationToken);

                    // Handle message...
                    Console.WriteLine(cr.Message.Value);
                }
                catch (OperationCanceledException)
                {
                    break;
                }
                catch (ConsumeException e)
                {
                    Console.WriteLine($"Consume error: {e.Error.Reason}");

                    if (e.Error.IsFatal)
                    {
                        break;
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine($"Unexpected error: {e}");
                    break;
                }
            }
        }
        public override void Dispose()
        {
            _consumer.Close(); // Commit offsets and leave the group cleanly.

            _consumer.Dispose();

            base.Dispose();
        }
    }
}
`

**Program.cs**

`using extra;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

Console.WriteLine("Hello, World!");
var host = Host.CreateDefaultBuilder()
            .ConfigureAppConfiguration(app =>
            {
                app.AddJsonFile("appsettings.json");
            })
            .ConfigureServices(services =>
            {
                services.AddHostedService<ConsumerBackgroundService>();               
            });

host.RunConsoleAsync();
`

Checklist
=========

Please provide the following information:
 - [Y ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.8.2 ] Confluent.Kafka nuget version.
 - [2.13-3.1.0 ] Apache Kafka version.
 - [Windows 11 ] Operating system.

**Comment by mhowlett** [comment]
you must not call consume after close / dispose, there is no way to handle it.

we could add additional checks / locks to ensure this doesn't happen but it would come with a performance penalty under normal operation.

**Comment by mohamed-firoz** [comment]
@mrabhishek393  did you find a solution for this ?
