### ISSUE TITLE
Memory leak in SafeKafkaHandle.SendOffsetsToTransaction ln.551

### ISSUE THREAD

**Issue by Lubos-P** [confluentinc/confluent-kafka-dotnet#1833]
Description
===========

The suspected memory leak is here:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/af24fcb3f6c9c09d6c4d00ebe18903009eb3a7d3/src/Confluent.Kafka/Impl/SafeKafkaHandle.cs#L551

offsetsPtr is never destroyed.

I presume Librdkafka.topic_partition_list_destroy(offsetsPtr); should be added to the finally block (ln 577)

How to reproduce
================
Running kafka exactly once semantic which calls SendOffsetsToTransaction will reproduce the issue. Process memory dump shows an accumulation of Confluent.Kafka.Imlp.rd_kafka_topic_partition objects.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
oh dear

thanks @Lubos-P !

resolved in #1835
