### ISSUE TITLE
In Net 6.0 frozen call  consumer.Subscribe(topic); when using .SetLogHandler

### ISSUE THREAD

**Issue by P9avel** [confluentinc/confluent-kafka-dotnet#1846]
After migration wrom .Net 5 to .Net 6 my old code not worked

consumerConfig.Debug = "consumer";
consumerBuilder.SetLogHandler(delegate(IConsumer<string, string> arg1, LogMessage arg2)
                        {
                            SetLogHandler(arg1, arg2, consumerName);
                        });
consumer.Subscribe(topic);  <-- Here frozen

private void SetLogHandler(IConsumer<string, string> consumer, LogMessage message, string consumerName)
        {
            if (new[] {"REBALANCE", "ASSIGNOR", "ASSIGN"}.Contains(message.Facility))
            {
                _logger.LogInformation($"{consumerName} " + message.Message);
            }
        }

I am commented consumerBuilder.SetLogHandler and now all OK. Issue reproduced on 1.8.2 and om 1.9.0

**Comment by mhowlett** [comment]
Thanks. It's been reported before, but interesting to know that this is an issue on .NET 6 not .NET 5.
As a workaround, you could capture `stderr` to get the log messages instead of setting a log handler.

**Comment by P9avel** [comment]
>>As a workaround, you could capture stderr to get the log messages instead of setting a log handler
Can you to show C# example?

**Comment by AntonSmolkov** [comment]
I'm having the similar issue - asp.net core 6 app hangs, but only under IDE and only in Debug mode.
Removing LogHandler from consumers fixes it.

@mhowlett Could you please provide a link to previous report?

BTW. I'm using Rider and Linux

**Comment by P9avel** [comment]
I am using VS and project in Docker Compose for Linux

**Comment by mhowlett** [comment]
if the log handler is empty, do you still see problems?

reiterating that not using a log handler, and reading from stderr is preferable because it is much more efficient (in fact a log handler can't handle the volume of messages output by debug=all on many machines). suggest doing this as a work around (and best practice).

**Comment by mhowlett** [comment]
closing in favor of #1834 - they are not the same but bundling all the "problems with LogHandler" up into one issue.
