### ISSUE TITLE
Using same IConsumer to consume partitions concurrently

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [confluentinc/confluent-kafka-dotnet#1851]
I have a topic with multiple partitions.
I would expect a single consumer process to use multithreading to consume each partition concurrently.

If i set up this consumer snippet:
```csharp
 while (!cancellationToken.IsCancellationRequested)
  {
      try
      {
          var result = _consumer.Consume(cancellationToken);
          var consumeResult = new ConsumeResult<TKey, TValue>(result);
          _logger.LogDebug($"Message<{typeof(TKey).Name}, {typeof(TValue).Name}> is being consumed. topic={result.Topic}, partition={result.Partition.Value}, key={result.Message.Key}, value={result.Message.Value}, requestId={consumeResult.TraceId}.");
  
          await Task.Yield();
          await OnConsume(consumeResult);
  
          if (!_enableAutoCommit)
          {
              _consumer.Commit();
          }
      }
      catch (OperationCanceledException e)
      {
          _logger.LogError(e, "Consumer has been stopped by cancellation token.");
          break;
      }
      catch (KafkaException e)
      {
          if (e.Error.IsFatal)
          {
              _logger.LogError(e, $"Fatal Error has occurred while consuming a message from Kafka: {e.Message}.");
              break;
          }
  
          _logger.LogWarning(e, $"Non Fatal Error has occurred while consuming a message from Kafka: {e.Message}.");
      }
      catch (Exception e)
      {
          _logger.LogError(e, $"Unexpected Error has occured while running the consumer logic, shutting down consumer. It this is not your intention you should handlke exception in your consumer logic. [{e.Message}].");
          break;
      }
  }
```

This code is causing each message to be consumed and process it, only after which it will try to consume another message from any of the assigned partitions.

Now i wonder is that okay to use the same instance of IConsumer, to run multiple concurrent loop for consuming messages.
I was testing the following code..

```csharp
protected async Task RunConsumer(CancellationToken cancellationToken)
{
    if (_cancelled)
    {
        return;
    }

    await Task.Yield();


    var consumeLoopTasks = new List<Task>();

    while (_consumer.Assignment.Count == 0)
    {
        Console.WriteLine($"waiting consumer assignments: { _consumer.Assignment.Count}");
        await Task.Delay(500);
    }

    Console.WriteLine($"consumer assignments: { _consumer.Assignment.Count}");
    foreach (var topicPartition in _consumer.Assignment)
    {
        Console.WriteLine($"spinning up consume loop per assignment: {topicPartition.Partition}-{topicPartition.Topic}");
        consumeLoopTasks.Add(StartConsumeLoopTask(cancellationToken));
    }

    await Task.WhenAll(consumeLoopTasks);
    Cancel(true);
}
```

* so 1st thing to note that I need to wait for the assignment to complete, thats not an issue.. polling with a simple while loop until _consumer.Assignment.Count >0 
 * then according to the amount of assigned topic\ partitions I would like to start the number of consumer loops using the same instance of IConsumer
 * unit tests seem to work as expected, and I just wonder if this is the correct approach .. 
 * one concern I had is there is no real ability to tell the same consumer instance to consume a specific partition using the method `.Consume(ct)`, hence I just run parallel loops and not a dedicate loop per partition. 

Using Confluent.Kafka nuget 1.4.4

**Comment by mhowlett** [comment]
There's no way with the C# API (or Java API) to control which of the assigned partitions to consume (or fetch) messages from. Messages will be consumed from each assigned partition roughly equally, though there will be clumping.
