### ISSUE TITLE
Slow consumer on some topic/partitions

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1854]
Description
===========

We have several consumers instances running inside same application. Each consumer subscribed to different topic, each topic with different message type.
Topics have very different partition numbers, ex: 1 topic 30partitions, another topic 1 or 2 partitions.

We have noticed that the topic with few partitions number (1 or 2) is consumed very slowly compared with the topic with large partitions number.
Volume of messages and size is bigger in topic with 30 partitions (thousands).
In topic with 1 or 2 partitions there is less than hundreds messages.

Any explanation of this situation ?

There is any way to define priority for a consumer instance or at topic level ??

**Comment by amirvalhalla** [comment]
> # Description
> We have several consumers instances running inside same application. Each consumer subscribed to different topic, each topic with different message type. Topics have very different partition numbers, ex: 1 topic 30partitions, another topic 1 or 2 partitions.
> 
> We have noticed that the topic with few partitions number (1 or 2) is consumed very slowly compared with the topic with large partitions number. Volume of messages and size is bigger in topic with 30 partitions (thousands). In topic with 1 or 2 partitions there is less than hundreds messages.
> 
> Any explanation of this situation ?
> 
> There is any way to define priority for a consumer instance or at topic level ??

Hi @alfhv 
actually your issue is a bit hard to understand ! because it could be because of your Kafka hasn't configured well on the server etc.. , anyway you can define queue priority. for more info please check link, [click on link](https://stackoverflow.com/questions/30655361/does-kafka-support-priority-for-topic-or-message)

**Comment by alfhv** [comment]
this priority configuration exists in dotnet implementation ??

**Comment by mhowlett** [comment]
> There is any way to define priority for a consumer instance or at topic level ??

no. the logic for determining which partitions to fetch is fixed.

i can see some benefit in making this an advanced configuration (though it is unlikely to get prioritized soon).
