### ISSUE TITLE
GroupCoordinator: Disconnected ((after 1199072ms in state UP, 1 identical error(s) suppressed)

### ISSUE THREAD

**Issue by Seamless2014** [confluentinc/confluent-kafka-dotnet#1855]
%6|1657078204.617|FAIL|rdkafka#consumer-8| [thrd:GroupCoordinator]: GroupCoordinator: 192.168.0.204:9092: Disconnected (after 1199072ms in state UP, 1 identical error(s) suppressed)
%3|1657078206.337|ERROR|rdkafka#consumer-8| [thrd:app]: rdkafka#consumer-8: GroupCoordinator:192.168.0.204:9092: Disconnected (after 1199072ms in state UP, 1 identical error(s) suppressed)
%6|1657081804.660|FAIL|rdkafka#consumer-8| [thrd:GroupCoordinator]: GroupCoordinator: 192.168.0.204:9092: Disconnected (after 1199178ms in state UP, 1 identical error(s) suppressed)
%3|1657081806.359|ERROR|rdkafka#consumer-8| [thrd:app]: rdkafka#consumer-8: GroupCoordinator: 192.168.0.204:9092: Disconnected (after 1199178ms in state UP, 1 identical error(s) suppressed)

one topic and more partion(15 个分区)

创建15个消费者实例，启动15个线程，每个消费者使用一个线程消费相应分区里的数据，但是有时会报上面的错误
这个问题有没有解决办法？

**Comment by maxisam** [comment]
I got the same error. And I only have 1 consumer. This error pops like every other couple minutes (<10 minutes)

**Comment by mhowlett** [comment]
hard to know without further information. unlikely to be an issue with the client it think.
