### ISSUE TITLE
Invalid default for MessageSendMaxRetries in documentation

### ISSUE THREAD

**Issue by gliljas** [confluentinc/confluent-kafka-dotnet#1858]
The inline documentation for MessageSendMaxRetries claims that the default is 2,147,483,647. That's not really true, is it?

**Comment by amirvalhalla** [comment]
> The inline documentation for MessageSendMaxRetries claims that the default is 2,147,483,647. That's not really true, is it?

Hi @gliljas 

it's ok because Maximum amount of integer is **2,147,483,647** so Kafka can retry sending failed messages until **int.Max**

**Comment by gliljas** [comment]
Yes, but the question is if the documentation should say that it's the default value.

**Comment by amirvalhalla** [comment]
you can see this on

> Yes, but the question is if the documentation should say that it's the default value.

you can see in doc [here](https://docs.confluent.io/platform/current/clients/confluent-kafka-dotnet/_site/api/Confluent.Kafka.ProducerConfig.html#Confluent_Kafka_ProducerConfig_MessageSendMaxRetries)

**Comment by gliljas** [comment]
Ok, it seems that default has changed quite a bit. My bad.
