### ISSUE TITLE
Pause partition and rebalance question

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1859]
If a consumer pause a partition and another consumer join the group and rebalance happens then the previously paused partition could be revoked and assigned to new consumer?
If it is the case, this partition will remains in paused state or new consumer will start consumming from it?

**Comment by fanruinet** [comment]
I'm not sure about the .net consumer implementation. But the expected behavior is defined in Java [KafkaConsumer.pause(...)](https://kafka.apache.org/32/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#pause\(java.util.Collection\)):
> Note: Rebalance will not preserve the pause/resume state.
