### ISSUE TITLE
Consume value return type.

### ISSUE THREAD

**Issue by sharpzilla** [confluentinc/confluent-kafka-dotnet#1866]
Hi everybody!
Would you describe to me how IConsumer works behind the scene.

I want to achieve maximum performance. So is there difference between:
new ConsumerBuilder<Ignore, byte[]>(consumerConfig).Build();
new ConsumerBuilder<Ignore, string>(consumerConfig).Build();

A few lines of code below I'm Deserializing it.

var obj = JsonSerializer.Deserialize<T>(record, serializeOptions);

I want skip UTF-16 conversion. So when I'm consuming: 
var record = _consumer.Consume();
What is returning? When it passing by net is it always string and in background it converted to byte[], or it is always byte[]?
I'm talking about Message.Value

**Comment by amirvalhalla** [comment]
Hi @sharpzilla 
when you're using ``` new ConsumerBuilder<Ignore, byte[]>(consumerConfig).Build(); ``` you will get bytes for **Message.Value** and whenever you use ``` new ConsumerBuilder<Ignore, string>(consumerConfig).Build();  ``` you will get string for **Message.Value**  , of course you should consider your producer which produce string or byte[] so depends on it you can consume string or byte[] , about the performance , based on my experienced and as far as I know always byte[] has better performance , specially in large projects.

**Comment by mhowlett** [comment]
The consumer works in conjunction with the configured deserializer to convert the bytes in the kafka message to a .NET type. Some types have default deserializers, so specifying a deserializer is optional. In the case of string, the default deserializer assumes the bytes are UTF8.
