### ISSUE TITLE
Bug in web example

### ISSUE THREAD

**Issue by qrjo** [confluentinc/confluent-kafka-dotnet#1867]
There's a bug in `RequestTimeConsumer` in your web example ([link](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Web/RequestTimeConsumer.cs)).

The class inherits from `BackgroundService`, but does so in a wrong way: the `ExecuteAsync` implementation returns a completed task, while the thread with the consumer loop is still running. The task returned from `ExecuteAsync` should not complete until the entire background process is finished. The way it's done now, `Dispose` may be called before the consumer loop has stopped running, which may cause errors.

I also have a (somewhat) related question: why is a thread used here, rather than a task?

**Comment by amirvalhalla** [comment]
Hi @qrjo 

in the web example , in **ExecuteAsync** used thread because after new thread 

```
return Task.CompleteTask;
```
so if you use task instead of Thread here , the code just will run one time and task will finish after first run , if you wanna use task instead of Thread you should delete 
```
return Task.CompleteTask;
```

also using Task instead of Thread has better performance because Thread will use more resources than Task

**Comment by qrjo** [comment]
Could just use `Task.Run(() => StartConsumerLoop(stoppingToken))` instead of `new Thread(() => StartConsumerLoop(stoppingToken)).Start()`.

But returning `Task.CompleteTask` from `ExecuteAsync` is wrong whether you use threads or tasks.

It would be better to use something like this:

```cs
protected override Task ExecuteAsync(CancellationToken stoppingToken)
{
    Thread t = new Thread(() => StartConsumerLoop(stoppingToken));
    t.Start();

    return Task.Run(() => t.Join());
}
```

or

```cs
protected override Task ExecuteAsync(CancellationToken stoppingToken)
{
    return Task.Run(() => StartConsumerLoop(stoppingToken), stoppingToken);
}
```

**Comment by amirvalhalla** [comment]
Ok , but it's just an example so depends on your business you can implement your consumer by different approaches

**Comment by qrjo** [comment]
Yeah, but a broken example isn't a good example, right?

**Comment by amirvalhalla** [comment]
in some aspects I agree but in some others not , but I think the best solution for this issue is adding multiple examples instead of one

**Comment by mhowlett** [comment]
i might have merged https://github.com/confluentinc/confluent-kafka-dotnet/pull/1446 too quickly. maybe we just revert that.

**Comment by anchitj** [comment]
Closing, as the suggested changes are merged.
