### ISSUE TITLE
Kafka Consumer Issue

### ISSUE THREAD

**Issue by coooooool** [confluentinc/confluent-kafka-dotnet#1869]
Description
===========
We are using a kafka consumer app based on the example below: The problem: we receive Error in SetErrorHandler: {"Code":"Local_Transport","Message":"sasl_ssl://XXXX.servicebus.windows.net:9093/0: Disconnected (after 3654528ms in state UP)"}

{"Code":"Local_Transport","Message":"GroupCoordinator: XXXX.servicebus.windows.net:9093: Disconnected (after 3654381ms in state UP)"}

{"Code":"Local_AllBrokersDown","Message":"5/5 brokers are down"}

Consumer developpend with JAVA don't have this issue.

How to reproduce
================
`
public void Consume()
        {
        

            try
            {

              

                int i = 0;
                int j = 0;
                const int commitPeriod = 5;

                var config = new ConsumerConfig
                {
                    BootstrapServers = BootstrapServers,
                    GroupId = "$Default",

                    SecurityProtocol = SecurityProtocol.SaslSsl,
                    SocketTimeoutMs = 60000,
                    SessionTimeoutMs =10000,
                    StatisticsIntervalMs =9000,
                    SaslMechanism = SaslMechanism.OAuthBearer,
                    AutoOffsetReset = AutoOffsetReset.Earliest,
                    SocketKeepaliveEnable = true,          
                    EnableAutoCommit = true,
                    EnablePartitionEof = true,
                    PartitionAssignmentStrategy = PartitionAssignmentStrategy.CooperativeSticky

                };

         

                using (var consumer = new ConsumerBuilder<string, string>(config)
                     // Note: All handlers are called on the main .Consume thread.
                  .SetOAuthBearerTokenRefreshHandler(OAuthBearerTokenRefreshHandler)
                    .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
                .SetPartitionsAssignedHandler((c, partitions) =>
                {
                    // Since a cooperative assignor (CooperativeSticky) has been configured, the
                    // partition assignment is incremental (adds partitions to any existing assignment).
                    Console.WriteLine(
                        "Partitions incrementally assigned: [" +
                        string.Join(',', partitions.Select(p => p.Partition.Value)) +
                        "], all: [" +
                        string.Join(',', c.Assignment.Concat(partitions).Select(p => p.Partition.Value)) +
                        "]");

                    // Possibly manually specify start offsets by returning a list of topic/partition/offsets
                    // to assign to, e.g.:
                    // return partitions.Select(tp => new TopicPartitionOffset(tp, externalOffsets[tp]));
                })
                .SetPartitionsRevokedHandler((c, partitions) =>
                {
                    // Since a cooperative assignor (CooperativeSticky) has been configured, the revoked
                    // assignment is incremental (may remove only some partitions of the current assignment).
                    var remaining = c.Assignment.Where(atp => partitions.Where(rtp => rtp.TopicPartition == atp).Count() == 0);
                    Console.WriteLine(
                        "Partitions incrementally revoked: [" +
                        string.Join(',', partitions.Select(p => p.Partition.Value)) +
                        "], remaining: [" +
                        string.Join(',', remaining.Select(p => p.Partition.Value)) +
                        "]");
                })
                .SetPartitionsLostHandler((c, partitions) =>
                {
                    // The lost partitions handler is called when the consumer detects that it has lost ownership
                    // of its assignment (fallen out of the group).
                    Console.WriteLine($"Partitions were lost: [{string.Join(", ", partitions)}]");
                })
                  .Build())
                {

                    String[] TopicsList = consumerCriteria.workeroptions.Kafka.Topics.ToString().Split(',');
                    
                    consumer.Subscribe(TopicsList);
                    try
                    {
                        while (true)
                        {
                            try
                            {
                                var consumeResult = consumer.Consume(cts.Token);

                                if (consumeResult.IsPartitionEOF)
                                {
                                

                                    continue;
                                }

                             
                               

                                processMessage(consumeResult.Message.Value, eventFileName, consumeResult.Topic);

                                if (consumeResult.Offset % commitPeriod == 0)
                                {
                                    // The Commit method sends a "commit offsets" request to the Kafka
                                    // cluster and synchronously waits for the response. This is very
                                    // slow compared to the rate at which the consumer is capable of
                                    // consuming messages. A high performance application will typically
                                    // commit offsets relatively infrequently and be designed handle
                                    // duplicate messages in the event of failure.
                                    try
                                    {

                                        consumer.Commit(consumeResult);
                                        consumer.StoreOffset(consumeResult);
                                    }
                                    catch (KafkaException e)
                                    {
                                          Console.WriteLine($"Commit error: {e.Error.Reason}");
                                       

                                    }
                                    finally
                                    {
                                        consumer.Close();
                                    }
                                }
                            }
                            catch (ConsumeException e)
                            {
                               Console.WriteLine($"Consume error: {e.Error.Reason}");

                            }
                           
                        }
                    }
                    catch (OperationCanceledException e)
                    {
                         Console.WriteLine("Closing consumer.");
                    consumer.Close();
                    }
                  

                }

            }
            catch (Exception e)
            {
                Console.WriteLine("Exception consumer.");

            }
           

        }
`

Please provide the following information:
 - [ ] Confluent.Kafka nuget version: 1.9.0

**Comment by coooooool** [comment]
@edenhill , have you an explanation Please?

**Comment by coooooool** [comment]
Log when  Debug = "cgrp,broker" is activated:

{"Message":"Log from Kafka: Debug || HEARTBEAT || rdkafka#consumer-1 || [thrd:main]: GroupCoordinator/0: Heartbeat for group \"$Default\" generation id 91"},
{"Message":"Log from Kafka: Debug || HEARTBEAT || rdkafka#consumer-1 || [thrd:main]: GroupCoordinator/0: Heartbeat for group \"$Default\" generation id 91"},
{"Message":"Log from Kafka: Debug || HEARTBEAT || rdkafka#consumer-1 || [thrd:main]: GroupCoordinator/0: Heartbeat for group \"$Default\" generation id 91"},
{"Message":"Log from Kafka: Debug || HEARTBEAT || rdkafka#consumer-1 || [thrd:main]: GroupCoordinator/0: Heartbeat for group \"$Default\" generation id 91"},
{"Message":"Log from Kafka: Debug || FAIL || rdkafka#consumer-1 || [thrd:sasl_ssl://we-itgapp-evt-dev.servicebus.windows.net:9093/bootst]: sasl_ssl://we-itgapp-evt-dev.servicebus.windows.net:9093/0: Disconnected (after 3659257ms in state UP) (_TRANSPORT)"},
{"Message":"Log from Kafka: Debug || FAIL || rdkafka#consumer-1 || [thrd:sasl_ssl://WE-itgapp-evt-dev.servicebus.windows.net:9093/2]: sasl_ssl://WE-itgapp-evt-dev.servicebus.windows.net:9093/2: Disconnected (after 3654088ms in state UP) (_TRANSPORT)"},
{"Message":"Log from Kafka: Debug || FAIL || rdkafka#consumer-1 || [thrd:GroupCoordinator]: GroupCoordinator/0: we-itgapp-evt-dev.servicebus.windows.net:9093: Disconnected (after 3658888ms in state UP) (_TRANSPORT)"},
**{"Message":"Log from Kafka: Info || FAIL || rdkafka#consumer-1 || [thrd:sasl_ssl://we-itgapp-evt-dev.servicebus.windows.net:9093/bootst]: sasl_ssl://we-itgapp-evt-dev.servicebus.windows.net:9093/0: Disconnected (after 3659257ms in state UP)"},**
{"Message":"Log from Kafka: Debug || FAIL || rdkafka#consumer-1 || [thrd:sasl_ssl://WE-Itgapp-evt-dev.servicebus.windows.net:9093/3]: sasl_ssl://WE-Itgapp-evt-dev.servicebus.windows.net:9093/3: Disconnected (after 3654085ms in state UP) (_TRANSPORT)"},
{"Message":"Log from Kafka: Debug || FAIL || rdkafka#consumer-1 || [thrd:sasl_ssl://We-itgapp-evt-dev.servicebus.windows.net:9093/1]: sasl_ssl://We-itgapp-evt-dev.servicebus.windows.net:9093/1: Disconnected (after 3654073ms in state UP) (_TRANSPORT)"},
{"Message":"Log from Kafka: Info || FAIL || rdkafka#consumer-1 || [thrd:sasl_ssl://WE-itgapp-evt-dev.servicebus.windows.net:9093/2]: sasl_ssl://WE-itgapp-evt-dev.servicebus.windows.net:9093/2: Disconnected (after 3654088ms in state UP)"},
{"Message":"Log from Kafka: Info || FAIL || rdkafka#consumer-1 || [thrd:GroupCoordinator]: GroupCoordinator: we-itgapp-evt-dev.servicebus.windows.net:9093: Disconnected (after 3658888ms in state UP)"},
{"Message":"Log from Kafka: Debug || STATE || rdkafka#consumer-1 || [thrd:sasl_ssl://we-itgapp-evt-dev.servicebus.windows.net:9093/bootst]: sasl_ssl://we-itgapp-evt-dev.servicebus.windows.net:9093/0: Broker changed state UP -> DOWN"},
**{"Payload":{"Code":"Local_Transport"	Message:"sasl_ssl://we-itgapp-evt-dev.servicebus.windows.net:9093/0: Disconnected (after 3659257ms in state UP)"}},**
{"Message":"Log from Kafka: Info || FAIL || rdkafka#consumer-1 || [thrd:sasl_ssl://WE-Itgapp-evt-dev.servicebus.windows.net:9093/3]: sasl_ssl://WE-Itgapp-evt-dev.servicebus.windows.net:9093/3: Disconnected (after 3654085ms in state UP)"},
{"Message":"Log from Kafka: Info || FAIL || rdkafka#consumer-1 || [thrd:sasl_ssl://We-itgapp-evt-dev.servicebus.windows.net:9093/1]: sasl_ssl://We-itgapp-evt-dev.servicebus.windows.net:9093/1: Disconnected (after 3654073ms in state UP)"},
{"Message":"Log from Kafka: Debug || STATE || rdkafka#consumer-1 || [thrd:sasl_ssl://WE-itgapp-evt-dev.servicebus.windows.net:9093/2]: sasl_ssl://WE-itgapp-evt-dev.servicebus.windows.net:9093/2: Broker changed state UP -> DOWN"},
{"Payload":{"Code":"Local_Transport"	Message:"sasl_ssl://WE-itgapp-evt-dev.servicebus.windows.net:9093/2: Disconnected (after 3654088ms in state UP)"}},
{"Message":"Log from Kafka: Debug || STATE || rdkafka#consumer-1 || [thrd:GroupCoordinator]: GroupCoordinator: Broker changed state UP -> DOWN"},
{"Payload":{"Code":"Local_Transport"	Message:"GroupCoordinator: we-itgapp-evt-dev.servicebus.windows.net:9093: Disconnected (after 3658888ms in state UP)"}},
{"Message":"Log from Kafka: Debug || STATE || rdkafka#consumer-1 || [thrd:sasl_ssl://WE-Itgapp-evt-dev.servicebus.windows.net:9093/3]: sasl_ssl://WE-Itgapp-evt-dev.servicebus.windows.net:9093/3: Broker changed state UP -> DOWN"},
{"Payload":{"Code":"Local_Transport"	Message:"sasl_ssl://WE-Itgapp-evt-dev.servicebus.windows.net:9093/3: Disconnected (after 3654085ms in state UP)"}},
{"Payload":{"Code":"Local_Transport"	Message:"sasl_ssl://We-itgapp-evt-dev.servicebus.windows.net:9093/1: Disconnected (after 3654073ms in state UP)"}},
{"Message":"Log from Kafka: Debug || STATE || rdkafka#consumer-1 || [thrd:sasl_ssl://We-itgapp-evt-dev.servicebus.windows.net:9093/1]: sasl_ssl://We-itgapp-evt-dev.servicebus.windows.net:9093/1: Broker changed state UP -> DOWN"},
{"Message":"Log from Kafka: Debug || CGRPSTATE || rdkafka#consumer-1 || [thrd:main]: Group \"$Default\" changed state up -> query-coord (join-state steady)"},
{"Payload":{"Code":"Local_AllBrokersDown"	Message:"5/5 brokers are down"}},

**Comment by mhowlett** [comment]
This is informational, you can ignore it. The API terminology "Error" is misleading. We may change it in the future, but it would be a breaking change.
