### ISSUE TITLE
How do I get the key value of consumption

### ISSUE THREAD

**Issue by easyboot** [confluentinc/confluent-kafka-dotnet#1870]
Description
===========
how can I get the key value。
example  {cr.Message.Key} {cr.Key} 
I tried to get the key value but got a null value

my code 

       public async void ConsumeMessage()
        {
            App.Log.Debug($" 消费消息");
            var conf = new ConsumerConfig
            {
                GroupId = "group-consumer-jsjpmessage",
                BootstrapServers = MyConfig.GetInstance().GetConfig("KafkaIP") + ":" + MyConfig.GetInstance().GetConfig("KafkaPort"),
                AutoOffsetReset = AutoOffsetReset.Earliest
            };

            using (var c = new ConsumerBuilder<Ignore, string>(conf).Build())
            { 
                c.Subscribe("JSJP.InfusionBag.Message");

                CancellationTokenSource cts = new CancellationTokenSource();
                Console.CancelKeyPress += (_, e) =>
                {
                    e.Cancel = true; // prevent the process from terminating.
                    cts.Cancel();
                };

                try
                {
                    while (true)
                    {
                        try
                        {
                            var cr = c.Consume(cts.Token);
                            string msg = cr.Value;
                            // Debug.WriteLine($"kafka 消费 Consumed message \'{cr.Value}\' at: \'{cr.TopicPartitionOffset}\'.");
                            App.Log.Debug($"kafka 消费 消息 ~{cr.Message.Key}~ ~{cr.Message.Value}~ -{cr.Key}- \'{msg}\' at: \'{cr.TopicPartitionOffset}\'."); 
 
                        }
                        catch (ConsumeException e)
                        {
                            App.Log.Error($"KafkaConsumer 消费消息异常: {e.Error.Reason}"); 
                        }
                    }
                }
                catch (OperationCanceledException)
                {
                    c.Close();
                }
            }
        }

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
Kafka key and values are both are nullable, so the key is probably null.
