### ISSUE TITLE
Question: Message Timestamp unordered

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1872]
Checking offsets and message timestamps I found timestamps are not always ordered as offsets are.
Sometimes I can see that timestamp of offset N is greater that timestamp of offset N+1 (on same partition) with difference up to around 150milliseconds.
Messages were sent by a single producer, we are not settings timestamp value on messages on producer side.
Means that if I order messages of multiple partitions by timestamp I will end by unordered offsets for same partition.
is that the expected behaviour ? why ? it is possible to ensure correctly ordered timestamps (for the same partition) ?

**Comment by mhowlett** [comment]
Interesting, it may be because of retries.  Do you have EnableIdempotence set to true? (try that).

**Comment by mhowlett** [comment]
it's possible this could occur due to retries, though it should be pretty rare.
