### ISSUE TITLE
Unknown and Timed Out Errors

### ISSUE THREAD

**Issue by jrowland1230** [confluentinc/confluent-kafka-dotnet#1878]
Description
===========
We are receiving Unknown, Timed out: disconnect and Group Coordinator errors from the Client (Consumer) as shown below. We are still able to consume messages but receive these errors 3 to 4 times a minute continuously.

[thrd:ssl://kafka-XXX]: ssl://kafka-XXX/560631992: Connect to ipv4#99.999.121.227:9093 failed: Unknown error (after 21021ms in state CONNECT)

[thrd:ssl://kafka-XXX]: ssl://kafka-XXX/560631992: 1 request(s) timed out: disconnect (after 573987ms in state UP)  

[thrd:GroupCoordinator]: GroupCoordinator: kafka-XXX: Connect to ipv4#99.999.121.228:9093 failed: Unknown error (after 21020ms in state CONNECT)

How to reproduce
================
Run the windows service application. This is happening in multiple environments.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.9.0 Confluent.Kafka ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ dotnet 6, c# running as a windows service. Using all default configuration settings.] Client configuration.
 - [Windows 2016 Data Center] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
where are you seeing the errors? via the error handler? or as an exception from `Consume`? the former are intended to be informational.

it looks like you're having connectivity issues. the client is able to auto-recover from this.
