### ISSUE TITLE
Confluent.Kafka.ConsumeException: Unknown broker error

### ISSUE THREAD

**Issue by yesidbalvin** [confluentinc/confluent-kafka-dotnet#1879]
Description
===========
I'm using Confluent.Kafka to consume events from Azure Event Hubs, and sometimes getting this error when consume=>
Confluent.Kafka.ConsumeException: Unknown broker error
at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)

How to reproduce
================

It is happening after some days of a constant message consuming, retrying message process

Package Version
<PackageReference Include="Confluent.Kafka" Version="1.7.0" />

Source Code 

```
ConsumeResult<string, IEnumerable<BlobCreatedEvent>> fileUploadNotification = null;
try
        {
          fileUploadNotification = consumer.Consume(cancellationToken);
          //  Call the Use Case
          consumer.Commit(fileUploadNotification);
          IsWorking();
        }
        catch (ConsumeException ex)
        {
          _logger.LogError(ex, "AzureIoTFileUploadNotificationsSubscriber -> Error consuming from IoT Hub.");
          base.Suspend(consumer, fileUploadNotification, async () => { await StopAsync(cancellationToken); });
        }
```
What base.Suspend does is consumer.Unsubscribe(), and start the backgroundservice again 

Logs 
>  {
>   "@t": "2022-03-02T00:52:35.0090283Z",
>   "@m": "AzureIoTFileUploadNotificationsSubscriber -> Error consuming from IoT Hub.",
>   "@i": "1e51b70e",
>   "@l": "Error",
>   "@x": "Confluent.Kafka.ConsumeException: Unknown broker error
>    at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
>    at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
>    at .MessageBus.IoT.AzureIoTFileUploadNotificationsSubscriber.ListenToIoTFileUploadEventAsync(CancellationToken cancellationToken) in /src/MessageBus/IoT/AzureIoTFileUploadNotificationsSubscriber.cs:line 58","SourceContext": ".MessageBus.IoT.AzureIoTFileUploadNotificationsSubscriber","MachineName": "null",
>   "ProcessId": 1,
>   "ProcessName": "dotnet",
>   "ThreadId": 52,
>   "MemoryUsage": 85640664,
>   "ExceptionDetail": {
>     "HResult": -2146233088,
>     "Message": "Unknown broker error",
>     "Source": "Confluent.Kafka",
>     "ConsumerRecord": {
>       "Topic": "dev-files-gov-evh",
>       "Partition": {
>         "Value": 6,
>         "IsSpecial": false,
>         "$type": "Partition"
>       },
>       "Offset": {
>         "Value": 70149,
>         "IsSpecial": false,
>         "$type": "Offset"
>       },
>       "TopicPartition": {
>         "Topic": "dev-files-gov-evh",
>         "Partition": {
>           "Value": 6,
>           "IsSpecial": false,
>           "$type": "Partition"
>         },
>         "$id": "1"
>       },
>       "TopicPartitionOffset": {
>         "Topic": "dev-files-gov-evh",
>         "Partition": {
>           "Value": 6,
>           "IsSpecial": false,
>           "$type": "Partition"
>         },
>         "Offset": {
>           "Value": 70149,
>           "IsSpecial": false,
>           "$type": "Offset"
>         },
>         "TopicPartition": {
>           "$ref": "1"
>         }
>       },
>       "Message": {
>         "Key": null,
>         "Value": [
>           70,
>           101,
>           116,
>           99,
>           104,
>           32,
>           102,
>           114,
>           111,
>           109,
>           32,
>           98,
>           114,
>           111,
>           107,
>           101,
>           114,
>           32,
>           48,
>           32,
>           102,
>           97,
>           105,
>           108,
>           101,
>           100,
>           58,
>           32,
>           85,
>           110,
>           107,
>           110,
>           111,
>           119,
>           110,
>           32,
>           98,
>           114,
>           111,
>           107,
>           101,
>           114,
>           32,
>           101,
>           114,
>           114,
>           111,
>           114
>         ],
>         "Timestamp": {
>           "Type": "NotAvailable",
>           "UnixTimestampMs": -1,
>           "UtcDateTime": "1969-12-31T23:59:59.9990000Z",
>           "$type": "Timestamp"
>         },
>         "Headers": []
>       },
>       "Key": null,
>       "Value": {
>         "$ref": "Cyclic reference"
>       },
>       "Timestamp": {
>         "Type": "NotAvailable",
>         "UnixTimestampMs": -1,
>         "UtcDateTime": "1969-12-31T23:59:59.9990000Z",
>         "$type": "Timestamp"
>       },
>       "Headers": {
>         "$ref": "Cyclic reference"
>       },
>       "IsPartitionEOF": false
>     },
>     "Error": {
>       "Code": "Unknown",
>       "IsFatal": false,
>       "Reason": "Unknown broker error",
>       "IsError": true,
>       "IsLocalError": false,
>       "IsBrokerError": false
>     },
>     "Type": "Confluent.Kafka.ConsumeException"
>   },
>   "Application": "file-receiver"
> }

This error was previously reported with no answer
https://github.com/Azure/azure-event-hubs-for-kafka/issues/188

**Comment by mhowlett** [comment]
Seems likely this is related to event hubs. I think it is likely safe to ignore it, though you might want to have a check in your code to make sure offsets of returned messages are contiguous.
