### ISSUE TITLE
Consumer should implement an interface

### ISSUE THREAD

**Issue by michael-sherling** [confluentinc/confluent-kafka-dotnet#188]
I'm trying to make a unit test for my code that is using the Consumer class, but actually it is very difficult to do it because I can't mock it.
there are some workarounds, I thought creating some warping class and use it, but I think it is very important for the consumer to implement an interface (the producer is doing so)

**Comment by mhowlett** [comment]
Thanks for the suggestion @michael-sherling - sounds like a great idea to me. 

Note that the interface `ISerializingProducer` implemented by `Producer` is actually for a subset of the functionality. We probably should add 4 new interfaces (for serializing and non-serializing variants of producer and consumer).

**Comment by michael-sherling** [comment]
This will be very nice, thanks.
BTW, is this project opened for development outside of the confluent team only so I can create pull request also? if so I can implement this small change

**Comment by treziac** [comment]
Yep it is. I'm a contributor outside confluent ^^

**Comment by michael-sherling** [comment]
@treziac great! so basically I just clone the repo and committing to a new branch and creating new pull request?
is there some guide lines for this?

**Comment by treziac** [comment]
That's it :)

No written guide lines for now. 
For interfaces, we will want it fully documented (the indentation in the project is not the default one so try to keep with what exists) Simply copy the one from the Producer class should be enough As often, just respect the global syntax in other files. Copying the one from producer should be enough.
Also feel free to add unit/integration tests (but I don't think there will be any necessary here)

Also (related to the issue and not the contribution) we will have to be sure this doesn't decrease perf (adding abstraction is not free) This should not be a problem usually as long as we don't use the interface internally (the CLR/JIT misses some optimizations here) I wonder if this could be the case in the Producer<K,V> by the way, will have to check this - this is negligible usually (perhaps <1ms), but as we plan to have a high-perf-library with hundred of thousands calls per second...

**Comment by mhowlett** [comment]
yes - feel free to do a PR :-).

You might want to open a PR with just one interface first (maybe `IConsumer<TKey, TValue>`) which will be quicker to iterate on if we want any changes made.

regarding API docs, there is an `include` tag, and I was thinking now might be a good time to start using it: https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/xmldoc/include 

I'm not worried about performance here - if there is a perf hit, it will be very small and it's a small price to pay for the benefit.

**Comment by mhowlett** [comment]
BTW: This should be a straightforward change, so I think we should be able to get it in to 0.9.6 if you get onto it soon. The main thing that's likely to hold it up I think is doing a good job on the API docs.

**Comment by michael-sherling** [comment]
@mhowlett Regarding the the interface, I think it will be good for now to have this complete interface.
 For future versions I think we need to make it consistent with the producer and have the same nature of interfaces for both.

Regarding the docs, so basically what you suggested is adding a doc with the API description for the interface and just reference it inside the interface instead of writing the text inside the interface itself? if so I can do it and we can see how it looks and can adopt it to the other interfaces for future version.

**Comment by mhowlett** [comment]
yep - my suggestion to open a PR with only one interface done is just to minimize the amount of re-work required if we want changes before merging. 

note that we'll will want `IProducer` and `IProducer<TKey,TValue>` in addition to `ISerializingProducer` - they are for different purposes. 

re docs - yes + also reference it from the `Producer` classes. We need to minimize the amount of duplication in the API doc comments - it's already getting out of hand and adding 4 new interfaces is going to cause much more duplication.

thanks for your efforts!

**Comment by lixiandai** [comment]
@mhowlett we are also facing the difficulty to add unit tests for the wrapper of Confluent.Consumer and Confluent.Producer. I noticed the interface has been checked in in 1.0 experimental branch already. do u know if this will be back-port to 11.0.4 or not? if no, when the 1.0 official release will be out for users?

Thanks.

**Comment by mhowlett** [comment]
It won't be backported.

1.0-experimental will become 1.0.x soonish (fully reviewed, you'll be able to have decent confidence in it).

The 1.0 release is between 3 and 6 months away (coinciding with the other librdkafka based clients also going to 1.0). It's going to be a big one.

**Comment by mhowlett** [comment]
closing, this feature should be merged to master within a couple of weeks.
