### ISSUE TITLE
time out error

### ISSUE THREAD

**Issue by easyboot** [confluentinc/confluent-kafka-dotnet#1882]
Description

When my program runs for a period of time, it will prompt timeout.

Kafka is closed. When I start Kafka, it will work normally and the fault will reappear in about 10 days,

The following is the log information of windows:

Application: ImportPIVASData.exe CoreCLR Version: 4.700.22.16002 .NET Core Version: 3.1.24 Description: The process was terminated due to an unhandled exception. Exception Info: Confluent.Kafka.ProduceException`2[System.String,System.Object]: Local: Message timed out at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken) at ImportPIVASData.Kafka.KafkaProducer.SendAsync(String Topic, String Key, String Value) in D:\work\projects\ImportPIVASData\ImportPIVASData\Kafka\KafkaProducer.cs:line 62 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state) at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi) at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state) at System.Threading.QueueUserWorkItemCallback.Execute() at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by mhowlett** [comment]
seems like a connectivity issue. you could increase the number of retries and/or timeouts. or set `EnableIdempotence` to true, which will automatically do this, and give you exactly once produce semantics.
