### ISSUE TITLE
Could not load file or assembly 'Confluent.Kafka, Version 1.8.2.0'

### ISSUE THREAD

**Issue by weberms** [confluentinc/confluent-kafka-dotnet#1885]
Description
===========
The latest version 1.8.2 of Confluent.SchemaRegistry has a reference to v1.8.2 of Confluent.Kafka so you cannot use the latest version of Confluent.Kafka v1.9.2 unless a binding redirect is added to app.config.

How to reproduce
================
Create a project that references both Confluent.SchemaRegistry v1.8.2 and Confluent.Kafka v1.9.2.  Add code to consume from a Kafka topic using the schema registry.  Debug the app and observe the error.

**Comment by mhowlett** [comment]
the latest version of Confluent.SchemaRegistry is 1.9.2. https://www.nuget.org/packages/Confluent.SchemaRegistry/1.9.2
to minimize potential problems, it is best to align versions.
