### ISSUE TITLE
A memory leak when putting strings from kafka to list<string>

### ISSUE THREAD

**Issue by wafeelka** [confluentinc/confluent-kafka-dotnet#1888]
Description
===========
I have a memory leak when i consume from kafka topic and put message into a simple list<string>

More details:
I created a simple web api empty, where i have  hosted service. Inside the hosted service i have a infinity loop which every 15 second repeat some simple action (Request to topic to back a new records and put record into a list).
After this the hosted service wait 15 seconds and repeat this actions again.

The problem is  every HostedService Loop a memory increase and never free.
I did some cases like:
1)Turn off a method list.Add(record); and memory leak was gone. But wait a 2 case
2) I create a simple string and put example message like into kafka topic, and put this message into list. Memory leak didnt happened, but if i put a string whith a got from consumer.Consume().Message.Value a memory leak heppened with my app.
I tried before every consume loop call list.Clear(). also tried use after using construction call GC.Collect(). And i tried to wrote this before the conume loop: list = null; All this things can't help.
Can you help me with that?

This is my memory after first loop 
![image](https://user-images.githubusercontent.com/49671882/188065456-d7372dce-6ff6-4aab-a21a-e1862f47b7c5.png)

This after second loop

![image](https://user-images.githubusercontent.com/49671882/188065823-fb3ed9a1-da4a-4819-a66a-c16f75919db5.png)

Also, in snapshot i see what list was clear after consume but memory doesnt free
![image](https://user-images.githubusercontent.com/49671882/188065395-7b15913f-4a2c-41df-a719-2e38e9223381.png)

How to reproduce
================
Create a hosted service and into a loop try consume message and put into a list() a several times.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
My hosted service:

 public class HostedMailsFromKafkaSender : BackgroundService
    {
        private readonly ILogger<HostedMailsFromKafkaSender> _logger;
        private readonly IKafkaSender _kafkaSender;
        public HostedMailsFromKafkaSender(IKafkaSender sender, ILogger<HostedMailsFromKafkaSender> logger)
        {
            _kafkaSender = sender;
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken cancellationToken)
        {
            await Task.Delay(5000, cancellationToken);

            while (!cancellationToken.IsCancellationRequested)
            {
                try
                {
                    _kafkaSender?.SendMails();

                }
                catch (Exception e)
                {
                    _logger.LogCritical(e, "Send error");
                }
                await Task.Delay(TimeSpan.FromSeconds(15), cancellationToken);
            }
        }
    }

My kafka consume logic 

public  List<TaskModel> ReadFromTopic(string topic)
        {
            List<string> mailListTest = new();
            var consumerConfig = new ConsumerConfig();
            config.GetSection("Kafka:ConsumerSettings").Bind(consumerConfig);
            using (var _consumer = new ConsumerBuilder<string, string>(consumerConfig).Build())
            {
                try
                {
                    _consumer.Subscribe(topic);
                   
                    while (true)
                    {
                        var consumeResult = _consumer.Consume(10000);
                         if (consumeResult.IsPartitionEOF)
                            break;

                         //tried wihtout this cast.Same thing
                        var encodingBytesRecord = Encoding.UTF8.GetBytes(consumeResult.Message.Value.ToString());
                        var record = Encoding.UTF8.GetString(encodingBytesRecord);
                        try
                        {
                            mailListTest.Add(record); 
                        }
                        catch (Exception ex)
                        {
                           
                        }
                    }
                    return null;
                }
                catch (Exception ex)
                {
                    return null;
                }
            }
        }

My DI registration: 
 public void ConfigureServices(IServiceCollection services)
        {
           services.AddTransient<IKafkaSender, KafkaSender>();
           services.AddHostedService<HostedMailsFromKafkaSender>();
           services.AddControllers();
        }

 - [ ] Confluent.Kafka nuget version. **1.9.2**
 - [ ] Apache Kafka version. sorry but i dont know
 - [ ] Client configuration.

My consumer settings:
 "AutoOffsetReset": "Earliest",
      "EnableAutoCommit": "false",
      "EnablePartitionEof": "true",
      "Topic": "",
      "BootstrapServers": "",
      "SslKeystorePassword": "",
      "SslCaLocation": "",
      "SecurityProtocol": "Ssl",
      "MaxPollIntervalMs": 600000

 - [ ] Operating system: **tested on windows 10 and centos 8**
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.For me -yes

PS. Sorry about my english

**Comment by wafeelka** [comment]
I got dotMemory and what I saw.
The Consume() method has a GetString() method that eats up all the memory. Or I'm wrong?
Is this because I have read all posts from the topic (AutoOffsetReset: "Earliest") or not?

Can anyone tell me what should I do?

![image](https://user-images.githubusercontent.com/49671882/188116693-b31a9b07-0738-4059-a539-3d3206ecf1f4.png)

**Comment by gurustron** [comment]
I would argue that there is no memory leak happening here cause you are adding strings to a list in endless loop.

**Comment by albertherd** [comment]
I suspect that this is an issue with GC.

Well, not an issue really. I guess you're stumbling GC in Server Mode. -> https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc

This video explains it in very good way -> https://www.youtube.com/watch?v=y7FTxAqExyU

**Comment by mhowlett** [comment]
yes, most likely not a leak associated with the client.

librdkafka may allocate up to a fair amount of memory. you could try fiddling with queued.max.messages.kbytes to limit that but i don't think this is the issue. i think more likely on the .net side.
