### ISSUE TITLE
Avro Serializer

### ISSUE THREAD

**Issue by anupkumarsharma** [confluentinc/confluent-kafka-dotnet#189]
This is actually a question. We follow the exact same structure of wire transfer Magic Byte + SchemaId+Message. We already have JAVA project doing the same but now we want to extend it for C# as well. I wanted to know that is there any default implementation in this project, which can handle such type of serialization?  Any examples ?

**Comment by treziac** [comment]
See #67 for some answers
I think I will post a sample on how to use existing lib to do this to have something before the wrapper on the desert C library. 
Using https://github.com/jakobz/schema-registry-dotnet should work pretty straight-forward. No computer for the we so won't post anything before next week

**Comment by mhowlett** [comment]
this was added in the 0.11.4 release
