### ISSUE TITLE
[SSL] running producer with SSL config pointing to keystore fails

### ISSUE THREAD

**Issue by Protheon** [confluentinc/confluent-kafka-dotnet#1896]
Description
===========

running producer with SSL config pointing to keystore fails

"_producerConfig.SslKeystoreLocation = {KEYSTORENAME}";
"_producerConfig.SslKeystorePassword = {KEYSTOREPASSWORD}";

error msg:
Error reading ssl.keystore.location PKCS#12 file: #\Test\keystore.p12: error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data

stack trace:

   at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config, IClient owner)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
   at Confluent.Kafka.ProducerBuilder`2.Build()

i dug a bit and see that this safehandle uses runtime lbrdkafka.dll to create the connection.
on their site i see that to setup ssl they make no mention of using keystore, instead suggest using file location
ssl.key

Exposing the client key in a file poses a serious security risk and cannot be used on production environment.

is loading the keystore supported?

How to reproduce
================

setup a simple kafka producer that points to a valid keystore with a valid certificate in producerconfig. 
run the application.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ win 10/2019 serv] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ x] Critical issue.

**Comment by mhowlett** [comment]
I just opened a PR that walks through how to set up TLS Auth, and verified this works on my machine https://github.com/confluentinc/confluent-kafka-dotnet/pull/1900/files . How are you generating the PKCS12 keystore? The error you are seeing matches this issue: https://github.com/dotnet/runtime/issues/29799 and indicates either an invalid PKCS12 file or invalid path.

Note: I have not tested this on Windows yet. I would be interested to know if you see the same error on following the instructions in PR #1900.

**Comment by Protheon** [comment]
Hi @mhowlett . Thank you very much for looking into it and providing support links.

Indeed i am running on windows 10 and will be deploying to a windows 2019 server.

PKCS12 keystore is being generated through the app KeyStore Explorer and is valid since I use the exact same keystore ( with exact same certificates and path ) with the SchemaRegistryConfig initialization and it works perfect.
But the Confluent.SchemaRegistry.SchemaRegistryConfig uses the Confluent.SchemaRegistry (ver. 1.9.0) confluent package which uses CachedSchemaRegistryClient to directly create a x509certificate:
var cert = new X509Certificate2(certificateLocation, certificatePassword);

However, the Kafka.ProducerBuilder is using a combination of dllimport and delegates to call the runtime librdkafka.dll which seems to be written in c/c++ and seems to use openssl to work with the keystore.

Could it be that somehow down in the stack, the use of openssl fails? I can't even troubleshoot, because i cant decompile the code and the opensource repo is cryptic to read (especially because its low level C).

I left a question there but doubt they will answer https://github.com/edenhill/librdkafka/discussions/3979

just in case, here is my full schemaconfig and producer config initialization:

`
            _producerConfig = new ProducerConfig
            {
                MessageTimeoutMs = kafkaSettings.MessageTimeoutMs,
                BootstrapServers = kafkaSettings.BootStrapServers
            };

            var schemaRegistryConfig = new SchemaRegistryConfig
            {
                Url = kafkaSettings.SchemaRegistryUrls
            };

            if (kafkaSettings.SslEnabled)
            {
                schemaRegistryConfig.SslKeystoreLocation = $"{kafkaSettings.TlsFilesLocation}\\{KEYSTORENAME}";
                schemaRegistryConfig.SslKeystorePassword = kafkaSettings.KeyPassword;

                _producerConfig.SecurityProtocol = SecurityProtocol.Ssl;
                _producerConfig.SslCaLocation = $"{kafkaSettings.TlsFilesLocation}\\{CANAME}";
                _producerConfig.SslKeystoreLocation = $"{kafkaSettings.TlsFilesLocation}\\{KEYSTORENAME}";
                _producerConfig.SslKeystorePassword = kafkaSettings.KeyPassword;
            }
`

*update* producer config has some extra settings like sslengine which supposedly points to the openssl file. should i use that?
i tried to use _producerConfig.SslEngineLocation to point to the openssl.exe path, but got new error  "engineId missing" . no idea what the engine id is.

i have openssl.exe ver 1.1.1.

also tried with confluent.kafka 1.9.3, no success.

**Comment by mhowlett** [comment]
Thanks for the input.

Here are some things I'm thinking of to try and narrow this down.
1. Run the steps in the TlsAuth example on Windows and verify whether they do or do not work. If this doesn't work, we know it's an issue on Windows.
2. If that works fine, compare the PKCS12 file generated with KeyStore Explorer vs one generated with openssl. The openssl tool should facilitate that, I think.
3. Another cross platform check - verify the KeyStore Explorer PKCS12 file on macos or linux (maybe with docker or WSL2)

Feel free to try any of that or other :-). 

SslEnginePath should point to openssl.dll (assuming this is supported on windows, i'm not sure).

This issue has come up elsewhere too, so I will be looking into it.

**Comment by Protheon** [comment]
Hi @mhowlett 
I can succesfully use openssl to open my keystore.p12 using
openssl pkcs12 -nokeys -info -nocerts -in /path/to/your/file/foo.p12

I can also export the certificate as pem using openssl, so I don't think anything is wrong with the keystore or its openssl compatibility. 
I am using the openssl for windows version that comes with git https://gitforwindows.org/. I'm not sure if there is any difference between that one and the one that librdkafka uses (if any at all, since i dont know how librdkafka is setup to work with openssl).

I copy/pasted the tls program in your pr1900 and ran using 1.9.3 and got the same error at line
var producer = new ProducerBuilder<Null, string>(config).Build()

Error reading ssl.keystore.location PKCS#12 file: #\Test\keystore.p12: error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data

I also converted the pkcs12 to pem and tried to use that as file but got error:
Error reading ssl.keystore.location PKCS#12 file: ...\keystore.pem: error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error: Type=PKCS12'

I suppose it only works with pkcs12 file.

I think its a problem with running the library on windows. Its somehow related to either a misconfiguration of openssl or an incompatibility of librdkafka.redist 1.9.2 with windows.

i've opened an incident on https://github.com/edenhill/librdkafka .

What's the next step?

**Comment by mhowlett** [comment]
I think the next step is to try loading the pkcs12 file that doesn't work on windows on linux (inside a docker container would be fine). Are you able to do that easily? Appreciate if you can... regardless we'll pick this up and investigate further - the probabilities seem to be pointing towards this being a real issue on Windows.

**Comment by mhowlett** [comment]
@emasab found the root cause of this issue - the file should be opened in 'rb' mode. on linux there is no difference, but on windows there is. 

https://github.com/edenhill/librdkafka/blob/2a8bb418e0eb4655dc88ce9aec3eccb107551ff4/src/rdkafka_ssl.c#L1249 

closing in favor of the librdkafka issue.

**Comment by Protheon** [comment]
hurray! :) @emasab created a pr. lets hope its merged soon. do you know how soon can we use the fix on this library?

**Comment by Protheon** [comment]
hi @mhowlett . any idea when this fix will be released? best regards

**Comment by edenhill** [comment]
The v2.0.0 release is planned for mid january, including this fix.

**Comment by Protheon** [comment]
Happy new year @edenhill. Is the v2.0.0 release on schedule for mid January? Best regards!
