### ISSUE TITLE
Delivery report ordering

### ISSUE THREAD

**Issue by edenhill** [confluentinc/confluent-kafka-dotnet#19]
It seems that the delivery report callbacks/delegates are called "randomly" on the internal thread pool which results in losing the actual delivery order.

Example, see how offset goes from 7741 back to 7730 and then to 7743.
````
{"topic":"test.net","partition":"2","key":"","value":"44","offset":"7737","name":"producer_send_success","_time":"2017-01-25 13:55:26","_thread":"7"}
{"topic":"test.net","partition":"2","key":"","value":"45","offset":"7738","name":"producer_send_success","_time":"2017-01-25 13:55:26","_thread":"7"}
{"topic":"test.net","partition":"2","key":"","value":"46","offset":"7739","name":"producer_send_success","_time":"2017-01-25 13:55:26","_thread":"7"}
{"topic":"test.net","partition":"2","key":"","value":"49","offset":"7740","name":"producer_send_success","_time":"2017-01-25 13:55:26","_thread":"7"}
{"topic":"test.net","partition":"2","key":"","value":"52","offset":"7741","name":"producer_send_success","_time":"2017-01-25 13:55:26","_thread":"7"}
{"topic":"test.net","partition":"2","key":"","value":"32","offset":"7730","name":"producer_send_success","_time":"2017-01-25 13:55:26","_thread":"12"}
{"topic":"test.net","partition":"2","key":"","value":"53","offset":"7743","name":"producer_send_success","_time":"2017-01-25 13:55:26","_thread":"12"}
{"topic":"test.net","partition":"2","key":"","value":"54","offset":"7744","name":"producer_send_success","_time":"2017-01-25 13:55:26","_thread":"12"}
````

Delivery reports must retain their original order, preferably globally but at least per partition.

**Comment by mhowlett** [comment]
The ProduceAsync variant that has a DeliveryHandler callback parameter should be deterministic (if you're using that and calling of that is not deterministic, this is a problem I didn't know about).

We have the Task based variant as this is so idiomatic (task completion won't be deterministic). I need to put more thought into this than I have right at this minute, but we might be able to make the Task based method ordering deterministic using a custom scheduler or (thread pool with one thread) or something. Regardless of whether this turns out to be a viable solution in practice, it would have been good to think this through that far.

**Comment by edenhill** [comment]
Right, I'm using the Task-based one, should I switch to the callback Produce()?
```
            var deliveryReport = Handle.ProduceAsync(topic, null, value);
            deliveryReport.ContinueWith((result) => HandleDelivery(result.Result));
````

**Comment by edenhill** [comment]
Works much better with the IDeliveryHandler, thanks Matt!

We must make a big bold note of this behaviour in the Task-based Produce API.

**Comment by mhowlett** [comment]
Note: you could also call the Task ProduceAsync method synchronously buy Wait()ing on the task between calls (or by simply accessing the .Result property of the task). Performance will be abysmal though of course. ContinueWith doesn't block.

yep, this needs documenting pretty fully.

**Comment by edenhill** [comment]
You should know better than telling me to use a sync produce interface ;)

**Comment by mhowlett** [comment]
closing this issue. it's core stuff that needs documenting which will be prioritized elsewhere.

**Comment by edenhill** [comment]
I suggest keeping this one open until the documentation is fixed, otherwise it is easy to loose track
