### ISSUE TITLE
Exit abnormally when sending message

### ISSUE THREAD

**Issue by easyboot** [confluentinc/confluent-kafka-dotnet#1903]
Description
===========
I installed kafka under Windows, but kafka will exit abnormally, and my program will terminate abnormally when sending a message to kafka during running. How can I determine whether kafka is connected normally

Description: The process was terminated due to an unhandled exception. Exception Info: Confluent.Kafka.ProduceException`2[System.String,System.Object]: Local: Message timed out at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken) at ImportPIVASData.Kafka.KafkaProducer.SendAsync(String Topic, String Key, String Value) in D:\work\projects\ImportPIVASData\ImportPIVASData\Kafka\KafkaProducer.cs:line 62 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state) at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi) at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state) at System.Threading.QueueUserWorkItemCallback.Execute() at System.Threading.ThreadPoolWorkQueue.Dispatch()

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
You can set the debug config property to "all" to get verbose logging. it might be an issue related to needing to set advertised listeners. note that there are a number of issues running Kafka on Windows and it is not supported. Maybe following the instructions here will get you set up correctly: https://www.confluent.io/blog/set-up-and-run-kafka-on-windows-linux-wsl-2/
