### ISSUE TITLE
1.9.3 breaking change in ISchemaRegistryClient

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [confluentinc/confluent-kafka-dotnet#1908]
Description
===========

[Version 1.9.3](https://github.com/confluentinc/confluent-kafka-dotnet/releases/tag/v1.9.3) of the Confluent.SchemaRegistry package changed method signatures in ISchemaRegistryClient (<https://github.com/confluentinc/confluent-kafka-dotnet/pull/1874>). This change is:

- ✔ Source compatible for callers of ISchemaRegistryClient.
- ⚠ Binary incompatible for callers of ISchemaRegistryClient; see <https://github.com/confluentinc/confluent-kafka-dotnet/issues/1908#issuecomment-1259113620>.
- ⚠ Source incompatible for custom implementations of ISchemaRegistryClient. It broke a custom ISchemaRegistryClient implementation that I use for offline testing; see below.
- ⚠ Binary incompatible for custom implementations of ISchemaRegistryClient. 

Please mark such breaking changes prominently in release notes, and preferably make them only in major versions ([NuGet Package Version Reference](<https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-basics> "NuGet Package Version Reference | Microsoft Learn")).

How to reproduce
================

The following builds OK with Confluent.SchemaRegistry 1.9.2:

```C#
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Confluent.SchemaRegistry;

namespace InterfaceBreakingChange
{
    public sealed class TestingRegistry : ISchemaRegistryClient
    {
        public int MaxCachedSchemas => throw new NotImplementedException();

        public string ConstructKeySubjectName(string topic, string recordType = null)
        {
            throw new NotImplementedException();
        }

        public string ConstructValueSubjectName(string topic, string recordType = null)
        {
            throw new NotImplementedException();
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }

        public Task<List<string>> GetAllSubjectsAsync()
        {
            throw new NotImplementedException();
        }

        public Task<RegisteredSchema> GetLatestSchemaAsync(string subject)
        {
            throw new NotImplementedException();
        }

        public Task<RegisteredSchema> GetRegisteredSchemaAsync(string subject, int version)
        {
            throw new NotImplementedException();
        }

        public Task<Schema> GetSchemaAsync(int id, string format = null)
        {
            throw new NotImplementedException();
        }

        public Task<string> GetSchemaAsync(string subject, int version)
        {
            throw new NotImplementedException();
        }

        public Task<int> GetSchemaIdAsync(string subject, string avroSchema)
        {
            throw new NotImplementedException();
        }

        public Task<int> GetSchemaIdAsync(string subject, Schema schema)
        {
            throw new NotImplementedException();
        }

        public Task<List<int>> GetSubjectVersionsAsync(string subject)
        {
            throw new NotImplementedException();
        }

        public Task<bool> IsCompatibleAsync(string subject, string avroSchema)
        {
            throw new NotImplementedException();
        }

        public Task<bool> IsCompatibleAsync(string subject, Schema schema)
        {
            throw new NotImplementedException();
        }

        public Task<RegisteredSchema> LookupSchemaAsync(string subject, Schema schema, bool ignoreDeletedSchemas)
        {
            throw new NotImplementedException();
        }

        public Task<int> RegisterSchemaAsync(string subject, string avroSchema)
        {
            throw new NotImplementedException();
        }

        public Task<int> RegisterSchemaAsync(string subject, Schema schema)
        {
            throw new NotImplementedException();
        }
    }
}
```

Then upgrade to Confluent.SchemaRegistry 1.9.3, and the build fails:

>Program.cs(8,43,8,64): error CS0535: 'TestingRegistry' does not implement interface member 'ISchemaRegistryClient.RegisterSchemaAsync(string, string, bool)'  
>Program.cs(8,43,8,64): error CS0535: 'TestingRegistry' does not implement interface member 'ISchemaRegistryClient.RegisterSchemaAsync(string, Schema, bool)'  
>Program.cs(8,43,8,64): error CS0535: 'TestingRegistry' does not implement interface member 'ISchemaRegistryClient.GetSchemaIdAsync(string, string, bool)'  
>Program.cs(8,43,8,64): error CS0535: 'TestingRegistry' does not implement interface member 'ISchemaRegistryClient.GetSchemaIdAsync(string, Schema, bool)'  
>Program.cs(8,43,8,64): error CS0535: 'TestingRegistry' does not implement interface member 'ISchemaRegistryClient.LookupSchemaAsync(string, Schema, bool, bool)'  

Alternatively, a runtime exception might be thrown if such a class is built for Confluent.SchemaRegistry 1.9.2 and then used with 1.9.3 without rebuilding.

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
   *Confluent.SchemaRegistry versions 1.9.2 and 1.9.3.*
 - [ ] Apache Kafka version.  
   *Not applicable: The repro does not involve any Kafka server.*
 - [ ] Client configuration.
   *Not applicable: The repro does not create an instance of CachedSchemaRegistryClient.*
 - [X] Operating system.
   *Windows 10 version 21H2.*
 - [X] Provide logs (with "debug" : "..." as necessary in configuration).
   *The compiler errors are included.*
 - [ ] Provide broker log excerpts.
   *Not applicable: The repro does not involve any Kafka server.*
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
we won't revert this, that would probably make the situation worse.

sometimes we accidentally break things, this is one of those cases. we'll remember to put default interface implementations in the future.
