### ISSUE TITLE
'Invalid librdkafka version b06ff, expected at least 10502ff' - dotnet framework 4.8

### ISSUE THREAD

**Issue by TheLarsinator** [confluentinc/confluent-kafka-dotnet#1909]
Description
===========
I am using the latest version of the confluent kafka nuget package (1.9.3) in my dotnet framework 4.8 console application. I am using a producer with the following configuration: 
Debug = "broker,topic,msg" and Acks = Acks.All. 

Occasionally I am getting the error message "Invalid librdkafka version b06ff, expected at least 10502ff". There is no pattern to when my application run successfully and when this error occurs. The error occurs when creating the producer instance. When this error doesnt occur, the application runs as expected, producing kafka messages with the producer.

I have cleared all bin/obj folders, cleared my entire .nuget cache and made sure there is no other librdkafka.dll file present on my machine. 

How to reproduce
================
I am just running a console application with the latest confluent.kafka package (1.9.3) and creating a producer. Its about 50/50 whether the application will run or whether it will crash with a FileLoadException when creating the producer.

**Comment by mhowlett** [comment]
we have not updated the version in that check for a long time (10502ff), though we should have. Have you ever used / referenced a version of Confluent.Kafka below v1.6? it seems like this might be something other than loading an old version of the library errantly. have not come across this before.
