### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by milfordjosh** [confluentinc/confluent-kafka-dotnet#1911]
Question:
===========
Hi, 
I see that there is no security policy listed currently for this project. Is there any such security policy that exists and is being used for this project development?
For example:
https://www.microsoft.com/en-us/securityengineering/sdl/practices
Thanks!

**Comment by mhowlett** [comment]
Confluent has a large security team whose mandate covers the client libraries. The development team interact with them regularly for a variety of purposes, including those listed in the linked to article.
I don't believe we have anything published publicly.
