### ISSUE TITLE
Wrong API documentation

### ISSUE THREAD

**Issue by Arclight3** [confluentinc/confluent-kafka-dotnet#1912]
Description
===========

The documentation for  the```Produce``` methods of the ```https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/IProducer.cs``` interface is wrong.

This is the wrong part: "**Asynchronously** send a single message to a Kafka topic".
There are a few signs that the statement above is wrong.
1. I looked a few levels inside the method implementation (```https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Producer.cs```) up to the ```private void ProduceImpl()...``` function and there is no asynchronous operation.
2. In dotnet we have a best practice to add the "async" suffix to the method name if the method is asynchronous.

Solution
================

Only the ```ProduceAsync``` methods should say that they "Asynchronously send a single message to a Kafka topic".
The synchronous methods should say: "Synchronously send a single message to a Kafka topic" or "Send a single message to a Kafka topic".

**Comment by mhowlett** [comment]
The `produce` method never blocks - the message is send asynchronously to Kafka, with the the result made available out-of-band on the delivery handler if supplied.

**Comment by Arclight3** [comment]
1. I would appreciate if you would explain or show some proof of how it sends the event asynchronously. I tried to find it myself but I found a lot of unsafe code that I am not really familiar with and I hope you can provide more details.

2. In dotnet, an "asynchronous" method should return a ```System.Threading.Tasks.Task```. An action that can be awaited.
This is the first thing a dotnet developer thinks to when they read that a method is "asynchronous".
Also if a method is not returning a Task that can be awaited but it does some magic behind the scenes to not block the current thread doesn't mean it is asynchronous.

These APIs are confusing and misusing the dotnet "asynchronous" terminology..

3. What is the difference between ```Produce()``` and ```ProduceAsync()```? Why are both needed if the first call is also asynchronous?
