### ISSUE TITLE
does Confluent.SchemaRegistry support the schema reference?

### ISSUE THREAD

**Issue by yidi-liu** [confluentinc/confluent-kafka-dotnet#1915]
Description
===========
Trying to consume from topics produced by the 3rd team. They use avro, schema registry with complicated schemas and schema references. When consume from the topic we get exception with InnerException:

InnerException = {"Undefined name: xx.xx.xx.VehicleOrder at 'fields[9].type.items.fields[0].type'"}

where the xx.xx.xx.VehicleOrder is the schema referenced by the topic's value schema.

here is my code section for consumer testing:

            var nextOne = true;
            using (var consumer = new ConsumerBuilder<GenericRecord, GenericRecord>(consumerConfiguration)
           .SetKeyDeserializer(new AvroDeserializer<GenericRecord>(registryClient).AsSyncOverAsync())
           .SetValueDeserializer(new AvroDeserializer<GenericRecord>(registryClient).AsSyncOverAsync())
           .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}")).Build())
            {
                consumer.Subscribe(consumerTopic);
                while (nextOne)
                {
                    try
                    {
                        var consumerResult = consumer.Consume(cts.Token);
                        Console.WriteLine(consumerResult.Message.Key);
                        Console.WriteLine(consumerResult.Message.Value);
                    }
                    catch (Exception ex)
                    {
                        var message = ex.Message;
                    }
                    if (i++ > 5) nextOne = false;
                }
            }

we are able to consume the same topic with <string, string>
it seems schema reference issue was fixed: https://github.com/confluentinc/schema-registry/issues/426
But wondering if the dotnet package include this fix?  or how should we deserialize the avro value we consume.

Thanks.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
Avro schema references aren't yet support by the .NET client.

**Comment by jeffreyjjenningsacertus** [comment]
Hi, Matt,

When on Confluent's roadmap is it planning to support Avro schema references in .Net?

**Comment by belint01** [comment]
What about resolving references on schema registry side ? Would be much easier to add support for given client

**Comment by meisterm** [comment]
What is the workaround to use referenced schemas?

**Comment by Hanskrogh** [comment]
Is this still not supported?
