### ISSUE TITLE
AdminClient missing DeleteConsumerGroupOffsets

### ISSUE THREAD

**Issue by taspeotis** [confluentinc/confluent-kafka-dotnet#1919]
Description
===========

I'd like my code to be able to "migrate" topics from one consumer group to the next, and then clean up the migrated topics from the old consumer group.

I believe [`deleteConsumerGroupOffsets`](https://cwiki.apache.org/confluence/display/KAFKA/KIP-496%3A+Administrative+API+to+delete+consumer+offsets#KIP496:AdministrativeAPItodeleteconsumeroffsets-AdminClient) (also [here](https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/admin/Admin.html#deleteConsumerGroupOffsets-java.lang.String-java.util.Set-org.apache.kafka.clients.admin.DeleteConsumerGroupOffsetsOptions-)) could achieve this, but it's not exposed in the .NET library.

How to reproduce
================

1. Install NuGet Packge

2. Look at `Confluent.Kafka.IAdminClient` interface

3. ???

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
not implemented yet. tracking in #1655
