### ISSUE TITLE
Messages skipped by consumer after broker problem

### ISSUE THREAD

**Issue by qed-** [confluentinc/confluent-kafka-dotnet#192]
Using Confluent.Kafka 0.9.5. We have a consumer with callbacks set up to log Error, ConsumeError, PartitionAssigned and PartitionRevoked and Message events. Offsets are being manually committed.

We first saw some timeout problems at the broker as follows, there are some corresponding broker errors at that time which imply the leader changed:

13:27:01,034 ERROR Kafka error: Local_MsgTimedOut: kafka-prod01-01.xxx.com:9092/1: 1 request(s) timed out: disconnect (average rtt 97.563ms)
13:27:02,049 INFO Revoked partitions: TopicName [0]
13:27:09,909 INFO Revoked partitions: TopicName [0]
13:27:10,018 INFO Revoked partitions: TopicName [0]
13:27:10,737 INFO Received message
13:27:10,737 INFO Received message
13:27:22,472 ERROR Kafka error: Local_MsgTimedOut: kafka-prod01-01.xxx.com:9092/1: 1 request(s) timed out: disconnect (average rtt 97.568ms)
13:27:23,488 INFO Revoked partitions: TopicName [0]
13:27:37,660 INFO Revoked partitions: TopicName [0]
13:27:39,004 INFO Revoked partitions: TopicName [0]

The revoked partitions callback was then invoked continuously every two seconds indefinitely, until we eventually restarted the consumer process. It did however continue to receive most messages.

More worryingly, messages were sporadically skipped while it was in this state. They were in the topic but missed by the consumer. The topic has a single partition, and despite the revoked message the consumer still continued to receive most messages. There was no partition assigned callback until after the process was restarted.

We will start running with debug logs enabled in case we see this again, that's all the information we have at the moment.

**Comment by treziac** [comment]
Do you call Unassign on PartitionRevoked?

**Comment by qed-** [comment]
No.. thanks, I guess that's it.
