### ISSUE TITLE
Delivery handler callback ordering guarantees for idempotent producer

### ISSUE THREAD

**Issue by tukaef** [confluentinc/confluent-kafka-dotnet#1922]
According to the [docs](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#guarantees), for idempotent producers, it is guaranteed that messages are written to the log in the same order as they were produced.

Is the same guaranteed for delivery handler callback invocation? 

I. e. if I produce a sequence of messages e. g. `1, 2, 3, 4, 5`, will the callback be called first for message `1`, then for message `2`, and so on?

**Comment by mhowlett** [comment]
yes (for `Produce`).

In the `ProduceAsync` case, you may need to be a bit careful with threads.

**Comment by tukaef** [comment]
Great, thank you!
