### ISSUE TITLE
How do we change topic partition count using this library

### ISSUE THREAD

**Issue by gojanpaolo** [confluentinc/confluent-kafka-dotnet#1923]
Hello, how do we change the topic's partition count using this library?

We use this library to create our topics using `IAdminClient.CreateTopicsAsync`. There seems to be a `IAdminClient.AlterConfigsAsync` but we're not sure how to use that and if that can change the partition count.

Thanks!

**Comment by mhowlett** [comment]
`CreatePartitionsAsync`
