### ISSUE TITLE
Question:  Can i use a certificate from the windows certificate store for my SSL secure topic connection

### ISSUE THREAD

**Issue by zlsmith86** [confluentinc/confluent-kafka-dotnet#1933]
Description
===========
Is there a way to use a certificate from the windows certificate store instead of a PEM file on the local machine when connecting to a secure topic?

How to reproduce
================
NA

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
I believe that librdkafka can only use certificate stores for CA certs.

**Comment by cdhunt** [comment]
This library can read the certificates and pass the bytes to libradkafka via [`rd_kafka_conf_set_ssl_cert()`](https://github.com/confluentinc/librdkafka/blob/c5260738670b6a06429b26e4d5a86fda8925ac7e/src/rdkafka_cert.c#L443).

https://github.com/confluentinc/librdkafka/discussions/3819
