### ISSUE TITLE
Cannot consume messages with SSL Security

### ISSUE THREAD

**Issue by F3rrY** [confluentinc/confluent-kafka-dotnet#1937]
Description
===========
I set up this config with SSL for consume a topic with a C# Project.

```
var config = new ConsumerConfig
{
    ClientId = Guid.NewGuid().ToString(),
    GroupId = Guid.NewGuid().ToString(),
    BootstrapServers = Configuration.GetValue<string>("KafkaQueueConfiguration:BootstrapServer"),
    SecurityProtocol = SecurityProtocol.Ssl,
    SslCertificateLocation = Configuration.GetValue<string>("KafkaQueueConfiguration:PathToCertificatePem"),
    AutoOffsetReset = AutoOffsetReset.Earliest
};
```

And when I try to build the consumerbuilder

```
using (var consumer = new ConsumerBuilder<Ignore, string>(config).Build())
{
    consumer.Subscribe("topic");
    var result = consumer.Consume(new CancellationTokenSource().Token);
}
```
He gives me and exception with the error:

> ssl.certificate.location failed: error:140DC009:SSL routines:use_certificate_chain_file:PEM lib

The certificate PEM starts with "-----BEGIN RSA PRIVATE KEY-----"

The Confluent.Kafka nuget version is 1.9.3

What's the problem?

**Comment by edenhill** [comment]
Seems like you are passing your private key to SslCertificateLocation - which should be your public key.
The private key goes in SslKeyLocation.

**Comment by F3rrY** [comment]
Yeah, that's right, after create the issue I made a change and now I can consume...

Thanks and sorry for the question :)
