### ISSUE TITLE
Settings offsets when using subscribe

### ISSUE THREAD

**Issue by kcnguyen82** [confluentinc/confluent-kafka-dotnet#194]
Hi all,

I want to change the offsets of my kafka consumer (to a particular set of offsets, not just to the beginning or end.) when I am using the subscribe call with multiple threads without having to use a new consumer group id every time. I can use assign perfectly fine to change my offsets but I am limited to just one thread. Is there anyway to change my offsets when using subscribe so that I can take advantage of the load balanced consumer?

Thanks in advance!

**Comment by mhowlett** [comment]
add a handler to `OnPartitionsAssigned` and set the offsets in the call to `Assign`. In the AdvancedConsumer demo the offsets are not explicitly set here, but you can do this.

**Comment by kcnguyen82** [comment]
we added a handler to OnPartitionsAssigned that updates only offsets of the partitions assigned to our consumer thread to the offset we wanted to move it to. It looks to be working fine until the rebalance_cb triggers another partition assignment event and then our handler is called. I can see our consumer threads rereading data after this. We have tried to make the custom handler run the custom assignment code only once when it first assigns using a flag, thinking the rereading behavior we are seeing is caused by the custom offsets overwriting the current offsets every time the on partition assigned handler is fired.

Does this sound correct? Our end goal is to assigned to our load balanced consumer threads to distinct custom offsets any where in the queue and continue to move forward from there instead of rereading data?

**Comment by treziac** [comment]
I don't quite understand your needs. Could you elaborate on what you try to achieve (how many consumers in the group, what you want to read, how you commit offsets...)
If you want to consume from a specified offset, perhaps you should use Assign rather than Subscribe

**Comment by kcnguyen82** [comment]
I’ve a multiple threads that share the same group.id the expectation to load balanced the consumer between the different threads.  Although we do the Assign as suggested in the OnPartitionsAssigned, we are still seeing duplicate read, the same partition / offset is read multiple times from different threads.

**Comment by mhowlett** [comment]
> We have tried to make the custom handler run the custom assignment code only once when it first assigns using a flag, thinking the rereading behavior we are seeing is caused by the custom offsets overwriting the current offsets every time the on partition assigned handler is fired.

yep, that's what happens. when you get a new assignment, you need to specify where the consumer will start reading from for all partitions in the assignment (or let librdkafka work it out for you - it'll use either the last committed offsets if they exist or the offset as determined by `auto.offset.reset` if not).

note that a consumer is relatively heavy weight. rather than have more than one consumer in a process, it's usually better to have one consumer and spawn off work to thread pool threads. this may complicate offset management, but you may also want to be using a dead letter queue, which may mitigate that (i don't quite understand your use case).
