### ISSUE TITLE
Something ablout Kafka  ACK

### ISSUE THREAD

**Issue by huangmq-code** [confluentinc/confluent-kafka-dotnet#1941]
Description  How to  use the ACK，i use ACKs=Acks.All. The program skip the ACK and return set message true.How to deal it?
===========

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
unfortunately, i don't understand the question. using Acks.All will instruct the cluster to ensure the message has been replicated to all insync replicas before responding to the producer -> producer creates the delivery report.
