### ISSUE TITLE
Partitions auto-revoked and re-assigned if too much consumers with the same GroupId

### ISSUE THREAD

**Issue by Dionisos94** [confluentinc/confluent-kafka-dotnet#1945]
Description
===========
Hello,
I have just upgraded the Confluent.Kafka library from v0.11.3 to v1.9.3 on my app.

I noticed a strange behavior that did not happen before and I would like to check if that is expected.To make it simple, my app creates 40 consumers that all consume 1 separate Kafka Topic with only 1 partition each.

All consumers have the same groupId.When I launch my app, all consumers subscribe to their topic and start consuming. However, I noticed that if some consumers are already in “partition assigned” and another one is subscribing/consuming, then all consumers are “partition revoked” and assigned again.I am not very familiar with the concept of Rebalancing in Kakfa, but could that been the case that if there is too much consumer on the same group, a rebalancing occurs, causing each consumer from the group to revoke its topic before assigning it again?

If it’s the case, should I do something to avoid this behavior or should I just let it happen ?
This behavior does not happen when I launch only few consumers or when I put a different groupId for each consumer.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/15048957/202679734-274882a2-5bb2-417c-bccc-8877785be876.png">

How to reproduce
================
I prefer not to share my code for now.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version : v1.9.3
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system. Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue : no

**Comment by mhowlett** [comment]
> All consumers have the same groupId.

since you are not using consumers to cooperatively consume from the one topic, there is only downside, no upside to doing this (because every time a consumer joins or leaves the group this is a stop-the-world operation). use a different group id for each consumer.

also, you do not need to use subscribe (which brings the consumer group into play) - just directly assign to the topic/partition of interest.

**Comment by Dionisos94** [comment]
Thank you @mhowlett !
After reading about Rebalancing, your answer makes total sense.
