### ISSUE TITLE
AdminClient API for deleting consumer groups

### ISSUE THREAD

**Issue by undrivendev** [confluentinc/confluent-kafka-dotnet#1948]
Hello,
is there an API exposed by the AdminClient to perform the 'delete consumer groups' operation as described in the [official docs](https://kafka.apache.org/documentation.html#basic_ops_consumer_group)?

Having the Kafka binaries installed, it would be analogous to the command:
`bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --delete --group my-group --group my-other-group`

which relies on the implementation of the Java Admin client [here](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L3413).

Thanks.

**Comment by anchitj** [comment]
Please check [`DeleteGroupsAsync`](https://github.com/confluentinc/confluent-kafka-dotnet/blob/fa7626c49fc5955a82db276d199b73361a739e16/src/Confluent.Kafka/IAdminClient.cs#L117) API.
