### ISSUE TITLE
Consumer group session timed out Confluent.Kafka 1.6.3 

### ISSUE THREAD

**Issue by Seamless2014** [confluentinc/confluent-kafka-dotnet#1950]
Hi. 
I use Confluent.Kafka In My .net Core project.
I come across always this problem like this: Consumer group session timed out (in join-state steady) after 10328 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
can you find the reason?
Thanks

1.6.3
Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.  -----Confluent.Kafka 1.6.3
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.-----windows server 2016 Standard
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

%4|1669773880.096|SESSTMOUT|rdkafka#consumer-4| [thrd:main]: Consumer group session timed out (in join-state steady) after 10112 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
%4|1669773892.104|SESSTMOUT|rdkafka#consumer-4| [thrd:main]: Consumer group session timed out (in join-state steady) after 10104 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
%5|1669773894.599|REQTMOUT|rdkafka#consumer-4| [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out HeartbeatRequest in flight (after 10494ms, timeout #0)
%4|1669773894.599|REQTMOUT|rdkafka#consumer-4| [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1669773894.600|FAIL|rdkafka#consumer-4| [thrd:GroupCoordinator]: GroupCoordinator: 123.60.2.67:9092: 1 request(s) timed out: disconnect (after 441382ms in state UP)
%3|1669773894.605|ERROR|rdkafka#consumer-4| [thrd:app]: rdkafka#consumer-4: GroupCoordinator: 123.60.2.67:9092: 1 request(s) timed out: disconnect (after 441382ms in state UP)
%3|1669773915.620|FAIL|rdkafka#consumer-4| [thrd:GroupCoordinator]: GroupCoordinator: 123.60.2.67:9092: Connect to ipv4#123.60.2.67:9092 failed: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.. (after 21014ms in state CONNECT)
%3|1669773915.620|ERROR|rdkafka#consumer-4| [thrd:app]: rdkafka#consumer-4: GroupCoordinator: 123.60.2.67:9092: Connect to ipv4#123.60.2.67:9092 failed: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.. (after 21014ms in state CONNECT)
%4|1669773933.517|SESSTMOUT|rdkafka#consumer-3| [thrd:main]: Consumer group session timed out (in join-state steady) after 10153 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
%5|1669773935.631|REQTMOUT|rdkafka#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out HeartbeatRequest in flight (after 10151ms, timeout #0)
%4|1669773935.631|REQTMOUT|rdkafka#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1669773935.632|FAIL|rdkafka#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator: 123.60.2.67:9092: 1 request(s) timed out: disconnect (after 482416ms in state UP)
%4|1669773961.843|SESSTMOUT|rdkafka#consumer-3| [thrd:main]: Consumer group session timed out (in join-state steady) after 10078 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
%4|1669773998.016|SESSTMOUT|rdkafka#consumer-3| [thrd:main]: Consumer group session timed out (in join-state steady) after 10328 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
%5|1669773998.748|REQTMOUT|rdkafka#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out HeartbeatRequest in flight (after 10756ms, timeout #0)
%4|1669773998.748|REQTMOUT|rdkafka#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1669773998.754|FAIL|rdkafka#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator: 123.60.2.67:9092: 1 request(s) timed out: disconnect (after 63111ms in state UP, 1 identical error(s) suppressed)
%5|1669774012.807|REQTMOUT|rdkafka#consumer-5| [thrd:123.60.2.67:9092/bootstrap]: 123.60.2.67:9092/0: Timed out MetadataRequest in flight (after 60652ms, timeout #0)
%4|1669774012.807|REQTMOUT|rdkafka#consumer-5| [thrd:123.60.2.67:9092/bootstrap]: 123.60.2.67:9092/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1669774012.808|FAIL|rdkafka#consumer-5| [thrd:123.60.2.67:9092/bootstrap]: 123.60.2.67:9092/0: 1 request(s) timed out: disconnect (after 559593ms in state UP)

**Comment by anchitj** [comment]
I can see from your logs that the broker at `123.60.2.67:9092` is unreachable which must be the reason for this.
