### ISSUE TITLE
Bug: asserting an interface and using non-interface members

### ISSUE THREAD

**Issue by AlexeyRaga** [confluentinc/confluent-kafka-dotnet#1958]
https://github.com/confluentinc/confluent-kafka-dotnet/blob/376a3250c06f347c6492e90b9921f55eec7a5676/src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs#L54-L57

I think that this must be a bug.
The code asserts `ISpecificRecord` but then goes and reads some random field on the type that has nothing to do with the interface. Which is not really correct conceptually, and doesn't work with all types that legally implement `ISpecificRecord` but do not expose that field.

Since the deserialiser already requires a parameterless constructor, maybe it'd be cleaner to once create an empty instance of the type and read `ISpecificRecord.Schema` from it? (this is what `Protobuf` does).

**Comment by AlexeyRaga** [comment]
I noticed that the Serialiser is doing the same, which is a subject of the same bug:

https://github.com/confluentinc/confluent-kafka-dotnet/blob/376a3250c06f347c6492e90b9921f55eec7a5676/src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs#L124-L127

**Comment by anchitj** [comment]
Addressed in #1961. Closing.
