### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#196]
What other serializers are offered by default besides string serializer? Also, is there a native JSON serializer option available.

**Comment by mhowlett** [comment]
List of existing serializers is here:
https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/src/Confluent.Kafka/Serialization

Only basic ones so far. We don't have any good generic serializers yet. We are working on Avro first (in progress) with schema registry integration.

The serializer interface is pluggable - it's easy to write your own.
