### ISSUE TITLE
Veracode scan reports openssl vulnerability (librdkafka dependency on ibssl.so.1.0.0)

### ISSUE THREAD

**Issue by saheerabbas1** [confluentinc/confluent-kafka-dotnet#1966]
Description
===========

Vercode scan of the build package flags openssl vulnerability related to version 1.0.0
Please advice how to mitigate this issue

How to reproduce
================
1. Build the solution (built using .net 6 in VS 2022)
2. Confluent kafka version 1.8.2
3. The build generates the following files in bin\Debug\net6.0\runtimes\linux-x64\native folder - alpine-librdkafka.so, centos6-librdkafka.so, centos7-librdkafka.so and librdkafka.so
4. Do a veracode scan of the entire package.
5. The scan reports an issue related to libssl.so.1.0.0 file used by librdkafka.so
![openssl_issue1](https://user-images.githubusercontent.com/83164865/208127802-cc9951df-dc3a-4faa-a77c-b18d5565bfb1.PNG)
![openssl_issue2](https://user-images.githubusercontent.com/83164865/208127804-cafaf08d-1396-49f0-a17b-6e1793468824.PNG)

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
The upcoming v2.0.0 release will ship with OpenSSL 3.0.7

**Comment by saheerabbas1** [comment]
> The upcoming v2.0.0 release will ship with OpenSSL 3.0.7

**Comment by saheerabbas1** [comment]
Expected v2 release date?

**Comment by edenhill** [comment]
mid jan

**Comment by jhonambrad** [comment]
@edenhill We also encountered this issue. Is libssl.so.1.0.0 actually being used? or whatever version of openssl we have installed?
