### ISSUE TITLE
Is support Kafka 3.3?

### ISSUE THREAD

**Issue by CwjXFH** [confluentinc/confluent-kafka-dotnet#1976]
[This document](https://cwiki.apache.org/confluence/display/KAFKA/Clients#Clients-.NET) says confluent-kafka-dotnet support Kafka 0.8.x, 0.9.x, 0.10.x, 0.11.x. 
![企业微信截图_16732353818948](https://user-images.githubusercontent.com/11468733/211237199-9226dc83-8a2d-4c4a-b3e2-f3a484dc0620.png)

Does confluent-kafka-dotnet support other Kafka versions, like 3.3?

**Comment by Xor-el** [comment]
@CwjXFH  been using it with version 3.3 and it works great.

**Comment by OneCricketeer** [comment]
Anything that says 0.11, generally means that and higher since the basic client API hasn't had breaking changes since then
