### ISSUE TITLE
Is where another way to send heartbeats to the server?

### ISSUE THREAD

**Issue by alewmt** [confluentinc/confluent-kafka-dotnet#1977]
Hi! I may have situations in which there are delays in processing read messages, and I need to inform the broker that the client is alive without calling the Consume method. Now I get "Application maximum poll interval (300000ms) exceeded". Something like described here https://www.marionzualo.com/2019/08/10/always-manually-send-heartbeats-when-processing-message-batches-in-ruby-kafka/

**Comment by RZProf** [comment]
I think in your case you should process kafka messages with another thread and call pause() method on consumer to do not face with max interval error

**Comment by anchitj** [comment]
@alewmt You can try changing the `MaxPollIntervalMs` according to your use case.
