### ISSUE TITLE
Consuming and Producing at the same time

### ISSUE THREAD

**Issue by TonyGerace** [confluentinc/confluent-kafka-dotnet#198]
I have a consumer that depending on the message will possibly need to produce a message. Every time we need to produce we try to create and dispose of the produce with a using statement. However the producer under this scenario is never disposed of. My guess is because of the consumer holding on to something the producer is trying to dispose. Should we be newing up a producer every time we need to produce or should we keep it open for the life of the consumer?

**Comment by mhowlett** [comment]
Unless you're producing very infrequently, I wouldn't create/dispose the producer - just create it once and dispose on application exit.

Can you say more specifically what you mean by 'never disposed of'?

The producer and consumer will operate independently - they shouldn't interfere with each other.

**Comment by TonyGerace** [comment]
We have a small wrapper library around the Producer that lets us abstract away and replace it with an in memory solution or some other tech but basically this is the class before I switch it to keep the producer open. What I have noticed is that when we call our SendAsync method in this fashion while also consuming the Producer here is never disposed of. The "Confluent Start/Confluent End" are both written to console but "Disposed" is not. I am switching the code in this library today to keep the Producer open.

```
public class KafkaProducer : IProducer
    {
        private readonly Dictionary<string, object> _config;
        ILogger Logger { get; } = ApplicationLogging.CreateLogger<KafkaProducer>();

        public KafkaProducer(
            params string[] bootstrapServers)
        {
            Logger.LogDebug($"Constructing {nameof(KafkaProducer)}");
            var servers = string.Join(", ", bootstrapServers);

            Logger.LogDebug($"Creating local producer for servers: {servers}");
            _config = new Dictionary<string, object> {{"bootstrap.servers", servers}};
        }

        public async Task SendAsync(string topicName, string message)
        {
            using (var producer = new Producer<Null, string>(_config, null, new StringSerializer(Encoding.UTF8)))
            {
                Console.WriteLine("Confluent Start");
              
                await producer.ProduceAsync(topicName, null, message);

                Console.WriteLine("Confluent End");

                producer.Flush();
            }
            Console.WriteLine("Disposed");
        }
    }
```

**Comment by treziac** [comment]
Yes, this is a known bug, see #180 
Basically we are messing with threads. For now, you can call Task.Yield before producer.Flush to quickly fix this

Note that creating a Producer for each produceAsync is a killer perf. You should create a single instance in your process (here in KafkaProducer class) (it's thread safe). Also, no need to flush then - this is to be done only when you need to be sure all requests are complete, before disposing the producer for example (your KafkaProducer class should be IDisposable in this case)

**Comment by TonyGerace** [comment]
Is it a performance killer in the code or for Kafka? IE - we have a lot of services that might produce to Kafka. Would it be better to have one service to produce to Kafka and all other services call that? Or Each create their own Producer?

**Comment by treziac** [comment]
Both - if you create a producer on each request, you will create connexion to all brokers. If you have  thousands of request by second, ths make a lot of open/close connection for nothing

One producer by service is fine :) Basically you are looking at one producer instance by process

**Comment by TonyGerace** [comment]
I appreciate the fast and informative responses. You guys are awesome.
