### ISSUE TITLE
Unexpected 300s timeout behavior around kafka publisher

### ISSUE THREAD

**Issue by sarudak** [confluentinc/confluent-kafka-dotnet#199]
Using only some slight modification to the producer sample I am getting some fairly strange behavior.  Message timeout seems to take 300s and does not appear to retry. The only setting I saw that defaulted to 300s was message.timeout.ms which seems a reasonable setting to control this behavior. However changing it seems to have no effect on the timeout.

            string topicName = "Test";

            var config = new List<KeyValuePair<string, object>>
            {
                new KeyValuePair<string, object>("message.send.max.retries", "5"),
                new KeyValuePair<string, object>("retry.backoff.ms", "5000"),
                new KeyValuePair<string, object>("message.timeout.ms", "7000"),
                new KeyValuePair<string, object>("topic.metadata.refresh.interval.ms", "4000"),
                new KeyValuePair<string, object>("bootstrap.servers", "notarealurl.kafka.com:9092")
            };
            using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
            {
                Console.WriteLine($"{producer.Name} producing on {topicName}. q to exit.");
                producer.OnError +=
                    (obj, e) =>
                    {
                        Console.WriteLine(string.Format("There was an error! Message was {0}", e.Reason));
                    };

                string text;
                while ((text = Console.ReadLine()) != "q")
                {
                    var deliveryReport = producer.ProduceAsync(topicName, null, text);
                    deliveryReport.ContinueWith(task =>
                    {
                        Console.WriteLine($"Partition: {task.Result.Partition}, Offset: {task.Result.Offset}");
                    });
                }

                // Tasks are not waited on synchronously (ContinueWith is not synchronous),
                // so it's possible they may still in progress here.
                producer.Flush();
            }

**Comment by mhowlett** [comment]
socket.timeout.ms = 60s socket.timeout.ms * message.send.max.retries = 300s - ?
