### ISSUE TITLE
Access violation Exception thrown in consume method after consumer object is disposed

### ISSUE THREAD

**Issue by ksdvishnukumar** [confluentinc/confluent-kafka-dotnet#1997]
Description & How to reproduce
=======================
Hi,
I use .Net core 6 to connect to kafka using Confluent Kafka Library with1.9.3 version.
I used hosted service to create a kafka clients (Consumer and Producer). 
Hosted service uses StartAsync and StopAysc.
StartAsync method have logic to create a Kafka Consumer and Producer client.
StopAsync method have logic to dispose the Kafka Consumer and producer clients.

StartAsync has a method to consume the message from subscribed topic in a while loop.
StopAsync method to dispose the client.

Both of the method shares the same cancellation token using CancellationTokenSource.Token. 
While stopping the application, we use CancellationTokensource Cancel method to notify consumer to stop the processing.

To consume the message we use the Consume(cancellationToken) method.

In the above case am seeing the Access violationException is thrown in the consume method.

I have gone through the Consume Method ideally it should through the ObjectDisposedException. But i did not get that. Even i tried with latest 2.0.2 version. Still the same.

I use the custom config model to map to the respective kafka configuration.

Below are the Consumer configuration
![image](https://user-images.githubusercontent.com/9166122/218003336-43320a04-a349-499a-8448-996464fb0926.png)

Producer Configuration
![image](https://user-images.githubusercontent.com/9166122/218003177-c5b6f22a-254b-4ec2-add7-65acc5e4fbce.png)

Exception:
We use a wrapper around the Consume method
![image](https://user-images.githubusercontent.com/9166122/218003862-9593a723-31ed-478c-8ec2-078b1c527ec5.png)

Checklist
=========

Please provide the following information:
 - [ ] Confluent.Kafka nuget version -1.9.3
 - [ ] Apache Kafka version - 3.1.0
 - [ ] Client configuration.
 - [ ] Windows 10 and K8s .

**Comment by anchitj** [comment]
We have an example in the client of a consumer as an IHostedService. You can refer that https://github.com/confluentinc/confluent-kafka-dotnet/blob/68e76dd319014381387bef38460dd89ad8e4281f/examples/Web/RequestTimeConsumer.cs
