### ISSUE TITLE
SchemaRegistryException error code 40301 using protobuf

### ISSUE THREAD

**Issue by fgaravaglia** [confluentinc/confluent-kafka-dotnet#1999]
Description
===========
Publishing a message on topic using Protobuf and schema registry, we got the following error:

**Confluent.SchemaRegistry.SchemaRegistryException: user is denied operation Write on Subject: google/protobuf/timestamp.proto; error code: 40301**

the schema used for protobuf is referencing obviously google definition for some item such timestamp.
Is it possible to reference external schema?

**Comment by anchitj** [comment]
@fgaravaglia Yes, it's possible to reference external schema. Please refer this example in the client for reference https://github.com/confluentinc/confluent-kafka-dotnet/blob/f45e6a39fb3bf054770fbccd67ec5c42a7e43b9b/test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Protobuf/ProduceConsumeExternalRef.cs#L25.
