### ISSUE TITLE
How can I read the latest messages on a topic?

### ISSUE THREAD

**Issue by fadfood** [confluentinc/confluent-kafka-dotnet#200]
I am using QueryWatermarkOffsets on a consumer so I can get the highest (latest) offset but I get an error "Broker: Leader not available".

Plus, we need more docs other than the samples..

**Comment by mhowlett** [comment]
sounds like either your kafka cluster is not running/reachable or you're configured bootstrap.servers incorrectly.

**Comment by fadfood** [comment]
Kafka cluster is fine and I can run a consumer in cmd. 

If I use a timeout say 2 seconds then QueryWaterMarkOffsets works as expected.
