### ISSUE TITLE
"Unexpected eof while reading" error log thrown from internal librdkafka

### ISSUE THREAD

**Issue by RefaelP23** [confluentinc/confluent-kafka-dotnet#2016]
Description
===========
We recently upgraded to the latest NuGet version: 2.0.2 and then started noticing intermittent warning and error logs thrown to the Log(Error)Handler:

`[thrd:ssl://kafka-host-1]: ssl://kafka-host-1:9093/3: Receive failed: ssl/record/rec_layer_s3.c:321:ssl3_read_n error:0A000126:SSL routines::unexpected eof while reading (after 734729026ms in state UP)`

The time "in state UP" varies but it's usually in the range of 3-8 days.
Now we suspect that this might have something to do with the upgrade to OpenSSL 3 (https://github.com/openssl/openssl/issues/18866#issuecomment-1194219601) but we don't really know.

We're using certificates to authenticate between clients and brokers.
The only configuration we changed is `SslEndpointIdentificationAlgorithm="None"` to restore the previous behavior (per the librdkafka release notes).
We're using Strimzi to manage our Kafka cluster on k8s.
Our broker versions are 2.8, and their configuration hasn't changed.

Looking at the broker logs we noticed these:
`ERROR [SslTransportLayer channelId=5 key=channel=java.nio.channels.SocketChannel[connection-pending remote=kafka-host-2/<IP>:9091], selector=sun.nio.ch.EPollSelectorImpl@71452035, interestOps=8, readyOps=0] Renegotiation requested, but it is not supported, channelId 5, appReadBuffer pos 0, netReadBuffer pos 0, netWriteBuffer pos 160 handshakeStatus NEED_WRAP (org.apache.kafka.common.network.SslTransportLayer) [ReplicaFetcherThread-0-5]`

They don't usually coincide with the client logs, but they are also intermittent.

We haven't noticed any real issues but we these errors trigger alerts and we're wondering if there's something we need to change or just ignore it as unharmful.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka NuGet version: 2.0.2
 - [X] Apache Kafka version: Strimzi baked image - [kafka:0.27.1-kafka-2.8.0](http://quay.io/strimzi/kafka:0.27.1-kafka-2.8.0)
 - [ ] Client configuration.
 - [ ] Operating system.
 - [X] Provide logs (with "debug" : "..." as necessary in configuration).
 - [X] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by connorstorer-kbxcom** [comment]
This looks to be resolved in [2.3.0](https://github.com/confluentinc/confluent-kafka-dotnet/releases/tag/v2.3.0). I did not test 2.1.0, 2.2.0.

**Comment by anchitj** [comment]
Yes, this is fixed in 2.3.0.
