### ISSUE TITLE
Server certificate validation broken after upgrade from 1.9.3 to 2.0.2

### ISSUE THREAD

**Issue by gimik17** [confluentinc/confluent-kafka-dotnet#2022]
Description
===========
After upgrading confluent kafka nuget from 1.9.3 to 2.0.2 broker certificate validation fails with the following message:

[thrd:sasl_ssl://XXX:9093/bootstrap]: sasl_ssl://XXX:9093/bootstrap: SSL handshake failed: error:0A000086:SSL routines::certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (add broker's CA certificate to the Windows Root certificate store) (after 21ms in state SSL_HANDSHAKE)

Client Plattform is: net472 / x86
Broker: 5.4.0

How to reproduce
================
User consumer config:

```
SecurityProtocol = SaslSsl,
EnableSslCertificateVerification = true,
SslCaLocation = "c:\pathto\kafka.client.truststore.cer.pem",
```

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [2.0.2 ] Confluent.Kafka nuget version.
 - [5.4.0] Apache Kafka version.
 - [ ] Client configuration.
 - [ windows server 2016] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by TheStripe** [comment]
Same Issue!

**Comment by ahickey-sfdc** [comment]
+1

**Comment by samjegal** [comment]
+1

**Comment by tsawyer999** [comment]
I'm in the gang! Same issue!

**Comment by tsawyer999** [comment]
Did someone find a workaround?
