### ISSUE TITLE
SSL verification failed on 2.0.2 version

### ISSUE THREAD

**Issue by deepakbhise28** [confluentinc/confluent-kafka-dotnet#2028]
Description
===========
*.cer and *.key is working on 1.9.3 version whereas same cert is failing on version 2.0.2

Error
:SSL routines::certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed 

How to reproduce
================

Producer config 
 "KafkaTopic": "topic name",  
    "BootstrapServers": "broker list",
    "EnableSslCertificateVerification": true,
    "EnableDeliveryReports": false,
    "SslKeyLocation": "path k.key",
    "SslCertificateLocation": "path c.cer",
    "SecurityProtocol": "Ssl"

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 2.0.2
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by phy2000** [comment]
Release 2.x deprecates TLS 1.0 and 1.1.

**Comment by anchitj** [comment]
Closing as this was expected with 2.x release. Please check https://github.com/confluentinc/librdkafka/releases/tag/v2.0.0
