### ISSUE TITLE
Question - Is Consume thread safe?

### ISSUE THREAD

**Issue by podprad** [confluentinc/confluent-kafka-dotnet#2033]
I see some discussions here saying that Kafka is thread safe.
https://github.com/confluentinc/confluent-kafka-dotnet/issues/1732
https://github.com/confluentinc/confluent-kafka-dotnet/issues/119
https://github.com/confluentinc/confluent-kafka-dotnet/issues/103

Native library doc says "The API is completely thread-safe and the calling application may call any of the API functions from any of its own threads at any time."
https://docs.confluent.io/2.0.0/clients/librdkafka/INTRODUCTION_8md.html

This blog post says "When implementing a multi-threaded consumer architecture, it is important to note that the Kafka consumer is not thread safe. Multi-threaded access must be properly synchronized, which can be tricky. This is why the single-threaded model is commonly used."
https://www.confluent.io/blog/kafka-consumer-multi-threaded-messaging/

Which of the facts is true?
I'm using Confluent.Kafka and librdkafka.redist both in version 1.7.0.

In my code I have one consumer instance and multiple threads that might call `ConsumeResult<TKey, TValue> Consume(int millisecondsTimeout);` method in the same time.

**Comment by anchitj** [comment]
For librdkafka specifically Consume is thread safe.
