### ISSUE TITLE
Request: Expose AddBrokers API

### ISSUE THREAD

**Issue by yousifh** [confluentinc/confluent-kafka-dotnet#204]
I have a setup where my app connects to bunch of Kafka brokers running in Docker containers. Given nature of Docker, the IPs of those brokers can change when they restart or servers change. Now librdkafka is able to handle partial failures/changes in the topology of the Kafka cluster. However there is a case where all IPs of the brokers change completely. My app can discover those new IPs separately, however I have no way of telling librdkafka about those new brokers since it can't auto-discover them now. 

Based on this issue here (https://github.com/edenhill/librdkafka/issues/1073) it's suggested to use `rd_kafka_brokers_add()` This method is available in `SafeKafkaHandle` in `AddBrokers()` however it's not available to the producer or consumer. 

This is a feature request asking if it's possible to expose this internal API for public usage. 

Thanks

**Comment by mhowlett** [comment]
added in #209
