### ISSUE TITLE
Closing consumer replica causes request timeouts in other consumers

### ISSUE THREAD

**Issue by sleary56** [confluentinc/confluent-kafka-dotnet#2064]
Description
===========
Hi, I currently have 5 Confluent Kafka consumer replicas connected to Eventhubs via the Kafka connector. These consumers are consuming a constant flow of messages. When a pod scales down and a rebalance occurs, I have noticed a 60 second consumption delay for the partitions that were assigned to the scaled down pod. After this 60 seconds, a timeout error occurs and the consumer begins consuming the newly acquired partitions. 

- Running in K8s with the dotnet/sdk:6.0-bullseye-slim image
- Confluent Kafka 2.1.1

For the purposes of testing, I replicated this issue with 2 pods scaling down to 1:
Consumer 1: Partitions 2, 3, 4
Consumer 2: Partitions 1, 2

17:49:51 Consumer 2 shuts down
17:49:53 Rebalance starts
17:49:54 Consumer 1 continues processing 2, 3, 4
17:50:55 Consumer 1 gets two timeout errors, then immediately begins processing partitions 1, 2

Consumer shut down code:

```
      _consumer.Close();
      _consumer.Dispose();
```

Consumer Options:
```
      BootstrapServers = bootstrapServers,
      GroupId = “ConsumerGroup”
      SecurityProtocol = SecurityProtocol.Ssl,
      SslCaLocation = caRootPath,
      SslCertificateLocation = certificatePath,
      SslKeyLocation = keyfilePath,
      EnableAutoCommit = true,
      AutoOffsetReset = AutoOffsetReset.Earliest,
      LogConnectionClose = false,
      EnableAutoOffsetStore = false,
      AutoCommitIntervalMs = 5000
```

Consumer code:
```
      while (true)
      {
        var cr = _consumer.Consume(stoppingToken);
        _logger.LogDebug("Kafka consumed message");
        await messageHandler(cr.Topic, cr.Partition.Value, cr.Offset.Value, cr.Message.Key, cr.Message.Value);
        
        try
        {
          _consumer.StoreOffset(cr);
        }
        catch (KafkaException e)
        {
          _logger.LogCritical(ERROR_KAFKA_COMMIT, e);
        }

        if (stoppingToken.IsCancellationRequested)
        {
          _logger.LogDebug("Kafka consumption canceled through cancellation token");
          throw new OperationCanceledException();
        }
      }
```

Error log
================
Specific error:

```
2023-06-12T17:50:55.067643408Z       Kafka consumer connection log Message: [thrd:sasl_ssl://eventhub.servicebus.windows.net:9093/b]: sasl_ssl://eventhub.servicebus.windows.net:9093/0: Timed out FetchRequest in flight (after 61055ms, timeout #0)

2023-06-12T17:50:55.067669208Z       Kafka consumer connection log Message: [thrd:sasl_ssl://eventhub.servicebus.windows.net:9093/b]: sasl_ssl://eventhub.servicebus.windows.net:9093/0: Fetch backoff for 500ms: Local: Timed out

2023-06-12T17:50:55.067696008Z       Kafka consumer connection log Message: [thrd:sasl_ssl://eventhub.servicebus.windows.net:9093/b]: sasl_ssl://eventhub.servicebus.windows.net:9093/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests

2023-06-12T17:50:55.068285711Z       Kafka consumer connection log Message: [thrd:sasl_ssl://eventhub.servicebus.windows.net:9093/b]: sasl_ssl://eventhub.servicebus.windows.net:9093/0: 1 request(s) timed out: disconnect (after 973904ms in state UP)
```

Please let me know if a larger log sample would be helpful.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by anchitj** [comment]
What's the issue here? You can tune `session.timeout.ms` and `heartbeat.interval.ms` if you want to detect the failures fast. Check https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
