### ISSUE TITLE
OffsetLag and Partition Size Information

### ISSUE THREAD

**Issue by niemyjski** [confluentinc/confluent-kafka-dotnet#2073]
Description
===========

Is there a good way to get the current consumer groups OffsetLag and the Partition size from the consumer side of things? We are talking over VPCE / cross cloud accounts and it's a bit harder to get this information. Having this information would be great for logging but also to help build out autoscaling?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version: Latest
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by anchitj** [comment]
You can probably use `ListConsumerGroupOffsets` and `QueryWatermarkOffsets` in AdminClient.
