### ISSUE TITLE
On .Net7+ used LibraryImport instead of DllImport

### ISSUE THREAD

**Issue by SoftStoneDevelop** [confluentinc/confluent-kafka-dotnet#2074]

**Comment by SoftStoneDevelop** [comment]
I don’t know if it makes sense (it’s unlikely there will be a performance boost), but it seems that it is recommended to use the new API for P / Invoke. Even if there is no boost now, it may appear in future versions of .NET.

**Comment by nhaq-confluent** [comment]
@SoftStoneDevelop I noticed there is no description, is this still an issue?
