### ISSUE TITLE
Memory leak whist producing messages when broker(s) down

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#208]
from #180, @chiru1205 notes:

I have noticed another memory leak issue this morning while testing a disconnect scenario.
Steps to recreate the issue

![image](https://cloud.githubusercontent.com/assets/19174/26596079/658665d6-4522-11e7-80a2-02f4aac8717a.png)

Shut down Kafka Broker(in my case local).
Use a non-serializing producer with a Delivery Handler.
Send thousands of messages to see if Delivery Handler can handle the error logging. I received error messages as expected. But memory was pushed to the limit and finally got the Access violation exception. Here is a screenshot of the memory leak.
image
I think there should be some kind of mechanism to halt message send requests if broker is not connected or down.

**Comment by treziac** [comment]
Well, it's not a memory leak here (memory not freed which would end up using all memory and end in OutOfMemory exception) but an AccessViolation (much worse - we are writing in an invalid space - I think we have raither release memory we shouldn't have because used in librdkafka)

Memory usage would be normal - as long as message don't timeout (default: 5 min), we won't release any memory, as it's possible the broker switch on again so we can send message. The default is very high, reducing it might be better in prod to avoid huge memory usage in this case.

**Comment by chiru1205** [comment]
@treziac  you are correct. I don't think its memory leak. ,Here is some more information, I noticed that this issue  happens(at least in my case) when queue.buffering.max.messages is increased to 2 Million messages and each of my message size is 2398 bytes. That's a lot of data. There is not enough memory to accommodate queue requirements.
Here are some configuration parameters I'm using 
{"bootstrap.servers", "test"},
   
            {"delivery.report.only.error",true },
           {"queue.buffering.max.messages", 2000000 },
            {"queue.buffering.max.ms",100 },
            {"message.send.max.retries", 3 },
            { "debug", "all" },
            {"client.id", Dns.GetHostName()},
            {
                "default.topic.config", new Dictionary<string, object>
                {
                    {"acks", "all"}, //updated to support leader & follower acknowledgments
                    {"message.timeout.ms", 3000}
                }
            }

Changing the setting back to default values(100000 for queue buffer max messages) did work with any exceptions. I did a test for 6 millions messages and all 6 Million error messages came through. I may have to play with queue.buffering.max.ms to keep up with send requests.

**Comment by treziac** [comment]
Well, didn't see your message while editing :) Thanks for feedback!

**Comment by treziac** [comment]
But there is effectively problems with `delivery.report.only.error` and the `Task ProduceAsync` method.

**Comment by chiru1205** [comment]
> But there is effectively problems with delivery.report.only.error and the Task ProduceAsync method.

I have removed that setting completely from the configuration and using a non serializing producer.

**Comment by mhowlett** [comment]
The growth in memory usage was initially worrying, but with the numbers mentioned above I don't think there is a problem.

The access violation seems likely caused by an OOM error which isn't being checked for in librdkafka ( and arguably shouldn't be: https://stackoverflow.com/questions/763159/should-i-bother-detecting-oom-out-of-memory-errors-in-my-c-code )

**Comment by chiru1205** [comment]
I have increased my message set size to send more messages. Changed it to 5MB and achieved more through put. I think this issue can be closed at this point.
