### ISSUE TITLE
ProduceAsync segmentation fault on a specific produce configuration

### ISSUE THREAD

**Issue by timramone** [confluentinc/confluent-kafka-dotnet#2084]
Description
===========

`ProduceAsync` with certain lengths of `ProducerConfig.ClientId` and `TopicName` strings leads to an invalid memory access and a segmentation fault.

How to reproduce
================

```csharp
var message = "1";

var bootstrapServers = "<your bootstrap servers>";

var topicName = new String('a', 69);
var clientId = new String('a', 239);

var config = new ProducerConfig
{
	BootstrapServers = bootstrapServers,
	ClientId = clientId,
};

var builder = new ProducerBuilder<string, string>(config);
var producer = builder.Build();

await producer.ProduceAsync(topicName, new Message<string, string>()
{
	Value = message
});
```

You can reproduce it with confluent.kafka nuget versions 2.2.0 and 2.1.1.
It can't be reproduced with confluent.kafka nuget version 1.9.3.

Apache Kafka 2.8.1

It can be reproduced on any OS afaik.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by korchak-aleksandr** [comment]
@emasab @edenhill @mhowlett Hello!

Could you help with prioritizing this issue? We are looking forward to a fix for this problem.

We have blocked any updates to confluent-kafka-dotnet library because of this issue.

**Comment by anchitj** [comment]
Thanks for the bug report. This is due to an underflow issue in librdkafka. Fix is being tracked in https://github.com/confluentinc/librdkafka/pull/4689

**Comment by anchitj** [comment]
Closing, as the fix is released now. Please feel free to reopen if you still face this.
