### ISSUE TITLE
ProtobufDeserializer doesn't use SchemaRegistry

### ISSUE THREAD

**Issue by ISBronny** [confluentinc/confluent-kafka-dotnet#2093]
Description
===========
The [ProtobufDeserializer ](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializer.cs)code does not use the schema registry client. But for [AvroDeserializer]( https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Avro/AvroDeserializer.cs) it used. Also it is used in Java deserializer [implementation](https://github.com/confluentinc/schema-registry/blob/49181369e6cf94f9d02cf14edead871bef5348dc/protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufDeserializer.java#L39).

Is it a bug or feature?

**Comment by betmix-matt** [comment]
There's no need to use the SchemaRegistry to deserialize protobuf messages as you must have the generated class from the original proto to specify as the generic argument and you can deserialize into that message without use of the SchemaRegistry.

**Comment by rayokota** [comment]
The deserializer can now optionally take the SR client
