### ISSUE TITLE
Produce() call does not guarantee delivery

### ISSUE THREAD

**Issue by CooperWolfe** [confluentinc/confluent-kafka-dotnet#2110]
Description
===========
`await ProduceAsync()` is very slow in our use case, taking up to 13s at times, but most often sitting around 500ms. For this reason, we decided to try calling `Produce()`, which is performing far better, in the single-digit ms. However, we misconfigured the producer to produce to a topic that didn't exist. When this happened, the `Produce()` call succeeded and we lost the messages. I was under the impression that setting `"EnableIdempotence": true` and `"Acks": "All"` would guarantee the delivery of these messages, but that is not happening. Going back to ProduceAsync, it will throw an exception. Is this expected behavior?

How to reproduce
================
Set up a producer, set the topic to a topic that does not exist (feel free to try ""), and call Produce().

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
```csharp
var config = new ProducerConfig()
{
    // Your connection details/security/etc.,
    AllowAutoCreateTopics = false,
    EnableIdempotence = true,
    Acks = "All"
};
var producerBuilder = new ProducerBuilder<string, string>(config)
    .SetKeySerializer(Serializers.Utf8)
    .SetValueSerializer(Serializers.Utf8);
var producer = producerBuilder.Build();
producer.Produce("", new Message<string, string>()
{
    Key = "key",
    Value = "value"
}); // Does not throw
```
 - [x] Confluent.Kafka nuget version.
 2.2.0
 - [ ] Apache Kafka version.
 - [x] Client configuration.
See above
 - [x] Operating system.
 Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.
Yes

**Comment by anchitj** [comment]
his is indeed expected, because the Produce method operates asynchronously and does not immediately throw exceptions for non-recoverable errors.

If you add delivery handler to the produce method like 
```csharp
producer.Produce("", new Message<string, string>
{
    Key = "key",
    Value = "value"
}, handler =>
{
    if (handler.Error.IsError)
    {
        Console.WriteLine($"Failed to deliver message: {handler.Error.Reason}");
    }
    else
    {
        Console.WriteLine($"Delivered message to {handler.TopicPartitionOffset}");
    }
});
```

you can see the error getting logged.

**Comment by CooperWolfe** [comment]
Consider this scenario:
```csharp
while (true) {
  var consumeResult = consumer.Consume();
  producer.Produce();
  consumer.Commit();
}
```
Here, I want to guarantee the delivery of the produced message before committing the offset and consuming the next message. From what I'm seeing here, is there truly no way to do that, and get good performance?
