### ISSUE TITLE
Confluent.SchemaRegistry.Serdes.Avro AvroDeserializer Probable bug

### ISSUE THREAD

**Issue by ahmar-husain** [confluentinc/confluent-kafka-dotnet#2113]
Description
It seems like the order of field matters when deserializing using AvroDeserializer or doc tag matters .A message encoded with an avro schema where fields are in a particular order , if one tries decode the message which has same name of the feilds , same data type but in different order AvroDeserializer throws a Deserialization exception

**"Confluent.Kafka" Version="2.1.0"
"Confluent.SchemaRegistry.Serdes.Avro" Version="2.1.0"**

How to reproduce
================
**Client configuration**
```

var consumerConfig = new ConsumerConfig
{
    BootstrapServers = "<Bootstrap>",
    GroupId = "test.consumergroup.v1",  
    SecurityProtocol = SecurityProtocol.SaslSsl,
    SaslMechanism = SaslMechanism.Plain,
    SaslUsername = "***********************",
    SaslPassword = "***********************",
    AutoOffsetReset = AutoOffsetReset.Earliest,
};
var schemaRegistryConfig = new SchemaRegistryConfig
{
    Url = "https://localhost",
    BasicAuthUserInfo = "Key:Password",
};
```
**Exception**
"Confluent.Kafka.ConsumeException: Local: Value deserialization error\r\n ---> Avro.AvroException: Schema mismatch. Reader  

**Steps to reproduce** 
Encode a message with this schema
{
"namespace": "storage.management.example.schema",
"type": "record",
"doc": "Example schema for testing",
"name": "Event",
"fields": [
    **{ "name": "A", "type":  "string"  },
    { "name": "B", "type":  "string"  },**
   
]
}

Try decoding it by reversing the order of A and B
{
"namespace": "storage.management.example.schema",
"type": "record",
"doc": "Examp schema for testing",
"name": "Event",
"fields": [
    **{ "name": "B", "type":  "string"  },
    { "name": "A", "type":  "string"  },**
   
]
}

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by rayokota** [comment]
The order of fields is significant with Avro.
