### ISSUE TITLE
Getting license of confluent kafka-dotnet

### ISSUE THREAD

**Issue by Amitssh** [confluentinc/confluent-kafka-dotnet#213]
Hi, I would like to know if I want to use this dotnet library for my product, what would be the licensing terms and conditions?
 
Thank you for your time in advance.

**Comment by mhowlett** [comment]
Apache 2

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/LICENSE

**Comment by mhowlett** [comment]
oh and it's derived from rdkafka-dotnet which is two-clause BSD.
