### ISSUE TITLE
Clients impacted by librdkafka bug in 2.2.0

### ISSUE THREAD

**Issue by rwkarg** [confluentinc/confluent-kafka-dotnet#2130]
Description
===========

After maintenance operations on clusters (ex. moving nodes) or other communication interruptions, some clients will spam `OffsetForLeaderEpoch` and `Metadata` calls until the process is restarted.

This appears to be due to the below issue in `librdkafka` that is fixed but not yet released:
https://github.com/confluentinc/librdkafka/issues/4425

How to reproduce
================

1. Have client application connect to a broker
2. Perform maintenance operation (add/remove nodes) or interrupt network communication
3. Occasionally the client will start calling `OffsetForLeaderEpoch` and `Metadata` thousands of times a second

**Comment by rwkarg** [comment]
Is there somewhere that a roadmap can be followed for when new versions of `librdkafka` and `confluent-kafka-dotnet` are planned to be available and when they're released?

**Comment by anchitj** [comment]
Hi, we are planning to release version 2.3.0 this week, which should address this fix. We already have a release candidate (RC) available with this fix if you'd like to test it. You can find it here: https://www.nuget.org/packages/Confluent.Kafka/2.3.0-RC3.

**Comment by anchitj** [comment]
Since it's a RC it's not announced there. We will announce once we do the final release for 2.3.0

**Comment by anchitj** [comment]
2.3.0 is released now which has this fixed. Closing. Feel free to reopen if the issue still persists.
