### ISSUE TITLE
How to consume messages faster

### ISSUE THREAD

**Issue by vaibhavg1985apr** [confluentinc/confluent-kafka-dotnet#214]
Hello,

Could you please suggest how can i consume messages faster?

**Comment by mhowlett** [comment]
if you are more specific, we can give specific advice.

**Comment by vaibhavg1985apr** [comment]
Ask is to consume messages at the rate of 40 millions per hour. Producer (written by another vendor ) is able to produce messages with that speed on 40 partitions. We want to consume that many messages with that speed. I tried to use parallel.Invoke but with no luck.

**Comment by mhowlett** [comment]
You don't say how you're trying to use `Parallel.Invoke`.. (you almost certainly shouldn't be using this). Have a look at the AdvancedConsumer example for how to consume messages. 

A single consumer on my dev machine can read at about 400000 messages per second (100 byte messages). 40 million messages per hour is a small number.

**Comment by AminQurjili** [comment]
Hi Matt . could you please link the advance consumer example code page. I can not find it in the examples directory.
