### ISSUE TITLE
Can't connect to remote host - producer points to localhost

### ISSUE THREAD

**Issue by djsowa** [confluentinc/confluent-kafka-dotnet#216]
Hi,

I have problem with connection to remote host, here is example of my code:
`

	var config = new Dictionary<string, object> { { "bootstrap.servers", _connectionString.ToString() }, { "broker.address.family", "v4" }};
	_producer = new Producer(config);
	var messageBody = Encoding.UTF8.GetBytes(FormatMessage(message));
	var produceRes = _producer.ProduceAsync(_connectionString.QueueName, null, messageBody).GetAwaiter().GetResult();
`

The value of __connectionString.ToString()_ is SOME_REMOTEIP:9092.
I'm sure broker is working on the address I try to use, the 9092 port is opened(i test using telnet).
But on server side I can't see any "traffic". I run WireShark to check what is hapening and all traffic from this lib is going to the "localhost". What I'm doing wrong ?

**Comment by treziac** [comment]
From you computer, if you run consoler-producer / consumer (from kafka or confluent binaries, for example here: https://kafka.apache.org/downloads and then (assuming you are on windows)
`bin\windows\kafka-console-producer.bat --broker-list SOME_REMOTEIP:9092 --topic test`
does it work?

**Comment by djsowa** [comment]
I'm receiving:
D:\Tools\Kafka\kafka_2.12-0.10.2.1\bin\windows>kafka-console-producer.bat --broker-list REMOTE_IP:9092 --topic test
testmessage
[2017-06-02 16:04:52,460] ERROR Error when sending message to topic test with key: null, value: 11 b
ytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for test-0: 1508 ms has passed
 since batch creation plus linger time

**Comment by treziac** [comment]
You cannot receive message from your broker it seems
Are you sure you don't have a firewall issue for incoming traffic (or on your broker for output traffic?)

also, be sure to not use http or other protocol in REMOTE_IP, just the ip

**Comment by treziac** [comment]
Also on your broker, check your server properties for listeners (and eventually advertised.listeners if you use it)
it should be PLAINTEXT://REMOTE_IP:9092

**Comment by djsowa** [comment]
I have run tcpdump on server where Kafka is installed. I see that traffic is incoming to the server.
I'm using Bitmapi image of Kafka on MS Azure. Maybe some issues with configuration, I will check !

**Comment by mhowlett** [comment]
opened, debugged, answered, closed even before I even get in in the morning - thanks @treziac !
