### ISSUE TITLE
Space characters in Confluent.SchemaRegistry.RestService encodes as '+' instead of '%20'

### ISSUE THREAD

**Issue by Rand0mCitizen** [confluentinc/confluent-kafka-dotnet#2163]
Description
===========

Incorrect encoding space characters of subject parameter value in all methods which accepts subject in Confluent.SchemaRegistry.RestService class.

How to reproduce
================

Register schema with subject field containing space character.
Try to get schema version.

Request will be executed with incorrect url with '+' characters instead of '%20'.
For example executing simple curl request 
`curl http://127.0.0.1:8081/subjects/Some%20Domain%20Event/versions` 
gives correct response - list of schema versions.

The reason for the problem is that Confluent.SchemaRegistry.RestService class uses WebUtility.UrlEncode to encode subject parameter value. I think you should use Uri.EscapeDataString to encode uri segment.

Package version used: Confluent.SchemaRegistry.2.3.0

**Comment by rayokota** [comment]
Fied by https://github.com/confluentinc/confluent-kafka-dotnet/pull/2226
