### ISSUE TITLE
Does AvroDesrializer support reference schema/multiple events for the same topic ?

### ISSUE THREAD

**Issue by alpeshdhanesha** [confluentinc/confluent-kafka-dotnet#2168]
Description
===========
I'm using Reference avro schema for my project and facing the issue while deserializing encrypted message. As i'm using encryption before serializing to AvroSerializer, I have to deserialize it separately. everything is working fine if i use the single schema (WITHOUT REFERENCE SCHEMA) but when i try to desacralize with reference schema its not working. Any help would be much appreciated. 

Thanks 

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by alpeshdhanesha** [comment]
Hello,

Anything on this ?

**Comment by anchitj** [comment]
Hi,

This is not supported as of now with the .NET client.
