### ISSUE TITLE
How to retrieve message at specific offset?

### ISSUE THREAD

**Issue by vinodres** [confluentinc/confluent-kafka-dotnet#217]
I am trying to figure out a better solution to deal with poison messages (messages that consumer is unable to process). I am thinking to create a companion topic called topicname.quarantine and when a consumer cannot process a message even after configured number of retry attempts, the message will be published to its quarantine topic. 

My question is more towards how can I retrieve a message from quarantine topic? Most off these messages require some sort of manual intervention. Is there a way to retrieve the messages using an offset and partition number? Our support team is going to have a dashboard from where they will have option to either dismiss a message or send it for re-processing. So based on the user action, I would like to retrieve a message on demand and take necessary action.

**Comment by mhowlett** [comment]
so when the consumer reads a message, you know the topic, partition, offset, key, value, timestamp and error from the source and you'll write all that out to your quarantine topic?

You could have topic/partition/offset of the original message as the key in the quarantine topic. Then create a materialized view of your quarantine topic in a key/value store or db table. your user interface reads from that view. when the user takes action on a particular message, you could then send a null value with the same key to the quarantine topic (which gets materialized in the view as the item disappearing). Your quarantine topic could be a compacted topic. 

also to answer your question directly, yes you can read from a particular topic/partition/offset directly by specifying this in the `Assign` method - see the `SimpleConsumer` example.

**Comment by vinodres** [comment]
My initial thinking was to publish key / value of poison message to the quarantine topic and then deal with rest of message handling from there. 

@mhowlett : Your idea definitely seems more interesting :+1: . It avoids duplication of poison message payload in two topics. I will give this approach a try.

**Comment by mhowlett** [comment]
btw: i think what you are doing is unusual - most of the time I think an appropriate thing to do would be to just log an error and ignore the message (and have someone keep on top of the logs), or possibly fail fast and require the error fixed before continuing (as I can't think of any time you would design a system where this sort of thing would be expected). I don't know your use case though ...

**Comment by vinodres** [comment]
Long story short, we are transitioning from legacy systems built over last 20 years to new technology stack. We are in the middle of this transition and we have to keep both sides in sync. Legacy systems are bit unreliable and this process is to avoid legacy system issues impacting new applications. New systems fire and forget the message. So far we were logging the failures as errors. Trying to figure out if some of the manual intervention steps can be automated to certain degree. Just exploring options.

**Comment by mhowlett** [comment]
sounds good

**Comment by eyantiful** [comment]
Hows the quarantine topic serve the solution?
If the poison message is stored and served from K/V store, whats this topic goal?

**Comment by treziac** [comment]
If you change your K/V store, or use something else in the future, you don't have to change where the quarantaine message is send, only how it is consumed, and the producer don't have to know what the store is or how the message is treated behind. Stream-oriented architecture and decoupling ;)
