### ISSUE TITLE
"Broker: Unknow Member" error when committing while using assign()

### ISSUE THREAD

**Issue by kboniadi** [confluentinc/confluent-kafka-dotnet#2173]
Description
===========
I have a use case in my app where I need to maintained order within each partition for a topic. To handle this on the consumer side, I've implemented some custom logic to handle consumer assignment to specific partitions where I'm incorporating the assign() method.

I cant use the typical kafka rebalancing mech bc the logic breaks if a single consumer ever read from two partitions at once--I must maintain one consumer for one partition. Even if I use the Range strategy, this is not good enough since if a consumer ever goes down, then kafka's rebalancing may assign two partitions to a consumer for a split second until a new consumer is brought back online.

But when I go to commit a consumed message by a specific consumer which only reads on the assigned topic partition, I get this error: "Broker: Unknown Member".

Is there a way to use the assign() method as I'm doing it and commit offsets so that if another consumer connects to a partition, it will start consuming from where the last connected consumer left off?

How to reproduce
================
- setup typical consumer but use the assign() method to assign the consumer to partition 0 of a topic
- Once you have consumed a message, Commit it using the ConsumeResult object.
```charp
var config = new ConsumerConfig
{
    BootstrapServers = this.bootstrapServers,
    GroupId = this.configuration.GetValue<string>("configuration:kafka:groupId"),
    ClientId = this.ClientId,
    AutoOffsetReset = AutoOffsetReset.Earliest,
    EnableAutoCommit = false,
    MaxPollIntervalMs = this.kafkaMaxPollIntervalMilliSeconds,
    PartitionAssignmentStrategy = strategy,
    // Debug = "protocol",
};

...

consumer.assign(new [] { new TopicPartitionOffset(this.topic, 0, Offset.Stored) })
```

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version = 2.2.0
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system = macos
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [x] Provide broker log excerpts.

**Comment by anchitj** [comment]
You can use a unique GroupId for each consumer-partition pair. This way, each consumer will be part of its own consumer group, and Kafka will allow offset commits for that specific group. Something like `"{this.configuration.GetValue<string>("configuration:kafka:groupId")}-partition-{partitionNumber}"`
