### ISSUE TITLE
Does Confluent Kafka dotnet support KSQL or Stream Processing the way Java supports ?

### ISSUE THREAD

**Issue by mshahins** [confluentinc/confluent-kafka-dotnet#2179]
Description
===========

Does Confluent Kafka dotnet support KSQL or Stream Processing the way Java supports ?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by anchitj** [comment]
This isn't supported yet by the .NET client.
