### ISSUE TITLE
Producer buffer size

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#218]
Going through kafka documentation, the producer maintains buffers of unsent records for each partition. These buffers are of a size specified by the batch.size config. When I specified the batch.size configuration for producer, I am getting an exception back. Please advice on how to implement this pattern i.e. producer maintains a buffer of messages. Once the buffer is reached, a secondary thread flushes the messages to the broker.

**Comment by mhowlett** [comment]
The dotnet client is based on librdkafka which has a different set of configuration properties as documented here: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

The one's you're interested in are:

`batch.num.messages`
`queue.buffering.max.kbytes`
