### ISSUE TITLE
StringDeserializer uses hard coded encoding

### ISSUE THREAD

**Issue by bschmidtbauer** [confluentinc/confluent-kafka-dotnet#22]
The built-in StringDeserializer doesn't use the constructor specified encoding but uses UTF8.  The StringSerializer uses the specified encoding.

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Serialization/StringDeserializer.cs#L35

**Comment by mhowlett** [comment]
whoops! good catch, thanks.
