### ISSUE TITLE
Simple Produce Example takes over 1 seconds to complete and another second to dispose

### ISSUE THREAD

**Issue by arijoon** [confluentinc/confluent-kafka-dotnet#221]
I have used your simple produce example and it takes over 1 seconds to produce and over another seconds to dispose the Producer object. I was wondering if it is supposed to be this slow, or I am not using it correctly. 

```cs
var config = new Dictionary<string, object> { { "bootstrap.servers", brokers } };
using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
{
    var publishTask = producer.ProduceAsync(topic, null, payload);

    producer.Flush(timeoutMiliseconds);

    if(!publishTask.IsCompleted)
    {
        // Failed to publish in time
        return false;
    }

    var deliveryReport = await publishTask;
}
```

`timeoutMiliseconds` being around `5000`, and is there a way to terminate the publishTask if it did not complete in time because it seems like it'll go forever if the kafka server is down.

**Comment by edenhill** [comment]
Set the `queue.buffering.max.ms` configuration property to a lower value, it defaults to 1 second

**Comment by arijoon** [comment]
Assume that's on the main config object
```
var config = new Dictionary<string, object> { { "bootstrap.servers", brokers }, { "queue.buffering.max.ms", 100 } };
```

still takes the same amount of time (1 sec to publish, 1 sec to dispose)

**Comment by arijoon** [comment]
Will also need `queue.buffering.max.messages=1` for it to work. Surprising thing is, this will speed up the first request, but the rest take 1 seconds!

**Comment by bschmidtbauer** [comment]
If your goal is to do a synchronous request as fast as possible (e.g. no batching delay) then you could try something like the below.  This would typically not be something that you would want to do in a high throughput system as your overall throughput would be lower as you don't take advantage of client batching.

```cs
var config = new Dictionary<string, object>();
var topicConfig = new Dictionary<string, object>();
config.Add("bootstrap.servers", bootstrapServers);
config.Add("retries", 0);
config.Add("client.id", "someId");
config.Add("batch.num.messages", 1);
config.Add("socket.blocking.max.ms", 1);
config.Add("socket.nagle.disable", true);
config.Add("queue.buffering.max.ms", 0);
config.Add("default.topic.config", topicConfig);
topicConfig.Add("acks", 1);

// should use the producer as a singleton as there is broker discovery that happens at initialization
using (var producer = new Confluent.Kafka.Producer<string, string>(config, new Confluent.Kafka.Serialization.StringSerializer(Encoding.UTF8), new Confluent.Kafka.Serialization.StringSerializer(Encoding.UTF8)))
{
    var produceResult = producer.ProduceAsync(topic, "some key", "some val").Result;
    // do something with the result...
}
```
The above is not how you would want to deploy this - you would definitely want to use the producer as a singleton to avoid all the overhead of discovering the full broker set and the partition leaders.

**Comment by arijoon** [comment]
Thanks @bschmidtbauer that speeds it up dramatically, especially if producer is singleton. In my use case I need each message to be sent separately without batching. It would be nice if you can compose that above example into an example program for future of reference of anyone else hitting this specific use case. 

Thanks again

**Comment by treziac** [comment]
Added in https://github.com/confluentinc/confluent-kafka-dotnet/wiki/Producing-messages#reduce-latency, thanks @bschmidtbauer

**Comment by mhowlett** [comment]
thanks @bschmidtbauer and @treziac - good input.
