### ISSUE TITLE
Availability of commitOffsetsOnFirstJoin property

### ISSUE THREAD

**Issue by fabmoll** [confluentinc/confluent-kafka-dotnet#2210]
Description
===========

For a specific configuration to discard/ignore pending message when a consumer start, we would like to be able to set the commitOffsetsOnFirstJoin to false.

But as I can see this property isn't available.  
Is it planned for a next version? Or maybe is there away to set this property in another way?

We're using the Kafka 2.3 library

Regards.

**Comment by anchitj** [comment]
I think you are talking about `auto.offset.reset`. You can set it to `latest` then the consumer will start reading from the end of the log (i.e., only new messages) if no previous offset is found for the consumer's group.

Please feel free to reopen if this doesn't helps.

**Comment by fabmoll** [comment]
Indeed I thought I had to set those members to be able to do it:

autoCommit: false, 
fromOffset: 'latest'
commitOffsetsOnFirstJoin: false 

Thank you @anchitj
