### ISSUE TITLE
Consuming batch of messages

### ISSUE THREAD

**Issue by eyantiful** [confluentinc/confluent-kafka-dotnet#224]
Hi,
As far as i can see there is no option to fetch batch of messages in Consume (although rd_kafka_consume_batch is part of LibrdKafka as far as the Doc at least).

Is that correct?
Is there a design reason for this or just prioritization?

Thanks.

**Comment by mhowlett** [comment]
There are currently no plans to provide a C# API that provides messages / events in batches. Note that behind the scenes, delivery of messages to/from Kafka is batched (and this is configurable via the config parameters) - they are just delivered to you one at a time from a queue.

In the future we may look into marshaling messages / events across the managed/unmanaged boundary in batches as I suspect this would result in a measurable performance improvement. We may also consider exposing them via a batch style API in C#, though I'd guess the benefit of this wouldn't be that big (so probably not).

**Comment by eyantiful** [comment]
Thanks matt.
Are you referring to config "max.poll.records"?

**Comment by treziac** [comment]
`max.poll.records` does not exist in librdkafka (it's a java client option)

For consuming, the involved parameters are `fetch.min.bytes`, `fetch.wait.max.ms` and `fetch.message.max.bytes`	
By default, librdkafka let 100ms to broker to batch data, with a max of 1MB by batch (min 1B)- those shoud fit most case
For producing, relevant config values are `batch.num.messages` and `queue.buffering.max.ms`
Other parameter are involved with the local queue, but this is what is involved with broker exchange.

To be more clear, there is a local queue in librdkafka which act as a buffer with broker - this allow to put all the messaging process in the C library, and wrapper in other languages like confluent-kafka-dotnet have just to poll from this local queue. 
So here, consuming one by one won't change a lot regarding network - this is only internal state on the process, the messages poll from broker are indeed batched by default

See https://github.com/edenhill/librdkafka/blob/0.9.5.x/CONFIGURATION.md for list of configs

**Comment by eyantiful** [comment]
Thank you very much.
