### ISSUE TITLE
ProtobufDeserializer constructor throws an exception if ProtobufDeserializerConfig is provided in 2.5.0

### ISSUE THREAD

**Issue by bradwestness** [confluentinc/confluent-kafka-dotnet#2267]
Description
===========
In 2.4.0 and earlier versions, it was possible to create a `ProtobufDeserializer` instance while providing a `ProtobufSerializerConfig` object as follows:

```csharp
var deserializerConfig = new ProtobufSerializerConfig();
// set deserializer options

var deserializer = new ProtobufDeserializer<Any>(deserializerConfig);
```

in 2.5.0, the above code throws a `NullReferenceException` in the `ProtobufDeserializer` constructor, because the constructor passes null for the `schemaRegistryClient` argument to the base constructor of the `AysncSerde` type it inherits from ([on line 63 here](https://github.com/confluentinc/confluent-kafka-dotnet/blob/380d861e2edcda7de3bae9b4fd1e0284a84794a1/src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializer.cs#L63)), and the `AsyncSerde` constructor then attempts to dot into the `schemaRegistryClient` instance ([on line 54 here](https://github.com/confluentinc/confluent-kafka-dotnet/blob/380d861e2edcda7de3bae9b4fd1e0284a84794a1/src/Confluent.SchemaRegistry/AsyncSerde.cs#L54)), which is null in this scenario.

How to reproduce
================

Complete repro:

```xml Project.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.SchemaRegistry.Serdes.Protobuf" Version="2.5.0" />
  </ItemGroup>

</Project>
```

```csharp Program.cs
using Confluent.SchemaRegistry.Serdes;
using Google.Protobuf.WellKnownTypes;

var deserializerConfig = new ProtobufSerializerConfig();
var deserializer = new ProtobufDeserializer<Any>(deserializerConfig);
```

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [X] Client configuration.
 - [X] Operating system.
 - [X] Provide logs (with "debug" : "..." as necessary in configuration).
 - [X] Provide broker log excerpts.
 - [X] Critical issue.

**Comment by yinzara** [comment]
While I agree this is a breaking change, how can you use a ProtobufSerializer without a SchemaRegistryClient? The whole point of the ProtobufSerializer from this library is to use Schema Registry. If you wanted to serialize Protobuf without it, you can just use the generated classes `ToByteArray()` method.

**Comment by yinzara** [comment]
Confirmed this is a breaking change.  ProtobufDeserializer should NOT require a SchemaRegistryClient to work.

**Comment by yinzara** [comment]
This bug is actually much more serious than it lets on.
This actually affects ALL deserializers that extend from AsyncSerde (i.e. ALL of them).
Previously you couldn't even specify an ISchemaRegistryClient in the constructor and now it's required or you get this exception.
IMHO this is a showstopper defect as well.
