### ISSUE TITLE
No license in nuget since 2.5.0 because of wrong tag used

### ISSUE THREAD

**Issue by rogerbriggen-securiton** [confluentinc/confluent-kafka-dotnet#2269]
Description
===========
With https://github.com/confluentinc/confluent-kafka-dotnet/pull/2192/files#diff-625d4f5deb9157fe8215f0f0aa6d44f4697beb50b8142cdbb3342a3353aad599R8 you changed to nuget license expression which is appreciated but you used the wrong tag, so now the nuget does not have any license.
see https://github.com/confluentinc/confluent-kafka-dotnet/pull/2192/files#r1693253202

How to reproduce
================
Check https://nuget.info/packages/Confluent.Kafka/2.5.0 

Checklist
=========

Please provide the following information:
 - [-] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [-] Apache Kafka version.
 - [-] Client configuration.
 - [-] Operating system.
 - [-] Provide logs (with "debug" : "..." as necessary in configuration).
 - [-] Provide broker log excerpts.
 - [-] Critical issue.

**Comment by anchitj** [comment]
Thanks for catching this bug. We've fixed it in https://github.com/confluentinc/confluent-kafka-dotnet/pull/2275
