### ISSUE TITLE
Compression Codec enum not implemented yet?

### ISSUE THREAD

**Issue by TeaLeafReader199** [confluentinc/confluent-kafka-dotnet#227]
Has compression codec been implemented? Not able to find the enum in the source code and was not sure.

**Comment by mhowlett** [comment]
use the `compression.codec` config parameter (refer to: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)

I believe they're all available in the nuget librdkafka.redist.

**Comment by TeaLeafReader199** [comment]
The type is an Enum, what is the enum used? Are there any examples of the compression being set through the producers config?

**Comment by mhowlett** [comment]
no examples in the dotnet repo.
specify the value as a string, not an enum type.
the API is done this way to allow for easy specification via a text file
and also consistency with other clients.
in the future we may provide a strongly typed .net configuration class
(together with specific enum for compression and other enum types), but we
don't do that presently.
