### ISSUE TITLE
Any plans to expose offsetsForTimes method on Consumer

### ISSUE THREAD

**Issue by denisivan0v** [confluentinc/confluent-kafka-dotnet#228]
Java consumer API has the [method](https://kafka.apache.org/0102/javadoc/org/apache/kafka/clients/consumer/Consumer.html#offsetsForTimes(java.util.Map))
```java
Map<TopicPartition,OffsetAndTimestamp> offsetsForTimes(Map<TopicPartition,Long> timestampsToSearch)
```
which helps to assign a consumer to a specified offset based on timestamp.

Is there any plans to support this in .NET API?

**Comment by mhowlett** [comment]
Should be easy to add (corresponding function exists in librdkafka) but hasn't been prioritized - you're the first person to ask for the dotnet client I think.

PRs accepted :-)

**Comment by denisivan0v** [comment]
I'll take a look. Will be appreciated for docs/guidelines describing how to work with librdkafka correctly.

**Comment by denisivan0v** [comment]
Here is the corresponding Kafka improvement proposal: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=65868090

**Comment by mhowlett** [comment]
The relevant librdkafka function is `rd_kafka_offsets_for_times`.
This should be wrapped in LibRdKafka.cs (for examples, see other methods).
Then exposed as a method on `Consumer`.

Ahh yes, I forgot someone else asked for this :-). It'd be a quick win, we should do this. Any help appreciated, but I'll try to get to it sooner rather than later.

**Comment by denisivan0v** [comment]
I'm started to implement this method, but stuck at passing arguments to librdkafka.
Here is my commit https://github.com/denisivan0v/confluent-kafka-dotnet/commit/8ff96aea529891c3d71a77601f8321cb570bb002.

Now I need to convert `IEnumerable<KeyValuePair<TopicPartition, long>>` instance to `rd_kafka_topic_partition_list_t` instance to call the corresponding method https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L2433. But I'm really not sure how to do it. 

@mhowlett, can you give me an advice on this? Comments on current changes are also appreciated.

**Comment by mhowlett** [comment]
Have a look in `SafeKafkaHandle` for something similar... perhaps `GetCTopicPartitionList`. This conversion should happen in `SafeKafkaHandle` - sorry didn't think of that before.

**Comment by denisivan0v** [comment]
Pinned: java implementation is here https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L1489

**Comment by melnikov77** [comment]
Any plans to release this method? I can't find it in "0.11.0.x" branch :-(

**Comment by mhowlett** [comment]
it will be in the next major release, or you can use a package from the appveyor nuget feed.

**Comment by jake0029** [comment]
Sorry, do we have sample usage of OffsetFortimes event in .net code?  Thank you
