### ISSUE TITLE
Unable to produce the messages using SSL authentication

### ISSUE THREAD

**Issue by ManteshJ** [confluentinc/confluent-kafka-dotnet#229]
I am trying to connect to Kafka v0.10.2.1 running on Windows 8.
I am using Confluent.Kafka v0.9.5 and my test producer and consumer applications are running on Windows 8 with .NET 4.6.2 framework.

Kafka server.properties as follows

`
listeners=PLAINTEXT://ip_addr:9093,SSL://ip_addr:9094
ssl.client.auth=required
ssl.keystore.location=C:\\OpenSSL-Win64\\Kafka.server.keystore.jks
ssl.keystore.password=test1234
ssl.key.password=test1234
ssl.truststore.location=C:\\OpenSSL-Win64\\Kafka.server.truststore.jks
ssl.truststore.password=test1234
ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
ssl.keystore.type=JKS
ssl.truststore.type=JKS
security.inter.broker.protocol = SSL`
I am trying to use the below configuration for the producer

`string brokerList = "SSL://ip_addr:9094";
            string topicName = "ConfTest2";
            Console.WriteLine("index: " + index);
            try
            {
                var config = new Dictionary<string, object> { { "bootstrap.servers", brokerList } };
                config.Add("session.timeout.ms", "6000");
                config.Add("retries", "3");
                config.Add("security.protocol", "SSL");
                config.Add("ssl.ca.location", "C:\\OpenSSL-Win64\\ca-cert");
                config.Add("ssl.certificate.location", "C:\\OpenSSL-Win64\\cert-signed");
                config.Add("ssl.key.password", "test1234");

                using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
                {
                    string text = "Message_"+DateTime.Now.ToString() + "-" + index;
                    DateTime dt = System.DateTime.Now.Add(new TimeSpan(0, 0, 10));
                    DateTime dt1 = new DateTime() + new TimeSpan(0, 0, 10);
                    var deliveryReport = producer.ProduceAsync(topicName, null, text);
                    deliveryReport.ContinueWith(task =>
                    {
                        Console.WriteLine("index:" + index + " Partition: " + task.Result.Partition + ", Offset: " + task.Result.Offset);
                    });
                    producer.Flush();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.Message);
            }
`
I am not getting any exceptions.

**Comment by smiffy1989** [comment]
You haven't escaped the backslashes (use \\ or @ before the string) and in the broker list you don't need to specify SSL:// just use <host/IP>:<port>.

Also, you should subscribe to the OnError event so you can see the errors:

```
producer.OnError += (_, error) =>
{
      Console.WriteLine($"Error: {error}");
};
```

**Comment by ManteshJ** [comment]
Hi @smiffy1989, thank you for your reply. I have changed the code, what you have mentioned and I tried but yet not working, I am getting following error
`Error: ssl://XX.X.XXX.XX:9094/bootstrap: SSL handshake failed: .\ssl\s3_both.c:408: error:1408E0F4:SSL routines:ssl3_get_message:unexpected message: : client authentication might be required (see broker log)`

Changed Code:

`string brokerList = "XX.X.XXXXX:9094";
            string topicName = "ConfTest2";

            Console.WriteLine("index: " + index);
            try
            {
                var config = new Dictionary<string, object> { { "bootstrap.servers", brokerList } };
                config.Add("session.timeout.ms", "6000");
                config.Add("retries", "3");
                config.Add("security.protocol", "SSL");
                config.Add("ssl.ca.location", "C:\\OpenSSL-Win64\\ca-cert");
                config.Add("ssl.certificate.location", "C:\\OpenSSL-Win64\\cert-signed");
                config.Add("ssl.key.password", "test1234");

                using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
                {
                    string text = "Message_" + DateTime.Now.ToString() + "-" + index;
                    DateTime dt = System.DateTime.Now.Add(new TimeSpan(0, 0, 10));
                    DateTime dt1 = new DateTime() + new TimeSpan(0, 0, 10);
                    var deliveryReport = producer.ProduceAsync(topicName, null, text);
                    deliveryReport.ContinueWith(task =>
                    {
                        Console.WriteLine("index:" + index + " Partition: " + task.Result.Partition + ", Offset: " + task.Result.Offset);
                    });
                    producer.OnError += (_, error) =>
                    {
                        Console.WriteLine($"Error: {error}");
                    };
                    producer.Flush();
                }
            }
            catch (Exception ex)
            {

                Console.WriteLine("Exception: " + ex.Message);
            }`

**Comment by nagarjuna119** [comment]
Hi Mantesh, were you able to get this working? I am having the same issue

**Comment by petersonnek** [comment]
@nagarjuna119 are you using the latest version? I'm pretty sure there was an issue handling SSL in the version released when this issue was opened.

**Comment by nagarjuna119** [comment]
Yes, I am on  0.11.3, Below is sample I am trying to use the sample below, after a long wait I get invalid partition. changing the port to non SSL port and removing ssl config's works fine.

        static void Main(string[] args)
        {
            string brokerList = "kafka.test.test.net:9093";
            string topicName = "testtopic";

            var config = new Dictionary<string, object>
            {
                {"bootstrap.servers", brokerList},
                {"client.id", Dns.GetHostName()},
                {"security.protocol", "SSL"},
                {"ssl.ca.location", @"C:\certs\windows\ca-cert"}
            };

            using (
                var producer = new Producer<string, string>(config, new StringSerializer(Encoding.UTF8),
                    new StringSerializer(Encoding.UTF8)))
            {
                Console.WriteLine("\n-----------------------------------------------------------------------");
                Console.WriteLine($"Producer {producer.Name} producing on topic {topicName}.");
                Console.WriteLine("-----------------------------------------------------------------------");

                var deliveryReport = producer.ProduceAsync(topicName, "", "Test Message");

                try
                {
                    var result = deliveryReport.Result; // synchronously waits for message to be produced.
                    Console.WriteLine($"Partition: {result.Partition}, Offset: {result.Offset}");

                }
                catch (Exception)
                {
                    throw;
                }
            }
        }


Output:
-----------------------------------------------------------------------
Producer WPC0JG6JP#producer-1 producing on topic nord_epm_export_ssl.
-----------------------------------------------------------------------
Partition: -1, Offset: Invalid [-1001]
Press any key to continue . . .

**Comment by nagarjuna119** [comment]
Yes, I am on 0.11.3, Below is sample I am trying to use the sample below, after a long wait I get invalid partition. changing the port to non SSL port and removing ssl config's works fine.

    static void Main(string[] args)
    {
        string brokerList = "kafka.test.test.net:9093";
        string topicName = "testtopic";

        var config = new Dictionary<string, object>
        {
            {"bootstrap.servers", brokerList},
            {"client.id", Dns.GetHostName()},
            {"security.protocol", "SSL"},
            {"ssl.ca.location", @"C:\certs\windows\ca-cert"}
        };

        using (
            var producer = new Producer<string, string>(config, new StringSerializer(Encoding.UTF8),
                new StringSerializer(Encoding.UTF8)))
        {
            Console.WriteLine("\n-----------------------------------------------------------------------");
            Console.WriteLine($"Producer {producer.Name} producing on topic {topicName}.");
            Console.WriteLine("-----------------------------------------------------------------------");

            var deliveryReport = producer.ProduceAsync(topicName, "", "Test Message");

            try
            {
                var result = deliveryReport.Result; // synchronously waits for message to be produced.
                Console.WriteLine($"Partition: {result.Partition}, Offset: {result.Offset}");

            }
            catch (Exception)
            {
                throw;
            }
        }
    }
Output:

Producer machine#producer-1 producing on topic testtopic.

Partition: -1, Offset: Invalid [-1001]
Press any key to continue . . .

**Comment by mhowlett** [comment]
I wrote some detailed notes on setting up SSL some time back: https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security - they might be useful.

If you're still experiencing problems, you could set the `debug` config parameter to `all` (or possibly just `ssl` will be enough) for verbose logging of what's going on.

Closing since this issue is very old. Feel free to open again if unresolved and the above doesn't help.
