### ISSUE TITLE
librdkafka not found error on mono5

### ISSUE THREAD

**Issue by vlaldis** [confluentinc/confluent-kafka-dotnet#231]
I `m facing this issue, when running my app:
","exception details":"System.TypeInitializationException: The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception. ---> System.DllNotFoundException: librdkafka\n at (wrapper managed-to-native) Confluent.Kafka.Impl.LibRdKafka+NativeMethods:rd_kafka_version ()\n at Confluent.Kafka.Impl.LibRdKafka.version () [0x00000] in <8426b4d916c24ebf868942fa8580dfa7>:0 \n at Confluent.Kafka.Impl.LibRdKafka..cctor () [0x004e8] in <8426b4d916c24ebf868942fa8580dfa7>:0

Only solution is to copy librdkafka.so from restored nugets to build dir. However, this is complicating deployment on multiple  different machines.

Environment:
Ubuntu 16.04
mono 5
Confluent.Kafka v0.9.5

**Comment by treziac** [comment]
We don't support mono (though we try to make it work on best effort when feedback arrise)
Indeed we are trying to load the native windows dll rather than the linux one.
Note that we don't test on mono for now (only .NET Core and .NET Framework)
Any reason not to use .NET Core on linux?

If we fix this, it won't be before two next release (the next one is in process and I don't think confluent will add any more changes in it) Also the change is not trivial, we would have to check on which platform we are (debian, centos, windows...) and/or change the way we load the dll on .NET framework.

For now, as you said you can simply copy the dll, eg. add the .so in your project as an item with property copy to output directory enable.

**Comment by treziac** [comment]
On other way to solve this should be to install librdkafka directly, packages are
librdkafka-dev and librdkafka1

**Comment by mhowlett** [comment]
I remember many headaches getting library loading to work with mono from when I was working on NNanomsg... and it's that experience that makes me wary of officially supporting mono in general. 

I do want to update Confluent.Kafka to allow the librdkafka load path to be specified programmatically (and it would make sense to think about this issue with mono then), but we have other higher priority things to do atm.

**Comment by treziac** [comment]
Did installing librdkafka-dev and librdkafka1 worked?

**Comment by yousifh** [comment]
What sort of app is this? I'm running aspnet core app on Mono 4.6 and with `dotnet publish` all the native dependencies are copied over properly so Mono can find them.

**Comment by vlaldis** [comment]
@treziac  Installing librdkafka-dev and librdkafka1 did not help. 
@yousifh It`s .Net framework 4.6.1 console application under mono 5.

We are going to deploy the soft to docker, and deploy it as container, so librdkafka will be added to the container separately. This should fix the problem with deployment to multiple environments.

**Comment by treziac** [comment]
Don't have time now to test, busy on my projects

@yousifh, do you use mono on debian-based system too? Do you have any vustom step in your installation (like copying the .so files), and what is the version of confluent-kafka-dotnet you use?

We might have broke something when fixing an issue on .NetFramework, will lok at this when have time

**Comment by treziac** [comment]
@youfish if you can use docker, can't you use .NetCore? We mainly worked on this one, so it should ork properply on windows, mac, debian (centos seems broker for now, should be fixed on next release)

**Comment by yousifh** [comment]
@treziac yeah Mono running on Ubuntu, no custom steps. Just `dotnet publish` the app and put it in the Docker image. It's running latest confluent-kafka-dotnet

@vlaldis with Docker based deployment I think you should be able to download `librdkafka.so` and put it under `/usr/lib/`? I know this hack workaround is needed to get Kestrel running on Mono for aspnet core

**Comment by treziac** [comment]
dotnet publish => do you mean you are using new csproj format targeting net461? I don't see where you would put mono in a docker image, aren't you using .net core?

**Comment by yousifh** [comment]
@treziac Yeah everything is using new tooling, but when you target net461 you can publish an .exe file for the app and then run it using Mono inside Docker.

**Comment by mhowlett** [comment]
tracking this in PR #418.

**Comment by neptoess** [comment]
Just chiming in that Confluent.Kafka 1.0.0-RC4 NuGet package works with the Mono Docker Hub image. Post-build:
1) Copy the netstandard1.3 Confluent.Kafka.dll to your bin folder
2) Copy debian9-librdkafka.so to libdebian9-librdkafka.so in your bin folder
3) Copy the entire bin folder into your docker container
