### ISSUE TITLE
Manually committing - producer and consumer

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#232]
I am implementing "At-least" once message delivery pattern for our apps. I will like to control when the message gets committed from the producer or consumer. I understand that I can set the "enable auto commit" property to false. 

Is there a method on producer and consumer that can be used to commit messages manually based on app logic?

Thanks,

**Comment by mhowlett** [comment]
The method you're looking for on the consumer is `CommitAsync`.

On the producer, there isn't the concept of 'committing' a message, rather you can wait for a delivery report which tells you when a message has been successfully produced.

**Comment by ashishbhatia22** [comment]
Thanks. When I call commitAsync, will it commit the latest offset that the consumer has read? The design I have is -- A single consumer thread and using .NET reactive, it is handling the individual messages to own thread. I will like to provide control to consumer to commit the message after they have successfully processed

**Comment by mhowlett** [comment]
There are a number of overloads of `commitAsync` - you can either specify offsets explicitly or commit based on the last read message. Note that committed offsets reflect the next message that should be read, not the last successfully read message.
