### ISSUE TITLE
Unable to connect to azure event hub with Confluent.Kafka 2.6 with connection string

### ISSUE THREAD

**Issue by abratv** [confluentinc/confluent-kafka-dotnet#2327]
Anyone else has issue to connect to Azure Event Hub with Kafka using version 2.6?
Simply rolling back to version 2.5.3 make it work again, so I guess its something with 2.6

**Comment by abratv** [comment]
![image](https://github.com/user-attachments/assets/53c77ef5-511b-44a5-93cc-901a866b0622)

**Comment by abratv** [comment]
![image](https://github.com/user-attachments/assets/6008f301-b28f-4e4d-ab9c-828fa355ff21)

**Comment by t03apt** [comment]
Same issue for me.

**Comment by t03apt** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/issues/2331

**Comment by anchitj** [comment]
Same issue as https://github.com/confluentinc/confluent-kafka-dotnet/issues/2335.
The fix is already merged, and it would be included in the next release
