### ISSUE TITLE
Azure Event Hubs: I can produce but not consume

### ISSUE THREAD

**Issue by robertobasile84** [confluentinc/confluent-kafka-dotnet#2331]
Description
===========

With such producer I can write to an Azure Event Hubs:

```csharp
 var config = new ProducerConfig
 {
     BootstrapServers = bootstrapServers,
     SecurityProtocol = SecurityProtocol.SaslSsl,
     SaslMechanism = SaslMechanism.Plain,
     SaslUsername = saslUsername,
     SaslPassword = saslPassword
 };
```

With the same configuration (on the consumer side):

```csharp
 var config = new ConsumerConfig
 {
     BootstrapServers = bootstrapServers,
     SecurityProtocol = SecurityProtocol.SaslSsl,
     SaslMechanism = SaslMechanism.Plain,
     SaslUsername = saslUsername,
     SaslPassword = saslPassword,
     GroupId = consumerGroup,
     EnableSslCertificateVerification = false,
     Debug = "all"
 };
```

I get a lot of errors like the following (and consume method never returns):

[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: Skipping metadata refresh of 1 topic(s): connected: already being requested
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Fetch topic anothertest [2] at offset 42 (leader epoch -1, current leader epoch -1, v2)
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Fetch 1/1/3 toppar(s)
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Sent FetchRequest (v12, 98 bytes @ 0, CorrId 31)
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Disconnected (after 42ms in state UP) (_TRANSPORT): identical to last error: error log suppressed
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Broker changed state UP -> DOWN
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: Broadcasting state change
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Purging bufq with 1 buffers
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Fetch reply: Local: Broker transport failure
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Fetch backoff for 500ms: Local: Broker transport failure
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Purging bufq with 0 buffers
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Updating 0 buffers on connection reset
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: Requesting metadata for 1/1 topics: broker down
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: GroupCoordinator/0: Request metadata for 1 topic(s): broker down
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Broker changed state DOWN -> INIT
[Confluent.Kafka] Debug: [thrd:GroupCoordinator]: GroupCoordinator/0: Sent MetadataRequest (v5, 39 bytes @ 0, CorrId 18)
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: Broadcasting state change
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Broker changed state INIT -> TRY_CONNECT
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: Broadcasting state change
[Confluent.Kafka] Debug: [thrd:sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/boots]: sasl_ssl://smpksmain-eh-3-dev.servicebus.windows.net:9093/0: Delaying next reconnect by 3878ms
[Confluent.Kafka] Debug: [thrd:GroupCoordinator]: GroupCoordinator/0: Received MetadataResponse (v5, 198 bytes, CorrId 18, rtt 39.11ms)
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: ===== Received metadata (for 1 requested topics): broker down =====
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: ClusterId: smpksmain-eh-3-dev.servicebus.windows.net, ControllerId: 0
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: 1 brokers, 1 topics
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0:   Broker #0/1: smpksmain-eh-3-dev.servicebus.windows.net:9093 NodeId 0
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0:   Topic anothertest with 3 partitions
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [0] Leader 0 Epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [0]: leader 0 epoch -1 -> leader 0 epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [0]: skipping offset validation in fetch state none
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [1] Leader 0 Epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [1]: leader 0 epoch -1 -> leader 0 epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [1]: skipping offset validation in fetch state none
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [2] Leader 0 Epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [2]: leader 0 epoch -1 -> leader 0 epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [2]: skipping offset validation for offset 42 (leader epoch -1): no leader epoch set
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: 1/1 requested topic(s) seen in metadata (lookup by name)
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [0]: broker is down: re-query
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [1]: broker is down: re-query
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [2]: broker is down: re-query
[Confluent.Kafka] Debug: [thrd:main]: Requesting metadata for 1/1 topics: refresh unavailable topics
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: Request metadata for 1 topic(s): refresh unavailable topics
[Confluent.Kafka] Debug: [thrd:GroupCoordinator]: GroupCoordinator/0: Sent MetadataRequest (v5, 39 bytes @ 0, CorrId 19)
[Confluent.Kafka] Debug: [thrd:GroupCoordinator]: GroupCoordinator/0: Received MetadataResponse (v5, 198 bytes, CorrId 19, rtt 40.86ms)
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: ===== Received metadata (for 1 requested topics): refresh unavailable topics =====
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: ClusterId: smpksmain-eh-3-dev.servicebus.windows.net, ControllerId: 0
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: 1 brokers, 1 topics
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0:   Broker #0/1: smpksmain-eh-3-dev.servicebus.windows.net:9093 NodeId 0
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0:   Topic anothertest with 3 partitions
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [0] Leader 0 Epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [0]: leader 0 epoch -1 -> leader 0 epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [0]: skipping offset validation in fetch state none
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [1] Leader 0 Epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [1]: leader 0 epoch -1 -> leader 0 epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [1]: skipping offset validation in fetch state none
[Confluent.Kafka] Debug: [thrd:main]: Topic anothertest [2] Leader 0 Epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [2]: leader 0 epoch -1 -> leader 0 epoch -1
[Confluent.Kafka] Debug: [thrd:main]: anothertest [2]: skipping offset validation for offset 42 (leader epoch -1): no leader epoch set
[Confluent.Kafka] Debug: [thrd:main]: GroupCoordinator/0: 1/1 requested topic(s) seen in metadata (lookup by name)

How to reproduce
================

With the previous configuration (pointing to an Azure Event Hub), try to consume with a simple:

```csharp
        consumer.Subscribe(topic);

        CancellationTokenSource cts = new CancellationTokenSource();
        Console.CancelKeyPress += (_, e) =>
        {
            e.Cancel = true;
            cts.Cancel();
        };

        try
        {
            while (true)
            {
                try
                {
                    var consumeResult = consumer.Consume(cts.Token);
                    string logMessage = $"Consumed message '{consumeResult.Message.Value}' at: '{consumeResult.TopicPartitionOffset}'.";
                    Console.WriteLine(logMessage);
                    logWriter.WriteLine(logMessage);
                    logWriter.Flush();

                    // Manually commit the offset.
                    consumer.Commit(consumeResult);
                }
                catch (ConsumeException e)
                {
                    string errorLog = $"Consume error: {e.Error.Reason}";
                    Console.WriteLine(errorLog);
                    logWriter.WriteLine(errorLog);
                    logWriter.Flush();
                }
            }
        }
```

Checklist
=========

Please provide the following information:
 - [X] Confluent.Kafka nuget version. **(2.6.0)**
 - [X] Operating system: **Windows 10**

**Comment by robertobasile84** [comment]
I noticed that going back to 2.5.3 fixed my problem. I guess there is an issue with 2.6.0 in talking to Azure Event Hubs

**Comment by DumbTechLion** [comment]
Having the same problem. Using 2.5.3 fixes it temporarily I guess.

**Comment by anchitj** [comment]
This must be the same issue as https://github.com/confluentinc/confluent-kafka-dotnet/issues/2335. 
The fix is already merged, and it would be included in the next release.

**Comment by anchitj** [comment]
2.6.1 is released which should fix this issue. Feel free to reopen if you're still facing it.
