### ISSUE TITLE
Using vulnerable nuget package Microsoft.Extensions.Caching.Memory

### ISSUE THREAD

**Issue by BjornEGlomsrud** [confluentinc/confluent-kafka-dotnet#2334]
Description
===========
The package Confluent.SchemaRegistry.Serdes.Json v 2.6.0 uses the vulnerable package `Microsoft.Extensions.Caching.Memory` version 8.0.0. Should update to v8.0.1

See also https://github.com/advisories/GHSA-qj66-m88j-hmgj 

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-dotnet/pull/2344
