### ISSUE TITLE
driver 2.6.0 "broker might require SASL authentication" error

### ISSUE THREAD

**Issue by korchak-aleksandr** [confluentinc/confluent-kafka-dotnet#2335]
Description
===========

Same issue on dotnet version as on python https://github.com/confluentinc/confluent-kafka-python/issues/1842

How to reproduce
================

There is one for normal operation in version 2.5.3 and one for the failure in 2.6.0.
You can use logs from attached issue

We have permanent error same as: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 6ms in state UP, 4 identical error(s) suppressed)

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version. 2.6.0
 - [ ] Apache Kafka version. 2.8.1
 - [ ] Client configuration.
 - [ ] Operating system. linux
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by anchitj** [comment]
The fix is already merged, and it would be included in the next release.

**Comment by anchitj** [comment]
2.6.1 is released which should fix this issue. Feel free to reopen if you're still facing it.
