### ISSUE TITLE
AsyncSerde.GetMigrations() expects schema version

### ISSUE THREAD

**Issue by mannerydhe** [confluentinc/confluent-kafka-dotnet#2356]
Description
===========
The `AsyncSerde.GetMigrations()` method in the Confluent.SchemaRegistry library expects the `writerSchema` to include a version number. However, when the `writerSchema` is fetched by ID using the the `RestService.GetSchemaAsync()`, the returned schema does not contain a version, defaulting it to 0. This behavior causes `GetMigrations()` to attempt to retrieve all schema versions from 1 to n (where n is the version of the `readerSchema`). If any of these schema versions (e.g., version 1) have been deleted from the Schema Registry, an exception is thrown stating that the schema version is not found.

The root cause is that the endpoint `/schemas/ids/<id>` does not return the schema version, unlike e.g. `/subjects/<subject>/versions/latest`. Although the schema version and subject can be obtained via `/schemas/ids/<id>/versions`, `RestService.GetSchemaAsync(int id, string format)` and `RestService.GetSchemaBySubjectAndIdAsync(string subject, int id, string format)` does not utilize this endpoint to fetch the correct version number for the writerSchema.

How to reproduce
================
1. Create schema
2. Add a couple of versions
3. Delete version 1 (not necessary but will throw exception)
4. Produce a message using version 2
5. Consume using latest version

Confluent.SchemaRegistry nuget version: 2.6.1
Kafka version: 3.6
AvroDeserializerConfig: 
{
    SubjectNameStrategy = SubjectNameStrategy.TopicRecord,
    UseLatestVersion = true,
}

**Comment by rayokota** [comment]
@mannerydhe , thanks for reporting this, I'll work on a fix

**Comment by mannerydhe** [comment]
Thanks for the quick response!
When do you expect this to be available in a release?
