### ISSUE TITLE
How to use ContinueWith method

### ISSUE THREAD

**Issue by RammG** [confluentinc/confluent-kafka-dotnet#237]
Question for how to use continuewith method after call produce method.
 private void SendKafkaTopic(long? serviceId, List<ECPServiceQueue> queueObjectList)
        {
            if (String.IsNullOrEmpty(KafkaServer))
                return;
            var config = new Dictionary<string, object> { { "bootstrap.servers", KafkaServer } };
            ECPServiceQueueDataManager queueDM = new ECPServiceQueueDataManager();
            config["broker.version.fallback"] = "0.8.2.2";

            using (var producer = new Producer<string, string>(config, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8)))
            {
                foreach (ECPServiceQueue qObj in queueObjectList)
                {
                    //Start threads for each queueId
                    qObj.QueueStatus = ECPServiceQueueStatus.PROCESSING;
                    qObj.IsDirty = true;
                    queueDM.SaveQueueChanges(qObj);

                    RDFResult rdfData = DataManagerFactory.GetDataManager<RDFResult>().GetDataByID(qObj.RDFResultID.Value);
                    if (rdfData != null)
                    {
                        string topicName = String.Format("{0}.{1}", TopicName, serviceId.ToString());
                        var deliveryResult = producer.ProduceAsync(topicName, rdfData.GraphURI, rdfData.RDF);

                        //Console.WriteLine($"Partition: {deliveryResult.Result.Partition}, Offset: {deliveryResult.Result.Offset}");

                        deliveryResult.ContinueWith(task =>
                        {
                            Console.WriteLine($"*******Partition: {task.Result.Partition}, Offset: {task.Result.Offset}");
                            if (task.Result.Error.Code == ErrorCode.NoError)
                            {
                                qObj.IsDeleted = true;
                                DataManagerFactory.GetDataManager<ECPServiceQueue>().SaveData(qObj);
                            }
                            else
                            {
                                qObj.QueueStatus = ECPServiceQueueStatus.NEWRECORD;
                                qObj.IsDirty = true;
                                queueDM.SaveQueueChanges(qObj);
                                Console.WriteLine(task.Result.Error.ToString());
                            }
                        });
                    }
                }
                //producer.Flush(1000);
            }
        }

Logic in continuewith never get called here. But if I use Console.WriteLine($"Partition: {deliveryResult.Result.Partition}, Offset: {deliveryResult.Result.Offset}"); right after produceasync it works, since it forced to get the deliveryResult here. But it is not the preferred way, ContinueWith suppose to be call back after async call to send message. 
Anything I am missing here?

**Comment by treziac** [comment]
You should not create a Producer everytime - only create one and use it as singleton in your whole process;

Your problem here (I think) is that you dispose your producer before getting the callback - your task will never complete (when calling dispose, you stop polling librdkafka and delivery will never be served).

Am I right saying that uncommenting your flush, perhaps with hight time given your network, will work?
