### ISSUE TITLE
Reading messages in batches

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#239]
Can a consumer read multiple messages at the same time? For high throughput, I will like to see if I can read a group of messages as a batch. Once the batch is read, it is handed over to the .NET process to process them in parallel. Please confirm

**Comment by mhowlett** [comment]
see #224. the consumer is very performant. it gives you the messages one at a time, but you can hand these off to worker threads to process in parallel if you want.
