### ISSUE TITLE
Question: Planned API support

### ISSUE THREAD

**Issue by bschmidtbauer** [confluentinc/confluent-kafka-dotnet#24]
Is there any plan/timeline to support some of the missing requests (or at least I didn't find them)? e.g. OffsetFetchResponse & OffsetCommitResponse that could be used outside of a producer/consumer in more of an administrative fashion.

**Comment by edenhill** [comment]
The protocol requests are not exposed themselves, but the corresponding functionality is provided through abstracted APIs.

To retrieve committed offsets (OffsetFetch), use Committed:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/e318dcae5c8b5ab41132e596c192a510b7fd456d/src/Confluent.Kafka/Consumer.cs#L250

And to commit offsets, use Commit:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/e318dcae5c8b5ab41132e596c192a510b7fd456d/src/Confluent.Kafka/Consumer.cs#L234

**Comment by mhowlett** [comment]
yeah - we don't have (and don't plan to implement) an abstraction for the concept of a Kafka client separate to Producer and Consumer (following rd_kafka_new in librdkafka which has a type parameter which needs to be either producer or consumer).

[more feedback on this encouraged if you have it]

**Comment by bschmidtbauer** [comment]
I think the challenge for us is that we have a large investment in .NET, it is where our skill sets lie and our existing custom application base is almost exclusively built with it (1,000+ apps).

Having a native client (producer/consumer) is fantastic and will get us out of using the REST proxy for any new/existing applications that want to start taking advantage of Kafka (currently a very low percentage are leveraging Kafka).

The administrative side of Kafka is where only having the producer/consumer abstraction makes it more difficult.  Doing things like finding all the consumer groups (or by name) and then being able to drill down to see what is happening with each (e.g. topics they are consuming, offsets they are at and the topic is at, resetting those offsets, etc.) feels like it going against the grain of what was intended.  The concept of a transient consumer is also something that we will be trying to do - basically admin ability to peek messages in given topics.  I suspect this is possible with the consumer since we would control if offsets are committed or not.

Does that make sense?

**Comment by edenhill** [comment]
Both Producer and Consumer share the same underlying client implementation and the differention in run mode only enables or disables some features: such as consumer groups for the consumer.

A Consumer instance won't force you to join a consumer group and consume messages if you dont call Assign() or Subscribe(), you are free to use it for such administrative tasks that you outlined.

Same thing with the Producer, it won't do much until you actually call Produce() to produce messages.

Offset management, group coordinator, etc, requires a Consumer instance (since producers currently don't make any use of that functionality and thus has it disabled).

Let us know if you are missing any particular administrative API. (KIP-4 support (Topic manipulation) is on the backlog.)

**Comment by bschmidtbauer** [comment]
Thanks for the info - we'll try this out

**Comment by mhowlett** [comment]
One more thing related to consumers: My understanding is that nothing related to consumer groups will come into play unless you call .Subscribe(). If you create a Consumer and .Assign() to some collection of topic / partitions and start reading (as in the SimpleConsumer example), a consumer group will not be created. You could do this for lightweight peeking at messages, or if you really wanted to, bypass the group management provided by Kafka altogether and do it yourself. The Consumer constructor requires the "group.id" config property to be specified even when used in the above way (I guess the reasoning behind that is it's assumed consumers will pretty much always be members of groups), but it's never used.

If my understanding above is wrong, someone please point that out :-)

**Comment by mhowlett** [comment]
closing, though I have some new ideas about breaking out admin like functionality from `Producers` and `Consumers` that isn't documented yet.
