### ISSUE TITLE
Consumer and Producer metrics

### ISSUE THREAD

**Issue by HenningRoigaard** [confluentinc/confluent-kafka-dotnet#240]
Does the client emit any metrics for producer and consumer instances, and if so, how can I access them?
A reference will suffice, if I have missed some documentation.

For reference:
The java client emits a number of jmx metrics (http://kafka.apache.org/documentation/#monitoring) for both consumers and producers.

**Comment by mhowlett** [comment]
`statistics.interval.ms` config setting + `OnStatistics` event on `Producer` and `Consumer`.
