### ISSUE TITLE
offset.store.method=file does not work

### ISSUE THREAD

**Issue by wangjia184** [confluentinc/confluent-kafka-dotnet#242]
Here is the global configuration

```
    private static Dictionary<string, object> ConstructConfig(string brokerList)
    {
        string dir = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "cache", "kafka");
        if (!Directory.Exists(dir))
            Directory.CreateDirectory(dir);
        return new Dictionary<string, object>
        {
            { "group.id", Environment.GetEnvironmentVariable("Cluster.Name") },
            { "offset.store.method", "file" },  // Offset commit store method: 'file' - local file store 
            { "offset.store.path", dir }, // Path to local file for storing offsets. 
            { "offset.store.sync.interval.ms", 0 }, // Use -1 to disable syncing; and 0 for immediate sync after each write. 
            { "enable.auto.commit", false },
            { "statistics.interval.ms", 60000 },
            { "bootstrap.servers", brokerList },
            { "default.topic.config", new Dictionary<string, object>()
                {
                    { "auto.offset.reset", "smallest" }
                }
            }
        };
    }
```
With the following code, I can receive the messages.
But there is no offset file created in the target directory. When I start the app again, I receive the messages since the beginning again. Surely I have write permission on the offset.store.path

```
           Consumer consumer = new Consumer<MessageKey, byte[]>(ConstructConfig(_brokerList), new MessageKeyDeserializer(), new ByteArrayDeserializer());
                       consumer.OnError += OnError;
            consumer.OnConsumeError += OnConsumerError;
            consumer.OnPartitionEOF += OnPartitionEOF;

            consumer.OnPartitionsAssigned += (_, partitions) =>
            {
                string ids = string.Join( ",", partitions.Select(p => p.Partition.ToString()));
                log.Info($"Assigned partitions: [{ids}], member id: {consumer.MemberId}");
                consumer.Assign(partitions);
            };

            consumer.OnPartitionsRevoked += (_, partitions) =>
            {
                string ids = string.Join(",", partitions.Select(p => p.Partition.ToString()));
                log.Info($"Revoked partitions: [{ids}]");
                consumer.Unassign();
            };


            consumer.Subscribe(new List<string>(){ _topic });

           while (true)
           {
               try
               {
                   msg = null;
                   if (!consumer.Consume(out msg, ts))
                       continue;
                   OnMessage(msg);

                   log.InfoFormat($"Offset = {msg.Offset}");

                   await consumer.CommitAsync(msg);
               }
               catch (Exception ex)
               {
                   // ...
                   break;
               }
           }
```

Is this a bug?

**Comment by treziac** [comment]
There seems to be a related issue on librdkafka : https://github.com/edenhill/librdkafka/issues/1254

**Comment by abhishekakumar** [comment]
@treziac @mhowlett - Any updates on this. I am also having the same issue. I have tried many configuration but still cannot get the offset commit to a local file. It goes to the broker.

 rdkafka#consumer-1OFFSET7[thrd:main]: Topic test [0]: stored offset 131, committed offset -1001
 rdkafka#consumer-1OFFSET7[thrd:main]: Topic test [0]: setting stored offset 131 for commit
 rdkafka#consumer-1COMMIT7[thrd:main]: localhost:9092/0: Committing offsets for 1 partition(s): cgrp auto commit timer
 rdkafka#consumer-1OFFSET7[thrd:main]: localhost:9092/0: Enqueue OffsetCommitRequest(v1, 1/1 partition(s))): cgrp auto commit timer
 rdkafka#consumer-1RECV7[thrd:localhost:9092/0]: localhost:9092/0: Received FetchResponse (v2, 36 bytes, CorrId 14, rtt 110.00ms)
 rdkafka#consumer-1FETCH7[thrd:localhost:9092/0]: localhost:9092/0: Topic test [0] MessageSet size 0, error "Success", MaxOffset 131, Ver 2/2
 rdkafka#consumer-1FETCH7[thrd:localhost:9092/0]: localhost:9092/0: Fetch topic test [0] at offset 131 (v2)
 rdkafka#consumer-1FETCH7[thrd:localhost:9092/0]: localhost:9092/0: Fetch 1/1/1 toppar(s)
 rdkafka#consumer-1SEND7[thrd:localhost:9092/0]: localhost:9092/0: Sent FetchRequest (v2, 63 bytes @ 0, CorrId 15)
 rdkafka#consumer-1SEND7[thrd:localhost:9092/0]: localhost:9092/0: Sent HeartbeatRequest (v0, 82 bytes @ 0, CorrId 16)
 rdkafka#consumer-1SEND7[thrd:localhost:9092/0]: localhost:9092/0: Sent OffsetCommitRequest (v1, 118 bytes @ 0, CorrId 17)
 rdkafka#consumer-1SEND7[thrd:localhost:9092/0]: localhost:9092/0: Sent OffsetCommitRequest (v1, 118 bytes @ 0, CorrId 18)
 rdkafka#consumer-1RECV7[thrd:localhost:9092/0]: localhost:9092/0: Received FetchResponse (v2, 36 bytes, CorrId 15, rtt 109.00ms)
 rdkafka#consumer-1FETCH7[thrd:localhost:9092/0]: localhost:9092/0: Topic test [0] MessageSet size 0, error "Success", MaxOffset 131, Ver 2/2
 rdkafka#consumer-1FETCH7[thrd:localhost:9092/0]: localhost:9092/0: Fetch topic test [0] at offset 131 (v2)
 rdkafka#consumer-1FETCH7[thrd:localhost:9092/0]: localhost:9092/0: Fetch 1/1/1 toppar(s)
 rdkafka#consumer-1SEND7[thrd:localhost:9092/0]: localhost:9092/0: Sent FetchRequest (v2, 63 bytes @ 0, CorrId 19)
 rdkafka#consumer-1RECV7[thrd:localhost:9092/0]: localhost:9092/0: Received HeartbeatResponse (v0, 2 bytes, CorrId 16, rtt 140.00ms)
 rdkafka#consumer-1RECV7[thrd:localhost:9092/0]: localhost:9092/0: Received OffsetCommitResponse (v1, 20 bytes, CorrId 17, rtt 140.00ms)
 rdkafka#consumer-1RECV7[thrd:localhost:9092/0]: localhost:9092/0: Received OffsetCommitResponse (v1, 20 bytes, CorrId 18, rtt 140.00ms)
 rdkafka#consumer-1COMMIT7[thrd:main]: localhost:9092/0: OffsetCommit for 1 partition(s): cgrp auto commit timer: returned: Success
 rdkafka#consumer-1COMMIT7[thrd:main]: All commited, call fetch_start.
 rdkafka#consumer-1COMMIT7[thrd:main]: localhost:9092/0: OffsetCommit for 1 partition(s): cgrp auto commit timer: returned: Success
 rdkafka#consumer-1COMMIT7[thrd:main]: All commited, call fetch_start.

**Comment by edenhill** [comment]
File-based offset commits with consumer groups won't really work since a new consumer on some other machine can be assigned the same partition, and it would have no way to read the committed offsets on file from another machine, right?

**Comment by edenhill** [comment]
The file store method is a legacy from the low level consumer days, it has not been tested with the high-level consumer.
Is there a reason you don't want to commit offsets to the broker?

**Comment by abhishekakumar** [comment]
Ok. I am having a problem where if the broker is restarted, at times the committed offsets are lost and it replays old messages to the consumer. I don't have control of the configuration on the broker so don't know why the broker will lose committed offsets.
I have tried setting offset.reset to latest to get the latest from broker but even that did not work. So I am open to suggestions what to try to make it work.
