### ISSUE TITLE
No consumption after Subscribe()

### ISSUE THREAD

**Issue by agoretsky** [confluentinc/confluent-kafka-dotnet#243]
Hello!
I have 3 brokers: kafka1, kafka2, kafka3.
I've created a topic:
`/opt/kafka/bin/kafka-topics.sh —zookeeper localhost:2181 —create —replication-factor 2 —partitions 10 —topic mytopic`

Then started simple console app producer:
```
using Confluent.Kafka;
using Confluent.Kafka.Serialization;
using System;
using System.Collections.Generic;
using System.Text;

namespace Kafka.Producer
{
    class Program
    {
        static void Main(string[] args)
        {
            string brokerList = "kafka1:9092,kafka2:9092,kafka3:9092";
            string topicName = "mytopic";

            var config = new Dictionary<string, object> { { "bootstrap.servers", brokerList } };

            using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
            {
                Console.WriteLine($"{producer.Name} producing on {topicName}. q to exit.");
                string text;
                while ((text = Console.ReadLine()) != "q")
                {
                    text = DateTime.Now.ToString();
                    var result = producer.ProduceAsync(topicName, null, text).Result;
                    Console.WriteLine($"Partition: {result.Partition}, Offset: {result.Offset}");
                }
            }

            Console.ReadKey();
        }
    }
}
```
In producer console I can see that messages were sent successfully

Then I started console app consumer:
```
using System;
using System.Collections.Generic;
using System.Text;
using Confluent.Kafka.Serialization;

namespace Confluent.Kafka.Examples.AdvancedConsumer
{
    public class Program
    {
        private static Dictionary<string, object> constructConfig(string brokerList) =>
            new Dictionary<string, object>
            {
                { "group.id", Guid.NewGuid() },
                { "enable.auto.commit", false },
                { "bootstrap.servers", brokerList },
                {"partition.assignment.strategy", "roundrobin" },
                { "default.topic.config", new Dictionary<string, object>()
                    {
                        { "auto.offset.reset", "smallest" }
                    }
                }
            };

        public static void Run_Poll(string brokerList, List<string> topics)
        {
            using (var consumer = new Consumer<Null, string>(constructConfig(brokerList), null, new StringDeserializer(Encoding.UTF8)))
            {
                consumer.OnMessage += (_, msg)
                    => Console.WriteLine($"Topic: {msg.Topic} Partition: {msg.Partition} Offset: {msg.Offset} {msg.Value}");

                consumer.OnPartitionEOF += (_, end)
                    => Console.WriteLine($"Reached end of topic {end.Topic} partition {end.Partition}, next message will be at offset {end.Offset}");

                consumer.OnError += (_, error)
                    => Console.WriteLine($"Error: {error}");

                consumer.OnConsumeError += (_, msg)
                    => Console.WriteLine($"Error consuming from topic/partition/offset {msg.Topic}/{msg.Partition}/{msg.Offset}: {msg.Error}");

                consumer.OnOffsetsCommitted += (_, commit) =>
                {
                    Console.WriteLine($"[{string.Join(", ", commit.Offsets)}]");

                    if (commit.Error)
                    {
                        Console.WriteLine($"Failed to commit offsets: {commit.Error}");
                    }
                    Console.WriteLine($"Successfully committed offsets: [{string.Join(", ", commit.Offsets)}]");
                };

                consumer.OnPartitionsAssigned += (_, partitions) =>
                {
                    Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}], member id: {consumer.MemberId}");
                    consumer.Assign(partitions);
                };

                consumer.OnPartitionsRevoked += (_, partitions) =>
                {
                    Console.WriteLine($"Revoked partitions: [{string.Join(", ", partitions)}]");
                    consumer.Unassign();
                };

                consumer.OnStatistics += (_, json)
                    => Console.WriteLine($"Statistics: {json}");

                consumer.Subscribe(topics);

                Console.WriteLine($"Subscribed to: [{string.Join(", ", consumer.Subscription)}]");

                var cancelled = false;
                Console.CancelKeyPress += (_, e) => {
                    e.Cancel = true; // prevent the process from terminating.
                    cancelled = true;
                };

                Console.WriteLine("Ctrl-C to exit.");
                while (!cancelled)
                {
                    consumer.Poll(TimeSpan.FromMilliseconds(100));
                }
            }
        }

        public static void Main(string[] args)
        {
            var brokerList = "kafka1:9092,kafka2:9092,kafka3:9092";
            var topics = new List<string> { "mytopic" };

            Run_Poll(brokerList, topics);
        }
    }
}
```
But everything that I can see in consumer console is:

> Subscribed to: [mytopic]
> Ctrl-C to exit.

There are no more messages about consumption.

Note that I was able to consume messages when used Assign() method instead of Subscribe().

I'have tried different combinations of settings, but got no result. 

What am I doing wrong? Thanks

**Comment by treziac** [comment]
Hi
Everything looks fine. Could you add "debug", "cgrp,topic,fetch" to your consumer conf?
Does it work when removing partition.assignment.strategy?

**Comment by agoretsky** [comment]
@treziac, kafka version is 0.10.2.1, library version is 0.9.5, I have this issue both on Windows 10 and Mac OS 10.12.5 under .NET Core

> 7|2017-06-26 22:57:04.054|rdkafka#consumer-1|MEMBERID| [thrd:app]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": updating member id "(not-set)" -> ""
7|2017-06-26 22:57:04.079|rdkafka#consumer-1|BRKREASSIGN| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" management reassigned from broker (none) to :0/internal
7|2017-06-26 22:57:04.079|rdkafka#consumer-1|CGRPSTATE| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" changed state init -> wait-broker (v1, join-state init)
7|2017-06-26 22:57:04.079|rdkafka#consumer-1|BRKASSIGN| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" management assigned to broker :0/internal
7|2017-06-26 22:57:04.090|rdkafka#consumer-1|CGRPOP| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" received op SUBSCRIBE (v0) in state wait-broker (join state init, v1 vs 0)
7|2017-06-26 22:57:04.090|rdkafka#consumer-1|SUBSCRIBE| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": subscribe to new subscription of 1 topics (join state init)
7|2017-06-26 22:57:04.090|rdkafka#consumer-1|UNSUBSCRIBE| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": unsubscribe from current unset subscription of 0 topics (leave group=no, join state init, v1)
7|2017-06-26 22:57:04.090|rdkafka#consumer-1|CGRPJOINSTATE| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" changed join state init -> wait-unassign (v1, state wait-broker)
7|2017-06-26 22:57:04.091|rdkafka#consumer-1|UNASSIGN| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": unassign done in state wait-broker (join state wait-unassign): without new assignment: unassign (no previous assignment)
7|2017-06-26 22:57:04.091|rdkafka#consumer-1|CGRPJOINSTATE| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" changed join state wait-unassign -> init (v1, state wait-broker)
7|2017-06-26 22:57:04.091|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": no broker available for coordinator query: intervaled in state wait-broker
7|2017-06-26 22:57:04.093|rdkafka#consumer-1|CGRPOP| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" received op GET_SUBSCRIPTION (v0) in state wait-broker (join state init, v1 vs 0)
Subscribed to: [mytopic]
Ctrl-C to exit.
7|2017-06-26 22:57:04.279|rdkafka#consumer-1|SUBSCRIPTION| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": effective subscription list changed from 0 to 1 topic(s):
7|2017-06-26 22:57:04.279|rdkafka#consumer-1|SUBSCRIPTION| [thrd:main]:  Topic mytopic with 10 partition(s)
7|2017-06-26 22:57:04.279|rdkafka#consumer-1|BRKREASSIGN| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" management reassigned from broker :0/internal to host:9092/1095
7|2017-06-26 22:57:04.279|rdkafka#consumer-1|LEADER| [thrd:host:9092/bootstrap]: host:9092/1095: Mapped 0 partition(s) to broker
7|2017-06-26 22:57:04.279|rdkafka#consumer-1|BRKUNASSIGN| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" management unassigned from broker handle :0/internal
7|2017-06-26 22:57:04.279|rdkafka#consumer-1|BRKASSIGN| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" management assigned to broker host:9092/1095
7|2017-06-26 22:57:04.279|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": no broker available for coordinator query: intervaled in state wait-broker
7|2017-06-26 22:57:06.086|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: host2:9092/1093: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": querying for coordinator: intervaled in state wait-broker
7|2017-06-26 22:57:06.171|rdkafka#consumer-1|CGRPCOORD| [thrd:main]: host2:9092/1093: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" GroupCoordinator response error: Broker: Group coordinator not available
7|2017-06-26 22:57:07.089|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: host2:9092/1093: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": querying for coordinator: intervaled in state wait-broker
7|2017-06-26 22:57:07.147|rdkafka#consumer-1|CGRPCOORD| [thrd:main]: host2:9092/1093: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" GroupCoordinator response error: Broker: Group coordinator not available
7|2017-06-26 22:57:08.091|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: host:9092/1095: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": querying for coordinator: intervaled in state wait-broker
7|2017-06-26 22:57:08.149|rdkafka#consumer-1|CGRPCOORD| [thrd:main]: host:9092/1095: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" GroupCoordinator response error: Broker: Group coordinator not available
7|2017-06-26 22:57:09.093|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: host2:9092/1093: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": querying for coordinator: intervaled in state wait-broker
7|2017-06-26 22:57:09.165|rdkafka#consumer-1|CGRPCOORD| [thrd:main]: host2:9092/1093: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" GroupCoordinator response error: Broker: Group coordinator not available
7|2017-06-26 22:57:10.095|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: host:9092/1095: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": querying for coordinator: intervaled in state wait-broker
7|2017-06-26 22:57:10.151|rdkafka#consumer-1|CGRPCOORD| [thrd:main]: host:9092/1095: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" GroupCoordinator response error: Broker: Group coordinator not available
7|2017-06-26 22:57:11.098|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: host3:9092/1094: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": querying for coordinator: intervaled in state wait-broker
7|2017-06-26 22:57:11.173|rdkafka#consumer-1|CGRPCOORD| [thrd:main]: host3:9092/1094: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" GroupCoordinator response error: Broker: Group coordinator not available
7|2017-06-26 22:57:12.103|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: host2:9092/1093: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": querying for coordinator: intervaled in state wait-broker
7|2017-06-26 22:57:12.175|rdkafka#consumer-1|CGRPCOORD| [thrd:main]: host2:9092/1093: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" GroupCoordinator response error: Broker: Group coordinator not available
7|2017-06-26 22:57:13.107|rdkafka#consumer-1|CGRPQUERY| [thrd:main]: host:9092/1095: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490": querying for coordinator: intervaled in state wait-broker
7|2017-06-26 22:57:13.162|rdkafka#consumer-1|CGRPCOORD| [thrd:main]: host:9092/1095: Group "a278c188-2f0d-4ecc-afe2-d1f96af23490" GroupCoordinator response error: Broker: Group coordinator not available

**Comment by treziac** [comment]
This seems to be a broker issue. Can you check  your broker logs if you have any related inputs?
Does it work with the console-consumer?

From experience, this may be due to some inconsistency in zookeeper (either because creating/suppressing test cluster multiple times or manual action improperly done) or of one of your broker, you could try to reinstall them if it's on test/local, or check logs / conf in details if you can't

**Comment by agoretsky** [comment]
`/opt/kafka/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic mytopic --from-beginning` - this works
`/opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic mytopic --from-beginning` - this doesn't

Will find problem of brokers installation/configuration. Thank you!

**Comment by treziac** [comment]
First one use the old consumer - coordination was done in zookeper
Second one use the new consumer, where coordinator is needed

So this indeed is a problem on coordinator - broker side. Do you see anything on your brokers logs (server.log)?

**Comment by agoretsky** [comment]
Yes, there are some exceptions:
```
[2017-06-27 08:08:17,294] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
kafka.common.KafkaException: Failed to acquire lock on file .lock in /opt/data/kafka. A Kafka instance in another process or thread is using this directory.
	at kafka.log.LogManager.$anonfun$lockLogDirs$1(LogManager.scala:107)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.log.LogManager.lockLogDirs(LogManager.scala:103)
	at kafka.log.LogManager.<init>(LogManager.scala:65)
	at kafka.server.KafkaServer.createLogManager(KafkaServer.scala:658)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:208)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2017-06-27 08:08:17,295] INFO [Kafka Server 1095], shutting down (kafka.server.KafkaServer)

[2017-06-27 08:56:32,193] FATAL [Kafka Server 1093], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/1093. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:411)
	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:394)
	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:72)
	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:51)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:269)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)

[2017-06-27 08:56:29,377] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/1094. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:411)
	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:394)
	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:72)
	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:51)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:269)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
```

**Comment by treziac** [comment]
I think you registred two brokers with same id/logs.dir, or you started a broker multiple times. Check your server.properties and kafka process (kill broker and restart them with kafka-server-stop.sh if necessary)

**Comment by mhowlett** [comment]
Kafka configuration issue - closing. thanks for debugging @treziac!
