### ISSUE TITLE
will .net library support wildcard topic name?

### ISSUE THREAD

**Issue by mogliang** [confluentinc/confluent-kafka-dotnet#245]
Description
===========
Thank you guys for providing kafka .net library.

I want to subscribe several topics with pattern 'binlog-*', however, it seems .net library doesn't support wildcard topic name, also i didn't find method to get topic list. 

Is there a way for me to get topic list by pattern? 

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.9.5
 - [x] Operating system: windows 10
- [x] Critical issue: no
- [ ] Apache Kafka version: 
 - [ ] Client configuration:
  - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts

**Comment by edenhill** [comment]
Yes, for Subscribe() you may prefix the topic name with "^" to turn on regex matching.

**Comment by mogliang** [comment]
thanks a lot!
