### ISSUE TITLE
Reccomended way not to lose producer messages

### ISSUE THREAD

**Issue by devteamexpress** [confluentinc/confluent-kafka-dotnet#246]
This isn't a bug but a general question with the library.

What is the recommended way to ensure that messages aren't lost if the .net process is restarted while Kafka is down. Is their a way to recover the buffer or are they gone forever?

Would appreciate any advice on the subject?

**Comment by edenhill** [comment]
There is currently no way to purge and retrieve the queue of outstanding messages, but you can keep track of the messages in-flight yourself between produce() and the delivery report.
