### ISSUE TITLE
SSL handshake errors when using client authentication

### ISSUE THREAD

**Issue by smiffy1989** [confluentinc/confluent-kafka-dotnet#247]
Description
===========
When producing and consuming (both consumer.Consume and consumer.Poll) with SSL client authentication enabled, SSL Handshake errors are returned from the consumer.OnError event:

Error: ssl://kafka3.test.net:9093/bootstrap: SSL handshake failed: .\ssl\s3_both.c:408: error:1408E0F4:SSL routines:ssl3_get_message:unexpected message: : client authentication might be required (see broker log) ErrorReason: ssl://kafka3.test.net:9093/bootstrap: SSL handshake failed: .\ssl\s3_both.c:408: error:1408E0F4:SSL routines:ssl3_get_message:unexpected message: : client authentication might be required (see broker log) BrokerError: False LocalError: True Code: Local_Ssl

This seems to be intermittent and doesn't seem to cause a problem since it is still possible to produce and consume to/from all brokers.

- Tested both Windows & Ubuntu based Clusters and kafka_2.12-0.10.2.1 & kafka_2.12-0.11.0.0
- Generated certs from our own CA and using the script here: https://github.com/edenhill/librdkafka/blob/master/tests/gen-ssl-certs.sh

I suspect that the ca/cert/key isn't being provided to every broker every time as using the openssl client without passing in the ca/cert/key does result in the same error:
140414289491608:error:1408E0F4:SSL routines:ssl3_get_message:unexpected message:s3_both.c:406:

How to reproduce
================
Follow SSL setup guide here: https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

Use the Producer & Consumer examples with the OnError events subscribed.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 
0.9.5
 - [x] Apache Kafka version: 
kafka_2.12-0.10.2.1 & kafka_2.12-0.11.0.0
 - [x] Client configuration:
{ "bootstrap.servers", brokerList },
{ "api.version.request", "true" },
{ "security.protocol", "SSL" },
{ "ssl.ca.location", @"C:\Users\luke smith\Desktop\gen\ca-cert" },
{ "ssl.certificate.location", @"C:\Users\luke smith\Desktop\gen\kafkaadminclient.pem" },
{ "ssl.key.location", @"C:\Users\luke smith\Desktop\gen\kafkaadminclient.key" },
{ "ssl.key.password", "abcdefgh" }
 - [x] Operating system: 
Ubuntu 16.04 LTS & Windows Server 2012 for the brokers. Windows 10 for the client.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
I'm not sure what is required here? Happy to provide anything to help get this resolved if you can let me know how!
 - [x] Provide broker log excerpts
No errors are logged into the broker logs.
 - [ ] Critical issue
Everything seems to work as normal the majority of the time, but occasionally all brokers will fail.

**Comment by treziac** [comment]
Ca you try using nuget librdkafka.redist 0.11.0-RC2 (in place of 0.9.5 which is transitive with Confluent.Kafka 0.9.5), it solved some SLL errors. 

given debug, you can add { "debug", "security" } in config to have logs related to ssl

**Comment by smiffy1989** [comment]
Apologies, I'm not a dev and know just about enough C# to get by so bare with me!

I've installed the librdkafka.redist 0.11.0-RC2 NuGet package with:
Install-Package librdkafka.redist -Pre

I've added the client config and now I'm getting additional stuff output to the console and still getting the errors:

> 7|2017-06-29 13:34:25.987|rdkafka#producer-1|SSL| [thrd:app]: Loading CA certificate(s) from file C:\Users\luke smith\Desktop\gen\ca-cert
> 7|2017-06-29 13:34:25.989|rdkafka#producer-1|SSL| [thrd:app]: Loading certificate from file C:\Users\luke smith\Desktop\gen\kafkaadminclient.pem
> 7|2017-06-29 13:34:25.994|rdkafka#producer-1|SSL| [thrd:app]: Loading private key file from C:\Users\luke smith\Desktop\gen\kafkaadminclient.key
> 7|2017-06-29 13:34:25.999|rdkafka#producer-1|SSLPASSWD| [thrd:app]: Private key file "C:\Users\luke smith\Desktop\gen\kafkaadminclient.key" requires password
> 
> -----------------------------------------------------------------------
> Producer rdkafka#producer-1 producing on topic test.
> -----------------------------------------------------------------------
> 7|2017-06-29 13:34:26.067|rdkafka#producer-1|SSLVERIFY| [thrd:ssl://kafka3.test.net:9093/bootstrap]: ssl://kafka3.test.net:9093/bootstrap: Broker SSL certificate verified
> Error: ssl://kafka1.test.net:9093/bootstrap: SSL handshake failed: .\ssl\s3_both.c:408: error:1408E0F4:SSL routines:ssl3_get_message:unexpected message: : client authentication might be required (see broker log)
> Error: ssl://kafka4.test.net:9093/bootstrap: SSL handshake failed: .\ssl\s3_both.c:408: error:1408E0F4:SSL routines:ssl3_get_message:unexpected message: : client authentication might be required (see broker log)
> 7|2017-06-29 13:34:26.072|rdkafka#producer-1|SSLVERIFY| [thrd:ssl://kafka2.test.net:9093/bootstrap]: ssl://kafka2.test.net:9093/bootstrap: Broker SSL certificate verified
> 7|2017-06-29 13:34:27.086|rdkafka#producer-1|SSLVERIFY| [thrd:ssl://kafka4.test.net:9093/bootstrap]: ssl://kafka4.test.net:9093/4: Broker SSL certificate verified
> 7|2017-06-29 13:34:27.089|rdkafka#producer-1|SSLVERIFY| [thrd:ssl://kafka1.test.net:9093/bootstrap]: ssl://kafka1.test.net:9093/1: Broker SSL certificate verified
> Partition: 0, Offset: 177
> Partition: 0, Offset: 178
> Partition: 0, Offset: 179
> Partition: 0, Offset: 180
> Partition: 0, Offset: 181
> Partition: 0, Offset: 182

**Comment by treziac** [comment]
Thanks!

Problem will continue to be tracked in #61. I assume it's a race condition on the ssl library used at startup without downside, we  have to investigate a bit more. By any chance if this is a test cluster, can you confirm there is no error when only one broker is up?

**Comment by mhowlett** [comment]
I believe this is resolved (#61 is closed). Please re-open if the problem exists in v0.11.5.

**Comment by dsanan0714** [comment]
I have received truststore.jks & keystore.jks file from a team who manages kafka. We are required to build a producer application in .NET using these .jks files. I have used below commands to convert .jks files to required format as .jks is not compatible with .net applications.

keytool -importkeystore -srckeystore truststore.jks -destkeystore truststore.p12 -deststoretype PKCS12
openssl pkcs12 -in truststore.p12 -nokeys -out truststore.cer.pem

keytool -importkeystore -srckeystore keystore.jks -destkeystore keystore.p12 -srcstoretype jks -deststoretype pkcs12
openssl pkcs12 -in keystore.p12 -out keystore.pem
openssl rsa -in keystore.pem -out newrsakeystore.pem

Output of above commands are assinged to producer config properties as below:
<img width="352" alt="Untitled" src="https://user-images.githubusercontent.com/105284193/167616005-f768a606-e0e0-416d-9f3d-aaa728dc14f9.png">


After running getting error: "SSL Handshake failed. client SSL Authentication might be required (see ssl.key.location and ssl.certificate.location)"
<img width="945" alt="Untitled1" src="https://user-images.githubusercontent.com/105284193/167616036-4bb38a8d-b713-4758-a2d7-3f09b38cb03e.png">


Could anyone please help what wrong i am doing here?
@mhowlett @htims1989 @treziac @astubbs @ijuma
