### ISSUE TITLE
Add Committed() API

### ISSUE THREAD

**Issue by liu-hongwei** [confluentinc/confluent-kafka-dotnet#251]
Description
===========
the API QueryWatermarkOffsets is unstable, 

 var config = new Dictionary<string, object>
            {
                { "group.id", Guid.NewGuid().ToString("N") },
                { "bootstrap.servers", this.brokers },
                { "client.id", Guid.NewGuid().ToString("N") }
            };

            using (var consumer = new Consumer<string, string>(config, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
            {
                consumer.Assign(new List<TopicPartitionOffset> { new TopicPartitionOffset(this.topic, 0, 0) });
                var partition = new TopicPartition(this.topic, 0);
                 var  watermarkOffsets = consumer.GetWatermarkOffsets(partition);
          }

the FIRST time calls on GetWatermarkOffets returns below:

![image](https://user-images.githubusercontent.com/9062771/27809270-014be888-6003-11e7-937d-ac6385736729.png)

then Second time call to it returns below:
![image](https://user-images.githubusercontent.com/9062771/27809307-428b6e0e-6003-11e7-84f8-4562125cdae9.png)

if i want to get the lag for specific consumer group on a topic, without call the Assign method before Position call, i could not get the committed offsets.

i think it is useful to expose the API for query lag for given consumer group without actually consume the messages.

How to reproduce
================
see above code

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.9.5, 
 - [ ] Apache Kafka version: 2.11-0.10.2
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is documented behaviour:
 * GetWatermarkOffsets returns the last known (cached) lo, hi offsets and is very fast.
 * QueryWatermarkOffsets queries the broker for the actual lo, hi offsets and is slow since it requires a broker roundtrip or more.

See docs here:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/3f48fd8b87831f6e1b7eba939a4bbf00fb584555/src/Confluent.Kafka/Consumer.cs#L564

**Comment by liu-hongwei** [comment]
i searched at the librdkafka, there is the method

rd_kafka_cgrp_offsets_fetch

which returns committed offsets for given consumer group,

why is this not exposed in this .net sdk ? 

we need this so we can get lag by using this api and the QueryWatermarkOffsets.

what do you think?

Thanks
Hongwei

**Comment by edenhill** [comment]
It is exposed as `rd_kafka_committed()` in librdkafka's public API, but seems to be lacking from the .NET API.

**Comment by liu-hongwei** [comment]
ok, so i can expose it from .net in my private branch.  hope in new official release you expose it in .NET API.

Thanks
Hongwei

**Comment by treziac** [comment]
Commited is already available in Consumer Api, internally calling rd_kafka_committed
https://github.com/confluentinc/confluent-kafka-dotnet/blob/0.9.5.x/src/Confluent.Kafka/Consumer.cs#L1083

**Comment by mhowlett** [comment]
Yep, this exists. Note that in the 1.0 API, this will be changing to an async version: `CommittedAsync`.
