### ISSUE TITLE
improve performance for API QueryWatermarkOffsets by supporting list of partitions rather than one

### ISSUE THREAD

**Issue by liu-hongwei** [confluentinc/confluent-kafka-dotnet#253]
Description
===========
while i am trying to get latest data offsets for a topic, i use the API QueryWatermarkOffsets, but it does not accept list of partitions , only accept one partition, which makes it very low performance.

i suggest to support list of partitions, then internally you **group the partitions by leader, so you can send a single request to the same broker with multiple partitions** and get all the offsets for those partitions in just one response.

my testing code as below.
using (var consumer = new Consumer<string, string>(config, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
            {
                var metadata = consumer.GetMetadata(true, TimeSpan.FromMinutes(5));

                TopicPartition partition = null;
                WatermarkOffsets watermarkOffsets = null;
                List<TopicPartitionOffsetError> comittedOffsets = null;
                while (true)
                {
                    var target = metadata.Topics.FirstOrDefault(x => x.Topic == this.topic);
                    if (target.Partitions != null)
                    {
                        Console.WriteLine(string.Format(
                            "Topic{0,10}Partition{1,5}High{2,10}Low{3,10}Comitted{4,10}Lag{5,10}", "", "", "", "", "",
                            ""));

                        foreach (var pm in target.Partitions)
                        {
                            partition = new TopicPartition(target.Topic, pm.PartitionId);

                            watermarkOffsets = consumer.QueryWatermarkOffsets(partition);

                            comittedOffsets = consumer.Committed(new List<TopicPartition>() { partition }, TimeSpan.FromMinutes(1));

                            var comittedOffset = comittedOffsets.FirstOrDefault().Offset;

                            var lag = watermarkOffsets.High - comittedOffset.Value;

                            Console.WriteLine(string.Format("{0, 10}{1, 5}{2, 10}{3, 10}{4, 10}{5,10}", this.topic,partition.Partition, watermarkOffsets.High, watermarkOffsets.Low, comittedOffset.Value,lag));
                        }
                    }

                    Console.WriteLine("");
                    Thread.Sleep(10);
                }

            }

without the change, the API is really not performing.

How to reproduce
================
see above

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:0.9.5
 - [ ] Apache Kafka version: 2.11-0.10.2
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This needs to be implemented in librdkafka first.

**Comment by mhowlett** [comment]
currently not high priority. if you want this feature, please +1 here to let us know.
