### ISSUE TITLE
Question: Exactly-Once Semantics

### ISSUE THREAD

**Issue by geofflamrock** [confluentinc/confluent-kafka-dotnet#255]
Description
===========
Apologies if this isn't the correct forum to ask this, given it's not an issue as such but more a question.

With Kafka 0.11, there is support for an application to produce/consume with exactly-once semantics using transactions, are there any plans to add support for this? Thanks.

How to reproduce
================
N/A

Checklist
=========
N/A

Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Github is also for question :)

This will have to be implemented by librdkafka, this is already on roadmap.

**Comment by geofflamrock** [comment]
Fantastic thanks, do you by chance know of a github issue in librdkafka that is tracking this at all so I can follow it? I did a quick search and couldn't find anything. Thanks.

**Comment by treziac** [comment]
This was mentionned here:
https://github.com/edenhill/librdkafka/issues/1092

**Comment by geofflamrock** [comment]
Thanks, should I close this issue now or leave it open to track support for this in the .NET client?

**Comment by mhowlett** [comment]
librdkafka v0.11.0 (and hence the dotnet client v0.11.0) understands the new message format added in 0.11.0 but idempotence and transaction functionality is yet to come. this is on the roadmap but we don't have an ETA for you at this point.

**Comment by ayoung** [comment]
I am waiting for this as well. Keep us updated.

**Comment by adrianwright** [comment]
I am waiting for this too.

**Comment by mhowlett** [comment]
we haven't started working on it but we will soon. it should be here within 6 months (it's a big feature).

**Comment by ZebpayArjunVachhani** [comment]
@mhowlett is it still in road map or is it implemented.

**Comment by mhowlett** [comment]
it's absolutely going to be implemented. idempotent producer will be done before transactions. can't yet guarantee a release date, but it's a current open task.

**Comment by Tenseiga** [comment]
+1

**Comment by Rymix** [comment]
Also waiting transactions, gonna wait

**Comment by tomnagly** [comment]
Hello, any update?

**Comment by mhowlett** [comment]
1.0 has idempotent producer. The consumer side of transaction support is underway here: https://github.com/mhowlett/librdkafka/tree/isolation1

**Comment by tomnagly** [comment]
Thank you @mhowlett 
It is not clear to me if I can use it on dotnet client?

**Comment by mhowlett** [comment]
yep, simply set the `EnableIdempotence` property to `true`, and you're good to go!
