### ISSUE TITLE
Exception on producer example

### ISSUE THREAD

**Issue by israelaltar** [confluentinc/confluent-kafka-dotnet#257]
Description
===========
SimpleProducer example doesn't work, it throws NullReference Exception when running it.
 The exception is being thrown from: Producer.cs line 1049: serializingProducer.KeySerializer;

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.9.5
 - [ ] Apache Kafka version: 0.9.5
 - [ ] Client configuration:
 - [ ] Operating system: windows 7
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Yes, there is an issue on master, will be fixed. You can replace
`Consumer<Null, string>(config, null, new StringDeserializer(Encoding.UTF8)))` with
`Consumer<Null, string>(config, new NullDeserializer(), new StringDeserializer(Encoding.UTF8)))`
(same with Producer and NullSerializer)

Note it does not impact releases, simple producer will work corectly there

**Comment by israelaltar** [comment]
Great! Many thanks.

**Comment by treziac** [comment]
You can cherry pick https://github.com/confluentinc/confluent-kafka-dotnet/commit/68c03c3c1a230caf53052a47d45771083b85c039
Also note there is a new librdkafka.redist version you might want to target if you which to test latest improvements
