### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by EranOfer** [confluentinc/confluent-kafka-dotnet#258]
Description
===========
I am getting AccessViolationException in my testing   .
version Confluent.Kafka (0.11.0-RC1)

System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Confluent.Kafka.Impl.LibRdKafka.NativeMethods.rd_kafka_consumer_poll(IntPtr rk, IntPtr timeout_ms)
   at Confluent.Kafka.Impl.SafeKafkaHandle.ConsumerPoll(Message& message, IntPtr millisecondsTimeout)
   at Confluent.Kafka.Consumer.Consume(Message& message, Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(Message`2& message, Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Poll(TimeSpan timeout)
   at .<ConsumptionsLoop>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at KafkaConsumer.ConsumptionsLoop()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

How to reproduce
================

Run polling loop in a thread started via Task.Run
Call dispose on different thread .

```
consumer = new Consumer<string, string>(configDictionary, stringDeserializer, stringDeserializer);

//Constructor
Task.Run (()=>{
while (CancellationTokenSource.IsCancellationRequested == false)
 {
  consumer.Poll(PollTimeOut);
 }
});

public void Dispose()  {
CancellationTokenSource.Cancel()
consumer.Dispose();
}
```

**Comment by treziac** [comment]
When you call cancel, you are not awaiting your task. Thus, followinf can happen:

- On Poll thread: pass the test (not cancelled), jump to other thread
- Cancel token
- Begin dispose => destroy consumer handle
- Jump back to poll thread: call Poll => crash, the handle was disposed

You need to wait your task

**Comment by EranOfer** [comment]
Theank for your ansenr.
I know how to fix the code.

I think it should never throw AccessViolationException and this is the real issue.

**Comment by EranOfer** [comment]
## **AccessViolationException and try/catch blocks**
Starting with the .NET Framework 4, AccessViolationException exceptions thrown by the common language runtime are not handled by the **catch** statement in a structured exception handler if the exception occurs outside of the memory reserved by the common language runtime
https://msdn.microsoft.com/en-us/library/system.accessviolationexception.aspx

**Comment by treziac** [comment]
We could throw ObjectDisposedException in this case for most method

**Comment by EranOfer** [comment]
Sound great

**Comment by afrancoc2000** [comment]
How did you solve this? I'm having the same problem inside an azure function and a worker role

**Comment by afrancoc2000** [comment]
Sorry just added an await some where :P

**Comment by mhowlett** [comment]
@afrancoc2000 what version of Confluent.Kafka are you using?

**Comment by afrancoc2000** [comment]
I was using v0.11.2 but the problem was mine, I didn't awaited the call to poll messages

**Comment by mhowlett** [comment]
thanks @afrancoc2000 - we shouldn't be throwing access violation exceptions anywhere, so reopening this as a reminder to investigate this case. low priority bug though.

**Comment by ashishbhatia22** [comment]
EranOfer - Can you share details on how you fixed this. I am using the following code during shutdown and we still see this exception:

      public bool Cancel()
        {
            cancelled = true;

            //TODO: Raise event when consumer wants to cancel this
            ConsumerPoll();

            return true;
        }

        /// <summary>
        /// Shuts down the message-bus subscription.
        /// </summary>
        /// <returns></returns>
        public bool ShutDown()
        {
            MessageConsumer.Unsubscribe();
            Cancel();
            Dispose(true);
            return true;
        }

**Comment by mhowlett** [comment]
An access violation exception indicates you're probably trying to use a client after it's been disposed. Mostly we catch that this is happening and throw a better exception, but in some cases we don't / can't.

- You don't need to unsubscribe explicitly - call `Dispose` on your consumer and this will be automatic.
- What is `ConsumerPoll`? I don't understand why you'd be calling a method called that in a method called `Cancel`.

**Comment by ashishbhatia22** [comment]
Cancel is when we want to stop the consumer from processing new messages from a topic.

We have implemented the following dispose pattern. We have few apps that are hosted in IIS and developers typically issue iisreset. Please confirm if you see any issues with this..

 protected virtual void Dispose(bool disposing)
        {
            if (isDisposed) return;

            try
            {
                if (disposing)
                {
                    generalLog.Log(LOGLEVELS.Info, "Dispose Consumer Object");
                    // Call Shutdown on Message Consumer
                    ShutDown();
                  //  MessageConsumer.Unsubscribe();
                }
            }
            finally
            {
                MessageConsumer.Dispose();
                isDisposed = true;
            }
        }

**Comment by mhowlett** [comment]
tracking this in #577
