### ISSUE TITLE
OnPartitionsAssigned fallback doesn't work

### ISSUE THREAD

**Issue by edenhill** [confluentinc/confluent-kafka-dotnet#26]
If the application doesn't provide an OnPartitionsAssigned delegate then the Consumer should call Assign() itself, and there's code that attempts to do this in the Rebalance handler.
But since the consumer.OnPartitionsAssigned is always set to a lambda that checks if the application's OnPartitionsAssigned is set it or not, the code that checks for the fallback doesn't actually kick-in so we end up with Assign() not being called automatically.

The best option would be if the Consumer wouldn't register a rebalance_cb at all if the application developer doesn't want On..Assign/On..Revoke but it seems this isn't really possible since those delegates are registered after rd_kafka_t creation.

**Comment by mhowlett** [comment]
this was resolved by PR #32
