### ISSUE TITLE
Application crashing when creating/disposing consumer when all brokers are down

### ISSUE THREAD

**Issue by nollotta** [confluentinc/confluent-kafka-dotnet#264]
Description
===========
I am using the Confluent.Kafka.dotnet library within my application and it is working great, except when we test one error scenario: 
All brokers are offline and my application starts up. It creates an instance of a consumer, and tries to GetMetaData, which fails since no broker is online. Everything appears to work, and in my code I then call Dispose on the consumer, which returns successfully. What I see happening is that after a certain amount of time (2-5 minutes), my application crashes due to an exception popping up from the librdkafka library.

I did some debugging, and it appears that the error callback is being called from the librdkafka library, but since I have already called dispose there is no callback, which throws the exception.

Here is the exception caught in the debugger (a few minutes after dispose was called):
_Managed Debugging Assistant 'CallbackOnCollectedDelegate' : 'A callback was made on a garbage collected delegate of type 'Confluent.Kafka!Confluent.Kafka.Impl.LibRdKafka+ErrorDelegate::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'_

This results in this .NET/application exception, which crashes the application:
_System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=mscorlib
  StackTrace:
   at System.StubHelpers.StubHelpers.CheckCollectedDelegateMDA(IntPtr pEntryThunk)
   at Confluent.Kafka.Impl.LibRdKafka.NativeMethods.rd_kafka_destroy(IntPtr rk)
   at Confluent.Kafka.Impl.SafeKafkaHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize()_

How to reproduce
================
(1) Kill all kafka brokers and zookeepers
(2) Start application
   (2a) Create a consumer Confluent.Kafka.Consumer<string,string>, and subscribe to the standard events (OnError, OnMessage, OnConsumeError, OnStatistics, OnLog, etc),
   (2b) Make a call to consumer.GetMetadata(true, 30000)
   (2c) Catch the Kafka exception that occurs and log (or whatever you want to do with it)
   (2d) Call consumer.Dispose()
   (2e)  Wait 2-5 minutes and you will see the exception

You can reproduce with producer as well, if you create producer and then publish something, then call dispose.

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version:  0.9.5
 - [X] Apache Kafka version: 2.12-0.10.2.1
 - [X] Client configuration:

- socket.timeout.ms=60000
- max.in.flight.requests.per.connection=1
- enable.auto.commit=true
- enable.auto.offset.store=true
- auto.commit.interval.ms=5000
- fetch.wait.max.ms=10
- socket.blocking.max.ms=10
- fetch.error.backoff.ms=50
- fetch.message.max.bytes=1048576
- statistics.interval.ms=60000
- default.topic.config[auto.offset.reset]=latest

 - [X] Operating system: Windows 10
 - [] Provide logs (with "debug" : "..." as necessary in configuration)
 - [] Provide broker log excerpts
 - [] Critical issue

**Comment by mhowlett** [comment]
thanks for the detailed bug report @nollotta 

looks like either `rd_kafka_destroy` isn't getting called as expected or librdkafka is generating errors even after the handle has been destroyed. we'll take a look.

**Comment by nollotta** [comment]
Thanks. I had a thought that might explain this behavior. Since all my brokers are down, calls won't go through to the brokers (I get the error on the GetMetaData call quickly). When I call Dispose on the consumer, even though it returns, I am wondering if it somehow doesn't clean up everything properly. Looking at the description for the Dispose method on the consumer, it says:
_"Releases all resources used by this Consumer. This call will block until the consumer has revoked its assignment, calling the rebalance event if it is configured, committed offsets to broker, and left the consumer group. [UNSTABLE-API] - The Dispose method should not block. We will separate out consumer close functionality from this method."_

**Comment by nollotta** [comment]
You can close this issue. This was a bug in our code, not in Kafka. The exception is the expected behavior when you don't properly clean up your unmanaged code that is referenced from managed code.

I dug into our code a bit more and tested a few variations to verify, the issue was definitely in our code, not the Kafka code. In this corner case (when meta data call fails because all brokers are down), the consumer was not getting disposed properly (we were not explicitly calling Dispose on the consumer), so it had not been fully cleaned up. The behavior makes total sense once that was clear. Even though our code thought everything was disposed, the consumer had not been fully disposed/garbage collected, so it was still alive and then it makes total sense that the error handler error gets called and the error happens since my callback was cleaned up.

I have fixed our code, and now it works as expected even in this case.

Thanks for a great library - very easy to use and understand!

**Comment by mhowlett** [comment]
no worries @nollotta - thanks for looking further and reporting back. it's actually v. useful for us to get an idea of where people are making mistakes. if lots of people get tripped up by the same thing, we might want to make changes to try and prevent it.

great to hear you like the library.

**Comment by chiru1205** [comment]
This is definitely related to #226
