### ISSUE TITLE
Consuming application crash.

### ISSUE THREAD

**Issue by eyantiful** [confluentinc/confluent-kafka-dotnet#269]
Description
===========
[dump-anlz.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1159143/dump-anlz.txt)

Hi,
We have applications which consuming Kafka topic crashing.
From the dump excerpt attached we see stack overrun exception.
We haven't been able to find any previous issues in rdKafka with this issue.

How to reproduce
================
We dont currently have reproduction.
It crashes occasionally.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:rdkafka 0.9.1
 - [ ] Apache Kafka version: 0.9.1
 - [ ] Client configuration:
 - [ ] Operating system:Windows 2012R2
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
try using the latest version of the client (0.11.0-RC3) and see if the problem persists. I don't recognise it explicitly, but we've made a number of changes that may be related.

**Comment by treziac** [comment]
If the problem persists (I assume you call some methods after having diposed the client), can you provide some code?
