### ISSUE TITLE
dotnet quit unexpectedly

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#27]
I'm using Confluent.Kafka in an application in which I create a (non serializing) producer and then do nothing more with it. The application does a lot of processing and at semi-random points in time (doesn't take too long ~ 20 seconds) exits with "dotnet quit unexpectedly". This is repeatable. The problem is (repeatably) resolved if I don't create the producer, so I'm sure Confluent.Kafka is at fault.

One time (but only one time, most of the time not), an error including the following was printed to the console: "pointer being freed was not allocated"

Maybe this is something to do with the pointer to the kafka config being accessed after being garbage collected. I swapped out .Dup with .DangerousGetHandle() when setting the config. Maybe the problem is related to that.

We could write a test for this - create a producer / consumer then do lots of arbitrary processing to give the GC a work out.

**Comment by mhowlett** [comment]
switching .DangerousGetHandle() back to .Dup() fixes this, but I haven't yet put any effort into understanding why.

**Comment by edenhill** [comment]
Not sure it has bearing on this, but the *_conf_t objects passed to rd_kafka_new() and rd_kafka_topic_new() are freed by librdkafka and the application mustn't touch them after a successful such _new call

**Comment by bschmidtbauer** [comment]
FWIW - When hosting a consumer or producer in a console I get an access violation when exiting the console.

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Confluent.Kafka.Impl.LibRdKafka.NativeMethods.rd_kafka_conf_destroy(IntPtr conf)
   at Confluent.Kafka.Impl.LibRdKafka.conf_destroy(IntPtr conf)
   at Confluent.Kafka.Impl.SafeConfigHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()

The code is effectively:
```
        static void Main(string[] args)
        {
            var config = new Dictionary<string, object>
            {
               // config here
            };
            using (var consumer = new Confluent.Kafka.Consumer(config))
            {
                PrintConsumerGroups(consumer);
            }

            Console.WriteLine("Press Enter to exit");
            Console.ReadLine();
        }
```
Is there a way to avoid this?  In the example above it was just trying to use the ListGroups method but it happens the same whether I do that or not.  The exception happens after you hit enter to satisfy the last ReadLine method.

**Comment by edenhill** [comment]
I'm getting this too if the offset commit is called prior to exiting.

**Comment by mhowlett** [comment]
ok, that's the problem (i knew it would be something simple like this - just hadn't had a chance to look).

I missed that ReleaseHandle was ever going to get called.

In rdkafka-dotnet, the configuration wraps a librdkafka configuration struct and this hangs around after construction of the client. in confluent.kafka the native config info is not required after construction and so I no longer duplicate reference and keep it around. I missed where it was getting cleaned up.

Will fix all this up.
