### ISSUE TITLE
ProduceAsync does not return when no kafka server is running

### ISSUE THREAD

**Issue by Arash-Sabet** [confluentinc/confluent-kafka-dotnet#272]
Description
===========
Invoking ```await producer.ProduceAsync(topicName, null, val)``` in an ```async``` method does not return delivery report while kafka server is down or when it cannot be reached to. The code waits for an infinite amount of time but nothing happens.

How to reproduce
================

See above.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: "Confluent.Kafka" Version="0.11.0"
 - [x] Apache Kafka version: The recent stable release.
 - [ ] Client configuration:
 - [x] Operating system: Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts 
 - [x] Critical issue

**Comment by mhowlett** [comment]
Did you wait an infinite amount of time to be sure :-) Try setting the config properties `message.timeout.ms` and `message.send.max.retries` to lower values and see if you still see the problem. I verified there is no problem on .net core (though the way this is implemented on net452 and net46 is different). If you're still seeing a problem please provide a small example demonstrating.

```
            var config = new Dictionary<string, object> 
            { 
                { "bootstrap.servers", brokerList },
                { "message.send.max.retries", 0 },
                { "default.topic.config", new Dictionary<string, object>()
                    {
                        { "message.timeout.ms", 5000 }
                    }
                }
            };
```

**Comment by Arash-Sabet** [comment]
Well, I can say that we waited at least 60 seconds but I did not get anything back. The code is in .net core though. After applying the configuration that you suggested we are way in better shape. We were able to proceed with examining deliveryReport.Error.HasError flag and decide based upon it. Previously, that piece of code was never reached.

At this point, I'm not sure whether I should close this thread as "resolved" or leave it open and up to you for further investigations. Maybe it makes sense to initialize the configuration dictionary with some default ```message.send.max.retries``` and ```message.timeout.ms``` values if one forgets to supply them.

**Comment by treziac** [comment]
`message.timeout.ms` is 300 000 by default, so 5 min
Available configuration and default values are listed here: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by mhowlett** [comment]
also `message.send.max.retries` default is 2, so the expected time you'll need to wait for a delivery report is 15min.

**Comment by mhowlett** [comment]
oh, i should say thanks for reporting - it's v. useful for us to get data points on where people are getting confused - may cause us to make changes to address in the future.

**Comment by Arash-Sabet** [comment]
@mhowlett you're welcome. I think a small piece of document or note somewhere in the wiki helps a lot.

**Comment by shwen4477** [comment]
Sorry, but in  0.11.3 I have reproduced this infinite waiting despite configuration:

`

	{
		{ "bootstrap.servers", config.Servers },  
		{ "queue.buffering.max.ms", 5 },
		{ "queue.buffering.max.kbytes", 10240 },
		{ "topic.metadata.refresh.interval.ms", 200000 },
		{ "message.send.max.retries", 3 },
		{ "default.topic.config", new Dictionary<string, object>
			{
				{ "message.timeout.ms", 3000 },
				{ "request.required.acks", "1" },
			}
		}
	};
`
0.11.2 is ok. Returns "Message timed out" .

**Comment by enniopastore** [comment]
Same issue of shwen4477.
On 0.11.13 the timeout error is never reached.

**Comment by xs2bharat** [comment]
Yes i am using 0.11.4, it is waiting for infinite time.

**Comment by syedadeeliqbal** [comment]
When I run it as a Windows Service/application it is stuck infinitely. But when debugging and stepping through the code it timeouts properly... Any clues? I tried 0.11.2, 0.11.4 and 0.11.5
