### ISSUE TITLE
[Question] How to do topic partitioning and config consumers 

### ISSUE THREAD

**Issue by NineMvp** [confluentinc/confluent-kafka-dotnet#274]
Do you have any document or example project?

**Comment by mhowlett** [comment]
Examples: https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples

The API docs (via intellisense or by reading the code) are thorough, we're working on putting them online in a browsable format.

More thorough walkthroughs / documentation is coming.

For general kafka docs, check out 
http://docs.confluent.io/current/
http://kafka.apache.org/documentation/

**Comment by treziac** [comment]
Partitioner is not available yet, the librdkafka default one will be used (consistent random) - but you can explicitly specify a partition when producing, in addition to the topic name in ProduceAsync method
For consumer, you can find samples in the `example` folder

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdvancedConsumer/Program.cs
https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/SimpleConsumer

All available configurations (both consumer and producer) are here : https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
Most things you can find in librdkafka wiki apply on confluent-kafka

This project wiki has to be improved,, I give you this point ;) Don't hesitate if you have issues or feedback!

**Comment by sfrooster** [comment]
What's holding-up the custom partitioner?  It was available in the library you took over so...

**Comment by mhowlett** [comment]
Questions over API design mostly. Related were changes we were making to serializer configuration (which have been sorted out now). We're no longer blocked on this, but custom partitioners are not at the top of the priority queue. That said I want this in and it shouldn't take much.. 

Finally, note that although many people ask for this, in most scenarios use cases of custom partitioners is usually not necessary.

**Comment by sfrooster** [comment]
We wrote a custom Murmur2 partitioner to match the one used by the java client.  How would you recommend we accomplish the same without being able to do the same here?

**Comment by mhowlett** [comment]
right, that is a very legitimate use case.
presently, there is no way to accomplish this.

**Comment by mhowlett** [comment]
The best I can suggest is look to at rdkafka-dotnet for how to implement it and add it to the library yourself. It shouldn't be hard - all the p/invoke calls are still exposed internally. Then feel free to open a PR :-). Even if we decided to change the API you came up with, it wouldn't be a big deal to swap out with whatever the eventual decision is. Shouldn't need to let this block you.

**Comment by sfrooster** [comment]
Maybe we're confusing goals here.  In the version we're using, TopicConfig has a property named CustomPartitioner of type Partitioner which will be used if set.  Otherwise the Topic operates as normal.

We've already coded our own Murmur2 partitioner and set it into CustomPartitioner so we're good as long as that feature exists - which it currently doesn't.  Seems that'd be easy to add but the fact you're talking about pInvokes makes me think there's a wholesale rework underway.

We'd like to switch to this one but I think we'll wait until an easy migration path is available.  Thanks!

**Comment by mhowlett** [comment]
No - not confusing goals. Everything needed to implement the feature exists internally, it's just not exposed publicly yet.

**Comment by sfrooster** [comment]
Got it.  Looking forward to when we can make the switch. Thanks!

**Comment by mhowlett** [comment]
tracking this in #587
