### ISSUE TITLE
Debug Contexts?

### ISSUE THREAD

**Issue by BenjaminHolland** [confluentinc/confluent-kafka-dotnet#276]
Description
===========
from the OnLog Event handler

> You can specify one or more debug contexts using the 'debug'
>         ///     configuration property and a log level using the 'log_level'
>         ///     configuration property to enable more verbose logging,
>         ///     however you shouldn't typically need to do this.

Where are these context strings documented?

How to reproduce
================
Look at the documentation.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: N/A
 - [ ] Apache Kafka version: N/A
 - [ ] Client configuration: N/A
 - [ ] Operating system: N/A
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration) N/A
 - [ ] Provide broker log excerpts N/A
 - [ ] Critical issue N/A

**Comment by mhowlett** [comment]
see the entry for the debug config property here:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
