### ISSUE TITLE
SASL Handshake not supported by broker - false alarm?

### ISSUE THREAD

**Issue by vinodres** [confluentinc/confluent-kafka-dotnet#277]
Description
===========
I am keep seeing following error

> Subscriber Error: Details - Code [Local_Authentication], **IsLocalError** **[True]**, IsBrokerError [False], Reason [sasl_plaintext://mycorpmessaging:9092/2: Failed to initialize SASL authentication: SASL Handshake not supported by broker (required by mechanism SCRAM-SHA-256)]

But it does not appear to be preventing the consumer from working. The above error keep on occurring. It appears like the error is just noise.

How to reproduce
================
Configure the client to use SASL and rest of the code is similar to AdvancedConsumer.cs from samples. In my environment the "bootstrap.servers" url is a VIP going thru F5 router. 

```
var config = new Dictionary<string, object>()
                {
                    {"group.id", $"TEST-GROUP"},
                    {"client.id", "TEST"},
                    {"enable.auto.commit", false},
                    {"bootstrap.servers", "mycorpmessaging:9092"},
                    //Begin Security config
                    {"sasl.mechanisms", "SCRAM-SHA-256"},
                    {"security.protocol", "SASL_PLAINTEXT"},
                    {"sasl.username", 'testuser"},
                    {"sasl.password", "testpassword"},
                    {"api.version.request", "true"},
                    //End Security config
                    {
                        //Topic level configuration
                        "default.topic.config", new Dictionary<string, object>()
                        {
                            {"auto.offset.reset", "latest"}
                        }
                    }
                };
```

Whenever messages are produced, consumer is receiving them without any issues. Everything appears to be working as expected. But the above error is keep on pumping into logs. Just want to see if anyone has any thoughts on what might be causing it.

Any advice will be greatly appreciated.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:0.11.0
 - [ ] Apache Kafka version: 0.9
 - [ ] Client configuration:
 - [ ] Operating system: Windows Server 2016
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Thanks for report!

I'm not 100% sure (as it was for sasl  and not ssl and did not test SCRAM-SHA-256 myself), but it may be related to ssl handshake fail discussed at end of #61 : there seem to be a race condition when connecting to multiple broker due to way the ssl / sasl statically linked library is used, which will be investigated.
This seems to occur when there are multiple broker in the cluster (with a single broker, this does never fail), and is random. Are you in the same case? If yes, there doesn't seem to be any downside (except the error when initializing connection)

Can you run with the config "debug" = "security" and provide the logs?
Also, do you see any related log on broker side? (I don't think so)

Thanks!

**Comment by vinodres** [comment]
I have 3 brokers running behind the VIP. Let me capture additional info requested by you after enabling "debug" = "security". I will gather any server side logs as well.  I will post in next reply.

**Comment by mhowlett** [comment]
from #285 

> "This issue is most likely due to timeout of the ApiVersionRequest (10s) which makes it revert to the 0.9 broker feature set that does not have SASL Handshake support.
> The workaround for that is to set: 
> `api.version.fallback.ms=0 and broker.version.fallback=0.10.0`
