### ISSUE TITLE
Confusing Subscribe/Assign Semantics.

### ISSUE THREAD

**Issue by BenjaminHolland** [confluentinc/confluent-kafka-dotnet#278]
It's not at all clear how these methods are intended to be used, and there doesn't appear to be any documentation. Looking into the code, they seem to use the same underlying calls to rdkafka and use features not exposed to the .net API (the use of the unassigned partition identifier). The relationship between Subscription and Assignment is similarly fuzzy. 

Looking at the java documentation, it seems like Assign can be called outside of the event handler. but there's not much information about how this plays with Subscribe, since both Subscribe and Assign overwrite data. For instance, I cannot discern what is supposed to happen in the following scenario.

Main()
```
//Event handler stuff that appends whatever partitions are assigned to Btopic to the assignments.
var tpo=new TopicParitionOffset("ATopic",0,Offset.Beginning);
consumer.Assing(tpo);
consumer.Subscribe("BTopic")
...
consumer.Poll(TimeSpan.FromSeconds(10));
```

I'd expect the final result to be that Subsciption contains "ATopic,BTopic" and that Assignments "ATopic:0:-1,BTopic:?:?,BTopic:?:?...", but this doesn't seem to be the case.

**Comment by treziac** [comment]
Subscribe and assign (as you do) are exlusive

### Subscribe
Subscribe use consumer group (group id).
The consumer will automatically receive assignment from kafka coordinator, where partitions from the topics subscribed will be distributed among the members of the group.

For example, if you have 2 consumers with the same group.id, and both subscribe to topic "topic" with 2 partitions, the first consumer will receive assignment to topic:0 and the second to topic:1
You can get new assignment automatically when the members of the group (or the number of partition of a topic) change
The assignments are received via the OnPartitionsAssigned  and OnPartitionsRevoked event. If you register to those event, you will have to call Assign and Unassign yourself in your event handler (as in the sample linked below), and you can change the values to different offset if needed

For an sample usage, see advanced consumer here:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdvancedConsumer/Program.cs#L83

### Assign
Assign will force assignment to a given list of topic/partition/offset
Actually subscribe call assign, bet get assignment from coordinator
example here: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/SimpleConsumer/Program.cs#L43

**Comment by BenjaminHolland** [comment]
So what's the program flow for subscribing to some topics and assigning
others? This seems like it should be possible by passing an invalid
partition number in the TopicPartitionOffset when calling assign, but this
doesn't seem to work.

**Comment by mhowlett** [comment]
Either manually `Assign` to a specific set of topic/partitions, or `Subscribe` to a set of topics. If you want to do both, use more than one `Consumer` instance.

**Comment by mhowlett** [comment]
closing, #592, #593 are relevant.
