### ISSUE TITLE
Logging when exception is thrown

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#281]
Description
===========
I am trying to write a message to a remote kafka server. Produce Aync method is invoked and I can catch the message timeout error. I will like to find out additional details on why the library is not able to talk to remote server. Is there a way to configure logging for the package to write debug/error logs in log4net config file

How to reproduce
================
Invoke ProduceAsync operation to the server that does not exist.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue - false

**Comment by mhowlett** [comment]
set the `debug` configuration property (refer to https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) and if you want to log somewhere other than the console, add a handler to `OnLog` on the producer.

**Comment by ashishbhatia22** [comment]
Thanks! On further review of Kafka logs, it seems the library only supports IPV4 when connecting to server. Is this correct?

**Comment by mhowlett** [comment]
It should support IPV6. Are you specifying a hostname? The following is a really old issue, but it may still be relevant:
https://github.com/edenhill/librdkafka/issues/23

**Comment by ashishbhatia22** [comment]
yes, If I specify a host name, it translates to IPV4 address. The machine that is hosting Kafka only supports IPV6 over VPN..

**Comment by mhowlett** [comment]
maybe try setting a hostname in /etc/hosts (or however you do this on Windows if you're on windows) instead of using DNS.
