### ISSUE TITLE
Producer setting

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#282]
Description
===========
I am trying to control the number of messages in producer in-memory queue. Even though I have defined the following settings for the producer, it still takes approx. 15 seconds before messages are written to kafka cluster. 

    ["queue.buffering.max.kbytes"] = 10,
     ["queue.buffering.max.ms"] = 100,
     ["queue.buffering.max.messages"] = 1,
     ["auto.commit.interval.ms"] = kafkaConfig.producerconfig.Properties["autocommitintervalms"] is set to 10

Can you please confirm which producer setting takes precedence when definining how many messages to buffer in-memory before writing the message to Kafka? It seems that even though I've defined to only buffer 1 message in the in-memory queue, there is some other setting that is taking precedence and controlling when the message gets pushed to Kafka? Thanks,

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
It should take much less than 15 seconds to produce a message (with the default settings, or with any of the settings you have defined above). I suspect some external problem.

`auto.commit.interval.ms` is not relevant here - it's a consumer config property.

try setting the `debug` config property to `all` and look at the log messages for problems. If you can't figure it past the output here and we'll have a look.

**Comment by treziac** [comment]
If you are on windows (please complete the checklist ;) ), also try setting `socket.nagle.disable` to `false`. This will (whould) not resolve the 15s problem, but it can solve a `1s => some ms` problem.
