### ISSUE TITLE
Implement KTable/KStream

### ISSUE THREAD

**Issue by MaitreDede** [confluentinc/confluent-kafka-dotnet#286]
Description
===========

Add KTable/KStream implementation, eventually with Linq support.

**Comment by mhowlett** [comment]
sounds great, but you forgot to attach the code for review :-).

seriously though, yes we would like to add a kstreams implementation and it's on our roadmap, but it's not an immediate priority.

**Comment by MaitreDede** [comment]
Ok, thanks :)

**Comment by rsaltrelli** [comment]
Can we get an update on this?  We're a .NET shop and would love to be able to make use of all the Kafka features from .NET.

**Comment by mhowlett** [comment]
Confluent is currently focused on KSQL as a language agnostic alternative. We don't have near term plans for building kafka streams implementations in other languages.

I have been working on some streaming abstractions for .NET in my spare time, but there's still a long way to go: https://github.com/mhowlett/howlett-kafka-extensions

**Comment by rsaltrelli** [comment]
Thanks.  I'll give KSQL a try.
