### ISSUE TITLE
Confluent.Kafka.KafkaException Local: Queue Full

### ISSUE THREAD

**Issue by mtranter** [confluentinc/confluent-kafka-dotnet#287]
Description
===========
Intermittently seeing "Confluent.Kafka.KafkaException Local: Queue Full"

How to reproduce
================
We are unable to reproduce locally. We only see this in long running processes (IIS hosted Web Apps)
Restarting the application pool fixes the problem. We see this problem around every 3 days but there is no clear pattern and it is not happening after App Pool restarts. During these 3(ish) days, we would have sent roughly 210K messages. We have the queue.buffering.max.messages and queue.buffering.max.kbytes set at their defaults of 100K and 400K respectively. 

We don't loose any messages until the Queue Full exceptions start. I would guess the local queue is filling with delivery reports?

Is it possible that the long running task in the Producer that calls rd_kafka_poll is dying somehow? We set manualPoll = false on construction of the Producer.

We do not see any exceptions pertaining to the kafka producer at all ever except Local: Queue Full. We capture all Unobserved exceptions in a global handler for logging.

We are not producing a high volume of msgs/s. Only around 13/s 

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version: 0.9.4
 - [X] Apache Kafka version: 0.10.1.1-cp1
 - [X] Client configuration:
Global: 
api.version.request: true
Topic:
request.required.acks: 0
request.timeout.ms: 5000
message.timeout.ms: 2000

 - [X] Operating system: Windows 2012
 - [X] Provide logs (with "debug" : "..." as necessary in configuration)
```
Confluent.Kafka.KafkaException: Local: Queue full
   at Confluent.Kafka.Producer.Produce(String topic, Byte[] val, Int32 valOffset, Int32 valLength, Byte[] key, Int32 keyOffset, Int32 keyLength, Nullable`1 timestamp, Int32 partition, Boolean blockIfQueueFull, IDeliveryHandler deliveryHandler)
   at Confluent.Kafka.Producer.Produce(String topic, Byte[] val, Int32 valOffset, Int32 valLength, Byte[] key, Int32 keyOffset, Int32 keyLength, Nullable`1 timestamp, Nullable`1 partition, Boolean blockIfQueueFull)
   at Confluent.Kafka.Producer.ProduceAsync(String topic, Byte[] key, Byte[] val)
```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
yes, this sounds like a problem with unhandled delivery reports filling up librdkafka's message queue. do you have `disableDeliveryReports` set to true? there is possibly a bug here - this is not commonly used (and we will likely depreciate it). try using the default `Producer` constructor.

**Comment by mtranter** [comment]
Thanks for the quick response @mhowlett 

We have disableDeliveryReports set to false... Should we not try setting it to true if the problem is delivery reports filling up the queue?

Would this affect the delivery.report.only.error config? (Not that we are currently setting it. But we might give that a shot too)

**Comment by treziac** [comment]
What is strange for me is that ProduceAsync shoud not throw when queue is full - by default, it should block (blockIfQueueFull is true by default), and this exception (looking at librdkafka master - did not check on 0.9.4) only seems to happen when calling Produce directly...

@mtranter Use neither delivery.report.only.error (let it to false) nor disableDeliveryReports (let it to false) - they are not necessary and may behave strangely.

Also, is there a reason in using 0.9.4 rather than latest (0.11.0) or even 0.9.5? There have been some bugfixes since then, but none which seems relevant to your issue

It may indeed be the poll thread which end (but I see no reason to this - I'm not using windows server 2012 and its IIS though...) Do you have any automatic recycle pool which could match the 3 days you are seeing?

**Comment by mhowlett** [comment]
yep, if you can upgrade to 0.11.0 that would be great as then we're sure we're not trying to track down a problem that's already been fixed.

👍 to @treziac's comments.

You could also maybe try setting `request.required.acks` to 1 (maybe there is a bug here somewhere - and it would be good to know if so).

we might need some more sophisticated logic to fail-safe the poll thread - i'm not aware of anything that can go wrong here, but maybe there is.

**Comment by mtranter** [comment]
Hi @treziac 

There is no correlation between app pool recycles and this error that we can see. It was the first thing we checked.

There is no reason for us not to upgrade as far as I know. I'll do it ASAP, but as you say, I compared the relevant code between the versions and couldn't see anything obvious that would affect this issue.

I checked 0.9.4 and ProduceAsync(string topic, byte[] key, byte[] val) passes 'true' as blockIfQueueFull.

**Comment by mtranter** [comment]
Thanks @mhowlett 

Will do the upgrade.

**Comment by mhowlett** [comment]
side note: even if this isn't resolved, there are a number of important fixes since 0.9.4 that you're likely to run into, so upgrading is definitely a good idea.

**Comment by mtranter** [comment]
Sweet. Thanks Matt

**Comment by mtranter** [comment]
Hi Guys,

I did the upgrade as suggested. We have been running the latest version for a few weeks now and we are not seeing the Queue Full problem anymore so I guess this can be closed.

Thanks for your help.

**Comment by smeana** [comment]
Hello @mhowlett 

One of the .net producers received today the below exception:
```bash
Confluent.Kafka.ProduceException`2[Confluent.Kafka.Null,System.String]: Local: Queue full
   en Confluent.Kafka.Producer`2.<ProduceAsync>d__51.MoveNext()
```
One broker shutdown unexpectedly, and probably this scenario filled the Queue, but not sure.

I am using the default Producer:
```c#
  var config = new ProducerConfig { BootstrapServers = "192.168.1.100:9092" };
                    p = new ProducerBuilder<Null, string>(config).Build();
                    this.LogDebug(Instrument + " ProducerBuilder Created");
```

**Comment by mhowlett** [comment]
looks like the broker being down prevented messages from being acknowledged (behavior determined by your `Acks` setting, how many replicas etc.).  Eventually, the producer will give up trying to deliver a message (timing of that determined by `MessageTimeoutMs`) but if the local message queue fills up before that occurs, trying to produce new messages will result in a queue full error as you're seeing. to avoid that, you can reduce the message timeout, or increase `QueueBufferingMaxKBytes` / `QueueBufferingMaxMessages`.

**Comment by smeana** [comment]
Thanks @mhowlett many indexes corrupted on broker due unexpected shutdown and probably the reason to been acknowledged. 
Corrupted Logs and indexes cleaned, and running one more time!!

**Comment by Turhan8** [comment]
I received this error today 02/11/2022
Confluent.Kafka.ProduceException`2[System.String,System.String]: Local: Queue full

This happened after sending around 100K messages to Kafka. Is there a limit to the number of messages that we can send to Kafka before we do a Flush?

**Comment by careless6666** [comment]
I have the same issue, I want to produce 1 000 000 messages to kafka
my config
```
 var config = new ProducerConfig
        {
            BootstrapServers = "kafka-dev-1.company.net,kafka-dev-2.company,kafka-dev-3.company.net",
            LingerMs = 25,   
            BatchSize = 128_000,  
            CompressionType = CompressionType.Zstd,
            EnableDeliveryReports = true,
            DeliveryReportFields = "all",
            Debug = "queue",
            BatchNumMessages = 1000,
            MessageMaxBytes = 100_000,
        };
```

```
using var producer = new ProducerBuilder<string, string>(config).Build();
var message = new Message<string, string> { Value = "a log message " };
        
var start = Stopwatch.GetTimestamp();

for (var j = 0; j < 1; j++)
        {
            var taskList = new List<Task<DeliveryResult<string, string>>>();
            for (var i = 0; i < 1_000_000; i++)
            {
                taskList.Add(
                    producer.ProduceAsync("web_blog", message));
            }
        
            await Task.WhenAll(taskList);
            producer.Flush();
        }
        
        var elapsed = Stopwatch.GetElapsedTime(start, Stopwatch.GetTimestamp());
        Console.WriteLine($"Elapsed {elapsed}");
```
I receive error:
```
Unhandled exception. Confluent.Kafka.ProduceException`2[System.String,System.String]: Local: Queue full
```

if i rewrite cycle from 1 million to 10 X 100_000 it will be work

```
for (var j = 0; j < 10; j++)
        {
            var taskList = new List<Task<DeliveryResult<string, string>>>();
            for (var i = 0; i < 100_000; i++)
            {
                taskList.Add(
                    producer.ProduceAsync("web_blog", message));
            }
        
            await Task.WhenAll(taskList);
            producer.Flush();
        }
```

DOTNET 8, Confluent.Kafka - 2.3.0

**Comment by careless6666** [comment]
I had the same question and when i change in my config QueueBufferingMaxMessages to 1_000_000 it is helped me

var config = new ProducerConfig
        {
            
            LingerMs = 25,   
            BatchSize = 128_000,  
            CompressionType = CompressionType.Zstd,
            EnableDeliveryReports = true,
            DeliveryReportFields = "all",
            //Debug = "queue",
            Debug = "conf",
            BatchNumMessages = 1000,
            MessageMaxBytes = 100_000,
            QueueBufferingMaxMessages = 1_000_000
        };
