### ISSUE TITLE
Does not work with Kafka 0.8.2.1

### ISSUE THREAD

**Issue by reacharaj7** [confluentinc/confluent-kafka-dotnet#293]
I tried using this library with Kafka 0.8.2.1. I set the following 2 properties as recommended

            {"api.version.request",false},   
            {"broker.version.fallback","0.8.2.1"}
I am getting Required feature not supported by broker.

How to reproduce

Checklist

I am using the advancedconsumer dotnet from Master branch.
Kafka Version 0.8.2.1

**Comment by mhowlett** [comment]
the advanced consumer example uses Subscribe ('new' high level consumer functionality), which is not supported by 0.8.2.1 brokers. you'll need to manually assign to partitions.

**Comment by reacharaj7** [comment]
Thank you. I switched to simple consumer and was able to consume the queue.
