### ISSUE TITLE
Reliability use case  

### ISSUE THREAD

**Issue by viveksonawan** [confluentinc/confluent-kafka-dotnet#297]
Description
===========
I am using ProduceAsync method to produce the messages.
Now to get the better reliability i have created topic with following configuration 

.\bin\windows\kafka-topics.bat -zookeeper localhost:2181 --create --topic Account --partitions 3 --replication-factor 3 \--config min.insync.replicas=2

I am setting producer properties are as:   

 var config = new Dictionary<string, object> { { "bootstrap.servers", brokerList },
                    { "batch.num.messages", 1 }, { "request.timeout.ms",2000},{"queue.buffering.max.messages",100 },
                    { "default.topic.config", new Dictionary<string, object>
                        {
                             { "acks", "all" }
                             }
                         }
                    };
My Producer code look like ->

`   using (var producer = new Producer<String,Account>(config, new StringSerializer(Encoding.UTF32), new TypeSerializer<Account>()))
                {
                    Console.WriteLine("\n-----------------------------------------------------------------------");
                    Console.WriteLine($"Producer {producer.Name} producing on topic {topicName}.");
                    Console.WriteLine("-----------------------------------------------------------------------");
                    Console.WriteLine("To create a kafka message with UTF-8 encoded key/value message:");
                    Console.WriteLine("> key value<Enter>");
                    Console.WriteLine("To create a kafka message with empty key and UTF-8 encoded value:");
                    Console.WriteLine("> value<enter>");
                    Console.WriteLine("Ctrl-C to quit.\n");

                    var cancelled = false;
                    Console.CancelKeyPress += (_, e) =>
                    {
                        e.Cancel = true; // prevent the process from terminating.
                        cancelled = true;
                    };
                    int acct = 0;
                    DateTime time = DateTime.Now;
                    Log("Start Time" + time , logfile);
                    while (acct <= 500)
                    {
                        Console.Write("> ");

                        Account text = new Account();
                        try
                        {

                            text.AccountNumber =  acct.ToString();
                            text.age = "34";
                            text.FirstName = "Test first name  ";
                            text.Lastname = "Test last name";                                                       

                            
                            acct = acct + 1;
                        }
                        catch (IOException)
                        {
                            // IO exception is thrown when ConsoleCancelEventArgs.Cancel == true.
                            break;
                        }
                        if (text == null)
                        {
                            // Console returned null before 
                            // the CancelKeyPress was treated
                            break;
                        }                        
                        var val = text;
                        try
                        {
                            //int ptnum= GetPartition();
                            var dh = new ResultHandler();                          

                             producer.ProduceAsync(topicName,acct.ToString() , val,true, dh);
                           
                            producer.Flush(-1);
                            
                            var Result = dh.GetMessage();

                            Console.WriteLine($"Key: {acct.ToString()} ,Partition: {Result.Partition}, Offset: {Result.Offset},account number : { Result.Value.AccountNumber}, Status: { Result.Error}, Message Numner ;{ acct }");
                            Log("Msg Details:" + $"Key: {acct.ToString()},Status {Result.Error},Partition: {Result.Partition}, Account Number: {Result.Value.AccountNumber.ToString()},Offset : { Result.Offset}", logfile);

                           
                        }
                        catch (Exception ex)
                        {
                            Log("Excption"+ex, logfile);
                        }
                    }
                    Log("End Time" + DateTime.Now.ToString(), logfile);
                    Log("End Time" + (time-DateTime.Now).ToString(), logfile);
                  
                }
`
Questions:-
1> I am always getting acknowledgment message status as "Success" (i.e value of Result.Error object)
I tried different way to create error by shutting brokers but never received the Error object filled with error details.How I will receive the error details. 
2> I am using producer.Flush(-1) is that correct way ? wanted to know, is there any way to increase throughput. OR how we can increase performance with reliability?  

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:Confluent.Kafka.0.11.0.nupkg.sha512
 - [ ] Apache Kafka version: kafka_2.11-0.11.0.0
 - [ ] Client configuration:
 - [ ] Operating system: Windows 7
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
What do you mean exactly by reliability? Messages all acked, log properly failed messages, messages in order?
Some things from your code:

- see http://docs.confluent.io/current/clients/producer.html and search the part about ordering. You don't necesseraly need a sync producer to achieve ordering (just make sure you don't have more than one in flight request at a time), but it really depends on your needs. It seems broken at the time being though (https://github.com/edenhill/librdkafka/issues/1092), so for now continue using your sync producer
- if you use a deliveryhandler, you may want to use a single deliveryhandler for all produceAsync, not creating one each time. Also, could you post your code for `ResultHandler` ? I don't see what you `GetMessage` will do, so cannot explain why you always get success

- Did you try shutting down all broker to get error, for more than five minutes? By default, librdkafka will retry to send failure. If you want to maximize 'chances' of receiving failures, set `retries` to 0 and `message.timeout.ms` to 10000 for example, 
- I would discourage calling `Flush(-1)` : if there are some network issues, this will block until all your messages timeout, which is by default 5min. Call `Fluh(TimeSpan.FromSeconds(10))` for example, and check that result is 0 (it returns the number of messages which were net send yet), and log if necessary. You can call flush in a while loop if you want - this will have same result, but at least you can monitor it
- `request.timeout.ms` is the time to wait ack once data has been send to broker, not the time to wait to send data (which is  `message.timeout.ms`). So if brokers are down, you will wait at least this time
- What are you trying to achieve with `batch.num.messages` to 1? I assume you want to send the message right away, then it's ok - but you can also use `queue.buffering.max.ms` and set it to 1.
- set `socket.blocking.max.ms` to 1, or you may wait up to 1s between each request
- as you are on windows, disable nagle y setting `socket.nagle.disable` to `true`
- newly ExactlyOnce semantic would help you, but it's not available yet on librdkafka. It's on roadmap!
- If you want full reliability, you may also want to check for CRC32 (`check.crcs`)

**Comment by viveksonawan** [comment]
Thanks for quick response. 
As part of this we need 
1)Messages all acked, 
2)log properly failed messages 


My ResultHandler  code is as:-

` public  class ResultHandler : IDeliveryHandler<String,Account>
        {

            public ResultHandler()
            {
                
            }
            bool marshdata;
            public bool MarshalData
            {
                get
                {
                    return marshdata;
                }
            }
            Message<String, Account> newmessage;
            public void HandleDeliveryReport(Message<String, Account> message )
            {
                newmessage = message;
            }
            public Message<String, Account> GetMessage()
            {
                return newmessage;
            }
           

        }`
I am expecting Message.Error should be different from Error.NoError. I am always getting following values is error  object. 

? Result.Error 
{Success}
    Code: NoError
    HasError: false
    IsBrokerError: false
    IsLocalError: false
    Reason: "Success"

If we have configure { "acks", "all" } and  min.insync.replicas=2 set on topic, Then  error object should to be populated with error detail, If I stop two broker. (3 broker out of 2) .Error object should be reflected Because Kafka is failed to update all replicas. Please help me here to understand this or correct me . 
 
How to check the full reliability by checking for CRC32.? Please provide samples.                                   
 Also thanks for your suggestions ,I will modify my code accordingly. 
Also I wanted to know how i will get better performance for this case OR suggest code for good  reliability with performance.

**Comment by treziac** [comment]
So you don't need order? (You can improve throughput a lot if you don't need it)

Will respond when I have time :)

**Comment by viveksonawan** [comment]
Yes that correct , but remember we need Reliability as well.

**Comment by treziac** [comment]
I have no problem on my side, with confluent.Kafka 0.11 and kafka 0.11
Check the result of `producet.GetMetadata(false, topicname)`. Do you effectively see only one in-sync replica?
You can also check this via 
`kafka-topics.bat --describe --topic <topicName>--zookeeper localhost:2181`
Also, if you are still seeing `NoError`, did you try producing via the commande line provided with kafka to see if you have the same problem?

For reliability, if you don't need order, you should send batches in an async way - see Advanced Producer. If a message fails, it will be retried (3 times by default, config via `retry`, except if this is a permanent error), and only then if it still fails will you get an error. Messages may not be ordered in case a broker failure, but with `ack=all`, you will be assured to catch all exceptions (if message was not replicated to at least two brokers), so all messages acked will be effectively written under all standard conditions

Note that for the time being, you can still have some problem. In case the broker did in fact write data to every replica, but crash before sending an ack, you might resend this data which wil be duplicate. If your client fail, you may not know when restarting your client what was written and what was not (or will have to consume the topic to check this.) You can read more about this here: https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/ Apache kafka now offer ExactlyOnce delivery semantic but librdkafka is not implementing it yet - this is on the roadmap!

**Comment by treziac** [comment]
Concerning CRC, my mistake, it's only a consumer option. I never used it myself (I assume TCP is enough), but enabling `check.crcs` to true should be enough. If you want to test this, the best thing to do would be to use wireshark (or some other tool) and editing response.

**Comment by viveksonawan** [comment]
I waiting for some of answers.
1) How to log  properly failed messages if ack="all". I have tried this- 
if three brokers are running and min.insync.replicas=2 and if we close the 2 brokers manually while producer processing messages. I have received "Queue full" exception(Kafka was busy) after few millisecond Kafka producer started processing again and processed all the messages. In this case I should receive error as other brokers not working because (min.insync.replicas=2) ,Please help me to understand this.
2) How we can create fail over case to test the reliability? and How to log errors and re-process failed messages?

**Comment by viveksonawan** [comment]
Also there was more messages losses in case of Scenario’s (1) I have explained above

**Comment by treziac** [comment]
Messages are retried, and librdkafka will try to resend them. Did you wait enough time? By default, timeout is at 5 minutes as explained in my first post. I'm correctly receiving error when reproducing your scenario. Please describe your scenario better (with time at which you cut broker and reactive them), when you send data, when you receive ack...)

You can use `debug` config to monitor what is going on, set it to `broker,topic,msg`

Did you try what I asked in the first two paragraphs of last post, metadata and reproducing this with console tool? Please post those results first.

**Comment by viveksonawan** [comment]
Thanks for reply, yes its right I miss the time out parameter to set. Now I am getting error object with all related details that I was expecting. 
But now I am observing different issue. if we close all brokers while Producer is processing messages ,Immediately we receive duplicates Message object from (HandleDeliveryReport paramter) kafka     

  :Msg Details:Key: 1813,Status Success,Partition: 0, Account Number: 259,Offset : 137
  :Msg Details:Key: 1814,Status Success,Partition: 0, Account Number: 259,Offset : 137
  :Msg Details:Key: 1815,Status Success,Partition: 0, Account Number: 259,Offset : 137
  :Msg Details:Key: 1816,Status Success,Partition: 0, Account Number: 259,Offset : 137

After some time application throw the time out exception. This behavior miss-leading us. How to avoid this.?

**Comment by mhowlett** [comment]
We plan to make an in-depth example + docs highlighting reliability features. Tracking that task internally.
