### ISSUE TITLE
Exception when running Examples\Misc

### ISSUE THREAD

**Issue by Leon99** [confluentinc/confluent-kafka-dotnet#314]
Description
===========
Confluent.Kafka.KafkaException: 'Local: Broker transport failure'
   at Confluent.Kafka.Impl.SafeKafkaHandle.ListGroupsImpl(String group, Int32 millisecondsTimeout)
   at Confluent.Kafka.Producer.ListGroups(TimeSpan timeout)

How to reproduce
================

1. Install kafka + zookepeer locally on Win10 (from https://github.com/renukaradhya/confluentplatform)
2. Start servers
3. Produce few messages to a topic called "test" (using the SimpleProducer example - works fine, confirmed with SimpleConsumer)
4. Run the provided Misc example with `localhost --list-groups`

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.0
 - [ ] Apache Kafka version: 0.11

**Comment by treziac** [comment]
Note first that the repo you use seems to be confluent 3.0.1, so kafka 0.10.0.1 - are you sure it's kafka 0.11? This should not be a problem whatever. For info, the apache kafka release content proper windows file, distributed for convenience - the confluent package does not works well as support of windows is not provided for the moment.

I have no problem on my side, on windows 10, with kafka 0.11 and confluent-kafka-dotnet 0.11.

Broker transport failure indicates that you could not contact broker - can you confirm the brokers where up (for example, you could properly produce messages after you had this issue?)

You can add the configuration "debug", "broker" to configuration dictionary to get more details and post it here

**Comment by Leon99** [comment]
Thanks @treziac. You're probably right about kafka versioning -  I tried separate kafka/zookeeper chocolatey packages first though and had some issues with that, then tried confluent and, finally, ended up with using that repo. Like you said, it shouldn't matter, since Kafka Tool works just fine.

Yes, I can still produce/consume after that error.

Now, here is the log I get with the debug flag:

> Hello RdKafka!
B00FF
0.11.0
all, generic, broker, topic, metadata, queue, msg, protocol, cgrp, security, fetch, feature
7|2017-09-03 08:09:43.868|rdkafka#producer-1|BROKER| [thrd:app]: localhost:9092/bootstrap: Added new broker with NodeId -1
7|2017-09-03 08:09:43.868|rdkafka#producer-1|BRKMAIN| [thrd::0/internal]: :0/internal: Enter main broker thread
7|2017-09-03 08:09:43.874|rdkafka#producer-1|STATE| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
7|2017-09-03 08:09:43.876|rdkafka#producer-1|BRKMAIN| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Enter main broker thread
7|2017-09-03 08:09:43.876|rdkafka#producer-1|CONNECT| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: broker in state INIT connecting
7|2017-09-03 08:09:43.884|rdkafka#producer-1|CONNECT| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connecting to ipv4#127.0.0.1:9092 (plaintext) with socket 1016
7|2017-09-03 08:09:43.885|rdkafka#producer-1|STATE| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state INIT -> CONNECT
7|2017-09-03 08:09:43.885|rdkafka#producer-1|CONNECT| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected to ipv4#127.0.0.1:9092
7|2017-09-03 08:09:43.885|rdkafka#producer-1|CONNECTED| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected (#1)
7|2017-09-03 08:09:43.885|rdkafka#producer-1|FEATURE| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
7|2017-09-03 08:09:43.885|rdkafka#producer-1|STATE| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
7|2017-09-03 08:09:43.886|rdkafka#producer-1|FEATURE| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4
7|2017-09-03 08:09:43.886|rdkafka#producer-1|STATE| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP

**Comment by Leon99** [comment]
Hmm I've just tried 0.11 (from chocolatey) again and it works fine (including the Misc example in question).

**Comment by treziac** [comment]
I would assume the repo you used to launch confluentinc on windows does not works correctly (I did not test it)
I tested against a kafka 0.10.0.1 vanilla (used by confluent 3.0.1) and have no issue

Confluent does not provide windows support, but it does provide docker images
For example, you can run following commands to run zookeeper and kafka:

```
docker run -d     --name=zookeeper     -p 2181:2181     -e ZOOKEEPER_CLIENT_PORT=2181     confluentinc/cp-zookeeper:3.0.1
docker run -d     --link zookeeper     -p 9092:9092     -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181          -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092     -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1     confluentinc/cp-kafka:3.0.1
```

I tested, ListGroups works ok here.
Of course, I would advise using tag 3.3.0 (or `latest`) if you use docker ;) or adapt to your production target.

**Comment by Leon99** [comment]
I tried the docker approach - with your command line there is some port mapping missing, but even after I added it, it still can't get into topics (I'm using Kafka Tool to test the setup)... I suspect there is some confusion because of the docker network. Thanks for trying though, I suppose I'll stick with just local install for now.

**Comment by treziac** [comment]
For docker, you will need to replace localhost in KAFKA_ADVERTISED_LISTENERS by the IP/hostname of your docker host, so it is reachable from remote computer

**Comment by ttallskog** [comment]
This solved my problem...
