### ISSUE TITLE
ByteArrayDeserializer 0.11.0 does not exist？

### ISSUE THREAD

**Issue by MikeDGitHub** [confluentinc/confluent-kafka-dotnet#317]
Description
===========
nuget downloads does not exist ByteArrayDeserializer,but  Source code  exists

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version:0.11.0
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Indeed, it seems it was commited after the branch was pulled (same for many serializer). Best thing is to create the serializer on your side for now (fairly straight-forward)

**Comment by MikeDGitHub** [comment]
I cloned the source code compiled with the debug version
