### ISSUE TITLE
about key store file

### ISSUE THREAD

**Issue by a7618317a** [confluentinc/confluent-kafka-dotnet#320]
Description
===========

When I use the Key store file,add property "ssl.keystore.location、ssl.keystore.password、ssl.key.password、ssl.truststore.location、ssl.truststore.password" in the config, It throw error:"can not find the property ssl.keystore.location....." ,how can i use librdkafka with key store file,thank you !

How to reproduce
================

add property "ssl.keystore.location、ssl.keystore.password、ssl.key.password、ssl.truststore.location、ssl.truststore.password" in the config

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Dup of https://github.com/edenhill/librdkafka/issues/1420
