### ISSUE TITLE
Consumer performance - Assistance and Advice Needed

### ISSUE THREAD

**Issue by combrinckd** [confluentinc/confluent-kafka-dotnet#321]
Description
===========
I have found significant differences when consuming different topics. Obviously, there will be slower throughput on larger messages; however, all topic messages are quite small. However, I found that the one topic I am consuming from with the highest throughput does not contain the smallest messages... 
To lay out the scenario a little better, I am testing throughput and performance. I have three topics, each set up with 16 partitions. All messages are raw byte[], so no special serialization and formatting etc.

----------------------------------------------------

**Topics are:**
**GPRS_Vodacom_IREQ_Qabc777df-686a-4253-b563-576142bf0b5e**
Current message lengths between 850 – 900 bytes 
Messages use to be between 5500 - 6500 bytes, so I applied gzip compression first expecting better consumer rates, however it is still the same (maybe improved with 50msgs/sec) 
Slowest consume rate below 900 msgs/sec

**Devmessages**
Message lengths between 60 – 90 bytes
Consume rates between 1000 – 1300 msgs/sec max

**RawImports** 
Message lengths between 160 – 250 bytes 
This topic has the fastest consuming rate at between 11 000 – 20000 msgs/sec

--------------------------------------

The rates above are for both Poll and Consume, results staying the same. The tests ran with no “after consumption processing”, as the case in an actual implementation. Meaning, I only consume and calculate the rates, committing offset every 100 messages. Even if I do automatic offset commits every 5 seconds, the rate is also in the same region as above. 
One important aspect I forgot to mention also is that the CPU runs almost 100% . 

Running against the same topics with the java client I get consume rates on average 60 000, 200 000 and 350 000 messages per second respectively.

I must be doing something fundamentally wrong. The problem is what and where?  I have read through your “Kafka Definitive Guide ebook”, documentation, various posts on configurations, polling vs consuming, performance tweaking on both client side and kafka cluster configs etc. Im at a loss and would greatly appreciate any pointers someone can provide. 

Client is using latest nuget version as at this moment in time (0.11.0).
Attached is the sample client app that I am testing with.

[ConsoleApp2.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/1302948/ConsoleApp2.zip)

**Kafka Cluster Setup (Apache Kafka 2.12-0.11.0.0)**
4 virtual servers each running Windows Server 2012 Standard, 8GB ram, 2 x 2.67Ghz CPU
Single Zookeeper instance. 
4 Kafka Brokers
Broker config (obviously broker.id differ per instance..):
•	broker.id=1
•	num.network.threads=16
•	num.io.threads=8
•	socket.send.buffer.bytes=1048576
•	socket.receive.buffer.bytes=1048576
•	socket.request.max.bytes=104857600
•	queued.max.requests=16
•	fetch.purgatory.purge.interval.requests=100
•	producer.purgatory.purge.interval.requests=100
•	log.dirs=/tmp/kafka-logs	
•	**num.partitions=16**
•	num.recovery.threads.per.data.dir=1
•	message.max.bytes=10000000
•	auto.create.topics.enable=true
•	**offsets.topic.replication.factor=3
•	transaction.state.log.replication.factor=3
•	transaction.state.log.min.isr=3**
•	log.retention.hours=168
•	log.segment.bytes=1073741824
•	log.retention.check.interval.ms=300000
•	zookeeper.connect= …………:2181
•	zookeeper.connection.timeout.ms=6000
•	group.initial.rebalance.delay.ms=0

_Edit: Forgot to attach screenprints and kafka tool topic views (might be usefull to look at)_
[Kafka Cluster and Testing Consumer performance.pdf](https://github.com/confluentinc/confluent-kafka-dotnet/files/1303006/Kafka.Cluster.and.Testing.Consumer.performance.pdf)

**Comment by edenhill** [comment]
Thanks for a great issue report.

I think you might be hitting this bug in librdkafka: https://github.com/edenhill/librdkafka/issues/1384

It has been fixed on master but we haven't pushed a new release just yet.
If you want to verify this fix I suggest grabbing the appropriate librdkafka.dll from AppVeyor to replace the one installed from NuGet:
https://ci.appveyor.com/project/edenhill/librdkafka/build/0.11.0-R-post207-fnnfsgiu/job/d26woeir09hx6bri/artifacts

**Comment by combrinckd** [comment]
**This is awesome!!!**
Thank you for the assistance in this @edenhill  
This seem to have fixed the issue on both throughput as well as CPU usage. 
I am now actually getting the same or even better performance than the java client I ran earlier. 

Do you perhaps have an idea of when this will be release via the official nuget package? For now I will work around it by ensuring I keep the dll's and updating when I need to deploy to Dev, QA, but it would be great to have everything in place in the nuget release.

Once again thanks!! 
Attached is screenprints of new rates.
[New throughput rates.pdf](https://github.com/confluentinc/confluent-kafka-dotnet/files/1303433/New.throughput.rates.pdf)

**Comment by edenhill** [comment]
Happy it fixed the problem!

We're looking to release a new librdkafka version with this fix in about 2-3 weeks time.

**Comment by mhowlett** [comment]
thinking it's worth leaving this issue open until we do the next release to make it easier to find for others who may be wondering the same thing.

**Comment by edenhill** [comment]
A release candidate for librdkafka is now available on NuGet, please help verifying the fix:
https://www.nuget.org/packages/librdkafka.redist/0.11.1-RC1

**Comment by mhowlett** [comment]
... and a release candidate for the dotnet client that references this is also now available:
https://www.nuget.org/packages/Confluent.Kafka/0.11.1-RC1

**Comment by geofflamrock** [comment]
Hi @mhowlett @edenhill, 

Do either of you know if there is a timeline for a final 0.11.1 release to fix this issue?

Thanks.

**Comment by mhowlett** [comment]
#294 is the only blocker I'm aware of, and we worked out what we're going to do to fix that today. It shouldn't be long. 0.11.1-RC1 should be fine to use in the meantime and I would highly recommend this over 0.11.

**Comment by asmx1986** [comment]
Hi @mhowlett @edenhill , do you know when the final 0.11.1 release would be?

**Comment by mhowlett** [comment]
Imminent... The #294 fix didn't make it unfortunately (but it's coming soon after).

**Comment by mhowlett** [comment]
closing - 0.11.1 was released long ago ...
