### ISSUE TITLE
Producer Metadata Call Error: Broker Transport Failure

### ISSUE THREAD

**Issue by chiru1205** [confluentinc/confluent-kafka-dotnet#323]
Description
===========
Call to get metadata of a specific topic fails and all I see is broker transport failure error. Also my kafka messages are timing out. This worked well with previous version of .NET client , issues started with v 0.11.0. 

Here is the producer configuration I use to get metadata info.
   {"bootstrap.servers", brokerList},
            {"client.id",Guid.NewGuid()},
            {"debug", "protocol,broker,topic,msg" },
            {
                "default.topic.config", new Dictionary<string, object>
                {
                    {"acks", "all"},
                    {"message.timeout.ms", 3000}
                }
            }

Here is the info from the logs
![image](https://user-images.githubusercontent.com/16243876/30609493-26ba311c-9d41-11e7-85e0-9dfd6307ca29.png)

Is there something I'm missing? or Do i need to update my broker version for the new 0.11.0 version?

How to reproduce
================
1. Use version 0.11.0 of .NET Client
2. Broker version 0.9.0.1
3. Make a call using a producer instance with above specified configuration to get metadata info

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.0
 - [ ] Apache Kafka version: 0.9.0.1
 - [ ] Client configuration: 
 - [ ] Operating system: Windows 2012 server
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka v0.11.0 changed the default value of api.version.request from false to true, and you are now hitting a 0.9.0.1 broker bug.
Set `api.version.request` to false in your client configuration to fix the problem.

More info:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by chiru1205** [comment]
it works now with the configuration update you suggested. Thank you @edenhill
