### ISSUE TITLE
0.9.5-RC3 was working for Consumer, later releases return Null messages

### ISSUE THREAD

**Issue by malinovskiyy** [confluentinc/confluent-kafka-dotnet#325]
Description
===========
We're using Kafka 0.10.1.1 to populate a topic that we've been reading from without issue, using the 0.9.5-RC3 client. However, after upgrading to 0.11.0, the consumer receives no messages at all, behaving like the topic is not recognized at all (Consume() returns null, and no errors are thrown - as if the topic name is wrong...). Trying the 0.9.5 Client resulted in a similar failure. We can see this without using any of our code (SimpleConsumer examples for 0.11.0 and 0.9.5 don't work and 0.9.5-RC3 works). 

How to reproduce
================
We can reproduce by just running the current 0.9.5-RC3 and latest (0.11.0) SimpleConsumer examples and connecting to a Kafka 0.10.1.1 topic. 

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.9.5+
 - [ ] Apache Kafka version: 0.10.1.1
 - [ ] Client configuration: Windows Service running on .NET 4.5 (Visual Studio 2013), also tried with VS2017 + .NET 4.6
 - [ ] Operating system: Windows 7 Client

**Comment by mhowlett** [comment]
Can't think of what could be the problem. Can you set the "debug" configuration property to "all" and paste the output here.

**Comment by malinovskiyy** [comment]
Thanks for the prompt response - here are the debug:all logs for the simple consumer example using 0.11.0 - I suppose it looks like it does find the topic (?):
[out_0110.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1318568/out_0110.txt)

For comparison, here are the logs for 0.9.5-RC3:
[out_095RC3.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1318572/out_095RC3.txt)

When running the simple consumer example in 0.11.0, no additional output besides the log is created, while 0.9.5-RC3 prints out the message content.

**Comment by mhowlett** [comment]
There are lots of PROTOERR's in there... Maybe try setting `api.version.request` to `false` and `broker.version.fallback` to `0.9.0`. Can you share details of the configuration of the producer that produced the messages? It looks like something is going wrong under the covers.. I've not seen this before.

```
4|2017-09-20 09:19:31.031|rdkafka#consumer-1|PROTOERR| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Protocol parse failure at 1048290/1048621 (rd_kafka_msgset_reader_msg_v0_1:464) (incorrect broker.version.fallback?)
4|2017-09-20 09:19:31.031|rdkafka#consumer-1|PROTOERR| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: expected 595 bytes > 331 remaining bytes
```

**Comment by edenhill** [comment]
It looks like it is indeed fetching messages from the broker:
```
...
7|2017-09-20 09:19:33.139|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Fetch topic ie-trans-out1 [0] at offset 138217863 (v2)
7|2017-09-20 09:19:33.139|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Fetch 1/1/4 toppar(s)
7|2017-09-20 09:19:33.139|rdkafka#consumer-1|SEND| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Sent FetchRequest (v2, 72 bytes @ 0, CorrId 257)
7|2017-09-20 09:19:33.430|rdkafka#consumer-1|RECV| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Received FetchResponse (v2, 152279 bytes, CorrId 257, rtt 281.00ms)
7|2017-09-20 09:19:33.430|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Topic ie-trans-out1 [0] MessageSet size 152234, error "Success", MaxOffset 138218113, Ver 2/2
7|2017-09-20 09:19:33.430|rdkafka#consumer-1|CONSUME| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Enqueue 250 message(s) on ie-trans-out1 [0] fetch queue (qlen 250, v2, last_offset 138218112)
7|2017-09-20 09:19:33.430|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Fetch topic ie-trans-out1 [0] at offset 138218113 (v2)
7|2017-09-20 09:19:33.430|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Fetch 1/1/4 toppar(s)
7|2017-09-20 09:19:33.430|rdkafka#consumer-1|SEND| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Sent FetchRequest (v2, 72 bytes @ 0, CorrId 258)
7|2017-09-20 09:19:33.526|rdkafka#consumer-1|RECV| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Received FetchResponse (v2, 40856 bytes, CorrId 258, rtt 109.00ms)
7|2017-09-20 09:19:33.526|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Topic ie-trans-out1 [0] MessageSet size 40811, error "Success", MaxOffset 138218180, Ver 2/2
7|2017-09-20 09:19:33.526|rdkafka#consumer-1|CONSUME| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Enqueue 67 message(s) on ie-trans-out1 [0] fetch queue (qlen 67, v2, last_offset 138218179)
7|2017-09-20 09:19:33.526|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Fetch topic ie-trans-out1 [0] at offset 138218180 (v2)
7|2017-09-20 09:19:33.526|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Fetch 1/1/4 toppar(s)
7|2017-09-20 09:19:33.526|rdkafka#consumer-1|SEND| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Sent FetchRequest (v2, 72 bytes @ 0, CorrId 259)
7|2017-09-20 09:19:33.576|rdkafka#consumer-1|RECV| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Received FetchResponse (v2, 5529 bytes, CorrId 259, rtt 47.00ms)
7|2017-09-20 09:19:33.577|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Topic ie-trans-out1 [0] MessageSet size 5484, error "Success", MaxOffset 138218189, Ver 2/2
7|2017-09-20 09:19:33.577|rdkafka#consumer-1|CONSUME| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Enqueue 9 message(s) on ie-trans-out1 [0] fetch queue (qlen 9, v2, last_offset 138218188)
7|2017-09-20 09:19:33.577|rdkafka#consumer-1|FETCH| [thrd:dnfbkafka05:9092/5]: dnfbkafka05:9092/5: Fetch topic ie-trans-out1 [0] at offset 138218189 (v2)
...
```

So it is a bit weird if you don't see any messages in your consumer.
Can you share your client configuration and your consumption loop code?

**Comment by edenhill** [comment]
@mhowlett 
The PROTOERR are actually no errors but partial receives, it is only debug=protocol that turns them into error logs (which is weird, yes). The partial messages are an optimization in the broker to allow sendfile() usage which the client is supposed to handle (and so it does)

**Comment by mhowlett** [comment]
ahh ok. 

he notes the problem occurs with the SimpleConsumer example code which uses the deserializing consumer. Perhaps try using the non-deserializing consumer. I'm not sure why this would work, but it will at least narrow down the problem a little.

**Comment by malinovskiyy** [comment]
You're right - I think the issue is in the StringDeserializer. Running the following code:
'''c#
        public static void Main(string[] args)
        {
            string brokerList = args[0];
            var topics = args.Skip(1).ToList();

            var config = new Dictionary<string, object>
            {
                { "group.id", "simple-csharp-consumer" },//{"debug", "all"},
                { "bootstrap.servers", brokerList }
            };

            using (var consumer = new Consumer(config))
            {
                consumer.Assign(new List<TopicPartitionOffset> { new TopicPartitionOffset(topics.First(), 0, 0) });

                while (true)
                {
                    Message msg;
                    if (consumer.Consume(out msg))
                    {
                        Console.WriteLine($"Topic: {msg.Topic} Partition: {msg.Partition} Offset: {msg.Offset} {msg.Value.Count()}");
                    }
                }
            }
        }
    }
'''
Produces the following output:
[out.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1318907/out.txt)

So, I can see the byte arrays are not empty and getting through. Our messages are JSON strings, so this makes sense... Did something change about the deserializer from 0.9.5-RC3 onwards?

**Comment by mhowlett** [comment]
you'll probably get events on OnConsumeError - the strings are probably not valid utf8.

**Comment by mhowlett** [comment]
previously the de-serializers would throw an exception if there was an error decoding (can't recall exactly when that changed). it may be appropriate to specify a different string encoding in the deserializer, or write your own deserializer.

feel free to provide more information about / dump of the encoded message if you think it's reasonable that something other than what currently happens should happen.

**Comment by malinovskiyy** [comment]
Hmm, on the producer side, we're using the org.apache.kafka.common.serialization.{Serde, Serdes} (in Scala):
```scala
object AclArchiveDestination extends KafkaStreamDestination[JLong, String]{
  override def deliverStream: (PrefixedProperties) => (KafkaStreams) => (KStream[JLong, String]) => Unit =
    props => streamsController => stream => {
      val longSerde: Serde[JLong] = Serdes.Long()
      val stringSerde: Serde[String] = Serdes.String()

      stream.to(longSerde, stringSerde, props.getProperty("stream.output.topic"))
      startStream(streamsController)
    }
}
```
That should be UTF8 by default, looking at org.apache.kafka.common.serialization:
```java
public class StringSerializer implements Serializer<String> {
    private String encoding = "UTF8";

    public StringSerializer() {
    }
....
```
Do we have to explicitly specify it now?

**Comment by mhowlett** [comment]
oh, your keys are `long`? the problem is there then I think - if you're using the simple consumer example as is, it expects null keys. if it gets any data at all, that will cause the Consumer to give consume errors.

**Comment by malinovskiyy** [comment]
Yes, this is it! We were keeping our consumer agnostic to key type and passing a Null deserializer for the key. This used to work in 0.9.5-RC3, but as you mentioned, it looks like we now need to match the consumer key deserializer with the produced type, even if we do not use the key at all. Not sure if that was a desired effect of the changes from 0.9.5-RC3, but we can move forward - changing the consumer  to use a long deserializer resolved our issue. Many thanks!

**Comment by mhowlett** [comment]
I think we should add an `Ignore` deserializer type (alternatively parameterize the null deserializer constructor, though I think that would be worse).
