### ISSUE TITLE
kafka consumer issue 

### ISSUE THREAD

**Issue by narekaleksanyan** [confluentinc/confluent-kafka-dotnet#327]
I have implemented kafka consumer via java and I got messages from Kafka.
I'm trying to run  simple example from here with the same configurations( topic,groupId,brokers) , but I cannot get any message from kafka.

**Comment by mhowlett** [comment]
some things to try:

make sure you're handling OnError and OnConsumeError - look for errors there.
try setting the debug config setting to 'all' for very verbose log information.

**Comment by edenhill** [comment]
And set auto.offset.reset=earliest
