### ISSUE TITLE
GC is killing delegates created in Consumer & Producer constructors

### ISSUE THREAD

**Issue by vaspas** [confluentinc/confluent-kafka-dotnet#33]
A callback was made on a garbage collected delegate of type 'Confluent.Kafka!Confluent.Kafka.Impl.LibRdKafka+LogDelegate::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.

**Comment by mhowlett** [comment]
thanks @vaspas - surprised I hadn't seen evidence of this issue myself yet.
