### ISSUE TITLE
Network Storage Directory

### ISSUE THREAD

**Issue by eaba** [confluentinc/confluent-kafka-dotnet#330]
Description
===========

This is not an issue, but a question.
How can I replace the default log.dir with azure storage network drive?

Thanks

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by eaba** [comment]
Hi @mhowlett can you kindly say something?

**Comment by mhowlett** [comment]
@eaba - I have to admit to having never used Azure, but you'll just need to mount the drive and set the `log.dir` config property on the broker.
