### ISSUE TITLE
Heap corruption while using consumer

### ISSUE THREAD

**Issue by derrickaccountnumbertwo** [confluentinc/confluent-kafka-dotnet#337]
Description
===========

Hello, I'm encountering a nasty bug with what seems to be a basic use case. Am I doing something wrong?

- I'm creating several threads near-simultaneously, each of which runs the code found in the 'how to reproduce' section.

- My usage seems basic, but somewhere in librdkafka the heap is getting corrupted. This shows an error in ntdll.dll and causes a hard crash - can't catch heap corruption exceptions.

- This error is intermittent but generally happens often enough (one time in 5?) to be reproduced within a reasonable time.

- ~~Logging suggests that this is happening inside consumer.Poll, which of course isn't surprising given how much goes on in that method.~~ Further testing shows that, the more frequently I dispose of a consumer and create a new one, the more frequently this problem occurs. Therefore this might not actually be related to Poll().

- UPDATE: Logs after a crash seem to always show multiple consumers being disposed at the same time - are there any known problems with this?

- UPDATE 2: Putting a lock around consumer disposal seems to lessen but NOT eliminate the problem. Perhaps this problem is common to Poll and Dispose? I'm starting to suspect it has something to do with librdkafka reading the SSL files - any thoughts on that?

- Each consumer is private to its thread and is never exposed, nor is Dispose() called before reaching the 'finally' block.

- I'm using SSL, with "ssl.ca.location" and the other 2 related config properties.

- Frequently, SSL handshake errors will appear (in OnError, not in an exception) when the consumer is first connecting, but these always resolve themselves within the same Poll() call, and usually the consumer works as expected after that. I assume this is normal and unrelated.

- The majority of the consumers being created are part of the same group, but a few may be in other groups.

- Any other questions?

How to reproduce
================

`        public void RunThread(){
            Consumer<byte[], byte[]> consumer = null;
            
            threadIsRunning = true;

            try
            {
                Dictionary<string, object> config = GetConfig();

                consumer = new Consumer<byte[], byte[]>(config, new ByteArrayDeserializer(), new ByteArrayDeserializer());

                consumer.Subscribe(GetTopic());

                consumer.OnMessage += (src, msg) =>
                {
                    //handle message, commit offset to local storage
                };
                consumer.OnPartitionsAssigned += (src, partitions) =>
                {
                    try
                    {
                        //fetch offsets from local storage, then call consumer.Assign
                    }
                    catch (Exception ex)
                    {
                        // Swallow exceptions here to avoid crashes if handles are already gone
                    }
                };
                consumer.OnPartitionsRevoked += (src, partitions) =>
                {
                    try
                    {
                        consumer.Unassign();
                    }
                    catch (Exception ex)
                    {
                        // Swallow exceptions here to avoid crashes if handles are already gone
                    }
                };
                consumer.OnPartitionEOF += (src, p) =>
                {
                    // Log this but do nothing else
                };
                consumer.OnConsumeError += (src, error) =>
                {
                    // Log this but do nothing else
                };
                consumer.OnError += (src, error) => {
                    // Log this but do nothing else
                };

                while (threadIsRunning)
                {
                    // Log poll start
                    consumer.Poll(GetTimeoutValue());
                    // Log poll end
                }
            }
            catch (Exception ex)
            {
                // Log error, then swallow exception
            }
            finally
            {
                try
                {
                    if(consumer != null)
                        consumer.Dispose();
                }
                catch(Exception ex)
                {
                    // Log error, then swallow exception
                }
            }
        }`

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.0
 - [ ] Apache Kafka version: 0.8 I think - CloudKarafka trial
 - [ ] Client configuration:
 - [ ] Operating system: Win10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue:  Yes

Thanks for the help.

**Comment by mhowlett** [comment]
Thanks for the detailed report.
Can you try 0.11.1-RC1 which is now on nuget and see if this works?

If not, if you create a self-contained program that I can run in which the problem occurs, that would help immensely (I will run it and debug).

I don't immediately see anything wrong with your code.

**Comment by derrickaccountnumbertwo** [comment]
Installed 0.11.1-RC1 about 30 minutes ago, and so far I can't get it to crash at all. Fingers crossed, knock on wood.

If 0.11.1-RC1 eliminates this problem, do you happen to know what commit or change fixed it? Just curious.

I'll try to update this issue again by Monday, after some more testing. Thanks!

**Comment by mhowlett** [comment]
In relation to this problem, I'm not exactly sure, but 0.11.1 does fix a number of relatively high impact regressions in 0.11.0. If you're not seeing any issues I think they are likely resolved.

**Comment by derrickaccountnumbertwo** [comment]
I've gone through all the situations where I previously had crashes, and there haven't been any with 0.11.1-RC1. I'm closing this issue - thanks again!
