### ISSUE TITLE
SafeKafkaHandle.ListGroup throws exception

### ISSUE THREAD

**Issue by bschmidtbauer** [confluentinc/confluent-kafka-dotnet#34]
The below method in SafeKafkaHandle will throw an exception when a non-existent group name is passed:

```
internal GroupInfo ListGroup(string group, int millisecondsTimeout)
   =>  ListGroupsImpl(group, millisecondsTimeout).Single();
```
The exception is due to the implementation of Single() in .NET, where the sequence you invoke it on needs to contain 1 and only 1 item that matches the predicate (in this case no predicate).  A different option is SingleOrDefault(), even better is probably FirstOrDefault() as using 'firs't is typically going to perform better as the 'single' methods need to scan the entire collection to make sure there are no duplicates.  In this case there should never be more than one so it shouldn't matter.

**Comment by mhowlett** [comment]
fixed in #43
