### ISSUE TITLE
NullDeserializer may only be used to deserialize data that is null

### ISSUE THREAD

**Issue by evenbing** [confluentinc/confluent-kafka-dotnet#345]
run at example exception:NullDeserializer may only be used to deserialize data that is null
config:    
private static Dictionary<string, object> constructConfig(string brokerList, bool enableAutoCommit) =>
            new Dictionary<string, object>
            {
                { "group.id", "advanced-csharp-consumer" },
                { "enable.auto.commit", enableAutoCommit },
                { "auto.commit.interval.ms", 5000 },
                { "statistics.interval.ms", 60000 },
                { "bootstrap.servers", brokerList },
                { "default.topic.config", new Dictionary<string, object>()
                    {
                        { "auto.offset.reset", "smallest" }
                    }
                }
            };

===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
This is not a bug, it's a feature! You would be trying to deserialize a key or value that has data. The null deserializer expects null, and considers it an error if it gets something else.

I plan to add a new deserializer `IgnoreDeserializer`, which will return `null` regardless of the data in the message.

**Comment by mhowlett** [comment]
`IgnoreDeserializer` has been added in 0.11.3
