### ISSUE TITLE
How to hide librdkafka.redist dlls(x86 x64) floder at visual studio solution

### ISSUE THREAD

**Issue by yuleyule66** [confluentinc/confluent-kafka-dotnet#346]
When I refer to the latest README, and reference to the latest version of `librdkafka.redist` (0.11.1),  it generates two folders in my solution, This looks ugly.
![image](https://user-images.githubusercontent.com/8205994/31883128-79b1ebae-b81b-11e7-8c0c-aeae65472f97.png)

Is there any way to solve this problem? thanks.

**Comment by mhowlett** [comment]
thanks for the timely feedback @yuleyule66 - I'm currently working on some other problems with packaging and I'll look into why this is happening as well.

**Comment by mhowlett** [comment]
Can you share some more information about your environment? Which version of visual studio are you using? I just tried referencing both librdkafka.redist and Confluent.Kafka in a Web Application in both VS 2017 and VS 2015 and I do not get these folders on my machine. It would be good to know under what circumstances they occur (I am aware that this problem has occurred before)

**Comment by yuleyule66** [comment]
Environment : 
Visual Studio 2017 (Version : 15.4.1)
librdkafka.redist (Version: 0.11.1)

How to reproduce
================
1. Open Visual Studio 2017, Create a new netstandard class library project. (netstandard2.0)
2. Open manager NuGet package  window.
3. Search librdkafka.redist and click Install button.
4. Visual Studio Solution Explorer shown below:


![20171024153431](https://user-images.githubusercontent.com/8205994/31930047-d87135cc-b8d0-11e7-8c0a-7c906e494687.png)

The csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="librdkafka.redist" Version="0.11.1" />
  </ItemGroup>

</Project>
```

**Comment by Bertrand67** [comment]
Why did your remove librdkafka.redist dependency on version 0.11.1 of Confluent.Kafka nuget ?https://www.nuget.org/packages/Confluent.Kafka/0.11.1
Now it's doesn't build anymore.

**Comment by yuleyule66** [comment]
@Bertrand67 Do you have the same problem?

**Comment by Bertrand67** [comment]
Yes, I have the same problem on VS2015 with librdkafka.redist nuget version 0.11.0.

De : Savorboard [mailto:notifications@github.com]
Envoyé : mardi 24 octobre 2017 11:56
À : confluentinc/confluent-kafka-dotnet <confluent-kafka-dotnet@noreply.github.com>
Cc : Bertrand <bertrand_schneider@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [confluentinc/confluent-kafka-dotnet] How to hide librdkafka.redist dlls(x86 x64) floder at visual studio solution (#346)


@Bertrand67<https://github.com/bertrand67> Do you have the same problem?

**Comment by mhowlett** [comment]
0.11.2 is now on nuget and adds back the dependency. We won't have an implicit dependency for all platforms going forward (there are many of them), but we have decided to keep this for windows x64. in hindsight removing this was a mistake.

**Comment by mhowlett** [comment]
After upgrading visual studio I see the 'x86' 'x64' folders too. This seems to be more of a feature than a problem - No extra folders/files are actually created in my project directory. The folders in VS seem to be just an indication that they will be created in the output directory on build. Note that I'm currently changing the details of how library loading works (there will probably be one top level folder called 'runtimes' instead), however I don't know how to make this directory disappear, whether or not you really want to, or the exact reason for it's existence. Can anyone enlighten us?
