### ISSUE TITLE
Pause/Resume methods are missing in nuget package

### ISSUE THREAD

**Issue by krajek** [confluentinc/confluent-kafka-dotnet#347]
Description
===========
Hi, why Pause/Resume methods are not available on nuget package? I will really need those . Is there any chance they will be available soon?

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.1
 - [ ] Apache Kafka version: 0.11.1

**Comment by alexvaluyskiy** [comment]
@krajek `Consumer.Pause/Resume`, `Consumer.OffsetForTimes`, `updated serializers` are not released yet.
I'm also waiting for these features

**Comment by krajek** [comment]
Let me know if I can help with that one. If Pause/Resume will not be available I will have to switch to much more complex solution in my project.

**Comment by mhowlett** [comment]
they will be in the next major release.

note that you can find an appropriate nuget package on appveyor if you want to access this functionality now (CI-75 should be fine). I'm not aware of any stability problems with master.

**Comment by krajek** [comment]
Thanks for the information
