### ISSUE TITLE
Producer.Dispose does not return after awaiting ProduceAsync

### ISSUE THREAD

**Issue by scharrenberg** [confluentinc/confluent-kafka-dotnet#350]
Description
===========
In the code below the execution stops when leaving the using block. 
When pausing in Visual Studio the debugger reports two deadlocked tasks. 

We derived the example below from the SimpleProducer example. We did not expect any significant difference in behavior, with reference to [the producer documentation](https://github.com/confluentinc/confluent-kafka-dotnet/wiki/Producing-messages)

How to reproduce
================
- Create a producer in an `using` block.
- Await call to ProduceAsync
- Leave `using` block

```C#
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Confluent.Kafka;
using Confluent.Kafka.Serialization;

namespace ResourceTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            const string brokerList = "<broker-url>";
            const string topicName = "topic";

            var config = new Dictionary<string, object>
            {
                {"bootstrap.servers", brokerList}
            };

            PublishWithBlockingDispose(config, topicName).Wait();
        }

        private static async Task PublishWithBlockingDispose(Dictionary<string, object> config, string topicName)
        {
            using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
            {
                var deliveryReport =
                    await producer.ProduceAsync(topicName, null, "samplePayload").ConfigureAwait(false);
                Console.WriteLine($"Partition: {deliveryReport.Partition}, Offset: {deliveryReport.Offset}");
            }

            Console.WriteLine("Unreachable code");
        }
    }
}
```

Checklist
=========
Confluent.Kafka nuget version: 0.11.2
Apache Kafka version: 0.11.0
Client configuration: See code example
Operating system: Windows 10

**Comment by mhowlett** [comment]
This does appear to be a problem. This is surprising since we put a fair bit of effort into resolving this previously. I will look, though unfortunately there are a few things in the queue in front of it.

**Comment by scharrenberg** [comment]
Thanks for the quick reply @mhowlett. Do you have any suggestions for a workaround?

**Comment by ig2r** [comment]
@scharrenberg we're impacted by this issue also, but managed to work around it by having `await Task.Yield()` immediately after the call to `ProduceAsync(...)`, as suggested initially in #92.

**Comment by framiere** [comment]
Can you confirm that #382 fixes the issue?

**Comment by mhowlett** [comment]
yes, I checked this and it's resolved.
