### ISSUE TITLE
Question - multiple topics

### ISSUE THREAD

**Issue by risogolo** [confluentinc/confluent-kafka-dotnet#353]
How do I recognize from what topic the message was received when I'm subscribed for multiple topics. I want to process the data from each topic differently ad I don't want to create a consumer per topic when not neccesary

**Comment by mhowlett** [comment]
you can use the `Topic` property on the `Message` instances received.

**Comment by risogolo** [comment]
But this probably works only within Consume method, what if I want use Poll method?

**Comment by risogolo** [comment]
Thanks
