### ISSUE TITLE
Producer: NullReferenceException when deliveryhandler is null

### ISSUE THREAD

**Issue by alighanem** [confluentinc/confluent-kafka-dotnet#356]
Hello,

Description
===========
I tried the suggestion written in the wiki page which explained to set the deliveryhandler at null when we produce a message to have a fire-and-forget  action (https://github.com/confluentinc/confluent-kafka-dotnet/wiki/Producing-messages).

I got a nullreferenceexception. After taking a look on the code (https://github.com/confluentinc/confluent-kafka-dotnet/blob/268f8b64006bb5a081793671aa72ac0bd9b5e935/src/Confluent.Kafka/Producer.cs), it seems normal that I got this error.

Maybe the documentation have to be updated.

How to reproduce
================

Create the producer with a using statement and use the produceasync method which have a deliveryhandler in its signature . 
The stacktrace : 

System.NullReferenceException: 
   à Confluent.Kafka.SerializingProducer`2.TypedDeliveryHandlerShim.HandleDeliveryReport(Message message)
   à Confluent.Kafka.Producer.DeliveryReportCallbackImpl(IntPtr rk, IntPtr rkmessage, IntPtr opaque)
   à Confluent.Kafka.Impl.LibRdKafka.NativeMethods.rd_kafka_poll(IntPtr rk, IntPtr timeout_ms)
   à Confluent.Kafka.Impl.LibRdKafka.poll(IntPtr rk, IntPtr timeout_ms)
   à Confluent.Kafka.Impl.SafeKafkaHandle.Poll(IntPtr millisecondsTimeout)
   à Confluent.Kafka.Producer.<>c__DisplayClass10_0.<StartPollTask>b__0()
   à System.Threading.Tasks.Task.Execute()
System.AggregateException: 
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Task.Wait()

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.0
 - [x] Apache Kafka version: 0.11.0.1
 - [ ] Client configuration:
 - [x] Operating system: Windows
 - [x] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
Thanks @alighanem, that would be a good feature. I don't think this method has ever behaved as noted on the wiki. Labeled this issue as enhancement and removed from the wiki.

**Comment by alighanem** [comment]
Thanks @mhowlett for your response 👍

**Comment by treziac** [comment]
Indeed, I wrote the doc a bit quick - I was almost sure it was working, sorry for misdirection.

**Comment by mhowlett** [comment]
this is resolved in 1.0-experimental (the callback parameter of `BeginProduce` may be `null`).
