### ISSUE TITLE
Unable to load DLL 'librdkafka': The specified module could not be found.

### ISSUE THREAD

**Issue by JoshLefebvre** [confluentinc/confluent-kafka-dotnet#364]
Description
===========
When trying to create a producer in my existing .NET 4.6.2 framework project using the latest Confluent.Kafka version:
`producer = new Producer<string, string>(config, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8));`
I get the following error: 

> "Unable to load DLL 'librdkafka': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

When I copy my code over to a .NET Core project the producer works fine.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.2
 - [ ] Operating system: Windows 10 x64

**Comment by mhowlett** [comment]
I'm not sure from the information provided. You could try referencing librdkafka.redist explicitly in your project rather than relying on the implicit dependency (i'm not sure why that would work, but it might).

Note that I'm currently changing how native library loading works, and these changes are targeted for inclusion in a release on 20th Nov. Waiting for this will likely solve the issue.

**Comment by JoshLefebvre** [comment]
Yea I read the following from the latest release:

> The librdkafka.redist package dependency is no longer implicit. You must now reference the librdkafka.redist package explicitly in addition to the Confluent.Kafka package

However it does not state how to explicitly add the reference?  I have both packages referenced in my solutions packages.config:
```
  <package id="Confluent.Kafka" version="0.11.2" targetFramework="net462" />
  <package id="librdkafka.redist" version="0.11.1" targetFramework="net462" />
```
and in my .csproj the only reference to librdkafka is the following at the top of the file:
`<Import Project="..\..\..\packages\librdkafka.redist.0.11.1\build\net\librdkafka.redist.props" Condition="Exists('..\..\..\packages\librdkafka.redist.0.11.1\build\net\librdkafka.redist.props')" />`

while Confluent.Kafka is referenced in the followign way:
```
    <Reference Include="Confluent.Kafka, Version=0.11.2.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\..\packages\Confluent.Kafka.0.11.2\lib\net46\Confluent.Kafka.dll</HintPath>
    </Reference>
```

**Comment by JoshLefebvre** [comment]
When trying to explictly reference librdkafka.redist in my .csproj as follows:
```
   <Reference Include="librdkafka.redist, Version=0.11.1.0, Culture=neutral">
      <HintPath>..\..\..\packages\librdkafka.redist.0.11.1\runtimes\win7-x64\native\librdkafka.dll</HintPath>
   </Reference>
```
I get the follow exception: 

> BadImageFormatException: An attempt was made to load a program with an incorrect format.

**Comment by JoshLefebvre** [comment]
Using the following code referenced in https://github.com/confluentinc/confluent-kafka-dotnet/issues/72: 
```
 var baseUri = new Uri(Assembly.GetExecutingAssembly().GetName().CodeBase);
 var baseDirectory = Path.GetDirectoryName(baseUri.LocalPath);
 var directory = Path.Combine(baseDirectory, "x64")
```
I was able to determine that the dependency to librdkafka.redist was not being resolved in my module's /bin folder but rather in a central location where all of my dll's reside for the entire solution. I am using an MVC framework called Orcahrd CMS and this uses a folder called app_data/dependencies for "load an arbitrary set of modules at run-time".  Therefore I needed to manually copy my x64 dlls to this folder.

**Comment by mhowlett** [comment]
thanks for giving an update on this. The x64/x86 directories need to be in the same location as Confluent.Kafka.dll (in the .NET Framework case). This is is what you describe, right? 

In the next release, just a warning that the x64/x86 directories will be moved to be sub-directories of a librdkafka directory.

Also, you'll be able to explicitly specify a path to your librdkafka, something you may find useful.

**Comment by JoshLefebvre** [comment]
Yep exactly that, in my case te x64/x86 directories weren't being copied over to the correct directory. This seems to be an Orchard CMS issue and not related to the package itself. Yes this will be extremly important to specify an exact location for librdkafka going forward seeing as the directory to which I need to manually copy it into is part of my .gitignore

**Comment by HanaaGhasoub** [comment]
Supported framework is only 462 https://www.nuget.org/packages/Confluent.Kafka/#supportedframeworks-body-tab
