### ISSUE TITLE
Confusion  of  using  CommitAsync

### ISSUE THREAD

**Issue by wangkewei111** [confluentinc/confluent-kafka-dotnet#365]
Description
===========
I'm confused about the use of CommitAsync. 
Consumer test code：
~~~ csharp

using (var consumer = new Consumer<Null, string>(config, null, new StringDeserializer(Encoding.UTF8)))
                {
                    var committedOffset1 = consumer.CommitAsync(new List<TopicPartitionOffset> { new TopicPartitionOffset("test", 1, 5) }).Result;
                    foreach (var offset in committedOffset1.Offsets)
                    {
                        Console.WriteLine($"commitoffset: {offset.Offset}");
                    }
                    consumer.Subscribe("test");                    
                    while (true)
                    {
                        Message<Null, string> msg;
                        if (consumer.Consume(out msg, TimeSpan.FromSeconds(5)))
                        {                      
                            var committedOffset2 = consumer.CommitAsync(new List<TopicPartitionOffset> { new TopicPartitionOffset(topics.First(), 1, 12) }).Result;
                            foreach(var offset in committedOffset2.Offsets)
                            {
                               Console.WriteLine($"commitoffset: {offset.Offset}");
                            }
                            Console.WriteLine($"Topic: {msg.Topic} Partition: {msg.Partition} Offset: {msg.Offset}  value:{msg.Value}");            
                        }
                    }
                }
~~~
![77a1a305749e518ee1efb52e9ccafc9](https://user-images.githubusercontent.com/17756087/32585066-9409cfc6-c536-11e7-9584-6847383d9b5e.png)

call CommitAsync() before Consume(),it works. the offset is 5:   
![ce1e9c8746859f3aabe630d370660b4](https://user-images.githubusercontent.com/17756087/32585120-d4337494-c536-11e7-9797-a84f2d39ab24.png)

call CommitAsync() after Consume(),the next offset is not affected, 
in the loop:offset is 12.

![cacb879ce603fde5a5265b4d609ed70](https://user-images.githubusercontent.com/17756087/32585191-34de3f04-c537-11e7-9284-76ff0d787b45.png)

when Consumer  closed,the offset is the last  number 
![f659fc74b7670a0cd863b40ff2f5182](https://user-images.githubusercontent.com/17756087/32585265-995a9f22-c537-11e7-985a-ab685d73fdc9.png)  

I run the consumer again，offset is the last number,consumer can not receive msg . CommitAsync  does not work:

![764b4854b9d493e9af69529e1845de8](https://user-images.githubusercontent.com/17756087/32585348-034fde1a-c538-11e7-8741-7d0ae629a995.png)

![a8976b87dbbd3fac71da80cc9b1f707](https://user-images.githubusercontent.com/17756087/32585317-e08d73ce-c537-11e7-80d8-b29aa1dde22f.png)

then,wait a moment,run again,it works,just like the first time.

**Comment by mhowlett** [comment]
sorry for the looong delay in responding @wangkewei111 . `CommitAsync` does not change the current read position of the `Consumer` - only the offsets committed to Kafka. The two are independent. If you want to change the read position, you can use the `Seek` method. We don't have this documented clearly yet - sorry about that! Noted this as something to document.
