### ISSUE TITLE
Manual commit takes long

### ISSUE THREAD

**Issue by KarolisKaj** [confluentinc/confluent-kafka-dotnet#366]
Description
===========
I am commiting every single message manually & synchronous, meaning next message will be consumed after previously finished commit. How ever when I synchronously publish a message it takes 95ms. So issue is that synchronous commit takes 1036 ms while synchronous publish takes 95 ms. How can I make commits as fast as publishes?

Maybe there is an issue with my configuration? Please, suggest what could be wrong. Thanks!

__Update__
I have tried on a different topic and with freshly created topic it works flawlessly, maybe you can suggest what could cause the problem in the settings of the topic?

How to reproduce
================
Create a new consumer on each message received perform CommitAsync in a synchronous fashion. Blocking of Commit will take something close to 1036 ms.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.1
 - [x] Apache Kafka version: 0.10
 - [x] Client configuration:
```xml
<add key="group.id" value="Consumer" />
<add key="bootstrap.servers" value="hosts" />
<add key="socket.blocking.max.ms" value="1" />
<add key="enable.auto.commit" value="false" />
```
 - [x] Operating system: Win7x64
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration): There are no logs related to it.
 - [ ] Provide broker log excepts: There are no logs related to it.
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka will use the same broker connection both for commits and fetching messages, thus a commit may be backed up behind a long-poll blocking Fetch request.
The long-poll behaviour of fetch requests is configured with the `fetch.wait.max.ms` property that defaults to 100ms. You can decrease that value to decrease offset commit latency at the expense of a larger number of Fetch requests (depending on your traffic pattern).

To see the latency of each request you can enable `debug=protocol` and look at the rtt (round-trip-time) printout of OffsetCommit and Fetch requests.

**Comment by KarolisKaj** [comment]
@edenhill Thank you so much for getting back to me! I will try to apply these configuration properties when I get back to work.
Say, could that be the case even if one topic allows you to commit within 100 ms range while another topic performs same task 10x slower (1s)?

**Comment by mhowlett** [comment]
this is the same issue as #433 and https://github.com/edenhill/librdkafka/issues/1787 . closing in favor of those.
