### ISSUE TITLE
why message is consumed before HandleDeliveryReport event

### ISSUE THREAD

**Issue by llmsjraj** [confluentinc/confluent-kafka-dotnet#368]
Hi,

i want to know why message is consumed before HandleDeliveryReport event fired. Is there any sense it? I don't know whether message is delivered or not but message is getting consumed.

@mhowlett  Is there any way to restrict that HandleDeliveryReport event is fired first then message would be consumed?

Thanks

**Comment by mhowlett** [comment]
By 'consumed' I think you mean 'the offset is committed'. You can disable auto offset commit (see #362 for more info - it's a bit confusing at present) and explicitly commit the message yourself using `CommitAsync`. Note that this is relatively slow - if you want high throughput you'll need to commit periodically. There is also 'store offsets' functionality coming in the next release that can be used to automate this.

**Comment by mhowlett** [comment]
i think i misunderstood you before. if you're using 'acks=all' (or have just one broker), the message will be available for consumption, and to be acked at exactly the same time. which one you get first would be non-deterministic. there is probably a bias one way or the other (quite likely the consume path is faster by the sounds of it). no, I can't think how you could guarantee a delivery report before the message is consumed.
