### ISSUE TITLE
After upgrade to Kafka 1.0.0 version : java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by VinayDanda** [confluentinc/confluent-kafka-dotnet#372]
Description
===========
I upgraded Kafka from 0.10.2.1 to 1.0.0 version. And only from then, I'm seeing the kafka service going down because of below issue:
```ERROR [KafkaApi-1] Error when handling request ; (kafka.server.KafkaApis) {replica_id=-1,max_wait_time=500,min_bytes=1,topics=[{topic=xxxx,partitions=[{partition=1,fetch_offset=847134777,max_bytes=1048576}]}]} java.lang.OutOfMemoryError: Java heap space```
Even after increasing the HEAP size (KAFKA_HEAP_OPTS) to 7G, still the same error is coming. 

Can you please help on this issue.

How to reproduce
================
Upgrade from 0.10.2.1 version to 1.0.0 version.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [x] Apache Kafka version: 2.12-1.0.0
 - [ ] Client configuration:
 - [x] Operating system: Centos 7
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
How many partitions are you consuming?

Does it help to decrease `fetch.message.max.bytes` on the consumer?

**Comment by VinayDanda** [comment]
Thanks Edenhill for your reply.
3 partitions are being consumed, with replication factor 2. 
As i see, there shouldn't be an issue with the fetch.message.max.bytes on the consumer because before the upgrade, it was working perfectly fine without any issues. So, this wouldn't make difference.

**Comment by edenhill** [comment]
Also provide your client configuration (see Checklist above)

**Comment by VinayDanda** [comment]
I'm using Apache Kafka: version - 2.12-1.0.0. 
Consumer instance is logstash to pull data from kafka.
Not using librdkafka.redist/confluent.kafka.

**Comment by edenhill** [comment]
So you are not using confluent-kafka-dotnet?

**Comment by VinayDanda** [comment]
Nope. I'm using only Apache Kafka. If this is wrong place to post the question, can you please direct the right link.

**Comment by edenhill** [comment]
This repo is for issues with Confluent's .NET kafka client only.

For questions about Apache Kafka itself, use the kafka-users mailing list:
https://kafka.apache.org/contact

**Comment by VinayDanda** [comment]
Thank you, and sorry for the trouble.
