### ISSUE TITLE
Why is Consumer.Consume going away?

### ISSUE THREAD

**Issue by afrancoc2000** [confluentinc/confluent-kafka-dotnet#376]
Hi, I have an implementation of a consumer that runs everyday and reads everything in a topic and then process it and sends it to a file.

I like the way the reactive programming using Poll and OnMessage works but, in my case I'm not being reactive and I don't intend to stay reading if there are no new messages. I will just stop the app until the next day and then it can read all the new messages.

I don't see how can I see if Poll timed out but with consume I have a nice boolean return, I could meassure the time since the beginning of the Poll but somehow that seems kind of ugly.

And also, I return a list of all the messages I found in the broker so, again not reacting, collecting all the messages in the OnMessage method makes me fear I may loose a message if I return the list of messages and maybe after the polling timeout the OnMessage hasn't finish.

This is avoided too with the Consume method but I am getting a message telling me that I should prefer The Poll method and that Consume is going away.

So these are the reasons I believe it shoul stay.

This is my code:

        public IEnumerable<T> GetMessages<T>()
        {
            var targets = new List<T>();

            Message<Null, string> message;
            while (consumer.Consume(out message, TimeSpan.FromMilliseconds(100)) && targets.Count() < MaxRequests)
            {
                logger.Info($"Topic: {message.Topic} Partition: {message.Partition} Offset: {message.Offset} {message.Value}");

                T target = JsonConvert.DeserializeObject<T>(message.Value);
                targets.Add(target);

                var committedOffsets = consumer.CommitAsync(message).Result;
                logger.Info($"Committed offset: {committedOffsets}");
            }

            return targets;
        }

I guess I shoud change it like this but I think the one using Consume its better:

        public IEnumerable<T> GetMessages<T>()
        {
            var targets = new List<T>();

            consumer.OnMessage += (_, message) =>
            {
                logger.Info($"Topic: {message.Topic} Partition: {message.Partition} Offset: {message.Offset} {message.Value}");

                T target = JsonConvert.DeserializeObject<T>(message.Value);
                targets.Add(target);

                var committedOffsets = consumer.CommitAsync(message).Result;
                logger.Info($"Committed offset: {committedOffsets}");
            };

            var timeout = false;
            while (!timeout)
            {
                var start = DateTime.Now;
                consumer.Poll(TimeSpan.FromSeconds(5));

                if (DateTime.Now - start >= TimeSpan.FromSeconds(5))
                {
                    timeout = true;
                }
            }

            return targets;
        }

I'm using confluent.kafka nuget v0.11.2

**Comment by mhowlett** [comment]
Hi @afrancoc2000 - thanks for the feedback! you can be confident the `Consume` method is not going to be removed. We have removed this warning in the master branch.

**Comment by afrancoc2000** [comment]
Thanks!!!
