### ISSUE TITLE
Multiple consumer instances, or nah?

### ISSUE THREAD

**Issue by TaiAivaras** [confluentinc/confluent-kafka-dotnet#378]
Hey,

I'm facing a challenge of needing to consume different types of messages in my application. I was wondering what are some of the best practices for this case - is creating multiple connections to Kafka cluster the best solution?

Also for this case - what would be the best way to handle deserializers? Would a generic object deserializer would be possible?

Thanks!

**Comment by gwake1** [comment]
I think this might help: http://www.enterpriseintegrationpatterns.com/patterns/messaging/CanonicalDataModel.html

**Comment by mhowlett** [comment]
@gwake1's comment is good (side note: avro serdes are not too far away), and required if you're trying to store different types in the same topic. If you have different types in different topics, the most efficient way to do what you want is to consume as `byte[]` then switch on topic name and deserialize by hand. If you're not network resource constrained (i.e. your cluster is small & you only need 2 or 3 of them), you could use multiple `Consumer`s for convenience.

**Comment by TaiAivaras** [comment]
I see - thanks for the answers, closing the question.
