### ISSUE TITLE
Feature Request: Producer and Consumer Interfaces for IOC and Unit testing

### ISSUE THREAD

**Issue by David-V-Spencer** [confluentinc/confluent-kafka-dotnet#380]
Description
===========
Unit testing is critical for any production application and Dependency Injection is a very common design pattern used in C# applications.

With the absence of interfaces for the producer and consumer in Kafka-dotnet mocking/substituting the kafka dependency in unit tests is difficult and requires abstracting the library with an extra layer.

Additionally the producer and consumer does not support the IOC design pattern that is common in many modern applications. 

Additionally adding producer and consumer interfaces should not be a breaking change to implement but would provide great value and flexibility to the project.

How to reproduce
================
Using Kafka Server version 2.11-0.10.2.1.

Currently developing Windows 7 / 10 / Server 2012 operating systems but moving towards .net core 2.0 and supporting Linux Centos/Ubuntu distros as well.

Create any new project utilizing Confluent Kafka Dotnet version 11.2 or earlier with default configuration.
- Only way to create producer or consumer is to directly instantiate them inside a class.
- Lacking interface makes kafka dotnet dependecies impossible to substitute directly in unit tests with tools such as N-Substitute.

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version:
 - [X] Apache Kafka version: 
 - [X] Client configuration:
 - [X] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
Thanks @David-V-Spencer - this is high priority, yes. the second most requested feature behind avro/schema registry integration. i will try to get this done soon, but it'll happen after avro/sr as there is huge demand for that.

**Comment by David-V-Spencer** [comment]
@mhowlett  Thanks for the response. Looking forward to this addition as well as schema registry.

**Comment by teraxas** [comment]
Any idea when this will be completed? Currently I see there is ISerializingProducer<TKey, TValue>, but it doesn't cover whole class

**Comment by mhowlett** [comment]
These are in 'experimental' builds already, which hopefully will be fully reviewed and on a 1.0.x branch relatively soon.

**Comment by mhowlett** [comment]
closing - track the experimental branch for progress.
