### ISSUE TITLE
Connect failure to kafka server

### ISSUE THREAD

**Issue by LeDucThang** [confluentinc/confluent-kafka-dotnet#386]
Description
===========
I installed kafka by tutorial : https://www.vultr.com/docs/how-to-install-apache-kafka-on-centos-7
and used Advance Producer from https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdvancedProducer/Program.cs and project installed nuget Confluent.Kafka -Version 0.11.2

But i can't run success example and the error returned is "Local: Message timed out"
I don't know where i was wrong. Can somebody help me ?

Checklist
=========
Please provide the following information:

 - [X ] Confluent.Kafka nuget version: 0.11.2
 - [X ] Apache Kafka version:  kafka_2.11-0.11.0.2.tgz  
 - [ X] Client configuration: var config = new Dictionary<string, object> { { "bootstrap.servers", brokerList } };
 - [ X] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
i sounds like you've configured bootstrap.servers incorrectly (it should be IP:PORT, eg 127.0.0.1:9092) or maybe you have some security settings blocking access.

**Comment by LeDucThang** [comment]
This is my configuration of bootstrap.servers
 string brokerList = "10.1.11.244:9092";
string topicName = "OrganizationEntities";

i only successed 1 time when i used docker pull wurstmeister/kafka. However, when i try others kafka docker or my instance on server, i just have got Messsage timed out. The returned error didn't show the real cause for me.
I still see a established connection from my PC to server on port 9092 by netstat command

**Comment by mhowlett** [comment]
try using the confluent docker images using the instructions here:
https://docs.confluent.io/current/installation/docker/docs/quickstart.html

you can set the "debug" configuration property to "all" for very verbose client logs.

the client assumes that brokers will go down from time to time and considers this normal. it will just keep trying to reconnect in the background. if a message can't be delivered according to the configured timeout settings, you'll get a time out error.
