### ISSUE TITLE
 Multiple Subscribes and Unsubscribes using single consumer instance

### ISSUE THREAD

**Issue by chiru1205** [confluentinc/confluent-kafka-dotnet#388]
Description
===========
I'm working on a recovery process which will replay messages based on a key value and recreate our data objects. During replay , there is a chance that recovery process kicks in multiple times for multiple keys to recreate our data object collection. I was able to achieve what I wanted but noticed that there is an unmanaged exception thrown in the librdKafak.dll and it completely shutsdown my application.

At any give time there is only one recovery process using the consumer instance. Process does this
1. use the consumer instance to subscribe to a topic
2. replay messages from a specific offset.
3. After the replay unsubscribe from the topic

The reason to use one consumer instance is to avoid creating bunch of consumer instances. I don't know whats the hard limit on the number of consumer connections.

How to reproduce
================

1. Create a consumer instance 
2. Subscribe to a topic by calling Consumer.Subscribe("Topic")
3. On PartitionAssigned,  assign partitions to read from and from a specific offset 
4. Unsubscribe from the topic by calling Consumer.UnSubscribe

Replay above steps for like 100 times. My application is shutdown during 8th replay or 9th.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version:0.11.0.0
 - [x] Apache Kafka version: 0.9.0.0
 - [x] Client configuration:
 {"group.id", groupId},
                {"enable.auto.commit", enableAutoCommit},
                {"api.version.request", false },
                {"auto.commit.interval.ms", 5000},
                {"statistics.interval.ms", 60000},
                {"debug","protocol,cgrp,topic,fetch,msg" },
                {"bootstrap.servers", brokerList},
                {
                    "default.topic.config", new Dictionary<string, object>()
                    {
                        {"auto.offset.reset", "smallest"}
                    }
                }
 - [x] Operating system: Windows 7
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue: Yes for my use case

**Comment by mhowlett** [comment]
@chiru1205 - can you upgrade to 0.11.3 and verify this is still a problem? there have been substantial changes since then, and it's possible this is no longer an issue.

If there is still a problem, it'd be great if you could provide a minimal program demonstrating it - this would help a lot in verifying / tracking down it down. 

thanks for the feedback!

**Comment by chiru1205** [comment]
@mhowlett , here is a sample code that shuts down the application 



_recoveryConsumer =
             new Consumer<Null, string>(
                  GetConsumerConfig(
                      Guid.NewGuid().ToString(),
                      "localhost:9092", false), null, new StringDeserializer(System.Text.Encoding.UTF8));
long[] currentOffset = { 0L };
_recoveryConsumer.OnMessage += (_, m) =>
            {
                currentOffset[0] = m.Offset;
                try
                {
                    nMessages++;
                    catchupMessage = JsonConvert.DeserializeObject<KafkaMessage>(m.Value);
                    //additional logic
                }
                catch (Exception ex)
                {
                  //ignore
                }
            };
           _recoveryConsumer.OnPartitionsAssigned += (obj, partitions) =>
                {
                  
                    _recoveryConsumer.Assign(new List<TopicPartitionOffset> { new TopicPartitionOffset("TestAttempt", 0, 123456) }); //here read from a specific offset
                };
         _recoveryConsumer.Subscribe("TestTopic") ;

       
           while (currentOffset[0] < originalMessageOffset)
            {

                _recoveryConsumer.Poll(TimeSpan.FromMilliseconds(100));
            }
        
        _recoveryConsumer.UnSubscribe() ;

Put this in a for loop and run 10 times. what the code above is doing is read from a specific offset and recover data related to a specific key and build our object for the key.  Everytime this code is run, see that I subscribe and later unsubscribe.

**Comment by chiru1205** [comment]
I also tried assign and unassign, it did work but I see a different problem. Here is the data I see in the logs after running recovery for 4 times, this time using assign and unassign combination instead of subscribe , unsubscrie. It appears each assign will be an instance of consumer that will fecth data. Since I ran the recovery 4 times, 4 th run its fetching same data 4 times.

![image](https://user-images.githubusercontent.com/16243876/33624900-7dc2bc84-d9bb-11e7-9969-487adbc4a747.png)

**Comment by edenhill** [comment]
debug=fetch,topic  can be useful to see what and why a consumer is fetching

**Comment by chiru1205** [comment]
13:41:47,655 [9]  - Starting......
 13:41:53,454 [9]  - Recovery Consumer Task Started...
 13:41:53,468 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTSTATE,[thrd:main]: Partition TestTopic [0] changed fetch state none -> active
 13:41:53,472 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op PARTITION_JOIN in state up (join state started, v3) for TestTopic [0]
 13:41:53,476 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTADD,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": add TestTopic [0]
 13:41:53,716 [18]  - OnLog Message : rdkafka#consumer-1,7,QRYLEADER,[thrd:main]: Topic TestTopic [0]: leader is unavailable: re-query
 13:41:53,807 [30]  - OnLog Message : rdkafka#consumer-1,7,TOPBRK,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Topic TestTopic [0]: joining broker (rktp 0ACA61C0)
 13:41:53,837 [20]  - OnLog Message : rdkafka#consumer-1,7,SEND,[thrd:ati-stg-kaf03:9092/bootstrap]: ati-stg-kaf03:9092/bootstrap: Sent MetadataRequest (v0, 38 bytes @ 0, CorrId 2)
 13:41:53,920 [20]  - OnLog Message : rdkafka#consumer-1,7,RECV,[thrd:ati-stg-kaf03:9092/bootstrap]: ati-stg-kaf03:9092/bootstrap: Received MetadataResponse (v0, 310 bytes, CorrId 2, rtt 93.00ms)
 13:41:53,921 [18]  - OnLog Message : rdkafka#consumer-1,7,METADATA,[thrd:main]:   Topic TestTopic partition 0 Leader 5
 13:41:53,922 [18]  - OnLog Message : rdkafka#consumer-1,7,METADATA,[thrd:main]: ati-stg-kaf03:9092/bootstrap: 1/1 requested topic(s) seen in metadata
 13:41:54,808 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCHDEC,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: Topic TestTopic [0]: fetch decide: updating to version 2 (was 0) at offset 323054998 (was 0)
 13:41:54,809 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Topic TestTopic [0] in state active at offset 323054998 (0/100000 msgs, 0/1000000 kb queued, opv 2) is fetchable: 
 13:41:54,812 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCHADD,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Added TestTopic [0] to fetch list (1 entries, opv 2)
 13:41:54,813 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Fetch topic TestTopic [0] at offset 323054998 (v2)
 13:41:54,814 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Fetch 1/1/1 toppar(s)
 13:41:54,815 [30]  - OnLog Message : rdkafka#consumer-1,7,SEND,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Sent FetchRequest (v1, 70 bytes @ 0, CorrId 1)
 13:41:55,605 [30]  - OnLog Message : rdkafka#consumer-1,7,RECV,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Received FetchResponse (v1, 1032202 bytes, CorrId 1, rtt 795.00ms)
 13:41:55,607 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Topic TestTopic [0] MessageSet size 1032159, error "Success", MaxOffset 323143774, Ver 2/2
 13:41:55,610 [30]  - OnLog Message : rdkafka#consumer-1,7,CONSUME,[thrd:ATI-STG-KAF05.ad.ascendlearning.com:9092/5]: ATI-STG-KAF05.ad.ascendlearning.com:9092/5: Enqueue 2023 messages on TestTopic [0] fetch queue (qlen 0, v2)
 13:41:55,611 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch topic TestTopic [0] at offset 323057021 (v2)
 13:41:55,613 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch 1/1/1 toppar(s)
 13:41:55,637 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op ASSIGN (v0) in state up (join state started, v3 vs 0)
 13:41:55,637 [30]  - OnLog Message : rdkafka#consumer-1,7,SEND,[thrd:TestServer:9092/5]: TestServer:9092/5: Sent FetchRequest (v1, 70 bytes @ 0, CorrId 2)
 13:41:55,639 [18]  - OnLog Message : rdkafka#consumer-1,7,ASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": new assignment of 0 partition(s) in join state started
 13:41:55,641 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": rd_kafka_cgrp_assign:2198: new version barrier v4
 13:41:55,642 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPJOINSTATE,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" changed join state started -> wait-unassign (v4, state up)
 13:41:55,642 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": rd_kafka_cgrp_unassign:2114: new version barrier v5
 13:41:55,643 [18]  - OnLog Message : rdkafka#consumer-1,7,UNASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": unassigning 1 partition(s) (v5)
 13:41:55,644 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: TestTopic [0]: rd_kafka_toppar_op_fetch_stop:2039: new version barrier v3
 13:41:55,646 [18]  - OnLog Message : rdkafka#consumer-1,7,CONSUMER,[thrd:main]: Stop consuming TestTopic [0] (v3)
 13:41:55,647 [18]  - OnLog Message : rdkafka#consumer-1,7,DESP,[thrd:main]: Removing (un)desired topic TestTopic [0]
 13:41:55,648 [18]  - OnLog Message : rdkafka#consumer-1,7,RESUME,[thrd:main]: Library resuming 1 partition(s)
 13:41:55,649 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: TestTopic [0]: rd_kafka_toppar_op_pause_resume:2097: new version barrier v4
 13:41:55,651 [18]  - OnLog Message : rdkafka#consumer-1,7,RESUME,[thrd:main]: Resume TestTopic [0] (v4)
 13:41:55,656 [18]  - OnLog Message : rdkafka#consumer-1,7,UNASSIGN,[thrd:main]: Unassign not done yet (1 wait_unassign, 1 assigned, 0 wait commit): unassign
 13:41:55,657 [18]  - OnLog Message : rdkafka#consumer-1,7,ASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": assigning 0 partition(s) in join state wait-unassign
 13:41:55,658 [18]  - OnLog Message : rdkafka#consumer-1,7,OP,[thrd:main]: TestTopic [0] received op FETCH_STOP (v3) in fetch-state active (opv2)
 13:41:55,659 [18]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:main]: Stopping fetch for TestTopic [0] in state active (v3)
 13:41:55,660 [9]  - Consumed 6 in 2s
 13:41:55,661 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTSTATE,[thrd:main]: Partition TestTopic [0] changed fetch state active -> stopping
 13:41:55,661 [9]  - 3 messages/s
 13:41:55,662 [18]  - OnLog Message : rdkafka#consumer-1,7,STORETERM,[thrd:main]: TestTopic [0]: offset store terminating
 13:41:55,662 [9]  - Recovery Consumer Task Ended... 
 13:41:55,663 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTSTATE,[thrd:main]: Partition TestTopic [0] changed fetch state stopping -> stopped
 
 
 13:41:55,664 [9]  - Recovery Consumer Task Started...
 13:41:55,664 [18]  - OnLog Message : rdkafka#consumer-1,7,OP,[thrd:main]: TestTopic [0] received op PAUSE (v4) in fetch-state stopped (opv3)
 13:41:55,666 [18]  - OnLog Message : rdkafka#consumer-1,7,RESUME,[thrd:main]: Not resuming stopped TestTopic [0]: at offset 323054998 (state stopped, v4)
 13:41:55,667 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op PARTITION_LEAVE in state up (join state wait-unassign, v5) for TestTopic [0]
 13:41:55,672 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTDEL,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": delete TestTopic [0]
 13:41:55,675 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v5) for TestTopic [0]
 13:41:55,677 [18]  - OnLog Message : rdkafka#consumer-1,7,UNASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": unassign done in state up (join state wait-unassign): without new assignment: FETCH_STOP done
 13:41:55,680 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPJOINSTATE,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" changed join state wait-unassign -> init (v5, state up)
 13:41:55,683 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op ASSIGN (v0) in state up (join state init, v5 vs 0)
 13:41:55,687 [18]  - OnLog Message : rdkafka#consumer-1,7,ASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": new assignment of 1 partition(s) in join state init
 13:41:55,689 [18]  - OnLog Message : rdkafka#consumer-1,7,DESP,[thrd:main]: Setting topic TestTopic [0] partition as desired
 13:41:55,692 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": rd_kafka_cgrp_assign:2198: new version barrier v6
 13:41:55,693 [18]  - OnLog Message : rdkafka#consumer-1,7,ASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": assigning 1 partition(s) in join state init
 13:41:55,694 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPJOINSTATE,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" changed join state init -> assigned (v6, state up)
 13:41:55,695 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": rd_kafka_cgrp_partitions_fetch_start0:1568: new version barrier v7
 13:41:55,696 [18]  - OnLog Message : rdkafka#consumer-1,7,FETCHSTART,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": starting fetchers for 1 assigned partition(s) in join-state assigned (usable_offsets=no, v7, line 2243)
 13:41:55,699 [18]  - OnLog Message : rdkafka#consumer-1,7,FETCHSTART,[thrd:main]: List with 1 partition(s):
 13:41:55,700 [18]  - OnLog Message : rdkafka#consumer-1,7,FETCHSTART,[thrd:main]:  TestTopic [0] offset 323054998
 13:41:55,701 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPJOINSTATE,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" changed join state assigned -> started (v7, state up)
 13:41:55,703 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: TestTopic [0]: rd_kafka_toppar_op_fetch_start:2012: new version barrier v5
 13:41:55,704 [18]  - OnLog Message : rdkafka#consumer-1,7,CONSUMER,[thrd:main]: Start consuming TestTopic [0] at offset 323054998 (v5)
 13:41:55,705 [18]  - OnLog Message : rdkafka#consumer-1,7,OP,[thrd:main]: TestTopic [0] received op FETCH_START (v5) in fetch-state stopped (opv4)
 13:41:55,706 [18]  - OnLog Message : rdkafka#consumer-1,7,OP,[thrd:main]: TestTopic [0] received op FETCH_START (v5) in fetch-state stopped (opv4)
 13:41:55,707 [18]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:main]: Start fetch for TestTopic [0] in state stopped at offset 323054998 (v5)
 13:41:55,708 [18]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:main]: Start fetch for TestTopic [0] in state stopped at offset 323054998 (v5)
 13:41:55,709 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTSTATE,[thrd:main]: Partition TestTopic [0] changed fetch state stopped -> active
 13:41:55,709 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTSTATE,[thrd:main]: Partition TestTopic [0] changed fetch state stopped -> active
 13:41:55,710 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op PARTITION_JOIN in state up (join state started, v7) for TestTopic [0]
 13:41:55,711 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op PARTITION_JOIN in state up (join state started, v7) for TestTopic [0]
 13:41:55,712 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTADD,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": add TestTopic [0]
 13:41:55,714 [18]  - OnLog Message : rdkafka#consumer-1,7,PARTADD,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": add TestTopic [0]
 13:41:55,741 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCHDEC,[thrd:TestServer:9092/5]: Topic TestTopic [0]: fetch decide: updating to version 5 (was 2) at offset 323054998 (was 323057021)
 13:41:55,742 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCHDEC,[thrd:TestServer:9092/5]: Topic TestTopic [0]: fetch decide: updating to version 5 (was 2) at offset 323054998 (was 323057021)
 13:41:56,283 [30]  - OnLog Message : rdkafka#consumer-1,7,RECV,[thrd:TestServer:9092/5]: TestServer:9092/5: Received FetchResponse (v1, 1029540 bytes, CorrId 2, rtt 640.00ms)
 13:41:56,285 [30]  - OnLog Message : rdkafka#consumer-1,7,RECV,[thrd:TestServer:9092/5]: TestServer:9092/5: Received FetchResponse (v1, 1029540 bytes, CorrId 2, rtt 640.00ms)
 13:41:56,287 [30]  - OnLog Message : rdkafka#consumer-1,7,DROP,[thrd:TestServer:9092/5]: TestServer:9092/5: TestTopic [0]: dropping outdated fetch response (v2 < 5)
 13:41:56,289 [30]  - OnLog Message : rdkafka#consumer-1,7,DROP,[thrd:TestServer:9092/5]: TestServer:9092/5: TestTopic [0]: dropping outdated fetch response (v2 < 5)
 13:41:56,290 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch topic TestTopic [0] at offset 323054998 (v5)
 13:41:56,291 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch topic TestTopic [0] at offset 323054998 (v5)
 13:41:56,295 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch 1/1/1 toppar(s)
 13:41:56,296 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch 1/1/1 toppar(s)
 13:41:56,297 [30]  - OnLog Message : rdkafka#consumer-1,7,SEND,[thrd:TestServer:9092/5]: TestServer:9092/5: Sent FetchRequest (v1, 70 bytes @ 0, CorrId 3)
 13:41:56,299 [30]  - OnLog Message : rdkafka#consumer-1,7,SEND,[thrd:TestServer:9092/5]: TestServer:9092/5: Sent FetchRequest (v1, 70 bytes @ 0, CorrId 3)
 13:41:56,801 [30]  - OnLog Message : rdkafka#consumer-1,7,RECV,[thrd:TestServer:9092/5]: TestServer:9092/5: Received FetchResponse (v1, 1032202 bytes, CorrId 3, rtt 499.00ms)
 13:41:56,805 [30]  - OnLog Message : rdkafka#consumer-1,7,RECV,[thrd:TestServer:9092/5]: TestServer:9092/5: Received FetchResponse (v1, 1032202 bytes, CorrId 3, rtt 499.00ms)
 13:41:56,806 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Topic TestTopic [0] MessageSet size 1032159, error "Success", MaxOffset 323143774, Ver 5/5
 13:41:56,806 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Topic TestTopic [0] MessageSet size 1032159, error "Success", MaxOffset 323143774, Ver 5/5
 13:41:56,808 [30]  - OnLog Message : rdkafka#consumer-1,7,CONSUME,[thrd:TestServer:9092/5]: TestServer:9092/5: Enqueue 2023 messages on TestTopic [0] fetch queue (qlen 0, v5)
 13:41:56,809 [30]  - OnLog Message : rdkafka#consumer-1,7,CONSUME,[thrd:TestServer:9092/5]: TestServer:9092/5: Enqueue 2023 messages on TestTopic [0] fetch queue (qlen 0, v5)
 13:41:56,809 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch topic TestTopic [0] at offset 323057021 (v5)
 13:41:56,833 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch topic TestTopic [0] at offset 323057021 (v5)
 13:41:56,834 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch 1/1/1 toppar(s)
 13:41:56,842 [30]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:TestServer:9092/5]: TestServer:9092/5: Fetch 1/1/1 toppar(s)
 13:41:56,863 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op ASSIGN (v0) in state up (join state started, v7 vs 0)
 13:41:56,864 [30]  - OnLog Message : rdkafka#consumer-1,7,SEND,[thrd:TestServer:9092/5]: TestServer:9092/5: Sent FetchRequest (v1, 70 bytes @ 0, CorrId 4)
 13:41:56,865 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPOP,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" received op ASSIGN (v0) in state up (join state started, v7 vs 0)
 13:41:56,865 [30]  - OnLog Message : rdkafka#consumer-1,7,SEND,[thrd:TestServer:9092/5]: TestServer:9092/5: Sent FetchRequest (v1, 70 bytes @ 0, CorrId 4)
 13:41:56,866 [18]  - OnLog Message : rdkafka#consumer-1,7,ASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": new assignment of 0 partition(s) in join state started
 13:41:56,868 [18]  - OnLog Message : rdkafka#consumer-1,7,ASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": new assignment of 0 partition(s) in join state started
 13:41:56,869 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": rd_kafka_cgrp_assign:2198: new version barrier v8
 13:41:56,870 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": rd_kafka_cgrp_assign:2198: new version barrier v8
 13:41:56,871 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPJOINSTATE,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" changed join state started -> wait-unassign (v8, state up)
 13:41:56,872 [18]  - OnLog Message : rdkafka#consumer-1,7,CGRPJOINSTATE,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443" changed join state started -> wait-unassign (v8, state up)
 13:41:56,873 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": rd_kafka_cgrp_unassign:2114: new version barrier v9
 13:41:56,874 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": rd_kafka_cgrp_unassign:2114: new version barrier v9
 13:41:56,875 [18]  - OnLog Message : rdkafka#consumer-1,7,UNASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": unassigning 1 partition(s) (v9)
 13:41:56,875 [18]  - OnLog Message : rdkafka#consumer-1,7,UNASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": unassigning 1 partition(s) (v9)
 13:41:56,876 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: TestTopic [0]: rd_kafka_toppar_op_fetch_stop:2039: new version barrier v6
 13:41:56,877 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: TestTopic [0]: rd_kafka_toppar_op_fetch_stop:2039: new version barrier v6
 13:41:56,878 [18]  - OnLog Message : rdkafka#consumer-1,7,CONSUMER,[thrd:main]: Stop consuming TestTopic [0] (v6)
 13:41:56,879 [18]  - OnLog Message : rdkafka#consumer-1,7,CONSUMER,[thrd:main]: Stop consuming TestTopic [0] (v6)
 13:41:56,879 [18]  - OnLog Message : rdkafka#consumer-1,7,DESP,[thrd:main]: Removing (un)desired topic TestTopic [0]
 13:41:56,880 [18]  - OnLog Message : rdkafka#consumer-1,7,DESP,[thrd:main]: Removing (un)desired topic TestTopic [0]
 13:41:56,881 [18]  - OnLog Message : rdkafka#consumer-1,7,RESUME,[thrd:main]: Library resuming 1 partition(s)
 13:41:56,883 [18]  - OnLog Message : rdkafka#consumer-1,7,RESUME,[thrd:main]: Library resuming 1 partition(s)
 13:41:56,884 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: TestTopic [0]: rd_kafka_toppar_op_pause_resume:2097: new version barrier v7
 13:41:56,886 [18]  - OnLog Message : rdkafka#consumer-1,7,BARRIER,[thrd:main]: TestTopic [0]: rd_kafka_toppar_op_pause_resume:2097: new version barrier v7
 13:41:56,886 [18]  - OnLog Message : rdkafka#consumer-1,7,RESUME,[thrd:main]: Resume TestTopic [0] (v7)
 13:41:56,887 [18]  - OnLog Message : rdkafka#consumer-1,7,RESUME,[thrd:main]: Resume TestTopic [0] (v7)
 13:41:56,888 [18]  - OnLog Message : rdkafka#consumer-1,7,UNASSIGN,[thrd:main]: Unassign not done yet (1 wait_unassign, 1 assigned, 0 wait commit): unassign
 13:41:56,889 [18]  - OnLog Message : rdkafka#consumer-1,7,UNASSIGN,[thrd:main]: Unassign not done yet (1 wait_unassign, 1 assigned, 0 wait commit): unassign
 13:41:56,890 [18]  - OnLog Message : rdkafka#consumer-1,7,ASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": assigning 0 partition(s) in join state wait-unassign
 13:41:56,890 [18]  - OnLog Message : rdkafka#consumer-1,7,ASSIGN,[thrd:main]: Group "4b756696-e53d-43c1-bb81-be958e626443": assigning 0 partition(s) in join state wait-unassign
 13:41:56,891 [18]  - OnLog Message : rdkafka#consumer-1,7,OP,[thrd:main]: TestTopic [0] received op FETCH_STOP (v6) in fetch-state active (opv5)
 13:41:56,891 [9]  - Consumed 8 in 1s
 13:41:56,892 [18]  - OnLog Message : rdkafka#consumer-1,7,OP,[thrd:main]: TestTopic [0] received op FETCH_STOP (v6) in fetch-state active (opv5)
 13:41:56,892 [9]  - 7 messages/s
 13:41:56,893 [18]  - OnLog Message : rdkafka#consumer-1,7,FETCH,[thrd:main]: Stopping fetch for TestTopic [0] in state active (v6)
 13:41:56,893 [9]  - Recovery Consumer Task Ended...

**Comment by chiru1205** [comment]
@edenhill This is what I see for two runs

**Comment by mhowlett** [comment]
I notice a problem with the initial code snippet - `OnPartitionsAssigned` is defined but `OnPartitionsRevoked`/`Unassign` isn't, and in 0.11.x versions you must specify neither or both. This constraint doesn't apply to 1.0.x versions.

I'm closing this issue since it's very old and I think it's unlikely it relates to a real problem in current releases. Please re-open another issue if the problem persists.
