### ISSUE TITLE
Native lib no longer being loaded in 11.3

### ISSUE THREAD

**Issue by slafave** [confluentinc/confluent-kafka-dotnet#390]
Updated my project from 11.2 to 11.3.  Native lib no longer being loaded.  Null reference exception being thrown.  Confluent.Kafka.Library.IsLoaded is false.

If I load up the Confluent.Kafka solution from this repo, I get the same error running any of the examples.

The error goes away and Confluent.Kafka.Library.VersionString returns "0.11.1" in my project if I revert to the 11.2 package.  The error goes away in the Confluent.Kafka solution from this repo if I cut a branch from the 0.11.2 tag and run the examples.

I can see the 11.3 librdkafka.redist in my local NuGet cache.  It looks a bit different from 11.1.  The "lib" files are missing from the win7-x64\native directory, compared to the 11.1 librdkafka.redist NuGet cache dir.

My Workstation:
- Win 10 1709 (Fall Creator's update)
- VS 2017 15.5
- .Net Core 2.0.3

**Comment by mhowlett** [comment]
the .lib files are static libraries and not needed - they've been removed to make the nuget package smaller.

Can you try referencing Confluent.Kafka version 0.11.3-RC1-ci-170 (hidden on nuget.org) - I tested this under a scenario very similar to what you outline (and 0.11.3 shouldn't be any different). 

I will try to replicate/investigate in a few hours. We've made some big changes to all this.

**Comment by slafave** [comment]
Same issue under Confluent.Kafka 0.11.3-RC1-ci-170

**Comment by slafave** [comment]
If I try to direct load it with Confluent.Kafka.Library.Load(@"<mypath>") I get "Failed to load librdkafka at location '<mypath>'. Win32 error: 126".  I verified I have full permissions to <mypath>.

**Comment by mhowlett** [comment]
this suggests to me that one of librdkafka's dependencies can't be loaded (which would also explain why it works on my system and not yours). @edenhill - have any of the dependencies changed since 0.11.1? 

You could try installing c++ redistributables from VS 2013 and VS 2015 (I have these installed, so my first guess is this).

If that doesn't help, feel free to have a look at the difference between librdkafka.redist 0.11.1 and 0.11.3 in dependency walker http://www.dependencywalker.com/

I'll wait for @edenhill to comment before investigating further.

we'll need to fix this.

**Comment by edenhill** [comment]
@mhowlett There should be no change how the librdkafka.redist libraries are built, the only thing that differs is your layout changes to the package.

**Comment by mhowlett** [comment]
@slafave - it would also be good to know if 0.11.3 works with .NET Framework or .NET Core 1.1 / 1.0 on your machine. I don't see how this would be a factor in your problem, but maybe there is something I don't understand.

If there is anyone else out there hitting this problem, please chime in so we can get an idea of how widespread it is.

**Comment by slafave** [comment]
I have VS 2013 and VS 2015 installed as well, so I have those c++ redistributables.

I'll go thru dependency walker, try a couple of different simple solution configurations, Framework and Core combinations.

**Comment by slafave** [comment]
I updated my VS2017 instance to 15.5 on 12/4.  That update installed new versions of all C++ redistributables.  It also looks like it uninstalled all the 2015 C++ redistributable, for some odd reason.  Let me install the latest 2015 C++ redis and see if it helps.

**Comment by slafave** [comment]
I can't reinstall the 2015 C++ redistributables, they are considered a downgrade of the latest 2017 ones.
2017 version -> 14.10.25008
2015 version -> 14.0.24212

I verified in a simple console project that I cannot load the native 11.3 DLL in Framework, Core 1.0, 1.1, or 2.0.  The 11.1 native DLL works fine in all.

In dependency walker, both 11.1 and 11.3 display the same errors of not finding some dependencies.

Are you able to update VS2017 to 15.5 and see if that is a repro?  That and the update of Win10 from 1703 (Creators) to 1709 (Fall Creators) are the "only" things that changed on my machine in the last 2 days.  I will see if I can find someone with Win10 1703 and VS2017 15.4.x and see if their machine can load 11.3.

**Comment by edenhill** [comment]
The only difference I see between librdkafka.redist 0.11.1 and 0.11.3 is that the librdkafka*.lib files were removed from runtimes/, not sure if that's the issue or not, it should not rely on those.

@mhowlett any ideas?

@slafave You could try manually copying librdkafka.lib from build/native... to the appropriate runtimes folders

```
maglun@eden:~/src/librdkafka/packaging/nuget (0.11.x)$ unzip -l ~/Hämtningar/*0.11.1.nupkg | grep win7-x64
    39848  2017-10-17 22:00   build/native/lib/win7/x64/win7-x64-Release/v120/librdkafka.lib
    39098  2017-10-17 22:00   build/native/lib/win7/x64/win7-x64-Release/v120/librdkafkacpp.lib
  2598912  2017-10-17 22:01   runtimes/win7-x64/native/librdkafka.dll
    39848  2017-10-17 22:01   runtimes/win7-x64/native/librdkafka.lib
    74752  2017-10-17 22:01   runtimes/win7-x64/native/librdkafkacpp.dll
    39098  2017-10-17 22:01   runtimes/win7-x64/native/librdkafkacpp.lib
   963232  2017-10-17 22:01   runtimes/win7-x64/native/msvcr120.dll
    77824  2017-10-17 22:01   runtimes/win7-x64/native/zlib.dll
maglun@eden:~/src/librdkafka/packaging/nuget (0.11.x)$ unzip -l *0.11.3.nupkg | grep win7-x64
    39848  2017-12-04 12:52   build/native/lib/win7/x64/win7-x64-Release/v120/librdkafka.lib
    39098  2017-12-04 12:52   build/native/lib/win7/x64/win7-x64-Release/v120/librdkafkacpp.lib
  2604032  2017-12-04 12:52   runtimes/win7-x64/native/librdkafka.dll
    74752  2017-12-04 12:52   runtimes/win7-x64/native/librdkafkacpp.dll
   963232  2017-12-04 12:52   runtimes/win7-x64/native/msvcr120.dll
    77824  2017-12-04 12:52   runtimes/win7-x64/native/zlib.dll
```

**Comment by lakario** [comment]
Tested on two systems using LINQPad as my .NET environment. Exception produced shows that the latest version of the Confluent.Kafka package is trying to read librdkafka.dll from a path which does not exist:
  
 C:\Users\user\AppData\Local\LINQPad\NuGet.FW46\Confluent.Kafka\Confluent.Kafka.0.11.3\lib\net46\runtimes\win7-x86\native\librdkafka.dll

**Comment by mhowlett** [comment]
@slafave - can you double check this is definitely correct:

> If I try to direct load it with Confluent.Kafka.Library.Load(@"<mypath>") I get "Failed to load librdkafka at location '<mypath>'. Win32 error: 126". I verified I have full permissions to <mypath>.

note that the dependencies contained in the nuget package (msvcr120.dll and zlib.dll) must be in the same location as librdkafka.dll, if they are not you would see the above.

@lakario - thanks for the input, this would appear to be another issue. I'm guessing this is related to moving `librdkafka.redist.props` in the nuget package (which stops warning message(s) during restore related to not knowing what the target framework is). Another fix for that problem would be to include a dummy managed .dll in `librdkafka.redist`, I'm thinking we'll likely do that.

@edenhill - the .lib files are not needed.

**Comment by slafave** [comment]
@edenhill adding the lib files did not help

@mhowlett I verified all files from the NuGet are in the directory I tried to load from

**Comment by slafave** [comment]
@mhowlett Could it be something with your updated loader code?  When I point the new Confluent.Kafka.Library.Load method to the v11.1 lib path, I get the same exception with Win32 error: 126 that I get when I point to the 11.3 lib path.

**Comment by mhowlett** [comment]
@slafave - good data point, i'll look at that.

**Comment by slafave** [comment]
@mhowlett Gotta be the updated loader code -> when I replace the 11.1 native binaries with 11.3 native binaries in my NuGet cache, the 11.2 version of Confluent.Kafka.dll loads the 11.3 native DLL. Confluent.Kafka.Library.VersionString displays "0.11.3" in the 11.2 Confluent.Kafka.dll.

**Comment by mhowlett** [comment]
Another data point: I just tried to replicate on a fresh AWS instance.

Windows_Server-2016-English-Full-Base-2017.11.29 (ami-f6d8008e)
VS 2017 15.5
.Net Core 2.0.3

librdkafka is loading fine without an explicit `Library.Load` call, and also loads fine when specifying an absolute path to `Library.Load` (the load mechanism is different in each case).

**Comment by mhowlett** [comment]
@slafave - can you paste the exception trace mentioned below? Also, I assume this is when you're not attempting to load the library manually? 

> Updated my project from 11.2 to 11.3. Native lib no longer being loaded. Null reference exception being thrown.

**Comment by slafave** [comment]
Correct, this exception is not when I'm attempting to load the library manually.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Confluent.Kafka
  StackTrace:
   at Confluent.Kafka.Impl.LibRdKafka.version()
   at Confluent.Kafka.Library.get_Version()
   at Framework.Program.Main(String[] args) in C:\Code\TestKafkaNet\Framework\Program.cs:line 13

```

**Comment by mhowlett** [comment]
Did you attempt `Library.Load()` without any arguments before calling `Library.Version`? (this is necessary - only the producer and consumer constructors auto-call this). Maybe we should auto load on `Library.Version` as well, come to think of it..

**Comment by mhowlett** [comment]
i mean loading the library in some way (`Library.Load` with or without path to librdkafka).

**Comment by slafave** [comment]
That worked!

Is that new behavior?  I've always called Confluent.Kafka.Library.Version as one of the first lines in my service, so I can verify which native lib is loaded.  No producers or consumers have been instantiated at that point.  So that call worked in < 11.3. :)

Also, the version string I get is "721919" instead of the expected "0.11.3" -> is that new behavior?  What does "721919" refer to?

**Comment by mhowlett** [comment]
The string should be 0.11.3 - you would be printing `Library.Version` not `Library.VersionString`.
Yes, this is new behavior. Previously there was no capability to manually load the librdkakfa. `Library.Load` is new. It's auto-called in producers and consumer constructors only, not in the call to `Library.Version`

My learning from this thread is that `Library.Version` should auto-call `Library.Load()` otherwise people are going to get confused :-)

**Comment by slafave** [comment]
Sorry for the rabbit-chase, didn't occur to me to try that.  

I see VersionString is what I meant and it does indeed return "0.11.3" as expected.

Thanks for the assistance!

**Comment by mhowlett** [comment]
this still leaves the issue you're having specifying the absolute path to librdkafka unresolved. My best guess is you're doing something wrong (I've tested this in a few environments), but the loading mechanism is a different in this case, so there may be a real issue. I'll wait for more complaints before investigating this further.

**Comment by slafave** [comment]
Does the absolute path need to include the library as well?  The documentation makes it sound like just the path itself is fine.

I was doing this - "C:\Users\slafave\.nuget\packages\librdkafka.redist\0.11.1\runtimes\win7-x64\native"

Did I need to do this? "C:\Users\slafave\.nuget\packages\librdkafka.redist\0.11.1\runtimes\win7-x64\native\librdkafka.dll"

**Comment by mhowlett** [comment]
yes. cool, looks like another misunderstanding. I'll update the docs to make that clear. 

thanks for the feedback. This may seem like a rabbit-chase, but I think both things will commonly confuse people, so I'll fix them up.

**Comment by mhowlett** [comment]
@lakario - I'm unable to test this because it looks like I need a LINQPad license to reference the Confluent.Kafka nuget package. The way un-managed packages work in the .NET Framework case is not as good as .NET Core, and I suspect you're running into an issue we won't ever resolve (maybe not, though likely). 

The `Library.Load` method was added for such situations. Specify the path (including filename) to your librdkafka.dll using this before using the library and it should work.
