### ISSUE TITLE
ProduceAsync takes about 1000ms

### ISSUE THREAD

**Issue by jbezak** [confluentinc/confluent-kafka-dotnet#391]
Description
===========
After changing our library to Confluent.Kafka we noticed significant performance downgrade when producing messages to kafka. After some research we found out that setting `socket.blocking.max.ms = 1` solves the issue but it is marked deprecated in [librdkafka configuration](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)

Is there another known way how to fix the latency? 

 - [ ] Confluent.Kafka nuget version: 0.11.3
 - [ ] Apache Kafka version: 0.10.0.2.5
 - [ ] Client configuration: acks = all
 - [ ] Operating system: Windows

**Comment by edenhill** [comment]
It is not deprecated on Windows, see:
https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency
