### ISSUE TITLE
Seek api behavior differs from native Java Consumer APIs Seek?

### ISSUE THREAD

**Issue by rajayaad** [confluentinc/confluent-kafka-dotnet#394]
I had been waiting for a month for Seek api to be added(https://github.com/confluentinc/confluent-kafka-dotnet/issues/290). 
But with reference to documentation of Seek api at :
https://github.com/confluentinc/confluent-kafka-dotnet/blob/45790d9af1fea47555f58ff611c103388a2d2d92/src/Confluent.Kafka/include_docs.xml#L101

as well as what I am observing from testing, calling Seek when partitions are auto-assigned via Subscribe api, throws exception. It works correctly when called after doing manual Assign. 

So, we are left in an either or scenario. We can either get auto-rebalancing(which pretty much covers high-availability) with kafka committed offset or fixed partition allocation with seek to custom offset.
But not both. As per https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html , auto-rebalancing with Seek seems to be a pretty good paradigm when offsets are externally committed with consumed messages, and still deriving benefits of Kafka's auto-rebalancing.

So, was there a particular reason why dotnet's(librdkafka?) Seek implementation differs? And will this difference go away in near future?
Thanks.

**Comment by mhowlett** [comment]
Assigning manually and the assign done after a subscription assignment are the same thing. I'm not completely familiar with how seek in librdkafka works. perhaps there is a problem related to specifying an offset of -1 in the assign call (which is what happens whilst subscribing). you could override the `OnPartitionsAssigned` method and try `Assign`ing in there with a specific offset that is not -1. If this is the problem, this behavior does seems not ideal from a usability perspective to me.

**Comment by edenhill** [comment]
@rajayaad 
Seek() may only be called for Assign():ed partitions, its main use is to seek/skip during consumption, for the case where you want to start consuming at a certain position you would use the TopicPartitionOffset-variant of Assign().

Due to implementation differences between the (originally) single threaded Java consumer and the multi-threaded librdkafka consumer there was a need in librdkafka to synchronize state between the application and internal consumer when the rebalance callback/OnPartitionsAssigned|Revoked is called to know if the application wanted to modify the assigned partitions, or their offsets, prior to starting consumption.

This does not necessarily make it more complex for the application to use, it is just that the APIs are a bit different. Looking at the Java example in the link you provided, all we need to do in a librdkafka-based application is modify the assigned partitions list by specifying an alternate start offset for each partition and then calling Assign().
@mhowlett can you provide an exact .NET-representation of the Java example above as a reference implementation?


nit: offset -1 means OFFSET_END, you probably mean OFFSET_INVALID (-1001) which is the default offset to use (first check for committed offset, then faill back to auto.offset.reset).

**Comment by rajayaad** [comment]
Thanks @mhowlett , @edenhill , for quick response.
So, both of you are suggesting that I use "Subscribe" api, and when OnPartitionsAssigned is invoked, I call "Assign" (on same partition that has already been allocated to current instance) with custom offset.

I started trying that. So, on OnPartitionsAssigned, say current instance gets assigned 4 partitions, i get offsets for each of 4 from my db, and call Assign, passing 4 TopicPartitionOffset s. 
With preliminary testing, it didnt throw any exceptions, and seems to be working. For now, I have data only on one partition, and I got message correctly from that partition. I will setup proper test tomorrow, where data is published to all 4 partitions. 

Also, more importantly, another test will be to bring up another instance, so that OnPartitionsRevoked gets called on first instance and it loses, say 2, partitions and OnPartitionsAssigned gets called on second instance and those 2 partitions get assigned to it. This seems important to test, because, atleast according to documentation of "Subscribe" and "Assign" in Java Consumer APIs(https://kafka.apache.org/0101/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#subscribe(java.util.Collection)), its pretty explicitly stated that these two apis cannot be combined together. Which makes sense. So I am surprised librdkafka is allowing simultaneous use.

I will test and update you guys here. Thanks again.

**Comment by edenhill** [comment]
> its pretty explicitly stated that these two apis cannot be combined together. Which makes sense. So I am surprised librdkafka is allowing simultaneous use.

librdkafka is a tad more flexible when it comes to the actual assignment by allowing the assignment to be modified before applying it.
One emerging use-case is to use a balanced consumer group with a set of topics that are balanced across the consumer, but also adding a common topic+partition that all consumers in the group consumes. The assign() call from within OnPartitionsAssigned allows you to do this.

**Comment by rajayaad** [comment]
Alright, both tests succeeded, i.e. with calling Assign inside OnPartitionsAssigned :
1) Single Instance : No adverse affects. I was able to read from all assigned partitions.
2) More importantly, with multiple instances, Kafka's auto-rebalancing still works. So in that way, it does seem to differ from Java api's documentation.

Note: Its very important to call "Unassign" at end of OnPartitionsRevoked. This is what I am observing with 4 partition setup if "Unassign" is **not** called at end of OnPartitionsRevoked;

Action Sequence # | Action | Events
----------------- | ------ | -----
1| Start Instance_1 | Instance_1.OnPartitionsAssigned invoked with all 4 partitions
2| Start Instance_2 | 1) Instance_1.OnPartitionsRevoked invoked with all 4 partitions 2) Instance_2.OnPartitionsAssigned invoked _**with all 4**_ partitions
3| Stop Instance_2 | Instance_1.OnPartitionsAssigned _**is not**_ invoked

So, note above that, when Instance 2 came up, Instance 1 ended up with 0 partitions instead of 2. And moreover, even if instance 2 goes down, Instance 1 never gets those partitions back. No one is listening on those partitions even though one instance is up.

If we do call  "Unassign" at end of OnPartitionsRevoked, things seem to work correctly:

Action Sequence # | Action | Events
----------------- | ------ | -----
1| Start Instance_1 | Instance_1.OnPartitionsAssigned invoked with all 4 partitions
2| Start Instance_2 | 1) Instance_1.OnPartitionsRevoked invoked with all 4 partitions 2) Instance_1.OnPartitionsAssigned invoked with 2 partitions 3) Instance_2.OnPartitionsAssigned invoked with 2 partitions
3| Stop Instance_2 | 1) Instance_2.OnPartitionsRevoked invoked with 2 partitions 2) Instance_1 OnPartitionsRevoked invoked with 2 partitions 3) Instance_1.OnPartitionsAssigned invoked with 4 partitions

So, not sure why Unassign is playing such significant role. And since it seems mandatory for correct functioning, can it be moved to inside library?

**Comment by mhowlett** [comment]
librdkafka has only a 'rebalance' callback. This is split out into two events in the C# client.

Specifying either `OnPartitionsAssigned` or `OnPartitionsRevoked` will cause this rebalance callback to be provided to librdkafka and thus stop `Assign` being automatically applied inside librdkafka.

thanks for the details feedback, this is un-intuitive enough behavior that i'm going to label it as a bug. In a hurry, so labelling this issue, though I should create another issue.

**Comment by mhowlett** [comment]
just looked at this again. my previous comment is incorrect (as noted, I was in a hurry...).

if you add a handler to an `OnPartitionsRevoked` event, you must call `Unassign` in it. If you don't add a handler, `Unassign` will be called automatically for you. i don't like this API, but I can't think of anything better that exposes the full functionality librdkafka provides. needs documenting.

**Comment by edenhill** [comment]
The librdkafka<->application contract is for the application to call assign() from OnPartitionsAssigned and unassign() from OnPartitionsRevoked, this is required to synchronize internal state.
That is, however, in C and C++.

The high-level language bindings can be more forgiving;
what the Python and Golang clients do is check if assign() and unassign() has been called from the delegate, and if not performs the call for the user:
https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/src/Consumer.c#L1101
and
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/event.go#L134

**Comment by mhowlett** [comment]
tracking action items out of this issue in #592, #593.
