### ISSUE TITLE
Unable to produce messages using SSL from windows machine

### ISSUE THREAD

**Issue by nagarjuna119** [confluentinc/confluent-kafka-dotnet#398]
Below is sample I am trying to use, after a long wait I get invalid partition. changing the port to non SSL port and removing ssl config's works fine. Nonwindows and non .net clients are working fine 

How to reproduce
================
 static void Main(string[] args)
{
    string brokerList = "kafka.test.test.net:9093";
    string topicName = "testtopic";

    var config = new Dictionary<string, object>
    {
        {"bootstrap.servers", brokerList},
        {"client.id", Dns.GetHostName()},
        {"security.protocol", "SSL"},
        {"ssl.ca.location", @"C:\certs\windows\ca-cert"}
    };

    using (
        var producer = new Producer<string, string>(config, new StringSerializer(Encoding.UTF8),
            new StringSerializer(Encoding.UTF8)))
    {
        Console.WriteLine("\n-----------------------------------------------------------------------");
        Console.WriteLine($"Producer {producer.Name} producing on topic {topicName}.");
        Console.WriteLine("-----------------------------------------------------------------------");

        var deliveryReport = producer.ProduceAsync(topicName, "", "Test Message");

        try
        {
            var result = deliveryReport.Result; // synchronously waits for message to be produced.
            Console.WriteLine($"Partition: {result.Partition}, Offset: {result.Offset}");

        }
        catch (Exception)
        {
            throw;
        }
    }
}

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 11.3
 - [ ] Apache Kafka version: 2.11-0.11.0.1
 - [ ] Client configuration: sample above
 - [ ] Operating system: Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Enable the `{"debug", "security,broker"}` configuration property to see what is going on

**Comment by nagarjuna119** [comment]
Below are the logs with debug, any ideas what could be wrong..?

7|2017-12-17 21:23:02.210|rdkafka#producer-1|SSL| [thrd:app]: Loading CA certificate(s) from file C:\certs\CARoot.pem
7|2017-12-17 21:23:02.210|rdkafka#producer-1|BROKER| [thrd:app]: ssl://kafka.nonprod.xxx.net:9093/bootstrap: Added new broker with NodeId -1
7|2017-12-17 21:23:02.210|rdkafka#producer-1|BRKMAIN| [thrd::0/internal]: :0/internal: Enter main broker thread
7|2017-12-17 21:23:02.210|rdkafka#producer-1|STATE| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
7|2017-12-17 21:23:02.210|rdkafka#producer-1|BRKMAIN| [thrd:ssl://kafka.nonprod.xxx.net:9093/bootstrap]: ssl://kafka.nonprod.xxxx.net:9093/bootstrap: Enter main broker thread
7|2017-12-17 21:23:02.210|rdkafka#producer-1|CONNECT| [thrd:ssl://kafka.nonprod.xxx.net:9093/bootstrap]: ssl://kafka.nonprod.xxxx.net:9093/bootstrap: broker in state INIT connecting

-----------------------------------------------------------------------
Producer rdkafka#producer-1 producing on topic nord_epm_export_ssl.
-----------------------------------------------------------------------
7|2017-12-17 21:23:02.442|rdkafka#producer-1|CONNECT| [thrd:ssl://kafka.nonprod.xxx.net:9093/bootstrap]: ssl://kafka.nonprod.xxxx.net:9093/bootstrap: Connecting to ipv4#172.19.67.166:9093 (ssl) with socket 1184

7|2017-12-17 09:14:45.321|rdkafka#producer-1|STATE| [thrd:ssl://kafka.nonprod.xxx.net:9093/bootstrap]: ssl://kafka.nonprod.xxx.net:9093/bootstrap: Broker changed state INIT -> CONNECT
7|2017-12-17 09:14:45.398|rdkafka#producer-1|CONNECT| [thrd:ssl://kafka.nonprod.xxx.net:9093/bootstrap]: ssl://kafka.nonprod.xxx.net:9093/bootstrap: Connected to ipv4#172.19.67.166:9093
7|2017-12-17 09:14:45.658|rdkafka#producer-1|BROKERFAIL| [thrd:ssl://kafka.nonprod.xxx.net:9093/bootstrap]: ssl://kafka.nonprod.xxx.net:9093/bootstrap: failed: err: Local: SSL error: (errno: No error)

**Comment by msdotnetclr** [comment]
Your code says "{"ssl.ca.location", @"C:\certs\windows\ca-cert"}" while the log says "Loading CA certificate(s) from file C:\certs\CARoot.pem". Inconsistency?

**Comment by mhowlett** [comment]
these notes might help: https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security

also maybe try setting `debug` to all - i'm not getting much out of those log messages. 

closing because this is very old. if the above doesn't help, feel free to re-open.

**Comment by mfkashani** [comment]
I am running into the same situation and the link provided is no longer valid.
[https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security](url)
