### ISSUE TITLE
Please consider to abstract a rawer Consumer/Producer class

### ISSUE THREAD

**Issue by csyszf** [confluentinc/confluent-kafka-dotnet#402]
Hi,

I've noticed that:

> [UNSTABLE-API] We are considering making this class private in a future version so as to limit API surface area. Prefer to use the deserializing consumer Consumer<TKey, TValue> where possible.

but in many of my cases, I need to manually consume/deserializ messages (to adapt existing framework),
so I hope that there could be two or more public Consumer/Producer class——
1. a base Consumer/Producer，more free, more plain, just wrap the librdkafka.
2. Consumer<TKey, TValue> as high-level Consumer/Producer with advaced method like Poll().

Is this reasonable?

**Comment by mhowlett** [comment]
@csyszf - the non-deserializing `Consumer` is definitely being removed in 1.0. However you can just use the output from `ByteArrayDeserializer` or write your own custom deserializer (which can access the `ReadOnlySpan<byte>` data directly).
