### ISSUE TITLE
ProduceAsync returns a task which never completes

### ISSUE THREAD

**Issue by badyam** [confluentinc/confluent-kafka-dotnet#406]
Description
===========
When Producer constructed with disableDeliveryReports = true option,
then ProduceAsync returns a task which never completes.
That may lead to a blocking of code execution and, potentially, to memory leaks.
This behavior is mentioned in docs on disableDeliveryReports parameter in Producer's constructor:

> If true, disables delivery report notification. Note: if set to true and you use a ProduceAsync variant that returns  a Task, the Tasks will never complete. Typically you should set this parameter to false. Set it to true for "fire and forget" semantics and a small boost in performance.

Despite of the fact this behavior is being described in docs, it seems weird. 
What is the reasoning behind returning a never-completed task?

I believe **in case of disabled delivery reports ProduceAsync should return completed task**.
Result of completed task should be a Message which has -1 in Partition and Offset properties  and null in Error, because these properties cannot be assigned with actual values without delivery report. Other properties of message can be actual.

Such behavior makes client code, that utilizes this method, a way more consistent and robust and prevents thread blocking and memory leaks.
Besides, such approach doesn't break an existing client code and doesn't violate "fire-and-forget" pattern.

As for impact of returning a completed task to performance, it seems to be inconsiderable.

To support my opinion I'm referencing to Stephen Toub's blog post.
https://blogs.msdn.microsoft.com/pfxteam/2011/10/02/dont-forget-to-complete-your-tasks/

How to reproduce
================
```
var producer = new Producer(new Dictionary<string, object> {{ "bootstrap.servers", "localhost:9092" }}, false, true);
var key = new byte[] { 16 };
var value = new byte[] { 42 };
var task = producer.ProduceAsync("test-topic", key, value);
var sentMessage = task.GetAwaiter().GetResult();
Console.WriteLine("Message sent");
```
"Message sent" wont be printed until program is forcibly terminated.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [x] Apache Kafka version: 0.10.1.0
 - [ ] Client configuration:
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks @badyam - completely agree. this should be a quick win - feel free to submit a PR :-) or I will get to implementing it myself at some point.

**Comment by badyam** [comment]
Thanks! I'll take care on a PR.

**Comment by mhowlett** [comment]
just added this feature/fix to the 1.0-experimental branch. It'll be in the next package based on this branch (probably 1.0-experimental-7).

**Comment by notlikethis1** [comment]
I had the same issue when producing from a controller on a server when DeliveryReportFields was ste to "all". Changed it to "key" and it worked.
This problem wasn't seen debugging on a local development laptop.

This is what we did to find the issue;

In producer.cs we added some debug lines using logHandler?.Invoke...

`private void DeliveryReportCallbackImpl(IntPtr rk, IntPtr rkmessage, IntPtr opaque)
        {
            logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl started"));
            // Ensure registered handlers are never called as a side-effect of Dispose/Finalize (prevents deadlocks in common scenarios).
            if (ownedKafkaHandle.IsClosed) { return; }

            logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 1"));


            var msg = Util.Marshal.PtrToStructure<rd_kafka_message>(rkmessage);

            // the msg._private property has dual purpose. Here, it is an opaque pointer set
            // by Topic.Produce to be an IDeliveryHandler. When Consuming, it's for internal
            // use (hence the name).
            if (msg._private == IntPtr.Zero)
            {
                // Note: this can occur if the ProduceAsync overload that accepts a DeliveryHandler
                // was used and the delivery handler was set to null.
                return;
            }

            logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 2"));

            var gch = GCHandle.FromIntPtr(msg._private);
            var deliveryHandler = (IDeliveryHandler) gch.Target;
            gch.Free();

            logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 2.a"));

            Headers headers = null;
            if (this.enableDeliveryReportHeaders) 
            {
                logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 2.b"));
                headers = new Headers();
                Librdkafka.message_headers(rkmessage, out IntPtr hdrsPtr);
                if (hdrsPtr != IntPtr.Zero)
                {
                    logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 2.c"));
                    for (var i=0; ; ++i)
                    {
                        logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 2.d"));
                        var err = Librdkafka.header_get_all(hdrsPtr, (IntPtr)i, out IntPtr namep, out IntPtr valuep, out IntPtr sizep);
                        logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", $"DeliveryReportCallbackImpl 2.e err: {err}"));
                        if (err != ErrorCode.NoError)
                        {
                            break;
                        }
                        var headerName = Util.Marshal.PtrToStringUTF8(namep);
                        byte[] headerValue = null;
                        if (valuep != IntPtr.Zero)
                        {
                            headerValue = new byte[(int)sizep];
                            Marshal.Copy(valuep, headerValue, 0, (int)sizep);
                        }
                        headers.Add(headerName, headerValue);
                    }
                }
            }

            logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 2.f"));

            IntPtr timestampType = (IntPtr)TimestampType.NotAvailable;
            long timestamp = 0;
            if (enableDeliveryReportTimestamp)
            {
                timestamp = Librdkafka.message_timestamp(rkmessage, out timestampType);
            }

//log lines stop after this ->

            logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 2.g"));

//log lines stop after this ->

            PersistenceStatus messageStatus = PersistenceStatus.PossiblyPersisted;
            if (enableDeliveryReportPersistedStatus)
            {
                messageStatus = Librdkafka.message_status(rkmessage);
            }

            logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl 3"));

            deliveryHandler.HandleDeliveryReport(
                new DeliveryReport<Null, Null>
                {
                    // Topic is not set here in order to avoid the marshalling cost.
                    // Instead, the delivery handler is expected to cache the topic string.
                    Partition = msg.partition, 
                    Offset = msg.offset, 
                    Error = KafkaHandle.CreatePossiblyFatalError(msg.err, null),
                    Status = messageStatus,
                    Message = new Message<Null, Null> { Timestamp = new Timestamp(timestamp, (TimestampType)timestampType), Headers = headers }
                }
            );

            logHandler?.Invoke(new LogMessage("SUPER HACK", SyslogLevel.Critical, "JORIS", "DeliveryReportCallbackImpl klaar"));
        }`

After 2.g nothing is logged which is where the request dies.

2019-06-21 13:41:35,992 [116] DEBUG OurController - Sending 1 thing to Kafka for someid
2019-06-21 13:41:38,320 [173] DEBUG OurKafkaProducer - [librdkafka/PRODUCE]: [thrd:ssl://some-url.com:6668/bootst]: ssl://some-url.com:6668/1002: topicname [1]: Produce MessageSet with 1 message(s) (218 bytes, ApiVersion 3, MsgVersion 2)

2019-06-21 13:41:38,320 [173] DEBUG OurKafkaProducer - [librdkafka/MSGSET]: [thrd:ssl://some-url.com:6668/bootst]: ssl://some-url.com:6668/1002: topicname [1]: MessageSet with 1 message(s) delivered
2019-06-21 13:41:38,320 [172] DEBUG OurKafkaProducer - [librdkafka/JORIS]: DeliveryReportCallbackImpl started
2019-06-21 13:41:38,320 [172] DEBUG OurKafkaProducer - [librdkafka/JORIS]: DeliveryReportCallbackImpl 1
2019-06-21 13:41:38,320 [172] DEBUG OurKafkaProducer - [librdkafka/JORIS]: DeliveryReportCallbackImpl 2
2019-06-21 13:41:38,320 [172] DEBUG OurKafkaProducer - [librdkafka/JORIS]: DeliveryReportCallbackImpl 2.a
2019-06-21 13:41:38,320 [172] DEBUG OurKafkaProducer - [librdkafka/JORIS]: DeliveryReportCallbackImpl 2.b
2019-06-21 13:41:38,320 [172] DEBUG OurKafkaProducer - [librdkafka/JORIS]: DeliveryReportCallbackImpl 2.f
2019-06-21 13:41:38,320 [172] DEBUG OurKafkaProducer - [librdkafka/JORIS]: DeliveryReportCallbackImpl 2.g

(line 3 should be here)

After changing the delivery report fields from default "all" to "key" it does work.

**Comment by jorisvergeer** [comment]
@mhowlett @notlikethis1 
To clearify: 

The execution stops somewhere in these lines:
```csharp
        PersistenceStatus messageStatus = PersistenceStatus.PossiblyPersisted;
        if (enableDeliveryReportPersistedStatus)
        {
            messageStatus = Librdkafka.message_status(rkmessage);
        }
```
