### ISSUE TITLE
Is it possible to set per-topic config variables?

### ISSUE THREAD

**Issue by alinmotogna** [confluentinc/confluent-kafka-dotnet#408]
Description
===========
Found this discussion on the go library https://github.com/confluentinc/confluent-kafka-go/issues/20

My use case is that I'm using a generic subscriber wrapper class to consume from several topics, and some of them I only need to read from latest offset, while others need to subscribe from the begining 

Checklist
=========
Please provide the following information:
 - [ 0.11.3] Confluent.Kafka nuget version:

**Comment by edenhill** [comment]
You can control the starting offset in your OnPartitionsAssigned delegate by calling Assign() with specific offsets to start consumption (default is use committed offset, fall back on auto.offset.reset)

**Comment by mhowlett** [comment]
Also note that you can use `Offset.Beginning` and `Offset.End` in the `Assign` call.

Per-topic configuration is not possible with the .net client (and rarely needed). e.g. you can't specify `auto.offset.reset` on a per-topic basis (behaviour if there is no committed offset). But I think that is not what you need.

**Comment by alinmotogna** [comment]
Sorry for this late reply (especially considering the awesome reply time from your side :-|)
Suggested solution works fine
