### ISSUE TITLE
Multiple topics synchronization

### ISSUE THREAD

**Issue by pavel-agarkov** [confluentinc/confluent-kafka-dotnet#421]
Description
===========
I have two topics "commands" and "events". After consumer processes a command it produces a new event.
For example after processing "Create item" command - "Item created" event will be produced. But commands should be processed only after all existing events have been processed.   
  
I have successfully implemented this logic by calling `Consumer.QueryWatermarkOffsets` before each `Consumer.Poll` and comparing `WatermarkOffset.High` with current offset. If there are new messages then I call `Consumer.Pause` for "commands" `TopicPartition`. When there are no new messages left I call `Consumer.Resume` for "commands" `TopicPartition`.  After that consumer resumes processing of commands from the offset it stopped before.
   
This works perfectly fine except one use case: If after consumer full process restart there are some new events so I call `Consumer.Pause` for "commands" `TopicPartition` before first `Consumer.Poll`. When all events have been processed I call `Consumer.Resume` for "commands" `TopicPartition` but consumer starts from the beginning of "commands" topic - not the last offset!
   
But when there is no new events after consumer restarts then consumer starts reading commands from the last offset as expected - not the beginning of the topic.
  
I need consumer to always start from the last offset after resuming. Is it possible or I have to switch to manual offset management / manual partition assignment / one consumer per topic / something else?
   
Checklist
=========
 - [x] Confluent.Kafka nuget version: 0.11.3
 - [x] Apache Kafka version: 2.11-1.0.0 from [solsson/kafka](https://hub.docker.com/r/solsson/kafka/)
 - [x] Operating system: Windows+Kubernetes Minikube+[solsson/kafka](https://hub.docker.com/r/solsson/kafka/) container
 - [x] Client configuration: 
      >"group.id": "processor",
      "bootstrap.servers": "bootstrap.kafka:9092",
      "partition.assignment.strategy": "range",
      "enable.auto.commit": true,
      "auto.commit.interval.ms": 1000,
      "auto.offset.reset": "earliest"

**Comment by pavel-agarkov** [comment]
I ended up using one consumer for a topic and balancing between them like this:
```cs
while (!cancellationToken.IsCancellationRequested)
{
    if (HasNewMessages(eventsConsumer, assignedEventsPartitions))
    {
        eventsConsumer.Poll(timeout);
    }
    else
    {
        requestsConsumer.Poll(timeout);
    }
}
```
Probably less efficient but at least it works.

**Comment by mhowlett** [comment]
yep, I'd use two consumers in your scenario (as I understand it) as well.
