### ISSUE TITLE
Avro Serializers/Deserializers + Schema Registry Integration

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#423]
For those looking for Avro Serializers/Deserializers + Schema Registry integration, this functionality has now been merged to master and CI builds uploaded to nuget.org:

https://www.nuget.org/packages/Confluent.Kafka/0.11.3-ci-255
https://www.nuget.org/packages/Confluent.Kafka.Avro/0.11.3-ci-255

Example code is here:
https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/AvroSpecific

This functionality will be included in the next release.

This is a minimal implementation and at this stage only specific serializers have been implemented, but moving forward we plan to reach feature parity with the java implementation.

Big thanks to @treziac for contributing the working prototype on which this feature is based (much of his implementation remains)!

**Comment by vadlit** [comment]
Hello! When new release with these features is expected to be published?

**Comment by mhowlett** [comment]
aiming for mid february. The release will also include generic avro serializers (in addition to the specific serializers already merged) + ability to produce custom timestamps + message headers + IProducer and IConsumer interfaces.

**Comment by sonicsqwirl** [comment]
Are you guys planning Tombstone support for compacted topics?  I don't believe the current CI255 properly handles null messages.   Serializer throws exception, and Deserializer appears to just ignore them.

**Comment by unfw** [comment]
One of my use cases has multiple event types per topic which are represented by different classes. Would that require multiple consumers to listen to a topic?

**Comment by joelnet** [comment]
Hello!

I have been playing with the new avro + schema registry additions and have some feedback.

First I would like to say that I am very excited about this addition. I am using v0.11.0 and have created my own SchemaRegistry and Serializers that I am looking forward to deprecating.

My project assumes the Model will be created first and I have supporting libraries to generate the avro schema from the model. It seems like the opposite is required for this current version.

Adding the new fields Schema, _SCHEMA, Get and Put are easy enough to add to the model. Though I would like to reduce the boiler plate. Also, doing this manually (instead of generated from an avsc doesn't seem ideal) as Get and Put require a fieldPos, which could change and break in the future.

I'd like to share some code that could be beneficial to this project.

We are encoding our models using Microsoft.Hadoop.Avro.AvroSerializer like this:

```csharp
public static string GetRawJsonSchema(Type type)
{
    var serializer = typeof(AvroSerializer)
        .GetMethod("Create", new Type[] { })
        .MakeGenericMethod(type)
        .Invoke(null, null);

    return typeof(IAvroSerializer<>)
        .MakeGenericType(type)
        .GetProperty("WriterSchema")
        .GetValue(serializer)
        .ToString();
}
```

This will generate the schema programatially based on the Serialization attributes.
```csharp
// AVRO Schema will be generated using this DTO.
[DataContract(Name = "User", Namespace = "demo")]
public partial class User
{
	[DataMember(Name = "name")]
	public string Name { get; set; }
	
        [NullableSchema]
	[DataMember(Name = "favorite_number")]
	public System.Nullable<int> FavoriteNumber { get; set; }

	[DataMember(Name = "favorite_color")]
	public string FavoriteColor { get; set; }
}

```

Finally the Serializer / Deserializer:

```csharp
namespace Serialization
{
    using System;
    using System.IO;
    using Microsoft.Hadoop.Avro;
    using Avro = Microsoft.Hadoop.Avro;
    using Schemas;
    using System.Linq;
    using MyProject.Models;

    public static class Serializer<T>
    {
        private static readonly IAvroSerializer<T> AvroSerializer = Avro.AvroSerializer.Create<T>();
        private const byte MagicByte = 0;
        
        public static MemoryStream Serialize(T obj)
        {
            var schemaIdObj = obj as ISchemaId;
            var schemaId = schemaIdObj?.SchemaId ?? 0;

            return Serialize(schemaId, obj);
        }

        public static MemoryStream Serialize(int schemaId, T obj)
        {
            var stream = new MemoryStream();
            stream.WriteByte(MagicByte);
            stream.Write(GetBytes(schemaId), 0, 4);

            AvroSerializer.Serialize(stream, obj);
            stream.Seek(0, SeekOrigin.Begin);

            return stream;
        }

        public static T Deserialize(Stream stream)
        {
            stream.Seek(5, SeekOrigin.Current);
            return AvroSerializer.Deserialize(stream);
        }

        public static T Deserialize(byte[] bytes)
        {
            return Deserialize(new MemoryStream(bytes));
        }

        private static byte[] GetBytes(int number)
        {
            var value = BitConverter.GetBytes(number);
            return BitConverter.IsLittleEndian ? value.Reverse().ToArray() : value;
        }
    }
}
```

I know this feature is early, so I didn't create a pull request and I am a little hesitant until the path for this feature is more solid.

Cheers!

**Comment by raghavrkapoor** [comment]
Hi Matt

When new release with Avro support is expected to be published? Saw a comment above - about target release date to be around mid feb.

**Comment by mhowlett** [comment]
realistically 2-3 weeks. #431 will also be included + generic avro serdes (which haven't been implemented yet).

**Comment by lixiandai** [comment]
hi, Matt
when i use generic Serializer and Deserializer
`using (var producer = new Producer<string, GenericRecord>(producerConfig, new AvroSerializer<string>(), new AvroSerializer<GenericRecord>()))`

i have to use GenericRecord? can i use our own data contract object as T like 
`using (var producer = new Producer<string, T>(producerConfig, new AvroSerializer<string>(), new AvroSerializer<T>()))` then solve it using Autofac or other IOC container?

if doing this way, my code always throw out error below
"only accepts type parameters of int, bool, double, string, float, long, byte[], instances of ISpecificRecord and subclasses of SpecificFixed."

to me, seems i am not using generic Deserializer but using specific Deserializer

**Comment by mhowlett** [comment]
You can also use the avrogen tool from here: https://github.com/confluentinc/avro/releases/tag/v1.7.7.4 to generate C# classes corresponding with specific schemas and use these classes (which implement ISpecificRecord) with `AvroSerializer` and `AvroDeserializer`.

**Comment by lixiandai** [comment]
Matt, tks for pointing me the avrogen tool, but in the zip i did not see any executable exe file

**Comment by mhowlett** [comment]
`dotnet avrogen.dll -s <schema name> .`

**Comment by lixiandai** [comment]
Hi, Matt,
If we want to use the Avro Serializers/Deserializers + Schema Registry, do we have to replace our existing Consumer (config) to Consumer<TKey, TValue>, same for producer, right?

**Comment by lixiandai** [comment]
Hi, Matt,
When i tried the specific Deserializer, 

```
 using (var consumer = new Consumer<Kafka.Null, ClientEventMessage>(consumerConfig, new AvroDeserializer<Kafka.Null>(), new AvroDeserializer<ClientEventMessage>()))
            using (var producer = new Producer<Kafka.Null, ClientEventMessage>(producerConfig, new AvroSerializer<Kafka.Null>(), new AvroSerializer<ClientEventMessage>()))
```

I set TKEY AS Kafka.Null, TValue is our own type which generated by avrogen, but seems the SpecificSerializerImpl<T> class is not happy with the Kafka.Null as TKEY there.

Is that mean I have to give some type like int, bool, double, string, float, etc for TKEY?

Thanks.

**Comment by mhowlett** [comment]
I appear to have omitted to add support for the `null` primitive type. Just implemented this to the 1.0-experimental branch (CI build 385, you can follow the instructions on the readme to reference the nuget package). Note that you can use the 1.0-experimental branch version of Confluent.Kafka.Avro with the 0.11.4 version of Confluent.Kafka. 

Alternatively, you can use the NullSerializer + NullDeserializer/IgnoreDeserializer (and not register the key with schema registry).

**Comment by lixiandai** [comment]
@mhowlett really appreciated for a quick turn-around. I also realized there are lot of other changes between1.0-experimental branch vs 0.11.4 branch we are currently using. Would it be possible to back-forward support this fix in 0.11.4 stable version or not?

Thanks.

**Comment by mhowlett** [comment]
Confluent.Kafka.Avro 1.0-experimental-2 is exactly the same as 0.11.4, except for this change. You can safely use it with Confluent.Kafka v0.11.4. I'll back port it to the master branch, but we probably won't release it soon.

**Comment by lixiandai** [comment]
i did just update Confluent.Kafka.Avro from 0.11.4 to 1.0-experimental-2, however , in my .netframework project, it automatically update my Confluent.Kafka from 0.11.4 to 1.0-experimental-2 also, which is what i did not expect.

When i mean' lot of other changes' are those from Confluent.Kafka package such as 
1. 'Consumer : IConsumer' become internal now
2. 'Consume' function now return ConsumerRecord<TKey, TValue> instead of Message<TKey, TValue>
etc

Is there anyway to only update Confluent.Kafka.Avro to experimental version but let Confluent.Kafka  stay 0.11.4 version?

Thanks.

**Comment by lixiandai** [comment]
@mhowlett 
So here is the issue I am facing. 
I have a producer<Null, CustomziedObject> but it only produces to one partition always. 
Previously my assumption is as long as we did not give any key, the producer should behavior as same as the one without KV and randomly distribute our message to different partitions.   
However, seems Kafka.Null is same as other type like string, int, does that mean we have to handle how to evenly distribute our message to different partitions by assigning the different keys by our own, or any other way which i missed?

Thank you very much.

**Comment by mhowlett** [comment]
ahh right, I forgot about the references. You'll need to wait until I get the change on master, then use a PR built nuget package (or you can use the code and make a nuget package yourself).

I see another comment in this thread via email, which isn't here (presumably deleted). but it's something that didn't occur to me before. Since the avro serializer prepends the schema id to the serialized data, the assignment of messages to partitions will not be random (like if you use the null serializer). You can achieve that by setting the `partitioner` configuration property to `random`.

**Comment by lixiandai** [comment]
@mhowlett one more question related to schema involving. can we evolve the avsc file and generate the same c# class object with different namespace? by doing that, my consumer is not able to consume out the previous version of data. but if i only evolve the avsc file and copy/paste to replace the existing c# class object with same namespace, my consumer is able to consume out both new and old data. 

Is that making sense to you or it is just because i did not something wrong?

**Comment by mhowlett** [comment]
@lixiandai - i noticed this as well and didn't like it. i'm not sure what the behavior is with java. if java is more flexible on this, I'll look at making changes to the .net avro library.

**Comment by mhowlett** [comment]
closing as this feature has now been merged.

**Comment by sanzor** [comment]
Can this avro serializer be used when working with Conflient's KSQL ? I have not yet found a way to just serialize a C# object to AVRO and send it to a kafka topic , and then consume it.

**Comment by mhowlett** [comment]
You need to define the schema first and use avrogen to generate the C# class (and integrate with Schema Registry). See the README.md / examples.

If you haven't yet chosen a serialization format yet, i would caution that Avro in .NET is a bit buggy. I would recommend JSON or Protobuf. The JSON serializers allow you to work object first (serialization defined using attributes), which seems to be what you want.

**Comment by jfloodnet** [comment]
> You need to define the schema first and use avrogen to generate the C# class (and integrate with Schema Registry). See the README.md / examples.
> 
> If you haven't yet chosen a serialization format yet, i would caution that Avro in .NET is a bit buggy. I would recommend JSON or Protobuf. The JSON serializers allow you to work object first (serialization defined using attributes), which seems to be what you want.

A few years on now, would you still give the same advice for .net and avro?
