### ISSUE TITLE
No public method available on producer to produce with timestamp.

### ISSUE THREAD

**Issue by maximecaron** [confluentinc/confluent-kafka-dotnet#429]
Description
===========
It's currently impossible from another assembly to produce message with a custom Creation Time because the produce method on the producer class is internal.

Is there any reason this feature is not exposed yet ?

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3.0
 - [x] Apache Kafka version: 0.10.1
 - [x] Client configuration:
 - [x] Operating system: Windows

**Comment by mhowlett** [comment]
it just hasn't been implemented yet. I'm working on this right now, expect it soon.

**Comment by maximecaron** [comment]
Thanks a lot Matt. 
Please Let me know if I can be of any help.

**Comment by mhowlett** [comment]
the relevant PR is #431. Keep an eye on that.
