### ISSUE TITLE
how to release memory when my producer run for a long time.

### ISSUE THREAD

**Issue by liaodawee** [confluentinc/confluent-kafka-dotnet#432]
Description
===========
 my producer is used in webapi
 when the producer run a long time ,i find **iis memory increase too quick  。。。**  
 i create producer when application start like this.
  protected void Application_Start()
        {
            HttpContext.Current.Cache["MyTopic"] = KafkaProducerHelper.CreateNewNullKeyProducer("MyTopic");   
        }
  when it send message ,i catch some exception  ,i will call dispose and re-create the producer .
  so when the web run a long time,iis process memory increase too much.
  how can i resolve this .please help me ,thanks.

 
How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version:0.11.3
 - [x] Apache Kafka version: 0.11.0
 - [ ] Client configuration: 
 - [x] Operating system:win10 
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
  

 - [ ] Provide broker log excerpts
 - [x] Critical issue discussion

**Comment by edenhill** [comment]
Please edit your original comment and fill out the checklist, versions, OS and configuration in particular.
Thanks

**Comment by liaodawee** [comment]
@mhowlett    already updated .. thanks.    
 at first,i use producer by using(var producer =xxx){  }
later i found kafka logs in linux,shows: too many files opened.  and i alter linux file limit config ,65535,but still not work. Then i see windows performance , and find iis request is too many ,more than 2000 concurrence ,so i create the producer then application started to reduce producer's creatation
 i guess this problem is cause by the producer is create to quick ,but  gc release is slow. so i chanage my code , and resolve it .
HttpContext.Current.Cache["MyTopic"]=KafkaProducerHelper.CreateNewNullKeyProducer("MyTopic");  

but new problem occured.. iis memory increase to much.  i try to find librdkafka config to resolve it ,but failed ..
please help me ~thanks again

**Comment by liaodawee** [comment]
i send message by async , so when message are too much and the task runs for a long time ,the memory will increase too much ,i guess. 

@mhowlett
