### ISSUE TITLE
Can't find a build target for netcoreapp2.0

### ISSUE THREAD

**Issue by BFrancisA** [confluentinc/confluent-kafka-dotnet#435]
Description
===========

Can't find a build target for netcoreapp2.0.  Is there one?  NuGet has only netcoreapp1.1.

How to reproduce
================
Tried building as follows:  (On windows 10)

Open a CMD window In directory:  

\Kafka\confluent-kafka-dotnet\src\Confluent.Kafka>

Build and publish by running:  

dotnet publish -c Release

There is no version generated for netcoreapp 2.0 because it is missinge from the targets.

Checklist
=========
Please provide the following information:

 - [x ] Confluent.Kafka nuget version:  n/a
 - [ x] Apache Kafka version:  latest
 - [x ] Client configuration: latest
 - [x ] Operating system:  all
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
it targets `netstandard1.3`, which is compatible with `netcoreapp2.0`. maybe try `-f netstandard1.3` ?

**Comment by BFrancisA** [comment]
Yes, that was the problem.
