### ISSUE TITLE
Question Supported/Verified Kafka Broker Version

### ISSUE THREAD

**Issue by David-V-Spencer** [confluentinc/confluent-kafka-dotnet#437]
Description
===========
With the recent release of Kafka version 1.0.0 we are looking at upgrading broker version in production.

I don't see any information about supported brokers version in the Kafka DotNet project.

I lookied at LibRdKafka and found a list of broker versions listed support at:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

However, I don't see any mention about support for Kafka version 1.0 one way or the other.

Checking Kafka release notes the mention there are some potentially breaking changes:
http://kafka.apache.org/10/documentation.html#upgrade

For the most part these seem like none issues in our use case because we have been using broker version > 10.0 for a while now. One thing that did catch my eye was the not about the Kafka Java client and breaking change due to the change of expected collections, but I expect this is only client level change and transparent at the broker level...

Worst case scenario I can setup a Kafka 1.0 broker and test out our applications against it, but hoping there might be a quicker way. Is there any insights that you can provide about possible issues with upgrading to Kafka 1.0 using the Confluent client 11.2 or 11.3 versions?

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version: 11.2 & 11.3
 - [X] Apache Kafka version:  2.11-0.10.2.1
 - [ ] Client configuration: N/A
 - [ ] Operating system: N/A
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration) N/A
 - [ ] Provide broker log excerpts N/A
 - [ ] Critical issue

**Comment by mhowlett** [comment]
Confluent supports the .NET client for use with all broker versions, and it is tested against 1.0 brokers. I'm not aware of any issues specific to Kafka 1.0.
