### ISSUE TITLE
Is it possible to do crc checking when consuming?

### ISSUE THREAD

**Issue by HenningRoigaard** [confluentinc/confluent-kafka-dotnet#44]
It seems as if the Consumer does not support crc checking by default when fetching messages and I cannot find any configuration that enables it. In addition, the client library does not expose enough information for users of the library to do it themselves.

I do not know if this is related to Confluent.Kafka or Librdkafka, but it seems reasonable to enable crc checking one way or another. The java implementation has a config option “check.crcs” for the consumer, which does exactly that according to the [documentation](http://kafka.apache.org/090/documentation.html#consumerconfigs)

I have tested the missing crc checking by producing a simple message (key “123” and value “abc”), editing the log with visual studios binary editor to have key “124”, and then consume the message. Consuming the message yielded a message with key “124” and no error. As the crc is not exposed when fetching a message in Confluent.Kafka, I could not directly check that the crc of the message was changed. To confirm that the crc was indeed changed, I wrote a simple client library using the [Kafka Fetch API](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchRequest) and calculated the crc using Crc32Provider from the [kafka-net library](https://github.com/Jroland/kafka-net/blob/master/src/kafka-net/Common/Crc32Provider.cs). This confirmed that the crc was changed when flipping “123” to “124” and unchanged when not. 
The test was performed using Kafka 0.9.0.1, Librdkafka 0.9.2-ci-28 and Confluent.Kafka 0.9.2-preview, all running on the same Windows 10 developer machine. The consumer was created with the following configuration:

```csharp
var config = new Dictionary<string, object>()
      {
        { "enable.auto.commit", false },
        { "group.id", "NOT_A_GROUP" },
        { "bootstrap.servers", "localhost:9092" },        
      };
```

**Comment by edenhill** [comment]
You are right that this isn't currently supported and will need to be implemented in librdkafka.

**Comment by HenningRoigaard** [comment]
ok, thank you for the speedy response. I will create a request for the feature in your librdkafka project.
