### ISSUE TITLE
Question: Should waiting on delivery for each message be extremely slow?

### ISSUE THREAD

**Issue by bencyoung** [confluentinc/confluent-kafka-dotnet#440]
I have a producer loop that looks like this:

```csharp
        private static async Task MainLoop(Confluent.Kafka.Producer producer, string topic, byte[] file, int pausems)
        {
            var timer = Stopwatch.StartNew();
            int count = 0;

            while (true)
            {
                Console.WriteLine("Count {0} at {1}/s", count, count / timer.Elapsed.TotalSeconds);
                var t = producer.ProduceAsync(topic, Guid.NewGuid().ToByteArray(), file);
                await Task.Delay(TimeSpan.FromMilliseconds(pausems));
                await t;
                ++count;
            }
        }
```
 This produces output like:

```
Count 2 at 1.98295629237144/s
Count 3 at 1.49284709777337/s
Count 4 at 1.32867649935994/s
Count 5 at 1.24676679085046/s
Count 6 at 1.19727146621934/s
Count 7 at 0.873526688049768/s
```

which seems very slow. If I remove the "await t" line then I typically get 60-80 messages a second. If I add a "producer.Flush(100)" then I get about 10 msg/s. 

I assume I'm missing some simple config setting to enable much faster production, even with delivery reports? The only config option I'm passing to the producer is the name of the server

**Comment by edenhill** [comment]
Some questions:
 * Whats your dotnet and librdkafka versions?
 * What is pausems set to?
 * Please provide your producer configuration

**Comment by bencyoung** [comment]
It's:

```
  <package id="Confluent.Kafka" version="0.11.3" targetFramework="net462" />
  <package id="librdkafka.redist" version="0.11.3" targetFramework="net462" />
```

pausems is 10ms, but changing it to 0 or even removing the line doesn't change anything.

Producer config is simply:

```csharp
        {
            var file = Encoding.UTF8.GetBytes(File.ReadAllText(args[0]));
            var kafka = args[1];
            var topic = args[2];
            var pausems = int.Parse(args[3]);

            using (var producer = new Confluent.Kafka.Producer(new Dictionary<string, object>
            {
                { "bootstrap.servers", kafka },
                //{ "debug", "all" }
            }))
            {
                producer.OnLog += (sender, message) => Console.WriteLine(message.Message);

                MainLoop(producer, topic, file, pausems).GetAwaiter().GetResult();
            }
        }
```

**Comment by edenhill** [comment]
On Windows you might need to lower `socket.blocking.max.ms` to expedite sending of messages.
We're looking for a proper fix to this but in the meantime that's the workaround.
More info
https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency

**Comment by bencyoung** [comment]
Thanks, that's great. Setting it to 1 gives me back 400 msg/s with the pause set to 0

**Comment by edenhill** [comment]
👍 
Do note that synchronous commits will always be limited by the broker round-trip-time.
https://github.com/edenhill/librdkafka/wiki/FAQ#why-is-there-no-sync-produce-interface
