### ISSUE TITLE
Consume(out Message<TKey, TValue> message, int millisecondsTimeout) returns only a single message

### ISSUE THREAD

**Issue by ayappant** [confluentinc/confluent-kafka-dotnet#443]
Description
===========
Consume(out Message<TKey, TValue> message, int millisecondsTimeout) returns only a single message. Is there any other method which we could use for consuming multiple messages() from a kafka topic

How to reproduce
================
Use Consume(out Message<TKey, TValue> message, int millisecondsTimeout) to consume messages from kafka. You end up getting only a single message. I am consuming from a topic which has billions of messages. What is the recommendation here.

Checklist
=========
Please provide the following information:

 - [0.11.3 ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ Windows 10] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
no, but note that behind the scenes, data is fetched from kafka in batches, it is just delivered to you via the api one message at a time.
