### ISSUE TITLE
Geeting Error Failed to create thread

### ISSUE THREAD

**Issue by soyebparvez** [confluentinc/confluent-kafka-dotnet#455]
Description
===========
Geeting Error Failed to create thread.

Exception: Failed to create thread: No error (0) StackTrace:    at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config)
   at Confluent.Kafka.Producer..ctor(IEnumerable`1 config, Boolean manualPoll, Boolean disableDeliveryReports)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer, Boolean manualPoll, Boolean disableDeliveryReports)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer)

How to reproduce
================
My app is hosted in ISS where on class publish and consume on different threads. This class is exposed through API.
We are hitting this API 300 times with 3 second delay.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: "0.11.3"
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system: Windows app hosted in IIS
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
librdkafka is apparently failing when attempting to create a thread. I don't know why this would occur. I'm not that familiar with IIS, but you could try tweaking parameters related to threads, though I would have guessed you can only control the number of request handling threads (and i don't know how this would affect the ability of librdkafka to create and manage threads, unless you're running into OS limits, but that doesn't seem likely).

**Comment by mhowlett** [comment]
I don't have more insight on this without reviewing code - i'm wondering if you're doing something that would result in many producers/consumers getting created and not disposed. closing since this is old and i've not seen this issue anywhere else, but feel free to re-open with more details if this is still a problem.

**Comment by soyebparvez** [comment]
Thanks for reply. Problem had solved. I was creating too many producer. I changed my code and use one producer to post my data in different topics.
