### ISSUE TITLE
Failed to verify broker certificate: unable to get local issuer certificate

### ISSUE THREAD

**Issue by tollek** [confluentinc/confluent-kafka-dotnet#456]
Description
===========
I am running 3 host cluster on a hosted service (cloudkarafka).
Client = Windows 10 + dotnet 4.7.1
I've successfully run tests using kafka builtin kafka-console-consumer & kafka-console-producer, so I think my credentials and system certs are fine.

When runnign a producer, I am getting following logs (logs file attched).
The error I am seeing is "Failed to verify broker certificate: unable to get local issuer certificate", but that might or might not be the issue.

How to reproduce
================
Log attached

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [ ] Apache Kafka version: 
 - [x] Client configuration: attached in log
 - [x] Operating system: Windows 10
 - [x] Provide logs (with "debug" : "generic,broker,topic,metadata,feature,queue,protocol,msg,security,all" as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
[log-2018-03-09.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1797676/log-2018-03-09.txt)

**Comment by mhowlett** [comment]
I started (but never finished) writing in detail about security here, I think it will help: 
https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security

**Comment by tollek** [comment]
Thanks.
It appeared to be an issue with the broker verification.
Everything worked when I set CA certificate:
```
var config = new Dictionary<string, object> {
  {"ssl.ca.location", <location of broker root CA> },
  ...
};
```

It looks that C# does not use the same root certificates as Java does (as the Java consumer/producer worked out of box).
I imported the certs from Java (using x509 format) and used them in the C# app (as the "ssl.ca.location").

**Comment by ewassef** [comment]
> Thanks.
> It appeared to be an issue with the broker verification.
> Everything worked when I set CA certificate:
> 
> ```
> var config = new Dictionary<string, object> {
>   {"ssl.ca.location", <location of broker root CA> },
>   ...
> };
> ```
> It looks that C# does not use the same root certificates as Java does (as the Java consumer/producer worked out of box).
> I imported the certs from Java (using x509 format) and used them in the C# app (as the "ssl.ca.location").

I am running into the same issue you were having, but dont understand what you meant by exported them from Java. 

I copied the Certificate value from the heroku page and saved it locally, but am still getting this error. I pointed the ssl.cert.location value to saved .crt file too

**Comment by ewassef** [comment]
@tollek @mhowlett Tagging you in case this gets lost since its an older issue

**Comment by tollek** [comment]
I can't really check it at this point - the source code I used for testing is long gone :)
It's worth to read the link posted by @mhowlett: https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security
Not sure if I understand your snippet correctly, but broker cert is one thing and CA root cert is another. It's very important to get this right.

**Comment by ewassef** [comment]
Yes, i read those links, but the SASL section is empty for both examples. I believe the one i would need is SASL_SSL.. 

I am trying to connect to a Heroku Karka resource called Carafka. They provide the SASL username/ password, API key (no clue what to do with that) and the CA cert string. Ive attempted to connect using SASL SCRAM and found almost no resources (except your issue) that seems to be right on the money

**Comment by saherahwal** [comment]
I had similar issue with SSL handshake problem https://github.com/confluentinc/confluent-kafka-dotnet/issues/1374 

I was able to solve having a .pem file under my root of the application and setting the SslCaLocation config. 

However, why doesn't Confluent Lib access the Windows Trusted Certificate Root Store ? is that a known issue?
