### ISSUE TITLE
Consume read messages already commited

### ISSUE THREAD

**Issue by Rymix** [confluentinc/confluent-kafka-dotnet#457]
Hi,

I face a problem since few weeks.
Sometimes the consumer function give me the message with offset 0, even i consumed him long time ago And it makes me read again all messages.
I tried on a local kafka and another kafka instance and both have the same problem.

Here is my code : 

```
        private Dictionary<string, object> _constructConfig(string brokerList, bool enableAutoCommit) =>
            new Dictionary<string, object>
            {
                {"group.id", "jokerGroup"},
                {"enable.auto.commit", enableAutoCommit},
                {"auto.commit.interval.ms", 5000},
                {"statistics.interval.ms", 60000},
                {"bootstrap.servers", brokerList},
                {
                    "default.topic.config", new Dictionary<string, object>
                    {
                        {"auto.offset.reset", "smallest"}
                    }
                }
            };
```
```
                while (foundMessage == false && nbRetry < 20)
                {
                    while (consumer.Consume(out msg, TimeSpan.FromMilliseconds(1000)))
                    {
                        foundMessage = true;
                        ....
                   }
                }
```

```
        public async Task<CommittedOffsets> CommitAsync(Consumer<Null, string> consumer, Message<Null, string> msg)
        {
            CommittedOffsets offsets = await consumer.CommitAsync(msg);
            _logger.LogInformation(LogEvent.NeedCreateCode, $"COMMIT : {offsets.Offsets.FirstOrDefault()}");

            return offsets;
        }
```

This problem happend randomly, i have no more informations (Maybe every 24h ?)
And i also read kafka on my windows using basics scripts and sometimes i got this warning (Maybe it can help us to find the issue) : 

> [2018-03-09 13:23:34,135] WARN Auto-commit of offsets {JokerTopic-0=OffsetAndMetadata{offset=10, metadata=''}} failed for group console-consumer-82368: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)

Thank you for your precious help !

Confluent.Kafka nuget version: v0.11.3-ci-255
Operating system: W10

**Comment by mhowlett** [comment]
committed offsets are by default discarded by the broker every 24 hours, you may need to increase the `offsets.retention.minutes` broker setting. i think you might be running into this. this confuses a lot of people and there is even a kip open to change it: https://cwiki.apache.org/confluence/display/KAFKA/KIP-186%3A+Increase+offsets+retention+default+to+7+days

**Comment by Oipo** [comment]
I currently have something similar, but it occurs roughly every hour. Even though it uses the default autocommit and auto.offset.reset settings. Is there a way to get extra debugging info as to why it happens?

**Comment by edenhill** [comment]
`"debug": "cgrp,topic,fetch"` will give you debugging from the fetcher,  et.al.

**Comment by Oipo** [comment]
Is there a way to log this debug to a file? The service is running under an account without rights to login to a console.

**Comment by Oipo** [comment]
One of the kafka instances in the cluster was broken, leading to different offsets in the leader and the follower. Thanks for the help.
