### ISSUE TITLE
IIS crash on 2nd request that uses Producer

### ISSUE THREAD

**Issue by tollek** [confluentinc/confluent-kafka-dotnet#458]
Description
===========
I am running a REST service deployed on IIS. The service reads data from request and tries to send it to kafka.
My code runs OK for the first request, but crashes IIS on 2nd request.

How to reproduce
================
Following code snippet works, but only on first request. 2nd request will crash IIS
```
// producer created in Global.asax and injected into Controller
var producer = new Producer(config, false, false)

public class KafkaController : ApiController {
  ...
  public HttpResponseMessage PostStats(...) { 
    // controller code (key=null, data=serialized json)
    var task = kafkaProducer.ProduceAsync(topicName, null, data);
    var result = task.Result;
    // first request: OK
    // second request: IIS crash
  }
}
```
And similar snippet with manual polling:
```
// producer created in Global.asax and injected into Controller
var producer = new Producer(config, true, false);

// controller code (key=null, data=serialized json)
var task = kafkaProducer.ProduceAsync(topicName, null, data);
kafkaProducer.Poll(5 * 1000);
var result = task.Result;
// first request: OK
// second request: IIS crash
```

Everything is fine if I create and dispose Producer inside controller action:
```
var kafkaProducer =  new Producer(config, false, false);
var task = kafkaProducer.ProduceAsync(topicName, null, data);
var result = task.Result;
kafkaProducer.Dispose();
// This will be OK, but is prohibitively slow
```

Client config:
```
Key = metadata.broker.list, Value = host1:9094,host2:9094,host3:9094
Key = batch.num.messages, Value = 50
Key = queue.buffering.max.ms, Value = 10
Key = message.timeout.ms, Value = 5000
Key = request.required.acks, Value = 0
Key = security.protocol, Value = SASL_SSL
Key = sasl.mechanisms, Value = SCRAM-SHA-256
Key = sasl.username, Value = <user>
Key = sasl.password, Value = <pass>
Key = ssl.ca.location, Value = <ca-cert-path>
Key = debug, Value = all
```

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [ ] Apache Kafka version: 
 - [x] Client configuration:
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
A stack trace would be handy - can you try catching exceptions and logging? Without more information my best guess is there is some reason you're either trying to use a disposed producer, or for some reason kafkaProducer is null.

**Comment by tollek** [comment]
@mhowlett  wow, I am impressed with your intuition ;-)
Indeed, I was calling producer.Dispose() after every request (I've implemented my own DI to have single producer instance for all requests. It has Dispose() method that was run after every request, not once for whole app, as I expected).

This closes the issues.

For future reports - as I am running inside IIS I cannot find debug info easily.
If I attach error & log handler to the producer, will this be enough, or is there some more info written to stderr?
