### ISSUE TITLE
Question: Understanding Kafka Statistics Event

### ISSUE THREAD

**Issue by keggster101020** [confluentinc/confluent-kafka-dotnet#459]
Description
===========

Hi, 

I'm looking to understand the kafka statistic event and the values that come from this. 

I'm using kafka inside of Azure Service Fabric with 5 brokers. I have logging wrapped around this statistic events and I'm seeing some behavior I don't quite understand.

1. Although I have registered 5 brokers, there are a total of 10 brokers from the statistic events.

    - 5 have IP addresses I've registered. 5 have what look like DNS of the SF cluster that weren't registered.

2. The brokers that are sending and receiving the most messages are the 5 additional brokers and not the 5 original brokers. (5 unregistered brokers have 100,000+ | 5 registered <1000).
3. From logging, statistic logs that are coming later have lower total messages count sometimes. That is a log at 10:00AM has more messages than a log at 10:01AM, if messages sent and received are total counts how is this possible? 

## Producer Configuration
```csharp
{ "bootstrap.servers", _brokerList },
{ "batch.num.messages", 1 },
{ "auto.offset.reset", "smallest" },
{ "socket.nagle.disable", true },
{ "socket.blocking.max.ms", 1 },
{ "queue.buffering.max.ms", 1 },
 { "default.topic.config", new Dictionary<string, object>
         {
               { "acks", 0 }
          }
}
```
## Consumer Configuration
```csharp
{ "group.id", "some-consumer" },
{ "enable.auto.commit", enableAutoCommit },
{ "bootstrap.servers", brokerList }, //5 registered brokers
{ "statistics.interval.ms", 60000 },
{ "default.topic.config", new Dictionary<string, object>
        {
              { "auto.offset.reset", "smallest" }
         }
}
```

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.0
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [x] Operating system: Windows Server 2016
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
re number of brokers:
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-broker-tcp-connections

**Comment by keggster101020** [comment]
Closing as the above answered the question. Thanks!
