### ISSUE TITLE
Question about Unassign on RebalanceCallback

### ISSUE THREAD

**Issue by melnikvitaly** [confluentinc/confluent-kafka-dotnet#462]
Description
===========
Have noticed in the code this line:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/309e75f7b98c867c7dc60cca6c15ac63d3d0bbd8/src/Confluent.Kafka/Consumer.cs#L785
If the consumer is subscribed to more then one topic will not this unassign us from all topic when rebalancing of one of them is in progress?

**Comment by mhowlett** [comment]
yes, that's correct. there are some inefficiencies here that we'll fix in the 1.0 branch or document & provide roadmap guidance on relatively soon.
