### ISSUE TITLE
Memory leak in produce?

### ISSUE THREAD

**Issue by jbouzaglou** [confluentinc/confluent-kafka-dotnet#464]
Description
===========
On current master, in "internal void Produce", Producer.cs, line 194, it seems the code allocates a GCHandle using GCHandle.Alloc, but only frees it if there was a error producing.
Is this expected?
![image](https://user-images.githubusercontent.com/2351915/37515310-4d8250d4-2902-11e8-9663-17d8b7db8c61.png)

How to reproduce
================
NA

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
yes, this is correct - we need to pin the delivery handler completion source until the delivery report is available at which point we un-pin it.

**Comment by jbouzaglou** [comment]
Indeed I should have looked in DeliveryReportCallbackImpl, where you free the handle when the callback executes
