### ISSUE TITLE
How to support more than one comsuer/producer

### ISSUE THREAD

**Issue by PingPongSet** [confluentinc/confluent-kafka-dotnet#467]
Description
===========
Only one consumer is allowed to assign partition. If a new consumer is launched, the new consumer will be assigned partition, and the old consumer will be removed from partition.

Is it possible to allow more than one consumer and producer?

https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/AdvancedConsumer

How to reproduce
================
1 Launch consumer A, which gets partition assigned.
2 Lauch consumer B, which gets partition assigned. Notice Consumer A is removed from partition.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [x] Apache Kafka version:  kafka_2.12-1.0.1
 - [ ] Client configuration:
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
any number of consumers can read from the same partition, but they need to be in different consumer groups (have different `group.id`). any number of producers can write to the same partition.

**Comment by PingPongSet** [comment]
@mhowlett That is helpful. It works once unique group.id is assigned, more than one consumer is supported. Thanks.
