### ISSUE TITLE
[Question] ordering guarantees detals

### ISSUE THREAD

**Issue by vchekan** [confluentinc/confluent-kafka-dotnet#469]
Description
===========
I am reading documentation on ordering
https://github.com/confluentinc/confluent-kafka-dotnet/wiki/Producing-messages#ordering
and I still do not have clear picture on what it says.

1. Does it mean "ordering within a partition is not guaranteed"?
2. What kind of out of order could happen? 
  2.1  Due to "at least once" nature of producer, batch can be repeated and as result, a message within those 2 repeated batches will look out of order, as in [1,2,3],[1,2,3] will contain sub-sequence (3,1)?
  2.2 Actual batches could be sent out of order within single partition, so [1,2,3],[4,5,6] can become [4,5,6],[1,2,3]?

What is technical reason for this out of order situation? Are messages in failed message set put aside until partition recovers and then re-queued, which creates possibility for failed batch to be sent after messages in queue already? How message queues are organized, are they per-broker or one queue per-producer plus failed messages retry buffer?

**Comment by mhowlett** [comment]
these are good questions (about the behavior of librdkafka) and we need better documentation. Rather than understand all the details here, you might typically (for maximal throughput) write applications that tolerate out of order messages by including a unique id in the message and de-duping / re-ordering on the consumer. To guarantee produce order, you'll need to produce synchronously (i.e. wait for a delivery report for a produced message before producing another). 

I think the main thing to note is that there can be multiple produce requests (of message batches) in flight (`max.in.flight`), and it's possible for an earlier request to fail and a later to not, in which case messages in the earlier batch will be retried (usually automatically: `message.send.max.retries`) and potentially come in later. 

When we implement EoS functionality (on the near term roadmap), this will allow for guaranteed ordering with multiple in flight requests.

**Comment by vchekan** [comment]
I think I am confused by the notion of `max.in.flight`. If there is single message queue per broker, then how it is possible to have multiple produce requests in flight? Is single queue being partitioned and message sets sent in parrallel? Perhaps not, because then message order would be broken for all messages. But if only one produce request per broker is allowed, then why do we need `max.in.flight`?

**Comment by edenhill** [comment]
With the upcoming v0.11.4 release you will get guaranteed ordering with max.in.flight=1, at the expense of lower throughput. But you don't need to do sync producing (which is terribly slow).
There's some updated documentation here:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#producer-retries

**Comment by vchekan** [comment]
@edenhill thanks for pointing to the documentation.
But what I read in the documentation contradicts to what @mhowlett  is saying. He says that the only way to produce in-order is to produce messages synchronously, whereas documentation says " if max.in.flight > 1 and retries > 0, retried messages may be produced out of order", which means that if I set max.in.flight to 1 then I am safe.

Also I still do not understand relations between failed and non-failed messages. Documentation says "A backoff time (retry.backoff.ms) is set on the retried messages which effectively blocks retry attempts until the backoff time has expired". Is it really retry which will be blocked or any attempt to produce? What I mean is scenario when message failed and marked for retry in 200ms, then new message comes in and because it is not marked for retry, it is being sent, and after 200ms first one is retries and sent.
Is my understanding correct, that failed and new messages are in different queues and this create race condition if there is >1 thread per broker, because thread is allowed to send produce message to broker from "fresh" message queue or "retry" queue?

**Comment by edenhill** [comment]
Sync producing is not required with max.in.flight=1 (from release v0.11.4), earlier releases had issues with retries and out of ordering could happen even with max.in.flight then, so the previous recommendation was to use sync produce in those cases, but that is no required.

The retry logic operates on a per-message basis and operates between your produce() call and the delivery report. Upon produce() each message is assigned an internal sequence number (for the given partition) and this sequence number is used to sort the partition's message queue when a produce request fails and a message is put back on the partition's producer queue for later retry. This queue contains both "fresh" messages and retrying messages.
Before constructing a message batch and transmitting it to the broker the producer will check the retry time of the first message in the queue, if there is no retry time (first time message is sent) or the retry time has expired the message is added to the batch, but if the retry time is in the future the producer skips that partition and moves to the next.
This ensures that messages are in fact in order even after retries, but requires max.in.flight=1.

**Comment by vchekan** [comment]
Thanks, its getting clearer. One last question :) Why sorting operation is required, isn't queue naturally sorted in order in which messages arrived?

**Comment by edenhill** [comment]
They are, until you need to retry a set of messages, in which case you need to insert them in the correct position of the queue.
There could be previous message sets being retried too, so it is not as simple as prepending to the queue.
