### ISSUE TITLE
Production is slow and slow

### ISSUE THREAD

**Issue by aqa510415008** [confluentinc/confluent-kafka-dotnet#471]
Description
===========
Production is slow and slow

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version : 0.11.3
 - [ ] Apache Kafka version : 2.11-1.0.0
 - [x] Client configuration:
![image](https://user-images.githubusercontent.com/28291464/37747150-b8e06aea-2db8-11e8-906b-44378f28760d.png)

 - [x] Operating system: 
 Kafka system： Windows Server 2012 R2 ，
 Confluent-kafka Application Systemn：Windows 10
 - [x] Provide logs (with "debug" : "..." as necessary in configuration)
Use this [ examples.SimpleProducer](https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/SimpleProducer)  to only modify the address for production.
![image](https://user-images.githubusercontent.com/28291464/37747130-9e9eb380-2db8-11e8-8f60-55afe5a54b55.png)

 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by aqa510415008** [comment]
Do not configure socket.blocking.max.ms this production takes one second

**Comment by mhowlett** [comment]
unfortunately you haven't provided enough information to give any insight. produce latency should be much less than 1 second in any practical scenario

**Comment by aqa510415008** [comment]
@mhowlett  Information has been added

**Comment by vchekan** [comment]
Could this be related to #475?
