### ISSUE TITLE
 Learning Resources for Confluent Kafka .NET Client

### ISSUE THREAD

**Issue by PingPongSet** [confluentinc/confluent-kafka-dotnet#473]
Description
===========

I am new to Kafka, I have gone through the links below with my thoughts. But I want to further understand how to code in terms of Consumer and Producer. For example, consumer/producer acknowledge (sync/async), message persistence, and much more, ideally with .net code.

This code example is helpful. However, I would like to understand further as to why it is coded that way, especially some areas in AdvancedConsumer project.
https://github.com/confluentinc/confluent-kafka-dotnet

This document can be improved further, as I am confused after reading it.
https://docs.confluent.io/current/clients/index.html

Code example is required for this API doc.
https://docs.confluent.io/current/clients/confluent-kafka-dotnet/api/Confluent.Kafka.html

Considering Java Client is different from .NET client, which makes it difficult to learn.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
agreed, we need better documentation. This is a priority after sorting out the 1.0 API and promoting the 1.0-experimental branch to master.
