### ISSUE TITLE
ProduceAsync not throwing exceptions on error

### ISSUE THREAD

**Issue by roederja2** [confluentinc/confluent-kafka-dotnet#479]
Description
===========
I use this code `_producer.ProduceAsync(_errorTopic, originalMessage.Key, originalMessage.Value).Wait()` to produce a message and I expected that if the method completes (after the Wait) without an exception the message is published. But in fact it can happen that the Message object returned by ProduceAsync has an Error on it - in my case it was "Not enough in-sync replicas". So to get the behaviour I want I actually have to do
`var result = _producer.ProduceAsync(_errorTopic, originalMessage.Key, originalMessage.Value).Result;
                    if (result.Error.HasError)
                    {
                        throw new KafkaException(result.Error);
                    }`

This is not what I expect in C#. I realize this is quite a breaking change to change it now. So I'm starting this to initiate a discussion.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [x] Apache Kafka version: 0.11
 - [x] Client configuration:
"request.required.acks", -1
 - [x] Operating system: windows/linux - affects both
 - [x] Provide logs (with "debug" : "..." as necessary in configuration)
 - [x] Provide broker log excerpts: Not relevant
 - [x] Critical issue NO

**Comment by mhowlett** [comment]
we will be making breaking changes elsewhere when moving to 1.0 (which will coincide with introducing EoS functionality). I think you're right here (but haven't thought through all the details).

**Comment by gccmbr** [comment]
@roederja2 I am seeing the Task.Result paradigm used frequently with asynchronous programming these days. Otherwise you are forced into either a synchronous wait or an async wait surrounded by a try/catch which has ramifications so as to determine the status of an async task. Returning a result provides information about the status of the task which gives options.

This is taken from the Azure Cloud Storage tutorials:
```
TableOperation retrieveOperation = TableOperation.Retrieve<customerentity>("Harp", "Walter");
TableResult result = await table.ExecuteAsync(retrieveOperation);

```
Here is another snippet via .NET Azure tutorials:

```
Task<bool> tableStatus = CreateTable(storageAccount, tableName);
tableStatus.Wait();
if (!tableStatus.Result) { Console.WriteLine("table creation error");}
```

**Comment by roederja2** [comment]
If you return a Task you can also look at the Exception property if you don't want to use try/catch. Plus, as it stands the ProduceAsync methods does throw exceptions in some cases, but not others depending on when they happen inside the library - this is inconsistent and also not what is expected in C#. Checking return codes is C style and very much discouraged in languages that support Exceptions.

**Comment by gccmbr** [comment]
I understand what you are saying.  Here is Microsoft .NET's statement on Task-based Asynchronous Patterns (TAP) and the link to the statement below:

> Task-based Asynchronous Pattern (TAP)   03/30/2017
>  
> The Task-based Asynchronous Pattern (TAP) is based on the System.Threading.Tasks.Task and System.Threading.Tasks.Task<TResult> types in the System.Threading.Tasks namespace, which are used to represent arbitrary asynchronous operations. TAP is the recommended asynchronous design pattern for new development. 

[https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap](url)

It seems to be the paradigm going forward for .NET.  I found that there was plenty of very well written documentation from Microsoft .NET on the subject which made my transition to TAP quicker.

**Comment by mhowlett** [comment]
This change is in the 1.0-experimental branch. Also, any method that returns more than one result, each of which could have an associated error (e.g. `Consumer.Pause`) will throw an exception if any of the results is in error (with the full result available as a property on the exception). You're right, expecting users to check for errors is inconvenient and error-prone in C#.
