### ISSUE TITLE
Can we set the number of partitions in Config or TopicConfig? 

### ISSUE THREAD

**Issue by surajchawla** [confluentinc/confluent-kafka-dotnet#48]
I am not sure where to ask this question? But can we set the number of partitions per topic when we create the topic?

**Comment by mhowlett** [comment]
there is currently no admin API that allows you to create topics using a client library (in any language). However this feature is coming soon. Right now, you can create topics via the command line:

> bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test

or rely on auto topic creation. Relevant broker config parameters: `auto.create.topics.enable` (defaults to true), `num.partitions` and `default.replication.factor`.

**Comment by ondrejtomcik** [comment]
Hello @mhowlett. How it looks like with admin API? You mentioned that it's coming soon. Do you have any idea when?

**Comment by treziac** [comment]
Not yet implemented on librdkafka (tracking is here: https://github.com/edenhill/librdkafka/issues/986). It is available on java client only for the moment. I assume the api in librdkafka will be equivalent
https://kafka.apache.org/0110/javadoc/index.html?org/apache/kafka/clients/admin/AdminClient.html
