### ISSUE TITLE
Performance affected when Consumer and Producer in same Process

### ISSUE THREAD

**Issue by idelix** [confluentinc/confluent-kafka-dotnet#485]
Description
===========

Application A is made up of a producer and a consumer
Consumer in application A is started and watches for new messages (i.e. jumps to the highest offset) on topic 2
Application A creates a message on topic 1
Application B processes the message from Application A and puts it onto topic 2
The consumer on application A takes 5 seconds to notify  me of a message on topic 2
If I split application A into 2 separate applications(1 consumer & 1 producer) the notification of a message on topic 2 to my consumer occurs within milliseconds
We have simplified this to 1 topic, 1 partition, 1 broker

In the code below, if (consumer.Consume(out var msg, TimeSpan.FromSeconds(1))) does not notice the new message for a long time, even though I have an acknowledgement that the message has been posted.

How to reproduce (Comsumer code)
================

```
using (var consumer = new Consumer<string, string>(config, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
            {
                consumer.Assign(new List<TopicPartitionOffset>
                {
                    new TopicPartitionOffset(listenTopicName, 0, currentoff)
                });
                while (true)
                {
                    if (consumer.Consume(out var msg, TimeSpan.FromSeconds(1)))
                    {
                        TopicPartition tp1 = new TopicPartition(msg.Topic, msg.Partition);
                        var higoff = consumer.GetWatermarkOffsets(tp1).High;
                        //consumer.Assign(new List<TopicPartitionOffset> { new TopicPartitionOffset(topicName, 0, higoff) });
                        //lastoff = (int)higoff;
                        if (higoff > lastoff && lastoff != -1 || higoff == 0)
                        {
                            isFirst = false;
                        }
                        var offsetVal = (int)higoff;
                        if (!isFirst)
                        {
                            offsetVal = (int)(higoff - 1);
                        }
                        if (msg.Offset == offsetVal)
                        {
                            if (msg.Key == key)
                            {
                                return msg.Value;
                            }
                        }
                        lastoff = (int)higoff;
                        consumer.Assign(new List<TopicPartitionOffset>
                        {
                            new TopicPartitionOffset(msg.Topic, 0, offsetVal)
                        });
                    }
                }
            }
```

Checklist
=========
Please provide the following information:

 - [ ] Apache Kafka version: 0.10.1
 - [ ] Operating system: Ubuntu 16.04.4 LTS

**Comment by idelix** [comment]
Thanks @mhowlett is there any chance you can provide me sftp address where we have visual studio solution that is 26mb in size it sot big to attach in github.

**Comment by idelix** [comment]
Hi @mhowlett sending attached the solution:

[KafkaSlnA.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/1884624/KafkaSlnA.zip)

Please let me know if you need any more details.

**Comment by mhowlett** [comment]
sorry @idelix - i only have the capacity to look at small programs demonstrating likely issues with the library. feel free to paste a small example demonstrating the problem.

**Comment by idelix** [comment]
Thanks mhowlett we will pass on this library for time being and try to use native java instead
