### ISSUE TITLE
Produced messages reordering

### ISSUE THREAD

**Issue by epriale** [confluentinc/confluent-kafka-dotnet#488]
Description
===========
Hi, we are starting using kafka to send data coming form sensors. For every single partition, we would like to have strict ordering of messages.
Now, I am trying to simulate broker and connection faults shutting down the broker and restarting it, 
whike the producer is sending messages.
We have set up these parameters:
                config = new Dictionary<string, object>
                {
                    { "bootstrap.servers", "127.0.0.1:9092"},
                    { "client.id", "kafkaid" },
                    { "max.in.flight.requests.per.connection", 1},
                    { "compression.codec", "lz4"},
                    { "socket.nagle.disable", "true"},
                    { "message.send.max.retries", 10000000},
                    { "batch.num.messages", 1000},
                    { "linger.ms", 200},
                    { "queue.buffering.max.messages", 600000},
                    {"retry.backoff.ms", 1000},
                            { "acks", "all" },
                            { "message.timeout.ms", 400000},                     
                            { "request.timeout.ms", 400000}                       
                };

We are receiving data from a consumer in order to check that the message ordering does not cahnge.
Every time we stop and restart the broker, we receive a lot of messages out of order, also if the broker down time is lesser than the request timeout (400 sec).
According ti the documantation, if I set max.in.flight.requests.per.connection to 1 I should not ave reodreing problems.
Wiche are the correct parameters to get a "good" message ordering?
We are using Confluent.Kafka.0.11.4
Thanks a lot!!!
Ettore

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version:
 - [x] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by vchekan** [comment]
I can not see any integration tests which would restart broker. Am I missing it, or there is none?

**Comment by mhowlett** [comment]
we have system tests that verify the operation of librdkafka under various broker restart scenarios (but not specifically for the dotnet client). and correct, integration tests don't cover this.

**Comment by edenhill** [comment]
@epriale That is correct.
`message.timeout.ms` and `message.send.max.retries` sets the upper bound on time and retry count for message delivery.

More info here:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability

**Comment by epriale** [comment]
Thanks
