### ISSUE TITLE
Performance issue of AdvancedProducer code example provided by Confluent Kafka .NET 

### ISSUE THREAD

**Issue by PingPongSet** [confluentinc/confluent-kafka-dotnet#495]
Description
===========

The code in the link below wass modified to send 50 messages of 100 characters. It takes around 50 seconds, which is slow, compared to 300 message/second on other brokers (300 * 50 = 15 000 messages for 50 seconds, 50 vs 15,000).

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdvancedProducer/Program.cs

How to reproduce
================

Basically, the code below is repeated to run 50 times

   var deliveryReport = producer.ProduceAsync(topicName, "", messageWith100Characters);
   var result = deliveryReport.Result; // synchronously waits for message to be produced.

Default settings from both Kafka and ZooKeeper are used, both of which are running on Windows 7.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.4 https://www.nuget.org/packages/Confluent.Kafka/0.11.4
 - [x] Apache Kafka version:   kafka_2.11-1.1.0.tgz 
 - [x] Client configuration: .NET CORE 2
 - [x] Operating system: Windows 7
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by mhowlett** [comment]
Maybe try setting `linger.ms` to 1. Generally, you should avoid synchronous delivery (async will give much higher performance, > 200 000 msg/s). I'm not sure why the performance is so slow, but if it's not linger.ms, I think it's probably something related to the broker. Note also that we don't support the broker/zookeper on Windows. Have you tried running these in a linux VM?

**Comment by PingPongSet** [comment]
> "async will give much higher performance, > 200 000 msg/s"

 is it the speed on Linux VM?

What Linux VM is best for Kafka? For example, the version that is used by Linkedin?

**Comment by gccmbr** [comment]
> What Linux VM is best for Kafka? For example, the version that is used by Linkedin?
> To run Linux on Windows 7, what VM and Linux can you recommend?

Google is a great source for such searches.  This is the wrong forum.
