### ISSUE TITLE
Exception upon creating Producer or Consumer in experimental branch with dotnet docker

### ISSUE THREAD

**Issue by louisledev** [confluentinc/confluent-kafka-dotnet#497]
Description
===========
when starting a simple consumer or producer using the Confluent.Kafka version 1.0.0-experimental-2 nuget package, I got an exception when running the code in docker image based on docker image from Microsoft (microsoft/dotnet:2.0-runtime). 
When starting the exact same program directly in Windows with dotnet core 2.0.5 runtime, I don't get the issue.

Unhandled Exception: System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
   at Confluent.Kafka.Impl.LibRdKafka.SetDelegates(Type nativeMethodsClass)
   at Confluent.Kafka.Impl.LibRdKafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Producer..ctor(IEnumerable`1 config)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer)
   at Confluent.Kafka.Examples.SimpleProducer.Program.Main(String[] args) in /app/Program.cs:line 42

How to reproduce
================
extract the provided zip file 
[SimpleProducer.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/1876972/SimpleProducer.zip) in a directory,
then, in console, execute:
$> docker build -t simpleproducer .
$> docker run simpleproducer

Checklist
=========

Please provide the following information:

 - [X] Confluent.Kafka nuget version: 1.0.0-experimental-2
 - [X] Apache Kafka version: 1.0.0 
 - [ ] Client configuration:
 - [x] Operating system: Linux (cf base docker image is microsoft/dotnet:2.0.5-runtime)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by louisledev** [comment]
No. 0.11.4 works fine. But I had the same issue with https://www.nuget.org/packages/Confluent.Kafka/0.11.3-ci-303
I actually really need to get access to the custom headers, so based on your comment in https://github.com/confluentinc/confluent-kafka-dotnet/issues/472, I tried first with the above package, but ran into the issue. Saw that the experimental branch also provided support for custom headers, but got the same issue.

**Comment by louisledev** [comment]
(sorry, got confused with buttons and closed by mistake, so reopened)

**Comment by mhowlett** [comment]
interesting. in order to implement headers and custom timestamps, we've changed how the produce method calls into librdkafka, seems like it might be related to that. I've had no problems running under dotnet core though (on any platform). I will try to reproduce by following your steps, though don't have a chance immediately. thanks a lot for reporting.

**Comment by MartinCui** [comment]
I encountered exactly the same exception when trying to use "1.0.0-experimental-2" in docker based on "microsoft/aspnetcore:2.0" image.
While it runs well when on my Windows based on .net core 2.0 environment.
Same as @louisledev we need this header support very much so thought it's good to give "1.0.0-experimental-2" a try.

**Comment by mhowlett** [comment]
thanks for the confirmation @MartinCui - noted.

**Comment by ojinxy** [comment]
Has this issue been fixed in 1.0.0-experimental-4. I am getting a similar issue.
