### ISSUE TITLE
Application breaks due to an exception if a consumer is polling when it is disposed

### ISSUE THREAD

**Issue by mindcrash** [confluentinc/confluent-kafka-dotnet#498]
Description
================

When a consumer is polling while being disposed an exception is thrown:

````
Unhandled Exception: System.ObjectDisposedException: kafka handle is closed
   at Confluent.Kafka.Impl.SafeHandleZeroIsInvalid.ThrowIfHandleClosed()
   at Confluent.Kafka.Impl.SafeKafkaHandle.ConsumerPoll(Message& message, IntPtr millisecondsTimeout)
   at Confluent.Kafka.Consumer.Consume(Message& message, Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(Message`2& message, Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Poll(Int32 millisecondsTimeout)
   at Cloud.StreamingServices.Program.StatisticsService.<StartAsync>b__2_1() in C:\repos\streamingservices\statistics\src\Cloud.StreamingServices\Program.cs:line 367
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
````

Which, ofcourse, is completely understandable.

However, the only current way to make sure that disposing the consumer does not break the application which is hosting the consumer is by putting it into a very costly exception handler.

This could be addressed by exposing a public IsDisposed property which is flagged when Dispose is called, which makes the code mentioned below look like this instead:

```
                var config = new Dictionary<string, object>()
                {
                    { "bootstrap.servers", "127.0.0.1:29092" },
                    { "group.id", "consumers" }
                };                

                consumer = new Consumer<Ignore, byte[]>(config, null, new ByteArrayDeserializer());
		consume.Subscribe("topic");

                consumer.OnMessage += (o, m) => {
                    Console.WriteLine("Message received!");
                };

                await Task.Factory.StartNew(() => {
                    while(!consumer.IsDisposed)
                       consumer.Poll(10);
                });
            }
````

How to reproduce
================

Disposing the consumer (e.g. when responding to the CancelKeyPress event) when the following code is running will trigger the exception mentioned above

```
                var config = new Dictionary<string, object>()
                {
                    { "bootstrap.servers", "127.0.0.1:29092" },
                    { "group.id", "consumers" }
                };                

                consumer = new Consumer<Ignore, byte[]>(config, null, new ByteArrayDeserializer());
		consume.Subscribe("topic");

                consumer.OnMessage += (o, m) => {
                    Console.WriteLine("Message received!");
                };

                await Task.Factory.StartNew(() => {
                    while(!stopped)
                       consumer.Poll(10);
                });
            }
````

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version: 0.11.4
 - [X] Apache Kafka version: 1.1.0
 - [X] Client configuration: See above
 - [X] Operating system: Windows 10 (consumer), Linux (broker)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts 
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks for the feedback @mindcrash - I'll think this through for the 1.0-experimental branch.

**Comment by mhowlett** [comment]
there's a race condition between checking `IsDisposed` and the `Poll` call, so i don't think the usage above is reason enough to add an `IsDisposed` property. You'll need to add some more book-keeping at the application level that ensures the poll loop exits before the consumer is disposed to solve this properly. I will think scenarios related to this through in some more detail - there may be scope here to make the library more straightforward to use.

**Comment by mhowlett** [comment]
tracking this in #577. note also that `Consumer.Poll` has been removed in `1.0-experimental-6` - we will only support `Consumer.Consume` in 1.0 (and the signature has changed).
