### ISSUE TITLE
How to limit the number of TCP connections using config

### ISSUE THREAD

**Issue by nkanand** [confluentinc/confluent-kafka-dotnet#499]
Description
===========
Using Confluent Kafka .NET library. With default configuration, Kafka producer opens up about 15k TCP connections. This is not needed for our use case. How to limit the number of TCP sockets using configuration?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
how many brokers do you have?
how many producers / consumers are you constructing? (you generally only need one per process). 

also, refer to:
https://github.com/edenhill/librdkafka/issues/825

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-broker-tcp-connections
