### ISSUE TITLE
Queries - .Net Client lirdkafka settings

### ISSUE THREAD

**Issue by raghavrkapoor** [confluentinc/confluent-kafka-dotnet#502]
Description
===========
Hi Team

I am in process of fine tuning the application for performance and resilience built with Confluent .net Kafka client and for the same have a couple of queries related to use of librdkafka settings in .net client. 

1. I have a scenario in which I run multiple windows services (each for a different requirement) and each windows service hosts multiple Consumers (running on different threads) and Producers connecting to the same brokers. Message is consumed by the consumer from a topic and as part of the processing produces an event on a different topic. If I apply following settings only for one producer will they be applied to other consumers and producers running in the same process?   
"broker.address.ttl": 30000,
"socket.blocking.max.ms": 10,
"socket.nagle.disable": true

My understanding is that above settings are applied at each producer/consumer level as each producer and consumer will have its own dedicated channel to communicate with brokers making the settings independent of other consumers, producers within or outside the same process. For eg; 
if "broker.address.ttl" is set to 30000 for Consumer1 and 1000 for Consumer2 then, for Consumer1 broker address will be resolved every 30000ms and for Consumer2 broker address will be resolved 
every 1000ms. 

Please confirm. 

2. **group.id** setting - I understand the use of this setting for a Consumer. What is the significance of this property for a producer?
librdkafka settings documentation show its applicable for both Consumer and Producer. 
group.id	*			Client group id string. All clients sharing the same group.id belong to the same group. Type: string
Taken from from https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

3. Which documentation of librdkafka settings is valid? I have been following the github settings at (https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) but my colleague shared a different link with me today https://docs.confluent.io/2.0.0/clients/librdkafka/CONFIGURATION_8md.html). There are differences in default values for the settings on the 2 pages. eg; queue.buffering.max.ms default value is 1000 on confluent page and 0 on github page. Based on overall activity in this forum and my testing github settings looks to reflect the correct state. May be Confluent documentation can be synced. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.4
 - [ ] Apache Kafka version: 
 - [ ] Client configuration: .Net Framework 4.6.1
 - [ ] Operating system: Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

Regards
Raghav.

**Comment by mhowlett** [comment]
some notes:
- each client (producer or consumer) is independent, settings are not shared in any way.
- you should generally have one consumer / producer per process since each client (in the current librdkafka implementation) opens a connection to all brokers, and on most hardware is performant enough to saturate the network. Farm out messages consumed to different threads if required.
- `group.id` is not a valid setting for a producer.
- use configuration settings from https://github.com/edenhill/librdkafka that corresponding to the version of librdkafka you're using (master currently the same as 0.11.4, which is the current release). On our TODO list is document all this on the dotnet client website so you don't need to go jumping between repos to work out what's going on.

**Comment by gccmbr** [comment]
@mhowett thank you for the summary of recommendations for this scenario. Can I get a quick general opinion on my kafka consumer setup? 

 I have a use case where I have several hundred clients running concurrently on one server running in one application.  Should I be concerned and/or consider a redesign or do you think my concuurency plan can handle several hundred consumers? 

Thank you for any opinions!

**Comment by raghavrkapoor** [comment]
Thanks Matt for the clarifications. All of our implementations have one consumer per process only except 1 where also we run maximum of 2 consumers in a process. We decided to use it this way as we were consuming exactly similar information but from 2 different topics (for 2 different clients).

**Comment by mhowlett** [comment]
@raghavrkapoor - sounds good. 

@gccmbr - without knowing more, it sounds like you might be using the consumer in a way that wasn't intended. 

more info on number of connections:
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-broker-tcp-connections

**Comment by gccmbr** [comment]
@mhowlett Thank you for the link.  Yes,  unintended use case sounds about right with my designs... I will keep you update with the performance results.  Experimental-1 using custom timestamps is working out great so far and seems to outperform 0.11.3 so far from a producer perspective.  


 an interesting
