### ISSUE TITLE
Producing with Powershell

### ISSUE THREAD

**Issue by JasonatCU** [confluentinc/confluent-kafka-dotnet#505]
Description
===========
I'm just looking for guidance or suggestions on what I could be doing wrong.  I've tried to port some of the Advanced Producer example for C# to Powershell.  

I'm trying to produce with Powershell, by referencing Confluent-kafka-dotnet.  It hangs when executing the producer System.Threading.Tasks.Task object.

I may be going about this all wrong, but I hope I'm getting close.

How to reproduce
================
[Reflection.Assembly]::LoadFile("C:\scripts\Powershell\Kafka\librdkafka\Confluent.Kafka.dll")

$BrokerList = "192.168.1.25:9092"
$Topic = "test"
$alert = "Testing from Powershell Function"

$config = New-Object "System.Collections.Generic.Dictionary``2[System.String,System.Object]"
$config.Add('bootstrap.servers',$BrokerList)

$enc = [System.Text.Encoding]::UTF8
$stringserializer = [Confluent.Kafka.Serialization.StringSerializer]::new($enc)

$producer = [Confluent.Kafka.Producer]::new($config, $null, $stringserializer)
$deliveryReport = $producer.ProduceAsync($Topic, $null, $Message)
$deliveryReport

When you run this code, $deliveryReport hangs, but netstat -an on both the Kafka/Zookeeper server and the producer show connected to each other on 9092 as expected. 

Kafka Server is on Ubuntu 1604 built using these directions, no changes https://devops.profitbricks.com/tutorials/install-and-configure-apache-kafka-on-ubuntu-1604-1/ .

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 11.4
 - [ ] Apache Kafka version: 2.11
 - [ ] Client configuration: Windows 10 1709 Producer/Powershell 5.1
 - [ ] Operating system: Windows 10 1709 Producer, Ubuntu 1604 Kafka

**Comment by mhowlett** [comment]
i'm not familiar with powershell (in particular how async stuff would work). Can you call .Result? or perhaps you could try a variant of produceasync that doesn't return a task (and takes a delivery handler instance instead).

If you get an example working, feel free to paste here or open a PR! it would be good to include in the repo.

**Comment by JasonatCU** [comment]
$deliverReport.Result also hangs.  Seems any method I run hangs, but I can view the properties of the object.  If I step through with a debug when I execute $deliveryReport I get to line 454 in Producer.cs when I get sent back to the shell where it appears to hang.

454 -- Produce(topic, val, 0, val?.length ?? 0, key, 0, key?.length ?? 0, null, RD_KAFKA_PARTITION_UA, true);

I'm thinking it's either the way I'm executing the System.Threading.Tasks.Task object, or an error on the encoding.  I'll work on enabling debug and getting more logs on the kafka server.

**Comment by JasonatCU** [comment]
I've made quite a few changes to my code above now.  I've actually initialized $producer object with the proper overloads in my new code.  Now I've figured out that I actually have an issue with my kafka server that I need to work out before troubleshooting this code any further.  I'll keep you guys updated with what I find.

**Comment by john159753** [comment]
@JasonatCU Did you ever get anywhere with this?
I am am experiencing the same issue.

-John

**Comment by mhowlett** [comment]
Guessing this issue is related to #545 which I'll be investigating further relatively soon. please try again after #545 has been resolved. I do find it odd that `wait` works, but `result` doesn't.

**Comment by zarochi** [comment]
Just wanted to confirm that the updated code in #545 seems to fix the issue.

**Comment by john159753** [comment]
Thank you @mhowlett !
