### ISSUE TITLE
How to determine whether the Kafka link is normal in the code

### ISSUE THREAD

**Issue by songjianhua678** [confluentinc/confluent-kafka-dotnet#511]
Description
===========

How to determine whether the Kafka link is normal in the code

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
I've added a note on this here: https://github.com/confluentinc/confluent-kafka-dotnet/wiki#can-i-use-the-net-client-to-check-if-my-kafka-cluster-is-down
