### ISSUE TITLE
Question: connection state

### ISSUE THREAD

**Issue by songjianhua678** [confluentinc/confluent-kafka-dotnet#514]
Description
===========

Is there a way to determine (in a synchronous fashion) the current state of a session?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
i'm unsure what you mean by session? the client maintains connections to all brokers. If there are connectivity problems, it attempts to reconnect / retry behind the scenes. This discussion may be relevant: https://github.com/confluentinc/confluent-kafka-dotnet/wiki#can-i-use-the-net-client-to-check-if-my-kafka-cluster-is-down
