### ISSUE TITLE
PartitionEOF is raised while messages are still being received

### ISSUE THREAD

**Issue by mindcrash** [confluentinc/confluent-kafka-dotnet#516]
Description
===========

Within a large batch of message (10K+) I noticed PartitionEOF is raised erratically while messages are still coming in. Is this expected behavior? 

After doing some research I noticed it could have something to do with current message offset and current high watermark offset as reported by the consumer having a delta of 1 at exactly the same moment the event is triggered.

I actually kind of hope this is a bug because a critical piece of historical batch aggregation code using Rx is depending on this event being triggered only once to flush the last set of messages through my HistoricalScheduler powered observable...

How to reproduce
================

* Wire up the PartitionEOF event with a event handler
* Produce about 10K of messages 
* Notice the event is raised erratically when messages are processed.

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version: 0.11.4
 - [X] Apache Kafka version: 1.1.0
 - [X] Operating system: Windows 10

**Comment by mindcrash** [comment]
Well, seems this is indeed expected behavior. 

Would be a good idea to document it as such, because all the examples I've found clearly state that "the end of the partition was reached".

Well, seems I need to find another way to get this working :/

**Comment by edenhill** [comment]
A partition end offset is a moving target.

Partition EOF will be emitted each time the consumer reaches the end of a
partition.
If no new messages are produced then this will only happen once per
partition,
but if new messages are produced after EOF has been reached the consumer
will consume the new messages and possibly reach the new partition end and
thus emit a new Partition EOF.



2018-04-24 19:13 GMT+02:00 mindcrash <notifications@github.com>:

**Comment by mindcrash** [comment]
Yes, noticed that. Since we have a finite data set we went with the most simple solution of giving each row a set based offset at the ingestion point to later on check if all items are processed.
