### ISSUE TITLE
Sync Message publishing

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#517]
Description
===========

I will like to synchronously produce a message to the producer. I understand that I can call flush after invoking ProduceAsync. I will like to control this behavior through properties. I tried setting the linger.ms to 0 but that still did not publish the message to Kafka right away. Can I get a confirmation which properties I can tweak to achieve this behavior?

Thanks,

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
`Wait()` on the returned task (or get the value of `Result`), though note that synchronous producing will be slow. On windows, you'll also need to adjust `socket.blocking.max.ms` - see the discussion midway down #501
