### ISSUE TITLE
GenericRecord to JSON string?

### ISSUE THREAD

**Issue by ehausig** [confluentinc/confluent-kafka-dotnet#518]
Hi, I'm unclear on how to dynamically extract the original JSON document from an Avro message's value. For example:

```
using (var consumer = new Consumer<string, GenericRecord>(config,
                                                          new AvroDeserializer<string>(),
                                                          new AvroDeserializer<GenericRecord>()))
{
    consumer.Consume(out Message<string, GenericRecord> message, TimeSpan.FromSeconds(100));
    var someValue = message.Value; // <<<<< how to get doc as json string?
}
```

If I cast message.Value.ToString() in the above example, I get a mashup of schema and document values, rather than the JSON doc, that looks like this:

`{Schema: {"type":"record","name":"myrecordname","namespace":"mynamespace","fields":[{"name":"message_id","type":"string"},{"name":"message_type","default":null,"type":{"type":"enum","name":"messagetype_enum","namespace":"mynamespace","symbols":["EXAMPLE1","EXAMPLE2","EXAMPLE3"]}}, ...`

I found the message.Value.TryGetValue(string fieldname, out object result) method, but this appears to be for grabbing individual values from the document.

Thanks

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.4
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system: macOs
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
The `GenericRecord` implementation is here: https://github.com/confluentinc/avro/blob/confluent-fork/lang/csharp/src/apache/main/Generic/GenericRecord.cs ). It appears as though there is no way to iterate through, or access the `content` in it's entirety. This appears to also be the case in the java implementation: https://github.com/confluentinc/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java#L178 . This seems odd to me as I'd expect this is something you'd want to be able to do. Transferring this issue over to https://github.com/confluentinc/avro/issues/8

**Comment by darknasty** [comment]
I have a similar question but I am using a SpecificRecord and trying to get it to json.  I have been reviewing the ConsumerResults to see if there is a nice result object I can access but don't see it.

**Comment by m1nkeh** [comment]
never really got a satisfactory answer to this one.. i rolled my clunky parser in the end, shudder..
