### ISSUE TITLE
Avrogen does not preserve JSON property order in generated class _SCHEMA property

### ISSUE THREAD

**Issue by comdw** [confluentinc/confluent-kafka-dotnet#519]
I noticed that if I start with avsc like this:
```
{
  "name": "MyField",
  "type": "int",
  "doc": "My numeric field"
}
```
In the generated .cs class the "doc" property comes before the "type" property.  Yet when the schema is registered through the schema registry the properties have the original order again.  I guess avrogen is coded with a particular ordering that differs slightly to the confluent schema registry backend.

I'm not sure whether this really counts as a bug in avrogen, I suspect the vanilla Apache one behaves the same way, and the order technically is not relevant, but its annoying that this means I can't directly compare if a local type's schema is the same as a schema registered in the registry.  The reason I'd like to do this is to enforce that a client is using the latest version of a schema.

Is there a built in way to compare two avro schemas for equivalence that I'm missing?  I note that the Confluent.SchemaRegistry.Equals method uses a direct string comparison for the two schema strings so I wouldn't be the first to make the assumption that the order is retained.

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version: 0.11.4
 - [X] Apache Kafka version: 1.0
 - [X] Operating system: Windows 10

**Comment by mhowlett** [comment]
Have you tried creating `Avro.Schema` references using `Avro.Schema.Parse` and then using `RecordSchema.Equals`?

using string comparison in the SR client was a deliberate decision which I believe is safe under normal usage.

**Comment by comdw** [comment]
Thanks, yes in fact it seems I can use `MyType._SCHEMA.Equals(Avro.Schema.Parse(schemaStringFromRegistry))`
