### ISSUE TITLE
 consumer.OnStatistics event.

### ISSUE THREAD

**Issue by Dexu5** [confluentinc/confluent-kafka-dotnet#52]
I just started using Confluent Kafka and I appreciate the efforts of developers.
I would like to print the consumer lag of a consumer and also display the list of consumers. I tried using `consumer.OnStastistics` event and it returns the Json data which has consumer lag and some more info. 
Do we have any way by which I can fetch those ?

Regards,
Dexu5

**Comment by edenhill** [comment]
consumer_lag is reported per consumed partition, so scan the returned JSON object for:
`topics[..].partitions[..].consumer_lag` (pseudo path syntax) according to the layout described here:
https://github.com/edenhill/librdkafka/wiki/Statistics

**Comment by Dexu5** [comment]
Also, Is there any way to display Kafka Consumer list ? 


Regards,
Dexu5
