### ISSUE TITLE
ssl config will lost message and it happens  high frequency。

### ISSUE THREAD

**Issue by liaodawee** [confluentinc/confluent-kafka-dotnet#524]
Description
===========
our project need to use ssl config to  producer and consumer .  after ssl config is OK .
i use C# procuder  to send message ,and i find that usually the message will lost ..
we each time send 1000 messages and lost about 5-10 messages.

How to reproduce
================
Here is the Producer settings used (c#).
we use ssl config and ssl config below we find it from librdkafka document.
 [https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka](url)
`var config = new Dictionary<string, object> {
                {
                    "bootstrap.servers", "192.168.142.128:9092:9092"
                },
                { "security.protocol","ssl"},
                { "ssl.key.password","kafka1234567"},
                { "ssl.key.location","cert/client_acrlnx002_client.key"},
                { "ssl.certificate.location","cert/client_acrlnx002_client.pem"},
                { "ssl.ca.location","cert/ca-cert"}
            };`
 

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3.0
 - [x] Apache Kafka version: kafka_2.11-1.0.0
 - [x] Client configuration:   { "security.protocol","ssl"},
                { "ssl.key.password","kafka1234567"},
                { "ssl.key.location","cert/client_acrlnx002_client.key"},
                { "ssl.certificate.location","cert/client_acrlnx002_client.pem"},
                { "ssl.ca.location","cert/ca-cert"}
 - [x] Operating system: WIN10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by liaodawee** [comment]
thanks for help

**Comment by mhowlett** [comment]
have you looked at the `Error` field in the delivery report for each message?

if you provide a more complete example we can comment further.
