### ISSUE TITLE
AvroSerializer doesn't dispose SR client

### ISSUE THREAD

**Issue by TheMidgardWatcher** [confluentinc/confluent-kafka-dotnet#525]
Description
===========
I'm testing your brand new Avro serialization and Schema Registry functionality.

I use producer with avro key/value serializer wrapped in 'using' block.  
I'm getting such error on second try to produce something, even though all resources was disposed and recreated after previous produce call:

`Key AvroSerializer schema registry client was configured via both the constructor and configuration parameters.`

Am I doing something wrong?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please provide your code

**Comment by mhowlett** [comment]
you would be passing in an `ISchemaRegistry` into the constructor as well as specifying schema registry related configuration parameters in the producer config dictionary. you can only do one or the other.

**Comment by TheMidgardWatcher** [comment]
Thanks @mhowlett , I've already tried to pass `ISchemaRegistryApi ` to serializers' constructors - works like a magic! But previously I was passing `schema.registry.url` config parameter into producer only.
My solution is too heavy to share, but I could try to reproduce mentioned issue in a 'light' example application.
