### ISSUE TITLE
Query related to Committed Offsets

### ISSUE THREAD

**Issue by raghavrkapoor** [confluentinc/confluent-kafka-dotnet#526]
Description
===========

I have a query related to fetching and committing of offsets from the brokers. This is a question to clarify my understanding:

My understanding is that .net client after fetching the committed offsets (from brokers) for the consumer group keeps them in memory. It reads from memory and when offsets are committed by consumers it commits them to the brokers and updates in memory. 

What will happen in following scenario (topic with 2 partitions - 0 & 1):
1. Start Consumer1 - subscribes to both the partitions (0 & 1). 
2. Start Consumer2 (same consumer group as Consumer1). 
3. Partitions revoked for Consumer1. 
4. Consumer1 is assigned Partition0 ---- **Query:** Will the committed offsets fetched from brokers at this stage for partition0 or the one's available in memory at step 1 will be used?
5. Consumer2 is assigned Partition1. 

**Question:** Are the offsets fetched from the brokers every time when the partitions are assigned?
If not, then is there a way to force the consumers to always fetch the committed offsets from broker whenever the partitions are assigned? Please help me understand how and when the committed offsets are fetched from the brokers. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.4
 - [ ] Apache Kafka version: 0.11.__
 - [ ] Client configuration: 
 - [ ] Operating system: Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
Just quickly - if you call `Assign` with a collection that includes a particular `TopicPartition`, the consumer's current position for that topic/partition will be set to the last committed offset for that partition and messages will be read linearly from there (i know you ask more questions, but hopefully this is enough)
