### ISSUE TITLE
Manual commit hangs indefinitely

### ISSUE THREAD

**Issue by treziac** [confluentinc/confluent-kafka-dotnet#53]
When I launch Advanced Consumer in consume mode (manual offset commit), it hangs on
`
            IntPtr rkev = LibRdKafka.queue_poll(cQueue, -1/*infinite*/);
`
in SafeKafkaHandle.commitSync

The offset are acutally commited when calling
`LibRdKafka.commit_queue(handle, cOffsets, cQueue, dummyOffsetCommitCb, IntPtr.Zero);` 

It works well on Poll mode. Setting the timeout to something else than infinite will also works (without commit delivery message)

Also, doc says that Consumer.OnOffsetCommited is raised for all commits (manual and automatic) but we disable it in commitSync with the dummyCallback
Removing the callback (`LibRdKafka.commit_queue(handle, cOffsets, IntPtr.Zero, null, IntPtr.Zero);` and removing the rest) and register to OnOffsetCommit works, but we have to wait a poll to get the offset commit then

**Env:** 
Windows 10 x64 on 0.9.4.x and master branch

**Comment by edenhill** [comment]
commitAsync() requires a newer version of librdkafka, which will be released shortly.
In the meantime you'll either need to build librdkafka yourself, or grab one of the DLLs from [here](https://ci.appveyor.com/project/edenhill/librdkafka/build/job/ybrmcbg64ox1k5a4/artifacts) to replace the one currently provided by RdKafka.internal

**Comment by treziac** [comment]
Links directrly to my other question then
Working ok with 0.9.4-rc1, thanks

**Comment by edenhill** [comment]
Great!
Did you use the DLLs I linked or did you build your own?

**Comment by treziac** [comment]
Linked one (but from Release artifacts). I build librdkafka some times ago but on a linux. Did not try the recent win32 changes on your repo yet.
