### ISSUE TITLE
Getting Confluent.Kafka.KafkaException: Broker: Message size too large

### ISSUE THREAD

**Issue by xs2bharat** [confluentinc/confluent-kafka-dotnet#532]
Description
===========
I followed multiple links online for sending large message to kafka but still getting this error.

exception: 
Confluent.Kafka.KafkaException: Broker: Message size too large
    at Confluent.Kafka.Producer.Produce(String topic, Byte[] val, Int32 valOffset, Int32 valLength, Byte[] key, Int32 keyOffset, Int32 keyLength, Nullable`1 timestamp, Int32 partition, Boolean blockIfQueueFull, IDeliveryHandler deliveryHandler)
   at Confluent.Kafka.SerializingProducer`2.Produce(String topic, TKey key, TValue val, Nullable`1 timestamp, Int32 partition, Boolean blockIfQueueFull, IDeliveryHandler`2 deliveryHandler)
   at Confluent.Kafka.SerializingProducer`2.ProduceAsync(String topic, TKey key, TValue val, IDeliveryHandler`2 deliveryHandler)
   at Confluent.Kafka.Producer`2.ProduceAsync(String topic, TKey key, TValue val, IDeliveryHandler`2 deliveryHandler)

Kafka broker settings:

message.max.bytes=10000000
replica.fetch.max.bytes=10485760
fetch.message.max.bytes=10000000

Message size is 1.1 mb

Not sure if i am missing any settings.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.4
 - [ ] Apache Kafka version: 0.11.0.1
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by xs2bharat** [comment]
To solve above issues, i was trying to add "max.request.size" into producer config but for some reason, confluent packages was not able to instantiate producer client. But adding "message.max.bytes" to producer client did solved the above error, which is weird because this setting is already configured on broker.

**Comment by DHirani** [comment]
I am getting the same error, how was this resolved?

**Comment by Caskia** [comment]
You need to set the message.max.bytes at broker side

**Comment by wangjia184** [comment]
```
            var config = new Dictionary<string, object>
            {
                { "bootstrap.servers", AppConfig.Kafka.Brokers },
                { "message.max.bytes", 1024*1024*10 }, // https://github.com/confluentinc/confluent-kafka-dotnet/issues/532
            };
            log.DebugFormat("KafkaProducer connecting to `{0}`", config["bootstrap.servers"]);
            _producer = new Producer<byte[], byte[]>(config, new ByteArraySerializer(), new ByteArraySerializer());
```

**Comment by michael-elly** [comment]
I have the same issue... I have increased the message.max.bytes and replica.fetch.max.bytes on the broker side. But I don't see what I need to configure on the producer config on Confluent.Net. There is no message.max.size property (or anything similar to it) on the ProducerConfig class object.

**Comment by atakanertrk** [comment]
@michael-elly 
you can find MessageMaxBytes property in ProducerConfig
