### ISSUE TITLE
Question: Confluent.Net and health check?

### ISSUE THREAD

**Issue by kuskmen** [confluentinc/confluent-kafka-dotnet#533]
Hi guyes, this is question basically, I tried to enter slack chat, but then I realized I need to contact administrator of the workspace, but I don't know who it is so anyway, I will ask here.

We are building microservices in our company and we are using Kafka for streaming bus so my and one of my colleague thought about creating some base health check for Kafka, like we did for other services in our tech stack (SQL,Mongo, Aerospike etc.), so each new service that has dependency of kafka will be using it.

My point is, is there something that I can use in confluent.net library to quickly check if Kafka is present and running?

Regards,
kuskmen

**Comment by mhowlett** [comment]
You could perhaps use `GetMetadata` and verify that you get a response in reasonable time. You might also find some of the information provided by `OnStatistics` useful https://github.com/edenhill/librdkafka/wiki/Statistics

**Comment by kuskmen** [comment]
Thanks for the fast response, I will surely take a look.

Regards,
kuskmen

**Comment by kuskmen** [comment]
@mhowlett  I did check that suggestions you gave me, however I was hoping for something that does need to introduce consumer/producer, cause they might be lazily evaluated on premise while typical health check will be called every few seconds from the beginning of the application lifetime.

**Comment by rnpridgeon** [comment]
@kuskmen, prehaps setting up some sort of monitoring infrastructure is more inline with your needs. 

Kafka also a variety of metrics via JMX which you can use to evaluate the health of your cluster without adding additional clients. 

https://kafka.apache.org/documentation/#monitoring

Your .NET clients may leverage the OnStatistics event handler to expose metrics specific to the clients themselves. 

https://github.com/edenhill/librdkafka/wiki/Statistics

Together this should give you a fairly cohesive view of the cluster's health from which you can set up various alerts and such.

**Comment by kuskmen** [comment]
Hi @rnpridgeon , I decided to go with Burrow for health checking kafka, statistics I will use for sure, but when it comes to adding monitoring.

Thank you very much for the help guys, you can close this one :)
