### ISSUE TITLE
[SchemaRegistry] GenericSerializerImpl cannot use one schema for multiple topics

### ISSUE THREAD

**Issue by NikolayDekov** [confluentinc/confluent-kafka-dotnet#536]
Description
===========
Dictionary<string, int> schemaIds  throws exception because item with the same key is added while trying to serialize data for more than one topic with the same writerSchemaString

How to reproduce
================
Bring up one Producer<TKey, TValue> with ISerializer<GenericRecord> and try to send data to more than one topic

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.4
 - [ ] Apache Kafka version: 0.11.4
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks @NikolayDekov - you're right, the logic doesn't consider that the producer may be producing to more than on topic. we need to fix this.

**Comment by NikolayDekov** [comment]
Hi, @mhowlett can you provide ETA on the fix, because i will need this functionality soon. I can help with the fix if needed.

**Comment by mhowlett** [comment]
@NikolayDekov - feel very free to open a PR :-) and if it's good, I'll review/merge it right away.

**Comment by NikolayDekov** [comment]
Hi @mhowlett. I have a fix ready, but I have problems pushing to repository. Should I have permissions or something?

**Comment by mhowlett** [comment]
resolved in #538 - thanks for your contribution @NikolayDekov
