### ISSUE TITLE
Idempotent producer not supported

### ISSUE THREAD

**Issue by cmeiklejohn** [confluentinc/confluent-kafka-dotnet#537]
Description
===========

I'm trying to use the idempotent producer option and I'm running into a runtime exception around the configuration parameter not being supported.

How to reproduce
================

```
    var conf = new Dictionary<string, object>
    {
        {"enable.idempotence", "true"}
        // Omitted obligatory connection strings.
    };


    using (var producer = new Producer<Null, string>(conf, null, new StringSerializer(Encoding.UTF8)))
    {
        await producer.ProduceAsync(_topicName, null, message);
    }
```

Generates:

```
System.InvalidOperationException: 'No such configuration property: "enable.idempotence"'
```

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.4
 - [ ] Apache Kafka version: confluentinc/cp-kafka:4.1.0
 - [ ] Client configuration: 
 - [ ] Operating system: Window 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by cmeiklejohn** [comment]
Ah, I see the relevant issue here: https://github.com/confluentinc/confluent-kafka-dotnet/issues/367

**Comment by mhowlett** [comment]
@cmeiklejohn - we have just started design work on this. It's a big job, but in progress.

**Comment by Tenseiga** [comment]
Hello @mhowlett , Is this still progess?

**Comment by mhowlett** [comment]
it's been implemented but not fully reviewed/merged: https://github.com/edenhill/librdkafka/pull/2001

it won't make it in 0.11.6, but it'll be in the release after.

**Comment by raufismayilov** [comment]
Hello everybody.

Has this feature been implemented? Any news on that?

Thanks

**Comment by mhowlett** [comment]
yes, set `EnableIdempotence` to `true` in the producer config.
