### ISSUE TITLE
Consumer OnStatistics without consuming messages

### ISSUE THREAD

**Issue by koushikchitta** [confluentinc/confluent-kafka-dotnet#539]
Description
===========
I have 2 consumers, both belong to same consumer group.  I would like one of the consumer to just do metrics reporting. **Is this possible ?**
I've written a small piece of code to test that and it doesn't seems to be fetching statistics unless I consume the messages from the same consumer code.

How to reproduce
================

           string topic = ConfigurationManager.AppSettings["topic"];
            string bootstrapservers = ConfigurationManager.AppSettings["bootstrap.servers"];

            var config = new Dictionary<string, object>
            {
                { "group.id", topic+"-Consumer" },
                { "bootstrap.servers", bootstrapservers },
                { "statistics.interval.ms", 600 },
                { "auto.offset.reset", "smallest" }
            };

            using (var consumer = new Consumer<string, string>(config, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
            {

                consumer.OnStatistics += (_, json)
                    => Console.WriteLine($"Statistics: {json}");

                consumer.Subscribe(topic);

                while (true)
                {
                    Message<string, string> msg;
                    //if (consumer.Consume(out msg, TimeSpan.FromMilliseconds(100)))
                    //{
                    Thread.Sleep(1000);
                    //}
                }
            }

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [x] Apache Kafka version: 0.10.2
 - [x] Client configuration:
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by koushikchitta** [comment]
using Poll() worked.
Thanks.

**Comment by mhowlett** [comment]
To do what you want, you'd need to set an `OnPartitionsAssigned` handler that does NOT call `Assign` in it otherwise `Poll` will still cause messages to be consumed, which using your settings will also cause offsets to be auto committed because by default `enable.auto.commit` is `true`. Also, note that your other `Consumer` would only be assigned to, and reading from half the partitions.

**Comment by edenhill** [comment]
The contract is that the application MUST call assign() from the OnPartitionsAssigned delegate.
But you can call assign() followed by pause() to avoid consuming anything.

**Comment by edenhill** [comment]
Do note that the paused consumer will not provide much in the sense of interesting metrics. What metrics specifically are you looking to monitor?

**Comment by mhowlett** [comment]
wow - that is not what I would have expected. is there a good reason why subscriptions and assigning/unassigning to partitions are not completely independent?

**Comment by koushikchitta** [comment]
@edenhill  I was interested in consuming **consumer group lag** metrics.

As I understand from wiki and other thread, the consumer lag metrics was just for that specific consumer 
and not that of the whole consumer group. I was looking for a replacement to "ConsumerGroupCommand" provided in Kafka Admin tools.

Is there any way I can achieve this ?

**Comment by edenhill** [comment]
@koushikchitta You can use ListGroups and DescribeGroups for that purpose, but I'm not sure if they're exposed in the .NET bindings yet. @mhowlett ?

**Comment by koushikchitta** [comment]
I see ListGroups is exposed in .NET API and not DescribeGroups.
@mhowlett Are there any plans to add DescribeGroups in near future ?

**Comment by mhowlett** [comment]
`ListGroups` is exposed but limited in that the group member metadata and member assignment data are not interpreted (are provided as byte[]). this api will change in the future (so as to be more useful out of the box for the consumer group case). implementing these is not on my radar in the near term, but it's part of a complete api, so we'll do it at some point.

**Comment by noahdav** [comment]
@edenhill Can you explain more details of how to get the offset information.  I see in `rd_kafka_list_groups `calls `rd_kafka_ListGroupsRequest `but uses the callback to populate the state.  However this info is not returned to the caller only the `rd_kafka_group_info `struct which contains the metadata info but not the lag information.  Can you help us understand how to get this data?

**Comment by edenhill** [comment]
You will need to use committed() to acquire the committed offsets for a groups partitions, but this can currently only be performed with the currently configured `group.id`, so you will need to instantiate a new client for each group, which is not very practical.
We should probably add a lower level API that allows you to fetch offsets by passing a group id

**Comment by koushikchitta** [comment]
@edenhill 

Clarifying on the question. We are trying to understand how to get the following information for a consumer group using librdkafka C API. Below data is retrieved using Apache Kafka Consumergroup Command

`kafka-run-class.bat kafka.admin.ConsumerGroupCommand --zookeeper localhost:2380/tenants/power --describe --group powerconsumer`

```
Group           Topic                        Pid Offset          logSize         Lag 
powerconsumer powertelemetry                 0   803942          809154          5212
powerconsumer powertelemetry                 1   824764          829426          4662 
```
i.e basically the last produced offset on a topic-partition, the last consumed offset on a topic-partition by a group, so that I can calculate the lag on each partition.

As you mentioned `DescribeGroups `should give us the information, But after going through the librdkafka C code, we observed that describegroup information is added as a callback to `ListGroups` and we are not sure how can we retrieve the information from this.

**Comment by koushikchitta** [comment]
Can I compute the consumer group lag by following for each partition ?
`lag =  consumer.QueryWatermarkOffsets().High - consumer.position() ;`

**Comment by edenhill** [comment]
Your solution is *almost* right, you need to use committed() rather than position() since the latter returns the current fetch offset for a running consumer (e.g., its local state).

**Comment by koushikchitta** [comment]
Could not retrieve the committed offsets of a partition using committed(). I see it as -1001.
Is there something I'm missing here ?
I'm using console producer & consumer to produce & receive messages. and following code to compute lag.

both the console consumer and below code uses the same group.id.

`kafka-console-consumer.bat --zookeeper MW45670117:2380 --topic powertelemetry --consumer-property group.id=test123 --consumer-property enable.auto.commit=true
`


```
var config = new Dictionary<string, object>
            {
                { "group.id", groupId },
                { "bootstrap.servers", bootstrapservers },
                //{ "statistics.interval.ms", 600 },
                { "auto.offset.reset", "smallest" }
            };

            using (var consumer = new Consumer<string, string>(config, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
            {
                while (true)
                {
                    var metadata = consumer.GetMetadata(false);
                    List<TopicPartition> topicPartitions = new List<TopicPartition>();
                    foreach (var topicMetaData in metadata.Topics)
                    {
                        if(topicMetaData.Topic == topic)
                        {
                            foreach(var partition in topicMetaData.Partitions)
                            {
                                topicPartitions.Add(new TopicPartition(topic, partition.PartitionId));
                            }
                            break;
                        }
                    }

                    var committedOffsets = consumer.Committed(topicPartitions, TimeSpan.FromSeconds(5));

                    foreach(var committedOffset in committedOffsets)
                    {
                        var logHigh = consumer.QueryWatermarkOffsets(committedOffset.TopicPartition, TimeSpan.FromSeconds(5)).High.Value;
                        var lag = logHigh - committedOffset.Offset.Value;
                        Console.WriteLine(committedOffset.TopicPartition.Partition + " " + logHigh + " " + committedOffset.Offset.Value + " " + lag);
                    }

                    Thread.Sleep(2000);
                }
            }
```
