### ISSUE TITLE
Question: librdkafka version and linking

### ISSUE THREAD

**Issue by treziac** [confluentinc/confluent-kafka-dotnet#54]
Hi,
What is the strategy for branch naming, releases and librdkafka version linking?
In rdkafka-dotnet, the release were named after the librdkafka version included and there was no branch. The version built did not contains all functionalities (lz4 missing for example)

Here, branch 0.9.4.x and release 0.9.4-preview do not seem to target librdkafka 0.9.4-rc1 (Rdkafka.Internal has not been updated)
Are there any directions planned? Continue using separate project RdKafka.Internal, or link source from librdkafka to build automaticaly, or any other method?

**Comment by mhowlett** [comment]
0.9.2-preview had a critical bug and so I wanted to get a nuget package out ASAP as people are using it. However we'd already upped the version number to 0.9.4 as part of preparation for a wider confluent platform release which will be using librdkafka 0.9.4. Unfortunately this was before a nuget package for librdkafka 0.9.4 was ready. This is the what's confusing things here. The naming will work as you would expect going forward except for 0.9.4-preview2. This nuget package is interim and will not be long lived. Sorry for the confusion.

we also plan to add flexibility to reference your own build of librdkafka (however that is not possible at present).

**Comment by ewencp** [comment]
To simplify, the plan is to make versioning match the librdkafka versioning (which we'll also be trying to make match Kafka versioning better as well, up to the point it makes sense given different constraints for clients).

I'm going to close this for now as I think the question has been addressed, but @treziac feel free to reopen if there are remaining questions.
