### ISSUE TITLE
Connecting to Azure Event Hubs using Kafka protocol

### ISSUE THREAD

**Issue by wsilveiranz** [confluentinc/confluent-kafka-dotnet#540]
Description
===========
Hi all, I am trying to use Confluent.Kafka to connect to Azure Event Hubs using the kafka protocol (which was enable a little while ago). Event hubs is only providing SSL channel (e.g. port 9093). I've tried to port the samples using a jaas config to Confluent Kafka, but get the following error:

2018-05-27 04:06:37.042|rdkafka#producer-1|STATE| [thrd:sasl_ssl://kafkahubs.servicebus.windows.net:9093/bootstrap]: sasl_ssl://kafkahubs.servicebus.windows.net:9093/bootstrap: Broker changed state INIT -> CONNECT
7|2018-05-27 04:06:37.211|rdkafka#producer-1|CONNECT| [thrd:sasl_ssl://kafkahubs.servicebus.windows.net:9093/bootstrap]: sasl_ssl://kafkahubs.servicebus.windows.net:9093/bootstrap: Connected to ipv4#40.112.242.0:9093
7|2018-05-27 04:06:37.530|rdkafka#producer-1|BROKERFAIL| [thrd:sasl_ssl://kafkahubs.servicebus.windows.net:9093/bootstrap]: sasl_ssl://kafkahubs.servicebus.windows.net:9093/bootstrap: failed: err: Local: SSL error: (errno: No such file or directory)

How to reproduce
================

- Create an Azure Event Hubs with kafka support [(](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-create-kafka-enabled)
- Create a new Producer with the following configuration:

                   { "bootstrap.servers", {eventhubsFQDN}:90393"},
                    { "security.protocol","SASL_SSL" },
                    { "sasl.mechanism","PLAIN" },
                    { "sasl.username", "$ConnectionString"},
                    { "sasl.password", "{ConnectionStringusingSASToken" },
                    { "debug", "security,broker,protocol" }

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.4
 - [x] Apache Kafka version: Based on Apache protocol 1.0 (Event Hubs with Kafka support)
 - [x] Client configuration: (see broker configuration)
 - [x] Operating system: Windows Server 2016 (client) - Azure (Server)
 - [x] Provide logs (with "debug" : "..." as necessary in configuration) (see description)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by wsilveiranz** [comment]
Hi everyone, please let me know if you I can provide any more information about this issue.

**Comment by mhowlett** [comment]
we don't yet automatically access the trusted root certificates store on windows, so you'll need to specify `ssl.ca.location` and you'll need to get the root CA certs from somewhere. Suggest downloading curl and using the `cert.pem` file from that. for confluent cloud, we also suggest setting `broker.fallback.version` and `api.version.fallback.ms`. I'm not sure of the reason for that (maybe it applies here too) @edenhill can you comment?
 
https://docs.confluent.io/current/quickstart/cloud-quickstart.html#librdkafka

**Comment by mhowlett** [comment]
why would you want to downgrade to the 0.9 protocol feature set?

**Comment by wsilveiranz** [comment]
Great, thanks guys. Will download the cacerts and test it again and report back. I am assuming that the broker.version.fallback and api.version.fallback.ms should be included in the config as well, something like this?
              { "bootstrap.servers", {eventhubsFQDN}:90393"},
              { "security.protocol","SASL_SSL" },
              { "sasl.mechanism","PLAIN" },
              { "sasl.username", "$ConnectionString"},
              { "sasl.password", "{ConnectionStringusingSASToken" },
              { "debug", "security,broker,protocol" },
              { "broker.version.fallback ","0.10.0.0" },
              { "api.version.fallback.ms","0" }

Cheers, Wagner.

**Comment by wsilveiranz** [comment]
It is working! Thanks for your help everyone!

 I am closing this issue now.

Producer sample is here if anyone is interested: [https://github.com/wsilveiranz/EventHubsKafkaSample]()
