### ISSUE TITLE
Consider exposing IConsumer interface on experimental branch

### ISSUE THREAD

**Issue by xqrzd** [confluentinc/confluent-kafka-dotnet#546]
I started porting code over to the experimental branch, and ran into a minor problem.

I was using this method to process multiple partitions in parallel, https://github.com/confluentinc/confluent-kafka-dotnet/issues/197#issuecomment-304014428
I created a single consumer instance, and had it add messages to queues (1 queue per partition). I then had multiple threads that would read off their assigned queue, and deserialize/process the messages.

The new design requires message deserialization to be done in the generic consumer, which means in my example, the single thread that was previously just adding messages to a queue must now also deserialize the messages. librdkafka seems to be very sensitive to processing that happens inside Consume(), even the most minimal processing in that method drastically reduces the message throughput. In my case, it resulted in over a 10x drop in message throughput.

I can work around it easily enough, by creating multiple consumer instances, but that seems slightly wasteful. I'm curious what the recommended approach is for high throughput consumers on the experimental branch.

**Comment by xqrzd** [comment]
Actually, I can still get that functionality by implementing IDeserializer<byte[]>, although I'm still curious if this is the right thing to do.

**Comment by mhowlett** [comment]
yes, that's correct. 

smaller API surface area is better, so we're getting rid of the non-generic client classes and providing alternate ways to do everything that could only be done via them.

**Comment by xqrzd** [comment]
Thanks for confirming.
