### ISSUE TITLE
Periodic disconnect on kafka consumer

### ISSUE THREAD

**Issue by holocentric-bmsnext** [confluentinc/confluent-kafka-dotnet#547]
Description
===========
We are running the Linux kafka docker image in a Kubernetes cluster hosted in Azure. We are witnessing periodic consumer disconnects which are diluting our logs with errors.

Kafka was installed using the Helm chart.

An example of the errors being recorded:
Error : 10.240.0.82:9092/0: Receive failed: Disconnected

How to reproduce
================
It happens periodically on all consumers (generally 10 minutes), however it sometimes skips for some consumers.

Checklist
=========
Please provide the following information:

 - [ x] Confluent.Kafka nuget version: 0.11.4
 - [ x] Apache Kafka version: helm chart version "kafka-0.7.1"
 - [ x] Client configuration:
                { "enable.auto.commit", false },
                { "auto.offset.reset", "earliest" }

we are polling with 
                    while (!stoppingToken.IsCancellationRequested)
                    {
                        consumer.Poll(PollTimeoutMs);

                        await Task.Delay(PollDelayMs);
                    }
and
    "PollTimeoutMs": 1000,
    "PollDelayMs": 5

 - [ x] Operating system: Linux docker container
 - [ x] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ x] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
hi @holocentric-bmsnext - this error can safely be ignored - it should not be being reported as an error. it's due to Kafka's idle connection reaper closing idle connections (which the client re-establishes as needed). There is a fix to suppress the message going in 0.11.5 which is due out sometime around the end of the month.
