### ISSUE TITLE
brokers are down

### ISSUE THREAD

**Issue by shivashankar-awanti** [confluentinc/confluent-kafka-dotnet#548]
Description
===========
i have been using the same code for producer and consumer to run locally but could see im getting issues as below:
localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: No connection could be made because the target machine actively refused it...
Error: 1/1 brokers are down

im running on windows, i tried doing netstat for port 9092 its working fine, can you please let know what is that im missing, i tried searching but did not find the proper solution for the issue. thanks in advance. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by shivashankar-awanti** [comment]
its because of i missed running kafka server, so can close the issue. Thank you

**Comment by mhowlett** [comment]
"works better if you turn it on" :-)
