### ISSUE TITLE
No provider for SASL mechanism GSSAPI error

### ISSUE THREAD

**Issue by srininz77** [confluentinc/confluent-kafka-dotnet#550]
Description
===========
I get the following error when I try to create the producer in a .net core 2.1 console application running in a docker linux container.

**An exception of type 'System.InvalidOperationException' occurred in Confluent.Kafka.dll but was not handled in user code: 'No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM'
Stack trace:
 >   at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config)
 >   at Confluent.Kafka.Producer..ctor(IEnumerable`1 config, Boolean manualPoll, Boolean disableDeliveryReports)
 >   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer, Boolean manualPoll, Boolean disableDeliveryReports)**

How to reproduce
================
Using Visual studio 2017

1.  Create .net core application targeting netcoreapp 2.1
2.  Add Confluent.Kafka 0.11.3 nugget package
3. Add docker support to the application
4. Create Kafka producer using the following config:

var config = new Dictionary<string, object> { //set default config
                    { "bootstrap.servers", edmBrokers},
                    { "batch.num.messages", 20 },
                    { "acks", "all" },
                    {  "debug","all" },

                    //SASL:
                    { "security.protocol","SASL_SSL" },
                    { "sasl.mechanisms", "GSSAPI" },
                    { "sasl.kerberos.service.name", "kafka" },
                    { "sasl.kerberos.principal","kafka"}
                };
           
Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [x] Apache Kafka version: 1.0.0
 - [x] Client configuration:
 - [x] Operating system: Debian GNU/Linux 9 (stretch)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by mhowlett** [comment]
have you tried with version 0.11.4 or experimental-3?

Confluent.Kafka depends on librdkafka.redist which includes builds of librdkafka for a number of platforms. The error message you're seeing implies the librdkafka build included in 0.11.3 for linux does not support SASL_SSL/GSSAPI. You can double check with `ldd` whether or not this is actually the case (i can't recall). If we aren't linking against this, it's probably because libsasl2 isn't installed on that platform by default.

Assuming 0.11.4 / experimental-3 don't work, you'll need to either use the confluent packages to install librdkafka or compile from source (which isn't hard). then use `Library.Load` to specify the path of your custom build of librdkafka.

**Comment by srininz77** [comment]
None of them worked. I made it work by using https://hub.docker.com/r/confluentinc/cp-kafka-connect/ and installing dot net core 2.1 runtime inside the container. I don’t know what’s missing in Microsoft’s dot net 2.1 runtime image.

**Comment by mhowlett** [comment]
IIRC the CP docker images are built on debian 8, and the .net core docker images > 2.0 are built on debian 9. we include different librdkafka's for each of these platforms in librdkafka.redist. a possible explanation for what you're seeing is that that librdkafka we deploy that's used with debian 8 has this capability compiled in and the librdkafka used with debian 9 doesn't. @edenhill ?

**Comment by srininz77** [comment]
I now see these in my debug logs:

7|2018-06-19 02:25:30.947|rdkafka#producer-1|CONNECT| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Connecting to ipv4#1.1.1.1 (sasl_ssl) with socket 100
7|2018-06-19 02:25:30.947|rdkafka#producer-1|STATE| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Broker changed state DOWN -> CONNECT
7|2018-06-19 02:25:30.959|rdkafka#producer-1|CONNECT| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Connected to ipv4#1.1.1.1
7|2018-06-19 02:25:31.012|rdkafka#producer-1|CONNECTED| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Connected (#169)
7|2018-06-19 02:25:31.012|rdkafka#producer-1|STATE| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
7|2018-06-19 02:25:31.015|rdkafka#producer-1|AUTH| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Auth in state APIVERSION_QUERY (handshake supported)
7|2018-06-19 02:25:31.015|rdkafka#producer-1|STATE| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Broker changed state APIVERSION_QUERY -> AUTH_HANDSHAKE
7|2018-06-19 02:25:31.022|rdkafka#producer-1|SASLMECHS| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Broker supported SASL mechanisms: GSSAPI
7|2018-06-19 02:25:31.022|rdkafka#producer-1|AUTH| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Auth in state AUTH_HANDSHAKE (handshake supported)
7|2018-06-19 02:25:31.022|rdkafka#producer-1|STATE| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Broker changed state AUTH_HANDSHAKE -> AUTH
2|2018-06-19 02:25:31.103|rdkafka#producer-1|LIBSASL| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: No worthy mechs found
7|2018-06-19 02:25:31.103|rdkafka#producer-1|BROKERFAIL| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: failed: err: Local: Authentication failure: (errno: Invalid argument)
7|2018-06-19 02:25:31.104|rdkafka#producer-1|STATE| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: Broker changed state AUTH -> DOWN
7|2018-06-19 02:25:31.169|rdkafka#producer-1|NOINFO| [thrd:main]: Topic ASB.CoreBanking.JournalEntries partition count is zero: should refresh metadata
7|2018-06-19 02:25:32.103|rdkafka#producer-1|CONNECT| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: broker in state DOWN connecting

My config:

                   { "security.protocol","SASL_SSL" },
                    { "sasl.mechanisms", "GSSAPI" },
                    { "sasl.kerberos.service.name", "kafka" },
                    { "sasl.kerberos.principal", "blah"},
                    { "sasl.kerberos.keytab",  "blah.keytab"},
                    { "sasl.kerberos.kinit.cmd", knitCmd},
                    { "ssl.ca.location", "location" }

**Comment by edenhill** [comment]
`2|2018-06-19 02:25:31.103|rdkafka#producer-1|LIBSASL| [thrd:sasl_ssl://abc/bootstrap]: sasl_ssl://abc/bootstrap: No worthy mechs found`

This either means you haven't installed the libsasl2 gssapi/kerberos plugins,e.g. libssasl2-modules-gssapi-mit on Debian, or that the broker is not set up for GSSAPI authentication

**Comment by srininz77** [comment]
Installing libsasl2 modules worked. Thanks.

**Comment by shatl** [comment]
@srininz77 I'm having the same issue, could you share solution details please?

**Comment by srininz77** [comment]
@shatl I made it work by using https://hub.docker.com/r/confluentinc/cp-kafka-connect/ and installing dot net core 2.1 runtime inside the container. I don’t know what’s missing in Microsoft’s dot net 2.1 runtime image.

**Comment by shatl** [comment]
Thanks @srininz77

**Comment by shatl** [comment]
@srininz77  I created this image (asp.net core runtime and librdkafka compiled with Kerberos). It should be a bit smaller that cp-kafka-connect.

**Comment by teachmeabhinav** [comment]
@srininz77 Can please share the sample code snippet or step how to configure SASL with ACl in dot net core

**Comment by shatl** [comment]
@gmakin I documented it here https://shatl.wordpress.com/2018/10/30/using-kafka-with-kerberos-authentication-from-net-core/

**Comment by gmakin** [comment]
Thanks @shatl for your help!! I'll try this.
