### ISSUE TITLE
How Consumer Assignment are being retrived

### ISSUE THREAD

**Issue by alex687** [confluentinc/confluent-kafka-dotnet#561]
Description
===========
Hello , I have a question how Consumer.Assignment are being retrieved? I see that it goes to librd Kafka , but when the list is updated. I've had an issue that despite that Kafka is death some of the consumer still have assigned partitions. Is it because  they have items in the local queue

I'm only subscribing to one topic and attaching to those events
```
            _consumer.Subscribe(_consumerConfiguration.Topics);
            _consumer.OnConsumeError += LogOnConsumeError;
            _consumer.OnError += LogOnError;
```

Checklist
=========
Please provide the following information:

 - [ 0.11.4] Confluent.Kafka nuget version:
 - [ 1.1.0] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by alex687** [comment]
@edenhill Could you please assist

**Comment by mhowlett** [comment]
If access to the cluster is lost, the consumer will continue returning messages from it's local queue, if there are any yet unconsumed (it will not have received an assignment revoked notification). `consumer.Assignment` returns the current set of partitions the consumer is reading from (client local information), it will not change if the cluster is killed.

**Comment by alex687** [comment]
OK so is there anyway to check if Kafka is alive via confluent client, and that the consumer is attached to the partition and consuming data ?

**Comment by mhowlett** [comment]
Any method that contacts the cluster will fail if none of the brokers is available, `CommitAsync` included, which I think you probably want to be using if you care about this.

**Comment by andreycha** [comment]
@alex687 you can as well set statistics interval, subscribe to statistics event and use it as a Kafka "heartbeat".

**Comment by mhowlett** [comment]
@alex687 also refer to: https://github.com/confluentinc/confluent-kafka-dotnet/wiki#can-i-use-the-net-client-to-check-if-my-kafka-cluster-is-down

**Comment by andreycha** [comment]
@alex687 sorry, I misinformed you. You're right, that event is fired always. What you can do is some math between old and new stats. E.g. if you expect some messages over the time, but you see that offsets don't change or you event get invalid values, then it can mean that driver doesn't receive new messages from broker for whatever reason, which for you can mean "broker is not available".
