### ISSUE TITLE
How to set max.poll.records ?

### ISSUE THREAD

**Issue by mts57017** [confluentinc/confluent-kafka-dotnet#562]
Description
===========
It looks like i am unable to set max.poll.records value; it gives me the "not a valid setting" message

How to reproduce
================
attempt to set the max.poll.records config option

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.4
 - [x] Apache Kafka version: latest

**Comment by mhowlett** [comment]
config properties are not the same as the java client - they're inherited from librdkafka. see: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

also, the .net client operates a bit differently to the java client. calling `consumer.Consume` will return at most one message (from an internal queue), so `max.poll.records` is not relevant. you might be interested in `queued.min.messages` or `queued.max.messages.kbytes`.

**Comment by mts57017** [comment]
great, will give this a shot thanks
