### ISSUE TITLE
Very slow producing messages 0.11.4.0

### ISSUE THREAD

**Issue by darrrrek** [confluentinc/confluent-kafka-dotnet#563]
Description
===========
We have problem with very slow producing messages to Kafka. I have created loop to produce events, below you can see timings:

2018-07-03 10:35:29 - start time of producing message 0
2018-07-03 10:35:29 - start time of producing message 1
2018-07-03 10:35:29 - start time of producing message 2
2018-07-03 10:35:29 - start time of producing message 3
2018-07-03 10:35:29 - start time of producing message 4
2018-07-03 10:35:50 - start time of producing message 5
2018-07-03 10:35:51 - start time of producing message 6
2018-07-03 10:36:12 - start time of producing message 7
2018-07-03 10:36:31 - start time of producing message 8
2018-07-03 10:36:53 - start time of producing message 9

As you can see it's extremally slow.

How to reproduce
================
```
public class KafkaRepository : IKafkaRepository
    {
        string _endpoint = "hostname";
        string _topic = "topicname";
        Dictionary<string, object> _config;

        public KafkaRepository()
        {
            _config = new Dictionary<string, object> { { "bootstrap.servers", _endpoint }, { "socket.blocking.max.ms", 1 }, { "socket.keepalive.enable", true }, { "enable.auto.commit", true } };
        }
        public async Task ProduceEvent()
        {
            using (var producer = new Producer<string, string>(_config, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8)))
            {
                for (int i = 0; i < 100; i++)
                {
                   Console.WriteLine($"{DateTime.Now} - start time of producing message {i}");
                    var deliveryReport = await producer.ProduceAsync(_topic, $"key{i}", $"value{i}");

                    if (deliveryReport.Error.HasError)
                    {
                        throw new InvalidOperationException(deliveryReport.Error.Reason);
                    }
                }
            }
        }
    }
```

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.4.0
 - [ ] Apache Kafka version: 
 - [ ] Client configuration: 
 - [ ] Operating system: Windows 7
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
By awaiting the result of `ProduceAsync` you are waiting for the delivery report to be available before producing the next message, which will be slow. Additionally, the method librdkafka uses to poll both the socket and it's internal message queue for new messages simultaneously isn't possible on Windows, so message delivery can be delayed due to this on Windows (this is on the roadmap to fix, but it requires quite a big change to librdkafka). You can work around this by setting `socket.blocking.max.ms` to a low value.

**Comment by mhowlett** [comment]
You could use `ContinueWith`, `Tasks.WaitAll`, or the `Producer.Produce` method. The async/await approach would be good, for example, in a web request handlers.

**Comment by darrrrek** [comment]
Thanks I have still issues with this. Looks like without async/await works better but only for small amount of messages (it's ok for 5-10 messages, not for 100/1000). Second issue is, because I want to send messages syncronously, to be sure that there will be correct order on kafka when consumer will get those messages.

Currently I'm producing asyncronously, so my messages are available on kafka like the following:

message ID 5
message ID 1
message ID 3
message ID 2
message ID 4

I need to have correct order, 

message ID 1 (message sent first)
message ID 2 (message sent second)
message ID 3 ...
message ID 4 ...
message ID 5 ...

According to send time.

Current code:

```
public Task Produce(List<object> events)
        {
            List<Task> taskList = new List<Task>();
            using (var producer = new Producer<string, string>(_config, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8)))
            {
                foreach (var @event in events)
                {
                    Task task = Task.Run(() =>
                    {
                        var jsonToSend = JsonConvert.SerializeObject(@event);
                        producer.ProduceAsync(_topic, null, jsonToSend);
                    });

                    taskList.Add(task);
                }

                try
                {
                    Task.WaitAll(taskList.ToArray());
                }
                catch (AggregateException e)
                {

                }
                finally
                {
                    producer.Flush(TimeSpan.FromSeconds(10));
                }
            }

            return Task.CompletedTask;
        }
```

**Comment by mhowlett** [comment]
you don't need to wrap the call to produce with `Task.Run(() => ..` - this is the source of your out of order messages. simply wait on the tasks returned by `ProduceAsync`. Also, in order to guarantee ordering when not producing synchronously, you'll need to set `max.in.flight` to 1.

I'm currently tidying up old issues and closing this one (sorry for the delay in reply!). If you have further questions, feel free to re-open.
