### ISSUE TITLE
Local_Transport Errors: "connection reset by peer", "connection closed", "broker transport failure"

### ISSUE THREAD

**Issue by holocentric-bmsnext** [confluentinc/confluent-kafka-dotnet#566]
Description
===========
Getting random kafka errors occurring in logs with seemingly no pattern throughout the day. Not sure if we can just safely ignore these errors:
*"connection reset by peer" 
*"connection closed" 
*"broker transport failure"

How to reproduce
================
Randomly occurs and seemingly no intervals. Occurs several times a day across different services with consumers on different topics.

Checklist
=========
Please provide the following information:

-[x] Confluent.Kafka nuget version: 0.11.4
-[x] Apache Kafka version: helm chart version "kafka-0.7.1"
-[x] Client configuration:

    { "enable.auto.commit", false },
    { "auto.offset.reset", "earliest" }
    we are polling with
    while (!stoppingToken.IsCancellationRequested)
    {
        consumer.Poll(PollTimeoutMs); 
        await Task.Delay(PollDelayMs);
    }
and
"PollTimeoutMs": 1000,
"PollDelayMs": 5

-[x] Operating system: Linux docker container
-[x] Provide logs (with "debug" : "..." as necessary in configuration)
-[x] Provide broker log excerpts

**Comment by edenhill** [comment]
See https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected
