### ISSUE TITLE
Question on Producer.QueryWatermarks

### ISSUE THREAD

**Issue by HenningRoigaard** [confluentinc/confluent-kafka-dotnet#569]
I have questions regarding watermarks, more specifically as defined by [WatermarkOffsets]( https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/WatermarkOffsets.cs) and acquired using _Producer.QueryWatermarks_ 

From general research (not only .Net specific behavior) I believe I know the answer to some of these questions for simple use cases, but bounce them of you guys for validation or correction in context of the .Net implementation. 

I am aware that it is both the intention and current behavior that only offsets of fully replicated messages are taken into consideration when determining HIGH and LOW watermarks.

Some of my questions relate to the expected behavior for empty partitions. Though not specific for the .Net client, I would like to validate an assumption:
1) Is it true, that a partition cannot be empty, once the first message has been appended?

It is my understanding that roll-condition, whether time or size based, is checked when appending messages, and if rolled, the new messages are appended to the new segment. At the same time, cleanup (compaction and deletion) is only performed on rolled segments, so the partition will always contain at least on message not cleaned up.

If so, is it true that for a partition containing messages we define

2. LOW as the minimum offset of all messages not cleaned up. More specifically, in this case, LOW is the offset of an actual message?
3. HIGH as the offset of the highest message ever produced + 1, regardless of whether it is cleaned up or not. More specifically, in this case, HIGH is NOT an offset of an actual message?

(3) seems to be supported by Edenhill in https://github.com/confluentinc/confluent-kafka-dotnet/issues/28, but the .Net documentation states that HIGH is “The offset of the last stored message”, which indicates that there is a message with offset equal to HIGH.

My final questions relate the empty partition.

By simple testing of the .Net client on a newly created (and empty) partition, I can see that LOW = HIGH = 0. This seems counter intuitive for me, at least for LOW, for two reasons

* This seems to go against LOW being the offset of an actual message. 
* 0 is a valid LOW offset for partitions with messages. We then need some method to discern between empty partitions and partition whose lowest uncleaned offset is 0.

4. Shouldn't LOW be INVALID or some other special value in this case?

5. What is the intended criteria for detecting empty partitions wth the current implementation?

I surmise that the criteria is one or more of
a. LOW = HIGH = 0
b. HIGH = 0 
c. LOW = HIGH

It is my belief that these are all equivalent. HIGH = 0 seems to imply that LOW = 0, while once messages are appended, LOW < HIGH always.

As a final bonus question

6. Can the returned watermarks ever be special (Offset.IsSpecial), and if so, when?

**Comment by mhowlett** [comment]
thanks for the question @HenningRoigaard 

> Is it true, that a partition cannot be empty, once the first message has been appended?

yes, the active segment is never deleted.

> LOW as the minimum offset of all messages not cleaned up. More specifically, in this case, LOW is the offset of an actual message?

Yes.

> HIGH as the offset of the highest message ever produced + 1, regardless of whether it is cleaned up or not. More specifically, in this case, HIGH is NOT an offset of an actual message?

Yes. The inconsistency is arguably questionable, but the values are taken directly from the Kafka offset API response, so I think it makes sense that this is what we expose.

> Shouldn't LOW be INVALID or some other special value in this case?

I agree. Librdkafka explicitly checks for this and makes them both zero: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L2616

I think we should change that, for the reasons you point out.

I didn't check what negative number Kafka returns for low in this case. My guess is -1 which could be an appropriate thing to return here except that librdkafka defines -1 as "end", and -2 as "beginning", which would be confusing. However it doesn't matter as I think the most appropriate thing for librdkafka to return here is -1001 (`Invalid`). cc: @edenhill 

> Can the returned watermarks ever be special (Offset.IsSpecial), and if so, when?

no, unless there is something I'm unaware of.

**Comment by mhowlett** [comment]
I'm closing this as the client is behaving appropriately to Kafka's idiosyncrasies. Also, I've added to the documentation which will make it into the next release.

**Comment by mhowlett** [comment]
and to clarify, yes, your surmising is correct.
