### ISSUE TITLE
Slow consumer after initial reads

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#573]
Description
===========
We are running into an issue where the Kafka Consumer slows down after reading first few thousands messages. When we initially start the application, we can see throughput of 5000 messages/second. However, after reading 30,000 messages, we notice that the throughput drops significantly and it hovers around 400 messages/second. System resources are not getting maxed out and CPU is around 30-40%. 

We are using 11.4 version of libdKafka. On the network traffic, we can see the receive bytes come down significantly

For the most part, we are using default settings. Here are the client properties:

enable.auto.commit: False
    auto.commit.interval.ms: 15000
    fetch.min.bytes: 1000
    fetch.max.bytes: 52428800
    socket.timeout.ms: 5000
    commit.offset: 200
    #retries: 5
    #reconnect.backoff.ms: 1000
    default.topic.config.auto.offset.reset: "smallest"
    polling.interval: 1000
    debug: "metadata"

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [11.4] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
in v0.11.4, maximum sustainable consume throughput is about 150k msg/s for 100 byte messages (and in the 1.0-experimental-5 build it's more like double that). what is the message size? is this just a simple test setup that does nothing more than consume from a pre-populated topic? are you committing offsets? if so, are you committing them synchronously?

**Comment by ashishbhatia22** [comment]
This is a simple drain out test. We have 1 million messages sitting in a given topic. Message size is 400 bytes. Test simply reads a message from topic and writes messages out using log4net. We are committing offsets in increments of 400. Here is the code for commit offset
 // Commit message asynchronously as it is more optimized
            if (e.Offset % minimumCommitCount == 0)
            {
                generalLog.LogFormat(LOGLEVELS.Info, "Committing offset {0}", e.Offset);

                CommittedOffsets committedOffsets = MessageConsumer.CommitAsync(e).Result;

                generalLog.Log(LOGLEVELS.Info, "Committed offset");
            }

**Comment by mhowlett** [comment]
Interesting. committing every 400 messages, receive rate is around 400. I think you might be hitting the 'control loop file descriptor wakeup not supported on Windows' issue. try setting `socket.blocking.max.ms` to 1 (it defaults to 1000). The way librdkafka waits on both the socket and application is currently very specific to *nix. This will be changed in a future release as part of a larger set of changes.

`MessageConsumer.CommitAsync(e).Result` is blocking. If possible, avoid this. Maybe using `StoreOffsets` with `enable.auto.offset.store` set to `false` will provide acceptable semantics.

**Comment by mhowlett** [comment]
closing since I assume you are on Windows and believe much higher synchronous throughput would be achieved if `socket.blocking.max.ms` were set to 1 (this is now noted in the front page README). If higher throughput is required still, you'll need to operate asynchronously (i.e. not call `Result`, `Wait` or `await` each `CommitAsyc` call). Please re-open if the above suggestions do not resolve.
