### ISSUE TITLE
[Proposal] Expose group offsets without joining group

### ISSUE THREAD

**Issue by vchekan** [confluentinc/confluent-kafka-dotnet#575]
Description
===========
Sometimes, for monitoring purposes we need to know group's lag behind watermark.
Obvious option for this would be for consumer to report delta between its committed offset and high watermark. But this means that reporting is possible only while consumer is running which makes it unfit for alert purposed monitoring.

Proposal: kafka does have OffsetFetch API (api key 9) which does provide offset for every partition for given group. This call works without joining a group. Expose this functionality with following API: 
```
class GroupPartitionProgress {
  int Partition;
  int64 ConsumerOffset;
  int64 LowWatermark;
  int64 HighWatermark;
  // Convenience properties
  int64 Lag => HighWatermark - ConsumerOffset;
  int64 Lead => ConsumerOffset - LowWatermark;
  int64 MessageCount => HighWatermark - LowWatermark;
}
/// If partitions is null, then all partitions
async GroupPartitionProgress[] QueryGroupProgress(String groupId, topic: String, IEnumerable<int> partitions)
```

**Comment by BenjaminHolland** [comment]
I can see this being useful, but attaching it to the Consumer class feels odd, since a consumer is logically part of a group. There are a couple other methods like this that don't seem to fit into the "Thing that consumes messages" conceptual model of consumer, even on a class level. 

Java seems to like sticking methods like this into a [Thing]s 'static' class or something similar, basically separating the instance class from the utility methods. Would that work here?

**Comment by mhowlett** [comment]
Yep, would love to add this feature. It would belong on the `AdminClient` class (exists on the 1.0-experimental branch). It looks like additions will be required in librdkafka as well to implement it.

In terms of priority, we desperately need to get 1.0-experimental API locked down and promoted to the master branch (currently focussed on that). There are also some outstanding issues I want to resolve and we need good documentation and non-trivial examples. There is quite a bit of work here. After all that, I think this would be a well used feature and we should add it.

**Comment by jezza323** [comment]
Any progress or ETA on this one?

**Comment by wxlevel** [comment]
Any progress or ETA on this one?

**Comment by wxlevel** [comment]
> Yep, would love to add this feature. It would belong on the `AdminClient` class (exists on the 1.0-experimental branch). It looks like additions will be required in librdkafka as well to implement it.
> 
> In terms of priority, we desperately need to get 1.0-experimental API locked down and promoted to the master branch (currently focussed on that). There are also some outstanding issues I want to resolve and we need good documentation and non-trivial examples. There is quite a bit of work here. After all that, I think this would be a well used feature and we should add it.

Is this feature added now？

**Comment by anchitj** [comment]
You can use ListConsumerGroupOffsetsAsync api.
