### ISSUE TITLE
Issue receiving any message from topic

### ISSUE THREAD

**Issue by tomikiss** [confluentinc/confluent-kafka-dotnet#578]
Description
===========

Currently we having issue to receive any data from Kafka with the Basic consumer. Code currently copy paste of the Simple consumer Polling for messages. Consumer connect successfully but never receive any message on the "OnMessage" event call back, partition assignment the last event from the consumer. 
The group show up on the kafka server logs, but kafka-consumer-groups.sh cannot find the consumer group.
Topic working fine from command line tools or from java this only affect some .net consumer. Log show no Fetch which normally show up on all working version of the .net consumer.

How to reproduce
================
-Can't find way to reproduce this reliably 

Checklist
=========
Please provide the following information:

 - [ x] Confluent.Kafka nuget version:
0.11.5.0
 - [ x] Apache Kafka version: 
1.1.0
 - [ x] Client configuration:
group.id=kafka-test1234
bootstrap.servers=mnd-ld5-kfk01:9092
auto.commit.interval.ms=5000
debug=all
 - [x ] Operating system:
Windows 7 and Windows Server 2012

 - [x ] Provide logs (with "debug" : "..." as necessary in configuration)

[Output.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2253523/Output.txt)
 - [x ] Provide broker log excerpts

Server.log:

2018-08-02 13:46:04,688] INFO [GroupCoordinator 0]: Preparing to rebalance group kafka-test1234 with old generation 0 (__consumer_offsets-21) (kafka.coordinator.group.GroupCoordinator)
[2018-08-02 13:46:04,689] INFO [GroupCoordinator 0]: Stabilized group kafka-test1234 generation 1 (__consumer_offsets-21) (kafka.coordinator.group.GroupCoordinator)
[2018-08-02 13:46:06,733] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-test1234 for generation 1 (kafka.coordinator.group.GroupCoordinator)

Consumer-group list after connection show group never created:
Error: The consumer group 'kafka-test1234' does not exist.

 - [ ] Critical issue

**Comment by mhowlett** [comment]
it looks from the client logs like the group exists but the topic doesn't. do you have auto-topic creation enabled, or does the topic exist?

**Comment by tomikiss** [comment]
Hi, the topic exists. I verified this by issuing metadata request, however highwatermark query return invalid High/ Low values for the topic. Auto-topic creation disabled on the server.

Code below used to verify topic exsist:
var data = consumer.GetMetadata(true);
var topicMetaData = data.Topics.Where(x => x.Topic == topic).ToList();
//TopicMetaData contains a single element for topic live_prices
 
I manage to reproduce the issue with the examples Consumer code in the repository, as well have the same topic tested against kafka-cat/linux have full debug log for that one. Would that help to pin down the issue?

**Comment by mhowlett** [comment]
actually, i do see later in the logs that the group was successfully joined, and the topic `live_prices` is known to the client. When you say 'cannot find the consumer group' what do you mean? the logs suggest you haven't committed any offsets for the group. note that the expected behavior of kafka-consumer-groups.sh in that case is to not show any output.

**Comment by tomikiss** [comment]
When you say 'cannot find the consumer group' what do you mean? - I would refer to the fact that consumer group is not visible on kafka server side which might be the reason we never receive any data. This is a new consumer group which seems never get assigned offset based on defaults strategy and never see any new data afterwards.

The main issue that we never get any data with our app, onPartitionAssigned either never called, or called after 20-30s and even after calling Assign we don't get anything from the server with the csharp consumer.

Do you have any idea why we never get any new data, why offset never assigned to the group? Shall I generate more scenarios with logs to pin down where is the issue?

**Comment by tomikiss** [comment]
It seems like the issue was only affecting one computer which built this incorrect assembly. After the box restarted it working correctly again. Will close this ticket as I won't able to reproduce this issue anymore.
