### ISSUE TITLE
Status for support of Kafka version 0.10.1.0

### ISSUE THREAD

**Issue by ishworgurung** [confluentinc/confluent-kafka-dotnet#58]
Folks, We are contemplating whether to use this library for our project. Could you be so kind as to tell us what the status of this library to support Kafka `0.10.1.0`/`latest`? thanks!

**Comment by ishworgurung** [comment]
I understand by using the latest `librdkafka` this lib can guarantee 0.10.1.0 compatibility. Are we missing anything in terms of feature set?

**Comment by mhowlett** [comment]
Yes, Confluent.Kafka is built on top of librdkafka which is forwards and backwards compatible with all versions of Kafka back to v0.8. More details can be found here: https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

Currently we reference a nuget package with native v0.9.2 librdkafka binaries. Very soon this will be updated to v0.9.4 (latest).

Confluent.Kafka it's self is very new and currently missing a few features: 
- custom partitioners.
- produce user specified timestamps.

Going forward it's high priority for us to keep the capability of all client libraries that we support up-to-date with the capability of the latest broker version and [confluent platform](https://www.confluent.io/product/) components (for example [schema registry](http://docs.confluent.io/3.1.0/schema-registry/docs/intro.html) and [confluent control center](https://www.confluent.io/product/control-center/)).

**Comment by ishworgurung** [comment]
Thanks for the clarification @mhowlett
