### ISSUE TITLE
Unable to load shared library 'libdl' or one of its dependencies.

### ISSUE THREAD

**Issue by nvpemmaraju** [confluentinc/confluent-kafka-dotnet#580]
Description
===========
I get this below error when i deploy my solution to AWS Lambda using confluent kafka. Please provide me a solution to overcome this error.

{   "errorType": "DllNotFoundException",   "errorMessage": "Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory",   "stackTrace": [     "at Confluent.Kafka.Impl.LibRdKafka.PosixNative.dlopen(String fileName, Int32 flags)",     "at Confluent.Kafka.Impl.LibRdKafka.Initialize(String userSpecifiedPath)",

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.11.5 ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [aws lambda ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [yes ] Critical issue

**Comment by mhowlett** [comment]
tracking this issue in #572 - thanks for reporting.

**Comment by nvpemmaraju** [comment]
@mhowlett  - Do you have an ETA on when this feature is going to available if solved ?

**Comment by mhowlett** [comment]
i'm not sure - there's a bunch of higher priority stuff ahead of it that's a good couple of months work. we'll resolve it though - it's in our sprint planning backlog. probably later this year.

**Comment by nvpemmaraju** [comment]
Thanks for the reply. Appreciate it.
