### ISSUE TITLE
Consumer cannot connect on Windows 2008 R2

### ISSUE THREAD

**Issue by 123g** [confluentinc/confluent-kafka-dotnet#591]
Description
===========
We moved from 0.11.4 to 0.11.5 latest. Running locally on a Windows 7 64 bit is fine. But running 0.11.5 on a Windows server 2008, the client does not connect to Kafka and thus no messages make it through. The app runs without throwing any errors. This is a consumer app and the group id was not displayed  in the Consumer List. First time we see it.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Reproduce with `"debug": "broker"` to see what is going on.
Please also fill out the checklist above.

**Comment by 123g** [comment]
Now is fine and cannot reproduce it. If it happens again, I will get the debug logs as requested.

Thanks

**Comment by vandungit277** [comment]
i also have the same problem with you!

**Comment by 123g** [comment]
I was changing the versions back the forth. Then I  left it alone and rebooted and was good.

**Comment by mhowlett** [comment]
Note: There was an integer overflow issue on windows in v0.11.5 which could be responsible for this behavior. Anyone on 0.11.5 should upgrade to 0.11.6 or higher.
