### ISSUE TITLE
Question : is this project a sink-connector

### ISSUE THREAD

**Issue by schoonhg** [confluentinc/confluent-kafka-dotnet#596]
Description
===========

I am looking at the Confluent website to check the possibilities of the Confluent Connectors.
We are using MarkLogic as a NoSql database, and we want to create a solution in .NET that can be used as a sink connector to deliever data to MarkLogic via Kafka.
Is this github project the way to go or are there any other connector to investigate ?

I could not find a better way to post my question, sorry for the way I want to get in contact with Matthew Howlett....

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
Kafka Connect connectors (for use with the Kafka Connect framework, which comes with Apache Kafka) need to be written in Java. If you are dealing with very large volumes of data, I would definitely recommend using the connect framework. An existing sink connector for MarkLogic is here: https://github.com/sanjuthomas/kafka-connect-marklogic (written by the community, not supported by Confluent).

If your operation is smaller scale and you don't want to include Java in your stack, yes, using this client is appropriate.
