### ISSUE TITLE
Send producer problem when the service broker is offline

### ISSUE THREAD

**Issue by ManikandanPP** [confluentinc/confluent-kafka-dotnet#60]
Hi, I'm facing a problem in case of the service broker is offline with the below code 

var config = new Dictionary<string, object> { { "bootstrap.servers", brokerList } };
using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
var deliveryReport = producer.ProduceAsync(topicName, null, text);

When i execute the producer code when server is offline,  code  hangs forever.
Are there anyway to see if the service broker is online before to send the message or give the time out configuration in the configuration for producer?

Thank you.

**Comment by mhowlett** [comment]
Hi @ManikandanPP - 

Can you please provide:
1. which dotnet runtime are you using (.NET Framework? .NET Core?). Version?
2. full source code (and project file).

I just did a quick test and was unable to reproduce. You should be able to instantiate a `Producer` and call `ProduceAsync` without blocking even if the server is down.

**Comment by ManikandanPP** [comment]
Thanks for your reply. I shared the full source code with projects. Please do the needful.

[App.config.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/783208/App.config.txt)
[ConfluentKafkaTest.csproj.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/783209/ConfluentKafkaTest.csproj.txt)
[packages.config.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/783211/packages.config.txt)
[Program.cs.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/783210/Program.cs.txt)

**Comment by mhowlett** [comment]
Your application is hanging for 5 minutes on each call to `Flush` according to the default value of the topic config property `message.timeout.ms` (note this needs to be set in the nested `default.topic.config` config parameter). You can also call `Flush` with a timeout if you would like message delivery to be abandoned earlier in the event the broker is down. Note: you will get a delivery report even if the message delivery was abandoned with a relevant error code.

**Comment by ManikandanPP** [comment]
Thanks lot for the clarification @mhowlett . Currently we are using v0.9.4-preview2 of confluent-kafka-dotnet. When will you release the final version of confluent-kafka-dotnet ?

**Comment by mhowlett** [comment]
Can't guarantee an exact date, but soon.
