### ISSUE TITLE
Kafka Producer Keeps getting disconnected

### ISSUE THREAD

**Issue by Chris2018Kafka** [confluentinc/confluent-kafka-dotnet#601]
I am using

Confluent.Kafka 0.11.5
Confluent.Kafka.Avro 0.11.5
Confluent.SchemaRegistry 0.11.5
Confluent.Apache.Avro 1.7.7.5

We are using the Avro Schema

I keep getting disconnected from some of my brokers. This happens at least 3 times a day.  
Here is a log file snippet.

     2018-08-19 22:15:49.443 +01:00 [Information] [TID:39] 8/19/2018 10:15:49 PM: 
     akka://Cluster/user/commander/O, -> BaseConsumerActor %40884959 speed: 284 
     msg/sec at 19/8/2018 10:15:49.443 PM, correct: 1227951, errors: 0.
     2018-08-19 22:24:49.919 +01:00 [Error] [TID:31] 8/19/2018 10:24:49 PM: 
     akka://Cluster/user/commander/GenericProducerGeneric, OnError in Kafka 
     generic producer sender Confluent.Kafka.Producer, reason Server/3: Disconnected
     2018-08-19 22:31:27.203 +01:00 [Information] [TID:10] 8/19/2018 10:31:27 PM: 
     akka://Cluster/user/commander/O, Message: 41-AC-43-7B-EB-A8-8B-04-DF-7F-C3-D1- 
     CF-B6-3C-3C, SourceSystem: 1
     Created: 636703146823540186, UnixTimestamp: 1534714271, ReceivedSequenceNr: 171284691

We have 3 kafka brokers and it hasn't happened on broker 1 yet, but it happens on brokers 2 and 3.
I'm not sure if this has to do with the number of partitions we have and it's a Kafka broker setup or it the .NET DLLs. We do seem to be losing messages when this happens.

Does the .NET Kafka automatically try to reconnect?

**Comment by mhowlett** [comment]
You can treat `OnError` events as informational - the client will reconnect automatically if a connection is lost.  If you are interested in some more detailed information as to why this might be happening, set the `debug` config property to `all` and have a look at the logs around the time you get the `OnError` event. What is your produce throughput? could there a 10 minute period where you don't produce anything to a particular broker? If that is the case, this is probably the broker's idle connection reaper killing the connection on purpose (i'm not sure if that generates events on `OnError` or not). The key thing to check for is the `Error` property on the message returned from the produce call. In the 1.0 API, this has changed to setting the exception on the returned `Task`.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected
