### ISSUE TITLE
cannot send message

### ISSUE THREAD

**Issue by zhaoqinghai** [confluentinc/confluent-kafka-dotnet#605]
Description
===========
`producer.ProduceAsync(topicName, null, "message");`
this can create topic in kafka server but i look up the log file is empty forever

How to reproduce
================
my webapi is running in windows kafka is running in ubuntu 

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:0.11.5
 - [ ] Apache Kafka version: 2.12
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
@zhaoqinghai - you don't want to call `Flush` after every produce (only before the `Producer` is disposed). where are you constructing the producer? when is it disposed? You could try doing `producer.ProduceAsync().Result` which will force the produce to be synchronous and also allow you to inspect the `Error` property in the returned `Message` for any problems. If this produces the message successfully, you're probably disposing the producer before the produce call had a chance to send the produce request, as @edenhill is guessing.

**Comment by zhaoqinghai** [comment]
when I force the produce to bu synchronous, it never excute next line code. why?

**Comment by zhaoqinghai** [comment]
thank you, when i edit listeners ,it run ok
