### ISSUE TITLE
Timeline for a 1.0 client release?

### ISSUE THREAD

**Issue by awhittier-metabolon** [confluentinc/confluent-kafka-dotnet#606]
I'm deciding whether to use a 0.X or 1.X version of the client for a project, and one thing that would be helpful to know is a tentative timeline for a production-quality 1.X release. I couldn't find this discussed anywhere else, so I figured I'd ask here. 

Thanks!

**Comment by mhowlett** [comment]
as fast as we can. at this point 1.X is more reliable than 0.11.x in addition to having a much improved API + more features. We will merge to master and label it 1.0-beta on the timeframe of about a week. The reason we won't release immediately is we don't want to lock down the API - once we release 1.0, we want don't want to make breaking changes to the API again any time soon.
