### ISSUE TITLE
elevated CPU after QPC change

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#607]
I'm closing #89 since the reported problem has been resolved, however @ranave notes https://github.com/confluentinc/confluent-kafka-dotnet/issues/89#issuecomment-390192151

> we have experienced a side effect of the QueryPerformanceCounter change: with the QPC version of RdKafka our applications using kafka and also the kafka server seem to be more busy, they are using more cpu with the same throughput.

this issue is to track that. I'm interested to know whether https://github.com/edenhill/librdkafka/pull/1930 has an impact (not in a nuget build yet). I think a good next step would be to test that.

**Comment by edenhill** [comment]
Before QPC the granularity of `socket.blocking.max.ms=1` wasn't great, it could easily slip into the 30 or 40ies of milliseconds, QPC fixes this which also means there will be more wakeups and possibly a higher rate of messages to the broker.

Npw with the queue wakeup fix in https://github.com/edenhill/librdkafka/pull/1930 there is no longer any need to use `socket.blocking.max.ms`, thus no unneccessary wakeups, which should improve CPU utilization.

**Comment by milindl** [comment]
Closing this since https://github.com/confluentinc/librdkafka/pull/1930 is fixed and released a while back.
