### ISSUE TITLE
Subscribe won't assign partitions randomly

### ISSUE THREAD

**Issue by vbucchare** [confluentinc/confluent-kafka-dotnet#610]
Description
===========
I'm not sure if this is a problem with the dotnet module, librdkafka, kafka itself or my own code. I've been struggling with this for weeks and cannot find a solution, so here goes.

I have a vendor supplied Kafka producer which seems to be working fine with no issues. 
I have a custom .net consumer program that works great, until it doesn't. For whatever reason, at program start the consumer sometimes does not get assigned partitions from Kafka. If this occurs, no matter how many times the program restarts, it will not be assigned partitions. Restarting the Windows server (2008) fixes the problem every time, until the consumer needs to be restarted for any reason, at which point it may or may not work. 

Log Files:

[WorkingLog.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2329585/WorkingLog.txt)
[NotWorkingLog.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2329586/NotWorkingLog.txt)

If it isn't obvious, I'm new to Kafka so I apologize in advance if I'm making some kind of obvious mistake.

How to reproduce
================
Stop/Start Consumer .net application until no partitions get assigned.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.5
 - [ ] Apache Kafka version: 1.1.x
 - [ ] Client configuration:
 - [ ] Operating system:  Consumer: Windows 2008 Server, Kafka: SUSE Linux Enterprise Server 12 SP2 64-bit
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
For some reason there's no 'querying for coordinator' or 'Sent GroupCoordinatorRequest' in the logs of the problematic case. Your problem seems different to #584, but it's reminiscent of it - it's resolved by restarting the windows machine that a consumer is running on. @edenhill would you mind having a look at the logs to see if you recognize any problems?

@vbucchare - can you try 1.0-experimental-11 and see if that resolves the issue? also, is possible, can you paste your code / consumer / broker config? also, if possible, can you to run your consumer app on a linux machine and see if the issue happens there?

**Comment by vbucchare** [comment]
Thank you for the reply. Here is my code. I will try the experimental 11 and let you know how it goes. It isn't possible to run this on Linux in my situation.

`public static int Run_Poll(string brokerList, List<string> topics, string groupID, int sleepInterval, int batchTimeout, Func<string, string, int, string, bool> consumeFunction, NLog.Logger logger, int sessionTimeout, bool debugProtocol)
        {            
            int noMessagesInterval = 0;
            bool errorEncountered = false;

            var config = new Dictionary<string, object>
            {
                { "bootstrap.servers", brokerList }, // current value 192.168.110.116:9093,192.168.110.117:9096,192.168.110.118:9099
                { "group.id", groupID }, // current value ConsumerTST2
                { "enable.auto.commit", false },
                // { "auto.commit.interval.ms", 5000 }, // changed auto commit to false, commented out this line
                { "statistics.interval.ms", 60000 },
                { "session.timeout.ms", sessionTimeout}, // current value 30000
                { "auto.offset.reset", "smallest" },
                { "client.id", Environment.MachineName } // TODO: When adding multithreading, add thread count here
            };

            if (debugProtocol)
            {
                config.Add("debug", "all"); // currently logging
            }

            using (var consumer = new Consumer<Ignore, string>(config, null, new StringDeserializer(Encoding.UTF8)))
            {
                consumer.OnLog += (_, msg) =>
                {
                    logger.Trace($"Consumer Log:  [{msg.Name}] [{msg.Facility}] [{msg.Level}] [{msg.Message}]");                    
                };
                
                consumer.OnPartitionEOF += (_, end) =>
                {
                    logger.Info($"Reached end of topic {end.Topic} partition {end.Partition}, next message will be at offset {end.Offset}");                    
                    noMessagesInterval = 0;
                };

                consumer.OnError += (_, error)
                    => logger.Error($"Error: {error}");
                    
                // Raised on deserialization errors or when a consumed message has an error != NoError.
                consumer.OnConsumeError += (_, msg)
                    => logger.Error($"Error consuming from topic/partition/offset {msg.Topic}/{msg.Partition}/{msg.Offset}: {msg.Error}");

                consumer.OnOffsetsCommitted += (_, commit) =>
                {
                    if (commit.Error)
                    {
                        logger.Error($"Failed to commit offsets: {commit.Error}");
                        // TODO: Throw Error?
                    }
                    else
                    {
                        logger.Info($"Successfully committed offsets: [{string.Join(", ", commit.Offsets)}]");
                    }
                };

                // Raised when the consumer is assigned a new set of partitions.
                consumer.OnPartitionsAssigned += (_, partitions) =>
                {
                    logger.Info($"Assigned partitions: [{string.Join(", ", partitions)}], member id: {consumer.MemberId}");
                    // If you don't add a handler to the OnPartitionsAssigned event,
                    // the below .Assign call happens automatically. If you do, you
                    // must call .Assign explicitly in order for the consumer to 
                    // start consuming messages.
                    consumer.Assign(partitions);
                    noMessagesInterval = 0;
                };

                // Raised when the consumer's current assignment set has been revoked.
                consumer.OnPartitionsRevoked += (_, partitions) =>
                {
                    logger.Info($"Revoked partitions: [{string.Join(", ", partitions)}]");
                    // If you don't add a handler to the OnPartitionsRevoked event,
                    // the below .Unassign call happens automatically. If you do, 
                    // you must call .Unassign explicitly in order for the consumer
                    // to stop consuming messages from it's previously assigned 
                    // partitions.
                    consumer.Unassign();
                };

                consumer.OnStatistics += (_, json) =>
                {
                    logger.Debug($"Statistics: {json}");
                };
                
                consumer.Subscribe(topics);

                logger.Info($"Subscribed to: [{string.Join(", ", consumer.Subscription)}]");

                var cancelled = false;
                //Console.CancelKeyPress += (_, e) => {
                //    e.Cancel = true;  // prevent the process from terminating.
                //    cancelled = true;
                //};

                //Console.WriteLine("Ctrl-C to exit.");
                while (!cancelled && !errorEncountered && noMessagesInterval < batchTimeout)
                {

                    // changed from poll to consume to handle errors
                    // consumer.Poll(TimeSpan.FromMilliseconds(100));

                    if (consumer.Consume(out Message<Ignore, string> msg, TimeSpan.FromMilliseconds(100)))
                    {
                        if (!consumeFunction(msg.Value, msg.Topic, msg.Partition, msg.Offset.ToString()))
                        {
                            errorEncountered = true;
                        }
                        else
                        {
                            // commit offset
                            var committedOffsets = consumer.CommitAsync(msg).Result;
                            logger.Info($"Committed offset: {committedOffsets.Offsets[0]}");
                            noMessagesInterval = 0;
                        }
                    }                    

                    if (noMessagesInterval > 1)
                    {
                        logger.Info($"Sleeping for {sleepInterval}; No Message Count: {noMessagesInterval}");
                        Thread.Sleep(sleepInterval);
                    }

                    noMessagesInterval += 1;
                }

                if (errorEncountered)
                {
                    // default return code 8
                    logger.Fatal($"Return Code 8, see log for error details");

                    return 8;
                }

                if (noMessagesInterval >= batchTimeout)
                {
                    logger.Info($"Ending program as no new messages have been produced in {batchTimeout * sleepInterval / 1000} seconds.");
                }

                consumer.Unassign();
                return 0;
            }
        }`

**Comment by vbucchare** [comment]
Actually it appears going up to 1.0-experimental-11 will cause significant re-write of my code. If this will for sure fix the problem I'll do it, but I'm not sure if I want to make that investment considering it's still in the  experimental phase.

**Comment by mhowlett** [comment]
this looks almost certainly related to #603, fix coming soon.

**Comment by mhowlett** [comment]
the fix will be in 0.11.6 as well as 1.0.

**Comment by vbucchare** [comment]
I agree the problems seem to be very similar. Do you know when 11.6 will be released? 

For kicks I tried 11.4 and it doesn't seem to have fixed my problem, unfortunately.

**Comment by chruska81** [comment]
we just ran into this issue as well.  I was wondering what the ETA is for version 11.6?

**Comment by mhowlett** [comment]
this is fixed in 0.11.6-RC2 (available on nuget). 0.11.6 is due this week.

**Comment by milindl** [comment]
Closing this with Matt's comment as we're now on 2.4.0.
