### ISSUE TITLE
ProduceAsync still deadlocks for nuget version: Confluent.Kafka -Version 1.0.0-experimental-12

### ISSUE THREAD

**Issue by foresightyj** [confluentinc/confluent-kafka-dotnet#612]
Description
===========

I upgraded to `Confluent.Kafka -Version 1.0.0-experimental-12` according to what you mentioned here. If I am not wrong, this package includes `1.0-experimental-9`.

#545 

But I still see `ProduceAsync` deadlock (for a console application). I added debug: all in the config and captures the following log:

![image](https://user-images.githubusercontent.com/1296736/44770419-93ee9580-ab9a-11e8-9268-6567c5e0781b.png)

Here is the relevant code:

      var config = new Dictionary<string, object> {
                { "bootstrap.servers", "192.168.0.228:9092" },
                { "queue.buffering.max.ms", 1 },
                { "socket.blocking.max.ms", 1 },
                { "debug", "all"}
            };
            _producer = new Producer<string, string>(config, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8));

        public void Publish<T>(T message) where T : IExternalMessage
        {
            if (message == null) throw new ArgumentNullException("message");
            var value = JsonConvert.SerializeObject(message, ExternalMessageConverters.SerializerSettings);
            Logger.Info("Publishing External Message: " + message.GetType().FullName + "\r\n" + value);
            var partition = new TopicPartition(_topicNamePrefix + message.Topic, new Partition(message.PartitionKey % 20));
            var m = new Message<string, string>
            {
                Key = message.Key,
                Value = value
            };
            Console.WriteLine("BEGIN ProduceAsync: {0}", DateTime.Now);
            _producer.ProduceAsync(partition, m).Wait();
            Console.WriteLine("END ProduceAsync: {0}", DateTime.Now);
            //AsyncContext.Run(async () =>
            //{
            //});
            Logger.Info("DONE Publishing Message");
        }

The entire log is attached below:

[entire.log](https://github.com/confluentinc/confluent-kafka-dotnet/files/2331066/entire.log)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: Confluent.Kafka -Version 1.0.0-experimental-12
 - [ ] Apache Kafka version: kafka_2.11-2.0.0
 - [ ] Client configuration: see code above
 - [ ] Operating system: Client runs on Windows 7 (my dev machine). Kafka Server runs in Ubuntu 14.04.5 LTS
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by foresightyj** [comment]
It is kind of weird that I have 3 types of projects that depend on `Publish` which uses `ProduceAsync` in my application. One is an ASP.NET MVC 5 application, the other is ASP.NET Web API 2 application and the others are console applications.

The reason I upgraded to your `1.0-experimental-9` is that the MVC application deadlocks while the other two run well. After the upgrade, the MVC application runs well but the console application deadlocks now (I didn't check the Web API application).

**Comment by mhowlett** [comment]
thanks for the issue @foresightyj - are you using .NET Framework or .NET Core? if you can provide a complete example / project file demonstrating the problem that would be really useful. I'll address this soon after we get 1.0-beta out.

**Comment by mhowlett** [comment]
great, glad you got it working.

**Comment by foresightyj** [comment]
@mhowlett 

I had encountered the same problem several times. Almost in all cases, it is because `System.Memory`
, `System.Runtime.CompilerServices.Unsafe` are missing. However, the code runs happily without any warning until it deadlocks at `PublishAsync`. It is very hard to guess what goes wrong.

I got into this situation probably because I use Resharper to automatically add references or manually edit your csproj files. In such cases, dependencies can get loose. 

In the end, I added a few lines in my kafka publisher:

```
#if DEBUG
            //make sure System.Memory, System.Runtime.CompilerServices.Unsafe are loaded
            Console.WriteLine(typeof (System.Memory<char>).Assembly.FullName + " is loaded");
            Console.WriteLine(typeof (System.Runtime.CompilerServices.Unsafe).Assembly.FullName + " is loaded");
#endif

```

to make sure that these two types can be instantiated without any problem.

**Comment by mhowlett** [comment]
thanks for the input @foresightyj. re-opening as a reminder to investigate further.

**Comment by kiedd** [comment]
There is also possibility, that using Task.Wait() on asynchronous method (which is ProduceAsync) causes deadlock. If you want to execute async method synchronously, you should use GetAwaiter().GetResult()

**Comment by mhowlett** [comment]
thanks @kiedd - this should all be fixed in -beta3 which I expect to be out early next week.

**Comment by mantzouranisc** [comment]
I have the exact same issue. The call to ProduceAsync blocks the entire code from continuing even though I don't wait for the result.

My packages.config:

`<packages>
  <package id="Confluent.Apache.Avro" version="1.7.7.6" targetFramework="net461" />
  <package id="Confluent.Kafka" version="1.0.0-beta3-ci-880" targetFramework="net461" />
  <package id="Confluent.SchemaRegistry" version="1.0.0-beta3-ci-880" targetFramework="net461" />
  <package id="Confluent.SchemaRegistry.Serdes" version="1.0.0-beta3-ci-880" targetFramework="net461" />
  <package id="librdkafka.redist" version="1.0.0-RC8" targetFramework="net461" />
  <package id="log4net" version="2.0.8" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net461" />
  <package id="System.Buffers" version="4.4.0" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.6.0-preview3.19128.7" targetFramework="net461" />
  <package id="System.Memory" version="4.5.0" targetFramework="net461" />
  <package id="System.Net.Http" version="4.3.0" targetFramework="net461" />
  <package id="System.Numerics.Vectors" version="4.4.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net461" />
</packages>`

**Comment by milindl** [comment]
Closing this with Matt's comment above. We're on 2.4.0 now. Please reopen if this persists.
