### ISSUE TITLE
Error in retrieving messages from kafka from WindowsServer2012R2 

### ISSUE THREAD

**Issue by NarayanGN** [confluentinc/confluent-kafka-dotnet#615]
Description
===========
using direct consumer and able to retrieve messages from kafka queue from Windows7

but the same code is not working with WindowsServer2012R2 with error "5/5 brokers are down"

Attached consumer logs from both machine
[Consumer Code.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2339437/Consumer.Code.txt)
[Windows7.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2339440/Windows7.txt)
[WindowsServer2012.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2339442/WindowsServer2012.txt)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.5
 - [ ] Apache Kafka version: 
 - [ ] Client configuration: Attached code
 - [ ] Operating system: WindowsServer2012R2
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration) Attached logs for security,protocol,consumer
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ievsiukovi** [comment]
Have a similar problem on Win2012R2 servers while on Win7 it works.
I figured that on win2012 consumer group is hanged on wait-broker state and not doing coordinator request like on win7 in example: 
CGRPQUERY [thrd:main]: kafkanode05.mysite.com:9092/bootstrap: Group "6585ac10-64b9-4edb-b449-68eca0f93d5b": querying for coordinator: intervaled in state wait-broker

Didn't find workaround yet.

**Comment by NarayanGN** [comment]
As a workaround moved to previous version (0.11.4 Confluent.Kafka) and is working fine in Win2012R2 servers.

**Comment by edenhill** [comment]
This could be related to the timing issues in #603

**Comment by mhowlett** [comment]
... which will be resolved in 1.0-beta, due to be released soon.

**Comment by mhowlett** [comment]
0.11.6-RC1 is now on nuget.org which should resolve this.

**Comment by milindl** [comment]
Closing this with Matt's comment above.
