### ISSUE TITLE
Very slow performance with Kafka Consumer

### ISSUE THREAD

**Issue by roikatz** [confluentinc/confluent-kafka-dotnet#619]
Description
===========
I'm opening a new issue, based on this one:https://github.com/confluentinc/confluent-kafka-dotnet/issues/554

We've tried all the configuration available in our disposal and in the issue above, but still the max performance we could achieve was around 600messages per second, without any processing on our side.
for example, with Java consumer (and console consumer) we can achieve a rate of 100 times that number, (60K)

We are not 100% sure why. And we are certain it is something one our side, and we should achieve more.
We are using blocking.ms =1, latest (0.11.5) SDK and tried sync, async, less frequent commits, StoreOffsets, nothing really seems like it increasing performance.

How to reproduce
================
Simple Kafka consumer,
Poll instead of consume with events.
commit % 400, 5, and 100

Checklist
=========
Please provide the following information:

 - [V] Confluent.Kafka nuget version: 0.11.5
 - [V] Apache Kafka version:  1.0.0
 - [ ] Client configuration: changing....
 - [V] Operating system: Centos 7.4
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
if you run the benchmark test, what throughput do you get? on my machine to a local broker, 0.11.5 gives me about 150k msg/s (1.0-experimental is about double that).

https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/test/Confluent.Kafka.Benchmark

**Comment by roikatz** [comment]
Hi, since it is a very long holiday in Israel I will update on Wednesday when I will have access to the machines. I'm waiting to see the results as much as you do.

**Comment by roikatz** [comment]
Using the benchmark we've managed to digest (with consume and poll) around 30K messages in 450ms which is about 65K per second. on a dev machine.
So back to the drawing board, why our client in the app being so slow. the implementations seems similar. But the core issue is that this is probably not the sdk's fault.

Thanks.

**Comment by jalaz** [comment]
Hi @roikatz, 
Would you mind sharing the root cause of the slow performance if it is not much trouble for you?
We are currently experiencing very similar behavior with latency optimized setup from [the docs](https://www.confluent.io/white-paper/optimizing-your-apache-kafka-deployment/)
Thanks
