### ISSUE TITLE
CachedSchemaRegistryClient in .Net Core doesn't work with proxy

### ISSUE THREAD

**Issue by janrys** [confluentinc/confluent-kafka-dotnet#620]
Description
===========
It's not possible to set proxy settings for CachedSchemaRegistryClient in .Net Core. If your service user proxy settings are not valid for your scenario, you cannot configure or change settings in code. CachedSchemaRegistryClient uses internally RestService, where HttpClient is instantiated without HttpClientHandler proxy settings.

How to reproduce
================
This code does not work without hacking private list of http clients in case your connection do not work with default proxy behaviour:

ISchemaRegistryClient schemaRegistry = new CachedSchemaRegistryClient(config);

/// HACK
object restService = schemaRegistry.GetType().GetField("restService", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(schemaRegistry);
List<HttpClient> clients = restService.GetType().GetField("clients", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(restService) as List<HttpClient>;

            for (int i = 0; i < clients.Count(); i++)
            {
                HttpClient client = clients[i];
                HttpClientHandler handler = new HttpClientHandler();
                handler.Proxy = WebRequest.DefaultWebProxy; /// your custom proxy settings
                clients[i] = new HttpClient(handler) { BaseAddress = client.BaseAddress, Timeout = client.Timeout };
            }            
/// END OF HACK

 List<string> subjects = await schemaRegistry.GetAllSubjectsAsync();

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.5
 - [ ] Apache Kafka version: 
 - [ ] Client configuration: 
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks for reporting, good point.

**Comment by Alpesh1984909090** [comment]
I'm facing the same issue. produce code with schema registry config works fine in .net framework but it's not working with .net core? Is there any work around on the issue ?

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-dotnet/pull/2128
