### ISSUE TITLE
OnPartitionsAssigned is not called any more.

### ISSUE THREAD

**Issue by wangjia184** [confluentinc/confluent-kafka-dotnet#624]
Description
===========
`OnPartitionsAssigned` is not called any more after `Subscribe` is fired.

Three environments(DEV/STAGE/PRODUCTION) share the same Kafka cluster.  The application worked well for more than 1 year and suddenly the application on STAGE environment started to encounter problem recently. 

* This only happens on STAGE environment even the application has the exact same code on all three environments.
* The application worked well before on STAGE environment.
* The application of each environment consumes different topics.
* I checked Kafka topics in Kafka Tool(http://www.kafkatool.com/),  nothing special.

After several hours investigation, it turns out `OnPartitionsAssigned` is not called.
Here is the code from application.

```
consumer.OnError += OnError;
consumer.OnConsumeError += OnConsumerError;
consumer.OnPartitionEOF += OnPartitionEOF;
consumer.OnOffsetsCommitted += OnOffsetsCommitted;

consumer.OnPartitionsAssigned += (_, partitions) =>
{
    if (partitions != null)
    {
        try
        {
            string ids = string.Join(",", partitions.Select(p => p.Partition.ToString()));
            log.InfoFormat("Assigned partitions: [{0}]", ids);
            consumer.Assign(partitions);
        }
        catch (Exception ex)
        {
            log.Error("OnPartitionsAssigned", ex);
        }
    }
    else
    {
        log.InfoFormat("Kafka assigned null partitions");
    }
};

consumer.OnPartitionsRevoked += (_, partitions) =>
{
    string ids = string.Join(",", partitions.Select(p => p.Partition.ToString()));
    log.InfoFormat("Revoked partitions: [{0}]", ids);
    consumer.Unassign();
};

consumer.Subscribe(new List<string>(){ _topic });
log.InfoFormat("KafkaConsumer({0}) subscribed {1}", this._brokerList, _topic);





private void OnPartitionEOF(object sender, TopicPartitionOffset e)
{
    log.InfoFormat("KafkaConsumer reached end of topic {0} partition {1}, next message will be at offset {2}"
        , e.Topic
        , e.Partition
        , e.Offset
        );
}

private void OnError(object sender, Error e)
{
    if( e != null)
    {
        string msg = $"KafkaConsumer({_topic}) encountered an error ({e.Code}) : {e.Reason}";
        if (e.Code == ErrorCode.Local_AllBrokersDown)
            log.ErrorFormat(msg);
        else
            log.WarnFormat(msg);
    }
    
}

private void OnConsumerError(object sender, Message msg)
{
    log.ErrorFormat("KafkaConsumer({0}) failed to consume error from partition/offset({1}/{2}) : {3}"
        , msg.Topic
        , msg.Partition
        , msg.Offset
        , msg.Error
        );
}
```
From the log, you can see `Subscribe` is called successfully.
![image](https://user-images.githubusercontent.com/2765840/45546400-bd244c80-b84f-11e8-8636-2fdc06fa04b7.png)

But after that,  there is no reaction. `OnError` / `OnConsumeError` / `OnPartitionEOF` /  `OnPartitionsAssigned` , none of these callbacks are fired.  It just failed silently.

There are two instances of application running in STAGE environment and they encounter the same problem.
I tried to change the `group.id` within these two instances, it does not help.

How to reproduce
================

I tried to connect to the same Kafka cluster from my local machine, consuming the same topic,  the issue cannot be reproduced.

Checklist
=========
Please provide the following information:

 - [x ] Confluent.Kafka nuget version: 0.11.5
 - [x ] Apache Kafka version: 0.10
 - [x ] Client configuration:
```
 new Dictionary<string, object>
 {
                { "group.id", "ubs_" + Environment.GetEnvironmentVariable("Cluster.Name") },
                { "bootstrap.servers", brokerList },
                { "enable.auto.commit", "false" },
                { "default.topic.config", new Dictionary<string, object>()
                    {
                        { "auto.offset.reset", "smallest" }
                    }
                }
};
```
 - [ x] Operating system: Windows 2016
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This might be #603, where timers would wrap after 7+ days (depending on clock freq) of system uptime.
It is fixed in v0.11.6-RC2

**Comment by wangjia184** [comment]
@edenhill   #603 is a bug in producer. My problem is in consumer.  (I do see messages in topic in KafkaTool) .      Are they related?

**Comment by wangjia184** [comment]
Yep, @edenhill , after upgrading to 0.11.6-RC2,  the issue has gone.
