### ISSUE TITLE
SSL Issue - KeyStore and OpenSSL

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#626]
I am implementing SSL by following this article. I have successfully started the Kafka on linux server by using keyStore and Open SSL. I successfully tested the connectivity between the client and server using a third party tool.

When I try using the confluent library, I am getting an exception
 - 2018-09-18 12:29:09,832 [17] DEBUG MessageBusProducer [(null)] - ConfluentKafka : [rdkafka#producer-1] [CONNECT] [7] [[thrd:ssl://xyzserver:9093/bootstrap]: ssl://xyzserver:9093/bootstrap: broker in state DOWN connecting]

I know server is up as I can connect to it from another tool.

How to reproduce
================
My configuration to connect is:
    security.protocol: "SSL"
    ssl.ca.location: "c:\\certs\\LinuxCert"

Please confirm if i can specify the truststore location using config. I don't need client authentication at this point.  

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ashishbhatia22** [comment]
ssl.ca.location is set to
 ssl.ca.location: "c:\\certs\\LinuxCert\\ca-root.crt"

**Comment by ashishbhatia22** [comment]
Please confirm if there is a setting to specify the truststore in config file.

**Comment by mhowlett** [comment]
I wrote the following some time back, but it hasn't made it into the repo yet. it's relevant:
https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security

**Comment by ashishbhatia22** [comment]
Thanks Matt! I followed this article to enable SSL on Kafka. After the changes, server was started successfully. As a next step, I was trying to connect my confluent client to write a message to the bus. Can you confirm what settings are required to enable this? Is there a setting to specify the trust store location.

settings I have now 
security.protocol: "SSL"
ssl.ca.location: "c:\certs\LinuxCert"

**Comment by mhowlett** [comment]
'trust store' is a java concept, it's not relevant here. that document describes in detail how to configure the .net client.

**Comment by ashishbhatia22** [comment]
Matt,

I have followed the document and it doesn't work. Can you validate the instructions?

On Sep 18, 2018, at 04:32 PM, Matt Howlett <notifications@github.com> wrote:

'trust store' is a java concept, it's not relevant here. that document describes in detail how to configure the .net client.

**Comment by ashishbhatia22** [comment]
Can you validate the settings that are required? Just entering this setting will not work
ssl.ca.location: "c:\certs\LinuxCert\ca-root.crt"

**Comment by ashishbhatia22** [comment]
I am using the following version
<package id="Confluent.Kafka" version="0.11.4" targetFramework="net462" />
Please confirm if the SSL is supported in this version

**Comment by ashishbhatia22** [comment]
@mhowlett - Can you please confirm which version of package supports SSL? I have a Kafka instance running SSL. Need to connect with .NET client to read./write messages over SSL

**Comment by mhowlett** [comment]
all versions of the .net client support SSL

**Comment by ashishbhatia22** [comment]
@mhowlett - Can you confirm the entries required for config file:
ssl.ca.location: "c:\certs\LinuxCert\ca-root.crt"

We are getting this error:
2018-09-19 11:29:32,847 [15] DEBUG MessageBusProducer [(null)] - ConfluentKafka : [rdkafka#producer-1] [BROKERFAIL] [7] [[thrd:ssl://USATLRD517.am.bm.net:9093/bootstrap]: ssl://USATLRD517.am.bm.net:9093/bootstrap: failed: err: Local: SSL error: (errno: No error)]

**Comment by ashishbhatia22** [comment]
The SSL settings that I have on Kafka server are:
listeners=SSL://USATLRD517.am.bm.net:9093
ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
ssl.keystore.location=../certs/server.keystore.jks
ssl.keystore.type=JKS
ssl.keystore.password=Landis123
ssl.key.password=Landis123
security.inter.broker.protocol=SSL
ssl.truststore.password=Landis123
ssl.truststore.location=../certs/server.truststore.jks

Server comes up fine and I can connect to this server from a Java app. For Java app, I specified the truststore location.

**Comment by ashishbhatia22** [comment]
Please ignore this. Issue was with incorrect root certificate. I had to add the CA public key certificate to server.truststore

**Comment by sushilsk** [comment]
> Please ignore this. Issue was with incorrect root certificate. I had to add the CA public key certificate to server.truststore

Hi , can u please send me the configuration u are using on .net side to connect to kafka over ssl . i am getting same error  failed: err: Local: SSL error: (errno: No error)]  . not sure whats the issue . 

verified the verificate is correct .

Many Thanks
sushil

**Comment by mrkannan3** [comment]
I am getting the same issue "err: Local: SSL error: (errno: No error)]". I followed the "https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security" link for certificate creation. Its working well with local setup (through docker and windows kafka as well) but its not working as soon as I moved the certificate to dev server (its a linux). any help would be greatly appreciated.

**Comment by MirzaAli-Baig** [comment]
I am facing above mentioned issue. Neither I have good experience on certificate nor with Kafka. I have keystore.jks and truststore.jks. I find the three cert in Keystore.jks using keytool Explorer. One is ca,other ica (both are trusted Certificate Entry ) and third one is Key Pair entry in keystore .jks. I can't understand which certificate need to be used
