### ISSUE TITLE
Broker metadata does not include topic on single machine

### ISSUE THREAD

**Issue by ChrisZollinger** [confluentinc/confluent-kafka-dotnet#627]
Description
===========

Broker metadata does not include topic so the subscription fails and the consumer just waits indefinitely for it (Windows 2016).  However, if I run the same application on another machine (windows 8) I have no problem getting the metadata back and everything works fine.  

How to reproduce
================

This is a pretty simple app...here is the code...

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Confluent.Kafka;
using Confluent.Kafka.Serialization;
using Newtonsoft.Json.Linq;

namespace KafkaConsoleConsumer
{
    class Program
    {
        public static void Main(string[] args)
        {
            var prodConfig = new Dictionary<string, object>
            {
               { "group.id", "test-prod-consumerZ" }, 
                 { "bootstrap.servers", ":443" }, 
                { "security.protocol", "SSL" },
                { "ssl.ca.location", @"" }, 
                { "ssl.certificate.location", @"" }, 
                { "ssl.key.location", @"" },  
                { "ssl.key.password", @"XXXXXXX" }, 
                { "auto.commit.interval.ms", 5000 }, //offsets will get commited every 5 seconds
                { "auto.offset.reset", "earliest" },
                { "debug", "all"}

            };

            System.IO.File.WriteAllText(System.IO.Path.Combine(Environment.CurrentDirectory, "config.txt"), Newtonsoft.Json.JsonConvert.SerializeObject(prodConfig));
            var configString = System.IO.File.ReadAllText(System.IO.Path.Combine(Environment.CurrentDirectory, "config.txt"));
            var config = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, object>>(configString);

            Consume(config, new [] { "OCXI" }, false);
            //Consume(devConfig, "clvtest01", false);
            //Produce(prodConfig);

        }

        private static void Produce(Dictionary<string, object> conf)
        {
            using (var producer = new Producer<Null, string>(conf, null, new StringSerializer(Encoding.UTF8)))
            {
                var dr = producer.ProduceAsync("EMMOUTBOUND", null, "test message text").Result;            
                Console.WriteLine($"Delivered '{dr.Value}' to: {dr.TopicPartitionOffset} | {dr.Error.Reason}");
                while (true)
                {
                }
            }
        }

        private static void Consume(Dictionary<string, object> conf, IEnumerable<string> topics, bool seekToBeginning = false)
        {
            long numberOfPolls = 0;
            long offsetNumber = 0;
            long messagesRead = 0;
            var errorsList = new List<string>();
            var logList = new List<string>();
            bool partionsHaveBeenAssigned = false;
            using (var consumer = new Consumer<string, string>(conf, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
            {
                consumer.OnMessage += (_, msg)
                    =>
                {
                    numberOfPolls = 0;
                    offsetNumber = msg.Offset.Value;
                    messagesRead++;

                    try
                    {
                        
                        var message = JObject.Parse(msg.Value);
                        var tenant = message["tenant"];

                        var messageLog = $" From: {msg.TopicPartitionOffset} \r\n Message: \r\n {msg.Value} \r\n";
                        System.IO.File.AppendAllText(System.IO.Path.Combine(Environment.CurrentDirectory,tenant + "_" + msg.Topic + ".txt"), messageLog);

                    }
                    catch
                    {
                        System.IO.File.AppendAllText(System.IO.Path.Combine(Environment.CurrentDirectory, "MessageReadingErrors.txt"), msg.Value);
                    }
                };

                consumer.OnError += (_, error)
                    =>
                {
                    numberOfPolls = 0;
                    errorsList.Add($"Error: {error}");
                    System.IO.File.WriteAllLines(System.IO.Path.Combine(Environment.CurrentDirectory, "KafkaErrors.txt"), errorsList);
                };

                consumer.OnConsumeError += (_, msg)
                    =>
                {
                    numberOfPolls = 0;                   
                    errorsList.Add($"Consume error ({msg.TopicPartitionOffset}): {msg.Error} {msg.Error.Code} {msg.Error.IsBrokerError} {msg.Error.IsLocalError} {msg.Error.Reason} ");
                    System.IO.File.WriteAllLines(System.IO.Path.Combine(Environment.CurrentDirectory, "KafkaErrors.txt"), errorsList);
                };

                consumer.OnPartitionsAssigned += (sender, list) =>
                {
                    partionsHaveBeenAssigned = true;
                    if (seekToBeginning)
                    {
                        var beginningTopicPartitionOffset = new List<TopicPartitionOffset>();
                        foreach (var topicPartition in list)
                        {
                            var position = new TopicPartitionOffset(topicPartition, Offset.Beginning);
                            beginningTopicPartitionOffset.Add(position);
                        }
                        consumer.Assign(beginningTopicPartitionOffset);
                    }
                    else
                    {
                        consumer.Assign(list);
                    }
                } ;

                consumer.OnLog += (sender, log) => 
                {
                    logList.Add(log.Message);
                };

                consumer.Subscribe(topics);

                while (true)
                {
                    numberOfPolls++;
                    //Console.Clear();
                    if (!partionsHaveBeenAssigned)
                    {
                        Console.WriteLine("Awaiting partition assignment from broker.  It has been {0} seconds.", (numberOfPolls * 100) / 1000);
                    }
                    else
                    {
                        Console.WriteLine("Paritions Assigned ({0}): Topics: {1} Partition: {2}  ", consumer.Assignment.Count, string.Join(",", consumer.Assignment.Select(x => x.Topic).ToList()), string.Join(",", consumer.Assignment.Select(x => x.Partition).ToList()));
                        Console.WriteLine("Polling for more messages.  It has been {0} since our last message. ", (numberOfPolls * 100) / 1000);
                    }
                    
                    Console.WriteLine("Messages read so far {0} | Offset {1} ", messagesRead, offsetNumber);
                    Console.WriteLine("Number of errors so far {0}", errorsList.Count);
                    System.IO.File.WriteAllLines(System.IO.Path.Combine(Environment.CurrentDirectory, "KafkaLog.txt"), logList);

                    consumer.Poll(TimeSpan.FromMilliseconds(1000));
                }
            }
        }

        private static void Consumer_OnPartitionEOF(object sender, TopicPartitionOffset e)
        {
            throw new NotImplementedException();
        }

        private static void Consumer_OnPartitionsRevoked(object sender, List<TopicPartition> e)
        {
            throw new NotImplementedException();
        }

        private static void Consumer_OnLog(object sender, LogMessage e)
        {
            throw new NotImplementedException();
        }
    }
}

Checklist
=========
Please provide the following information:

 - [] Confluent.Kafka nuget version: 0.11.4 
 - [ ] Apache Kafka version: 
 - [ ] Client configuration: 

                { "group.id", "test-prod-consumerZ" }, 
                 { "bootstrap.servers", ":443" }, 
                { "security.protocol", "SSL" },
                { "ssl.ca.location", @".crt" }, 
                { "ssl.certificate.location", @".crt" }, 
                { "ssl.key.location", @".key" },  
                { "ssl.key.password", @"XXXXXXX" }, 
                { "auto.commit.interval.ms", 5000 }, //offsets will get commited every 5 seconds
                { "auto.offset.reset", "earliest" },
                { "debug", "all"}

 - [ ] Operating system: windows 2016
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
please try 0.11.6-RC2, at a quick glance it looks like it might be related to #615 (and similar), though this was not a problem in 0.11.4 which you state you're using.

**Comment by ChrisZollinger** [comment]
Installing 0.11.6-RC2 fixed the issue...thank you!  I had 0.11.5 (latest stable) installed not 0.11.4...fat fingered that in the post.

Thanks again
