### ISSUE TITLE
strongly typed config properties that are enum types throw an exception when read

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#631]
to work around this issue, use the `Get` method, or `Dictionary<string, string>` to specify your configuration.

**Comment by AndyPook** [comment]
Are these kinds of issues "up for grabs"? Or are they being swept up into the big revamp PR?

**Comment by mhowlett** [comment]
go for it on this one! the way to do this is target the mhowlett/gooderr branch, which is 5 PR levels deep on top of master, then when everything is merged up to master retarget the PR to master (and there won't be any issues). thanks for the help!
