### ISSUE TITLE
AnyCPU Issue with Confluent.Kafka DLL (it switches project to x86)

### ISSUE THREAD

**Issue by DHirani** [confluentinc/confluent-kafka-dotnet#633]
Description
===========
When I reference Confluenct.Kafka.dll in my AnyCPU project, the binary is now x86 when it should be msil.

How to reproduce
================
Just create a C# Project as DLL and make sure its AnyCPU then add reference to Confluenct.Kafka.dll, then compile it and you will see it will be stamped as x86 rather than msil, if you remove the reference then it will be compiled as msil.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.4 and 0.11.5
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by DHirani** [comment]
I've tried version 1.0.0-beta and it works correctly, just an issue in the stable version.

**Comment by mhowlett** [comment]
good to know, thanks! closing as it's not something will fix in 0.11.x.
