### ISSUE TITLE
How do I check if the Kafka connection is loss and to reconnect

### ISSUE THREAD

**Issue by DHirani** [confluentinc/confluent-kafka-dotnet#634]
Description
===========
For any open Producer or Consumer, is there way to check if the Kafka connection is down and to issue a reconnect.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the client will automatically recover (reconnect) from all errors not marked as fatal (note: the `IsFatal` property on `ErrorEvent` is new in 1.0-beta). The only fatal errors currently are related to the idempotent producer (not yet in a release).

You can get information about whether there are connectivity issues via the `OnError` event, but you don't need to take action. Documenting all these cases is on our todo list.

**Comment by DHirani** [comment]
I like it, nothing to do.
