### ISSUE TITLE
Upgrading to version 0.11.5 cannot consume msgs

### ISSUE THREAD

**Issue by 123g** [confluentinc/confluent-kafka-dotnet#637]
Description
===========
Cannot consume messages after upgrading. Had the similar issue when we upgraded to 0.11.4 but this time I log the debug before rebooting the servers to see if there is a way of what is happening.

How to reproduce
================
Upgraded the c# app to 0.11.5 and cannot consume messages.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.5
 - [ ] Apache Kafka version:  2.11-1.1.0
 - [ ] Client configuration: see below
 - [ ] Operating system: windows 7 for client and windows 2008 R2 server
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration) see attached file
 - [ ] Provide broker log excerpts : see below
 - [ ] Critical issue

kafkaConfigCons = new Dictionary<string, object> {
                { "bootstrap.servers", kafkaServers },
                { "group.id", kafkaGrpID},
                { "statistics.interval.ms", 30000 }, 
                { "auto.commit.interval.ms", 2000 }, 
                { "enable.auto.commit", "true" },
                { "log.connection.close", "false" },
                { "default.topic.config", new Dictionary<string, object>()
                        {
                            { "auto.offset.reset", kafkaAutoOffsetReset } 
                        }
                },
                { "compression.codec", "LZ4" },
                };

**Server log**

**Comment by 123g** [comment]
[2018-09-28 16:05:07,020] INFO [GroupMetadataManager brokerId=1] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-09-28 16:06:44,596] INFO [GroupCoordinator 1]: Preparing to rebalance group ACTTRFQA_UL with old generation 2 (__consumer_offsets-44) (kafka.coordinator.group.GroupCoordinator)
[2018-09-28 16:06:47,607] INFO [GroupCoordinator 1]: Stabilized group ACTTRFQA_UL generation 3 (__consumer_offsets-44) (kafka.coordinator.group.GroupCoordinator)
[2018-09-28 16:06:49,604] INFO [GroupCoordinator 1]: Assignment received from leader for group ACTTRFQA_UL for generation 3 (kafka.coordinator.group.GroupCoordinator)
[2018-09-28 16:15:07,053] INFO [GroupMetadataManager brokerId=1] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)


**debug**

**Comment by mhowlett** [comment]
please try 0.11.6-RC2, you may be hitting a known bug related to integer overflow in timing calculations.

**Comment by 123g** [comment]
Still does not work. Seeing the below in the debug
Broker changed state APIVERSION_QUERY -> UP

**Comment by mhowlett** [comment]
`default.topic.config` parameters should be specified at the top level in 0.11.4 onwards. i.e. 

```
kafkaConfigCons = new Dictionary<string, object> {
  { "bootstrap.servers", kafkaServers },
  { "group.id", kafkaGrpID},
  { "statistics.interval.ms", 30000 },
  { "auto.commit.interval.ms", 2000 },
  { "enable.auto.commit", "true" },
  { "log.connection.close", "false" },
  { "auto.offset.reset", kafkaAutoOffsetReset },
  { "compression.codec", "LZ4" },
};
```

i mention that because `auto.offset.reset` may not be behaving as you expect. i'm surprised that's not throwing an exception actually.

**Comment by 123g** [comment]
What do you mean it should be at the top level? Is the below correct? I have a consumer and producer like below.

 var kafkaConfigProducer = new Dictionary<string, object> {
	{ "default.topic.config", new Dictionary<string, object>()
		{
		    { "auto.offset.reset", kafkaAutoOffsetReset },
		    { "acks", "all"}
		}
	},
	{ "bootstrap.servers", kafkaServers },
	{ "debug", "broker" }, 
	{ "enable.auto.commit", "true" },
	{ "log.connection.close", "false" },
	{ "compression.codec", "LZ4" },
	};
    
    
    kafkaConfigCons = new Dictionary<string, object> {
	{ "default.topic.config", new Dictionary<string, object>()
		{
		    { "auto.offset.reset", kafkaAutoOffsetReset }
		}
	},
	{ "bootstrap.servers", kafkaServers },
	{ "group.id", kafkaGrpID},
	{ "statistics.interval.ms", 30000 }, 
	{ "auto.commit.interval.ms", 2000 },
	{ "enable.auto.commit", "true" },
	{ "log.connection.close", "false" },
	{ "compression.codec", "LZ4" },
	};

**Comment by mhowlett** [comment]
i mean don't use "default.topic.config" at all. i wrote the config exactly as it should be in my previous comment. Note that 1.0-beta has a strongly typed api so you can't get it wrong. recommend that.

**Comment by 123g** [comment]
I see it now. Any sample code of how to use "1.0-beta has a strongly typed config api so you can't get it wrong"?

**Comment by 123g** [comment]
Meant to say see the config chnage

**Comment by mhowlett** [comment]
everything on master, the default branch. e.g. the README.md, all the examples.

**Comment by 123g** [comment]
Ok, I will take a look at them. Thank you
