### ISSUE TITLE
Memory Leak with 1.0.0 beta version with CancellationToken

### ISSUE THREAD

**Issue by DHirani** [confluentinc/confluent-kafka-dotnet#638]
Description
===========
When you call ProduceAsync with a CancellationToken it fails to dispose the register CancellationTokenRegister object.

Fixed by PR https://github.com/confluentinc/confluent-kafka-dotnet/pull/640

How to reproduce
================
Call ProduceAsync 1000s time and you will see the memory go up as the CancellationTokenRegister is not disposed.

In source code Producer.cs 
Line 567   cancellationToken.Register(() => handler.TrySetException(new TaskCanceledException()));
You are not disposing the Registered object.

            using (var producer = new Producer<string, string>(config))
            {
                // create a producer of different type that reuses producer's Handle.
                var producer2 = new Producer<Null, int>(producer.Handle, null, Serializers.Int32);

                // write (string, string) data to topic "first-topic", statically type checked.
                producer.ProduceAsync("TEST.ABC", new Message<string, string> { Key = "my-key-value", Value = "my-value" });

                // write (null, int) data to topic "second-data". statically type checked, using
                // the same underlying client as producer.
                producer2.ProduceAsync("TEST.ABC", new Message<Null, int> { Value = 42 });

                Console.WriteLine("Start");

                CancellationTokenSource source = new CancellationTokenSource();
                for (var i = 0; i < 100000; i++)
                {
                    // producers are not tied to topics. Although it's unusual that you might want to
                    // do so, you can use different producers to write to the same topic.
                    producer2.ProduceAsync("TEST.ABC", new Message<Null, int> {Value = 107 + i}, source.Token);

                    // As the ProducerAsync tasks are not waited on there will still be messages in flight.
                    producer.Flush(TimeSpan.FromMilliseconds(1));
                    Thread.Sleep(1);
                }

                Console.WriteLine("Done");
                Console.Read();
            }

https://docs.microsoft.com/en-us/dotnet/standard/threading/how-to-register-callbacks-for-cancellation-requests

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks @DHirani - we'll include your PR in beta2. we won't release beta2 immediately - there are some other changes I want to get in it as well. for now, please follow the instructions in my comment in #640 to get the build corresponding to your PR.

**Comment by mhowlett** [comment]
beta2 is out.
