### ISSUE TITLE
Where is CommitAsync?

### ISSUE THREAD

**Issue by sublee** [confluentinc/confluent-kafka-dotnet#639]
Before this issue, thank you for making a great and friendly library.

Description
===========

[The documentation](https://docs.confluent.io/current/clients/confluent-kafka-dotnet/api/Confluent.Kafka.Consumer-2.html) says `Consumer<Tkey, TValue>` has `CommitAsync` for the TAP style. But I couldn't find this method in `v1.0-beta`. Also, I couldn't find any news on removing `CommitAsync` at [CHANGELOG.md](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/CHANGELOG.md).

![image](https://user-images.githubusercontent.com/19982/46285906-1adac780-c5b8-11e8-920d-695a3804846c.png)

Actually, I found `CommitAsync` in `v0.9.4`. But the documentation doesn't specify its targetting version. And there's no explanation why is it removed. So it's confusing me.

How to reproduce
================

1. Visit the documentation. Go to `Consumer<TKey, TValue>`. Find `CommitAsync`. It exists.
2. Search `CommitAsync` in the source code. It doesn't exist.
3. Visit the change log. Find news on removing `CommitAsync`. It doesn't exist.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: `1.0-beta` (the recommended version)
 - [x] Apache Kafka version: didn't install yet
 - [x] Client configuration: didn't configure yet
 - [x] Operating system: Windows 10
 - [x] Provide logs (with "debug" : "..." as necessary in configuration) - I've never run it yet.
 - [x] Provide broker log excerpts - I've never run it yet.
 - [x] Critical issue - I want to use it in the TAP style.

**Comment by mhowlett** [comment]
behind the scenes, `CommitAsync` was implemented using `Task.Run`, which is an anti-pattern. this would be ok if our vision was to ultimately make a fully async consumer API with proper implementations of all the related methods, but we are not going to do this in 1.0. First, there is quite a bit of work to make this happen. Second, there are limited scenarios in which this is useful (it's much less needed in practice than an async producer). 

For now, if you really do want this behavior, use `Task.Run` to call the `Consumer.Commit` method (which is what the old implementation did).

**Comment by sublee** [comment]
Thank you for the clear explanation.
