### ISSUE TITLE
0.9.4-preview2 makes package dependent on netcoreapp1.0

### ISSUE THREAD

**Issue by thinktainer** [confluentinc/confluent-kafka-dotnet#64]
The latest nuget package seems to be a step backwards in the dependency requirements of the package metadata. Where 0.9.2 was dependent on netstandard1.3 which supports using this package in for example library projects, the latest version specifies netcoreapp1.0. This also stops it from being used in projects that target netcoreapp1.0 (or I didn't understand how to target an older framework).

**Comment by thinktainer** [comment]
I see that this has been fixed as part of #57. Happy to close, or leave as reminder to release new packages to nuget.

**Comment by mhowlett** [comment]
yes, this was a mistake. a new nuget package is coming hopefully today with some important changes.

**Comment by thinktainer** [comment]
Thank You!
