### ISSUE TITLE
Request.timeout.ms not considered during ProducerAsync()/BeginProduce()

### ISSUE THREAD

**Issue by Tenseiga** [confluentinc/confluent-kafka-dotnet#642]
Description
===========
Hi All,

I have set up the 
request.timeout.ms=5000
retries=2,
message.timeout.ms=30000
max.block.ms=1
Acks=1
Linger.ms=0

Expected:
When I disabled the broker, the timeout should happen after 10th second

Actual:
the timeout happens only after 30th second with an exception 'Local message time out' , which is due to the 'message.timeout.ms' timeout

Question:

1.The documentation says for message.timeout.ms says 'Delivery error occurs when either the retry count or the message timeout are exceeded.' 
and the documentation for request.timeout.ms - 'The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted.'

So if my understanding is correct, the producer should fail before 30 seconds, due to the retry time out
But that is not what is happening. 

Note: 
I have set the retry count also to 1, same thing happens.
I have set the 'MetadataRequestTimeoutMs' so to check if the timeout happends during the metadata fetch, but this also has no effect.
I have set the max.block.ms to 1

2. How to know if a retry is happening

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [2.0 ] Apache Kafka version: 
 - [ 1.02 experimental 13] Client configuration:
 - [windows ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by Tenseiga** [comment]
Hi @mhowlett any info pls?

**Comment by mhowlett** [comment]
`request.timeout.ms` is the time the client will wait for a response to a request it sent to a broker. what you're missing is that if the required broker is down, the client will never send a request (it can't) so this config value isn't relevant. the timeout for the produce call will be determined by `message.timeout.ms`.
