### ISSUE TITLE
Question on the best way to use the consumer API

### ISSUE THREAD

**Issue by sean-buchanan** [confluentinc/confluent-kafka-dotnet#644]
Please redirect me if this is not a good forum for questions.

It's more efficient for my consumer to process messages in batches. I'd like to get 500 messages are so, process them and then commit my offset once I know the processing was successful. 

It seems using the Consume method is the easier way to go about this. I can tell it what offset to start at. I can easily control how my messages I read. And I can save my offset where my output is. (That way if I have to restore the database my output is, the offset gets restored with it.)

Question:
1. The intellisense for the Consumer method says this method is unstable and the Poll() method should be used instead. Is this still the case? If using Poll() is preferred, and assuming I'm managing the offset myself (and storing it with my output), how do I start from a particular offset when using Poll. It looks like the only way to use Poll is for the Kafka API to track the offset for me.

**Comment by mhowlett** [comment]
In the 1.0 API, it is in fact the `Poll` method which has been depreciated, so use `Consume`. You can start consuming from a particular offset by using the `Assign` method from within an `OnPartitionsAssigned` event handler. If you're using 0.11.x build make sure you call `Assign` in both `OnPartitionsAssigned` / `OnPartitionsRevoked` if you call it at all. In the 1.0 API, you don't need to.
