### ISSUE TITLE
.net framework 3.5

### ISSUE THREAD

**Issue by Rymix** [confluentinc/confluent-kafka-dotnet#649]
Hi,

Is there anyway to get this version working on .NET framework 3.5 ?

Thank you for your great work on this lib.

R.A

**Comment by mhowlett** [comment]
sorry @Rymix, we have no plans for backwards compatibility with .net framework 3.5.

**Comment by BitterDone** [comment]
@mhowlett can you clarify - is there any version of Kafka that will work with .NET framework 3.5?

**Comment by mhowlett** [comment]
there is no version of this client that is compatible back that far. also, i'm not aware of any alternative that is.

**Comment by BitterDone** [comment]
@mhowlett Thank you for the clarification!

To anyone who lands here in the future, I'm finding success with basic C# sockets:
https://www.geeksforgeeks.org/socket-programming-in-c-sharp/
