### ISSUE TITLE
Check if Commit method successful

### ISSUE THREAD

**Issue by issatayev** [confluentinc/confluent-kafka-dotnet#650]
Description
===========
Previously, in version 0.11.5, I could check if Commit method resulted in no errors by doing this:

if (committedOffsets.Error.Code == ErrorCode.NoError) {}

How can I check in version 1.0.0-beta2 that Commit method resulted in no errors?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
A big change in 1.0 is exceptions are used to report most errors. This is more idiomatic and people were often omitting to check for errors where the should have been. Commit will throw a `TopicPartitionOffsetException`.

Now you ask, i'm thinking the exception name should be different, probably `CommitException` (though this will derive from `TopicPartitionOffsetException` with no changes). I'll likely make that change before 1.0.

**Comment by issatayev** [comment]
Thanks! If I wrap call to Commit method like this, will be sufficient right?

try
{
    var committedOffset = consumer.Commit(consumeResult);
}
catch(TopicPartitionOffsetException ex)
{
    Console.WriteLine($"Failed to commit an offset: [{ex.Message}]");
}

**Comment by issatayev** [comment]
Also, if ProduceAsync method fails, will it throw KafkaException? If no exceptions, then produce was successful?

**Comment by mhowlett** [comment]
yep. and yep, it'll throw an exception derived from KafkaException.

**Comment by milindl** [comment]
Closing this as the question was answered by Matt.
