### ISSUE TITLE
Increasing producing speed

### ISSUE THREAD

**Issue by RomainAn** [confluentinc/confluent-kafka-dotnet#651]
Description
===========

Hi, do you have an example of configuration that is increasing the producing speed of a message ?
`ProducerConfig config = new ProducerConfig { BootstrapServers = _configuration["Kafka:BrokerList"], SocketNagleDisable = true, SocketBlockingMaxMs = 1, QueueBufferingMaxMessages = 1, BatchNumMessages = 1 };
`
It's a little bit slow compare to the 0.11.6 version of the Kafka Lib (I already got a configuration for that)
For producing 1000 messages, i'm actually spending 39 secondes.

 - [ ] Confluent.Kafka nuget version: 1.0.0-beta2
 - [x] Operating system: W10

**Comment by mhowlett** [comment]
so about 25 msg/s - you must be producing synchronously. Note that we don't optimize for this. maybe try setting `LingerMs` to `0`.

**Comment by Rymix** [comment]
Hi, thank you for your help and advices.
Actually i forgot an Await in my code, the real time for 1000 messages is between 6 minutes and 8 minutes.
Even i added LingerMs = 0.
Maybe the only way to increase the speed is to build a list of Task and await at the end.

**Comment by mhowlett** [comment]
yes, the only way to produce quickly is not wait on a produce request before issuing the next.

**Comment by Rymix** [comment]
Okay i just found how to optimize all of that using a singleton and removing a using a single producer, it's makes the 1000 messages sended in 12 seconds (awaited).

**Comment by milindl** [comment]
Closing this as the original question was answered.
