### ISSUE TITLE
There is no way to know if a partition is EOF when using IConsumer

### ISSUE THREAD

**Issue by sfwester** [confluentinc/confluent-kafka-dotnet#655]
Description
===========
The changelog for 1.0.0-beta states:

> The `Consumer.OnPartitionEOF` event has been removed. You should inspect the ConsumeResult instance returned from `Consumer.Consume` instead.

and `OnPartitionEOF` has been removed from `IConsumer`.

However, the change where `Consumer.Comsume` returns a `ConsumeResult` instead of `null` has not been made in 1.0.0-beta*. The change is only in 1.0-experimental-10.

So currently in 1.0.0-beta2 we do not have a way to know if our partitions are at EOF when using the `IConsumer` interface.

My overarching use case is to track when all my partitions have been consumed. When that is the case, and I know my producer is done, then I would like to shut down. Is there a different mechanism I should be using for this?

How to reproduce
================
Start consuming on an empty topic and you will receive a null response.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0-beta2

**Comment by mhowlett** [comment]
The `OnPartitionEOF` event is there. There was some back-and-forth on how best to expose this and the changelog reflects an intermediate state - sorry, I will update this.

**Comment by sfwester** [comment]
`OnPartitionEOF` does exist on the `Consumer` class but it does not exist on the `IConsumer` interface. Should it be added back to the interface?

**Comment by mhowlett** [comment]
oh right, yes. that's a mistake. It'll be in beta3.

**Comment by edenhill** [comment]
It sounds like the unit tests need to be extended to cover all APIs using IConsumer as well, @mhowlett?

**Comment by mhowlett** [comment]
@sfwester - thanks for pointing this out - I've slipped both additions to `IConsumer` into #656. More complete testing is coming.

**Comment by sfwester** [comment]
Great thanks @mhowlett! Are there more changes planned for beta-3 or just 656?

**Comment by mhowlett** [comment]
it'll just be #656 - it's a fairly big deviation from the existing functionality so I want to get it out as a priority. After that, it'll be miscellaneous smaller things.

**Comment by milindl** [comment]
Closing this issue as the PR has been merged.
