### ISSUE TITLE
Should the SerializerGenerator generate the same object for each call?

### ISSUE THREAD

**Issue by allan-silva** [confluentinc/confluent-kafka-dotnet#657]
Description
===========
I'm using the `Generators.UTF8` in both Key/Value to serialize. Once it is a generator, is it right generate the same object per call?

How to reproduce
================
Any child class:
```
     

    public abstract class StringProducer : KafkaProducer<string, string>, IStringProducer
    {
        public StringProducer(string topic, IEnumerable<KeyValuePair<string, string>> config) :
            base(topic, config, Generators.UTF8, Generators.UTF8)
        {
        }
    }
```

Base class:
```
        public KafkaProducer(string topic, IEnumerable<KeyValuePair<string, string>> config,
            SerializerGenerator<TKey> keySerializer, SerializerGenerator<TMessage> valueSerializer)
        {
            _topic = topic;
            _producer = new Producer<TKey, TMessage>(config, keySerializer, valueSerializer);
        }
```

Equivalent to:
```
var producer = new Producer<string, string>(config, Generators.UTF8, Generators.UTF8);
```
Fails at:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/v1.0-beta2/src/Confluent.Kafka/Producer.cs#L169-L171

https://github.com/confluentinc/confluent-kafka-dotnet/blob/v1.0-beta2/src/Confluent.Kafka/Producer.cs#L74-L77

Edit: 
This also applies to deserializers.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2 
 - [ ] Apache Kafka version: NA
 - [ ] Client configuration: NA
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
First: I've just opened a PR that revamps how serialization works that will be in -beta3. It's much better and easier to use. 'generators' don't exist anymore. There were various problems with the way serialization worked in 0.11.6 and what's in -beta2 is halfway towards fixing that, but it has it's own problems which i've now addressed. https://github.com/confluentinc/confluent-kafka-dotnet/pull/656

But in -beta2 - the generators are really only useful for avro. for strings you should be just using serializers.

**Comment by allan-silva** [comment]
Got it. Thanks!
