### ISSUE TITLE
EntryPointNotFoundException

### ISSUE THREAD

**Issue by issatayev** [confluentinc/confluent-kafka-dotnet#658]
Description
===========
I have upgareded my consumer code to handle version 1.0.0-beta2. The problem is when I run it, and try consume messages, I get the following exception:

[System.EntryPointNotFoundException: Unable to find an entry point named 'rd_kafka_destroy_flags' in shared library 'librdkafka'.
   at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_destroy_flags(IntPtr rk, IntPtr flags)
   at Confluent.Kafka.Impl.SafeKafkaHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalDispose()
   at Confluent.Kafka.Impl.SafeKafkaHandle.Dispose(Boolean disposing)
   at Confluent.Kafka.Consumer`2.Dispose(Boolean disposing)
   at Confluent.Kafka.Consumer`2.Dispose()        

Can you help me to figure out why I get this exception, please?

How to reproduce
================
Here is my method for consuming:

        private static void RunConsumer(ConsumerConfig consumerConfig, List<string> topics)
        {
            try
            {
                using (var consumer = new Consumer<string, OutboundMessage>(consumerConfig, Deserializers.UTF8, MessageDeserializer.Deserialize))
                {
                    consumer.Subscribe(topics);

                    var consuming = true;

                    consumer.OnError += (_, e) =>
                    {
                        Console.WriteLine($"Error: [{e.Reason}]");
                        consuming = !e.IsFatal;
                    };

                    while (consuming)
                    {
                        try
                        {
                            var consumeResult = consumer.Consume();
                            // Here I have some business logic, and calling Commit method at some point
                        }
                        catch (ConsumeException ex)
                        {
                            Console.WriteLine($"Consume error: [{ex.Error.Reason}]");
                        }
                    }

                    // Ensure the consumer leaves the group cleanly and final offsets are committed.
                    consumer.Close();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"{ex.ToString()}");
            }
        }

Here my custom message deserializer:

    public static class MessageDeserializer
    {
        public static OutboundMessage Deserialize(string topic, ReadOnlySpan<byte> data, bool isNull)
        {
            using (MemoryStream stream = new MemoryStream(data.ToArray()))
            {
                var serializer = new DataContractJsonSerializer(typeof(OutboundMessage));

                return (OutboundMessage)serializer.ReadObject(stream);
            }
        }
    }

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
it looks to me like it's loading an earlier version of librdkafka (the method it's having a problem with is relatively new). are you referencing `librdkafka.redist` explicitly in you .csproj file? if so, remove that. if you have librdkafka installed on your system anywhere, remove that as well.

**Comment by issatayev** [comment]
@mhowlett  Thanks for answering. I found the problem. I am running application in docker under alpine. Currently, the latest version for librdkafka in Apline Linux packages is 0.11.6-r0. 

When approximately will stable version 1.0.0 of librdkafka.redist be released? And do you know how long will it take to be added to Alpine Linux packages?

**Comment by mhowlett** [comment]
@edenhill - another +1 for alpine linux in nuget. it's one of two standard .net docker images from microsoft.

.net 1.0 is about 1 or 2 months away.
