### ISSUE TITLE
System.DllNotFoundException: Failed to load the librdkafka native library.

### ISSUE THREAD

**Issue by vikasillumina** [confluentinc/confluent-kafka-dotnet#659]
Description
===========

`/usr/local/share/dotnet/dotnet /Users/vikas/RiderProjects/ConsoleApp1/ConsoleApp1/bin/Debug/netcoreapp2.1/ConsoleApp1.dll

Unhandled Exception: System.DllNotFoundException: Failed to load the librdkafka native library.
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Producer..ctor(IEnumerable`1 config)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, SerializerGenerator`1 keySerializerGenerator, SerializerGenerator`1 valueSerializerGenerator)
   at ConsoleApp1.Program.Main(String[] args) in /Users/vikas/RiderProjects/ConsoleApp1/ConsoleApp1/Program.cs:line 18

Process finished with exit code 6.`

How to reproduce
================
1. Make a console application using dotnet core 2.1.403
2. In the program.cs just add following code:

*****Code starts here*******
using System.Collections.Generic;
using Confluent.Kafka;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {   
            Producer<string, byte[]> _producer = new Producer<string, byte[]>(new Dictionary<string, string>());
        }
    }
}`
*****Code ends here*******

3. Build and run the application.
4. On running the application above error is thrown and dotnet core crashes.

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2
 - [x] Apache Kafka version: Not relevant since its not even connecting yet to Kafka but we are using 1.0 but would need to confirm this if its really needed
 - [ ] Client configuration:
 - [x] Operating system: Mac OSX 10.13.6 (17G65)
 - [x] Provide logs (with "debug" : "..." as necessary in configuration) Provided above
 - [x] Provide broker log excerpts- Not connected to Kafka yet
 - [x] Critical issue - Blocking the development of features that interacts with Kafka

**Comment by mhowlett** [comment]
it seems like you'll need to provide serializers in the constructor (probably indicating a bug in this code). note that the way serialization works has been revamped in -beta3 and this problem will no longer exist. beta3 will hopefully be out within a week. for now you could consider referencing: https://ci.appveyor.com/project/ConfluentClientEngineering/confluent-kafka-dotnet/builds/19776967 (for further instructions refer to the readme.md).

**Comment by vikasillumina** [comment]
Thanks @mhowlett for your quick response. I will try out the beta3 library.

**Comment by SebastianStehle** [comment]
I have the same problem with the Docker and Kubernetes. My base image is `microsoft/dotnet:2.1-runtime-deps-alpine`. Works fine under Windows.

**Comment by mhowlett** [comment]
unfortunately we don't yet support alpine linux out of the box, though including a compatible build of librdkafka in librdkafka.redist is up there on the priority list. As a work-around, you could compile librdkafka yourself and use `Library.Load`.

**Comment by SebastianStehle** [comment]
Thanks it works with a "non-alpine-image"

**Comment by vikasillumina** [comment]
I was playing around with different versions of Kafka Confluent and the one currently being used is older than the beta2, precisely '1.0.0-experimental-12'. We should probably upgrade but sometime later in this month. But the issue was same with the loading the librdkafka. After digging around with my other team member for whom the same application was working fine, we found that I was missing Openssl. After installing it my error went away. Wish the error message was more accurate.
![image](https://user-images.githubusercontent.com/8878754/48085263-9975e680-e1ae-11e8-88f5-9ca7fdfe65b7.png)
Above is the screenshot of loc where it was failing for and would say couldn't find librdkafka but it was openssl which I believe is the dependency of librdkafka. Hope this helps someone else.

**Comment by ratri-git** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/issues/778#issuecomment-560225446
