### ISSUE TITLE
[Question] What is the purpose of group.id, simple-cshar-consumer, bootstrap.servers?

### ISSUE THREAD

**Issue by jeffreycruzana** [confluentinc/confluent-kafka-dotnet#66]
I'm totally new at this and was wondering what should I replace these with?

 var config = new Dictionary<string, object>
            {
                { **"group.id", "simple-csharp-consumer**" },
                { "**bootstrap.servers**", brokerList }
            };

**Comment by mhowlett** [comment]
Consumers are usually part of consumer-groups (which have a unique id - group.id). 

When you connect to a kafka cluster you specify one (or more for redundancy) brokers in the cluster on initialisation ('bootstrap.servers'). The client communicates with these brokers to determine the address of all other brokers that it needs to communicate with, and will do so directly as needed.

the blog post below is about the java client, which is a bit different to this, but you might find it useful as a general kafka overview: 

https://www.confluent.io/blog/tutorial-getting-started-with-the-new-apache-kafka-0-9-consumer-client/

**Comment by jeffreycruzana** [comment]
What if I have more than 1 broker? How do I set more than 1 broker in 'bootstrap.servers'?

**Comment by ewencp** [comment]
@jeffreycruzana Sounds like you answered your own question. I'm going to close this, but if this isn't resolved, feel free to reopen and clarify any remaining questions.
