### ISSUE TITLE
Native Exception can't be handled by .NET core in linux

### ISSUE THREAD

**Issue by badwolfyao** [confluentinc/confluent-kafka-dotnet#661]
Description
===========
I believe Kafka is using librdkafka library, which is a C library. When Kafka brokers are down, or when encountering other kafka error, a native exception will be thrown in the librdkakfa. We are trying to catch this exception in our dotnet core application and handle it gracefully. But when we deploy our dotnet core application in docker/linux, the native exception can't be caught. The application will fail and exit immediately. 

How to reproduce
================
Running dotnet core application in docker/linux using Confluent.Kafka.dotnet, and shut down the Kafka brokers. An exception will be thrown and can't be caught by dotnet code, causing the application to fail immediately .

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [x] Apache Kafka version: Any
 - [x] Client configuration: debug/release
 - [x] Operating system: docker/linux
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [x] Provide broker log excerpts: N/A
 - [ ] Critical issue

**Comment by mhowlett** [comment]
please try version 0.11.6 or 1.0-beta2.

**Comment by milindl** [comment]
Closing this with version upgrades, please reopen if this persists.
