### ISSUE TITLE
consumer.seek() cannot update consumer.Position()

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [confluentinc/confluent-kafka-dotnet#663]
I am expecting that the result of "consumer.Position()" will be updated after calling "consumer.seek(position)".

**Comment by mhowlett** [comment]
This is intended operation https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Consumer.cs#L1019 : 

```
        ///     The offset field of each requested partition will be set to the offset
        ///     of the last consumed message + 1, or Offset.Invalid in case there was
        ///     no previous message consumed by this consumer.
```

there may be a good technical reason why this not next message to be consumed as you are expecting (i don't know without further investigation). I agree that would be more intuitive.
