### ISSUE TITLE
Sending Message to Kafka Rest Proxy topic in Dotnet core Application

### ISSUE THREAD

**Issue by shivashankar-awanti** [confluentinc/confluent-kafka-dotnet#664]
Description
===========
i'm trying to send message to a topic which is exposed by Kafka Rest API, but im unable to send data..is there any example where i can check that.

im getting below error: 

rdkafka#producer-1|METADATA| [thrd:main]: 127.0.0.1:8082/bootstrap: Metadata request failed: connected: Local: Bad message format (952153940ms): Permanent

im not getting what im missing, is there any separate method we need to follow to send data to Kafka Rest Proxy exposed topic?

How to reproduce
================

Im using ProduceAsync method to do the same Producer class of Confluent Kafka.

 string kafkaEndpoint = "127.0.0.1:8082/topics";

                // The Kafka topic we'll be using
                string kafkaTopic = "user";

                // Create the producer configuration
                var producerConfig = new Dictionary<string, object> { { "bootstrap.servers", kafkaEndpoint } };

                // Create the producer
                using (var producer = new Producer<Null, string>(producerConfig, null, new StringSerializer(Encoding.UTF8)))
                {
                    // Send 10 messages to the topic
                    for (int i = 0; i < 10; i++)
                    {
                        var message = $"Event {i}";
                       // var message = "{\"name\": \"Alyssaaa\", \"favorite_number\": {\"int\": 7}, \"favorite_color\": null}";
                        var result = await producer.ProduceAsync(kafkaTopic, null, message);
                        producer.Flush(100);
                        // Console.WriteLine($"Event {i} sent on Partition: {result.Partition} with Offset: {result.Offset}");
                    }
                }

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.6
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
This library doesn't contain functionality for interfacing with the Confluent Kafka REST proxy, it communicates with Kafka brokers directly. To interface with REST Proxy, use the `HttpClient` class instead. https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient

**Comment by shivashankar-awanti** [comment]
@mhowlett Thank you the reference link for webapi client, but can you please provide any reference links for sending and receiving messages from Kafka topics via Rest API.
