### ISSUE TITLE
SSL - Disable Broker certificate check.

### ISSUE THREAD

**Issue by anupkumarsharma** [confluentinc/confluent-kafka-dotnet#665]
Description
===========
Enabling SSL with generate below error. 
{ssl://broker2.aws.com:9092/bootstrap: Failed to verify broker certificate: self-signed certificate in certificate chain (after 356ms in state CONNECT)}

Is there a way I can disable the broker certificate check? 

How to reproduce
================
  BootstrapServers = "broker2.aws.com:9092",
                SslKeystoreLocation = @"C:\certs\MY_FILE.p12",
                SslKeystorePassword = "PassWord",
                SecurityProtocol = SecurityProtocolType.Ssl

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 1.0.0-beta2
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
Here are some docs I started writing up on using the .net client with SSL security some time ago. Hopefully they'll help you get up and running.

https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security
