### ISSUE TITLE
consume time out

### ISSUE THREAD

**Issue by emadghav** [confluentinc/confluent-kafka-dotnet#666]
Description
hi
i start apache kafka with 2 broker in windows server and about a one bilion record in 3 topic 
and consumer offset usually at the end of topic.
when i want consume a topic i have error
[thrd:brokerip:9095/0]: brokerip:9095/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partiall
-sent requests
app01-0#consumer-1
Error Consumer_OnError: {"Code":-185,"Reason":"brokerip:9095/0: 1 request(s) timed out: disconnect (a
ter 62549ms in state UP)","HasError":true,"IsLocalError":true,"IsBrokerError":false}
0
but after some try i can connect to the topic and start consume

Checklist
=========
Please provide the following information:

 - [ 11.6] Confluent.Kafka nuget version:
 - [ 2.0.0] Apache Kafka version: 
 - [
  
            {"enable.auto.commit", false}, // this is the default
            {"session.timeout.ms", 240000},
            {"auto.offset.reset", "smallest"}
        }; 
] Client configuration:
 - [ windows server 2012] Operating system:

**Comment by mhowlett** [comment]
it seems like the connection between client and broker has died. suggest looking at the client (set 'debug' config property to 'broker' or 'all') & kafka broker logs for more information.

**Comment by emadghav** [comment]
brokers is up
i solve this problem ,i shoud dispose consumer when app closing
