### ISSUE TITLE
Exception raised after migrating to Confluent.Kafka(1.0.0-beta2) ... Confluent.Kafka.Kafka Exception: Local: Queue full 

### ISSUE THREAD

**Issue by ghetze** [confluentinc/confluent-kafka-dotnet#667]
Description
===========
HI I have an console application which sends mesages to kafka.
Currently I've migrated the solution from Confluent.Kafka(0.11.6) to Confluent.Kafka(1.0.0-beta2).
By sending the same amount of messages to the same kafka server ...the following error occurs:
Error:Confluent.Kafka.KafkaException: Local: Queue full

How to reproduce
================
The idea of the application is to sent some data read from a database to a kafka topic.
Data is read from the database on batches and for each item from the batch, the ProduceAsync method is called.
We must be sure that all messages(sent in avro) are sent with success and as fast as possible to the kafka topic.

The configuration of the kafka producer is as follows:
_avroconfig = new AvroSerdeProviderConfig
{SchemaRegistryUrl = "some address"};
_avroProvider = new AvroSerdeProvider(_avroconfig);
_producerConfig = new ProducerConfig { BootstrapServers = "some address"};
_producerAvro = new Producer<string, string>(_producerConfig, _avroProvider.GetSerializerGenerator<string>(), _avroProvider.GetSerializerGenerator<string>());

The method who sends messages to kafka is the following :
public void ProduceAsync(string key, string value)
        {
            try
            {
                Task<DeliveryReport<string, string>> deliveryReport = _producerAvro.ProduceAsync(_kafkaSettings.Topic, new Message<string, string> { Key = key, Value = value });
                deliveryReport.ConfigureAwait(false);
                deliveryReport.ContinueWith(task =>
                {
                    try
                    {
                        if (!task.IsCompletedSuccessfully)
                        {
                            _succes = false;
                            _loggerInput.Warn($"Error:{task.Exception.ToString()}");
                        }
                    }
                    finally
                    {
                      Interlocked.Increment(some_variable);
                    }
                });
            }
            catch (KafkaException kex)
            {
                _succes = false;
                _loggerInput.Warn($"Error:{kex.ToString()}");
                throw kex;
            }
        }

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2
 - [x] Apache Kafka version: 0.11
 - [ ] Client configuration:
 - [ ] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
this is by design. In 0.11.6, the async method would block if the librdkafka queue was full which strictly speaking an async method should not do. 0.11.6 was written this way because this is sometimes what you want (but not always). you could replicate the previous behavior by waiting in a loop (with a small sleep) until you don't get an exception. I'll mark this issue as enhancement as it might be good to add a configuration property that enables the previous behavior.

**Comment by ghetze** [comment]
Hi ...thank you for your reply ... but i do not understand the proposes solution that you specified: "you could replicate the previous behavior by waiting in a loop (with a small sleep) until you don't get an exception".

**Comment by ghetze** [comment]
Thank you for you reply...just wanted to add that if you set the MessageSendMaxRetries big enough for the ProducerConfig (i've tested with 100), the internal retry mechanism runs into action and the exception Local: Queue is not generated anymore .

**Comment by 123g** [comment]
Another vote for the enhancement. Have the same issue.  Note that  bumping  MessageSendMaxRetries did not work for me.  Can we do something similar to below?

try {
                kafkaProducer.BeginProduce(kafkaTopic, new Message<Null, string> { Value = messageValue }, kafkaProducerHandler);
            } catch (Confluent.Kafka.KafkaException k)
            when (k.Message.Contains("Local") && k.Message.Contains("Queue full")) {
                var ret = kafkaProducer.Flush(new TimeSpan(1_000));
                while (ret > 1_000) {
                    if (ret > 50_000) { //assuming 50k per second
                        ret = kafkaProducer.Flush(new TimeSpan(1_000));
                    } else {
                        ret = kafkaProducer.Flush(new TimeSpan(300));
                    }
                }
                //resend lost msg
                kafkaProducer.BeginProduce(kafkaTopic, new Message<Null, string> { Value = messageValue }, kafkaProducerHandler);
            }
