### ISSUE TITLE
Hangs on AdminClient.OnLog subscription

### ISSUE THREAD

**Issue by HenningRoigaard** [confluentinc/confluent-kafka-dotnet#670]
I am unable to subscribe to AdminClient.OnLog.

This repro example was created a dotnet core app
```
static void Main(string[] args)
{
      using (var adminClient = new AdminClient(new AdminClientConfig() { BootstrapServers = "localhost:9092" }))
      {
        adminClient.OnLog += (s, e) => Console.WriteLine(e); // <- Hangs
      }
}
```
Due to this, I cannot get any debug output from LibRdKafka to supplement this issue.

When debugging in Visual studio (screenshot below) I see three threads which might be of interest in this context.
![visualstudio_onlogsubscribe_screenshot](https://user-images.githubusercontent.com/25740721/48059391-579e6d80-e1b9-11e8-847a-234261fb7459.png)

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2
 - [x] Apache Kafka version: cp-kafka 3.3.0
 - [x] Client configuration: See code example
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks @HenningRoigaard - have replicated. as a work around for the moment, you can construct an admin client from a producer instance handle. 

```
            using (var producer = new Producer<string, string>(new ProducerConfig { BootstrapServers = "localhost:9092" }))
            using (var adminClient = new AdminClient(producer.Handle))
            {
                adminClient.OnLog += (s, e) => Console.WriteLine(e);
            }
```

**Comment by mhowlett** [comment]
thanks again for your detailed issue reports @HenningRoigaard. This one is now resolved in the above branch. I'll open a PR for it when #656 is in.

**Comment by anchitj** [comment]
Closing as the fix is merged
