### ISSUE TITLE
Consumer Pause and Resume causes records to be skipped

### ISSUE THREAD

**Issue by HenningRoigaard** [confluentinc/confluent-kafka-dotnet#672]
**A little context**
This is the simplified version :) - We are using Kafka as State Store in addition to being an integration point between components. When a service is started we rebuild state by replaying previously processed records from all relevant partitions, before processing new records. To control this process, we use Pause to synchronize replay of partitions, before resuming partitions to enable processing of new records.

**Issue**
Offsets returned by Consumer.Consume is not as expected after Pause and Resume.

In the following example I have manually created a topic "TestTopic" with 1 partition, and produced a single message to it. 
The dotnet core app included below then consumes from the topic using consumer group assignment, and assign from Offset.Beginning during OnPartitionsAssigned, expecting to consume the single message produced during subsequent Consume-loops as well as getting EOF for the partition. 

The app has been executed twice: Once with Pause and Resume, and once without.

In the case **without** Pause/Resume everything works as expected as shown by the following output
```
Beginning consume loop
Assigned 1 partitions
Received TestTopic [[0]] @0
EOF - TestTopic [[0]]1
```
In the case **with** Pause/Resume the Consume-loop skip the message and raise OnEOF for the partition directly as shown by the following output
```
Beginning consume loop
Assigned 1 partitions
EOF - TestTopic [[0]]1
```
Consumer debug logs (Debug = "all") from both cases are included here.
[debugOutput_success.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2553042/debugOutput_success.txt)
[debugOutput_fail.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2553043/debugOutput_fail.txt)

_Note_: To reduce issues related to consumer groups, the two tests was executed using different consumer groups. However, to ease the process of comparing the debug output, I have abstracted away the consumer group name by replacing them with "GROUPID" in both files.

The example below illustrates the issue.

```
class Program
{
    const string connectionString = "localhost:9092";
    const string logFile = @"c:\temp\debug.txt";
    const string topic = "TestTopic";
    
    static void Main(string[] args)
    {
      if (File.Exists(logFile))
        File.Delete(logFile);

      var config = new ConsumerConfig() { BootstrapServers = connectionString, GroupId = Guid.NewGuid().ToString(), Debug = "all" };

      using (var consumer = new Consumer<string, string>(config))
      {
        consumer.OnLog += (s, e) => { lock (logFile) File.AppendAllText(logFile, e.Message + Environment.NewLine); };
        consumer.OnError += (s, e) => Console.WriteLine($"Error - {e}");
        consumer.OnPartitionEOF += (s, e) => Console.WriteLine($"EOF - {e.TopicPartition}{e.Offset}");
        consumer.OnPartitionsRevoked += (s, e) => Console.WriteLine($"Revoked");

        consumer.OnPartitionsAssigned += (s, e) =>
        {
          Console.WriteLine($"Assigned {e.Count} partitions");
          consumer.Assign(e.Select(x => new TopicPartitionOffset(x, Offset.Beginning)));
          consumer.Pause(e);  // !
          consumer.Resume(e); // !
        };

        consumer.Subscribe(topic);

        Console.WriteLine("Beginning consume loop");
        DoConsumeLoop(consumer, TimeSpan.FromSeconds(5));

        Console.WriteLine("Done Consuming");
      }
    }

    static void DoConsumeLoop(Consumer<string, string> consumer, TimeSpan timeout)
    {
      using (var tokenSource = new CancellationTokenSource(timeout))
      {
        while (!tokenSource.IsCancellationRequested)
        {
          var result = consumer.Consume(TimeSpan.FromMilliseconds(100));
          if (result == null)
            continue;

          Console.WriteLine($"Received {result.TopicPartitionOffset}");
        }
      }
    }
}
```

A couple of notes:
* Consumer Group assignment seems to be required to reproduce this issue. If I skip subscribe/OnPartitionsAssigned and manually Assign followed by Pause and Resume, then I cannot reproduce.
* The same problem can be seen when I do the same test using a topic with multiple partitions (I tried 3 and 6). However, in addition to the observations for the 1-partition case, I can also observe that EOF is not raised for all the partitions. For instance, in the error case with 6 partitions, the output might only contain EOF for partition 2 (which had the message) and partition 0 (which was empty), while the success case gave EOF for all partitions (as well as consume the single message).

I also have a final question: The issue mentioned in this report was actually not what we set out to reproduce. What we observed during tests, was that after pausing and resuming, Consumer.Consume suddenly returned messages processed before pausing, as if a Seek had been performed (which it was not). 
For instance, we could see the following sequence of events:
```
Consume Topic1[0]@0
Consume Topic1[0]@1
Consume Topic1[0]@2
Pause
Resume
Consume Topic1[0]@0
```
However we have not been able to reproduce it outside our own product stack. It sounds very much like https://github.com/edenhill/librdkafka/issues/1307, though that has been closed. Any idea what we might be seeing here?

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2
 - [x] Apache Kafka version: cp-kafka 3.3.0
 - [x] Client configuration: See example
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
@HenningRoigaard - i'm away for a bit longer on vacation, so haven't had a chance to look properly at this yet. for now, @edenhill - can you confirm that calling `Pause` and `Resume` before completion of the `OnPartitionsAssigned` callback is complete is allowed? I know librdkafka doesn't completely decouple the consumer group notification with the assignment, but I'm unclear on what's allowed and what isn't without digging deeper.

**Comment by edenhill** [comment]
Pause() will store the offset of the last message Consume()d by the application as the next offset to fetch when Resume() is called.

If Pause() is called prior to any message has been Consume()d then the subsequent Resume() will fall back on `auto.offset.reset`, which is `latest` (default) in your case, despite Assign() having been called with `Beginning`.

This is an issue in librdkafka.

**Comment by edenhill** [comment]
This is fixed in librdkafka and will be available in the next release.
