### ISSUE TITLE
consume result not match Seek() 

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [confluentinc/confluent-kafka-dotnet#675]
When the consumer seek one position, the next consume result do not match what it Seek(). 
It return the result of another partition.

var consumeResult = _consumer.Consume(_pollInterval);

if(consumeResult == null)
{
        _consumer.Seek(consumeResult.TopicPartitionOffset);
        var consumeResult = _consumer.Consume(_pollInterval);
}

 - [x] Confluent.Kafka nuget version: beta2
 - [x] Client configuration: auto.commit = true, auto.offset.store=false

**Comment by mhowlett** [comment]
that is not un-expected - the consume method can return messages from any partition that it is assigned to. the next message to be read from the offset on the partition you seeked to will be at the position you specified.

**Comment by Bo-Yee-Woods** [comment]
If the next message consumed is not guaranteed to what I Seek(), then what is the meaning of Seek() method?
