### ISSUE TITLE
SchemaRegistryBasicAuthCredentialsSource is missing from SchemaRegistryConfig in 1.0.0-beta2

### ISSUE THREAD

**Issue by ghost** [confluentinc/confluent-kafka-dotnet#679]
Description
===========
SchemaRegistryBasicAuthCredentialsSource is missing from SchemaRegistryConfig in 1.0.0-beta2

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks for reporting @prem-aiven-io ! just opened PR #728 to fix this.

**Comment by anchitj** [comment]
Closing as the fix is merged
