### ISSUE TITLE
I used the Kafka version 1.0 in nuget to connect to the Kafka server

### ISSUE THREAD

**Issue by anlem12** [confluentinc/confluent-kafka-dotnet#680]
Description
===========

I used the Kafka version 1.0 in nuget to connect to the Kafka server. At this time, I shut down the Kafka server, but there was no exception in the connection process, and I could not get the status of connecting to the Kafka server. Only when the message was sent out could I catch the exception in the onerror event. Is there any other solution to get to the state of the connection at the time of the connection

How to reproduce
================
`
internal Producer<string, string> GetMessageChannel()
        {
            if (producer == null)
            {
                lock (lockObj)
                {
                    if (producer == null)
                    {
                        var conf = new ProducerConfig
                        {
                            BootstrapServers = $"{_ServerAddr}:{_ServerPort}",
                            EnableGaplessGuarantee = true,
                            EnableIdempotence = true
                        };
                        producer = new Producer<string, string>(conf);
                    }
                }
            }
            producer.OnError += Chanel_OnError;
            producer.OnLog += Producer_OnLog;
            producer.OnStatistics += Producer_OnStatistics;
            return producer;
        }

`

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version:  1.0
 - [x] Apache Kafka version: 1.0
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/wiki#can-i-use-the-net-client-to-check-if-my-kafka-cluster-is-down

**Comment by anchitj** [comment]
Closing as the questions is answered. Feel free to reopen if still an issue.
