### ISSUE TITLE
[Suggestion] Use "static readonly" for const like properties

### ISSUE THREAD

**Issue by AndyPook** [confluentinc/confluent-kafka-dotnet#682]
Description
===========
This is more of a coding pattern / perf suggestion.
In classes like `Offset` there are static properties that create new instances. eg
`public static Offset Beginning { get { return new Offset(RD_KAFKA_OFFSET_BEGINNING); } }`

This pattern means that a new object instance is created everytime the property is used. As `Offset` is a readonly type is would be "better" if the same instance was returned every time. ie

`public static readonly Offset Beginning = new Offset(RD_KAFKA_OFFSET_BEGINNING);`
Or, if you really want it to look like a property (but prefer the above)
`public static Offset Beginning { get; } = new Offset(RD_KAFKA_OFFSET_BEGINNING); `

This makes the property essentially free rather than allocating and GC'ing every time.

How to reproduce
================

`var x = Offset.Beginning`
Creates a new instance of `Offset`

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by AndyPook** [comment]
happy to provide PR if interested

**Comment by mhowlett** [comment]
good point - happy to accept a PR :-)
