### ISSUE TITLE
MacOS Mojave DllNotFound Librdkafka

### ISSUE THREAD

**Issue by no1melman** [confluentinc/confluent-kafka-dotnet#688]
Description
===========

Running simple code using Rider on MacOS Mojave. On run throws DLLNotFound exception for librdkafka

How to reproduce
================

    public class Program
    {
        public static async Task Main(
            string[] args )
        {
            var producerConfig = new ProducerConfig
                                 {
                                     BootstrapServers = "192.168.99.100:9092"                                   
                                 };

            using ( var producer = new Producer<string, string>( producerConfig ) )
            {
                try
                {
                    var dr = await producer.ProduceAsync( "cis-member",
                                                          new Message<string, string>
                                                          {
                                                              Key = Guid.NewGuid().ToString( "N" ),
                                                              Value = "test"
                                                          } );
                    
                    Console.WriteLine($"Delivered {dr.Value} to {dr.TopicPartitionOffset}");
                }
                catch ( Exception e ) when ( e is KafkaException || e is DllNotFoundException )
                {
                    Console.WriteLine( e.StackTrace );
                    throw;
                }
            }
        }
    }

CSProj:

    <Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <OutputType>Exe</OutputType>
        <LangVersion>7.1</LangVersion>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" Version="1.0.0-beta2" />
      <PackageReference Include="librdkafka.redist.osx-x64" Version="0.11.1-TEST4" />
    </ItemGroup>
    
    </Project>

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2
 - [x] Apache Kafka version: N/A
 - [ ] Client configuration:
 - [x] Operating system: MacOS Mojave 10.14.1
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by no1melman** [comment]
Well I tried it without librdkafka and still get the issue

**Comment by mhowlett** [comment]
yeah, I did wonder that ... 

do you have librdkafka installed on your machine via any other means? (eg homebrew?) if so remove those.

if not, I'll need to test on Mojave.

**Comment by no1melman** [comment]
I don't have any of that installed - but let me check

**Comment by mhowlett** [comment]
I can report that it works fine on my other MBP which has mojave on it.
Best guess is a permissions problem.
The next step for me is to install .net core on a new machine and see if I can reproduce.

**Comment by no1melman** [comment]
Okay cool - I'm using SDK 2.1.403

**Comment by no1melman** [comment]
So I clone the repo and started debugging the example application, the actual error thrown is:

```
System.DllNotFoundException: Unable to load shared library 'librdkafka' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibrdkafka, 1): image not found
   at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_err2str(ErrorCode err)
   at Confluent.Kafka.Impl.Librdkafka.SetDelegates(Type nativeMethodsClass) in /code/confluent-kafka-dotnet/src/Confluent.Kafka/Impl/LibRdKafka.cs:line 297
```

**Comment by no1melman** [comment]
It seems like this was pointed out: `dlopen(liblibrdkafka, 1):`

**Comment by mhowlett** [comment]
thanks for your efforts in following up. going to look into this but really need to get -beta3 out the door first (if you're a confluent customer, definitely go via support, that'll be quicker).

**Comment by no1melman** [comment]
So looking at my logs closely this was happening:

```
dyld: loaded: /Users/melman/.nuget/packages/librdkafka.redist/1.0.0-pre1/runtimes/osx-x64/native/librdkafka.dylib
dyld: loaded: /usr/lib/libsasl2.2.dylib
dyld: unloaded: /Users/melman/.nuget/packages/librdkafka.redist/1.0.0-pre1/runtimes/osx-x64/native/librdkafka.dylib
```

I noticed the `libsasl2.2` and googled, someone mentioned running `brew upgrade openssl` I tried that but didn't have brew OR openssl installed. So I installed both (used brew to install openssl) and now it words!!

**Comment by mhowlett** [comment]
ahh yes, i should have thought to say that. it seems a compatible version of openssl is not on mojave by default. i will investigate that. something we're considering doing is including a version of librdkafka with no security dependencies/features enabled in the nuget package that will be loaded as a last resort. we can then add a flag in `Library` that will make this problem easy to debug.
