### ISSUE TITLE
Confluent Kafka Avro Serializer, is it released? or whats the plan?

### ISSUE THREAD

**Issue by vivekk1010** [confluentinc/confluent-kafka-dotnet#691]
Description
===========
we are working to on board entire Confluent package.
when i was working for Schema registry, i found still there is no such thing as io.confluent.kafka.serializers.KafkaAvroSerializer coresponding in dontnet library.
we do not want to look for Microsoft library.
or should we go for customer serializer in this case
it will be helpful if you can give some details soon.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version:
 - [x] Apache Kafka version: 
 - [x] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by mhowlett** [comment]
the `Confluent.Kafka.Avro` nuget package provides avro serdes for .net.
