### ISSUE TITLE
How to create a topic with Replication Factor > 1 and Num of partition > 1 just like what we can do from the CLI

### ISSUE THREAD

**Issue by bthakkar** [confluentinc/confluent-kafka-dotnet#692]
Description
===========
The producer logic does not have an option to specify custom Replication Factor and Num of Partition. 

Can you please guide how to do that?

The Integration TEST logic uses TopicSpecification class but same is not used in the examples. Not sure why it is like that. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
number of partitions and replication factor can't be specified when producing. they are set when the  topic is created (supported via `AdminClient` or use `./bin` utils in kafka dist). they can be modified after as well using tools in `.bin`, but that's something you'd need to do infrequently.

**Comment by mhowlett** [comment]
and yes, we should include some examples of `AdminClient` usage. they're on the priority list ...

**Comment by bthakkar** [comment]
Thank you
