### ISSUE TITLE
What is meaning of -key and -value in Schema Registry

### ISSUE THREAD

**Issue by bthakkar** [confluentinc/confluent-kafka-dotnet#693]
Description
===========
I see the schema subjects are stored as <topic>-key or <topic>-value.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
you will typically want to register schemas associated with both key and value in Schema Registry - the suffic simply differentiates them.
