### ISSUE TITLE
Bug : Code pulls older schema first and then pulls newer schema

### ISSUE THREAD

**Issue by bthakkar** [confluentinc/confluent-kafka-dotnet#694]
Description
===========

Schema mismatch AVRO Error

How to reproduce
================

I have crated schema v1 and then produced a topic XYZ with v1 schema. 
Then I tried to consume the topic. 
It works and I can see data related with topics.

Now I created v2 of the schema and now I am using the same topic name but Now I am producing with v2 Schema. I need to set Compatibility level in the root config as NONE or FULL and then I am able to produce.
But when I try to consume then it pulls older shcemaID first so I get "schema mismatch" exception.
Then after 100ms (in next poll) it is pulling correct schemaID so I can see data based on new schema.

why the consumer is looking at older schema when I specifically supply newly schema with the consumer code?

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
each message in kafka is pre-pended with an id which indicates what schema the message was written in. the deserializer will interpret the message to be in that schema. if the consumer is configured to expect a different schema (i.e. you made a class for v2 using avrogen), it the data will be converted to that type, if it's compatible.

**Comment by bthakkar** [comment]
Thank you so you are saying that if we set newly added fields in v2 schema as default NULL then it will not throw an exception because then it will be compatible. Kindly confirm.
