### ISSUE TITLE
please share some docs to versioning of schema

### ISSUE THREAD

**Issue by vivekk1010** [confluentinc/confluent-kafka-dotnet#695]
Description
===========
its particularly not an issue, but i want to work for the schema versioning int he schema.
i am using 1.0beta version of  dotnet library. most of the doc and examples are not from that. 
doing the POCs for my organization get more challenging.
so cna you please point me to some docs and examples for Schema registry versioning etc.

which will be the latest? AvroSerdeProvider or AvroSerializer<> ??
AvroSerializer is for primitive types?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the API related to this is changing again in -beta3 (or the next release may even be -RC) unfortunately. stay tuned for that. but i hear you, we need better documentation.
