### ISSUE TITLE
Performance Producer with no message duplication and error handling 

### ISSUE THREAD

**Issue by ghetze** [confluentinc/confluent-kafka-dotnet#696]
Description
===========
Hi All ..i am making a dot.net core application which reads data from a database and sends the data to a kafka topic. (the application will be called in parallel multiple times and each app needs to send more than 2 million messages.
I need that:
All messages to me sent with high throughput.
All messages to be sent without duplication.

My questions are:
1.Should I use the internal kafka retry mechanism + a custom retry mechanism + EnableIdemPotence ?

2.What can i teak in my producer configuration to have the best throughput ?

3.In case the internal kafka retry mechanism fails, for what kind of exceptions should the application try to resend the messages so that i do not duplicate any message.

4.I have errors logged on the on producer.OnError event, like :
localhost: 7 request(s) timed out: disconnect (after 129151ms in state UP)
localhost:9092/1: 16 request(s) timed out: disconnect (after 136150ms in state UP)
In this case, or in case i have other errors logged, can i identify the messages for which the errors was triggered ?
Are the errors thrown here only information messages and i should receive for all messages sent a delivery report with the status of the message ?

5.The overall idea is that i want to identify all messages that were not sent with success to kafka so i can resent them, but without duplicating them.
Is this possible?

The kafka producer config is :
 _producerConfig = new ProducerConfig {
                    BootstrapServers = "localhost:9092,localhost:9093,localhost:9094",
                    Acks = -1,
                    MessageSendMaxRetries = 1000,
                    RetryBackoffMs = 1000,
                    LingerMs = 1000,
                    EnableIdempotence = true
                };

The sending logic is as follows :
//Get data from database 
batch.SubscribersList = DataAccess.GetDataForId(id);
foreach (var subscriberInfo in batch.SubscribersList)
                        {
                            string kafkaKey = CreateAvroString(subscriberInfo.Id);
                            string kafkaValue = CreateAvroString(subscriberInfo.Value);
                            try
                            {
                                Retry.Execute(() => _kafka.BeginProduce(kafkaKey,kafkaValue), 
 CustomKafkaSendRetryIntervalMs, CustomKafkaSendMechanismRetryNo, details, _logger);                                
                            }
                            catch (RetryFatalException ex)
                            {
                                 //log errror
                             }

The method used to send messages is as follows :
public void BeginProduce(string key, string value)
{
   Action<DeliveryReportResult<string, string>> handler = (DeliveryReportResult<string, string> r) =>
   {
                if (r.Error.IsError)
                {
                    _loggerInput.Warn($"DeliveryReport with error for {_profileID},Session:{LoadSession},Key:{r.Key},Message:{r.Message}.Error:{r.Error.Reason}.");
                     //add message with delivery reports error to be send again
                    AddMessagesWithErrors(r.Key + "-" + r.Value);
                }
                else
                {
                    _totalReceivedDeliveries++;
                }
    };

    try
    {
    _producerAvro.BeginProduce(_kafkaSettings.Topic, new Message<string, string> { Key = key, Value = value }, handler);
    }
    catch (KafkaException kex)
    {
          throw kex;
    }
}

In case the BeginProduce throws an kafkaexception i have a retry mechanism that sends the messages  again .

Also messages for which there is a delivery report with error (r.Error.IsError)) are sent again using a custom retry mechanism.

I Also log errors that are trigerred by the producer's OnError event.

 private void _producerAvro_OnError(object sender, ErrorEvent e)
        {
            _loggerInput.Error($"Producer Error.Profile:{_profileID},Session:{LoadSession}.Code:{e.Code}.Reason:{e.Reason} ");
        }

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 1.0.0-beta2
 - [ ] Apache Kafka version: 0.11
 - [ ] Client configuration:
 - [ ] Operating system:Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x ] Critical issue

**Comment by edenhill** [comment]
1. Yes, the Producer's builtin retry handling should be sufficient. And enable.idempotence=true will be required to avoid duplicates (in case of retries).
 2. The most important configuration property for performance is to increase `linger.ms`, throughput increases drastically up to around 100ms where it typically flattens out.
 3. librdkafka exposes a message persistance status (rd_kafka_message_status()) that can tell you if manually retrying the message may risk duplication. I'm not sure .NET exposes it yet? (@mhowlett ). Typically you should rely on the idempotent producer to do retries for you though, so I don't think application retry logic is really needed.
 4. The timeouts will trigger retries, so those logs are more an indication that the network or kafka has problems (keeping up). You should rely solely on the delivery report to know if a message was successfully produced or not.
 5. The idempotent producer does this automatically, you don't need any application logic for it.

**Comment by ghetze** [comment]
Thanks for the reply...as far a I know rd_kafka_message_status() is not exposed for .net. Is there any chance to be exposed in the near future for the .net ? @mhowlett .

**Comment by mhowlett** [comment]
i've just implemented this in a local branch. it will be in -beta3, along with correct notification of fatal errors (-beta2 always sets fatal flag to false).

**Comment by mhowlett** [comment]
https://github.com/mhowlett/confluent-kafka-dotnet/pull/9

**Comment by ghetze** [comment]
thank you ...I do appreciate that you've added this to the .net implementation...waiting for the -beta3.
 A final question.
Another thing.
Let's say that i enable idempotent, but i do not set the QueueBufferingMaxMessages ,LingerMs and BatchNumMessages for the producer.
In this case the error Local: Queue full will be generated when calling producerAvro.BeginProduce.
Is it ok to make an retry mechanism to resend the message in this case ?
Are there any other errors for which I should manually retry the producerAvro.BeginProduce without message duplication ?

**Comment by mhowlett** [comment]
yes, if you get a local queue full error, you should retry as the message is yet to get to the point where librdkafka is managing it.

better documentation of error scenarios and providing good examples / guidance on best practice is a high priority and on the roadmap for Q1 next year.

**Comment by ghetze** [comment]
One more thing...about the producer OnError event.
Beacause -beta2 always sets fatal flag to false... is there a list of codes for which the sending mechanism 
should stop .. (because the kafka server is not responding anymore without a manual intervention ) ?

**Comment by mhowlett** [comment]
excerpt from what will be in -beta3 readme should answer your question:

https://github.com/mhowlett/confluent-kafka-dotnet/blob/d97b4c3855c0b5a1feab44a2389a7f74fc009dde/README.md#error-handling

**Comment by ghetze** [comment]
Hi ...any updates for when -beta3 will be released ?
