### ISSUE TITLE
How to limit the number of TCP connections

### ISSUE THREAD

**Issue by lun3322** [confluentinc/confluent-kafka-dotnet#697]
Description
===========
```
            using (var c = new Consumer<Null, string>(conf, null, new StringDeserializer(Encoding.UTF8)))
            {
                c.OnConsumeError += COnOnConsumeError;
                c.OnError += COnOnError;

                c.Subscribe(AppConfig.Topic);
                while (true)
                {
                    if (c.Consume(out Message<Null, string> msg, TimeSpan.FromSeconds(1)))
                    {
                        var lockObj = GetLockObj(msg.Partition);
                        Monitor.Enter(lockObj);
                        ProcessMsg(msg);
                        //_threadPool.QueueUserWorkItem(() =>
                        //{
                        //    ProcessMsg(msg);
                        //});
                    }
                }
            }
```
conf
```
            var conf = new Dictionary<string, object>
            {
                {"group.id", group},
                {"bootstrap.servers", servers},
                {"auto.commit.interval.ms", 5000},
                {"auto.offset.reset", "earliest"},
                {"socket.timeout.ms", 120000}
            };
```
tpc connections
C:\Users\Administrator>netstat -ano | find "52964"
  TCP    127.0.0.1:28132        127.0.0.1:28133        ESTABLISHED     52964
  TCP    127.0.0.1:28133        127.0.0.1:28132        ESTABLISHED     52964
  TCP    127.0.0.1:28134        127.0.0.1:28135        ESTABLISHED     52964
  TCP    127.0.0.1:28135        127.0.0.1:28134        ESTABLISHED     52964
  TCP    192.168.5.170:28136    192.168.5.127:9092     ESTABLISHED     52964

why 127.0.0.1
how to disable it

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:0.11.6
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
Without looking into this, my guess is this is the mechanism @edenhill is using in librdkafka to allow polling on sockets and internal librdkafka queues simultaneously. is that correct @edenhill ? if so, note that this only applies to Windows, and it's to get around a limitation on that OS.

**Comment by mhowlett** [comment]
ok, it looks like that's the case (so you can't disable it).
