### ISSUE TITLE
i am trying to get the offset for the consumer group but everytime it giving me -1001

### ISSUE THREAD

**Issue by vivekk1010** [confluentinc/confluent-kafka-dotnet#699]
Description
===========
i am trying to get the offset for the consumer group but everytime its giving me -1001.
and when I run the consumer continuously without anything. it takes up the messages and shows the 

How to reproduce
================
trying to write a wrapper around this. using 1.0.0beta2
Sample code:

   conf = new ConsumerConfig
            {
                GroupId = ConsumerGroupId,
                BootstrapServers = _bootstrapServers,
                AutoOffsetReset = AutoOffsetResetType.Earliest,
                EnableAutoCommit = false,
                
                    

            };
     public List<TopicPartitionOffset> GetPosition()
        {
         
            using (var consumer = new Consumer<Ignore, string>(conf))
            {
      
TopicPartition tp = new TopicPartition(_topic, 0);
              var offset=  consumer.Position(new List<TopicPartition>() { tp });
                return offset;
            }
        }

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by vivekk1010** [comment]
will be helpful if you can share some code snippet.

**Comment by mhowlett** [comment]
the `Consumer.Position` method tells you the last message consumed by the consumer. if you have not consumed any messages, it will return `Offset.Invalid` (== -1001). you might be looking for the `Consumer.Committed` method, which will give you the last committed offsets (or invalid if none have been committed).
