### ISSUE TITLE
{"Unable to find an entry point named 'rd_kafka_commit_queue' in DLL 'librdkafka'.":""}

### ISSUE THREAD

**Issue by jeffreycruzana** [confluentinc/confluent-kafka-dotnet#70]
I compiled  the Confluent.Kafka and referenced the Confluent.Kafka.dll to a Windows Service application.

Now, I'm getting this message when my code gets to this line.

var committedOffsets = consumer.CommitAsync(msg).Result;

and...

 internal static ErrorCode commit_queue(IntPtr rk, IntPtr offsets, IntPtr rkqu,
            CommitDelegate cb, IntPtr opaque)
            => _commit_queue(rk, offsets, rkqu, cb, opaque);

What could be the issue?

EDIT: My window service target framework is .NET Framework 4.5.2

**Comment by mhowlett** [comment]
yes this is a known issue. it's because we are currently referencing librdkafka v0.9.2 and this functionality requires librdkafka 0.9.4. you can expect a new nuget package within a day (we just verified we have it working, but it's midnight here, so I'll push tomorrow).

**Comment by mhowlett** [comment]
this should be fixed if you reference the latest nuget package (though I haven't explicitly tested it yet) - please let us know if this resolves the issue.

**Comment by mhowlett** [comment]
just a heads up that you're going to run into a new problem (infinite blocking on CommitAsync) which there is an open PR to fix... sorry about that. new nuget package tomorrow most likely to fix that.

**Comment by jeffreycruzana** [comment]
Hi mate. This is still happening. :-(

**Comment by mhowlett** [comment]
g'day - I think we should have a new nuget package for you to try in about an hour or something.

**Comment by mhowlett** [comment]
i was getting ahead of myself (most likely going to take longer than an hour). still, the error you're getting implies to me it's not referencing librdkafka 0.9.4, which it should be. we need to resolve this asap if it's a problem, but I think first step is to see if it's a problem with the new package we're working on now. sorry for the delay ..

**Comment by mhowlett** [comment]
Ok, we've pushed a new nuget package. can you try this and see if it works for you?

https://www.nuget.org/packages/Confluent.Kafka/0.9.4-preview8 

also contains a number of other fixes + API docs.

**Comment by jeffreycruzana** [comment]
Works now mate. Woo! Hoo!

**Comment by mhowlett** [comment]
great - closing. this might have been an interop issue that was present in preview4 as well (which ever way, it's solved now).
