### ISSUE TITLE
{"Unable to load DLL 'librdkafka': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

### ISSUE THREAD

**Issue by jeffreycruzana** [confluentinc/confluent-kafka-dotnet#71]
I compiled the Confluent.Kafka and referenced the Confluent.Kafka.dll to a Windows Service application.

I used the absolute current version of Confluent.Kafka and got this. 

![capture](https://cloud.githubusercontent.com/assets/3271327/23242648/d80e21c0-f9b4-11e6-856c-a5351fbdd92e.PNG)
Maybe I am missing some references after updating with the new version?

**Comment by mhowlett** [comment]
is it possible to reference the nuget package instead of referencing the dll?

if not, try pulling the librdkafka.redist nuget package, take the win7-x64 (or x86 if you're on a 32 bit platform) librdkafka.dll out of that and put it in the same directory as the Confluent.Kafka.dll.

note: nuget packages are .zips - to get inside, just change the extension from .nuget to .zip.

let us know how you go.

**Comment by mhowlett** [comment]
you will need version 0.9.4-RC1-preview4 of the librdkafka.redist nuget package.

**Comment by mhowlett** [comment]
also, this is potentially #72

**Comment by jeffreycruzana** [comment]
Thanks. Downloading the 0.9.4-RC1-preview4 of the librdkafka.redis fixed the issue!

**Comment by bhyatm** [comment]
Having the same problem

64 BIT - NET 4.5.2 - WEBAPI Project

I have put all the 64 bit dll's in the bin directory where confluent.kafka is 

I have the 2013 x86 and x64 visual c++ redistributable installed 

I am running the latest librdkafka.dll - 0.94 

Any ideas ?

**Comment by treziac** [comment]
Your dlls should be in x64 and/or x64 folder in your bin folder (though directly in bin should also works if you target the correct library)

Can you provide more details? (running on IDE or outside from IIS, where the error happen, your OS)
Thanks!

**Comment by abhishekakumar** [comment]
I am still getting this issue.
IDE - Visual Studio 2013
Confluent.Kafka - 0.9.4
librdkafka.redist - 0.9.4

Installing Confluent.Kafka did not generate dll for librdkafka.redist. I was able to resolve that by installing RdKafka.Internal.librdkafka version="0.9.1" but not sure if that's the right way.

@mhowlett - is it possible to reference the nuget package instead of referencing the dll? How can we reference a nuget package instead of the dll?

**Comment by treziac** [comment]
@abhishekakumar you need the package from #133 which has not been uploaded yet (or reference manually the dlls) the current lirdkafka.redist does not work on vs2013

@edenhill @mhowlett  is it possible to upload the nuget for librdkafka.redist (as 0.9.4.1 eg) on #133 (if you had time to test it) to deploy a patch on confluent.kafka?

**Comment by treziac** [comment]
@abhishekakumar 
I uploaded the package on nuget (I will unlist it when confluent upload their pacakge)
You can target it directly :

`Install-Package librdkafka.redist.treziac -Version 0.9.4-patch1 -Pre`

Be advised this package may not be available later, and it's only a temporary workaround

**Comment by gopipofficial** [comment]
im facing the same issue. 

.net framework 4.7.2
visual studio 2017
librdkafka.redist version 1.4.0
my system is 64 bit OS - windows

while creating the object for the producer in im getting "Error while loading librdkafka.dll or its dependencies from <my projects bin location ex: projectname/bin/ >" 

kindly help me to fix this issue.

**Comment by jcasement** [comment]
I'm facing the same issue today:
VS 2017
Framework 4.7.2
Windows 10 64-bit

At the .Build I get the error
Faulted: Error while loading librdkafka.dll or its dependencies from (...)  Check the directory exists

**Comment by jcasement** [comment]
I took my project back from a .NET standard 2.0 to the 4.7.2.
I had tried to move to the .NET 2.0 but that somehow does not produce the librdkafka.dll like the 4.7.2 project does.  Easily done just mod the csproj file to be Targetframework net472 and then reopen project.  It may take a few seconds to resolve dependencies.  Build and it's good to go

**Comment by naggar30** [comment]
@gopipofficial I am facing same issue now 
.net framework 4.7.2
visual studio 2017
librdkafka.redist version 1.4.4
my system is 64 bit OS - windows

Could you pls help me with this

**Comment by gopipofficial** [comment]
yeah I can, may be my answer weired for you. What I did was I used Task in C# which solved my issues. you dont need to manually copy paste or do any build script change to do so. the line which post data in async way you have to use that line with task which takes care of eveything

**Comment by gopipofficial** [comment]
yeah I can, may be my answer weired for you. What I did was I used Task in C# which solved my issues. you dont need to manually copy paste or do any build script change to do so. the line which post data in async way you have to use that line with task which takes care of eveything

**Comment by gopipofficial** [comment]
yeah I can, may be my answer weired for you. What I did was I used Task in C# which solved my issues. you dont need to manually copy paste or do any build script change to do so. the line which post data in async way you have to use that line with task which takes care of eveything

**Comment by gopipofficial** [comment]
yeah I can, may be my answer weired for you. What I did was I used Task in C# which solved my issues. you dont need to manually copy paste or do any build script change to do so. the line which post data in async way you have to use that line with task which takes care of eveything

**Comment by gopipofficial** [comment]
yeah I can, may be my answer weired for you. What I did was I used Task in C# which solved my issues. you dont need to manually copy paste or do any build script change to do so. the line which post data in async way you have to use that line with task which takes care of eveything

**Comment by gopipofficial** [comment]
yeah I can, may be my answer weired for you. What I did was I used Task in C# which solved my issues. you dont need to manually copy paste or do any build script change to do so. the line which post data in async way you have to use that line with task which takes care of eveything

**Comment by gopipofficial** [comment]
yeah I can, may be my answer weired for you. What I did was I used Task in C# which solved my issues. you dont need to manually copy paste or do any build script change to do so. the line which post data in async way you have to use that line with task which takes care of eveything

**Comment by gopipofficial** [comment]
yeah I can, may be my answer weired for you. What I did was I used Task in C# which solved my issues. you dont need to manually copy paste or do any build script change to do so. the line which post data in async way you have to use that line with task which takes care of eveything

**Comment by naggar30** [comment]
@gopipofficial I didn't get that I think I am using task only where we are using aysnc . Actually I am running a .net framework application on IIS and w3p lock the bin/librdkadfka folder and give access denied
