### ISSUE TITLE
Schema Registry URL redundancy does not work as expected

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#711]
There is an issue with referencing two urls in “schema.registry.url”.

Here are the cases we have tested:

- Case 1: {"schema.registry.url", "good_url,good_url"}

o The producer client works correctly and send a message to Kafka

- Case 2: {"schema.registry.url", "good_url,bad_url"}

o The producer client works correctly and send a message to Kafka

- Case 3: {"schema.registry.url", "bad_url,good_url"}

o The producer client crash with the following error

“The request message was already sent. Cannot send the same request message multiple times.”

**Comment by pranavrth** [comment]
Closing this as this has been  fixed.
