### ISSUE TITLE
SSL problem in .NET Core / Linux - "No such configuration property..."

### ISSUE THREAD

**Issue by tvigil** [confluentinc/confluent-kafka-dotnet#714]
Description
===========
When attempting to create a basic .NET Core consumer over SSL, when running in CentOS 7 Linux I'm getting this error in 1.0.0 beta:

>Unhandled Exception: System.InvalidOperationException: No such configuration property: "ssl.ca.location"
   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value) in /app/dotnet/kaf-core/confluent-kafka-dotnet-1.0-beta/src/Confluent.Kafka/Impl/SafeConfigHandle.cs:line 118
   at Confluent.Kafka.Consumer`2.<>c__DisplayClass35_0.<.ctor>b__2(KeyValuePair`2 kvp) in /app/dotnet/kaf-core/confluent-kafka-dotnet-1.0-beta/src/Confluent.Kafka/Consumer.cs:line 342
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.Kafka.Consumer`2..ctor(IEnumerable`1 config, DeserializerGenerator`1 keyDeserializerGenerator, DeserializerGenerator`1 valueDeserializerGenerator) in /app/dotnet/kaf-core/confluent-kafka-dotnet-1.0-beta/src/Confluent.Kafka/Consumer.cs:line 338
   at Confluent.Kafka.Consumer`2..ctor(IEnumerable`1 config, Deserializer`1 keyDeserializer, Deserializer`1 valueDeserializer) in /app/dotnet/kaf-core/confluent-kafka-dotnet-1.0-beta/src/Confluent.Kafka/Consumer.cs:line 214
   at kaf_vac_core.Program.Main(String[] args) in /app/dotnet/kaf-core/kaf-core/Program.cs:line 40

My Code:
            
            var conf = new ConsumerConfig
            {
                GroupId = "kaf_core",
                ClientId = "t1",
                BootstrapServers = "ipaddress:9999",

                AutoOffsetReset = AutoOffsetResetType.Latest,
                SslCaLocation = @".\Cert\ca.pem.txt",
                SslCertificateLocation = @".\Cert\cert.pem.txt",
                SslKeyLocation = @".\Cert\ket.key.txt",
                SecurityProtocol = SecurityProtocolType.Ssl
            };

            using (var c = new Consumer<Ignore, string>(conf))
            {
                c.Subscribe("topic");

                bool consuming = true;
                c.OnError += (_, e) => consuming = !e.IsFatal;

                while (consuming)
                {
                    try
                    {
                        var cr = c.Consume();
                        Console.WriteLine($"Consumed message '{cr.Value}' at: '{cr.TopicPartitionOffset}'.");
                    }
                    catch (ConsumeException e)
                    {
                        Console.WriteLine($"Error occured: {e.Error.Reason}");
                    }
                }

                // Ensure the consumer leaves the group cleanly and final offsets are committed.
                c.Close();
            }

            CreateWebHostBuilder(args).Build().Run();
        }

How to reproduce
================

Included the packages from 1.0.0 beta in my solution.  Seems to compile fine, but upon 'dotnet run' in linux, I get this error that seems to be related to librdkafka.  But I'm simply using the package (redist 0.11.6) that is included in project.  Any ideas?  
Thanks!!

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0 beta
 - [ ] Apache Kafka version: 
 - [x] Client configuration:  - .NET Core 2.1
 - [x] Operating system: Linux CentOS 7
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
you would get that error if you're using a librdkafka binary that has been compiled without support for ssl. I just looked in the librdkafka.redist nuget package (note: 1.0-beta2 uses librdkafka 1.0-pre1 not 0.11.6) and the centos7-librdkafka.so binary is significantly smaller than the other two, indicating this may be the case. I have marked this issue as 'investigate futher' to look into what the status of this is.

as a work around, you could compile a librdkafka binary yourself in your target environment and load it using `Library.Load`.

**Comment by pranavrth** [comment]
No update for a long time. Closing the issue. Please create a new one if required.
