### ISSUE TITLE
How to consume more than one message once?

### ISSUE THREAD

**Issue by starlily** [confluentinc/confluent-kafka-dotnet#717]
Description
===========

ConsumeResult<Ignore, string> messageResult
          = consumer.Consume(TimeSpan.FromMilliseconds(100));

How to consume more than one message? 
Thank you！

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
`Confluent.Kafka` only delivers one message at a time to the application. However, behind the scenes the client is preemptively fetching messages in batches and is highly optimized for throughput. In recent performance testing, I was able to consume more than 1 million messages / second from a broker running on localhost. `Consume` is threadsafe, so you can call it from multiple threads, however generally you should just have one consume loop per consumer. if handling each message is resource intensive, you can push this out to other threads from your consume loop.
