### ISSUE TITLE
There is no ProducerConfig in Confluent.Kafka dll

### ISSUE THREAD

**Issue by karuna7311** [confluentinc/confluent-kafka-dotnet#718]
Description
===========
Hi,

I installed latest Confluent.Kafka via Nuget manager UI. Although I can see ProducerConfig class in source code but when I referred dll directly which is installed via Nuget -  ProducerConfig is not found.

How to reproduce
================
Open VisualStudio 2015 -->Create New project --> INstall Confluent.kafka via Nuget Manger UI.

Tried below code as specified in Producer example.

 var config = new ProducerConfig { BootstrapServers = brokerList };
 using (var producer = new Producer<string, string>(config))
 {

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: Latest
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
are you referencing 0.11.6 or 1.0-beta2? you may need to check the prerelease box in visual studio.

**Comment by karuna7311** [comment]
Hi,

I installed 0.11.6 Stable version. Well, but its there in 1.0 though. But any idea when this will be stabilised?

Thanks,
Karuna

**Comment by mhowlett** [comment]
as soon as possible. the 1.0.x branch together with PRs #716 and #722 is getting close to release candidate quality from my perspective, but there's is some input from others coming.
