### ISSUE TITLE
Producer from nested JSON to AVRO 

### ISSUE THREAD

**Issue by 0xYasser** [confluentinc/confluent-kafka-dotnet#721]
Description
===========
I'm trying to post an Avro message from JSON. (To be posted using a schema to the server as JSON)
I'm not sure if'm doing this right, but I was following the examples to make a producer <string,GenericRecord> but that seems to not post the message as JSON, instead it post it as string

Basically I want to verify the provided JSON if it matches a specific schema, if true then send it as Avro using the producer.  

my json looks like this:
```
{
"firstname" : "person1",
"lastname"  : "person2",
"student":{ "firstname" : "person1","lastname"  : "person2"}
}
```
I want to be able to take the json and post it using a schema.

If anyone can help that would be appreciated. 

How to reproduce
================

This is the code that works for not nested JSON:

```
        var conf = new ProducerConfig {} //filled correctly
        var avroConfig = new AvroSerdeProviderConfig {SchemaRegistryUrl = "usl", // filled with SchemaRegistryUrl };

var schema = (RecordSchema)Schema.Parse(
                @"{	"name":"Person",
		"type": "record",
		"namespace":"com.ippontech.kafka",
		"fields": [
			{"name": "firstname", "type": "string"},
			{"name": "lastname", "type": "string"},
                        {"name": "student",
                        "type": 
			 {"type":"record",
					"name":"student",
					"fields": [
					{"name": "firstname", "type": "string"},{"name": "lastname", "type": "string"}]}}]}"
            );
using (var serdeProvider = new AvroSerdeProvider(avroConfig))
using (var p = new Producer<string, GenericRecord>(conf, serdeProvider.GetSerializerGenerator<string>(), serdeProvider.GetSerializerGenerator<GenericRecord>()))
                {
                    var record = new GenericRecord(schema );
                    string message = "{\"firstname\" : \"person1\",\"lastname\": \"person2\",\"student\":{ \"firstname\" : \"person1\",\"lastname\":\"person2\"}}";  // JSON to be parsed

                    //Create dynamic Json objects on the fly
                    dynamic jsonObject = JObject.Parse(message);

                    foreach (var eachObject in jsonObject)
                    {
                        var fieldName = eachObject.Name;
                        var fieldValue = eachObject.Value.Value;
                        record.Add(fieldName, fieldValue);
                     }                   

                    var task = Task.Run
                    (
                        async delegate
                        {
                            try
                            {
                                var dr = await p.ProduceAsync(topic, new Message<string, GenericRecord> { Key = keyValue, Value = record });

                            }
                            catch (Exception ex){}
                        }
                    );

                    task .Wait(30000);

```

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version: 1.0.0-beta2
 - [X] Apache Kafka version:  1.7.7.5
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
have you considered using `avrogen`? working with strongly typed specific classes is much easier and you generally should do this where possible.

also, what is `keyValue`? if you provide complete working code, it's much easier for us to help out.

**Comment by 0xYasser** [comment]
All I want to do is verify that the JSON message matches the schema before I send it. Avrogen seems to build classes from the schema which I don't need.

**Comment by mhowlett** [comment]
Avro does have a JSON encoding, but the C# client only works with the binary encoding. Any functionality related to working with JSON payloads is outside the scope of the library.
