### ISSUE TITLE
AdminClient throws StackoverflowException when passing in configuration and attaching event handler

### ISSUE THREAD

**Issue by Im5tu** [confluentinc/confluent-kafka-dotnet#724]
Description
===========
A stackoverflow exception is caused on the `AdminClient` when attempting to attach to any of the logging events. This scenario occurs when you pass in the configuration to the client.

How to reproduce
================
1. Create Configuration
2. Pass configuration into AdminClient (eg `new AdminClient(new Dictionary....)`)
3. Attempt to attach to any logging event handler (eg: `OnLog`)
4. Process will crash with a StackoverflowException

Workaround
================

```c#
using (var producer = new Producer<byte[], byte[]>(config))
using (var adminClient = new AdminClient(producer.Handle))
{
    adminClient.OnLog += (sender, message) => {};
}
```

Notes
================
- No log messages seem to be produced either (even with `debug: all`)
- Transport failures occur when trying to get metadata using: `adminClient.GetMetadata(TimeSpan.FromSeconds(5))`

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta2
 - [x] Apache Kafka version: n/a
 - [x] Client configuration:
 - [x] Operating system:
 - [x] Provide logs (with "debug" : "..." as necessary in configuration)
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by mhowlett** [comment]
thanks for the report. In #716, i'm proposing changing how clients are instantiated, which as a side effect resolves this issue. I just added an integration test for this specific case to that PR: https://github.com/confluentinc/confluent-kafka-dotnet/commit/f1812165767dcc3881ac89c9538c648f46e74543

**Comment by mhowlett** [comment]
closing since this has been addressed (though isn't in a release yet).

**Comment by mhowlett** [comment]
see als #670.

**Comment by Im5tu** [comment]
Thanks for the response @mhowlett - any idea of when we can expect the new bits to be available (even as a beta package) so I can carry on? Happy to beta test, since we are doing a lot of testing of new functionality as part of a migration anyway.

**Comment by mhowlett** [comment]
as soon as #716 is finalized.
