### ISSUE TITLE
How do I check if kafka connection or all the brokers are up and running ?

### ISSUE THREAD

**Issue by anujais** [confluentinc/confluent-kafka-dotnet#725]
Description
===========
Before I publish or consume any message, I would like to check if all the brokers (Endpoints) are up and running

**Comment by mhowlett** [comment]
see: https://github.com/confluentinc/confluent-kafka-dotnet/wiki#can-i-use-the-net-client-to-check-if-my-kafka-cluster-is-down

If you have a use-case where you think the above philosophy is not appropriate, i would be interested to read your thoughts on why.

you could possibly use the success/or not of e.g. `AdminClient.GetMetadata` as an indication of whether the cluster is operating.

**Comment by vladkras** [comment]
`telnet kafka-address port`

**Comment by kahara** [comment]
> `telnet kafka-address port`

The TCP port comes up before things are "up and running", so no.
