### ISSUE TITLE
Package does not contain a manifest

### ISSUE THREAD

**Issue by zsebastian** [confluentinc/confluent-kafka-dotnet#73]
When installing the package Confluent.Kafka.0.9.4-preview4, nuget complains that the dependency librdkafka.redist does not contain a manifest. It works fine for preview2 though.

**Comment by mhowlett** [comment]
hi @zsebastian - are you on windows? .net framework? .net core?

**Comment by edenhill** [comment]
Can you paste the exact output?

**Comment by Dexu5** [comment]
@edenhill @mhowlett Facing similar issues. And yes, I'm on windows machine using .NET Framework 4.6.01

**Comment by zsebastian** [comment]
I get the same issue using mono 4.6.2 on CentOS 7.2 and on Visual Studio 2015. 

On Visual Studio when running:

```
Get-Project XXX | Install-Package Confluent.Kafka -Pre -Version 0.9.4-preview4
```

Where preview2 has already been installed, I get the following:

```
Attempting to gather dependency information for package 'Confluent.Kafka.0.9.4-preview4' with respect to project 'XXX', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Confluent.Kafka.0.9.4-preview4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Confluent.Kafka.0.9.4-preview4'
Resolved actions to install package 'Confluent.Kafka.0.9.4-preview4'
Removed package 'Confluent.Kafka.0.9.4-preview2' from 'packages.config'
Successfully uninstalled 'Confluent.Kafka.0.9.4-preview2' from Ruin.Backend.Util
Adding package 'librdkafka.redist.0.9.4-RC1-preview4' to folder 'XXX\packages'
Added package 'librdkafka.redist.0.9.4-RC1-preview4' to folder 'XXX'
Added package 'librdkafka.redist.0.9.4-RC1-preview4' to 'packages.config'
Successfully installed 'librdkafka.redist 0.9.4-RC1-preview4' to XXX package 'Confluent.Kafka.0.9.4-preview4' to folder 'XXX\packages'
Added package 'Confluent.Kafka.0.9.4-preview4' to folder XXX\packages'
Added package 'Confluent.Kafka.0.9.4-preview4' to 'packages.config'
Successfully installed 'Confluent.Kafka 0.9.4-preview4' to XXX
Removing package 'Confluent.Kafka.0.9.4-preview2' from folder 'XXX\packages'
Removed package 'Confluent.Kafka.0.9.4-preview2' from folder 'XXX\packages'
```

As far as I can see there is nothing out of the ordinary. However, when opening "Manage Packages for Solution" and browsing to the Installed tab all I see is a message saying "Error occured". I can click "Show errors in output" and all it says is: 

```
Package does not contain a manifest.
```

Running `nuget restore` on my CentOS machine after installing the package from VS2015 with the above method, I get the following output:

```
WARNING: Package does not contain a manifest.
Installing 'Confluent.Kafka 0.9.4-preview4'.
Added file 'Confluent.Kafka.dll' to folder 'XXXX/packages/Confluent.Kafka.0.9.4-preview4/lib/net451'.
Added file 'Confluent.Kafka.dll' to folder 'XXXX/packages/Confluent.Kafka.0.9.4-preview4/lib/netstandard1.3'.
Added file 'Confluent.Kafka.0.9.4-preview4.nupkg' to folder 'Confluent.Kafka.0.9.4-preview4'.
WARNING: 'Confluent.Kafka.0.9.4-preview4/Confluent.Kafka.0.9.4-preview4.nupkg' already exists. Skipping...
Successfully installed 'Confluent.Kafka 0.9.4-preview4'.
Installing 'librdkafka.redist 0.9.4-RC1-preview4'.
```

**Comment by edenhill** [comment]
> Running nuget restore on my CentOS machine after installing the package from VS2015 with the above method, I get the following output:
@zsebastian I don't really understand this part, VS2015 would be a Windows thing, but you also mention CentOS. Can you clarify?
Thanks

**Comment by edenhill** [comment]
It looks like this is a problem with the old nuget client implementation.
NuGet.Client does not seem affected.
Could perhaps be caused by librdkafka.redist defining an xsd for its .nuspec file.
We'll try to reproduce this to be sure.

**Comment by edenhill** [comment]
What NuGet tool version are you on?

**Comment by mhowlett** [comment]
have verified this happens when using Nuget v2.8.6
by nuget v3.5 there is no problem. 
@ah-'s librdkafka 0.9.2 package is compatible with nuget 2.8.6 
going to try and work out what's causing this and @edenhill can upload a new version compatible with nuget 2.8.6 tomorrow.

**Comment by zsebastian** [comment]
To clarify, I have a project that I build and run on two different platforms: CentOS using mono on the one hand and Windows using VS2015 on the other hand. As to the NuGet tool version I can't check that atm but I can post tomorrow (in 12 ish hours) if it's still relevant. Looks like you have tracked down the problem though.

**Comment by mhowlett** [comment]
we now have a librdkafka.redist package that I was successfully able to install with nuget 2.8.6. This is referenced by Confluent.Kafka 0.9.4-RC-preview8. please try the latest version.

**Comment by jeffreycruzana** [comment]
I had this problem and installing Confluent.Kafka 0.9.4-RC-preview8 fixed the "Package does not contain a manifest" issue.

**Comment by zsebastian** [comment]
That fixes it for me.
