### ISSUE TITLE
Consumer throughput is very low 

### ISSUE THREAD

**Issue by Tenseiga** [confluentinc/confluent-kafka-dotnet#733]
Description
===========
The Consumer throughput is very low.
When I run 3 consumers with in the one consumer group, the throughput of the consumers are good say I am getting about 1000 msgs per sec. Each message is 100 KB (1 million messages in total)
Question:
When I run 3 consumer groups, with 2 consumers in each group, the throughput is severely dropped, around 145 messages per second. 

Note: All the producers are running in separate VM, 
Kafka - 3 brokers (each has 16vCPU, 64 GB RAM, 1Gbps internet).

Consumer properties:
"ReplicaFetchMinBytes": 1,
      "ReplicaFetchWaitMaxMS": 100,
      "AutoOffsetReset": "earliest",
      "EnableAutoOffsetStore": false,
      "EnableAutoCommit": true,
      "SessionTimeoutMS": 10000,
      "PollIntervalMilliseconds": 100,
      "EventProcessingTimeout": 10000000,
      "EventProcessingMaxTasks": 10000000,

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ 1.0 beta2] Confluent.Kafka nuget version:
 - [ 2.0] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
1000 * 100KB -> 100MB/s -> ~800Mbit/s which is close to 1Gbit - i would guess you're hitting a network bottleneck somewhere. suggest collecting kafka broker metrics to investigate further. [Confluent Control Center](https://www.confluent.io/confluent-control-center/) is a commercial offering that can help, or you could use something like: https://github.com/prometheus/jmx_exporter

how many partitions are you consuming from? what is the replication factor (and are you taking the associated required bandwidth into account)?
