### ISSUE TITLE
Please update librdkafka to last RC version in Beta packages

### ISSUE THREAD

**Issue by adcy** [confluentinc/confluent-kafka-dotnet#734]
We would really like to test new beta packages of Confluent.Kafka. But there are some bugs in librdkafka 1.0.0-PRE1 that referenced in last v1.0-beta2 package, which impede testing. It would be very great if your release new beta package with last librdkafka 1.0.0-RC5 with a lot of fixed bugs. I think it will very help community to test and adopt new features.

**Comment by drypa** [comment]
The same request from me!
In latest version I see the same behaviour like in issue https://github.com/edenhill/librdkafka/issues/2040

**Comment by mhowlett** [comment]
you can reference librdkafka 1.0.0-RC5 in your project in addition to Confluent.Kafka, and it should use the later version.

also, we'll be doing an RC of the .net library at the time librdkafka 1.0 is released.

**Comment by milindl** [comment]
Closing this as we're on v2.4.0 now.
