### ISSUE TITLE
Data contract for AVRO serialization/de-serialization

### ISSUE THREAD

**Issue by mrkannan3** [confluentinc/confluent-kafka-dotnet#739]
Description
===========

Is there way to use data contract object as T like
using (var producer = new Producer<string, T>(producerConfig, serdeProvider.GetSerializerGenerator<string>(), serdeProvider.GetSerializerGenerator<T>()))
consumer
using (var consumer = new Consumer<string, T>(consumerConfig, serdeProvider.GetDeserializerGenerator<string>(), serdeProvider.GetDeserializerGenerator<T>()))
then solve it using IOC container? 
the idea is to use something like below
Producer
--------------
using (var producer = new Producer<string KafkaMessage>()
Consumer
using (var producer = new Consumer<string KafkaMessage>()
Based on the topic, the actual entity will vary. for example, if its employee, then the employee class is written like this,
class Order : KafkaMessage, ISpecificRecord
{
}
if its Invoice then
class Invoice : KafkaMessage, ISpecificRecord
{
}
Could you pleas help?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ 5.1.0] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Closing this as #740 is pretty much the same thing, keeping that open to track the addition of an example.
