### ISSUE TITLE
Produce Batch of messages from Rabbit to Kafka

### ISSUE THREAD

**Issue by ASalihov** [confluentinc/confluent-kafka-dotnet#744]
I have a RabbiMQ consumer that consumes messages by one at a time. And I need to send that messages to Kafka topic. How can I do it in reliable and not too slow manner? Note that I need to return acknoledge to Rabbit produser.
If I send messages using Flush on each of them it will be very slow. But if I produce a bunch of messages and use Flush at that bunch I'll risk to miss messages in case of failure. So what strategy is the best in this case. 
p.s. We decided to gradually move from rabbit to kafka...

**Comment by mhowlett** [comment]
if you consume N messages from RabbitMQ, produce all of them to Kafka, then ack all the messages back to RabbitMQ you'll get at least once semantics. I'm not familiar with the RabbitMQ API, but you should be able to do that. If ordering is important, you'll need to set `max.in.flight` to 1, set `linger.ms` high enough to make sure you get good batching of messages in each broker produce request (depends on speed of getting your N messages from rabbit mq), and `message.send.max.retries` to 0. Alternatively, wait for idempotent producer to be ready (next release, coming soon).

**Comment by milindl** [comment]
Closing this as Matt answered the question (and idempotent producers are now available)
