### ISSUE TITLE
kafka-consumer-groups

### ISSUE THREAD

**Issue by emadghav** [confluentinc/confluent-kafka-dotnet#749]
hi
i have a topic with 4 partition and my consumer assigned 2 partition but when i use command "kafka-consumer-groups --bootstrap-server localhost:9094 --describe --group conumername --members --verbose" result of this command shows that my consumer assigned 4 partition !!!!
but i get data from 2 partition.
i think this command have a bug
and i use kafka on windows

**Comment by mhowlett** [comment]
how are you determining that your consumer is assigned to 2 partitions?

**Comment by emadghav** [comment]
i use confluent.kafka.dll and i use method consumer.Assign(partitions)
and partitions contain 2 partition info

**Comment by mhowlett** [comment]
Are you calling subscribe (this is how you join a consumer group, if you don't call this, you're not joining a consumer group), and are you calling Assign in a handler added to `OnPartitionsAssigned`? And is the set of partitions your assigning to the same as the set provided by the `OnPartitionAssigned` event? Note that it's possible to 'Assign' to (read from) a different (modified) set of partitions than the ones you're assigned to by the consumer group. 

Note: the naming is very confusing here - receiving a partition assignment, and assigning to a set of partitions to read from are two different things. I'm hoping to fix this in the upcoming 1.0 API.

**Comment by emadghav** [comment]
in event OnPartitionsAssigned i assigned a set of partitions
tnx

**Comment by michael-elly** [comment]
I'm having trouble listing the consumer groups. Getting error:
System.ArgumentNullException: 'Argument 'group' must not be null. Parameter name: group'
when calling: 
using (var adminClient = new AdminClientBuilder(new AdminClientConfig { BootstrapServers = bootstrapServers }).Build()) {
        var groups = adminClient.ListGroups(TimeSpan.FromSeconds(10));
my code is based on the adminClient sample, and making the same call using the batch file scripts works just fine. I posted a question in 
https://stackoverflow.com/questions/60301041/how-can-i-list-kafka-consumer-groups-using-confluents-net-client

**Comment by mhowlett** [comment]
this is resolved in 1.4.0-RC1, which is now on nuget.

**Comment by michael-elly** [comment]
Hi, Is there a way to identify lagging topics with this client DLL? i.e. topics/partitions which their commited offset was done a while ago and many new messages added to the partitions since... Also I'm looking for ways to get additional information on both publishers an subscribers (source host and name). Thanks.

**Comment by michael-elly** [comment]
As part of my Kafka learning process I'd like to use this DLL to write a little monitoring GUI application. Any source code in C# doing similar would be great. Also is there a .NET Core version DLL for this?
