### ISSUE TITLE
LibRdKafka static constructor throwing

### ISSUE THREAD

**Issue by namroot** [confluentinc/confluent-kafka-dotnet#76]
I have the same message of error. A same problem with LibRdKafka "The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception".
In my local machine, the application works correctly. But when i try to deploy it in the server, i have this error.
I am in dot.net environment (c#) and i am using Confluent.Kafka.0.9.4-preview2 library.
Local machine: Windows 7 Entreprise Service pack 1.
Server: Windows Server 2008 R2 Entreprise Service Pack 1.
I tried to install OpenSSL but without result.
Any suggestions please?

**Comment by mhowlett** [comment]
please try Confluent.Kafka.0.9.4-preview8

**Comment by namroot** [comment]
I tried it, same behavior.

**Comment by mhowlett** [comment]
did you use nuget to reference the package, or are you referencing the Confluent.Kafka.dll directly?

**Comment by mhowlett** [comment]
also is this a 32bit or 64bit OS.

**Comment by mhowlett** [comment]
also try installing the Visual C++ Redistributable Packages for Visual Studio 2013.

**Comment by namroot** [comment]
i am workin with 64nit and i used nuget to reference my package.
the same thing for C++ Redistributable , i have it in my server.

**Comment by mhowlett** [comment]
The problem is (almost certainly) that it can't find the librdkafka.dll library. can you copy the librdkafka.dll library and it's dependencies (for me, everything in the below folder) and put them in the same directory as the Confluent.Kafka.dll. Let me know if that works. 

C:\Users\<user>\.nuget\packages\librdkafka.redist\0.9.4-RC1-preview8\runtimes\win7-x64\native

**Comment by namroot** [comment]
Now we don't have the error but Kafka don't return the  Result object  when it publish the message.
then we can't see if it s ok or not

**Comment by mhowlett** [comment]
that sounds like an operational problem to me.

is the bootstrap server contactable? 

you could turn the log level right up and see if you can make sense of the messages. See:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Producer.cs#L402

or try playing with configuration parameters: 
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by mhowlett** [comment]
oh, and the behavior you're seeing is not ideal - thanks heaps for the feedback. In #77, we see this occurs when installing a service via InstallUtil.exe -i myService.exe. we will try to replicate and then make sure this all works out of the box.

**Comment by namroot** [comment]
Hi,
We solved our problem.
We must also install Visual C ++ Redistributable 32 bit even in a 64 bit server and even though we have Visual C ++ Redistributable 64 bit installed
Thank you for your help
