### ISSUE TITLE
SchemaRegistryClient in .Net Core GET subject's versions

### ISSUE THREAD

**Issue by mibrl12** [confluentinc/confluent-kafka-dotnet#761]
Description
===========

`Confluent.SchemaRegistry, Version=0.11.6.0`

There is no way to get all available versions of the schemas registered under the subject.

[GET /subjects/(string: subject)/versions](https://docs.confluent.io/current/schema-registry/docs/api.html#get--subjects-(string-%20subject)-versions)

It would really help a lot! I could volunteer for implementing this tiny feature. 

Checklist
=========
Please provide the following information:

 - [x] Client configuration: version 0.11.6.0

**Comment by mhowlett** [comment]
sounds good! thanks!

if it requires very little review time (seems likely), i should be able to slip it into the 1.0 release, else be warned that i won't get to it until 1.0 is out.

1.0.x is the best branch to open a PR on.
