### ISSUE TITLE
Suggested pattern for a Consume,Transform,Produce use case

### ISSUE THREAD

**Issue by jacksed** [confluentinc/confluent-kafka-dotnet#762]
Description
===========
Question:  Is there a suggested pattern or ideal way to consume, transform then republish the transformed objects to a new topic?  I don't want to drop a message either.

Would something like this be recommended?

    // Configuration
    _consumerConfig = new ConsumerConfig()
    {
        BootstrapServers = "localhost:9092",
        GroupId = "mygroup-id,
        EnableAutoCommit = false,
        StatisticsIntervalMs = 10000,
        SessionTimeoutMs = 6000,
        AutoOffsetReset = AutoOffsetResetType.Latest,
        ClientId = "clientid",
    };

    // Create Producer
    _producerConfig = new ProducerConfig
    {
        BootstrapServers = "localhost:9092",
        Acks = -1,
    };
    _producer = new Producer<Null, string>(_producerConfig);
    _consumer = new Consumer<Ignore, string>(_consumerConfig);

    // Main Loop 
    void ConsumeTransformProduce()
    {
        _consumer.Subscribe(new[]{"topic_A", "topic_B", "topic_C"});

        while(!_cancellationToken.IsCancellationRequested)
        {
            var msg = _consumer.Consume(_cancellationToken.Token);
            var topic = msg.Topic;
            var payload = msg.Value;

            if (topic == "topic_A")
            {
                var A1 = Transform_To_A1(payload);
                var A2 = Transform_To_A2(payload);
                _producer.BeginProduce("topic_xformed_A1", ToJson(A1));
                _producer.BeginProduce("topic_xformed_A2", ToJson(A2));
            } else if (topic == "topic_B")
            {
                var B1 = Transform_To_B1(payload);
                _producer.BeginProduce("topic_xformed_B1", ToJson(B1));
            }
            // else if (topic == "topic_C") ... etc

            _consumer.Commit(msg);

            // do we need to flush every time?
            _producer.Flush(TimeSpan.FromSeconds(10));
        }
        _consumer.Close();
    }

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0.0-beta2
 - [x] Apache Kafka version: kafka_2.11-2.1.0 
 - [x] Client configuration: 
 - [x] Operating system: Win10 Pro
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue: no

**Comment by mhowlett** [comment]
we plan to add an example + discussion of this. you can't get exactly once semantics yet because transactions are not implemented, but you can get at least once semantics by committing after you produce the new message.

**Comment by jacksed** [comment]
Great! Looking forward to learning from the example and discussion.

**Comment by anchitj** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/ExactlyOnce
