### ISSUE TITLE
Producer not pushing the messages while can push from CLI

### ISSUE THREAD

**Issue by vivekk1010** [confluentinc/confluent-kafka-dotnet#765]
Description
===========

Not able to publish message from Producer API, but when i use Kafka CLI to push the message, it works fine on my Azure cluster

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts : 
 - [ ] Critical issue : yes

**Comment by mhowlett** [comment]
that's not a lot to go on - can you provide more information?
