### ISSUE TITLE
Kafka Connector API and Unity3d support implementation

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [confluentinc/confluent-kafka-dotnet#766]
Description
===========
I found the implementation of producer and Consumer Api but the there is no example i found in the repo (except the fact that [stream API is not implemented yet and there is no future consideration about it](https://github.com/confluentinc/confluent-kafka-dotnet/issues/344)) about the reaming two Kafa Core Api namely the streams API and Connector API. Do i missed in the project or it is not implemented yet? If not, then what is future plan? Do i need to learn java for this?

Additionally How can i **use** confluent kafka in **unity3d** game engine? Do any support available?

How to reproduce
================

Its a required feature in confluent kafka. (if possible)

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
I don't know of any plans to implement the connect api in additional languages. The need is not as compelling as for streams (which is also currently java only), since most of the time people will be using off-the-shelf connectors.

For unity3d, #689 seems like it might be the only blocker. Unfortunately I missed this in -beta3. It's a  simple change though, so I'll do it now.

**Comment by MuhammadFaizanKhan** [comment]
> The need is not as compelling as for streams (which is also currently java only), since most of the time people will be using off-the-shelf connectors.

So there is no connect api in .net C#? and what to do you mean by off-the-shelf connectors? Any example available?

**Comment by mhowlett** [comment]
correct, there is no Connect API for C# (only Java).

Some existing connectors for common systems:
https://docs.confluent.io/current/connect/managing/connectors.html
https://www.confluent.io/hub/

**Comment by MuhammadFaizanKhan** [comment]
> https://docs.confluent.io/current/connect/managing/connectors.html
> https://www.confluent.io/hub/

Well thanks for answer and sharing valuable resources. **I don't know why there is no implementation of Connector and Streams API in .net yet**. At least streams API should be in implemented anyway thanks you have saved my time otherwise , i will be searching it again and again. 
Do there any other implementation availabe in .net other than confluent?

**Comment by mhowlett** [comment]
It's just a matter of the amount of work involved - there are currently about 10 people working full time on just the Java streams API I think (and about that again on KSQL), and that number is growing.
