### ISSUE TITLE
Keep same Producer instance throughout api requests

### ISSUE THREAD

**Issue by kaiohenrique** [confluentinc/confluent-kafka-dotnet#770]
Description
===========

Hello, everyone.
I am currently working on an API that sends messages to a Kafka Broker on some situations. I am wondering if a could keep a Producer instance always instantiated in order to make use of same message queue. I am afraid if a instantiate a Producer to each message I will not make use of the same queue. Am I right? Is it a good practice?

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
yes, creating a producer instance is expensive! you should generally keep a single instance alive for the lifetime of your application, even in low throughput scenarios.
