### ISSUE TITLE
1.0 API Feedback 

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#777]
If you have any feedback on the 1.0-beta3 API, please provide it here - we're keen to catch things we might not have thought of yet before the 1.0 release. I'm also happy to defend any design choice we've made here - some of them have been tough!

**Comment by Fresa** [comment]
In Confluent.Kafka.Config there is a property called CancellationDelayMaxMs that is used as "default" timeout value when consuming messages if no explicit timeout value has been given to the consumers Consume method. Would it not be better if the validation of this property occurs when setting the value? Now you can set the value to what ever and get no feedback until you start consuming messages. It would also be nice to have a getter for this property since you already can fetch it implicitly by calling Config.Get(ConfigPropertyNames.CancellationDelayMaxMs).

**Comment by mhowlett** [comment]
yep, agree. with that said, this property was built to match the behavior of the librdkafka properties which are checked on consumer construction (this property is too). It would be better to check for validity of all config parameters the point of setting them, however that would either require making the .net client aware of the allowable values (duplicating functionality in librdkafka, and requiring the two versions be maintained), or having the config object manage a native resource (i.e. requiring it to be `IDisposable`). i guess we could make this change for just this property, and that would be better, but priority isn't high enough at this point. thanks for the feedback!

**Comment by Trojaan** [comment]
Hello. I'm not completetly sure where to ask this question. But is there a roadmap for the 1.0 release and when do you expect to release it? Thanks.

**Comment by mhowlett** [comment]
End of March is the plan, along with v1.0 of the other clients.

**Comment by AndreSteenbergen** [comment]
What's the reason for removing the events OnError etc. In the past it was possible to reuse an existing producer and when you needed error handling in some of the modules you could add a delegate using OnError +=  ...... this seems impossible now. Is there any way to regain that functionality?

**Comment by mhowlett** [comment]
in the old design, errors can potentially occur before the handlers were added - moving them to the builder class means that can never occur. also, we felt the use-case you're suggesting was more open to misuse/misunderstanding than providing genuine value. what's your specific use-case? Note that error events are only informational in nature, except for the new idempotent producer functionality which can return a fatal error indicating the entire producer is in a failed state.

**Comment by AndreSteenbergen** [comment]
I am trying to keep Akka.Streams.Kafka up to date with Kafka latest versions. I am trying to do as little code change as possible, so this setting eventhandlers instead of adding delegates is quite some work at the moment.

**Comment by AndreSteenbergen** [comment]
But as I am reading through the code at the moment OnError isn't doing a lot. So I removing that code altogether ...

**Comment by mhowlett** [comment]
cool! apologies the extent of the changes. it is a bit of work to move over, but the improvement is substantial an we thought we might as fix all the things that were not great in one go.

yes, there probably isn't much to be gained by doing anything with the 'error' events. the name is a bit misleading (but we still arrived at this as the best choice).

**Comment by Rymix** [comment]
Have no problem with this V1.0 that's a great job. Looking forward the transactions ! 💯

**Comment by rohitshrivastava04** [comment]
the latest version doesn't have any event on consumer. OnPartitionsAssigned & OnPartitionsRevoked were quite useful to know partition assignment has changed. What is the new way for this?

**Comment by mhowlett** [comment]
@rohitshrivastava04 - this has moved to the ConsumerBuilder class - `SetRebalanceHandler`. Note that the exact rebalance API is still being tweaked. This is the last thing to finalize before doing an RC.

**Comment by avibe948** [comment]
My feedback - RC4 -  Trying to PublishAsync via the producer never returns a Broker not available when the broker is down. To work around it I need to define a policy (using Polly) for task timeout which also allows me to do retries ... Not sure whether this intended by design (exceptions are expensive and slow )

**Comment by mhowlett** [comment]
thanks @avibe948 - error handling logic is very difficult here in the general case. you are only connecting to one broker, but what about if you're connected to a cluster (which is how kafka is typically run)? there are many scenarios of up-ness to consider. librdkafka implements good logic for handling many scenarios and gives you tweakable configuration for this (number of retires etc). 

something related that we haven't implemented but want to is the special case of all brokers down on startup. this can often be due to a mis-configuration, and the user may want to handle this scenario differently. Currently there is only one all-brokers-down event type sent to the error handler (set with `SetErrorHandler`) - we'll probably ultimately have two types here.
