### ISSUE TITLE
EntryPointNotFound exception with 1.0.0-beta3 and CentOS calling a producer

### ISSUE THREAD

**Issue by TheFireCookie** [confluentinc/confluent-kafka-dotnet#783]
Description
===========
I'm having a .NET Core 2.2 app with the latest version of Confluent.Kafka (1.0.0-beta3).
It's a test solution. When running on Windows, everything is fine and my tests are running well.

When I'm trying to start the test project on CentOS 7.6.1810, I get the following error:
`[09:00:46]	[Step 8/8] The active test run was aborted. Reason: Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'rd_kafka_message_status' in shared library 'librdkafka'.
[09:00:46]	[Step 8/8] at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_message_status(IntPtr rkmessage)
[09:00:46]	[Step 8/8] at Confluent.Kafka.Producer`2.DeliveryReportCallbackImpl(IntPtr rk, IntPtr rkmessage, IntPtr opaque)
[09:00:46]	[Step 8/8] at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_poll(IntPtr rk, IntPtr timeout_ms)
[09:00:46]	[Step 8/8] at Confluent.Kafka.Producer`2.<>c__DisplayClass22_0.<StartPollTask>b__0()
[09:00:46]	[Step 8/8] at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)`

How to reproduce
================
Creating a producer in a class/test class/something and running it on CentOS.
Run it,
Bam error 😭 

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta3
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [x] Operating system: CentOS 7.6.1810
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the error indicates it's managing to find an older version of librdkafka and load that (message status is 
a new feature). i'm not sure why without further investigation. do you have librdkafka installed on your system? - it might be loading that for some reason, for example if the centos librdkafka binary included in the librdkafka.redist nuget package is not compatible with centos 7.6. another explanation is if an old version of librdkafka has been accidentally included in librdkafka.redist for the centos case.

we are not currently running automated testing on centos systems for the .net client yet (but plan to). thanks for the error report!

**Comment by mhowlett** [comment]
another explanation would be if you're explicitly referencing an older librdkafka.redist nuget package, or perhaps a project that is using an older version of `Confluent.Kafka`.

**Comment by TheFireCookie** [comment]
Hello,

Thanks for the fast answer.
A version of the librdkafka was installed on the machine. 0.11.something but I don't remember the exact version.

I uninstalled it and it seems to work. So my question is why it was using this one over the one that comes with your package?

**Comment by mhowlett** [comment]
It shouldn't be, that's a bug.

**Comment by MortalFlesh** [comment]
Hello,
I have same problem (_probably_) with

```
macOS Mojave: 10.14.3
librdkafka: stable 0.11.6 (installed by brew on my machine)
Confluent.Kafka: 1.0-beta3
dotnetcore: 2.2.102
```

It appeared when I've upgraded `Confluent.Kafka` to `1.0-beta3` (from `1.0-beta2`).

I tried to upgrade `librdkafka` on my machine, but it didn't help. (_consuming and producing still works, it just crashes afterwards_)

When I downgrade back to `1.0-beta2`, it works fine.

**Comment by bittercoder** [comment]
Having the same issue

MacOS Mojave: 10.14.3 

I appear to have multiple versions of Librdkafka.dylib in the ~/.nuget/packages/ folder (0.11.0, 0.11.6, 1.0.0-rc7) and 0.11.6 installed via homebrew. Confluent.Kafka: 1.0-beta3
dotnetcore: 2.2.102

**Comment by bittercoder** [comment]
I did a bit more digging this evening utilising `Library.Load(path)`

If I invoke:

    Library.Load("/Users/alexhenderson/.nuget/packages/librdkafka.redist/0.11.6/runtimes/osx-x64/native/librdkafka.dylib");

Than the call succeeds, but I get the error when invoking ProduceAsync

But if I switch it for a call to load the 1.0.0-rc7 librdkafka:

    Library.Load("/Users/alexhenderson/.nuget/packages/librdkafka.redist/1.0.0-rc7/runtimes/osx-x64/native/librdkafka.dylib");

Then it fails to load the native library at all - the error is just:

    System.InvalidOperationException: Failed to load librdkafka at location '/Users/alexhenderson/.nuget/packages/librdkafka.redist/1.0.0-rc7/runtimes/osx-x64/native/librdkafka.dylib'. dlerror: ''.

This led me to try adding an explicit dependency to `librdkafka.redist` with version `1.0.0-RC8-test-deps13` and removing the call to `Library.Load(...)` and that fixed the issue.  So I think 1.0.0-rc7 has some issues with it, which are preventing it from loading correctly on OSX (and probably Linux as per the issue) as well.

**Comment by mhowlett** [comment]
yep, that's right. 1.0.0-beta3-ci-880 of `Confluent.Kafka` which references librdkafka.redist 1.0-RC8 should also fix this issue.
