### ISSUE TITLE
Consumer Timeout does not work

### ISSUE THREAD

**Issue by 4JasonChou** [confluentinc/confluent-kafka-dotnet#797]
Description
===========
In a C# Windows ConsoleApp , try to consume the not exist kafka's ip and port.
But wait for long time, didn't receive exeception.

How to reproduce
================

KafkaConsumer mkafkaConsumer = new KafkaConsumer(new ConsumerConfig
{
     BootstrapServers = "10.9.176.190:9092",
     GroupId = "4j",
     AutoOffsetReset = AutoOffsetReset.Earliest,
     EnableAutoCommit = true,
     AutoCommitIntervalMs = 10
}, "4jtest");

var mConsumer = new ConsumerBuilder<Ignore, string>(mKafkaConfig).Build();
mConsumer.Subscribe(topic);

var cts = new CancellationTokenSource();
Console.CancelKeyPress += (_, e) => {
     e.Cancel = true; // prevent the process from terminating.
     cts.Cancel();
};

try
{
     var msg = mConsumer.Consume(cts.Token);
     Console.WriteLine(msg.Value);
 }
catch (Exception e)
{
    Console.WriteLine( e.Message );
}

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta3
 - [x] Apache Kafka version:  1.0.0
 - [x] Client configuration:  .NET Framework 4.6.2
 - [x] Operating system: Windows10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mrkannan3** [comment]
> var msg = mConsumer.Consume(cts.Token);

You are not using timeout option. You are passing the cancellation token instead of timespan object.

**Comment by mhowlett** [comment]
As @mrkannan3 says, you're using the variant of `Consume` which will block indefinitely or until the cancellation token is cancelled. The client is designed to work with a distributed system in which brokers are expected to go down periodically - it will not fail if you specify the wrong broker address. You'll get notification on vie the error callback that 'all brokers are down' (but generally such events should be considered informational).

**Comment by 4JasonChou** [comment]
It's work, thanks.
