### ISSUE TITLE
performance testing for Avro Serialization/Deserialization ?

### ISSUE THREAD

**Issue by vivekk1010** [confluentinc/confluent-kafka-dotnet#798]
Description
===========

i am doing one Performance Testing comparing serialization and deserialization of   Avro record using Confluent Avro serializer, vs our in house manual serializer.
i found that with large size objects avro serializer takes more time.
but i have a doubt about how i am using it.

what i am using is:
 **var  _avroserde = new AvroSerializer<DummyMsgAvro>(schemaRegistry);** 

and then benchmarking the method:

   **public byte[] SerializeDummy(string Topic,DummyMsgAvro record)
        {
          
            return _avroserde.Serialize(Topic, record);
        }**

while we produce the message,it is supposed to cache the schema and so serialization should be faster. But here with large object its slower so i have two questions:
1. am i serializing it right for the purpose of performance benchmark? should we only test it with producer producing to the topic?
2. in that(producer) case serialization happens on client using cached schema or how that happens? will that be actual test for the comparison? because ultimate goal is to compare that more number of messages are pushed/second ? 

it will be helpful if you could respond quickly.

Confluent Kafka version 1.0.0 beta
How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
what you're doing looks correct.

in my own testing, I've found the .net avro serializers to be relatively slow. the primary argument for using avro is it's a good match for the requirements of a streaming platform (and Confluent supports it throughout all components, e.g. Schema Registry, KSQL, Connect). Note: in the future, Confluent may support additional formats, even though they are not the best match for the streaming use-case. There are pros/cons for all of them.

**Comment by smeana** [comment]
> what you're doing looks correct.
> 
> in my own testing, I've found the .net avro serializers to be relatively slow. the primary argument for using avro is it's a good match for the requirements of a streaming platform (and Confluent supports it throughout all components, e.g. Schema Registry, KSQL, Connect). Note: in the future, Confluent may support additional formats, even though they are not the best match for the streaming use-case. There are pros/cons for all of them.

Hello,

Your testing has been done on large size records/objects ?
I haven't found big difference in terms of timing/performance. Using an AVRO with Registry against a custom serialized on small records like : (Datetime,int,string,int,float,float,int,float,int,int). What on my test makes the difference, is moving across the messages as strings, which is faster and keep less storage size but you will need to add the consumer parsing time.

**Comment by mhowlett** [comment]
thanks for the input @smeana

i've only tested relatively small message sizes (100 bytes or so). I was comparing performance specifically against protobuf (and newtonsoft json)

if you're passing data as a string, of course you need to include the time to deserialize the string in the cost of deserialization :-)

**Comment by smeana** [comment]
Many thanks @mhowlett 
Do you have any kafka example using protobuf? :)

**Comment by mhowlett** [comment]
the repo has a protobuf example:
https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/Protobuf
