### ISSUE TITLE
Out of memory after sending a large amount of data

### ISSUE THREAD

**Issue by SIDVEGE** [confluentinc/confluent-kafka-dotnet#808]
Description
===========
I'm trying to send all sensor data to a Kafka topic with multiple partitions.
I'm using multiple producers (1 per schema = 1 Partition key), all producers inherited from the main producer-handle.

In Beta3, I get out of memory after sending a large amount of data.
This sample shows how we set up the connection with the library, Schema registry and Kafka.
Once connected, we send a large amount of small (simple) messages to Kafka.
When watching the garbage collector (heap generation 0,1 & 2) you see that the memory in generation 2 is continuously growing and never get released, until the computer gets out of memory.

The memory problem doesn’t exist when not calling the lines:

// send the data to Kafka Connect
Task<DeliveryResult<Null, GenericRecord>> deliveryReport = producer.ProduceAsync(KafkaTopic, message, cancellationtokenSource.Token);
deliveryReports.Add(deliveryReport);

How to reproduce
================

In the sample code: change the:
•	uri2ConfluentSchemaRegistry
•	BootStrapSevers
•	KafkaTopic
Run the program, bet by using a memory profiler (I’ve used JetBrains dotMemory)
After a while you get a memory evolution as you find in the attached figure (see green area)

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
This is an excerpt of the packages.config file
  <package id="Confluent.Apache.Avro" version="1.7.7.5" targetFramework="net461" />
  <package id="Confluent.Kafka" version="1.0.0-beta3" targetFramework="net461" />
  <package id="Confluent.SchemaRegistry" version="1.0.0-beta3" targetFramework="net461" />
  <package id="Confluent.SchemaRegistry.Serdes" version="1.0.0-beta3" targetFramework="net461" />
  <package id="librdkafka.redist" version="1.0.0-RC7" targetFramework="net461" />

 - [ ] Apache Kafka version: 

2.0.1-cp1

 - [ ] Client configuration:

See attached sample code

 - [ ] Operating system:

.Net application runs on Windows 10 or Windows Server 2016
Kafka is running on red hat 7.5

 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)

See attached files

 - [ ] Provide broker log excerpts

See attached files

 - [ ] Critical issue

Out of memory (after long running)

[ConfluentKafkaBeta3Hangs.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/2931791/ConfluentKafkaBeta3Hangs.zip)
[grep OUTOMEMORY server.log.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2931792/grep.OUTOMEMORY.server.log.txt)
[grep OUTOMEMORY state-change.log.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2931793/grep.OUTOMEMORY.state-change.log.txt)
[Logging.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/2931794/Logging.zip)
![memory usage evolution](https://user-images.githubusercontent.com/47518431/53820079-69c3c900-3f6b-11e9-88df-f02af18e4d80.jpg)

**Comment by mhowlett** [comment]
@SIDVEGE - try using a different compression codec - I believe problem is likely related to the lz4 library. We have another report of this, we'll be looking into it soon after the 1.0 release.

**Comment by SIDVEGE** [comment]
I do see the same memory usage evolution with all compression codecs, even with 'none'.

**Comment by mhowlett** [comment]
@SIDVEGE - thanks for the update, I'll try to find time to look a bit closer later today.

**Comment by mhowlett** [comment]
@SIDVEGE - I tracked down the problem - it's because you're passing a `CancellationToken` to the `ProduceAsync` method. This was never implemented correctly and has been removed from the scope of 1.0 as too hard (we do plan to implement it later). If you just don't pass this parameter it should work. Also, I've just uploaded 1.0-beta3-ci-880 to nuget, which is the current state of the 1.0.x branch in which this feature has been removed.

**Comment by SIDVEGE** [comment]
YES! This is the solution! (well for now anyway :-) )
I'm affraid I've been looking to deep into the code to see and understand how to work with the library...
The cancellationToken looks very handy in long running services, but I do understand that 'get it working' is much more important than canceling.
Thanks for the update, it works fine now!
