### ISSUE TITLE
Getting Kafka handle is closed ObjectDisposedException

### ISSUE THREAD

**Issue by JohnKo009** [confluentinc/confluent-kafka-dotnet#811]
Description
=========
I am running multiple tasks and creating multiple Consumer instances for each task which will process the messages in a Windows Service. After every 10 mins whenever any of the partition is getting reinvoked, I am getting **Kafka handle is closed ObjectDisposedException**. If same code snippet, I will run in a simple Console application its working fine.

Code:
                      
           private Consumer<string, string> 
           kafkaConsumer = null; // Private 
           global property
           for (int i = 0; i < 9; i++)
           {
                 Task.Run(() => ConsumeKafkaMessages());
           }
            private void ConsumeKafkaMessages()
            {
                kafkaConsumer = new Consumer<string, string>(ConstructConfig(AutoCommitOffset ?? false), 
                new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8));

                kafkaConsumer.OnPartitionEOF += (_, end) =>
                {  

                };

                kafkaConsumer.OnError += (_, error) =>
                { 

                };
                  
                kafkaConsumer.OnPartitionsAssigned += (_, partitions) =>
                {   
                     kafkaConsumer.Assign(partitions);
                 };
              
                kafkaConsumer.OnPartitionsRevoked += (_, partitions) =>
                {
                    try
                   {
                        kafkaConsumer.Unassign(); // Here I am getting the error
                   }
                   catch { };
                 } 
                 kafkaConsumer.Subscribe(topicName);
           }

           private Dictionary<string, object> constructConfig(bool enableAutoCommit = false)
           {
                return new Dictionary<string, object>
                {
                   { "group.id", (ConsumerGroupName.Length > 0) ? ConsumerGroupName 
                   Guid.NewGuid().ToString() },
                   { "enable.auto.commit", enableAutoCommit },
                   { "enable.auto.offset.store", AutoStoreOffset ?? true },
                   { "auto.commit.interval.ms", AutoCommitInterval ?? 5000 },
                   { "statistics.interval.ms", StatisticsInterval ?? 60000 },
                   { "bootstrap.servers", BrokerAddress },
                   { "default.topic.config", new Dictionary<string, object>()
                       {
                           { "auto.offset.reset", "earliest" }
                       }
                   }
                };
           }

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: v0.11.6
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [x] Operating system: Windows 7
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
you're not keeping a reference to the consumers around, so they'll get garbage collected. the object disposed exception is something we've included to prevent disposed objects from being used. this can also get hit during a callback before the consumer finalization code is run which cleans up the librdkafka instance. this is not ideal, but it serves it's purpose of indicating error in usage (and doing better is difficult and would result in a perf hit).

finally, you probably don't want to be creating 10 consumers - you probably want to be using one for everything.

**Comment by JohnKo009** [comment]
What do you mean by keeping the references around? I am not getting any error when I run the same code in an Console application only getting this error in an windows service. 
And what will be disadvantage for creating multiple consumer instances? My scenario is I have to concurrently process messages and do some code execution for faster processing.

**Comment by avibe948** [comment]
I can confirm that this works properly matt.

**Comment by yaswanthkata** [comment]
@JohnKo009 Facing the same issue works fine in a wpf application, but fails in .net core 3.0 web application
