### ISSUE TITLE
producer   slowly.

### ISSUE THREAD

**Issue by summer092** [confluentinc/confluent-kafka-dotnet#814]
Description
===========
why producer is so slowly.  100 data need 15second

How to reproduce
================
![image](https://user-images.githubusercontent.com/5291221/54012963-9d446480-41b2-11e9-878c-4285d35b5d84.png)

![image](https://user-images.githubusercontent.com/5291221/54012998-b3eabb80-41b2-11e9-8f47-d8449037d9a2.png)

how to resolve it

Checklist
=========
Please provide the following information:

 - [ 0.11.6.0] Confluent.Kafka nuget version:
 - [ 2.1.1] Apache Kafka version: 
 - [] Client configuration:
 - [windows server 2012 r2 ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
don't call `Flush` after each `ProduceAsync` call. only call this before disposing the producer.
