### ISSUE TITLE
Consumer: seek to end of a partition

### ISSUE THREAD

**Issue by NickP82** [confluentinc/confluent-kafka-dotnet#816]
Hi all, 

I am consuming kafka topics. How can I get the information for an topic what the last availabe offset per partition is? 
I want to seekToEnd for some topics at startup. 
consumer.seekToEnd() is not supported so far I see. 

I am using Version 0.11.6

Kind regards,
Nick

**Comment by mhowlett** [comment]
you can use `Offset.End`

**Comment by NickP82** [comment]
Too easy. Thanks.
