### ISSUE TITLE
Sending message to specific partition.

### ISSUE THREAD

**Issue by john1401990** [confluentinc/confluent-kafka-dotnet#818]
Description
===========
I am trying to send message to specific partition.

Currently I have 15 partitions and I am trying to send message to a specific partition. For that I have a key saved in Redis and that gives me an integer value, after getting the value I divide that by 15 (which is total numbers of partition) and use the remainder as partition.

For example: If Redis returned me 5 then I will do **5%15** which will return **5** and then I will use "ProduceAsync(String, TKey, TValue, Int32)", and pass 5 as 4th parameter. 

In short if remainder is 0 then message should go to 0th partition and if remainder is 1 then message should go to 1st partition. 

The above setup worked well when there is only 1 broker and the same code is not working when there are multiple brokers.

Is this the right way or is there any other way to achieve this type of scenario?

Following is the link from where I get this idea:
https://docs.confluent.io/current/clients/confluent-kafka-dotnet/api/Confluent.Kafka.Producer-2.html#Confluent_Kafka_Producer_2_ProduceAsync_System_String__0__1_System_Int32_

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3.0
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
yep, that's correct - it should work. 

strongly advise upgrading to a later version of the client (preferably 1.0-beta3 which has many bug fixes and improvements over 0.11.3). Happy to help debug if you're also experiencing this problem with that version.
