### ISSUE TITLE
Need a help

### ISSUE THREAD

**Issue by namroot** [confluentinc/confluent-kafka-dotnet#82]
Hello,
I can't catch the exception when the Kafka server is unavailable.
In the console, i can see these messages:
`7|2017-02-28 15:12:14.991|rdkafka#producer-1|CONNECT| kafka1.Server.frr:9092/bootstrap: broker in state INIT connecting
7|2017-02-28 15:12:14.997|rdkafka#producer-1|BROKERFAIL| kafka1.Server.frr:9092/bootstrap: failed: err: Local: Host resolution failure: (errno: Bad address)
3|2017-02-28 15:12:14.998|rdkafka#producer-1|FAIL| kafka1.Server.frr:9092/bootstrap: Failed to resolve 'kafka1.Server.frr:9092': Hôte inconnu.
7|2017-02-28 15:12:14.998|rdkafka#producer-1|STATE| kafka1.Server.frr:9092/bootstrap: Broker changed state INIT -> DOWN
7|2017-02-28 15:12:14.998|rdkafka#producer-1|BROADCAST| Broadcasting state change`

The framework used is:
framework :  supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1"
Kafka library: Confluent.Kafka.0.9.4-preview2 & Confluent.Kafka.0.9.4-preview8

I must  necessarily capture the exception before proceeding with the next message.
The source code is in the attachment.
Thank you for your help

[Main.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/807056/Main.txt)

**Comment by mhowlett** [comment]
You should let Confluent.Kafka manage connection problems behind the scenes. Check the `Error` property on delivery reports for any problems with message delivery and resend if necessary. You can also use the `message.send.max.retries` and `retry.backoff.ms` config parameters to control how Confluent.Kafka helps you to do this automatically.

Distributed systems are complex - for example, when a broker goes down, the leader for partitions for which it was formerly the leader will move to another broker. Consequently, the broker to which the client should be sending messages will change (you do not care that the connection to the original broker was lost!).

Confluent.Kafka takes care of all of these complexities for you.
