### ISSUE TITLE
Creating partitions in producer

### ISSUE THREAD

**Issue by pavanarya** [confluentinc/confluent-kafka-dotnet#825]
Hi, is it possible to create partitions using confluent.kafka package.

Even when I am using patitioner.random in the config, but still I am seeing only one partition

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
yes, you can specify the number of partitions in `AdminClient.CreateTopicsAsync`, or increase the number of partitions in an existing topic using `AdminClient.CreatePartitionsAsync`. typically you should specify the number of partitions when you create the topic and not change this. note that auto topic creation is on by default (a broker setting), which will create topics you reference automatically if they don't exist and by default this will create topics with one partition. i'm guessing you're doing that?

**Comment by pavanarya** [comment]
Yep I am making use of automatic topic creation . Yep I'll give a try with AdminClient
