### ISSUE TITLE
How to implement seek after assign?

### ISSUE THREAD

**Issue by masyyy** [confluentinc/confluent-kafka-dotnet#827]
Description
===========
I have a usecase where I want to assign a topic and a partition on a consumer. After this I want to find the offset corresponding to a specific timestamp by using offsetsfortimes and then I want to seek to that offset and consume from there. However just calling assign => seek => consume produces Erroneous state exceptions. I found out that doing assign => consume => seek => consume seems to work, but im not sure if this is the right way of going about this.

How to reproduce
================
Assign topic and partition to consumer followed by seek and then consume.

Checklist
=========
Please provide the following information:

 - [v1.0.0-beta3 ] Confluent.Kafka nuget version:
 - [Kafka 2.11 ] Apache Kafka version:

**Comment by mhowlett** [comment]
You should be able to call `OffsetsForTimes` on the consumer instance before `Assign` to get the required offsets, then call `Assign` with `List<TopicPartitionOffset>` to specify the start offsets (no need to call `Seek`). The way librdkafka works here is a bit different here to the Java consumer.
