### ISSUE TITLE
GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed

### ISSUE THREAD

**Issue by esmelov** [confluentinc/confluent-kafka-dotnet#828]
Client OS: Windows 10 version 1803 (OS Build 17134.590)
Kafka client: Confluetn.Kafka 1.0.0-beta3-ci-880
Framework: .Net Core 2.2
Docker image: openSdk
Host OS: Oracle Linux
Kafka version: 2.1.1 

               `var consumerConfig = new ConsumerConfig
                {
                    GroupId = "custom-group",
                    BootstrapServers = _bootstrapServers,
                    AutoOffsetReset = AutoOffsetReset.Earliest,
                    BrokerAddressFamily = BrokerAddressFamily.V4
                };

                using (var consumer = new ConsumerBuilder<long, T>(consumerConfig)
                                          .SetValueDeserializer(new CustomDeserializer<T>())
                                          .SetErrorHandler((key, item) => Console.WriteLine("Consumer error: " + item.Reason))
                                          .Build())
                {
                    consumer.Subscribe(topic);

                    while (!cancellationToken.IsCancellationRequested)
                    {
                        var consumeResult = consumer.Consume(cancellationToken);
                        action?.Invoke(consumeResult.Value);
                    }
                }`

_bootstrapServers = XXX.XXX.XXX.XXX:9092

Telnet on server and port connect success.

On subscribe I get next error:

> Consumer error: GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed: No connection could be made because the target machine actively refused it... (after 1010ms in state CONNECT)

But my bootstrapServers are different from localhost.

What could be my mistake?

**Comment by edenhill** [comment]
The broker is advertising itself as localhost. See the broker's advertised.listeners configuration property.

**Comment by esmelov** [comment]
@edenhill Thank you!!!
