### ISSUE TITLE
Topic count limits on Consumer

### ISSUE THREAD

**Issue by alexandery** [confluentinc/confluent-kafka-dotnet#830]
Description
===========
It is recommended to stand up a single Consumer instance and use that to fetch messages from multiple topics (obviously this is a generic recommendation). My use case requires supporting multi-tenanted environments with hundreds of tenants.

1. What is the maximum number of topics a single Consumer can safely deal with? Is there such a number? Would I be able to subscribe to, potentially, 100-200-300 topics using a single Consumer?
2. What would be the overhead of serving few hundred topics in a single process (via a single of multiple instances of Consumer) - both client side and server side? Any approximation would be helpful.
3. I presume there are no cross-instance issues in case I initialize multiple instances of Consumer in a single process?
4. Does Producer has any such limitations (since topic name is a parameter to Produce method I would think there should not be any potential limitations)?

P.S. I was unable to find such stats and not sure if anyone has really looked into the capacity supported by .NET Confluent library.

Thank you!

**Comment by mhowlett** [comment]
1. 300 topics should be no problem at all.
2. A single consumer instance is much more efficient - 1. you will only have one connection to each broker 2. metadata requests (that are required at various times for various reasons) won't need to be made for each client. 3. data is batched for multiple topics resulting in far fewer broker requests.
3. Multiple client instances won't interfere with each other.
4. You should prefer a single producer instance.

**Comment by alexandery** [comment]
Thank you @mhowlett for quick answer!

When you say that data is batched for multiple topics - how does that work with few hundreds of topics? Does client receive batches per-topic or does messages from all topics get batched and received? Assuming I've got 200 topics with messages in each, what is the batching strategy then - 200 messages in a batch with 1 message from each topic or X messages from Y topics?

**Comment by mhowlett** [comment]
yes, messages from more than one topic can be included in a single fetch response from the broker. note that what gets included in a fetch response is impacted by the max fetch response size config.

https://github.com/apache/kafka/blob/trunk/clients/src/main/resources/common/message/FetchResponse.json#L50
