### ISSUE TITLE
Confusion between await and flush

### ISSUE THREAD

**Issue by rajazeeshan82** [confluentinc/confluent-kafka-dotnet#836]
Description
===========
I am creating a library for our team that will be used in multiple C# applications to send messages to Kafka. One of the requirements for the library is calling application should be informed when message fails to make it to Kafka so they can fail the Rest request or if they are in a background processor they can retry. I am confused about if I use await will it throw exception when message is not acked by Kafka broker or I have to use flush to send message?  

  var dr = await producer.ProduceAsync(
                        singlePartitionTopic,
                        new Message<Null, string> { Value = "test string" });
                    Assert.Equal(0, producer.Flush(TimeSpan.FromSeconds(10)));

In the code above when await finishes I should have dr that has partition returned by broker why would I need to flush then? Any help in this matter will be appreciated.
Thanks !

**Comment by mhowlett** [comment]
you should typically only use flush immediately before disposing a producer and only if you want to ensure any outstanding messages are delivered (or time out).

you should rely on exceptions from `ProduceAsync` to inform you of all errors (catch `ProduceException<K,V>` which has an `Error` property with `ErrorCode`).

note: I've just discovered a few minor issues with this (the type of exception thrown in some instances), which I'll resolve in a PR tomorrow. delaying RC1 because of it.

**Comment by rajazeeshan82** [comment]
Thanks mhowlett!
So to just be clear in my case to implement synchronous publish and failure for calling applications following pattern will suffice and just bubbling ProduceException will do the trick !  Does `await` makes sure the message in question is flushed? 
```
using System;
using System.Threading.Tasks;
using Confluent.Kafka;

class Program
{
    public static async Task Main(string[] args)
    {
        var config = new ProducerConfig { BootstrapServers = "localhost:9092" };

        // If serializers are not specified, default serializers from
        // `Confluent.Kafka.Serializers` will be automatically used where
        // available. Note: by default strings are encoded as UTF8.
        using (var p = new ProducerBuilder<Null, string>(config).Build())
        {
            try
            {
                var dr = await p.ProduceAsync("test-topic", new Message<Null, string> { Value="test" });
                Console.WriteLine($"Delivered '{dr.Value}' to '{dr.TopicPartitionOffset}'");
            }
            catch (ProduceException<Null, string> e)
            {
                Console.WriteLine($"Delivery failed: {e.Error.Reason}");
            }
        }
    }
}
```

**Comment by mhowlett** [comment]
yes, awaiting will return only after the message is produced, or errored (including timeout). but if you dispose the producer whilst produce calls are being awaited, they won't block. That reminds me, I need to test that scenario to make sure behavior is ok, thanks for reminding me.

**Comment by rajazeeshan82** [comment]
mhowlett - This was very helpful I greatly appreciate your help !
