### ISSUE TITLE
Consumer OnMessage event not working when other events handlers are attached.

### ISSUE THREAD

**Issue by PiotrKowalski93** [confluentinc/confluent-kafka-dotnet#841]
Description
===========
I created consumer and added OnMessage Event. My event is triggered and i can read all messages but when i add other events like: OnPartitionsAssigned, processing does not work. Only OnPartitionsAssigned works when I add other consumer to the same topic etc.

How to reproduce
================
var consumer = new Consumer<Null, string>(_clientSettings, null, new StringDeserializer(Encoding.UTF8));

consumer.OnMessage += Consumer_OnMessage;

 consumer.Subscribe("Test");

 while (!token.IsCancellationRequested) // can be while (true)
 {
    consumer.Poll(2000);
}

but with this does OnMessage is not triggered:

consumer.OnPartitionsAssigned += Consumer_OnPartitionsAssigned;

and any other event is not working:

consumer.OnConsumeError += Consumer_OnConsumeError;
consumer.OnError += Consumer_OnError;
consumer.OnOffsetsCommitted += Consumer_OnOffsetsCommitted;
consumer.OnStatistics += Consumer_OnStatistics;
consumer.OnLog += Consumer_OnLog;
consumer.OnPartitionEOF += Consumer_OnPartitionEOF;
consumer.OnPartitionsRevoked += Consumer_OnPartitionsRevoked;

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version: 0.11.6
 - [X] Apache Kafka version: 2.11-2.1.1
 - [X] Client configuration:

_clientSettings = new Dictionary<string, object>()
{
      { "bootstrap.servers", "XXX.XXX.XXX.XXX:XXXX" },
      { "enable.auto.commit", "false" },
      { "group.id", "testId"}
};

 var defaultTopicConfig = new Dictionary<string, object>()
{
      { "auto.offset.reset", "false"}
};

                _clientSettings.Add("default.topic.config", new Dictionary<string, object>(defaultTopicConfig));

 - [X] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
In v0.11.6, if you specify an `OnPartitionsAssigned/Revoked` event handler, you must call the `Assign` or `Unassign` method in your handler to cause the consumer to start reading from the partitions assigned by the consumer group.

v1.0-RC1 fixes many API design issues such as the above. It also contains many bug fixes that won't be back ported and provides many more features, for example an AdminClient. I would highly recommend moving to the new API.

**Comment by PiotrKowalski93** [comment]
Ok, thank you for information. I am writing new client based on v1.0-RC1 then 👍 When v1.0 will be released ?

**Comment by pranavrth** [comment]
We are now at v2.x . These issues are solved. Closing this issue. Please raise a new request if facing the issue.
