### ISSUE TITLE
Slow producer when messages are published on multiple threads to same broker and topic

### ISSUE THREAD

**Issue by vikas15bhardwaj** [confluentinc/confluent-kafka-dotnet#843]
Description
===========
The producer performance turns out to be very slow, takes up to 2 seconds in publishing messages on each thread. Each thread is publishing a batch of messages using ProduceAsync and then waiting for the batch to finish so that we can handle the errors for the batch on that thread. Running the same code on one thread to publish same amount of messages in batch takes significantly less time (0-50ms) .
After reading lots of threads, tried various options but it could not work as expected in multiple thread scenarios.
[SampleKafkaProducer.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/2997650/SampleKafkaProducer.zip)

How to reproduce
================

Run the below code via a Windows Console Application .Net framework 4.6.2 using nuget version 1.0.0-RC1

This code has two methods 
- PublishParallel sends 2K messages to a topic on 100 threads in a batch of 20 messages
- PublishSequential sends 2K messages on same topic on 1 thread in a batch of 20 messages

Application first run PublishParallel and print each batch time and total time and then prompt to run the same test using PublishSequential. 

`using Confluent.Kafka;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SampleKafkaProducer
{

    class Program
    {
        static void Main(string[] args)
        {
            DateTime start = DateTime.Now;

            PublishParallel("test-topic");
            Console.WriteLine($"done parallel {(DateTime.Now - start).TotalMilliseconds}");

            Console.WriteLine("Press any key to send messages on one thread");

            Console.ReadLine();
            start = DateTime.Now;
            PublishSequential("test-topic");
            Console.WriteLine($"done one thread {(DateTime.Now - start).TotalMilliseconds}");

            Console.ReadLine();

        }

        static void PublishParallel(string topic)
        {
            try
            {
                //parallel for loop spinning 100 threads to publish messages to same topic using same instance of producer.
                Parallel.For(0, 100, (count) =>
                {
                    //always get same producer instance
                    KafkaPublisher kafka = KafkaFactory.GetPublisher();
                    List<string> messageList = new List<string>();
                    for (int i = 0; i < 20; i++)
                        messageList.Add($"{count} - this is a test message {i.ToString()}");

                    kafka.Publish(messageList, topic);
                });
            }
            catch (AggregateException ex)
            {

                var exceptions = from e in ex.InnerExceptions
                                 select e as ProduceException<string, string>;

                foreach (var exc in exceptions)
                    Console.WriteLine(exc != null ? "error:" + exc.DeliveryResult.Key.ToString() : "");

                Console.WriteLine(ex.ToString());
            }

        }

        static void PublishSequential(string topic)
        {
            try
            {
                for(int count = 0; count < 100;  count++)
                {
                    //always get same producer instance
                    KafkaPublisher kafka = KafkaFactory.GetPublisher();
                    List<string> messageList = new List<string>();
                    for (int i = 0; i < 20; i++)
                        messageList.Add($"{count} - this is a test message {i.ToString()}");

                    kafka.Publish(messageList, topic);
                };
            }
            catch (AggregateException ex)
            {

                var exceptions = from e in ex.InnerExceptions
                                 select e as ProduceException<string, string>;

                foreach (var exc in exceptions)
                    Console.WriteLine(exc != null ? "error:" + exc.DeliveryResult.Key.ToString() : "");

                Console.WriteLine(ex.ToString());
            }

        }
    }

    internal class KafkaFactory
    {
        static KafkaPublisher _publisher;
        static object _syncRoot = new object();
        internal static KafkaPublisher GetPublisher()
        {
            if (_publisher != null)
                return _publisher;

            else
            {
                lock (_syncRoot)
                {
                    if (_publisher != null)
                        return _publisher;
                    else
                    {
                        Console.WriteLine("Creating new object");
                        _publisher = new KafkaPublisher();
                        return _publisher;
                    }

                }
            }
        }

    }
    internal class KafkaPublisher : IDisposable
    {
        IProducer<string, string> _producer;
        internal KafkaPublisher()
        {
            var config = new ProducerConfig { BootstrapServers = "localhost:9092" };
            //
            config.MessageSendMaxRetries = 0;
            config.MessageTimeoutMs = 10000;
            config.BatchNumMessages = 100;
            config.TopicMetadataRefreshIntervalMs = 10;
            //config.Debug = "all";

            //config.SocketNagleDisable = true;
            _producer = new ProducerBuilder<string, string>(config).Build();
        }

        public void Publish(List<string> messageList, string topic)
        {
            int i = 0;
            DateTime start = DateTime.Now;
            var tasks = from message in messageList
                        select _producer.ProduceAsync(topic, new Message<string, string> { Key = i++.ToString(), Value = message });

            Task.WaitAll(tasks.ToArray());
            Console.WriteLine($"published: {(DateTime.Now - start).TotalMilliseconds}");
        }
        public void Dispose()
        {
            if (_producer != null)
                _producer.Dispose();
        }
    }
}
`
Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-RC1
 - [x] Apache Kafka version: kafka_2.12-2.1.1 on Windows 2012 R2 DataCenter
 - [x] Client configuration: see app
 - [x] Operating system: Windows 2012 R2 Data Center
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration) - Tried capturing debug info, nothing showed up when enabled.
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks @vikas15bhardwaj for providing a complete minimal example demonstrating the problem - was able to replicate, and also see the same behavior on linux. It's not immediately obvious to me why this is occurring, so want to look into it, however likely won't until after the 1.0 release.

As a general comment I think it's a good idea to avoid waiting on bunches of produce results in this way, unless it's a strong match to the specific use case.

**Comment by vikas15bhardwaj** [comment]
Thanks Matt for quickly responding and reproducing it. I understand wait is not desirable but if we want to ensure messages are delivered and if we need to take some action on those messages after publishing, we have no option but to call wait. After looking into more, I also changed my above sample code Publish method slightly to use ContinueWith in addition to WaitAll

```
 var tasks = from message in messageList
                        select _producer.ProduceAsync(topic, new Message<string, string> { Key = i++.ToString(), Value = message })
                        .ContinueWith((dr) => 
                            {
                                //Console.WriteLine($"published: {(DateTime.Now - start).TotalMilliseconds}");
                                Console.WriteLine(dr.Result.TopicPartitionOffset.ToString());
                            });

            Task.WaitAll(tasks.ToArray());
```
and it gave me better results. I am not sure though why and how. This didn't fix it everything for me. As when I applied to my actual solution, it gave me inconsistent results, especially at the start of the process or when few thousands of small batch messages are sent on multiple threads concurrently. In these cases, I noticed ProduceAsync keep sending messages to Kafka but it does not return the thread to complete the wait and as a result threads keep waiting. Is this something you can look at before 1.0 release as it may help multiple people.

**Comment by mhowlett** [comment]
Below are four alternatives (with commentary) to what you are trying to do, all of which are fast. I admit to not fully understanding the root cause of why `Parallel.For` doesn't play nicely with `ProduceAsync`, but I did read it doesn't play nicely with async/await methods, and I think it's unlikely to be exactly what you want, so i didn't investigate further.

**Test2**: Is close to what you're trying to do - it uses `Parallel.For` but instead of `ProduceAsync`, uses `BeginProduce`. Note that `BeginProduce` is much faster than `ProduceAsync` because it has less overhead. It also doesn't have any async code so it works with `Parallel.For`. The (conceptual) problem with this variation is it wastes threads - there will be many threads blocking (the degree of the problem depends on the characteristics of the tasks). As it turns out, the overhead of this in these toy cases is minimal and this approach is very fast.

**Test4**: is Test2, but uses `Task.Run` instead of `Parallel.For`. I suspect this is what you would use in practice a real application (not parallel for). This is also very fast.

**Test1**: this is how to set it up properly in a fully async manner. Conceptually, no wasting of threads going on, but all the `Task`s and async/await state machine overhead makes this about 3x slower than Test2 or Test4.

**Test3**: A cross between the above methods (primarily async). About the same performance as Test1.

In conclusion, if you want to set things up in a nice async way, go with something like Test1. If you're concerned with getting the highest performance possible, something like Test4 is probably going to win.

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using System.Linq;
using System.Threading.Tasks;
using Confluent.Kafka;
using Confluent.Kafka.Admin;

namespace TestParallel
{
    class Program
    {
        async static Task BatchTask(IProducer<int, string> producer)
        {
            var tasks = Enumerable.Repeat<int>(0, 1000)
                .Select((_, i) 
                    => producer.ProduceAsync(
                        "parallel-test-topic",
                        new Message<int, string> { Key = i, Value = $"message {i}" }))
                .ToArray();
            await Task.WhenAll(tasks);
            // await DoOtherStuff(); - other stuff that depends on the above being completed.
        }

        static void Test1(IProducer<int, string> producer)
        {
            var tasks = Enumerable.Repeat<int>(0, 1000)
                .Select(_ => BatchTask(producer))
                .ToArray();
            Task.WaitAll(tasks);
        }

        static void BatchTask2(IProducer<int, string> producer)
        {
            var N = 1000;
            var drCount = new CountdownEvent(N);
            for (int i=0; i<N; ++i)
            {
                producer.BeginProduce(
                    "parallel",
                    new Message<int, string> { Key = i, Value = $"message {i}" },
                    dr => 
                    {
                        drCount.Signal();
                    });
            }
            drCount.Wait();
        }

        static void Test2(IProducer<int, string> producer)
        {
            Parallel.For(0, 1000, count => BatchTask2(producer));
        }

        static void Test3(IProducer<int, string> producer)
        {
            var tasks = new List<Task>();
            for (int i=0; i<1000; ++i)
            {
                tasks.Add(Task.Run(async () =>
                {
                    await BatchTask(producer);
                }));
            }
            Task.WaitAll(tasks.ToArray());
        }

        static void Test4(IProducer<int, string> producer)
        {
            var tasks = new List<Task>();
            for (int i=0; i<1000; ++i)
            {
                tasks.Add(Task.Run(() =>
                {
                    BatchTask2(producer);
                }));
            }
            Task.WaitAll(tasks.ToArray());
        }

        static void Main(string[] args)
        {
            var config = new ProducerConfig
            {
                BootstrapServers = "127.0.0.1:9092",
                LingerMs = 5,
                QueueBufferingMaxMessages = 2000000
                // Debug = "msg"
            };

            using (var producer =
                new ProducerBuilder<int, string>(config)
                    .SetLogHandler((p, m) => 
                    {
                        Console.WriteLine(DateTime.Now.ToString("HH:mm:ss.FFF") + " " + m.Message);
                    })
                    .Build())
            {
                var methods = new Action<IProducer<int, string>>[] { Test1, Test2, Test3, Test4 };

                foreach (var method in methods)
                {
                    Stopwatch sw = new Stopwatch();
                    sw.Start();
                    method(producer);
                    Console.WriteLine($"total time: {sw.Elapsed}");
                }
            }
        }
    }
}
```

**Comment by vikas15bhardwaj** [comment]
Thanks Matt for providing these options, I will look into these and will try. I also changed on my side the patterns threads were being creating and it removed the thread blocking issue. I will also give these options a try. For now I think I am good.

**Comment by lonnie749** [comment]
> thanks [@vikas15bhardwaj](https://github.com/vikas15bhardwaj) for providing a complete minimal example demonstrating the problem - was able to replicate, and also see the same behavior on linux. It's not immediately obvious to me why this is occurring, so want to look into it, however likely won't until after the 1.0 release.
> 
> As a general comment I think it's a good idea to avoid waiting on bunches of produce results in this way, unless it's a strong match to the specific use case.





+1
