### ISSUE TITLE
Consumer release resources has a problem.(Consumer.Close() or Dispose())

### ISSUE THREAD

**Issue by longbaochenlong** [confluentinc/confluent-kafka-dotnet#846]
Description
===========

When release the consumer's resources,I try to use Consumer.Close() or Dispose().But this method conflict with Consumer.Consume() method.And this error can not capture.I need your help.The follow is my code.

1.Build a consumer
 var consumerConfig = new ConsumerConfig
            {
                GroupId = Guid.NewGuid().ToString(),
                BootstrapServers = context.CurrentOptions.Addresses,
                EnableAutoCommit = false,
                StatisticsIntervalMs = 5000,
                SessionTimeoutMs = 6000,
                AutoOffsetReset = AutoOffsetReset.Earliest,
                EnablePartitionEof = true
            };
            _consumer = new ConsumerBuilder<Ignore, string>(consumerConfig).Build();

2.Start listening and receiving messages.
private void StartListen()
        {
            const int commitPeriod = 5;
            Task.Run(() =>
            {
                while (!_cts.IsCancellationRequested)
                {
                    try
                    {
                        var consumeResult = _consumer.Consume(_cts.Token);
                        if (null != consumeResult)
                        {
                            if (0 == consumeResult.Offset % commitPeriod || consumeResult.IsPartitionEOF)
                            {
                                _consumer.Commit(consumeResult);
                            }
                            if (null != consumeResult.Message)
                                _context.CurrentMessageManager.EnqueueMessage(MessageInfo.Create(consumeResult.Value, consumeResult.Topic));
                        }
                    }
                    catch (Exception ex)
                    {
                        //写日志
                    }
                }
            }).ConfigureAwait(false);
        }
3.Release resources,but conflict with step2 var consumeResult =_consumer.Consume(_cts.Token);
this error for memory.
public void Dispose()
        {
            if (null != _cts)
            {
                _cts.Cancel();
                _cts.Dispose();
                _cts = null;
            }
            if (null != _consumer)
            {
                _consumer.Unsubscribe();
                _consumer.Close();
                //_consumer.Dispose();
                _consumer = null;
            }
            
        }
How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-RC1
 - [x] Apache Kafka version: kafka_2.11-2.1.0
 - [ ] Client configuration:
 - [x] Operating system:windows10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
wait for the consume loop to finish before disposing the consumer. 

if you're having problems still, please provide a complete working minimal example and i'll update it.

**Comment by longbaochenlong** [comment]
I do not know when the consume loop is finish.There is a someone uncomfortable solution in which I set a thread await just like Thread.Sleep(CancellationDelayMaxMs) before disposing the consumer.
step 1.
var consumerConfig = new ConsumerConfig
            {
                GroupId = Guid.NewGuid().ToString("D"),
                BootstrapServers = "brokerlist",
                EnableAutoCommit = false,
                StatisticsIntervalMs = 5000,
                SessionTimeoutMs = 6000,
                AutoOffsetReset = AutoOffsetReset.Latest,
                EnablePartitionEof = true,
                **CancellationDelayMaxMs = 1//set CancellationDelayMaxMs** 
            };
            _consumer = new ConsumerBuilder<Ignore, string>(consumerConfig).Build();

step 2. disposing the consumer
  Thread.Sleep(1);
                _consumer.Close();

In fact,I do not wanna to sleep the thread.If there is any better way, please give a reply.Thanks.
