### ISSUE TITLE
Seek to a timestamp

### ISSUE THREAD

**Issue by vigneshc** [confluentinc/confluent-kafka-dotnet#85]
Hi,

I tried to find an API that 1. Finds offset for a given timestamp 2. Seeks consumer to that offset and start reading from that offset. Both of this doesn't exist.

RdKafka has offset request, and I think it also has some kind of seek.
Will these be added in the future in kafka-dotnet?

**Comment by mhowlett** [comment]
Hi @vigneshc -

1. currently seeking to a given timestamp is not supported by the C# client. The functionality exists in librdkafka though (rd_kafka_offsets_for_times), so it shouldn't be too difficult to add. I don't have a timeframe, but I suspect the cost/benefit will have us implementing this before too long.

2. Yes, you can start reading from any offset. The `Consumer.Assign` overload has a variant that takes an `IEnumerable<TopicPartitionOffset>` which allows you to do this.

**Comment by vigneshc** [comment]
Thanks. I do see Assign with IEnumerable<TopicPartitionOffset> overload
