### ISSUE TITLE
Estimated timeline for releasing the version 1.0.0 as an official

### ISSUE THREAD

**Issue by x-Zyte** [confluentinc/confluent-kafka-dotnet#850]
Do you have an estimated timeline for releasing the version 1.0.0 as an official?

**Comment by mhowlett** [comment]
probably next week. we'll delay this if we find an important issue with the API before then. i'm not aware of anything, but currently actively looking.

**Comment by avibe948** [comment]
I would like to ask this question again. Using RC4 and we have about 45 days before go live and I won't be able to go live without an official release (@UBS)

**Comment by mhowlett** [comment]
unfortunately, a couple of blocker issues came up just before release time. PRs are open to resolve, @edenhill is currently reviewing - #887 and #888. when they are in, we will do an RC5. I hope tomororw. We will release 1.0 a few days after RC5 assuming no additional blocker issues are found. we have finished actively looking for API issues and testing.
