### ISSUE TITLE
How to set compression in latest api

### ISSUE THREAD

**Issue by 123George** [confluentinc/confluent-kafka-dotnet#857]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by 123George** [comment]
We use both java and c# clients. Currently, in java we set compression to LZ4. In the c# version, we declare a dictionary and set  LZ4 via compression.codec. We can do this is old and latest api. However, when we use the consumer config class, there is no setting to set directly compression=LZ4, instead we have to  choose the compression level number.How do we set compression in the consumer config class to LZ4 to match to java?

Thanks

**Comment by mhowlett** [comment]
for now you can use the `Set` method on the consumer config class. This is a bug - the consumer config class is auto-generated from the librdkafka documentation, and for some reason CompressionType isn't being created. thanks for reporting.

**Comment by bartelink** [comment]
For avoidance of doubt, `CompressionType` seems to be be the only major Enum [that's not represented as such in the .NET API, necessitating me adding a shim one in a wrapper of ours](https://github.com/jet/Jet.ConfluentKafka.FSharp/blob/v1/src/Jet.ConfluentKafka.FSharp/ConfluentKafka.fs#L57) - it'd be nice to see same added to the API so we can use that directly as we've been able to do for all other aspects (we used to have lots of custom types in this wrapper lib).

**Comment by mhowlett** [comment]
resolved in #858
