### ISSUE TITLE
Cannot manage heartbeat frequency

### ISSUE THREAD

**Issue by hakankurcenlivivense** [confluentinc/confluent-kafka-dotnet#859]
I am using Confluent's C# Kafka client 1.0.0-RC2 nuget. When the consumer starts consuming, I observe using Wireshark that about 16 request are made to the server per second. I tried setting "`HeartbeatIntervalMs = 3000`" in the consumer config but it did not change anything. 

Requests are pairs of encryptic characters. In each pair of requests, the first one is about 60 bytes on wire and the second is about 140 bytes on wire. The second one contains the word "Kafka" and all of the subscribed topics, which would add upto a lot of data if the number of topics subscribed is high.

The code I am using is the sample code on Confluent's Github page. I just added the `HeartbeatIntervalMs` and `SessionTimeoutMs` but they do not change the frequency of the requests anyway:

    var conf = new ConsumerConfig
            { 
                GroupId = "test-consumer-group",
                BootstrapServers = "localhost:9092",
                // Note: The AutoOffsetReset property determines the start offset in the event
                // there are not yet any committed offsets for the consumer group for the
                // topic/partitions of interest. By default, offsets are committed
                // automatically, so in this example, consumption will only start from the
                // earliest message in the topic 'my-topic' the first time you run the program.
                AutoOffsetReset = AutoOffsetReset.Earliest,
                HeartbeatIntervalMs = 3000,
                SessionTimeoutMs = 10000
            };
    
            using (var c = new ConsumerBuilder<Ignore, string>(conf).Build())
            {
                c.Subscribe("my-topic");
    
                CancellationTokenSource cts = new CancellationTokenSource();
                Console.CancelKeyPress += (_, e) => {
                    e.Cancel = true; // prevent the process from terminating.
                    cts.Cancel();
                };
    
                try
                {
                    while (true)
                    {
                        try
                        {
                            var cr = c.Consume(cts.Token);
                            Console.WriteLine($"Consumed message '{cr.Value}' at: '{cr.TopicPartitionOffset}'.");
                        }
                        catch (ConsumeException e)
                        {
                            Console.WriteLine($"Error occured: {e.Error.Reason}");
                        }
                    }
                }
                catch (OperationCanceledException)
                {
                    // Ensure the consumer leaves the group cleanly and final offsets are committed.
                    c.Close();
                }
            }

**Comment by edenhill** [comment]
Set config property `Debug = "protocol"` to see what protocol request are being sent, I would guess what you are seeing are the FetchRequests

**Comment by hakankurcenlivivense** [comment]
@edenhill I did it now but I cannot see anything in the Debug Output of Visual Studio. Should I be looking somewhere else?

**Comment by mhowlett** [comment]
you need to specify a `LogHandler` in the builder class

**Comment by edenhill** [comment]
@mhowlett shouldn't the default loghandler output to stderr (or its windows counterpart)?

**Comment by mhowlett** [comment]
I'm not sure what the most appropriate destination for logs is in .net. `stderr` probably is appropriate (will need to investigate how that's handled in the various IDEs). Needing to do two things to enable logging is bad UX, yes. A default logger is not implemented yet due to the above open question and also another thing I've been meaning to check up on - if no debug context is configured, are any log messages ever emitted? (it would be best if the answer is no).

**Comment by edenhill** [comment]
Yes, logs may be emitted even if no debug level is set:
`git grep -A5 -E 'rd_(rkb|kafka)_log' src`

And they shall not be quenched by default since they provide meaningful error messages to the user.

I think it might be better for the .NET client to not set a log_cb at all unless one was specified by the user so that librdkafka's default stderr-logger is used.

**Comment by hakankurcenlivivense** [comment]
@edenhill You're right, after adding the log handler, the requests were logged as FetchRequests. And then I managed to adjust the frequency using the '`FetchWaitMaxMs`' parameter. But I could not understand why this parameter is set to 100ms by default., or why it is required in the first place. Since the connection between the consumer and the server is kept alive, and Kafka can send the message to the consumer right after it is produced, why should the consumer be fetching at all? And why does Kafka send a response even when there is nothing to send? Because setting this parameter to a value like 300000ms did not prevent the consumer from receiving messages.

**Comment by edenhill** [comment]
The Kafka protocol is pull based, not push, so the consumer employs a long-polling FetchRequest that blocks for up to fetch.wait.max.ms on the broker.

**Comment by hakankurcenlivivense** [comment]
@edenhill Do you think it would cause a problem to set it to `int.MaxValue`?

**Comment by edenhill** [comment]
Yes, that would not be great since it would block subsequent requests that are enqueued on the same connection.

What is the actual problem you are trying to solve? Is it CPU usage on the client, or broker? Network utilization?

**Comment by hakankurcenlivivense** [comment]
@edenhill I am mostly concerned about network utilization. I have tried it with 100 topics and have seen a bandwidth usage of 680kb/s, consisting of 300 requests and responses combined per second. Let's say we have 50 microservices, then it would add up to 33Mb/s. 

As a side note, I noticed that each request only consists of several topics, and as I add more topics, since names of the topics are sent with the requests, it causes the number of requests to increase. 

Kafka server already knows the topics subscribed by the consumer. Is there a reason why just sending the id of the consumer not enough?

**Comment by edenhill** [comment]
[KIP-227](https://cwiki.apache.org/confluence/display/KAFKA/KIP-227%3A+Introduce+Incremental+FetchRequests+to+Increase+Partition+Scalability) implements something to that end, but it is not yet available in librdkafka.

Try finding a good balance for fetch.wait.max.ms vs blocking behaviour, i.e., 1-2s should be fine.

**Comment by mhowlett** [comment]
> And they shall not be quenched by default since they provide meaningful error messages to the user.

i guess it only seems fair that if informational events can go to the error handler, error events should be able to go to the log handler.
