### ISSUE TITLE
Schema Registry API: RestService client base URL is not accessed 

### ISSUE THREAD

**Issue by FranklyBrandon** [confluentinc/confluent-kafka-dotnet#863]
Description
===========
Confluent.Kafka nuget version : 0.11.6
Confluent.Apache.Avro version : 1.7.7.6
Confluent.SchemaRegistry version : 0.11.6

Any call to the Schema Registry API via the RestService class is throwing an exception: 
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Confluent.SchemaRegistry.RestService.<ExecuteOnOneInstanceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Confluent.SchemaRegistry.RestService.<RequestAsync>d__6`1.MoveNext()

This is likely because the HTTP response coming back from the API service is invalid and cannot be parsed into a Schema object. I believe this is because the proper Client is not being populated or selected in the RestService.ExecuteOnOneInstanceAsync method, because I am able to successfully produce an Avro message if I debug the library and hard code the correct full URL into the GetSchema method calls.

How to reproduce
================
            var config = new Dictionary<string, object>
            {
                { "schema.registry.url", TestConfig.SchemaRegistryURL },
            };

            CachedSchemaRegistryClient client = new CachedSchemaRegistryClient(config);

            var schema = client.GetSchemaAsync(TestConfig.ImportTopic, 1);

Stepping into the createRequest method and replacing the endpoint parameter with the Full endpoint. (base URL) + /subjects/(topic)/versions/(version) will return successfully

Checklist
=========

**Comment by mhowlett** [comment]
just very quickly looked - is this #677? if so it's not resolved yet. If not, please try 1.0.0-RC3.

**Comment by MelonLordRoberts** [comment]
> just very quickly looked - is this #677? if so it's not resolved yet. If not, please try 1.0.0-RC3.

@mhowlett Thanks for the quick reply, I tried 1.0.0-RC3 and that returned a different exception. It seems to be related to #677 as my schema registry URL is an absolute path, though it doesn't end with a forward slash

**Comment by MelonLordRoberts** [comment]
@mhowlett I made a bit of a hacky fix that works well for my team. Since we are only using one SchemaRegistryURL I'm bypassing the client's base URL by :
     1.) saving the SchemaRegistryUrl passed into the RestService constructor as a property. 
     2.) Appending the endpoint parameter passed into the CreateRequest method onto the base URL and passing the full URL to all the subsequent methods from here.

    I haven't spent the time to figure out exactly what is going wrong, but for now this solution is working for me. Hope that's helpful in case anyone in the future has a similar problem

**Comment by Jake7D** [comment]
Has there been any progress on a fix for this? As it doesn't seem to have been fixed in 1.0.0-RC3
We're having the same issue with relative paths within the base url.

A simple fix seems to be just to remove the "/" from the start of the urls in RestService? As the Uri constructor used inside HttpClient removes any relative path parts from the base Uri if you prefix the relativeUri with "/" (https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netframework-4.7.2#System_Uri__ctor_System_Uri_System_String_)

**Comment by mhowlett** [comment]
won't fix in 1.0, targeting 1.0.1 to resolve this.

**Comment by mhowlett** [comment]
I believe this is resolved in 1.3.0-PRE1. Please open a new issue if this is not the case.
