### ISSUE TITLE
Producer best practice

### ISSUE THREAD

**Issue by robertocpsilva1** [confluentinc/confluent-kafka-dotnet#868]
What's the best practice for producer creation in things like web requests?
I believe we should be using one producer for multiple requests, i.e. create a singleton that always provides the same object and going by this [question](https://github.com/confluentinc/confluent-kafka-dotnet/issues/159) that seems correct?

So say if we have a singleton class that creates a producer with `new ProducerBuilder<string, string>(config).Build()` 
Will the GC be able to handle this or do we need to dispose when app is ending? So if we kill/restart the app, would it leak? 
Possibly prematurely worrying here but thought it would be  worth asking.

Cheers

**Comment by mhowlett** [comment]
suggest creating a lightweight wrapper class around the producer that takes `IConfiguration` as a constructor argument and sets everything up + is `IDisposable`. Then add this as a singleton in `ConfigureServices` and use dependency injection to access the instance in your web request handlers.

i'm about to start writing a blog post on exactly this - look out for that (though there is some chance I'll change my mind on the topic, no guarantees until it's out!).

**Comment by Spre3** [comment]
Thanks, sounds good. Looking forward to the blog, where would it be posted?

**Comment by mhowlett** [comment]
the confluent website

**Comment by Rwing** [comment]
> the confluent website

Is there a url now ?

**Comment by mhowlett** [comment]
sorry, haven't done it yet.

**Comment by moxixuan** [comment]
> 
> 
> sorry, haven't done it yet.

😂 url now?

**Comment by joshuajones02** [comment]
How about now?

**Comment by mhowlett** [comment]
no blog post on this but there is a web example now: https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/Web
