### ISSUE TITLE
StatisticsHandler topic is empty

### ISSUE THREAD

**Issue by andreas-soroko** [confluentinc/confluent-kafka-dotnet#869]
Description
===========
hey, i tried to use the adminclient to get statistics but the "topic" property ist empty,
what i am doing wrong or is this a bug ? 

![image](https://user-images.githubusercontent.com/47380084/55730426-70d17180-5a18-11e9-967a-5d987c672f10.png)

How to reproduce
================

```
public class KafkaTest
    {

        public KafkaTest()
        {
            var config = new AdminClientConfig()
            {
                ClientId = "admin-client-stats",
                BootstrapServers = Configuration.KafkaBootstrapServer,
                StatisticsIntervalMs = 10000,
                Debug = "broker,topic,msg"
            };

            var adminClient = new AdminClientBuilder(config)
                .SetStatisticsHandler(StatsHandler)
                .Build();
        }

        private void StatsHandler(AdminClient sender, string json)
        {
            Console.WriteLine(json);
        }
    }
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. (1.0.0-RC3)
 - [x] Apache Kafka version. (0.9.0.1)
 - [x] Client configuration.
 - [x] Operating system. ( win10, x64)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
the admin client doesn't read/write to topics, so there is nothing to report. this will be populated on producers/consumers only.

**Comment by ffandreassoroko** [comment]
i also tried a consumer and got the same result ( topic empty )

(didnt have the code actually, so free from the head... )

```
public class KafkaTest
    {

        public KafkaTest()
        {
            var config = new ConsumerConfig()
            {
                GroupId = "<service-name>",
                BootstrapServers = Configuration.KafkaBootstrapServer,
                StatisticsIntervalMs = 10000
            };

            var consumer = new ConsumerBuilder<TKey,TValue>(config)
                .SetStatisticsHandler(StatsHandler)
		.Set....();
                .Build();
			
			
	  consumer.Subscribe("<my-topic>");
  	  while(true){
		var logEntry = consumer.Consume();
		.....
	  }
        }	

        private void StatsHandler(Consumer<TKey,TValue> sender, string json)
        {
            Console.WriteLine(json);
        }
    }
```

**Comment by ffandreassoroko** [comment]
is there an another way to get the consumer lag for specific (or all) groups ?
