### ISSUE TITLE
Not able to use SSL 

### ISSUE THREAD

**Issue by mrkannan3** [confluentinc/confluent-kafka-dotnet#870]
Description
===========

I am getting the below error while trying to consume 
failed: err: Local: SSL error: (errno: No error)

How to reproduce
================

Followed the steps from here to create certificate,
https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ 1.0.0-beta2] Confluent.Kafka nuget version.
 - [ 5.0.0] confluent Kafka version.
 - [ ] Client configuration.
                  SecurityProtocol = SecurityProtocolType.Ssl
                , SslCaLocation = @"c:\Users\test\certs\ca-root.crt"
                , SslCertificateLocation = @"c:\test\rmohan\certs\localhost_client.crt"
                , SslKeyLocation = @"c:\Users\test\certs\localhost_client.key"

 - [ Client windows & server is linux] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
are you successfully consuming any messages despite the log message?

note: the API has changed a lot and stability improved a lot since 1.0.0-beta2, recommend upgrading.

**Comment by mrkannan3** [comment]
> are you successfully consuming any messages despite the log message? - 
No
> note: the API has changed a lot and stability improved a lot since 1.0.0-beta2, recommend upgrading. 
I will update the dll and update you soon

**Comment by mrkannan3** [comment]
I dont see the even onLog. Could you please let me know what is the new event?

**Comment by mrkannan3** [comment]
Got it. Used SetLogHandler

**Comment by mrkannan3** [comment]
I tested with local after I upgraded to RC4 but I am getting "Local: Key serialization error" while I am trying to produce. Could you please help?
below is the code
`

var producerConfig = new ProducerConfig { BootstrapServers = brokerList, SecurityProtocol = SecurityProtocol.Ssl

                , SslCaLocation = @"c:\tmp\certs\ca-root.crt"
                , SslCertificateLocation = @"c:\tmp\certs\localhost_client.crt"
                , SslKeyLocation = @"c:\tmp\certs\localhost_client.key" };

            using (var schemaRegistry = new CachedSchemaRegistryClient(new SchemaRegistryConfig { SchemaRegistryUrl = schemaRegistryUrl }))
            using (var producer = new ProducerBuilder<string, PatientAccess>(producerConfig)
                    .SetKeySerializer(new AvroSerializer<string>(schemaRegistry))
                    .SetValueSerializer(new AvroSerializer<PatientAccess>(schemaRegistry))
                    .Build())
            {
                try
                {
                    ErrorPV.IdPatient = ErrorPV.IdPatient;// + "Error";
                    var task = producer.ProduceAsync(topic, new Message<string, PatientAccess> { Key = key, Value = ErrorPV });
                    task.Wait();
                }
                catch (Exception e)
                {
                    Log.Error($"Error in producing to error topic  : {e.Message} \n StackTrace: {e.StackTrace} ");
                }`

**Comment by mhowlett** [comment]
for some reason the `AvroSerializer` is failing - check the inner exception(s).

**Comment by mrkannan3** [comment]
Its working now. Thanks for your help. It was the server side config issue. My original issue of the same certificates copying to dev server is not working though. All my test was done on local docker.

**Comment by oliveiramd** [comment]
@mrkannan3 , what kind of issues were there in the server side? I would apprecite your comments!

**Comment by pranavrth** [comment]
Closing the issue. Please open a new one if required.
