### ISSUE TITLE
Wisely ignore the producer config

### ISSUE THREAD

**Issue by edwardzhu** [confluentinc/confluent-kafka-dotnet#873]
Description
===========
My application is a combine of producer and admin of Kafka. In our appsettings.json, the same section is shared for both producer and admin config. It looks like:

````
{
  "Kafka": {
    "bootstrap.servers": "<my server>:9092",
    "dotnet.producer.enable.background.poll": true 
  } 
}
````

The demo code is:
[KafkaDemo.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/3057307/KafkaDemo.zip)

How to reproduce
================
Open the attachment project and launch the application. It throws the exception.
````
System.ArgumentException: 'AdminClient configuration must not include producer or consumer specific configuration properties.'
````

I hope that the `AdminConfig` class can filter the producer-special properties wisely instead of emitting the exception.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version: v1.0.0-RC4
 - [x] Apache Kafka version: Kafka 2.11(2.1.0), Zookeeper 3.4.13
 - [ ] Client configuration.
 - [x] Operating system: Ubuntu 18.04.2 LTS
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
There's an API tradeoff here - we believe it is wiser to prefer strictness over convenience (which can lead to problems - we often see people set in-appropriate config properties by mistake).
