### ISSUE TITLE
1.0.0-RC4 Broker: Unknown member Error

### ISSUE THREAD

**Issue by krudnickas** [confluentinc/confluent-kafka-dotnet#875]
Description
===========
While running a commit, we are receiving the error "Broker: Unknown member".  We have increased our session.timeout to 60 seconds which did not resolve the issue.  This results in re-consuming all messages when the application is restarted.  

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
when/where are you calling `commit`? please provide some more information as specified in the check list, i don't have a good idea based on information provided.

**Comment by ericadams** [comment]
@krudnickas  did you resolve this issue? What was the cause?

**Comment by RaajBadra** [comment]
@krudnickas Have you solved this issue ?
