### ISSUE TITLE
Strong name support for Confluent.SchemaRegistry.Serdes

### ISSUE THREAD

**Issue by TsuyoshiUshio** [confluentinc/confluent-kafka-dotnet#879]
Hi guys, 

Thank you for a cool project!  

Description
===========
I need Strong Named sign. I can see the Kafka project has Strong name sign. However, Confluent.SchemaRegistry.Serdes doesn't have it. 

How to reproduce
================

Include Confluent.SchemaRegistry.Serdes into a strong named project. You will see the error. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1390976/55977586-000e9d00-5c44-11e9-85c7-2db9137e857e.png)

Currently we are using 

```
    <PackageReference Include="Confluent.Kafka" Version="1.0.0-RC3" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes" Version="1.0.0-RC3" />
```

We can switch Confluent.Kafka to strong named one. but not ConfluentSchemaRegistry.Serdes.

**Comment by mhowlett** [comment]
thanks for asking, we're tracking this request internally.

**Comment by mhowlett** [comment]
done - all packages are now signed.
