### ISSUE TITLE
As a consumer read all messages that are in hub

### ISSUE THREAD

**Issue by senzacionale** [confluentinc/confluent-kafka-dotnet#882]
Is there a possibility to read all messages at once from hub when consumer is down and messages were persisted. I would like to get all messages while consumer was offline.

**Comment by mhowlett** [comment]
yes! consumers control their own offset in topic logs using offsets.

**Comment by senzacionale** [comment]
Do you have an example how to do it?

I would expect something like 
var recordsFromConsumer = consumer.poll(10000)

Thank you

**Comment by mhowlett** [comment]
i see what you're asking. no - you can only get one message at a time using `Conusmer.Consume`. Note that behind the scenes the kafka protocol is batched, and the client will aggressively get messages from the brokers as quickly as possible. if you need to work with batches of messages, you'll need to write an abstraction to provide that which sits on top of our api.

**Comment by pranavrth** [comment]
The question is answered and there is no response from the user for a long time. Closing the issue. Please feel free to create a new issue if required.
