### ISSUE TITLE
How to do a same partitioner on C# like Java (Scala)

### ISSUE THREAD

**Issue by OhSirius** [confluentinc/confluent-kafka-dotnet#885]
Description
===========
We have a main backend which is written on Scala with a producer 
(maven assembly org.apache.kafka" % "kafka-clients" % "2.1.0"). 
Also last Kafka and SchemaRegistry - 5.1.0 version from confluent opensource. But when we send a message with string keys from C# via producer 
(nuget assembly Confluent.Kafka 1.0.0-RC4), 
that this message get a different topic' partition with compared Scala code (the topic have 20 partitions). Because Kafka Streams and RocksDb state store don't' see this data.

How to reproduce
================
You may create a message with key 1434cf9a-8a47-4d47-8616-86b2570e08bf and get this error.

**Comment by mhowlett** [comment]
set the `Partitioner` config property to `Murmur2Random`

**Comment by OhSirius** [comment]
Just amazing - thx bro! You made my day.
