### ISSUE TITLE
Debezium SQL connector wrong schema

### ISSUE THREAD

**Issue by patsadow2** [confluentinc/confluent-kafka-dotnet#894]
Hello,

I am working on SQL connector from debezium and Entity Framework

I have sql

```
CREATE TABLE elastickafka (
--NOT WORKING
-- [Id] int NOT NULL IDENTITY,
-- [Surname] nvarchar(max) NULL,
-- CONSTRAINT [PK_Elastickafka] PRIMARY KEY ([Id])

--WORKING
 --id INTEGER IDENTITY(1001,1) NOT NULL PRIMARY KEY,
-- surname VARCHAR(255) NOT NULL UNIQUE,
 );

INSERT INTO elastickafka(surname) VALUES ('Sally');
	
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo', @source_name = 'elastickafka', @role_name = NULL, @supports_net_changes = 0;
```

Does anyone know why it doesnt work correcty ?

**Comment by patsadow2** [comment]
Please :( is it because of surname null column ?

**Comment by mhowlett** [comment]
unfortunately the people maintaining this repo don't work with debezium. here's some more information on where you might get a response to your question: https://debezium.io/community/
