### ISSUE TITLE
Strange connections on client machine

### ISSUE THREAD

**Issue by MoJI4yH** [confluentinc/confluent-kafka-dotnet#896]
Description
===========
If we run consumer with 10 threads, we will see strange connection on our machines:
[connections after start for 10 task](https://drive.google.com/file/d/1rA5MwzHQXu4wqYOq0ubfQVYaLPWCzIRD/view?usp=sharing)
[connections after start for 1 task](https://drive.google.com/file/d/16NQ3rdM8feftYyNP5KyYQPKecqg8VgL1/view?usp=sharing)

so we have 10 connections for each broker machine in cluster, that`s ok
but also it create 90 bound connections and 100 established connections on localhost

after debuging, I realized that connections are created after calling the method [SafeKafkaHandle.Create](https://github.com/confluentinc/confluent-kafka-dotnet/blob/ca82c65ce855a8450260f1b0649481217aba8d55/src/Confluent.Kafka/Impl/SafeKafkaHandle.cs#L134)

How to reproduce
================

```
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Confluent.Kafka;

namespace TestKafkaConnectionsProblem
{
    class Program
    {
        static void Main(string[] args)
        {
            var cts = new CancellationTokenSource();
            var taskList = new List<Task>();

            for (var i = 0; i < 10; i++)
            {
                var token = cts.Token;
                var task = Task.Factory.StartNew(() =>
                {
                    var consuming = true;
                    var config = GetConsumerConfig();
                    using (var consumer = new ConsumerBuilder<string, string>(config)
                        .SetErrorHandler((_, e) => consuming = !e.IsFatal).Build())
                    {
                        consumer.Subscribe("prod.LinkedDocuments.BaseDocuments.Command.BaseDocument.SetTaxStatus");

                        while (consuming)
                        {
                            if (token.IsCancellationRequested)
                            {
                                break;
                            }

                            try
                            {
                                var message = consumer.Consume(token);
                                Console.WriteLine(message.Message);
                            }
                            catch (ConsumeException ex)
                            {
                                Console.WriteLine(ex.Message);
                                //ignore
                            }
                            catch (OperationCanceledException)
                            {
                                consuming = false;
                            }
                            catch (Exception ex)
                            {
                                Console.WriteLine(ex.Message);
                                consuming = false;
                            }
                        }
                        
                        consumer.Unsubscribe();
                        consumer.Close();
                    }
                }, TaskCreationOptions.LongRunning);
                taskList.Add(task);
            }

            Console.ReadLine();
            cts.Cancel();
            Task.WaitAll(taskList.ToArray());
            Console.WriteLine("Stop");
            Console.ReadLine();
        }
        
        private static ConsumerConfig GetConsumerConfig()
        {
            var config = new ConsumerConfig
            {
                BootstrapServers = "kafka01.org.moedelo.kafka:9092,kafka02.org.moedelo.kafka:9092,kafka03.org.moedelo.kafka:9092",
                ClientId = "ClientId",
                GroupId = "GroupId",
                EnableAutoCommit = false,
                ApiVersionRequest = true,
                SocketKeepaliveEnable = true,
                FetchWaitMaxMs = 5,
                FetchErrorBackoffMs = 5,
                QueuedMinMessages = 1000,
                AutoOffsetReset = AutoOffsetReset.Earliest,
            };

            return config;
        }
    }
}
```

Checklist
=========

Please provide the following information:
 - [ 1.0.0-RC6 ] Confluent.Kafka nuget version.
 - [ 2.1.1 ] Apache Kafka version.
 - [ Windows 10, windows server 2016 ] Operating system.

**Comment by mhowlett** [comment]
on Windows, librdkafka uses TCP connections to implement simultaneous polling of the socket and internal queues. For more info, see: https://github.com/edenhill/librdkafka/pull/1930

note: you generally shouldn't need to create more than one consumer per process.

**Comment by MoJI4yH** [comment]
[But here](https://drive.google.com/file/d/16NQ3rdM8feftYyNP5KyYQPKecqg8VgL1/view?usp=sharing) I create 1 consumer for broker and it will create about 4 connections to broker and about  **9 bound and 10 establish connections on localhost**

I understand why it nead connections for broker, but I don`t understand why it nead * 10 connection on localhost machine.

netstat show 
[connections to broker](https://drive.google.com/file/d/1anPR4VmhFBdRI5Ayj4ZgdVpoyOtl3uYK/view?usp=sharing) one for each for producer and one fore each for consumer (OK)

[connections on localhost](https://drive.google.com/file/d/1eKg2T6KBDri8iuq8V8aPEtUlNZzYNaQW/view?usp=sharing)
if this connections use for internal queues: "Where does 10 connections come from, if there is only 1 consumer?"

Because I have 10 partitions on topic, I thought I need to run also 10 consulers for this topic?

**Comment by MoJI4yH** [comment]
@mhowlett, Thanks for your answer.
I run 1 consumer per process, but I want to handle messages in parrallel for each partitions, so I can create as much workers as consumer partitions assigned. 

Then I start consume loop:
pseudocode
```
while(true) 
{
    var msg = consumer.Consume();
    var worker = findWorkerForMessagePartition();
    worker,handle(message);
   /* 
     so hire do I need to call Pause for worker Partition to maintain the processing order?
     and Resume them after worker handled message
    */
}
```

Don`t you have any examples of such situation?

**Comment by mhowlett** [comment]
unfortunately not, though this is a frequent requirement and I hope we can provide something out-of-the-box to accommodate it (it's on our radar).
