### ISSUE TITLE
How to create admin client from existing connection?

### ISSUE THREAD

**Issue by scovel** [confluentinc/confluent-kafka-dotnet#897]
Description
===========
1.0.0-RC6 made the constructor 
```
AdminClient(handle); 
```
private.  How do we create an admin client from an existing connection?  I need to validate topics a consumer has access to.  I was creating a short-lived admin client to check the topics, using the consumer's connection, then disposing of the client.  (Keeping the client around led to 100% CPU utilization)

How to reproduce
================

Migrate code from RC3 to RC6 that uses the AdminClient constructor that takes a Handle.

Checklist
=========

Please provide the following information:
 - [X ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ X] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version. 5.2.1 (container)
 - [ ] Client configuration.
 - [ X] Operating system.  MacOs, Linux
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
We made the client classes internal, only exposing the interfaces. You need to use `DependentAdminClientBuilder`.

**Comment by scovel** [comment]
well that was easy enough.  Thanks
