### ISSUE TITLE
Where should i find the schema  registry url in C#

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [confluentinc/confluent-kafka-dotnet#899]
Description
===========
This is not an issue but a question regarding the avro example in the example folder. I checked this [avro generic example](https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/AvroGeneric) and found that both consumer and producer are in the same program (which don't make sense for me, please correct me if i am wrong?). Therefore i divided the program in two project one for consumer and second one is producer. 
Now avro producer relies on schema registry but there is no example that how to run the schema registry in C#? which port or url it will use?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ 1.0] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by Rytisk** [comment]
Hi,
The default value for SchemaRegistryUrl is 'localhost:8081'. You can modify this property when starting the schema-registry service.

**Comment by mhowlett** [comment]
schema registry is part of confluent platform (not written in C#!).  https://docs.confluent.io/current/schema-registry/index.html - if you're on Windows, I suggest running this and kafka inside Virtual Box or similar. Or Confluent Cloud also now provides a fully managed schema registry.

**Comment by undecided2013** [comment]
Guys, we probably need to be able to operate this without a schema registry for backward compatibility of the client with messages written pre-registry. What do you recommend in that case?

**Comment by mhowlett** [comment]
@undecided2013 - don't quite understand your question - what is 'this'? the avro serdes? - there's no way to use these without schema registry.

**Comment by gopipofficial** [comment]
Do we have schema registry for the C#.net. I'm trying to register schema from my application byt I'm getting bellow error. can you pls help me on this ? (my application is C# .net)
No such configuration property: "schema.registry.url"

**Comment by mhowlett** [comment]
refer to the examples - there are many that use schema registry:

https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples

you also need to install schema registry (in case that wasn't clear): https://docs.confluent.io/current/schema-registry/installation/index.html

**Comment by gopipofficial** [comment]
thanks for the reference and quick response.

**Comment by gopipofficial** [comment]
I'm having another issue. Based on the samples given I could able to register the schema. but unfortunately I couldnt able to post data to the topic created. Can you guys please suggest some way to do so??

**Comment by mhowlett** [comment]
need more specific information in order to comment.

**Comment by gopipofficial** [comment]
I have fixed the above issue @mhowlett
