### ISSUE TITLE
How to use ConsumerBuilder class provided in examples using NuGet packages

### ISSUE THREAD

**Issue by RahulKateSV** [confluentinc/confluent-kafka-dotnet#908]
Hi  Confluent Kafka team,

We saw samples from this github repository for kafka consumer with ConsumerBuilder class as,

![image](https://user-images.githubusercontent.com/45872845/56714638-09732b80-6753-11e9-9c75-24d016ec0471.png)

![image](https://user-images.githubusercontent.com/45872845/56715115-602d3500-6754-11e9-9cdf-6c9a47b8dd05.png)

Can we use the same client ConsumerBuilder class through NuGet Package provided for Dot Net Core...?

**Comment by enzian** [comment]
Yes: You will have to install the [RC packages from NuGet](https://www.nuget.org/packages/Confluent.Kafka/1.0.0-RC7) though!

**Comment by RahulKateSV** [comment]
Thanks for answer ....
