### ISSUE TITLE
Invalid project-package combination for Confluent.Apache.Avro.AvroGen 1.7.7.5. DotnetToolReference project style can only contain references of the DotnetTool type

### ISSUE THREAD

**Issue by MadBiceps** [confluentinc/confluent-kafka-dotnet#911]
Description
===========
Every time I tried to install _Confluent.Apache.Avro.AvroGen 1.7.7.5_ from the NuGet Package Manager comes this error:
_Invalid project-package combination for Confluent.Apache.Avro.AvroGen 1.7.7.5. DotnetToolReference project style can only contain references of the DotnetTool type_

How to reproduce
================
I use .NetCore 2.1 with these packages:
- Confluent.Apache.Avro (Version 1.7.7.6)
- Confluent.Kafka (Version 1.0.0)
- Confluent.Kafka.Avro (Version 1.0.0-beta)
- Confluent.SchemaRegistry (Version 1.0.0)
-Confluent.SchemaRegistry.Serdes (Version 1.0.0)

Thats my csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Apache.Avro" Version="1.7.7.6" />
    <PackageReference Include="Confluent.Kafka" Version="1.0.0" />
    <PackageReference Include="Confluent.Kafka.Avro" Version="1.0.0-beta2" />
    <PackageReference Include="Confluent.SchemaRegistry" Version="1.0.0" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes" Version="1.0.0" />
  </ItemGroup>

</Project>
```

Thanks for your help.

**Comment by mhowlett** [comment]
that package is a dotnet tool (can't be installed into a project with the nuget package manager) - you need to install it as described here: https://github.com/confluentinc/confluent-kafka-dotnet#working-with-apache-avro
