### ISSUE TITLE
[Question] Usage of producers with different configurations

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#912]
Referencing this [question](https://github.com/confluentinc/confluent-kafka-dotnet/issues/159).

It was said, that the optimal way is to reuse the only created instance of producer. But is it possible to change producers configuration when needed(preferably in run-time)?

In my application I have a number of transfer objects each of them has different configurations for producer, for example one of the transfers has GZip compression and other one doesn't.

Is there a way to reuse one producer instance or it has to be created for each of unique configurations?

**Comment by mhowlett** [comment]
unfortunately this isn't possible yet with the .NET Client (or any of the bindings, or the Java client in fact) - you'll need to use more than one client. librdkafka does provide this capability though which is awesome, and we plan to expose it. it's becoming more and more useful for emerging use cases.

**Comment by Never7Dice** [comment]
Thank you for the answer. Would be great to have that possibility one day.

**Comment by mhowlett** [comment]
i'm personally very keen on it, so that'll definitely help the prioritization :-)
