### ISSUE TITLE
Using Assign() on consumer with Partition.Any doesn't consume anything

### ISSUE THREAD

**Issue by dmeenhuis** [confluentinc/confluent-kafka-dotnet#917]
Description
===========

I'm trying to create a consumer that will, when started, always read from the beginning of a topic that has multiple partitions. I could achieve this by always generating a new group ID and using `AutoOffsetReset.Earliest`, but somehow that doesn't feel like the right way.

In the consumer example is Assign() called with a specific partition value of 0 and offset beginning, but I don't think that's going to work for my use case, since I'm trying to read from all partitions. 

I've tried creating a consumer and using assign with:

```csharp
var consumerConfig = new ConsumerConfig
{
    GroupId = new Guid().ToString(),
    BootstrapServers = settings.BootstrapServers,
    AutoOffsetReset = AutoOffsetReset.Earliest
};

var consumer = new ConsumerBuilder<string, string>(consumerConfig).Build();

consumer.Assign(settings.Topics.Select(topic => new TopicPartitionOffset(topic, Partition.Any, Offset.Beginning)));
```
However, that doesn't seem to work, as in, it's not consuming anything from the topic. Explicitly specifying a partition (for example 0), does work.

Checklist
=========

- Using Confluent.Kafka 1.0.0 nuget version

**Comment by Never7Dice** [comment]
You should check out the answer in this [question](https://github.com/confluentinc/confluent-kafka-dotnet/issues/909). I guess the only thing that will be different is .High ->.Low

**Comment by mhowlett** [comment]
If you don't need to use the consumer group re-balance capability, then best not to use `Subscribe` - just assign directly as you're doing. Due to a quirk of librdkafka, you'll still need to specify a group id, though it's ignored. Instead of using `Partition.Any`, you need to specify a `TopicPartitionOffset` for every partition you want to consume from. You can use `GetMetadata` on the `AdminClient` to get information about number of partitions if you don't know this ahead of time.

**Comment by dmeenhuis** [comment]
Thanks, I think that's the missing piece then, I kind of assumed `Partition.Any` meant I don't care which one, just read from all partitions. If that's not the case, when would one use `Partition.Any` then?

I don't think I need the rebalance capability. This service is deployed in a Kubernetes cluster and will be scaled horizontally to a given number and I need each instance of the service to read the entire topic from all partitions.

Our topics do have a fixed number of partitions, so I suppose I could get it to work then by using your suggestion to specify a `TopicPartitionOffset` for each partition. I'll play around with this and see what works best, this or using the `AdminClient`.

Do you reckon it would be useful to extend this library to provide a convenience option for `Assign()` so that it does work the way I expected it to work, by reading all partitions? Or perhaps making it a bit clearer in the docs?

**Comment by dmeenhuis** [comment]
Using the `AdminClient` indeed works fine, so I'll close this one then. Thanks for the suggestion!
