### ISSUE TITLE
producer.Flush can hang using a simple example

### ISSUE THREAD

**Issue by LucVL** [confluentinc/confluent-kafka-dotnet#92]
While experimenting with the SimpleProducer/-Consumer examples, I found that I can systematically make the producer.Flush() call hang without doing anything obviously wrong.

In my GitHub repo asyncAwait branch [LucVL/rdkafka-dotnet](https://github.com/LucVL/rdkafka-dotnet/tree/asyncAwait) you can see the steps I took to isolate and reproduce the problem, and then workaround it in an unexpected way.

What I basically did was:
- Change the example to produce a single message and return.
- Put the `producer.ProduceAsync` call chained with a `ContinueWith` in a separate method returning the Task created by `ContinueWith` (`ProduceAndReportUsingContinueWithAsync`).
- await the returned task instead of relying on `producer.Flush()` to do the awaiting on tasks in progress.

So far everything continues to work as expected.

Then:
- Create a new method that does exactly the same thing, but using the async/await syntax (`ProduceAndReportUsingAwaitAsync`).
- Call that method instead of `ProduceAndReportUsingContinueWithAsync`
=> example hangs on the producer.Flush() call.

If the producer.Flush call is put in comments, the program hangs on leaving the using block instead.

The async/await syntax is much more readable and should in principle be equivalent to the `ContinueWith` style, except that the compiler can short-circuit the `ContinueWith` if the first task immediately returns in the `RanToCompletion` state.

I suspect that that is the case here since a simple workaround is putting `await Task.Yield()` after the `await producer.ProduceAsync(...)` call.

Putting the `ProduceAndReportUsingContinueWithAsync` code directly in the using block produces the same effect (and requires the same workaround).

**Comment by mhowlett** [comment]
Your SimpleProducer variant is blocking in the Producer Dispose method. I haven't had a chance to take a proper look, but I'm currently guessing the answer is likely to be found in the below blog post and that we're doing things incorrectly in the library - thanks for pointing this out. 

http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by mhowlett** [comment]
what's going on here i think is that after the await, the Dispose method is being executed on the Poll thread. The Dispose method sets the cancellation token and waits for the Poll loop to exit ... which it never can because it's blocked waiting. The (only) solution I think is for the IDeliveryHandler instance to create a Task that completes on a different thread and return that. This is actually a good thing to do anyway, as marshaling / deserialization can often be a non-trivial amount of work, and this effectively parallellizes it. shouldn't be too hard.

**Comment by ah-** [comment]
The Dispose inside Poll sounds plausibe.

If you're changing IDeliveryHandler it might be worth setting up some benchmarks, the only reason that IDeliveryHandler even exists was that creating many Tasks and scheduling them got very expensive and the produce throughput went down. Maybe the new ValueTask helps with that though.

**Comment by mhowlett** [comment]
Yep - there won't be any impact on the ProduceAsync methods that take an IDeliveryHandler, just the implementation of this internal to Producer that makes the Task based overloads work (btw. I changed how you were doing things a bit here - IDeliveryHandler no longer mimics TaskCompletionSource methods, and I can't remember if you were allowing data to be marshalled back or not - I don't think so - anyway there is a flag for that now. Also, we felt delivery report errors shouldn't be considered exceptions).

Another advantage of using the IDeliveryHandler ProduceAsync overloads is ordering of delivery reports as provided by librdkafka is maintained, as everything happens on the poll loop thread.

The perf. bottleneck is currently somewhere unrelated to Task allocations (currently eluding me). But all those allocations is certainly something that worries me about the Task returning overloads.

I'll hopefully write a blog post soon on the recommended way of using the producer in various scenarios. There is lots of flexibility ...

**Comment by structify** [comment]
@LucVL thank you for the work around. This was causing me some grief the last couple of days!

**Comment by javierholguera** [comment]
@mhowlett could you elaborate a bit more on what's happening here? You said on a previous comment:

> i think is that after the await, the Dispose method is being executed on the Poll thread

How would that happen exactly? Is this `Producer.Dispose` method? Also you mentioned

> The Dispose method sets the cancellation token and waits for the Poll loop to exit ... which it never can because it's blocked waiting

I understand you refer to this code:

```csharp
// Note: It's necessary to wait on callbackTask before disposing kafkaHandle.
// TODO: If called in a finalizer, can callbackTask be potentially null?
callbackCts.Cancel();
callbackTask.Wait();
```

I understand why this would block if the Poll thread can't satisfy the cancellation request. However, the thread seems to block only for 100 ms before finishing and retrying.

```csharp
private Task callbackTask;
private CancellationTokenSource callbackCts;

private const int POLL_TIMEOUT_MS = 100;
private Task StartPollTask(CancellationToken ct)
    => Task.Factory.StartNew(() =>
        {
            while (!ct.IsCancellationRequested)
            {
                this.kafkaHandle.Poll((IntPtr)POLL_TIMEOUT_MS);
            }
        }, ct, TaskCreationOptions.LongRunning, TaskScheduler.Default);
```

I would have thought that `Poll` would block and return after `POLL_TIMEOUT_MS` has passed.

Thanks for your help.

**Comment by mhowlett** [comment]
The task is getting completed inside the call to `kafkaHandle.Poll` (via a callback) - on the same thread. So after the await, we're actually inside the call to `kafkaHandle.Poll` (i believe).
