### ISSUE TITLE
[Question] How can I consume message again?

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#923]
I have a system where I don't commit until the consumed message successfully transferred to other service. But consumer locally stores info that I already consumed the message and tries to consume next one.

How can I clear this info and start from the last committed state? Is there some better way than closing current consumer and creating new with same config?

 - [ 1.0.0 ] Confluent.Kafka nuget version.
 - [ Windows 10  .NET Framework 4.7.2 ] Operating system.

**Comment by mhowlett** [comment]
you can use `Consumer.Seek`

**Comment by Never7Dice** [comment]
Can you provide code sample for how I can use `Consumer.Seek` in already built consumer?

```
            var config = new ConsumerConfig { 
                ClientId = _clientId,
                GroupId = _groupId,
                BootstrapServers = $"{_address}:{_port}",
                AutoOffsetReset = AutoOffsetReset.Earliest,
                EnableAutoCommit = !_waitForTransfer, };

            var _confluentConsumer = new ConsumerBuilder<Ignore, string>(conf).Build();

            _confluentConsumer.Subscribe(_topic);

            var _cancelationToken = new CancellationTokenSource();

            var cr = _confluentConsumer.Consume(_cancelationToken.Token);
                if (!cr.IsPartitionEOF)
                {
                    foreach (var callback in _callbacks)
                    {
                        callback(new CallbackParams(cr));
                    }
                }               
            }
```
For example after callback() I may need to re-consume again.

**Comment by Never7Dice** [comment]
Also. For some reason when I recreate new consumer the same way I created previous one, assignment is empty. That's definitely not expected behavior, what can be the reason of it?

![image](https://user-images.githubusercontent.com/34353798/57532651-b6010000-7344-11e9-8584-124cb325fa10.png)

**Comment by Never7Dice** [comment]
> you can use `Consumer.Seek`

@mhowlett can you, please, tell if this code sample is the correct way to go? How can I do it for more than 1 assignment? (I don't know if it can ever happen)
```
var currentTopicPartition = consumer.Assignment.First();
consumer.Seek(new TopicPartitionOffset(currentTopicPartition, consumer.Position(currentTopicPartition) - 1));
```
