### ISSUE TITLE
AdminClient - An error occurred when using ResourceType

### ISSUE THREAD

**Issue by oandreeeee** [confluentinc/confluent-kafka-dotnet#926]
Description
===========
I'm exploring the `AdminClient` and when trying to use the `DescribeConfigsAsync` I'm getting the following error when using the `ResourceType` of the type: `Group`,`Any`,`Unknown`.
No matters if I use a invalid (not exists) or valid value.

The `Exception` is:
```
DescribeConfigsException: An error occurred describing the following resources: [[Unknown] abc123]: [Unexpected resource type UNKNOWN for resource abc123].
```

How to reproduce
================

With:
- Confluent.Kafka nuget version. 1.0.0
- Apache Kafka version. 2.12-2.0.1

```
public async Task UsingDescribeConfigsOptions()
{
    var input = new List<ConfigResource>
    {
        //new ConfigResource { Type = ResourceType.Group, Name= "topic" }
        //new ConfigResource { Type = ResourceType.Any, Name = "123" }
        new ConfigResource { Type = ResourceType.Unknown, Name = "abc123" }
    };

    var options = new DescribeConfigsOptions { RequestTimeout = TimeSpan.FromSeconds(10) };

    var r = await _adminClient.DescribeConfigsAsync(input, options);
}
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.0.0
 - [x] Apache Kafka version. 2.12-2.0.1
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

Keep the good work!

**Comment by edenhill** [comment]
I believe DescribeConfigs might be limited (in the broker) to ResourceType .Topic and .Broker at this point time.

**Comment by mhowlett** [comment]
yep, not in the java client either: https://kafka.apache.org/21/javadoc/index.html?org/apache/kafka/clients/admin/AdminClient.html

**Comment by oandreeeee** [comment]
Thanks a lot for the explanation.
