### ISSUE TITLE
No OnMessage in the new version? （1.0.0）

### ISSUE THREAD

**Issue by amwitx** [confluentinc/confluent-kafka-dotnet#928]
Description
===========

![image](https://user-images.githubusercontent.com/17676182/57517097-a97ea680-7348-11e9-8ad9-10e05759ac6f.png)

**Comment by mhowlett** [comment]
yes, it's gone - the API has changed a lot 0.11.6 -> 1.0.

**Comment by amwitx** [comment]
While (true) won't there be any performance problems?
