### ISSUE TITLE
[Question] Closing/Disposing consumer without committing.

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#929]
What is the best way to destroy consumer without committing anything after .Commit() and without leaving connection to timeout?

 - [ 1.0.0 ] Confluent.Kafka nuget version.

**Comment by mhowlett** [comment]
`Consumer.Close` - offsets will only be committed on `Close` if you have auto commit enabled (which it is by default).

**Comment by Never7Dice** [comment]
That's it, thank you.
