### ISSUE TITLE
Graceful shutdown for a Consumer

### ISSUE THREAD

**Issue by javierholguera** [confluentinc/confluent-kafka-dotnet#93]
I'm implementing some integrated tests with the library against dockerised Kafka instance. The setup in Kafka is 1 broker, 1 topic and 1 partition, using SSL between and with the clients. 

The tests will check that various commit strategies (before processing, after processing, no commit) work as expected. My problem is the tests work but take ages to execute. I've measured where the time is going and, roughly:
- 7 seconds to spin up a producer, produce 2 events and close it.
- 11 seconds to spin up the first consumer, consume 1 event and close it.
- 40 seconds to spin up the second consumer, consume 1 event (or 2, depending on the strategy chosen) and close it.

I can understand that the first two phases take some time. However, there is something weird with the third phase, clearly there must be some sort of timeout waiting to happen, after which the consumer does its job. The way I'm closing the Consumer is calling Dispose in the following snippet:

```c#
private Consumer<TKey, TValue> innerConsumer;

public async Task Stop()
{
    // Stop receiving events
    this.innerConsumer.Unsubscribe();

    // Make sure that, the moment Poll returns, start will complete
    this.isStarted = false;

    // https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Consumer.cs#L443
    // innerConsumer.Close will be added back soon. In the meantime, we can "wait" until the Poll processes the latest message
    // or comes back from the 100ms wait and closes naturally.

    await Task.Delay(TimeSpan.FromMilliseconds(1000));
} 

public void Dispose()
{
    Dispose(true);
}

private void Dispose(bool disposing)
{
    if (disposing)
    {
        if (!this.isDisposed)
        {
            this.Stop().Wait();

            this.innerConsumer.Dispose();
            this.isDisposed = true;
        }
        
        this.innerConsumer = null;
    }
}
```

The two Consumers share the same GroupId (the share all their configuration).

Any idea what I may be doing wrong so the first consumer is not shutting down gracefully enough?

**Comment by edenhill** [comment]
If the consumers share the same group id and are not started simultaneously then there will be a rebalance which takes up to session.timeout.ms (def 30s). I suggest decreasing session.timeout.ms to 6000. That should speed up the consumer.

For the producer it sounds strange that it runs longer than a second (queue.buffering.max.ms defaults to 1000ms). Can you try to time which part takes what time. e.g.: from startup until Producer is created, until messages are produced, until the Producer is flushed, until the Producer is disposed?

**Comment by javierholguera** [comment]
@edenhill thanks for your suggestion. I've implemented it and the test when from more than 50s to around 25s.

I'm measured the producer:
- 1s to create
- 4s to produce the first event
- 1s to produce the second event
- less than 1s to dispose

First consumer is still taking around 12s to do its consumption of 2 events. The second consumer is taking around 10s now.
