### ISSUE TITLE
Is there any way to share consumer connections?

### ISSUE THREAD

**Issue by dfturn** [confluentinc/confluent-kafka-dotnet#932]
The producer and admin client have the idea of sharing connections. `DependentProducerBuilder` for instance, so we can reuse the connection to Kafka when producing to multiple topics. Is there a technical reason this doesn't exist for consumers, or is it simply because it hasn't been added?

**Comment by mhowlett** [comment]
There's no technical reason at the kafka API level, but the client (including librdkafka) consumers are designed for high bandwidth streaming use cases and don't allow you to assign to (or subscribe to) more than one set of topics. as other use cases emerge I think this will change, but it's not the case at the moment.

**Comment by edenhill** [comment]
The consumer protocol has a couple of blocking protocol requests which make it troublesome to reuse a single connection for multiple consumers.

**Comment by mhowlett** [comment]
right, stupid me, fetch for instance. something else we've put some thought into is what an API for splitting messages from a single consumer based on headers or topic might look like. today, you could build something like that on top of a `Consumer<byte[],byte[]>`.

**Comment by dfturn** [comment]
Thanks, that makes sense!
