### ISSUE TITLE
Consumer messages are distributed with different group id

### ISSUE THREAD

**Issue by Veebh** [confluentinc/confluent-kafka-dotnet#938]
Description
===========
I have one Producer, 2 Consumers.(written in .net core).
Configured brokers 3, partitions 3.

My producer messages are distributed among the two Consumers. How can i get all the messages on each consumer.
I am creating different group id for both the consumers.

Confluent.Kafka version 1.0.0
Any help.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
the way you describe it, all messages should be delivered to both consumers.

**Comment by Veebh** [comment]
Additional information:
I am using Sasl_Plaintext(kerberos) authentication and SaslMechanism = SaslMechanism.Gssapi as mechanism.
I am providing the brokers as broker1:port;broker2:port,broker3:port.

Is there a possibility that cluster settings can impact the message delivery distribution among the clients.

**Comment by Veebh** [comment]
Hi,

We found the fix, as specified in the sample provided by kafka Providing Guid failed to wrok.
We passed normal string like "testing", worked fine.
Hence closing the issue.
