### ISSUE TITLE
producer failover behavior when node in cluster failed

### ISSUE THREAD

**Issue by xyang7421** [confluentinc/confluent-kafka-dotnet#940]
Description
===========

Hi, I am trying to understand how the fail over would work when node in cluster failed. Say I have 3 nodes in cluster, and the producer have 3 of them configured:
BootstrapServers = "kakfa1:9092,kafka2:9092,kafka3:9092",

create a topic that have 3 replicas, single partition.  with all 3 nodes up and running. producer working fine. Then shutdown kafka3.  Should the producer automatically use the working one? or we have to rebuild the producer with kafka1 and kafk2?

my observations was it always hit the last one in the list first. so if I shutdown kafka3, above config will always fail the produce. But if I reverse the order to kakfa3:9092,kafka2:9092,kafka1:9092
it will always work.

What is the correct way to handle node failure with the library?

Thanks,
Xu

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
the producer is designed to automatically handle/recover from all errors where possible. Note that you don't need to specify all the brokers in the bootstrap.servers list - the client will discover those you don't specify and order shouldn't matter.

when you say 'fail to produce', what is the error?

**Comment by xyang7421** [comment]
I got an aggregated exception, the inner one is a timeout.
I changed the timeout to 10 sec, or default. makes no difference. 
The reason I put all 3 in config was that I was hoping to give the library more connection points. If I just give one, e.g. kafka1, and that one happened to be down, there will be no chance for the producer to reach other two working ones.

**Comment by xyang7421** [comment]
when I use another java producer client, the order doesn't matter, it produced fine. so I don't think this was due to the cluster setup. Actually, there seems to be a background thread printed some error like:
%3|1557971151.275|FAIL|kafkactipsclient#producer-1| [thrd:kafka3:9092/bootstrap]: kafka3:9092/bootstrap: Connect to ipv4#10.200.49.221:9092 failed: No connection could be made because the target machine actively refused it... (after 2009ms in state CONNECT)
%3|1557971151.275|ERROR|kafkactipsclient#producer-1| [thrd:kafka3:9092/bootstrap]: kafka3:9092/bootstrap: Connect to ipv4#10.200.49.221:9092 failed: No connection could be made because the target machine actively refused it... (after 2009ms in state CONNECT)
kafka3 was down.
I have updated the library to the latest 1.0.0

**Comment by mhowlett** [comment]
i don't know without more information - you can get verbose client logs by setting the `Debug` config property to `all`. That error message is consistent with the broker being down (note that you can redirect it by setting a log handler if you don't want messages output to stderr).

**Comment by xyang7421** [comment]
sure, it was a test program so I can get more debugging info. 
thanks.

**Comment by xyang7421** [comment]
ha, looks like the kafka2 is indeed having trouble. as kafka1 shows 2 brokers, while kafka2 shows  0 in the metadata returned. when kafkas3 in the last position, the connect went to kafka2 first, so failed. 
I think this is still a setup problem. Thanks for pointing me to the right verbose flag.

**Comment by xyang7421** [comment]
Found my problem: the kafka1 has a newer version than kafka2 and kafka3.

**Comment by xyang7421** [comment]
Matt, just let you know after upgrade the 2 and 3 to the latest, the failover is working properly.
Thanks,
Xu
