### ISSUE TITLE
[Question] Why is there no ssl.truststore option in config?

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#941]
My Landoop Apache Kafka broker provides me keystore and truststore:
![image](https://user-images.githubusercontent.com/34353798/57873500-172e4500-7817-11e9-87de-c237ba370edb.png)

But I cannot find the way to plug it in ConsumerConfig in any way for it to work.
It doesn't even read .jks keystores.

 - [ 1.0.0 ] Confluent.Kafka nuget version.

**Comment by mkellogg** [comment]
You need to use the Java keytool utility to extract out the x509 certs (or convert the jks to a pkcs12 (pfx)) then you can pass them in the appropriate ConsumerConfig fields:

SecurityProtocol = SecurityProtocol.Ssl
SslCaLocation (truststore)
SslCertificateLocation (public key file from the client jks)
SslKeyLocation (private key file from the client jks)

**Comment by Never7Dice** [comment]
Thank you for the advice. I have a problem with CaLocation, but it gives me no useful info:
![image](https://user-images.githubusercontent.com/34353798/57876757-ce7a8a00-781e-11e9-89b6-983399abdd25.png)
Have I made mistake somewhere?
- downloaded truststore.jks and client.jks
- converted truststore.jks to trust.p12
- extracted private_key.pem from client.jks
- extracted cert.pem from client.jks

**Comment by Never7Dice** [comment]
Seems like I need to extract .pem from truststore.jks
`keytool -importkeystore -srckeystore truststore.jks -destkeystore truststore.p12 -deststoretype PKCS12`

`openssl pkcs12 -in truststore.p12 -nokeys -out truststore.cer.pem`

Now it looks like it successfully communicates with broker.

**Comment by MirzaAli-Baig** [comment]
How did you extract 
 private_key.pem from client.jks
extracted cert.pem from client.jks

**Comment by Never7Dice** [comment]
@MirzaAli-Baig hope it is not too late :D

Here's the lines I used:
> keytool -importkeystore -srckeystore client.jks -destkeystore client.p12 -deststoretype PKCS12
> openssl pkcs12 -in client.p12 -nokeys -out client.crt
> openssl pkcs12 -in client.p12 -nocerts -nodes -out client.key
