### ISSUE TITLE
Question: Does compression take place in parallel on multiple background threads?

### ISSUE THREAD

**Issue by bartelink** [confluentinc/confluent-kafka-dotnet#946]
The tile is the TL;DR...

I'm using `ProduceAsync` from many triggering Tasks to render large blocks of output concurrently.

Can someone confirm stuff I'm inferring from reading the code please?
- the .NET layer doesn't do the compression
- the call should never block, i.e., any back pressure would not be communicated by blocking, but instead via throwing or yielding an Error `DeliveryReport`

And finally, my question:
- if I submit 10 large items in parallel on a 4 processor machine, how many threads should I expect to show CPU consumption wrt that compression work? i.e. is compression and feeding out single threaded in the rdkafka layer for a given Producer?
- Assuming it is, would making multiple instances of the Producer and then round-robining across those be sufficient to trigger using >1 Processor ? or will there ultimately be something that will prevent that from having any benefit ?

**Comment by mhowlett** [comment]
- correct, the .net layer doesn't do compression.
- `ProduceAsync` never blocks. In the case of a local queue full exception, you can call `Producer.Poll` to block until it's no longer full.
- how large is large? IIRC Kafka has a performance wall @ around 30Mb (lower without tuning the config).
- librdkafka maintains one thread per broker. note that it is messages batches that are compressed (as opposed to individual messages). compression will happen serially for all messages destined for a particular broker, but in parallel across brokers.
- yes, more producers will allow compression to be done in parallel for messages destined for a particular broker, but you loose the benefits of batching (including better compression ratios, higher max throughput) and I find it surprising this is a bottleneck.

**Comment by bartelink** [comment]
Thanks for the detailed responses!

>how large is large? IIRC Kafka has a performance wall @ around 30Mb (lower without tuning the config)

No was more trying to get across that it was a situation where I'm trying to get a decent number of items that in aggregate are non-trivial in size out concurrently - individual messages will rarely go over the 1MB mark with the present workload (and are physically limited to 4MB by the nature of the origin)

>librdkafka maintains one thread per broker. note that it is messages batches that are compressed (as opposed to individual messages). compression will happen serially for all messages destined for a particular broker, but in parallel across brokers.

Thanks (assuming one thread per broker _per producer_ [based on next comment]); had been aware of this basic nature at some level but had not been giving it appropriate consideration (I had a vague idea of using them in a round-robin fashion, which may well be suboptimal for the exact reason you mention)

>yes, more producers will allow compression to be done in parallel for messages destined for a particular broker, but you lose the benefits of batching (including better compression ratios, higher max throughput) and I find it surprising this is a bottleneck.

I've yet to prove it is - thanks for calling it out explicitly

----

Bearing the above in mind, I'm wondering what downsides there are to doing setting `queue.buffering.max.messages` high to the point of irrelevance and then upping the `queue.buffering.max.kbytes` value as a way to enable work to be queued - is the main purpose to afford control of memory consumption, or is there also an question of algorithmic efficiency wrt buffer management in play ?

**Comment by mhowlett** [comment]
i'm not aware of any downside to doing that except memory consumption and latency.

**Comment by bartelink** [comment]
Thanks for all the help; closing.
