### ISSUE TITLE
[Question] Is there any way to request validation of client SSL certificate?

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#948]
Is there a possibility to make sure that current client certificate is acceptable by broker, meaning that the broker is up and running and returns approval or disapproval of client SSL certificates with a reason for it. For both 1-way SSL and 2-way SSL.

The only duct tape solution I found is using admin client with SSL config and handle errors.
![image](https://user-images.githubusercontent.com/34353798/58028652-e0f90a00-7b23-11e9-9c44-271125867de2.png)

 But the reason of errors is too vague, like client authentication might be required when you actually provide client certificate, but not the one that broker will accept.
![image](https://user-images.githubusercontent.com/34353798/58028669-ec4c3580-7b23-11e9-9c0d-de4a64d6d0d5.png)

And the only indicators are Local_Ssl and long message string.

Is there any better solution? Is it even reliable way to test for certificate disapproval?

 - [ 1.0.0 ] Confluent.Kafka nuget version.

**Comment by edenhill** [comment]
No, there is no other buitin solution than to instantiate a client, as you're already doing.

**Comment by Never7Dice** [comment]
Ok, thanks, I hope it would be sufficient.
