### ISSUE TITLE
[Question] Is it possible to receive broker SSL certificate and apply custom validation?

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#951]
Is it possible to somehow receive certificate as string or X509 object or something, and then send it to the library to test if it is acceptable? I cannot use truststore because my system injects externally configurable service that validates certificate based on several trusted sources.

So the desired process will look like this:
- consumer sends request;
- broker sends it's own certificate;
- client receives it and passes to service;
- if service acknowledges certificate client trusts broker and proceeds. 

Is that even remotely possible?

 - [ 1.0.0 ] Confluent.Kafka nuget version.

**Comment by edenhill** [comment]
We're adding support for in-memory SSL private & public keys and CA certs, it will be available in a future release.
And there's also support for a new broker certificate verification callback that allows an application to extend the default cert-verification with custom business logic.
Relevant docs: https://github.com/edenhill/librdkafka/pull/2309/files#diff-c59135f44ebf712a4c9fea7fae4538e6R1899

**Comment by Never7Dice** [comment]
Thank you for detailed answer. Sad that it's not currently possible.
