### ISSUE TITLE
Producer is slow. What's the proper way to publish messages?

### ISSUE THREAD

**Issue by alexandery** [confluentinc/confluent-kafka-dotnet#953]
Description
===========
I'm trying to publish messages to multiple topics. I'm trying with 40 test topics and I publish 5-10-15 messages to each topic. I'm publishing messages async with no await and then use .Flush() to ensure the messages get sent before i return from the method.

What I'm seeing is slow producing of messages.
- 200 messages (5 per topic) get accepted by Publisher within .05-.2 seconds, but then it takes on average 9-10 seconds before .Flush() completes, making it 20 messages a second.
- 400 messages (10 per topic) take about 17-20 seconds (so it seems to be somewhat linear).
- 800 messages (20 per topic) take about 35 seconds

Environment:
=========
- AWS managed Kafka offering
- AWS hosted VM that acts as a client for my tests

Questions
================
- Is this the max throughput I'll get if I want to ensure the messages are published?
- Are there ways to improve the performance?
- What is the proper way to deal with some messages out of a batch failing to be published? 

Checklist
=========

Please provide the following information:
 - [1.0.0] Confluent.Kafka nuget version.
 - [1.1.1] Apache Kafka version.
 - [Windows] Operating system.

Code
====
```
int currentMessageIndex = 1;
foreach (var topic in topics)
{
	for (int i = 0; i < messagesToPublish; i++)
	{
		PublishSingleToTopic(producer, topic, currentMessageIndex++);
	}
}
while (producer.Flush(TimeSpan.FromSeconds(1)) != 0)
{
	Thread.Sleep(50);
}
```

```
private Task PublishSingleToTopic(IProducer<string, string> producer, string topicName, int offset)
{
	SampleMessage message = new SampleMessage { TopicName = topicName, Offset = offset };
	var kafkaMessage = new Message<string, string>
	{
		Key = Guid.NewGuid().ToString(),
		Value = JsonConvert.SerializeObject(message)
	};
	return producer.ProduceAsync(topicName, kafkaMessage);
}
```

**Comment by mhowlett** [comment]
9-10s is a very long time for Flush to block in in this scenario, implies something is up with the cluster. Have you considered confluent cloud?

**Comment by mhowlett** [comment]
you could get a better idea what might be the cause of the issue by setting the `Debug` config property to `all` and looking at the logs.

**Comment by alexandery** [comment]
What should I be looking for there? There is literally a wall of debug printouts on console that will be hard to process unless I know what to look for. Any pointers are appreciated.

**Comment by mhowlett** [comment]
the flush call should complete very quickly for this many requests (within milliseconds). I think this most likely points to an issue with the cluster. I could analyze the logs for you to try and infer what's wrong (i'd start with the metadata requests), but since I believe this is an amazon issue and the broker logs will probably provide a more direct way to track this down, I think using their support channels is the probably the most appropriate avenue here.

**Comment by alexandery** [comment]
Fair enough. However for me to go to Amazon I need to provide them with specifics that point to their cluster as being the problem.

I can share the debug output with you (there is a lot of it) or, if you can tell me what to look for, then I can try to do the grunt work before asking you for clarifications on my findings.
