### ISSUE TITLE
Consumer spins CPU with 400 topics

### ISSUE THREAD

**Issue by alexandery** [confluentinc/confluent-kafka-dotnet#954]
Description
===========
Subscribing to 400 topics spins the CPU on my AWS VM (Xeon 2.3Ghz 1 virtual CPU) to 100% in idle mode. No messages are sent/received. The code is pretty much what you've got as examples here.

How to reproduce
================
Subscribe to 400 or more topics. I haven't explored yet at what minimum number of topics the CPU starts spinning.

Questions
=======
- What am I doing wrong?
- Is library able to support that many topics in a single consumer? 
  - I need to be able to serve 400-1000 topics in a single process with many processes per VM

Checklist
=========

Please provide the following information:
 - [1.0.0] Confluent.Kafka nuget version.
 - [1.1.1] Apache Kafka version.
 - [Windows] Operating system.

Code
====
```
private void ReceiveMessages(string servers, string consumerGroupName)
{
	var config = new ConsumerConfig
	{
		BootstrapServers = servers,
		GroupId = consumerGroupName,
		EnableAutoCommit = true,
		StatisticsIntervalMs = 5000,
		SessionTimeoutMs = 6000,
		AutoOffsetReset = AutoOffsetReset.Earliest,
		EnablePartitionEof = true
	};

	CancellationTokenSource cts = new CancellationTokenSource();
	Console.CancelKeyPress += (_, e) => {
		e.Cancel = true; // prevent the process from terminating.
		cts.Cancel();
	};

	using (var consumer = new ConsumerBuilder<Ignore, string>(config)
		// Note: All handlers are called on the main .Consume thread.
		.SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
		.Build())
	{
		consumer.Subscribe(topics);
		Console.WriteLine($"###### {DateTime.Now} - Subscribed to {topics.Count} topics");

		try
		{
			int counter = 0;
			while (!cts.IsCancellationRequested)
			{
				try
				{
					var result = consumer.Consume(cts.Token);
					if (!result.IsPartitionEOF)
					{
						var payload = JsonConvert.DeserializeObject<SampleMessage>(result.Value);
						Console.WriteLine($"{DateTime.Now} - {payload.TopicName} - {payload.Offset} - {payload.CreatedAt}");
					}
					else
					{
						Console.WriteLine($"{DateTime.Now} - EOF - {Thread.CurrentThread.ManagedThreadId} - {counter++}");
					}
				}
				catch (ConsumeException e)
				{
					Console.WriteLine($"***** {DateTime.Now} - ConsumeException: {e.Message}");
				}
			}
		}
		catch (OperationCanceledException e)
		{
			consumer.Close();
			Console.WriteLine($"***** {DateTime.Now} - OperationCanceledException: {e.Message}");
		}
	}
}
```

**Comment by mhowlett** [comment]
It's unusual to use Kafka in this way (subscribe to so many topics) - what is the use case? That said, the limiting factor is typically number of partitions (independent of number of topics) and subscribing to that many partitions should be fine. Do you see a similar issue subscribing to a single topic with 400-1000 partitions?

**Comment by alexandery** [comment]
Sorry, I should have mentioned that all of my test topics are created with 16 partitions, so for 400 topics we are talking about 6400 partitions.

Some of my use cases will require supporting very high message throughput (both publishing and consuming), so I'm looking at high number of partitions for those topics (16 is just a rough number I picked at this time, I may need to scale that up to 24/32/64 to enable consumers to keep up with messages).

I've estimated that my processes will need to subscribe to 400-600 topics, with partitions ranging from 4 to 16 on average. So, partially, my current tests are to estimate whether this is possible to do per process.

My ultimate goal for this particular set of tests is to push the limits of Kafka cluster I've got currently to understand what it can support and then extrapolate that to understand what my cluster needs to be to support 150-200K partitions and a high message throughput.

I will run further tests with less topics but higher number of partitions, but from the sounds of it I will be running into the same situation, if partition count is the important piece here.

**Comment by mhowlett** [comment]
that's a lot of partitions - note that you can fully utilize a single consumer instance by reading from just 1 or 2 partitions. also note that maximum number of partitions you can reasonable have in a Kafka cluster is ~100K (only relatively recently increased from 10K), so your anticipated scale is exceeding that.

**Comment by edenhill** [comment]
Since the underlying librdkafka library uses one thread per broker, we highly recommend instances with at least 4 vcores.

**Comment by alexandery** [comment]
> that's a lot of partitions - note that you can fully utilize a single consumer instance by reading from just 1 or 2 partitions. also note that maximum number of partitions you can reasonable have in a Kafka cluster is ~100K (only relatively recently increased from 10K), so your anticipated scale is exceeding that.

There are articles online that talk about >200K partitions as being fully supported and being performant. Here is one from Confluent: https://www.confluent.io/blog/apache-kafka-supports-200k-partitions-per-cluster . Is this not correct and I cannot expect it to scale to this level?

**Comment by mhowlett** [comment]
i'm not experienced at operating a single cluster at that scale, but at around this level (low 100's k's), the number of partitions will start to have meaningful impact as per that article (it's not a hard cutoff). what is your expected total throughput in the cluster? you might want to consider having multiple clusters. netflix have a good kafka summit talk on running kafka at massive scale, iirc the most brokers they have in a single cluster is ~100.

**Comment by alexandery** [comment]
> Since the underlying librdkafka library uses one thread per broker, we highly recommend instances with at least 4 vcores.

One thread per broker? So, if I have 10 brokers (let's say, to support >100K-150K partitions), I'm going to be potentially starving libdkafka for processes that consume from multiple topics and high partition count per each resulting in lots of context switches. 

In my case I want multiple processes (think Kubernetes, docker containers packed on each box and all of these being one large SOA system with a lot of messaging) running on each box. Am I CPU bound then and need high core count per box to mitigate potential effects on how librdkafka talks to brokers?

**Comment by alexandery** [comment]
> i'm not experienced at operating a single cluster at that scale, but at around this level (low 100's k's), the number of partitions will start to have meaningful impact as per that article (it's not a hard cutoff). what is your expected total throughput in the cluster? you might want to consider having multiple clusters. netflix have a good kafka summit talk on running kafka at massive scale, iirc the most brokers they have in a single cluster is ~100.

At this moment I'm still in the process of estimating message throughput (I presume you were asking for message throughput). I think we'll be in 10-40M messages **sent** per day (sorry, very large bracket - don't have all details yet) on average with influx of extra 20-40M/daily occasionally. Consumption will be x5-10 times (just wild number, may be higher). As for the message size (and volume throughput) - good chunk of those 10-40M will be in 1-10KB range, but we may have 100K-1M messages as well, from the looks of it, until proper re-architecture happens.

I have already started considering multiple Kafka clusters, but it doesn't change my goal of estimating what size of cluster do I need to successfully support ~200-250K partitions. I need to estimate cost as one of my goals. Having 100 brokers (Netflix example you've mentioned) will push the cost up very high, that's for sure.

I hope Netflix Kafka talk is online? I'll look for it, thank you for pointing it out.

**Comment by alexandery** [comment]
> that's a lot of partitions - note that you can fully utilize a single consumer instance by reading from just 1 or 2 partitions. also note that maximum number of partitions you can reasonable have in a Kafka cluster is ~100K (only relatively recently increased from 10K), so your anticipated scale is exceeding that.

In this example **no** messages are **sent** - the system is **idle** and the CPU starts spinning. I believe the Consumer doesn't event connect to all topics for a while (i keep getting printouts with EOF message while it's conecting).

So is it fair to say that a single consumer has a hard limit on number of partitions it can subscribe to, even when idle? I'll start playing around with numbers to see when the CPU starts misbehaving.

**Comment by mhowlett** [comment]
assume 100M messages / day @ 10kb per message. that's 1000 Gb / day = 1000 Gb / 86400s  ~= 0.01 Gb / s = 10 Mb/s * 10 (number of consumers) = 100Mb/s. When benchmarking the python client I was pushing 100Mb/s with a 3 broker cluster and a single client (both producer and consumer). Based on my recollection of the specs for large clusters for customers (and depending on your specific requirements around latency and replication), I'd estimate you'd need maybe 5 or 6 brokers.

i'm not sure what the client limit on # partitions is (need to look into it), but subscribing to 6400 partitions is a certainly quite a way above normal / recommended use.

**Comment by alexandery** [comment]
> assume 100M messages / day @ 10kb per message. that's 1000 Gb / day = 1000 Gb / 86400s ~= 0.01 Gb / s = 10 Mb/s * 10 (number of consumers) = 100Mb/s. When benchmarking the python client I was pushing 100Mb/s with a 3 broker cluster and a single client (both producer and consumer). Based on my recollection of the specs for large clusters for customers (and depending on your specific requirements around latency and replication), I'd estimate you'd need maybe 5 or 6 brokers.

Thank you for the details on calculations and your opinion, Matt. Appreciate it.

> i'm not sure what the client limit on # partitions is (need to look into it), but subscribing to 6400 partitions is certainly quite a way above normal / recommended use.

OK, understood. I'm going to see what's the magic number before CPU consumption gets out of hand.

**Comment by anchitj** [comment]
Closing as all the questions were answered. Feel free to reopen if you still need any help.
