### ISSUE TITLE
Question: Is calling IConsumer.Consume with 0ms timeout safe?

### ISSUE THREAD

**Issue by dfturn** [confluentinc/confluent-kafka-dotnet#959]
Root problem: I want a non-blocking Consume, even if it means I slightly increase latency. Use case is something like fronting `IConsumer.Consume()` with an HTTP endpoint, where I will have many requests per second, and I want to avoid starving my thread pool.

Based on local testing it seems like this works: I can set a 0 time timeout and still receive messages. But I want to make sure this is a valid use case and that I won't be broken by using this API in an unintended way. My hope is that the timeout is only for broker communication, and that if I'm thrashing the CPU, I won't hit this timeout even with items in the local consumer queue.

**Comment by mhowlett** [comment]
all broker communication happens on background threads - the `Consume` method simply polls an internal queue. Yes, i's valid to use a 0 timeout. You don't want to do this in a tight loop though of course.

**Comment by dfturn** [comment]
Absolutely, our normal consumers would use single-threaded polling with something like a 1s timeout. This is a rather specific use case, but I'm glad to hear that we can use it this way. Thanks for the rapid response!
