### ISSUE TITLE
support target framework 4.5

### ISSUE THREAD

**Issue by fangliuwh** [confluentinc/confluent-kafka-dotnet#96]
We are still at .net framework 4.5. Can you please add support of framework 4.5 besides 4.5.1 and .NETStandard 1.3? Thanks.

**Comment by mhowlett** [comment]
.NET Framework 4.5 (and 4.5.1) are no longer supported by Microsoft so I'm not going to prioritize looking into this unless lots of other people ask for it. We'll look at PRs or any investigation people might do into the viability of this though :-). The decision is inherited from rdkafka-dotnet and I don't know what @ah-'s reasons were. By default I assume there were reasons (but it may be somewhat arbitrary).

**Comment by ah-** [comment]
I don't quite remember, I think it was due to some bug and/or .net standard incompatibility in 4.5.0.

**Comment by combrinckd** [comment]
The project I am working on are also still on .NET 4.5 and updating this is not an option for at least a couple of months (maybe next year). Currently I am using kafka-net (https://www.nuget.org/packages/kafka-net/ ) producer. It would have been great to also validate this to find the best performance and stability on throughput. I need to be able to push at least 3000 to 4000 messages per second.

**Comment by treziac** [comment]
Had also this problem when working first with rdkafka but could update my packages, made a quick PR as it doesn't to introduce any issue
I assume it's not an uncommon case - in our company, introduce kafka in a legacy project before to move to new projects in .net core or other languages

@combrinckd : i would advise you to check that your production server run under net framework 4.5.2 (or 4.6+) and not 4.5, as it's not supported anymore by microsoft. You don't have to change your project at all, just the framework installed on the servers. There are very rare breaking change doing this upgrade that you can find here : https://msdn.microsoft.com/en-us/library/dn458358(v=vs.110).aspx
If possible update your projects, it's not that long ;)

**Comment by mhowlett** [comment]
ok - there seems to be sufficient demand for this, and @treziac worked out all the details and submitted a PR.. so it's in!

**Comment by treziac** [comment]
As a note, we may want to add a net45 and net451 reference and not just net45 and maybe even other moniker
(everything which is noted as obsolete in an upper .NET Framework version should target a new version. I don't think there will be any breaking changes in future but yet. There should be no obsolete warnings when targeting any framework)

Will do this later, no urge as long as it's only obsolete and not removed :)
