### ISSUE TITLE
[Question] Is it possible to set up SSL truststore to accept all certificates?

### ISSUE THREAD

**Issue by Never7Dice** [confluentinc/confluent-kafka-dotnet#963]
Is it possible to set up consumer's/producer's config to accept all SSL certificates?

 - [ 1.0.0 ] Confluent.Kafka nuget version.

**Comment by edenhill** [comment]
The upcoming release of librdkafka adds support for custom broker cert verification, which can be used to extend or override OpenSSL's builtin verification.
Now, why you would want to override those checks is questionable, but for what it is worth:
https://github.com/edenhill/librdkafka/pull/2309/files#diff-c59135f44ebf712a4c9fea7fae4538e6R1899

This will probably land in the dotnet client during Q3.

**Comment by Never7Dice** [comment]
Thank you for the answer, I bet upcoming releases would be nice.
