### ISSUE TITLE
Error 'dotnet build' on OSX

### ISSUE THREAD

**Issue by NineMvp** [confluentinc/confluent-kafka-dotnet#97]
My environment 

$ dotnet --version
_1.0.1_
$ dotnet
_Microsoft .NET Core Shared Framework Host
  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86_

Error:

$ dotnet build

Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/local/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Volumes/MacintoshHD2/git2/confluent-kafka-dotnet/src/Confluent.Kafka/Confluent.Kafka.csproj]

**Comment by treziac** [comment]
you need to build for netstandard only, as net451 is for windows only (so we fan use it in standard legacy project)
dotnet restore
dotnet build -f netstandard1.3 (for Confluent.Kafka)
