### ISSUE TITLE
Could you please add a Assembly Signature for your library in the next release version？

### ISSUE THREAD

**Issue by longbaochenlong** [confluentinc/confluent-kafka-dotnet#973]
Description
===========
My Dear Friend,Could you please add a Assembly Signature for your library in the next release version？Thanks!

Checklist
=========

Please provide the following information:
 - [ ] Confluent.Kafka 1.0.1.1.
 - [ ] Apache Kafka 1.0.1.
 - [ ] Windows10.
 - [ ] Assembly Signature.

**Comment by mhowlett** [comment]
yes, we do plan to do this soon.

**Comment by zhoubo56** [comment]
Our team want change projects into "Strong-naming Assemblies", got the same issue. As the reminder here, we can get the update release immediately.

**Comment by mhowlett** [comment]
we'll try to get to this this week and put out a 1.1.0.1.

**Comment by mhowlett** [comment]
this is more effort than I was initially thinking. here's a start: https://github.com/confluentinc/confluent-kafka-dotnet/pull/1000 ... there are issues. I think it's too big a scope for me to get done on the side without getting the ok from product. If you get this working (will also need a PR against our avro fork to make it signed), I can prioritize merging it. It seems like we really only need signed assemblies? (based on what other projects seem to do). seems the downsides to doing that are not material.

**Comment by mhowlett** [comment]
just doing a bit of research on this ... I now recall that [this blog post](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/) is responsible for us deciding to distribute a separate signed assembly. however, it seems that advice is no longer good: https://www.pedrolamas.com/2018/09/11/start-strong-naming-your-assemblies/

so, it seems we should move to signing all assemblies and get rid of the separate Confluent.Kafka.StrongName.

**Comment by anchitj** [comment]
Closing as it's fixed now.
