### ISSUE TITLE
No partition assigned when having 2 same instances

### ISSUE THREAD

**Issue by Rymix** [confluentinc/confluent-kafka-dotnet#975]
Hi,

Here again to ask for help.

Description
===========

When having 2 consumers with same GroupId one of the can subscribe to topics, but if you run another instance of the same program. You get no subscription on the 2nd instance :

2019-06-06 18:06:30,482 INFO  ServiceTrading - Assigned partitions: []

If i run the 2 instances at the same time, and i shutdown the one which successfully subscribe to topic, the other one will successfully subscribe to topics right after the shutdown.

I would like to have 2+ instances with same groupId reading kafka topic.

Is there anyway to fix this problem ?

Thank you for your help

 - [ ] Confluent.Kafka nuget version. 1.0.0
 - [ ] Operating system. W10

**Comment by mhowlett** [comment]
i'm guessing the topic you're reading from has only one partition. you need at least as many partitions as you have consumers.

**Comment by Rymix** [comment]
Oh, that's right, so i just need to increase the number of partition and it will be fine ?

Thank you for your quick help ! 💯
