### ISSUE TITLE
Issue while committing Offset: Local: Unknown partition 

### ISSUE THREAD

**Issue by RiteshKo** [confluentinc/confluent-kafka-dotnet#980]
Description
===========
While committing offset I am continuosly getting an error **Local: Unknown partition**

Code used in C# to commit manually:
 kafkaConsumer.StoreOffsets(new List<TopicPartitionOffset>
                {
                    new TopicPartitionOffset(new TopicPartition(kafkaTopic, kafkaPartition), new Offset(kafkaMessageOffset))
                });

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version: 0.11.6
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
the consumer must be assigned to the partitions you provide to `StoreOffsets`. you'd get this error if it's not.

**Comment by anchitj** [comment]
Closing. Feel free to reopen if still an issue.
