### ISSUE TITLE
OffsetsForTimes method on Consumer

### ISSUE THREAD

**Issue by jake0029** [confluentinc/confluent-kafka-dotnet#983]
Do we have sample code on how to use this event OffsetForTimes in .net with sample parameters ?

**Comment by mhowlett** [comment]
the best we've got right now are the integration tests: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/test/Confluent.Kafka.IntegrationTests/Tests/Consumer_OffsetsForTimes.cs
