### ISSUE TITLE
No way to pass the HttpClient a CA for schema registry

### ISSUE THREAD

**Issue by THEjoezack** [confluentinc/confluent-kafka-dotnet#986]
Description
===========

I'm not seeing a way to pass the CA for the schema registry. I found [the source code](https://github.com/confluentinc/confluent-kafka-dotnet/blob/026d320aef3959c83045b4daec6c1f2cf4719f81/src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs) that creates the HttpClient and it watches for "https" but it doesn't have a way to plumb the certificate through.

Unless I'm missing something, this means I either have to install self-signed certificates or turn verification off. I would rather not do either, and I think it would be a nice option to be consistent with the Kafka client anyway

How to reproduce
================

Use a self-signed certificate for the schema-registry, then it would be nice to have an additional config property like...
```C#
var schemaRegistryConfig = new SchemaRegistryConfig
{
  SchemaRegistryUrl = "https://localhost:8085",
  SslCaLocation = @"C:\self-signed-ca.crt" // this doesn't exist
};

using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
{
  schema = schemaRegistry.GetLatestSchemaAsync("").Result;
}
```

Checklist
=========

Please provide the following information:
- Confluent.Kafka 1.0
- Apache Kafka 5.2.1

**Comment by mhowlett** [comment]
thanks for the +1 - yep, this is on the todo list, particularly as SR is now in ccloud.

**Comment by p21x** [comment]
`CachedSchemaRegistryClient` still does not work with self-signed CA certificates.
It throws `AuthenticationException`: "The remote certificate is invalid according to the validation procedure." unless the certificate is installed into Trusted Root Certification Authorities, or `EnableSslCertificateVerification` parameter is set to `false`.

 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file:
```csharp
var schemaRegistryConfig = new SchemaRegistryConfig()
{
    Url = "https://localhost:8081",
    SslCaLocation = @"C:\path-to-self-signed-crt\kafka-ca-1.crt",
    SslKeystoreLocation = @"C:\path-to-keystore\kafka.keystore.p12",
    SslKeystorePassword = "123456"
};
var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig);

var x = schemaRegistry.GetLatestSchemaAsync("topic-name").Result;
```
 - [x] Confluent.Kafka nuget version: 1.6.2
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system: Windows 10 Pro 20H2
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.
