### ISSUE TITLE
Consumer does not recover from network outage

### ISSUE THREAD

**Issue by kmcclellan** [confluentinc/confluent-kafka-dotnet#990]
Description
===========
Following a temporary network outage, consumer commits will continue to fail until the assignment is manually revoked. This only happens _sometimes_ (~50% of disconnections). 

How to reproduce
================
Run the following code connected to a remote Kafka broker. In between calls to `Consume()` and `Commit()`, simulate a temporary network outage (e.g. disable/enable adapter).

```c#
var config = new ConsumerConfig
{
    BootstrapServers = "<remote-broker>:9092",
    GroupId = "my-group",
    EnableAutoCommit = false
};

using var consumer = new ConsumerBuilder<Ignore, byte[]>(config).Build();
consumer.Subscribe("my-topic");

var consumeResult = consumer.Consume();

// BREAKPOINT: Simulate network outage - disable and reenable network
Thread.Sleep(1000);

// Clearing out my assignment prevents the Exception!
// consumer.Unassign();

consumer.Commit(consumeResult);
Console.WriteLine("Committed successfully!");

consumer.Close();
```

**Expected**: I should be able to commit successfully.
**Actual**: Exception is thrown.
```
Confluent.Kafka.KafkaException: Broker: Unknown member
   at Confluent.Kafka.Impl.SafeKafkaHandle.Commit(IEnumerable`1 offsets) in C:\Users\kmcclellan\repos\confluent-kafka-dotnet\src\Confluent.Kafka\Impl\SafeKafkaHandle.cs:line 742
   at Confluent.Kafka.Consumer`2.Commit(IEnumerable`1 offsets) in C:\Users\kmcclellan\repos\confluent-kafka-dotnet\src\Confluent.Kafka\Consumer.cs:line 350
   at Confluent.Kafka.Consumer`2.Commit(ConsumeResult`2 result) in C:\Users\kmcclellan\repos\confluent-kafka-dotnet\src\Confluent.Kafka\Consumer.cs:line 363
   at ResiliencyTest.Program.Main() in C:\Users\kmcclellan\repos\confluent-kafka-dotnet\ResiliencyTest\Program.cs:line 31
```

Confluent.Kafka 1.0.1.1 - Windows 10

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [X] Client configuration.
 - [X] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by DanVicarel** [comment]
Looks good.  It might be better to use `HashSet<TopicPartitionOffset>` for the private collection, since all you really need is fast insertion and enumeration, and then you wouldn't need the `Select` statement in the `Commit` method.

**Comment by mhowlett** [comment]
the consumer must be a member of the group in order to commit offsets. I believe what is happening is when you disable the network, the consumer heartbeats are no longer making it through to the group controller. this causes the consumer to be kicked out of the consumer group. When you try to commit offsets after the network is re-enabled, some other consumer is now responsible for the partitions this consumer formerly was, so the commit is blocked.

**Comment by DanVicarel** [comment]
@mhowlett Thanks for the explanation. So what is the recommended workaround for committing from a consumer that has been kicked out of its consumer group? Is @kmcclellan's `Unassign` call, in a try/catch, the only option?

My team ran into this exception in a slightly different way: our app backs off exponentially while experiencing issues in some other business-logic code (15s, 30s, 1min, 2min, etc.), so the accumulated backoff can be longer than the `session.timeout.ms` configured on the brokers, causing the consumer to be kicked out of the group. This means that, when the errors in the business-logic code subside and the app is again able to commit, the commit fails with `Broker: Unknown member`. For this particular case, I assume turning up the consumer's `MaxPollIntervalMs` to the max backoff would be sufficient, but I'm still wondering about the case of network outages.

**Comment by czd890** [comment]
+1

**Comment by mhowlett** [comment]
not quite following what you mean 'backoff'?

the consumer sends heartbeats in a background thread, independent of calls to consume (so whether session.timeout.ms is hit is independent of anything you do). as an application developer, you only need to concern yourself with `MaxPollIntervalMs` - make sure your application calls `Consume` within that interval.

**Comment by milindl** [comment]
Closing this as Matt answered the original question, and there's been no follow up for a while.
