### ISSUE TITLE
Creating custom value deserializer 

### ISSUE THREAD

**Issue by Roll4D6** [confluentinc/confluent-kafka-dotnet#992]
Description
===========
The messages i'm reading from the kafak are Json's and i want to read them directly to a Newtonsoft,Jobject. In order to do that i wanted to create my own Deserializer that will implement IDeserializer but when i try to implement the interface i get a compile time error that say: "ReadOnlySpan' is obsolete: 'Types with embedded references are not supported in this version of your compiler.'"

How to reproduce
================
Create a new type that implements IDeserializer
```
        public string Deserialize(ReadOnlySpan<byte> data, bool isNull, SerializationContext context)
        {
            // here goes my deserialation
        }
```

Confluent.Kafka version 1.0.0
Runs on window 10
Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [X] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
A quick web search for that error suggests this is a .net bug. try moving to a newer version of .net.

**Comment by Roll4D6** [comment]
> A quick web search for that error suggests this is a .net bug. try moving to a newer version of .net.

You're right. sorry to bother you.
