### ISSUE TITLE
CachedSchemaRegistry getting 404 response codes

### ISSUE THREAD

**Issue by jonathansant** [confluentinc/confluent-kafka-dotnet#993]
Description
===========

I was playing around with the following example: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AvroSpecific/Program.cs using our schema registry.

I started getting a 404 from the schema registry.

How to reproduce
================

- Set `SchemaRegistryUrl` to `https://xxx.dev/schema-registry`
- Run the program
- Examine the requests using Fiddler:
-- Expected: https://xxx.dev/schema-registry/subjects/sucrose-external-value/versions
-- Actual: https://xxx.dev/subjects/sucrose-external-value/versions

![screenshot](https://user-images.githubusercontent.com/6423827/60269534-ea2d8180-98ee-11e9-8f7e-b32d47d1f0a8.png)

I tracked down the issue and it seems that there's some weird functionality when using `HttpClient`. Basically when adding prepending the `/` here: https://github.com/confluentinc/confluent-kafka-dotnet/blob/98edaaf8a746d1a38e85418933da34c2e3a220c2/src/Confluent.SchemaRegistry/Rest/RestService.cs#L234

causes `HttpClient` to discard part of the url.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by jonathansant** [comment]
Any news on this, please?

**Comment by mhowlett** [comment]
thanks for the PR! closing this issue in favor of that.
