### ISSUE TITLE
Reinstatement of Revoke+Assign events in v1?

### ISSUE THREAD

**Issue by bartelink** [confluentinc/confluent-kafka-dotnet#994]
I'm targeting 1.0.1 but have scenarios where I'm trying to self-monitor progress using algorithms from [Burrow](https://github.com/linkedin/Burrow). As part of this, I need to react to rebalancing of partition assignments involving the Consumer under observation; ideally I'd not have to infer that by caching and looking for deltas in assignments.

In the 0.x API, assignment/revocation events were exposed on the consumer, whereas when flipping (I have a shim that provides a v0/v1 interop) between v0 and v1, it seems like I'll need to wrap and expose such events myself (by wiring in callbacks to a buddy class when Building the Consumer).

Thus the question: Do you envisage ever reinstating a facility where the v1 APIs expose such notification events, or is the freezing of subscriptions/config after the initial Build of the Consumer a Final Decision?

**Comment by mhowlett** [comment]
there's no plan to re-instate notification of consumer group rebalance events via the c# event language feature - specifying these in the builder class is the only way going forward.

**Comment by bartelink** [comment]
Thanks for the clarity; closing - I agree this makes sense for the lib. I went all the way down the road of shimming them as events, but asking this question helped me find a more sensible answer (inferring based on `Assignment`) so I've since removed that (WIP PR https://github.com/jet/Jet.ConfluentKafka.FSharp/pull/41)
